In [37]:
from database.dependencies import DB_DEPENDENCY
from sqlalchemy.orm import Query
from sqlalchemy import text


def query_sql(query:str):
    from database.session import SessionLocal
    # To list tables in PostgreSQL, use the information_schema.tables view:
    with SessionLocal() as db:
        result = db.execute(text(query))
        # UPDATE/INSERT/DELETE don't return rows - use rowcount instead
        if result.returns_rows:
            return result.fetchall()
        db.commit()
        return result.rowcount

2026-05-12 17:37:58.687 | INFO     | database.session:<module>:50 - Database connected successfully

In [39]:
import pandas as pd


df = pd.read_csv("/Users/apple/Downloads/test_dispo.csv")

In [21]:
url = "http://localhost:8000/disposition"

In [46]:
json.loads(df['transcript'][0])

'[{"role": "assistant", "content": "हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं ज्ञानती देवी जी से बात कर रही हूँ?"}, {"role": "user", "content": "हां. Hello."}, {"role": "assistant", "content": "जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। आपके लोन की ईएमआई जो तीन हजार तीन सौ साठ रुपये है वो अब दो सौ तीन दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि अब चार हजार नौ सौ पचास हो चुकी है।?"}, {"role": "assistant", "content": "जी, मेर"}, {"role": "user", "content": "कर ली. ठीक है सब भुगतान सब कार्य रख लीजिए."}, {"role": "assistant", "content": "यदि आपने पहले ही भुगतान किया है, तो कृपया बता सकते ह"}, {"role": "user", "content": "हां. हां. सब भुगतान नाम कर ले सब हमें जहां जहां पर ले लिए सब हम पता करके बैठा लिए. फिर से बात कर रहे हैं. ठीक."}, {"role": "assistant", "content": "मैंने आपके बताए अनुसार भुगतान विवरण नोट कर ली हैं। अगर रसीद उपलब्ध हो तो कृपया अपनी नज़दीकी स्पंदना स्फूर्ति ब्रांच में दिखा दीजिए ताकि रिकॉर्ड जल्दी अपडेट हो सके। \\n\\nक्या मैं आपकी और किसी चीज़ में मदद कर सकती हूँ?"}]'

In [ ]:
df[''][0]

KeyError: 'call_diarization'

In [41]:
df.shape[0]

300

In [35]:
df["call_diarization"][0]

{'results': {'channels': [{'alternatives': [{'words': [{'end': 1.62,
        'word': 'hello',
        'start': 1.12,
        'speaker': 0,
        'confidence': 0.76049805,
        'punctuated_word': 'Hello,',
        'speaker_confidence': 0.50583696},
       {'end': 1.92,
        'word': 'main',
        'start': 1.68,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'main',
        'speaker_confidence': 0.50583696},
       {'end': 2.24,
        'word': 'aayasha',
        'start': 1.92,
        'speaker': 0,
        'confidence': 0.96875,
        'punctuated_word': 'aayasha',
        'speaker_confidence': 0.50583696},
       {'end': 2.48,
        'word': 'bol',
        'start': 2.24,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'bol',
        'speaker_confidence': 0.50583696},
       {'end': 2.88,
        'word': 'rahi',
        'start': 2.48,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'rahi',
        'speaker_confidence': 0.50583696},
       {'end': 3.28,
        'word': 'hoon',
        'start': 2.88,
        'speaker': 0,
        'confidence': 0.9880371,
        'punctuated_word': 'hoon.',
        'speaker_confidence': 0.50583696},
       {'end': 3.6,
        'word': 'kya',
        'start': 3.28,
        'speaker': 0,
        'confidence': 0.9941406,
        'punctuated_word': 'Kya',
        'speaker_confidence': 0.50583696},
       {'end': 3.76,
        'word': 'main',
        'start': 3.6,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'main',
        'speaker_confidence': 0.50583696},
       {'end': 4.0,
        'word': 'anjoo',
        'start': 3.76,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'anjoo',
        'speaker_confidence': 0.6619937},
       {'end': 4.16,
        'word': 'sinh',
        'start': 4.0,
        'speaker': 0,
        'confidence': 0.6743164,
        'punctuated_word': 'sinh',
        'speaker_confidence': 0.6619937},
       {'end': 4.4,
        'word': 'ji',
        'start': 4.16,
        'speaker': 0,
        'confidence': 0.82958984,
        'punctuated_word': 'ji',
        'speaker_confidence': 0.6619937},
       {'end': 4.56,
        'word': 'se',
        'start': 4.4,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'se',
        'speaker_confidence': 0.6619937},
       {'end': 4.72,
        'word': 'baat',
        'start': 4.56,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'baat',
        'speaker_confidence': 0.6619937},
       {'end': 4.88,
        'word': 'kar',
        'start': 4.72,
        'speaker': 0,
        'confidence': 0.99609375,
        'punctuated_word': 'kar',
        'speaker_confidence': 0.6619937},
       {'end': 5.04,
        'word': 'rahi',
        'start': 4.88,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'rahi',
        'speaker_confidence': 0.6619937},
       {'end': 5.54,
        'word': 'hoon',
        'start': 5.04,
        'speaker': 0,
        'confidence': 0.9995117,
        'punctuated_word': 'hoon?',
        'speaker_confidence': 0.6619937},
       {'end': 6.42,
        'word': 'ji',
        'start': 5.92,
        'speaker': 0,
        'confidence': 0.9223633,
        'punctuated_word': 'Ji.',
        'speaker_confidence': 0.26350147},
       {'end': 9.46,
        'word': 'hello',
        'start': 8.96,
        'speaker': 0,
        'confidence': 0.81591797,
        'punctuated_word': 'Hello.',
        'speaker_confidence': 0.20774758},
       {'end': 11.679999,
        'word': 'main',
        'start': 11.36,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'Main',
        'speaker_confidence': 0.681956},
       {'end': 12.0,
        'word': 'aayasha',
        'start': 11.679999,
        'speaker': 0,
        'confidence': 0.9951172,
        'punctuated_word': 'aayasha',
        'speaker_confidence': 0.681956},
       {'end': 12.16,
        'word': 'bol',
        'start': 12.0,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'bol',
        'speaker_confidence': 0.681956},
       {'end': 12.32,
        'word': 'rahi',
        'start': 12.16,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'rahi',
        'speaker_confidence': 0.681956},
       {'end': 12.48,
        'word': 'hoon',
        'start': 12.32,
        'speaker': 0,
        'confidence': 0.9707031,
        'punctuated_word': 'hoon.',
        'speaker_confidence': 0.681956},
       {'end': 12.719999,
        'word': 'kya',
        'start': 12.48,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'Kya',
        'speaker_confidence': 0.681956},
       {'end': 12.88,
        'word': 'main',
        'start': 12.719999,
        'speaker': 0,
        'confidence': 0.9941406,
        'punctuated_word': 'main',
        'speaker_confidence': 0.681956},
       {'end': 13.12,
        'word': 'anjoo',
        'start': 12.88,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'anjoo',
        'speaker_confidence': 0.681956},
       {'end': 13.28,
        'word': 'sinh',
        'start': 13.12,
        'speaker': 0,
        'confidence': 0.97265625,
        'punctuated_word': 'sinh',
        'speaker_confidence': 0.681956},
       {'end': 13.5199995,
        'word': 'ji',
        'start': 13.28,
        'speaker': 0,
        'confidence': 0.98535156,
        'punctuated_word': 'ji',
        'speaker_confidence': 0.681956},
       {'end': 13.679999,
        'word': 'se',
        'start': 13.5199995,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'se',
        'speaker_confidence': 0.681956},
       {'end': 13.84,
        'word': 'baat',
        'start': 13.679999,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'baat',
        'speaker_confidence': 0.681956},
       {'end': 14.0,
        'word': 'kar',
        'start': 13.84,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'kar',
        'speaker_confidence': 0.681956},
       {'end': 14.16,
        'word': 'rahi',
        'start': 14.0,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'rahi',
        'speaker_confidence': 0.681956},
       {'end': 14.535,
        'word': 'hoon',
        'start': 14.16,
        'speaker': 0,
        'confidence': 0.99853516,
        'punctuated_word': 'hoon?',
        'speaker_confidence': 0.681956},
       {'end': 15.495,
        'word': 'ji',
        'start': 15.095,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'Ji',
        'speaker_confidence': 0.26789033},
       {'end': 15.995,
        'word': 'bolie',
        'start': 15.495,
        'speaker': 0,
        'confidence': 0.907959,
        'punctuated_word': 'bolie.',
        'speaker_confidence': 0.26789033},
       {'end': 17.675,
        'word': 'dekhie',
        'start': 17.175,
        'speaker': 0,
        'confidence': 0.87060547,
        'punctuated_word': 'Dekhie',
        'speaker_confidence': 0.73073417},
       {'end': 18.135,
        'word': 'aapki',
        'start': 17.735,
        'speaker': 0,
        'confidence': 0.89746094,
        'punctuated_word': 'aapki',
        'speaker_confidence': 0.73073417},
       {'end': 18.535,
        'word': 'pandrah',
        'start': 18.135,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'pandrah',
        'speaker_confidence': 0.73073417},
       {'end': 18.695,
        'word': 'sau',
        'start': 18.535,
        'speaker': 0,
        'confidence': 0.81591797,
        'punctuated_word': 'sau',
        'speaker_confidence': 0.73073417},
       {'end': 19.015,
        'word': 'rupe',
        'start': 18.695,
        'speaker': 0,
        'confidence': 0.76416016,
        'punctuated_word': 'rupe',
        'speaker_confidence': 0.73073417},
       {'end': 19.335,
        'word': 'ki',
        'start': 19.015,
        'speaker': 0,
        'confidence': 0.98828125,
        'punctuated_word': 'ki',
        'speaker_confidence': 0.73073417},
       {'end': 19.654999,
        'word': 'emi',
        'start': 19.335,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'EMI',
        'speaker_confidence': 0.73073417},
       {'end': 19.975,
        'word': 'tin',
        'start': 19.654999,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'tin',
        'speaker_confidence': 0.73073417},
       {'end': 20.215,
        'word': 'hazaar',
        'start': 19.975,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'hazaar',
        'speaker_confidence': 0.73073417},
       {'end': 20.375,
        'word': 'chaar',
        'start': 20.215,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'chaar',
        'speaker_confidence': 0.73073417},
       {'end': 20.535,
        'word': 'sau',
        'start': 20.375,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'sau',
        'speaker_confidence': 0.73073417},
       {'end': 20.855,
        'word': 'sattar',
        'start': 20.535,
        'speaker': 0,
        'confidence': 0.9941406,
        'punctuated_word': 'sattar',
        'speaker_confidence': 0.73073417},
       {'end': 21.175,
        'word': 'rupe',
        'start': 20.855,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'rupe',
        'speaker_confidence': 0.73073417},
       {'end': 21.414999,
        'word': 'tin',
        'start': 21.175,
        'speaker': 0,
        'confidence': 0.99121094,
        'punctuated_word': 'tin',
        'speaker_confidence': 0.73073417},
       {'end': 21.575,
        'word': 'sau',
        'start': 21.414999,
        'speaker': 0,
        'confidence': 0.99121094,
        'punctuated_word': 'sau',
        'speaker_confidence': 0.73073417},
       {'end': 21.814999,
        'word': 'tin',
        'start': 21.575,
        'speaker': 0,
        'confidence': 0.99316406,
        'punctuated_word': 'tin',
        'speaker_confidence': 0.73073417},
       {'end': 21.975,
        'word': 'din',
        'start': 21.814999,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'din',
        'speaker_confidence': 0.73073417},
       {'end': 22.135,
        'word': 'se',
        'start': 21.975,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'se',
        'speaker_confidence': 0.73073417},
       {'end': 22.375,
        'word': 'baaki',
        'start': 22.135,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'baaki',
        'speaker_confidence': 0.73073417},
       {'end': 22.535,
        'word': 'hai',
        'start': 22.375,
        'speaker': 0,
        'confidence': 0.89453125,
        'punctuated_word': 'hai',
        'speaker_confidence': 0.73073417},
       {'end': 22.615,
        'word': 'aur',
        'start': 22.535,
        'speaker': 0,
        'confidence': 0.9111328,
        'punctuated_word': 'aur',
        'speaker_confidence': 0.73073417},
       {'end': 22.775,
        'word': 'kul',
        'start': 22.615,
        'speaker': 0,
        'confidence': 0.9941406,
        'punctuated_word': 'kul',
        'speaker_confidence': 0.73073417},
       {'end': 23.095,
        'word': 'bakaaya',
        'start': 22.775,
        'speaker': 0,
        'confidence': 0.9819336,
        'punctuated_word': 'bakaaya',
        'speaker_confidence': 0.73073417},
       {'end': 23.415,
        'word': 'ikkis',
        'start': 23.095,
        'speaker': 0,
        'confidence': 0.6303711,
        'punctuated_word': 'ikkis',
        'speaker_confidence': 0.73073417},
       {'end': 23.735,
        'word': 'hazaar',
        'start': 23.415,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'hazaar',
        'speaker_confidence': 0.73073417},
       {'end': 23.895,
        'word': 'saat',
        'start': 23.735,
        'speaker': 0,
        'confidence': 0.99609375,
        'punctuated_word': 'saat',
        'speaker_confidence': 0.73073417},
       {'end': 24.055,
        'word': 'sau',
        'start': 23.895,
        'speaker': 0,
        'confidence': 0.9951172,
        'punctuated_word': 'sau',
        'speaker_confidence': 0.73073417},
       {'end': 24.295,
        'word': 'tis',
        'start': 24.055,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'tis',
        'speaker_confidence': 0.73073417},
       {'end': 24.615,
        'word': 'rupe',
        'start': 24.295,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'rupe',
        'speaker_confidence': 0.73073417},
       {'end': 24.855,
        'word': 'ho',
        'start': 24.615,
        'speaker': 0,
        'confidence': 0.9970703,
        'punctuated_word': 'ho',
        'speaker_confidence': 0.73073417},
       {'end': 25.095,
        'word': 'gaya',
        'start': 24.855,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'gaya',
        'speaker_confidence': 0.73073417},
       {'end': 25.415,
        'word': 'hai',
        'start': 25.095,
        'speaker': 0,
        'confidence': 0.8562012,
        'punctuated_word': 'hai.',
        'speaker_confidence': 0.73073417},
       {'end': 25.575,
        'word': 'aap',
        'start': 25.415,
        'speaker': 0,
        'confidence': 0.9951172,
        'punctuated_word': 'Aap',
        'speaker_confidence': 0.73073417},
       {'end': 25.735,
        'word': 'kab',
        'start': 25.575,
        'speaker': 0,
        'confidence': 0.9394531,
        'punctuated_word': 'kab',
        'speaker_confidence': 0.73073417},
       {'end': 25.974998,
        'word': 'tak',
        'start': 25.735,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'tak',
        'speaker_confidence': 0.73073417},
       {'end': 26.294998,
        'word': 'jama',
        'start': 25.974998,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'jama',
        'speaker_confidence': 0.73073417},
       {'end': 26.794998,
        'word': 'karvaenge',
        'start': 26.294998,
        'speaker': 0,
        'confidence': 0.93969727,
        'punctuated_word': 'karvaenge?',
        'speaker_confidence': 0.73073417},
       {'end': 28.6,
        'word': 'ab',
        'start': 28.44,
        'speaker': 0,
        'confidence': 0.66552734,
        'punctuated_word': 'Ab',
        'speaker_confidence': 0.6035819},
       {'end': 29.1,
        'word': 'dekhie',
        'start': 28.6,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'dekhie',
        'speaker_confidence': 0.6035819},
       {'end': 31.18,
        'word': 'das',
        'start': 30.68,
        'speaker': 0,
        'confidence': 0.77246094,
        'punctuated_word': 'das',
        'speaker_confidence': 0.6035819},
       {'end': 32.2,
        'word': 'das',
        'start': 32.04,
        'speaker': 0,
        'confidence': 0.7602539,
        'punctuated_word': 'das',
        'speaker_confidence': 0.6035819},
       {'end': 32.52,
        'word': 'taarikh',
        'start': 32.2,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'taarikh',
        'speaker_confidence': 0.6035819},
       {'end': 32.76,
        'word': 'tak',
        'start': 32.52,
        'speaker': 0,
        'confidence': 0.9941406,
        'punctuated_word': 'tak',
        'speaker_confidence': 0.6035819},
       {'end': 33.0,
        'word': 'mein',
        'start': 32.76,
        'speaker': 0,
        'confidence': 0.83251953,
        'punctuated_word': 'mein',
        'speaker_confidence': 0.6035819},
       {'end': 33.32,
        'word': 'karte',
        'start': 33.0,
        'speaker': 0,
        'confidence': 0.96435547,
        'punctuated_word': 'karte',
        'speaker_confidence': 0.6035819},
       {'end': 33.82,
        'word': 'hain',
        'start': 33.32,
        'speaker': 0,
        'confidence': 0.9770508,
        'punctuated_word': 'hain.',
        'speaker_confidence': 0.6035819},
       {'end': 39.08,
        'word': 'achchha',
        'start': 38.76,
        'speaker': 0,
        'confidence': 0.5620117,
        'punctuated_word': 'Achchha',
        'speaker_confidence': 0.65651995},
       {'end': 39.32,
        'word': 'ikkis',
        'start': 39.08,
        'speaker': 0,
        'confidence': 0.28173828,
        'punctuated_word': 'ikkis',
        'speaker_confidence': 0.65651995},
       {'end': 39.559998,
        'word': 'taarikh',
        'start': 39.32,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'taarikh',
        'speaker_confidence': 0.65651995},
       {'end': 39.72,
        'word': 'ko',
        'start': 39.559998,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'ko',
        'speaker_confidence': 0.65651995},
       {'end': 39.96,
        'word': 'bhar',
        'start': 39.72,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'bhar',
        'speaker_confidence': 0.65651995},
       {'end': 40.2,
        'word': 'sakte',
        'start': 39.96,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'sakte',
        'speaker_confidence': 0.65651995},
       {'end': 40.598938,
        'word': 'hain',
        'start': 40.2,
        'speaker': 0,
        'confidence': 0.8859863,
        'punctuated_word': 'hain.',
        'speaker_confidence': 0.65651995},
       {'end': 41.63894,
        'word': 'thik',
        'start': 41.398937,
        'speaker': 0,
        'confidence': 0.9980469,
        'punctuated_word': 'Thik',
        'speaker_confidence': 0.4294061},
       {'end': 42.11894,
        'word': 'hai',
        'start': 41.63894,
        'speaker': 0,
        'confidence': 0.99902344,
        'punctuated_word': 'hai.',
        'speaker_confidence': 0.4294061},
       {'end': 42.61894,
        'word': 'aapka',
        'start': 42.11894,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'Aapka',
        'speaker_confidence': 0.4294061},
       {'end': 44.11894,
        'word': 'din',
        'start': 43.95894,
        'speaker': 0,
        'confidence': 1.0,
        'punctuated_word': 'din',
        'speaker_confidence': 0.4294061},
       {'end': 44.358936,
        'word': 'shubh',
        'start': 44.11894,
        'speaker': 0,
        'confidence': 0.9951172,
        'punctuated_word': 'shubh',
        'speaker_confidence': 0.4294061},
       {'end': 44.838936,
        'word': 'ho',
        'start': 44.358936,
        'speaker': 0,
        'confidence': 0.7597656,
        'punctuated_word': 'ho,',
        'speaker_confidence': 0.4294061},
       {'end': 45.338936,
        'word': 'dhanyavaad',
        'start': 44.838936,
        'speaker': 0,
        'confidence': 0.9946289,
        'punctuated_word': 'dhanyavaad.',
        'speaker_confidence': 0.4294061}],
      'confidence': 0.99609375,
      'paragraphs': {'paragraphs': [{'end': 12.48,
         'start': 1.12,
         'speaker': 0,
         'num_words': 23,
         'sentences': [{'end': 3.28,
           'text': 'Hello, main aayasha bol rahi hoon.',
           'start': 1.12},
          {'end': 5.54,
           'text': 'Kya main anjoo sinh ji se baat kar rahi hoon?',
           'start': 3.28},
          {'end': 6.42, 'text': 'Ji.', 'start': 5.92},
          {'end': 9.46, 'text': 'Hello.', 'start': 8.96},
          {'end': 12.48,
           'text': 'Main aayasha bol rahi hoon.',
           'start': 11.36}]},

In [51]:
json.loads(df['transcript'][0])

[{'role': 'assistant',
  'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं ज्ञानती देवी जी से बात कर रही हूँ?'},
 {'role': 'user', 'content': 'हां. Hello.'},
 {'role': 'assistant',
  'content': 'जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। आपके लोन की ईएमआई जो तीन हजार तीन सौ साठ रुपये है वो अब दो सौ तीन दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि अब चार हजार नौ सौ पचास हो चुकी है।?'},
 {'role': 'assistant', 'content': 'जी, मेर'},
 {'role': 'user', 'content': 'कर ली. ठीक है सब भुगतान सब कार्य रख लीजिए.'},
 {'role': 'assistant',
  'content': 'यदि आपने पहले ही भुगतान किया है, तो कृपया बता सकते ह'},
 {'role': 'user',
  'content': 'हां. हां. सब भुगतान नाम कर ले सब हमें जहां जहां पर ले लिए सब हम पता करके बैठा लिए. फिर से बात कर रहे हैं. ठीक.'},
 {'role': 'assistant',
  'content': 'मैंने आपके बताए अनुसार भुगतान विवरण नोट कर ली हैं। अगर रसीद उपलब्ध हो तो कृपया अपनी नज़दीकी स्पंदना स्फूर्ति ब्रांच में दिखा दीजिए ताकि रिकॉर्ड जल्दी अपडेट हो सके। \n\nक्या मैं आपकी और किसी चीज़ में मदद कर सकती हूँ?'}]

In [54]:
res = requests.post(url, json = json.loads(df['transcript'][0]))

In [74]:
import ast
import aiohttp
import asyncio
import json
import requests
for idx in range(df.shape[0]):

    result = requests.post(url, json = json.loads(df['transcript'][idx]))
    df.loc[idx,'new_disposition'] = result.json()['Disposition_code']
    # df.loc[idx,'confidence'] = result.get('confidence')
    # df.loc[idx,'explanation'] = result.get('explanation')
    # df.loc[idx,'summary'] = result.get('summary')
    # df.loc[idx,'key_points'] = result.get('key_points')
    print(idx, " done")

KeyboardInterrupt:

In [ ]:
res.json()['']

{'Disposition_code': 'CONTACT ESTABLISHED NO OUTCOME',
 'confidence': 0.9,
 'explanation': 'No customer reply or outcome observed; conversation only by agent.',
 'summary': 'summary of the transcript',
 'key_points': ['Agent speaks throughout, no customer response',
  'No evidence of voicemail, wrong number, language barrier, or payment']}

In [28]:
df['call_diarization'][0]['results']['channels'][0]['alternatives'][0]['words']

TypeError: string indices must be integers, not 'str'

In [47]:
import json
df['transcript'] = df['transcript'].apply(lambda x: json.loads(x))

In [3]:
df.head()

,current_disposition,updated_disposition,call_diarization
0,ANSWERED DISCONNECTED,PTP ON SPECIFIC DATE,"{""results"": {""channels"": [{""alternatives"": [{""..."
1,UNABLE TO PAY OTHER,GREVIENCE (PAYMENT DONE NOT UPDATED),"{""results"": {""channels"": [{""alternatives"": [{""..."
2,ALREADY PAID,ALREADY PAID,"{""results"": {""channels"": [{""alternatives"": [{""..."
3,ANSWERED DISCONNECTED,PTP ON SPECIFIC DATE,"{""results"": {""channels"": [{""alternatives"": [{""..."
4,ANSWERED BY FAMILY MEMBER,ANSWERED DISCONNECTED,"{""results"": {""channels"": [{""alternatives"": [{""..."

In [2]:
import pandas as pd
df = pd.read_csv("filter_data.csv")

In [3]:
df = df[['Phone Numeber','BorrowerCode','BorrowerName','lower_name','count']]

In [4]:
df['lower_name'] = df.apply(lambda x: x['BorrowerName'].lower() if x['BorrowerName'] is not None else None, axis=1)

In [5]:
df

       Phone Numeber  BorrowerCode      BorrowerName        lower_name  count
0         7737451883    SSF4002279       SHARDA DEVI       sharda devi      1
1         6263481515    SSF4009264          DEVAKALI          devakali      1
2         7232852188    SSF3984941      GAGALI MEENA      gagali meena      1
3         7681805283    SSF3988540     NILANDRI HATI     nilandri hati      1
4         9460050437    SSF4006327         MAYA DEVI         maya devi      1
...              ...           ...               ...               ...    ...
30260     8948078274    SSF3214290        MRS MAYA          mrs maya        1
30261     7275268499    SSF4599136        RANJU DEVI        ranju devi      1
30262     7489248378  CID207300772              SITA              sita      1
30263     9201362865  CID219406458  JASHOVANTI SIDAR  jashovanti sidar      1
30264     9201065435    SSF5183182       DULARIN BAI       dularin bai      1

[30265 rows x 5 columns]

In [6]:
df[df['count'] > 1]

       Phone Numeber     BorrowerCode   BorrowerName     lower_name  count
130       9649887823       SSF3552604          MENKA          menka      2
200       6376537802       SSF3567142  SAVITA DINDOR  savita dindor      2
619       9330453172       SSF4308734  ZAHIRA KHATUN  zahira khatun      2
1761      9983562314       SSF3903855      RAJU DEVI      raju devi      3
3987      8084725143       SSF3379591     RAJNI DEVI     rajni devi      3
...              ...              ...            ...            ...    ...
27227     9785469436  SID951374805440     GEETA DEVI     geeta devi      2
27423     9983562314       SSF2579848       KAILASHI       kailashi      3
28711     9602634054       SSF2281344       SUA DEVI       sua devi      2
29078     9828231496       SSF2579947    MOHANI DEVI    mohani devi      3
29942     9060466287  SID951375523888     MUNNI DEVI     munni devi      2

[110 rows x 5 columns]

In [7]:
db_data = query_sql("select * from public.spandana_sphoorty_data")

In [8]:
db_data = pd.DataFrame(db_data)

In [9]:
for index, row in db_data.iterrows():
    try:
        if index < 10:
            print(row['contact_to'][-10:])
        db_data.loc[index,'phone'] = int(row['contact_to'][-10:])
    except:
        db_data.loc[index,'phone'] = None

9137500629
9137500629
7277184813
7277184813
7277184813
7277184813
7277184813
7277184813
7277184813
7277184813

In [10]:
db_data

,s_no,json_data,disposition,created_at,language,is_disposition_available,transcript,is_transcript_available,contact_to,contact_from,...,recording,model,cost,is_duplicate,campaign_id,session_id,call_status,error_message,uid,phone
0,96026,"{'ts': 1768910280.2389543, 'voip': {'to': '+91...",NaN,2026-01-20 11:59:51.464692+00:00,hi,False,NaN,False,+919137500629,+918047093431,...,NaN,gpt-4o-mini,NaN,False,176.0,-OjQGCHQs_i1v0OfrVU4,failed,No response from telephony provider,SSF3893617,9.137501e+09
1,107136,"{'ts': 1768999179.775556, 'chat': [{'role': 'a...","{""Disposition_code"": ""ANSWERED - NO OUTCOMES""}",2026-01-21 12:39:52.319091+00:00,hi,False,NaN,True,+919137500629,+918045888912,...,https://millis-ai-recordings.s3.us-west-1.amaz...,gpt-4o-mini,2.181145,False,180.0,-OjVZH-0vKgkoqgoqXtf,user-ended,NaN,SSF3893617,9.137501e+09
2,51371,"{'ts': 1768387233.355765, 'voip': {'to': '+917...",NaN,2026-01-14 10:42:25.809097+00:00,hi,False,NaN,False,+917277184813,+918047095601,...,NaN,gpt-4o-mini,NaN,False,163.0,-Oiw4wHnbp4Saoq9GKqY,failed,No response from telephony provider,SID951375719431,7.277185e+09
3,40734,"{'ts': 1768214594.14525, 'voip': {'to': '+9172...",NaN,2026-01-12 10:45:15.356534+00:00,hi,False,NaN,False,+917277184813,+918047095601,...,NaN,gpt-4o-mini,NaN,False,147.0,-OilnN2LwqxDGBIhl5Nd,failed,No response from telephony provider,SID951375719431,7.277185e+09
4,111401,"{'ts': 1769062655.3882964, 'voip': {'to': '+91...",NaN,2026-01-22 06:20:03.938562+00:00,hi,False,NaN,False,+917277184813,+918045888912,...,NaN,gpt-4o-mini,NaN,False,185.0,-OjZLTFGgqMo0JMHc6Nc,failed,No response from telephony provider,SID951375719431,7.277185e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188853,95971,"{'ts': 1768910102.458004, 'voip': {'to': '+918...",NaN,2026-01-20 11:57:02.320753+00:00,hi,False,NaN,False,+918084725146,+918047093431,...,NaN,gpt-4o-mini,NaN,False,176.0,-OjQFWsEaahzNzRJsSSI,failed,No response from telephony provider,SSF3252416,8.084725e+09
188854,187698,"{'ts': 1770642328.5050218, 'voip': {'to': '+91...",NaN,2026-02-09 13:07:54.507286+00:00,hi,False,NaN,False,+918084725146,+918045889078,...,NaN,gpt-4o-mini,NaN,False,221.0,-Ol1VRbrv4HbUcATVM-b,failed,No response from telephony provider,SSF3252416,8.084725e+09
188855,95936,"{'ts': 1768910126.6067264, 'chat': [{'role': '...","{""Disposition_code"": ""MESSAGE DELIVERED FOLLOW...",2026-01-20 11:55:37.355748+00:00,hi,False,NaN,True,+917856820753,+918047093431,...,https://millis-ai-recordings.s3.us-west-1.amaz...,gpt-4o-mini,0.774917,False,176.0,-OjQFUmbp7srZ5qP1rGb,user-ended,NaN,SSF3896644,7.856821e+09
188856,100696,"{'ts': 1768973105.5149648, 'voip': {'to': '+91...",NaN,2026-01-21 05:26:47.684983+00:00,hi,False,NaN,False,+919137500629,+918047093431,...,NaN,gpt-4o-mini,NaN,False,177.0,-OjU-rTLWxRb4XGaZ3eI,failed,No response from telephony provider,SSF3893617,9.137501e+09
188857,103865,"{'ts': 1768985709.4685287, 'voip': {'to': '+91...",NaN,2026-01-21 08:57:25.144653+00:00,hi,False,NaN,False,+919137500629,+918045889377,...,NaN,gpt-4o-mini,NaN,False,178.0,-OjUkwcBerHWK-GURpk1,failed,No response from telephony provider,SSF3893617,9.137501e+09

In [11]:
db_data[db_data['phone'] == 9060506175]['meta_data']

175    {'Name': 'कुंती देवी', 'campaign_id': '147', '...
176    {'Name': 'कुंती देवी', 'campaign_id': '163', '...
177    {'Name': 'कुंती देवी', 'campaign_id': '185', '...
178    {'Name': 'कुंती देवी', 'campaign_id': '188', '...
179    {'Name': 'कुंती देवी', 'campaign_id': '165', '...
180    {'Name': 'कुंती देवी', 'campaign_id': '166', '...
181    {'Name': 'कुंती देवी', 'campaign_id': '168', '...
182    {'Name': 'कुंती देवी', 'campaign_id': '169', '...
183    {'Name': 'कुंती देवी', 'campaign_id': '195', '...
184    {'Name': 'कुंती देवी', 'campaign_id': '202', '...
185    {'Name': 'कुंती देवी', 'campaign_id': '137', '...
Name: meta_data, dtype: object

In [12]:
duplicate = pd.read_csv("duplicate.csv")

In [13]:
db_data.columns

Index(['s_no', 'json_data', 'disposition', 'created_at', 'language',
       'is_disposition_available', 'transcript', 'is_transcript_available',
       'contact_to', 'contact_from', 'direction', 'call_start_ts',
       'call_end_ts', 'chat', 'provider', 'call_id', 'agent_id', 'duration',
       'meta_data', 'recording', 'model', 'cost', 'is_duplicate',
       'campaign_id', 'session_id', 'call_status', 'error_message', 'uid',
       'phone'],
      dtype='str')

In [14]:
df[['Phone Numeber','BorrowerCode']][df['count'] == 1]

       Phone Numeber  BorrowerCode
0         7737451883    SSF4002279
1         6263481515    SSF4009264
2         7232852188    SSF3984941
3         7681805283    SSF3988540
4         9460050437    SSF4006327
...              ...           ...
30260     8948078274    SSF3214290
30261     7275268499    SSF4599136
30262     7489248378  CID207300772
30263     9201362865  CID219406458
30264     9201065435    SSF5183182

[30155 rows x 2 columns]

In [15]:
unique_data = db_data[db_data['phone'].isin(df[df['count'] == 1]['Phone Numeber'])][['phone','meta_data']]

In [16]:
db_data[['phone','meta_data']]

               phone                                          meta_data
0       9.137501e+09  {'Name': 'रंजना देवी', 'campaign_id': '176', '...
1       9.137501e+09  {'Name': 'रंजना देवी', 'campaign_id': '180', '...
2       7.277185e+09  {'Name': 'सबिता कुमारी', 'campaign_id': '163',...
3       7.277185e+09  {'Name': 'सबिता कुमारी', 'campaign_id': '147',...
4       7.277185e+09  {'Name': 'सबिता कुमारी', 'campaign_id': '185',...
...              ...                                                ...
188853  8.084725e+09  {'Name': 'प्रभा देवी', 'campaign_id': '176', '...
188854  8.084725e+09  {'Uid': 'SSF3252416', 'Name': 'प्रभा देवी', 'c...
188855  7.856821e+09  {'Name': 'अनीता देवी', 'campaign_id': '176', '...
188856  9.137501e+09  {'Name': 'रंजना देवी', 'campaign_id': '177', '...
188857  9.137501e+09  {'Name': 'रंजना देवी', 'campaign_id': '178', '...

[188858 rows x 2 columns]

In [17]:
unique_data = df[['Phone Numeber','BorrowerCode']][df['count'] == 1]

In [18]:
unique_data

       Phone Numeber  BorrowerCode
0         7737451883    SSF4002279
1         6263481515    SSF4009264
2         7232852188    SSF3984941
3         7681805283    SSF3988540
4         9460050437    SSF4006327
...              ...           ...
30260     8948078274    SSF3214290
30261     7275268499    SSF4599136
30262     7489248378  CID207300772
30263     9201362865  CID219406458
30264     9201065435    SSF5183182

[30155 rows x 2 columns]

In [2]:
import asyncio
import aiohttp

async def make_request(input_text):
    url = "http://localhost:1234/api/v1/chat"
    headers = {
        "Authorization": "Bearer sk-lm-COIGf9Y3:mSMCpR1zsaXD8wrPs45P",
        "Content-Type": "application/json",
    }
    data = {
        "model": "mistralai/ministral-3-3b",
        "input": input_text
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, headers=headers, json=data) as resp:
            return await resp.json()

async def main():
    inputs = [
        "My favorite color is blue.",
        "What is the capital of France?",
        "Tell me a joke."
    ]
    for i in inputs:
        print("*"*100)
        response = await make_request(i)
        print(response)
        print("*"*100)

# To run the async main function
asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

       Phone Numeber  BorrowerCode
0         7737451883    SSF4002279
1         6263481515    SSF4009264
2         7232852188    SSF3984941
3         7681805283    SSF3988540
4         9460050437    SSF4006327
...              ...           ...
30260     8948078274    SSF3214290
30261     7275268499    SSF4599136
30262     7489248378  CID207300772
30263     9201362865  CID219406458
30264     9201065435    SSF5183182

[30155 rows x 2 columns]

In [33]:
u_data =unique_data[unique_data['Phone Numeber'].isin(unique_data['Phone Numeber'][3188:])]

In [37]:
values_str = "" 

for index, row in u_data.iterrows():
    values_str += f"('+91{row['Phone Numeber']}', '{row['BorrowerCode']}'),"

In [42]:
print(values_str)

('+919801809893', 'SSF2855858'),('+918252906593', 'CID262400366'),('+919693891764', 'SSF5164983'),('+917283017003', 'SSF5690937'),('+919370493034', 'SSF6290569'),('+918955667998', 'SID951374921859'),('+919158981279', 'SID951374974884'),('+916264493165', 'SSF2323869'),('+919102017492', 'SSF4858766'),('+918175952173', 'SSF6327164'),('+917070964815', 'SSF2844977'),('+919981659266', 'SSF3788472'),('+918769177322', 'SSF5278443'),('+919009602558', 'SID951375416466'),('+918603054744', 'SSF5329577'),('+916263439205', 'SID951373278193'),('+916260346860', 'SID951375409952'),('+917089916362', 'SID951373463210'),('+919001546131', 'SID951374796538'),('+917255000507', 'SSF2788808'),('+919065825579', 'SSF3200431'),('+918695036975', 'SSF5938031'),('+919661653313', 'SSF4297549'),('+918210618537', 'SID951374604931'),('+917309088024', 'SSF4469447'),('+917542921017', 'SID951374865591'),('+919131318085', 'SSF3988432'),('+919334076180', 'SSF5686682'),('+917610738194', 'SID951375515482'),('+919801534642', 'SSF6226205'),('+919310344976', 'SSF5885583'),('+919580230233', 'SSF2497852'),('+916263907887', 'CID204603708'),('+918112211553', 'SSF5758586'),('+916200209585', 'SSF5402997'),('+919835470771', 'SSF5029995'),('+918235116601', 'SSF5685205'),('+917645987709', 'SSF5083677'),('+918595362971', 'SSF6072146'),('+916375481157', 'SID951375425571'),('+917723859125', 'SID951373879313'),('+917779869245', 'SSF2913608'),('+919216440994', 'SID951374794507'),('+917905795830', 'SSF3506244'),('+919142597477', 'SSF3951504'),('+917735805053', 'SSF6324767'),('+919628088917', 'SSF5071381'),('+919971655783', 'SSF6147881'),('+918540830634', 'SSF4165191'),('+919116587059', 'SID951374598634'),('+917909687431', 'SSF3973730'),('+918084326997', 'SSF3142638'),('+917631042677', 'SSF4980773'),('+919793056681', 'SSF4174991'),('+919636241488', 'SSF4464607'),('+917339844506', 'SSF3822478'),('+918840709761', 'SSF4918629'),('+919111455320', 'SID951373795667'),('+918103637455', 'SSF3183456'),('+916205328066', 'SID951375695807'),('+917230847646', 'SID951375521083'),('+918603700445', 'SSF6194524'),('+918862859726', 'SSF5700919'),('+917545881062', 'SSF5720433'),('+919304101967', 'SID951375200038'),('+917724839734', 'SSF5059365'),('+919660695976', 'SSF6197423'),('+918871684282', 'SSF3558325'),('+916203806307', 'SSF4704178'),('+918102963346', 'SID951375119705'),('+919142005283', 'SSF5421524'),('+919021734588', 'SSF6034615'),('+919058993472', 'SSF6250968'),('+919113413204', 'SSF5957206'),('+917067696421', 'SSF4272965'),('+917906025846', 'SSF5320180'),('+919034647665', 'SSF2686202'),('+919525914715', 'SSF4653236'),('+917024673636', 'SID2125245607'),('+917764919591', 'SSF4560110'),('+918445089068', 'SSF6243946'),('+918294578797', 'SSF5622646'),('+919264212609', 'SSF2489727'),('+918092545861', 'SSF5058525'),('+919982395251', 'SSF3413781'),('+917566218195', 'SID951376017513'),('+918766272085', 'SSF2373552'),('+919110623433', 'SSF3883875'),('+919905980167', 'SSF5470315'),('+919852164048', 'SSF6127360'),('+917033033653', 'SSF4965549'),('+919110133105', 'SSF4143043'),('+919926440632', 'SSF3100761'),('+918923219671', 'SSF5575049'),('+917987657858', 'SSF5674024'),('+917989556704', 'SSF3242279'),('+919162469879', 'SSF6138538'),('+916303547960', 'SSF6000048'),('+917488956126', 'SSF5217083'),('+919935389469', 'SSF5143672'),('+917294945477', 'SSF3424558'),('+918727096132', 'SSF5764309'),('+918406854009', 'SSF5494144'),('+917454905072', 'SSF6140080'),('+918210467899', 'SSF5526866'),('+918085838617', 'SSF3658344'),('+918306079249', 'SID951374975260'),('+918006652012', 'SSF5751421'),('+916391339056', 'SSF6045606'),('+916203838207', 'SSF5444237'),('+918959752202', 'SSF3089822'),('+917781089520', 'SID951373010189'),('+918460416440', 'SSF6308446'),('+917424902458', 'SSF3852948'),('+917267858939', 'SSF5751940'),('+917427044708', 'SID951375212069'),('+919950485291', 'SSF2863415'),('+918433798861', 'SSF4950162'),('+917858848904', 'SSF5468228'),('+919098675608', 'SID951375417630'),('+919570537659', 'SSF3199088'),('+917746015968', 'SSF4666940'),('+919068651107', 'SSF4447286'),('+919953024928', 'SSF5438078'),('+916268653993', 'SID951374432365'),('+916307657152', 'SSF5629204'),('+919284992911', 'SID951374363275'),('+917488516422', 'SSF4141461'),('+917678485765', 'SSF4807629'),('+917727901492', 'SSF3502859'),('+918292052350', 'SSF5093497'),('+919508889779', 'SSF5070701'),('+917667243583', 'SID951373178561'),('+919009619168', 'SSF4289534'),('+916367497897', 'SSF3919701'),('+918676894154', 'SSF5091121'),('+917834875347', 'SSF5099799'),('+919653818719', 'SSF4066882'),('+917976394223', 'SSF3890409'),('+917340127881', 'SSF3171146'),('+918375997911', 'SSF6252685'),('+919754235689', 'SSF2835664'),('+919992226401', 'SID951375890998'),('+919729391104', 'SSF2641144'),('+916299578876', 'SSF2737795'),('+916201008568', 'SSF2682562'),('+917470400240', 'SSF2992715'),('+919187616461', 'SSF2416041'),('+917209860152', 'SSF2696352'),('+918686886885', 'SSF2788429'),('+919709107716', 'SSF2757311'),('+919659975388', 'SSF2694464'),('+919334776405', 'SSF2822842'),('+919983781679', 'SSF2675604'),('+918294430152', 'SSF3271953'),('+918211378949', 'SSF3199960'),('+917201055871', 'SSF2676752'),('+919784422185', 'SSF2676777'),('+919694238714', 'SSF2585706'),('+918226065766', 'SSF2992694'),('+917247017282', 'SSF3251840'),('+916265494064', 'SSF3211012'),('+916265640495', 'SSF3247519'),('+918538921293', 'SSF2762273'),('+919638856265', 'SSF2710651'),('+918435254780', 'SSF3229950'),('+918538961450', 'SSF2540775'),('+919946464646', 'SSF3303596'),('+918302071695', 'SSF2682787'),('+918668216314', 'SSF3052838'),('+919044032962', 'SID951373911235'),('+919523063866', 'SSF2809791'),('+917997979797', 'SSF2681290'),('+917877120211', 'SSF4016012'),('+917976920316', 'SSF3498532'),('+918619917265', 'SSF3010301'),('+917489591610', 'CID206503185'),('+917440496083', 'SSF4334371'),('+918839201023', 'SSF3298661'),('+918830072943', 'SSF3675343'),('+919728446985', 'SSF3221499'),('+919864668664', 'SSF2793548'),('+919098725754', 'SSF3947772'),('+919340900816', 'SSF3319621'),('+919852688796', 'SSF3167846'),('+919452507603', 'SSF3309174'),('+919285095357', 'SSF3319620'),('+916262479071', 'SID951374044806'),('+918968548658', 'SSF3100937'),('+918468925954', 'SSF3099615'),('+918780018020', 'SSF3099632'),('+918976464554', 'SSF3111338'),('+918946497552', 'SSF3100959'),('+919685346671', 'SSF3099633'),('+919691189675', 'SSF3973468'),('+919567686834', 'SSF3053519'),('+919984228321', 'SSF3236617'),('+918441979452', 'SID951374395594'),('+919799784648', 'SSF3379398'),('+916306164239', 'SSF3189070'),('+918576096697', 'SSF3189107'),('+917589643128', 'SSF3180032'),('+919630958458', 'SSF2850993'),('+919308458741', 'SSF2850015'),('+919111261255', 'SSF2916776'),('+919784673768', 'SSF3211950'),('+918147256365', 'SSF3101940'),('+916246164281', 'SID951374230067'),('+919153405147', 'SSF3360645'),('+918109294864', 'SSF5121146'),('+918965085848', 'SSF3331980'),('+917667481334', 'SID2125728570'),('+918318884248', 'SSF3803387'),('+919572729784', 'SSF5786546'),('+918658875471', 'SSF4235464'),('+919660625396', 'SID951376001256'),('+918235311368', 'SSF4615324'),('+917737371215', 'SSF2818409'),('+916299209216', 'SSF6069411'),('+917024713027', 'SSF5811965'),('+917987882141', 'SID951373821898'),('+919525402295', 'SSF3642564'),('+919039925661', 'SSF4843275'),('+919559526238', 'SSF5846318'),('+916263631666', 'SID951374025569'),('+919353795808', 'SID951372968276'),('+919518623294', 'SSF6388923'),('+917909610054', 'SID951374429248'),('+919044124702', 'SSF5841050'),('+917781047107', 'SSF5435039'),('+918302638469', 'SSF5077440'),('+917043808641', 'SSF4934186'),('+919773840430', 'SSF5686916'),('+918103651684', 'SSF3573175'),('+919424239429', 'SID951374552163'),('+916206131548', 'SSF5754589'),('+917759958401', 'SSF5789137'),('+918630562509', 'SSF6027299'),('+917404483849', 'SSF5751771'),('+918319573583', 'SID951375884086'),('+917042209711', 'SSF5083462'),('+919939707891', 'SSF4395454'),('+919166404136', 'SSF5099112'),('+919555728282', 'SID951376201771'),('+917004243021', 'SSF4780207'),('+919527609035', 'SSF5204330'),('+919798072970', 'SSF6341213'),('+916207188658', 'SSF5801862'),('+919328894139', 'SSF4595868'),('+918171354104', 'SSF4890558'),('+919341122936', 'SSF5540978'),('+919649126674', 'SSF5196068'),('+918521071107', 'SSF6251943'),('+919630686049', 'SSF5060667'),('+916268035058', 'SSF5331990'),('+918859482210', 'SSF5977987'),('+918815313640', 'CID081004098'),('+919153246147', 'SID951375520138'),('+919576642961', 'SSF5560832'),('+919648674455', 'SSF2962013'),('+919955425370', 'SSF6077834'),('+916261612383', 'SSF5764844'),('+919399517013', 'SID951374631023'),('+918102386640', 'SSF5308661'),('+918789331454', 'SSF4403026'),('+919026931997', 'SSF4844626'),('+919927336651', 'SSF5519073'),('+919329282158', 'SID951375405457'),('+919753187733', 'SID951374023821'),('+919341482432', 'SSF5856257'),('+917970554342', 'SSF5698462'),('+918271272156', 'SSF5675207'),('+919006893759', 'SSF5675126'),('+917814724832', 'SSF5320787'),('+919368846101', 'SSF5105687'),('+917667941431', 'SSF4324727'),('+917463016547', 'SSF5109688'),('+916266991283', 'SSF4168502'),('+919893243154', 'SSF3599665'),('+918128166144', 'SSF4906823'),('+919560662018', 'SID951376099922'),('+919508373243', 'SSF4866068'),('+917417867153', 'SSF5462810'),('+917040969877', 'SID2125217106'),('+919065646764', 'SSF5163164'),('+917747902383', 'SSF5266365'),('+919128147496', 'SSF6224568'),('+919905886920', 'SSF5501075'),('+919031257070', 'SSF5955184'),('+919795156297', 'SSF5171106'),('+918709893895', 'SSF4994386'),('+916374448378', 'SSF6283229'),('+918755464237', 'SSF6245299'),('+917879570800', 'SID80517'),('+919355399969', 'SSF3862520'),('+919584948569', 'SSF4101977'),('+918084033745', 'SSF6293653'),('+918969407334', 'SSF6233809'),('+917091305429', 'SSF5551236'),('+919770621620', 'SSF4409656'),('+917976691463', 'SSF2325941'),('+919302177750', 'SSF4355965'),('+916206452140', 'SSF5516153'),('+919315892637', 'SSF6162401'),('+918292121088', 'SSF5471439'),('+917408953557', 'SSF6191970'),('+918002652349', 'SSF5412928'),('+919575969861', 'SID2125158553'),('+919301297789', 'SID951375251189'),('+918809488352', 'SSF2990873'),('+919399259846', 'SID951373477538'),('+916203972010', 'SSF6222562'),('+916202828356', 'SSF6101926'),('+918057268306', 'SSF5678664'),('+918963906847', 'SSF5716045'),('+917597389896', 'SSF4823609'),('+918000413846', 'SSF3658531'),('+916268545109', 'SSF4834440'),('+918085807854', 'CID053201465'),('+919369133823', 'SSF6353782'),('+919918561789', 'SSF6339512'),('+917654051952', 'SSF6353701'),('+919343454084', 'SSF2803703'),('+918543815624', 'SSF4913404'),('+919155857580', 'SSF4931843'),('+918829944100', 'SSF4276224'),('+917355317641', 'SSF5750176'),('+918305674091', 'CID053212300'),('+918307529182', 'SSF2630406'),('+919608199898', 'SSF4257039'),('+918294349164', 'SSF6194525'),('+917223857440', 'CID061213068'),('+919569094712', 'SSF2899676'),('+918757984335', 'SSF5519177'),('+918434184303', 'SSF5156835'),('+919399136643', 'SSF4783294'),('+918458927086', 'SSF4811927'),('+917020737377', 'SSF6211937'),('+919165538085', 'SID951375581389'),('+919691221664', 'SSF3583708'),('+919835122495', 'SSF4826301'),('+919510301678', 'SSF2457421'),('+919166144241', 'SSF5596890'),('+917739566133', 'SSF5494930'),('+918737917881', 'SSF5231943'),('+919262713950', 'SSF5917457'),('+916299543623', 'SSF6354402'),('+918383072201', 'SSF5889069'),('+919471262635', 'SSF6257223'),('+919380313315', 'SSF5644551'),('+917070255097', 'SSF5845639'),('+919787788497', 'SID951374121894'),('+917061953252', 'SSF5014626'),('+917261057576', 'SSF2938361'),('+919303192417', 'SSF6351795'),('+917779887361', 'SSF5427214'),('+918298190977', 'SSF5572197'),('+917371021282', 'SSF4760582'),('+919301665793', 'SID951375037227'),('+918349774142', 'SSF2404724'),('+918814819261', 'SID951376044015'),('+919369664172', 'SSF6173836'),('+918273901553', 'SSF5863982'),('+917719635664', 'SSF6089783'),('+918859278845', 'SSF5982769'),('+919670835382', 'SSF6078470'),('+918619567590', 'SSF2680214'),('+919301018526', 'SSF2729396'),('+919334609354', 'SSF5713454'),('+918858256249', 'SSF4149432'),('+918340141235', 'SSF6296647'),('+919341318745', 'SSF5668084'),('+919955618803', 'SSF5726514'),('+917870337121', 'SSF5939807'),('+917250203026', 'SSF6307133'),('+918340613253', 'SSF5663693'),('+917209377002', 'SSF5103090'),('+917033255146', 'SID951375719538'),('+918236034798', 'SSF6209359'),('+919352786618', 'SSF3878087'),('+919508240624', 'SSF5880740'),('+917571019329', 'SSF5662113'),('+919755831746', 'SSF4255522'),('+917493958912', 'SSF5184242'),('+919568826526', 'SSF2878370'),('+916437967979', 'SID951375986349'),('+919828852776', 'SSF5762666'),('+919990451621', 'SSF2488769'),('+917260061309', 'SSF5480454'),('+919570923449', 'SSF5963157'),('+917033147023', 'SSF5425579'),('+918789242110', 'CID951376209599'),('+919341052389', 'SSF5534958'),('+919770067304', 'SSF5905671'),('+919142280703', 'SSF6441996'),('+918332045797', 'SSF5787635'),('+917739352062', 'SSF5678304'),('+919608712305', 'SSF6306404'),('+918770087768', 'SID2125182956'),('+918709335886', 'SSF5873583'),('+919131960035', 'SSF3779621'),('+919754189675', 'SID951375110446'),('+917765929158', 'SSF6329057'),('+917292812383', 'SSF5925548'),('+917292992811', 'SSF5645998'),('+918839694368', 'SSF5186412'),('+918603591431', 'SID951375628275'),('+916266159533', 'SID951373796563'),('+918085022094', 'SID2125306500'),('+917903314491', 'SSF4274408'),('+919521845902', 'SSF4240597'),('+918109637177', 'CID087212676'),('+917451984409', 'SSF5825226'),('+919340817964', 'SSF5971137'),('+917672884932', 'SSF4854876'),('+919821202194', 'SSF4862998'),('+918434854568', 'SSF3066170'),('+916264144526', 'SID951375000556'),('+919131578224', 'SID951375947451'),('+918274054573', 'SSF5280209'),('+917739549385', 'SSF5056126'),('+917459930379', 'SSF5695499'),('+918292059080', 'SSF5545392'),('+916268116407', 'SID951373027508'),('+918193928425', 'SSF5288496'),('+917371939410', 'SID951375943340'),('+917294114526', 'SSF6297049'),('+918619271679', 'SSF5342031'),('+917355321952', 'SSF4396357'),('+917984325339', 'SSF3539396'),('+919116013244', 'SSF4765577'),('+919006051693', 'SSF3385152'),('+919234140072', 'SSF5647508'),('+919219406645', 'SSF5793347'),('+917066372052', 'SSF5912758'),('+917079774842', 'SSF5204382'),('+918858755101', 'SSF4240877'),('+917067995127', 'SID2125233696'),('+919257445077', 'SSF2801769'),('+917323010989', 'SSF5287403'),('+918815498527', 'SSF5917948'),('+917091860344', 'SSF6306060'),('+919576803131', 'SID951374688154'),('+919977749020', 'CID128709550'),('+917014561359', 'SID951375251627'),('+917496067514', 'SSF5578730'),('+919334592798', 'SSF6310132'),('+919263328399', 'SSF6311736'),('+919770115706', 'SSF4942684'),('+919641172151', 'SSF6288931'),('+918292899273', 'SSF5052971'),('+917434880906', 'SID951375455776'),('+917061495137', 'SID951374228012'),('+917763899549', 'SSF5869403'),('+919117859325', 'SSF5001339'),('+919368571797', 'SSF5810010'),('+919852592557', 'SSF6280189'),('+917800625235', 'SSF6163386'),('+919636503759', 'SSF5149207'),('+917667752183', 'SSF5636924'),('+917073944340', 'SSF5330116'),('+917061563935', 'SSF3989426'),('+918809431222', 'SSF5508885'),('+917891942628', 'SSF2706837'),('+917261027689', 'SSF5446849'),('+918897635775', 'SSF6300985'),('+916266740430', 'SID951375273335'),('+919343687668', 'SSF5876724'),('+918709192739', 'SSF5545711'),('+918102510402', 'SSF5646661'),('+917724967267', 'SSF3801113'),('+919651463185', 'SSF4436418'),('+918092149545', 'SID951374440180'),('+917849835675', 'SID951374237478'),('+918409621443', 'SSF5257949'),('+919958493157', 'SSF3816812'),('+919389218408', 'SSF6233212'),('+919693234386', 'SID951374165399'),('+917354973762', 'SID951374099735'),('+919752836282', 'SSF4174370'),('+919264488030', 'SSF2292806'),('+917879034012', 'SID951375299249'),('+919304741474', 'SSF5759816'),('+919508101782', 'SSF4888273'),('+918294868258', 'SSF5010119'),('+918103102805', 'SSF4021839'),('+917067227446', 'SSF5047265'),('+919981838629', 'SSF4598154'),('+918445138017', 'SSF6324197'),('+919234537627', 'SSF5768423'),('+918969410751', 'SSF6001940'),('+917209422534', 'SSF5583299'),('+919098009799', 'SSF4987814'),('+918815167506', 'SSF5837761'),('+919970318568', 'SSF5188338'),('+919301532529', 'SSF5207349'),('+916376718752', 'SSF6310260'),('+919304050788', 'SSF5664506'),('+919630326598', 'SID951374866569'),('+917979765733', 'SSF4818920'),('+917024532371', 'SID951375548211'),('+916207596170', 'SSF5686735'),('+919234040943', 'SSF6276676'),('+917007844248', 'CID211601951'),('+917300116069', 'SSF4701042'),('+919304890086', 'SSF5710590'),('+918178708904', 'SSF5841564'),('+917794982145', 'SSF3623296'),('+917080874689', 'SID951374514636'),('+918815290514', 'SSF3448798'),('+916378504863', 'SSF3930683'),('+917073064896', 'SSF5389513'),('+919958340831', 'SID951375576787'),('+917257845960', 'SSF4457670'),('+917004526874', 'SSF5969505'),('+919031277626', 'SID951374494750'),('+919026542029', 'SSF4993718'),('+919608163695', 'CID211103428'),('+918209244612', 'SSF5833567'),('+916306068682', 'SID951374691275'),('+917325051722', 'SID951375606743'),('+919102312450', 'SSF6193365'),('+916267801958', 'CID204902706'),('+919304883927', 'SSF5159282'),('+919260855767', 'SID951375836239'),('+918890026073', 'SSF3797299'),('+917765042372', 'SSF4857145'),('+917424815069', 'SSF4616565'),('+919546633613', 'SSF6313285'),('+916299561314', 'SSF5413702'),('+919580272860', 'SSF4951428'),('+919155106435', 'SSF5166948'),('+919508845921', 'SSF4226353'),('+917541990629', 'SSF5441495'),('+918887923293', 'SSF4742750'),('+917091742416', 'SSF5507309'),('+917352313079', 'SSF4868194'),('+919241785503', 'SSF5577890'),('+916207890880', 'SSF3721766'),('+916203695244', 'SSF3607218'),('+916350509696', 'SSF3381330'),('+917568306143', 'SID951374494989'),('+917061085364', 'SSF3766643'),('+918696898586', 'SSF3818040'),('+918568786557', 'SSF3457467'),('+918935925507', 'SSF2612675'),('+918757782563', 'SSF3737451'),('+918797808167', 'SSF3615892'),('+919863470074', 'SSF3721228'),('+919608522469', 'SSF3925421'),('+919661468496', 'SSF3917636'),('+919528461889', 'SSF3626151'),('+919752133586', 'SSF3360643'),('+919653288077', 'SSF2763018'),('+919835712514', 'SSF3742886'),('+919589556036', 'SSF3819996'),('+919398236984', 'SSF3367688'),('+919102065960', 'SSF4232630'),('+919116878568', 'SSF2561758'),('+917897622217', 'SSF4573465'),('+916201671734', 'SSF4390292'),('+916238852366', 'SSF3410745'),('+916288888788', 'SSF3500102'),('+918872315563', 'SSF3395107'),('+918938000415', 'SSF4923734'),('+918905139384', 'SID951375808896'),('+919783329431', 'SID951375729877'),('+919335194887', 'SSF2783403'),('+917398659344', 'SSF3920785'),('+917061012087', 'SSF3954594'),('+919131094910', 'SSF3751565'),('+919341711532', 'SSF3709793'),('+919303630155', 'SSF2944740'),('+919799734203', 'SSF3966064'),('+916266117337', 'SID2125295578'),('+916532991999', 'SSF2594071'),('+916398594647', 'SSF3375809'),('+916988757546', 'SSF3427432'),('+916287634638', 'SSF3449967'),('+916267079967', 'SSF3231424'),('+916265940133', 'SID2125298439'),('+916205224762', 'SSF3732497'),('+916268158402', 'SSF4068677'),('+916200852356', 'SSF3382677'),('+916233385236', 'SSF3488754'),('+916523886532', 'SSF3394925'),('+916354342553', 'SSF3259567'),('+916903082257', 'SSF3356883'),('+916351352562', 'SSF3471240'),('+917357024654', 'SID951375015615'),('+917352174976', 'SSF3668268'),('+917999412085', 'SID951375925886'),('+917004359309', 'SSF2781151'),('+917751854876', 'SSF3239402'),('+917588381843', 'SSF3817701'),('+917528459965', 'SSF3550300'),('+917506767045', 'SSF3656116'),('+917878370910', 'SSF3033788'),('+917667929732', 'SSF3333910'),('+917568412073', 'SSF4017417'),('+917292970826', 'SSF3822527'),('+917439861260', 'SSF3307148'),('+917887279814', 'SSF3356213'),('+917870335224', 'SSF3382606'),('+917882605505', 'SSF2770417'),('+917488413296', 'SID951375671407'),('+918294572455', 'SSF3625205'),('+918434949722', 'SSF3467354'),('+918054524424', 'SSF3306243'),('+918252784531', 'SSF3669862'),('+918

In [43]:
query_sql(f"""
UPDATE spandana_sphoorty_data AS s
SET uid = m.uid
FROM (VALUES 
  ('+919801809893', 'SSF2855858'),
('+918252906593', 'CID262400366'),
('+919693891764', 'SSF5164983'),
('+917283017003', 'SSF5690937'),
('+919370493034', 'SSF6290569'),
('+918955667998', 'SID951374921859'),
('+919158981279', 'SID951374974884'),
('+916264493165', 'SSF2323869'),
('+919102017492', 'SSF4858766'),
('+918175952173', 'SSF6327164'),
('+917070964815', 'SSF2844977'),
('+919981659266', 'SSF3788472'),
('+918769177322', 'SSF5278443'),
('+919009602558', 'SID951375416466'),
('+918603054744', 'SSF5329577'),
('+916263439205', 'SID951373278193'),
('+916260346860', 'SID951375409952'),
('+917089916362', 'SID951373463210'),
('+919001546131', 'SID951374796538'),
('+917255000507', 'SSF2788808'),
('+919065825579', 'SSF3200431'),
('+918695036975', 'SSF5938031'),
('+919661653313', 'SSF4297549'),
('+918210618537', 'SID951374604931'),
('+917309088024', 'SSF4469447'),
('+917542921017', 'SID951374865591'),
('+919131318085', 'SSF3988432'),
('+919334076180', 'SSF5686682'),
('+917610738194', 'SID951375515482'),
('+919801534642', 'SSF6226205'),
('+919310344976', 'SSF5885583'),
('+919580230233', 'SSF2497852'),
('+916263907887', 'CID204603708'),
('+918112211553', 'SSF5758586'),
('+916200209585', 'SSF5402997'),
('+919835470771', 'SSF5029995'),
('+918235116601', 'SSF5685205'),
('+917645987709', 'SSF5083677'),
('+918595362971', 'SSF6072146'),
('+916375481157', 'SID951375425571'),
('+917723859125', 'SID951373879313'),
('+917779869245', 'SSF2913608'),
('+919216440994', 'SID951374794507'),
('+917905795830', 'SSF3506244'),
('+919142597477', 'SSF3951504'),
('+917735805053', 'SSF6324767'),
('+919628088917', 'SSF5071381'),
('+919971655783', 'SSF6147881'),
('+918540830634', 'SSF4165191'),
('+919116587059', 'SID951374598634'),
('+917909687431', 'SSF3973730'),
('+918084326997', 'SSF3142638'),
('+917631042677', 'SSF4980773'),
('+919793056681', 'SSF4174991'),
('+919636241488', 'SSF4464607'),
('+917339844506', 'SSF3822478'),
('+918840709761', 'SSF4918629'),
('+919111455320', 'SID951373795667'),
('+918103637455', 'SSF3183456'),
('+916205328066', 'SID951375695807'),
('+917230847646', 'SID951375521083'),
('+918603700445', 'SSF6194524'),
('+918862859726', 'SSF5700919'),
('+917545881062', 'SSF5720433'),
('+919304101967', 'SID951375200038'),
('+917724839734', 'SSF5059365'),
('+919660695976', 'SSF6197423'),
('+918871684282', 'SSF3558325'),
('+916203806307', 'SSF4704178'),
('+918102963346', 'SID951375119705'),
('+919142005283', 'SSF5421524'),
('+919021734588', 'SSF6034615'),
('+919058993472', 'SSF6250968'),
('+919113413204', 'SSF5957206'),
('+917067696421', 'SSF4272965'),
('+917906025846', 'SSF5320180'),
('+919034647665', 'SSF2686202'),
('+919525914715', 'SSF4653236'),
('+917024673636', 'SID2125245607'),
('+917764919591', 'SSF4560110'),
('+918445089068', 'SSF6243946'),
('+918294578797', 'SSF5622646'),
('+919264212609', 'SSF2489727'),
('+918092545861', 'SSF5058525'),
('+919982395251', 'SSF3413781'),
('+917566218195', 'SID951376017513'),
('+918766272085', 'SSF2373552'),
('+919110623433', 'SSF3883875'),
('+919905980167', 'SSF5470315'),
('+919852164048', 'SSF6127360'),
('+917033033653', 'SSF4965549'),
('+919110133105', 'SSF4143043'),
('+919926440632', 'SSF3100761'),
('+918923219671', 'SSF5575049'),
('+917987657858', 'SSF5674024'),
('+917989556704', 'SSF3242279'),
('+919162469879', 'SSF6138538'),
('+916303547960', 'SSF6000048'),
('+917488956126', 'SSF5217083'),
('+919935389469', 'SSF5143672'),
('+917294945477', 'SSF3424558'),
('+918727096132', 'SSF5764309'),
('+918406854009', 'SSF5494144'),
('+917454905072', 'SSF6140080'),
('+918210467899', 'SSF5526866'),
('+918085838617', 'SSF3658344'),
('+918306079249', 'SID951374975260'),
('+918006652012', 'SSF5751421'),
('+916391339056', 'SSF6045606'),
('+916203838207', 'SSF5444237'),
('+918959752202', 'SSF3089822'),
('+917781089520', 'SID951373010189'),
('+918460416440', 'SSF6308446'),
('+917424902458', 'SSF3852948'),
('+917267858939', 'SSF5751940'),
('+917427044708', 'SID951375212069'),
('+919950485291', 'SSF2863415'),
('+918433798861', 'SSF4950162'),
('+917858848904', 'SSF5468228'),
('+919098675608', 'SID951375417630'),
('+919570537659', 'SSF3199088'),
('+917746015968', 'SSF4666940'),
('+919068651107', 'SSF4447286'),
('+919953024928', 'SSF5438078'),
('+916268653993', 'SID951374432365'),
('+916307657152', 'SSF5629204'),
('+919284992911', 'SID951374363275'),
('+917488516422', 'SSF4141461'),
('+917678485765', 'SSF4807629'),
('+917727901492', 'SSF3502859'),
('+918292052350', 'SSF5093497'),
('+919508889779', 'SSF5070701'),
('+917667243583', 'SID951373178561'),
('+919009619168', 'SSF4289534'),
('+916367497897', 'SSF3919701'),
('+918676894154', 'SSF5091121'),
('+917834875347', 'SSF5099799'),
('+919653818719', 'SSF4066882'),
('+917976394223', 'SSF3890409'),
('+917340127881', 'SSF3171146'),
('+918375997911', 'SSF6252685'),
('+919754235689', 'SSF2835664'),
('+919992226401', 'SID951375890998'),
('+919729391104', 'SSF2641144'),
('+916299578876', 'SSF2737795'),
('+916201008568', 'SSF2682562'),
('+917470400240', 'SSF2992715'),
('+919187616461', 'SSF2416041'),
('+917209860152', 'SSF2696352'),
('+918686886885', 'SSF2788429'),
('+919709107716', 'SSF2757311'),
('+919659975388', 'SSF2694464'),
('+919334776405', 'SSF2822842'),
('+919983781679', 'SSF2675604'),
('+918294430152', 'SSF3271953'),
('+918211378949', 'SSF3199960'),
('+917201055871', 'SSF2676752'),
('+919784422185', 'SSF2676777'),
('+919694238714', 'SSF2585706'),
('+918226065766', 'SSF2992694'),
('+917247017282', 'SSF3251840'),
('+916265494064', 'SSF3211012'),
('+916265640495', 'SSF3247519'),
('+918538921293', 'SSF2762273'),
('+919638856265', 'SSF2710651'),
('+918435254780', 'SSF3229950'),
('+918538961450', 'SSF2540775'),
('+919946464646', 'SSF3303596'),
('+918302071695', 'SSF2682787'),
('+918668216314', 'SSF3052838'),
('+919044032962', 'SID951373911235'),
('+919523063866', 'SSF2809791'),
('+917997979797', 'SSF2681290'),
('+917877120211', 'SSF4016012'),
('+917976920316', 'SSF3498532'),
('+918619917265', 'SSF3010301'),
('+917489591610', 'CID206503185'),
('+917440496083', 'SSF4334371'),
('+918839201023', 'SSF3298661'),
('+918830072943', 'SSF3675343'),
('+919728446985', 'SSF3221499'),
('+919864668664', 'SSF2793548'),
('+919098725754', 'SSF3947772'),
('+919340900816', 'SSF3319621'),
('+919852688796', 'SSF3167846'),
('+919452507603', 'SSF3309174'),
('+919285095357', 'SSF3319620'),
('+916262479071', 'SID951374044806'),
('+918968548658', 'SSF3100937'),
('+918468925954', 'SSF3099615'),
('+918780018020', 'SSF3099632'),
('+918976464554', 'SSF3111338'),
('+918946497552', 'SSF3100959'),
('+919685346671', 'SSF3099633'),
('+919691189675', 'SSF3973468'),
('+919567686834', 'SSF3053519'),
('+919984228321', 'SSF3236617'),
('+918441979452', 'SID951374395594'),
('+919799784648', 'SSF3379398'),
('+916306164239', 'SSF3189070'),
('+918576096697', 'SSF3189107'),
('+917589643128', 'SSF3180032'),
('+919630958458', 'SSF2850993'),
('+919308458741', 'SSF2850015'),
('+919111261255', 'SSF2916776'),
('+919784673768', 'SSF3211950'),
('+918147256365', 'SSF3101940'),
('+916246164281', 'SID951374230067'),
('+919153405147', 'SSF3360645'),
('+918109294864', 'SSF5121146'),
('+918965085848', 'SSF3331980'),
('+917667481334', 'SID2125728570'),
('+918318884248', 'SSF3803387'),
('+919572729784', 'SSF5786546'),
('+918658875471', 'SSF4235464'),
('+919660625396', 'SID951376001256'),
('+918235311368', 'SSF4615324'),
('+917737371215', 'SSF2818409'),
('+916299209216', 'SSF6069411'),
('+917024713027', 'SSF5811965'),
('+917987882141', 'SID951373821898'),
('+919525402295', 'SSF3642564'),
('+919039925661', 'SSF4843275'),
('+919559526238', 'SSF5846318'),
('+916263631666', 'SID951374025569'),
('+919353795808', 'SID951372968276'),
('+919518623294', 'SSF6388923'),
('+917909610054', 'SID951374429248'),
('+919044124702', 'SSF5841050'),
('+917781047107', 'SSF5435039'),
('+918302638469', 'SSF5077440'),
('+917043808641', 'SSF4934186'),
('+919773840430', 'SSF5686916'),
('+918103651684', 'SSF3573175'),
('+919424239429', 'SID951374552163'),
('+916206131548', 'SSF5754589'),
('+917759958401', 'SSF5789137'),
('+918630562509', 'SSF6027299'),
('+917404483849', 'SSF5751771'),
('+918319573583', 'SID951375884086'),
('+917042209711', 'SSF5083462'),
('+919939707891', 'SSF4395454'),
('+919166404136', 'SSF5099112'),
('+919555728282', 'SID951376201771'),
('+917004243021', 'SSF4780207'),
('+919527609035', 'SSF5204330'),
('+919798072970', 'SSF6341213'),
('+916207188658', 'SSF5801862'),
('+919328894139', 'SSF4595868'),
('+918171354104', 'SSF4890558'),
('+919341122936', 'SSF5540978'),
('+919649126674', 'SSF5196068'),
('+918521071107', 'SSF6251943'),
('+919630686049', 'SSF5060667'),
('+916268035058', 'SSF5331990'),
('+918859482210', 'SSF5977987'),
('+918815313640', 'CID081004098'),
('+919153246147', 'SID951375520138'),
('+919576642961', 'SSF5560832'),
('+919648674455', 'SSF2962013'),
('+919955425370', 'SSF6077834'),
('+916261612383', 'SSF5764844'),
('+919399517013', 'SID951374631023'),
('+918102386640', 'SSF5308661'),
('+918789331454', 'SSF4403026'),
('+919026931997', 'SSF4844626'),
('+919927336651', 'SSF5519073'),
('+919329282158', 'SID951375405457'),
('+919753187733', 'SID951374023821'),
('+919341482432', 'SSF5856257'),
('+917970554342', 'SSF5698462'),
('+918271272156', 'SSF5675207'),
('+919006893759', 'SSF5675126'),
('+917814724832', 'SSF5320787'),
('+919368846101', 'SSF5105687'),
('+917667941431', 'SSF4324727'),
('+917463016547', 'SSF5109688'),
('+916266991283', 'SSF4168502'),
('+919893243154', 'SSF3599665'),
('+918128166144', 'SSF4906823'),
('+919560662018', 'SID951376099922'),
('+919508373243', 'SSF4866068'),
('+917417867153', 'SSF5462810'),
('+917040969877', 'SID2125217106'),
('+919065646764', 'SSF5163164'),
('+917747902383', 'SSF5266365'),
('+919128147496', 'SSF6224568'),
('+919905886920', 'SSF5501075'),
('+919031257070', 'SSF5955184'),
('+919795156297', 'SSF5171106'),
('+918709893895', 'SSF4994386'),
('+916374448378', 'SSF6283229'),
('+918755464237', 'SSF6245299'),
('+917879570800', 'SID80517'),
('+919355399969', 'SSF3862520'),
('+919584948569', 'SSF4101977'),
('+918084033745', 'SSF6293653'),
('+918969407334', 'SSF6233809'),
('+917091305429', 'SSF5551236'),
('+919770621620', 'SSF4409656'),
('+917976691463', 'SSF2325941'),
('+919302177750', 'SSF4355965'),
('+916206452140', 'SSF5516153'),
('+919315892637', 'SSF6162401'),
('+918292121088', 'SSF5471439'),
('+917408953557', 'SSF6191970'),
('+918002652349', 'SSF5412928'),
('+919575969861', 'SID2125158553'),
('+919301297789', 'SID951375251189'),
('+918809488352', 'SSF2990873'),
('+919399259846', 'SID951373477538'),
('+916203972010', 'SSF6222562'),
('+916202828356', 'SSF6101926'),
('+918057268306', 'SSF5678664'),
('+918963906847', 'SSF5716045'),
('+917597389896', 'SSF4823609'),
('+918000413846', 'SSF3658531'),
('+916268545109', 'SSF4834440'),
('+918085807854', 'CID053201465'),
('+919369133823', 'SSF6353782'),
('+919918561789', 'SSF6339512'),
('+917654051952', 'SSF6353701'),
('+919343454084', 'SSF2803703'),
('+918543815624', 'SSF4913404'),
('+919155857580', 'SSF4931843'),
('+918829944100', 'SSF4276224'),
('+917355317641', 'SSF5750176'),
('+918305674091', 'CID053212300'),
('+918307529182', 'SSF2630406'),
('+919608199898', 'SSF4257039'),
('+918294349164', 'SSF6194525'),
('+917223857440', 'CID061213068'),
('+919569094712', 'SSF2899676'),
('+918757984335', 'SSF5519177'),
('+918434184303', 'SSF5156835'),
('+919399136643', 'SSF4783294'),
('+918458927086', 'SSF4811927'),
('+917020737377', 'SSF6211937'),
('+919165538085', 'SID951375581389'),
('+919691221664', 'SSF3583708'),
('+919835122495', 'SSF4826301'),
('+919510301678', 'SSF2457421'),
('+919166144241', 'SSF5596890'),
('+917739566133', 'SSF5494930'),
('+918737917881', 'SSF5231943'),
('+919262713950', 'SSF5917457'),
('+916299543623', 'SSF6354402'),
('+918383072201', 'SSF5889069'),
('+919471262635', 'SSF6257223'),
('+919380313315', 'SSF5644551'),
('+917070255097', 'SSF5845639'),
('+919787788497', 'SID951374121894'),
('+917061953252', 'SSF5014626'),
('+917261057576', 'SSF2938361'),
('+919303192417', 'SSF6351795'),
('+917779887361', 'SSF5427214'),
('+918298190977', 'SSF5572197'),
('+917371021282', 'SSF4760582'),
('+919301665793', 'SID951375037227'),
('+918349774142', 'SSF2404724'),
('+918814819261', 'SID951376044015'),
('+919369664172', 'SSF6173836'),
('+918273901553', 'SSF5863982'),
('+917719635664', 'SSF6089783'),
('+918859278845', 'SSF5982769'),
('+919670835382', 'SSF6078470'),
('+918619567590', 'SSF2680214'),
('+919301018526', 'SSF2729396'),
('+919334609354', 'SSF5713454'),
('+918858256249', 'SSF4149432'),
('+918340141235', 'SSF6296647'),
('+919341318745', 'SSF5668084'),
('+919955618803', 'SSF5726514'),
('+917870337121', 'SSF5939807'),
('+917250203026', 'SSF6307133'),
('+918340613253', 'SSF5663693'),
('+917209377002', 'SSF5103090'),
('+917033255146', 'SID951375719538'),
('+918236034798', 'SSF6209359'),
('+919352786618', 'SSF3878087'),
('+919508240624', 'SSF5880740'),
('+917571019329', 'SSF5662113'),
('+919755831746', 'SSF4255522'),
('+917493958912', 'SSF5184242'),
('+919568826526', 'SSF2878370'),
('+916437967979', 'SID951375986349'),
('+919828852776', 'SSF5762666'),
('+919990451621', 'SSF2488769'),
('+917260061309', 'SSF5480454'),
('+919570923449', 'SSF5963157'),
('+917033147023', 'SSF5425579'),
('+918789242110', 'CID951376209599'),
('+919341052389', 'SSF5534958'),
('+919770067304', 'SSF5905671'),
('+919142280703', 'SSF6441996'),
('+918332045797', 'SSF5787635'),
('+917739352062', 'SSF5678304'),
('+919608712305', 'SSF6306404'),
('+918770087768', 'SID2125182956'),
('+918709335886', 'SSF5873583'),
('+919131960035', 'SSF3779621'),
('+919754189675', 'SID951375110446'),
('+917765929158', 'SSF6329057'),
('+917292812383', 'SSF5925548'),
('+917292992811', 'SSF5645998'),
('+918839694368', 'SSF5186412'),
('+918603591431', 'SID951375628275'),
('+916266159533', 'SID951373796563'),
('+918085022094', 'SID2125306500'),
('+917903314491', 'SSF4274408'),
('+919521845902', 'SSF4240597'),
('+918109637177', 'CID087212676'),
('+917451984409', 'SSF5825226'),
('+919340817964', 'SSF5971137'),
('+917672884932', 'SSF4854876'),
('+919821202194', 'SSF4862998'),
('+918434854568', 'SSF3066170'),
('+916264144526', 'SID951375000556'),
('+919131578224', 'SID951375947451'),
('+918274054573', 'SSF5280209'),
('+917739549385', 'SSF5056126'),
('+917459930379', 'SSF5695499'),
('+918292059080', 'SSF5545392'),
('+916268116407', 'SID951373027508'),
('+918193928425', 'SSF5288496'),
('+917371939410', 'SID951375943340'),
('+917294114526', 'SSF6297049'),
('+918619271679', 'SSF5342031'),
('+917355321952', 'SSF4396357'),
('+917984325339', 'SSF3539396'),
('+919116013244', 'SSF4765577'),
('+919006051693', 'SSF3385152'),
('+919234140072', 'SSF5647508'),
('+919219406645', 'SSF5793347'),
('+917066372052', 'SSF5912758'),
('+917079774842', 'SSF5204382'),
('+918858755101', 'SSF4240877'),
('+917067995127', 'SID2125233696'),
('+919257445077', 'SSF2801769'),
('+917323010989', 'SSF5287403'),
('+918815498527', 'SSF5917948'),
('+917091860344', 'SSF6306060'),
('+919576803131', 'SID951374688154'),
('+919977749020', 'CID128709550'),
('+917014561359', 'SID951375251627'),
('+917496067514', 'SSF5578730'),
('+919334592798', 'SSF6310132'),
('+919263328399', 'SSF6311736'),
('+919770115706', 'SSF4942684'),
('+919641172151', 'SSF6288931'),
('+918292899273', 'SSF5052971'),
('+917434880906', 'SID951375455776'),
('+917061495137', 'SID951374228012'),
('+917763899549', 'SSF5869403'),
('+919117859325', 'SSF5001339'),
('+919368571797', 'SSF5810010'),
('+919852592557', 'SSF6280189'),
('+917800625235', 'SSF6163386'),
('+919636503759', 'SSF5149207'),
('+917667752183', 'SSF5636924'),
('+917073944340', 'SSF5330116'),
('+917061563935', 'SSF3989426'),
('+918809431222', 'SSF5508885'),
('+917891942628', 'SSF2706837'),
('+917261027689', 'SSF5446849'),
('+918897635775', 'SSF6300985'),
('+916266740430', 'SID951375273335'),
('+919343687668', 'SSF5876724'),
('+918709192739', 'SSF5545711'),
('+918102510402', 'SSF5646661'),
('+917724967267', 'SSF3801113'),
('+919651463185', 'SSF4436418'),
('+918092149545', 'SID951374440180'),
('+917849835675', 'SID951374237478'),
('+918409621443', 'SSF5257949'),
('+919958493157', 'SSF3816812'),
('+919389218408', 'SSF6233212'),
('+919693234386', 'SID951374165399'),
('+917354973762', 'SID951374099735'),
('+919752836282', 'SSF4174370'),
('+919264488030', 'SSF2292806'),
('+917879034012', 'SID951375299249'),
('+919304741474', 'SSF5759816'),
('+919508101782', 'SSF4888273'),
('+918294868258', 'SSF5010119'),
('+918103102805', 'SSF4021839'),
('+917067227446', 'SSF5047265'),
('+919981838629', 'SSF4598154'),
('+918445138017', 'SSF6324197'),
('+919234537627', 'SSF5768423'),
('+918969410751', 'SSF6001940'),
('+917209422534', 'SSF5583299'),
('+919098009799', 'SSF4987814'),
('+918815167506', 'SSF5837761'),
('+919970318568', 'SSF5188338'),
('+919301532529', 'SSF5207349'),
('+916376718752', 'SSF6310260'),
('+919304050788', 'SSF5664506'),
('+919630326598', 'SID951374866569'),
('+917979765733', 'SSF4818920'),
('+917024532371', 'SID951375548211'),
('+916207596170', 'SSF5686735'),
('+919234040943', 'SSF6276676'),
('+917007844248', 'CID211601951'),
('+917300116069', 'SSF4701042'),
('+919304890086', 'SSF5710590'),
('+918178708904', 'SSF5841564'),
('+917794982145', 'SSF3623296'),
('+917080874689', 'SID951374514636'),
('+918815290514', 'SSF3448798'),
('+916378504863', 'SSF3930683'),
('+917073064896', 'SSF5389513'),
('+919958340831', 'SID951375576787'),
('+917257845960', 'SSF4457670'),
('+917004526874', 'SSF5969505'),
('+919031277626', 'SID951374494750'),
('+919026542029', 'SSF4993718'),
('+919608163695', 'CID211103428'),
('+918209244612', 'SSF5833567'),
('+916306068682', 'SID951374691275'),
('+917325051722', 'SID951375606743'),
('+919102312450', 'SSF6193365'),
('+916267801958', 'CID204902706'),
('+919304883927', 'SSF5159282'),
('+919260855767', 'SID951375836239'),
('+918890026073', 'SSF3797299'),
('+917765042372', 'SSF4857145'),
('+917424815069', 'SSF4616565'),
('+919546633613', 'SSF6313285'),
('+916299561314', 'SSF5413702'),
('+919580272860', 'SSF4951428'),
('+919155106435', 'SSF5166948'),
('+919508845921', 'SSF4226353'),
('+917541990629', 'SSF5441495'),
('+918887923293', 'SSF4742750'),
('+917091742416', 'SSF5507309'),
('+917352313079', 'SSF4868194'),
('+919241785503', 'SSF5577890'),
('+916207890880', 'SSF3721766'),
('+916203695244', 'SSF3607218'),
('+916350509696', 'SSF3381330'),
('+917568306143', 'SID951374494989'),
('+917061085364', 'SSF3766643'),
('+918696898586', 'SSF3818040'),
('+918568786557', 'SSF3457467'),
('+918935925507', 'SSF2612675'),
('+918757782563', 'SSF3737451'),
('+918797808167', 'SSF3615892'),
('+919863470074', 'SSF3721228'),
('+919608522469', 'SSF3925421'),
('+919661468496', 'SSF3917636'),
('+919528461889', 'SSF3626151'),
('+919752133586', 'SSF3360643'),
('+919653288077', 'SSF2763018'),
('+919835712514', 'SSF3742886'),
('+919589556036', 'SSF3819996'),
('+919398236984', 'SSF3367688'),
('+919102065960', 'SSF4232630'),
('+919116878568', 'SSF2561758'),
('+917897622217', 'SSF4573465'),
('+916201671734', 'SSF4390292'),
('+916238852366', 'SSF3410745'),
('+916288888788', 'SSF3500102'),
('+918872315563', 'SSF3395107'),
('+918938000415', 'SSF4923734'),
('+918905139384', 'SID951375808896'),
('+919783329431', 'SID951375729877'),
('+919335194887', 'SSF2783403'),
('+917398659344', 'SSF3920785'),
('+917061012087', 'SSF3954594'),
('+919131094910', 'SSF3751565'),
('+919341711532', 'SSF3709793'),
('+919303630155', 'SSF2944740'),
('+919799734203', 'SSF3966064'),
('+916266117337', 'SID2125295578'),
('+916532991999', 'SSF2594071'),
('+916398594647', 'SSF3375809'),
('+916988757546', 'SSF3427432'),
('+916287634638', 'SSF3449967'),
('+916267079967', 'SSF3231424'),
('+916265940133', 'SID2125298439'),
('+916205224762', 'SSF3732497'),
('+916268158402', 'SSF4068677'),
('+916200852356', 'SSF3382677'),
('+916233385236', 'SSF3488754'),
('+916523886532', 'SSF3394925'),
('+916354342553', 'SSF3259567'),
('+916903082257', 'SSF3356883'),
('+916351352562', 'SSF3471240'),
('+917357024654', 'SID951375015615'),
('+917352174976', 'SSF3668268'),
('+917999412085', 'SID951375925886'),
('+917004359309', 'SSF2781151'),
('+917751854876', 'SSF3239402'),
('+917588381843', 'SSF3817701'),
('+917528459965', 'SSF3550300'),
('+917506767045', 'SSF3656116'),
('+917878370910', 'SSF3033788'),
('+917667929732', 'SSF3333910'),
('+917568412073', 'SSF4017417'),
('+917292970826', 'SSF3822527'),
('+917439861260', 'SSF3307148'),
('+917887279814', 'SSF3356213'),
('+917870335224', 'SSF3382606'),
('+917882605505', 'SSF2770417'),
('+917488413296', 'SID951375671407'),
('+918294572455', 'SSF3625205'),
('+918434949722', 'SSF3467354'),
('+918054524424', 'SSF3306243'),
('+918252784531', 'SSF3669862'),
('+918564946448', 'SSF3302664'),
('+918955790670', 'SSF3154347'),
('+918815824897', 'SSF3668908'),
('+918756457388', 'SSF3356203'),
('+918523641278', 'SSF3617402'),
('+919608442441', 'SSF3171032'),
('+919661649227', 'SID951375562481'),
('+919302367302', 'SID951373725385'),
('+919102073905', 'SSF3272980'),
('+919905149619', 'SSF3461986'),
('+919425528514', 'SSF3666052'),
('+919548451846', 'SSF3250481'),
('+919470707970', 'SSF3044598'),
('+919162396701', 'SID951375421639'),
('+919135331368', 'SSF3488698'),
('+919754607640', 'SSF3236474'),
('+919330444957', 'SSF3724975'),
('+919784646569', 'SSF2796507'),
('+919908754123', 'SSF3394987'),
('+919263310642', 'SSF3701473'),
('+919655554899', 'SSF3517539'),
('+919559609618', 'SSF3576489'),
('+919399694348', 'SSF4163427'),
('+916205602596', 'SSF3914090'),
('+918092870719', 'SID2125450849'),
('+919305429118', 'CID211503693'),
('+919835830503', 'SSF5526892'),
('+916200456772', 'SSF3446852'),
('+916203562172', 'SSF3155947'),
('+916350565657', 'SSF3381665'),
('+916346494878', 'SSF3160099'),
('+917876342454', 'SSF3398408'),
('+917250675097', 'SSF3322946'),
('+918292382692', 'SSF3382070'),
('+918434694848', 'SSF3547090'),
('+918089906456', 'SSF3259839'),
('+918656494440', 'SSF3312427'),
('+918597469875', 'SSF3236186'),
('+918769894369', 'SSF4266695'),
('+918754448494', 'SSF2744092'),
('+918239352618', 'SSF3616837'),
('+918348678496', 'SSF3356160'),
('+918648900455', 'SSF3345878'),
('+919508383594', 'SID951374496942'),
('+919783328119', 'SSF3517195'),
('+919292754305', 'SSF3321671'),
('+919739494573', 'SSF3427145'),
('+919162890236', 'SID951375851621'),
('+919934533340', 'SSF3589775'),
('+919534728939', 'SSF2684140'),
('+919709824282', 'SSF3249001'),
('+919335476288', 'SSF3250103'),
('+919693743380', 'SSF3258350'),
('+919176556885', 'SSF3120186'),
('+919185258235', 'SSF3332226'),
('+919648757649', 'SSF3297511'),
('+919661361641', 'SSF3407527'),
('+916204024968', 'SSF5101808'),
('+917070238496', 'SSF5599494'),
('+919536742494', 'SSF4023726'),
('+918604347953', 'SSF4901117'),
('+919523637772', 'SSF4049490'),
('+918847029283', 'SSF4960585'),
('+917763078836', 'SSF4930189'),
('+919036352112', 'SSF3506787'),
('+917267024898', 'SSF5325823'),
('+917479552311', 'SSF4865664'),
('+919234789458', 'SSF4891578'),
('+917903534446', 'SSF4773106'),
('+919155658581', 'SSF4772943'),
('+917488465867', 'SID951372982113'),
('+918252540054', 'SSF2616255'),
('+919508966106', 'SSF3381297'),
('+917543939220', 'SSF3943770'),
('+916397956794', 'SSF3740918'),
('+917607047524', 'SSF4725483'),
('+917368041256', 'SID951374343684'),
('+918409747026', 'SID951374371692'),
('+918303217277', 'SID951376099535'),
('+916245544856', 'CID239801339'),
('+916394897730', 'SSF3329760'),
('+919978484240', 'SSF3420716'),
('+919982533714', 'SSF3514924'),
('+919509390351', 'SSF3050479'),
('+917404978272', 'SSF2370843'),
('+917082026777', 'SSF2590852'),
('+919523101507', 'SID951374305923'),
('+918951152756', 'SSF3231332'),
('+919632841785', 'SID951375945234'),
('+919163777418', 'SSF3602111'),
('+918529966983', 'SSF3428511'),
('+917383782938', 'SSF3183577'),
('+918797746551', 'SID951374711454'),
('+917482812777', 'SSF3405424'),
('+919798797724', 'SSF3193593'),
('+919850066226', 'SID951373460501'),
('+918864346464', 'SSF2692038'),
('+919263934331', 'SSF3406223'),
('+919672554165', 'SID951375832009'),
('+918683077921', 'SID951375888719'),
('+919654830053', 'SSF2743503'),
('+918102293983', 'SSF3267024'),
('+919171429136', 'SSF3935338'),
('+918655364169', 'SSF2964952'),
('+919636734845', 'SSF2924519'),
('+918290107084', 'SSF4030413'),
('+919497961646', 'SSF2845791'),
('+919494846481', 'SSF2820601'),
('+919754455625', 'SSF3165007'),
('+919636674894', 'SSF2677509'),
('+917458066932', 'SSF3236605'),
('+917367876170', 'SSF2971642'),
('+919507031995', 'SSF3037828'),
('+917345685587', 'SSF2846692'),
('+919521151287', 'SSF2959651'),
('+916200069385', 'SSF3053097'),
('+917762558082', 'SSF2809916'),
('+917808660691', 'SSF3601187'),
('+916261390775', 'SSF3809258'),
('+919123494848', 'SSF2902236'),
('+919120352038', 'SSF3256642'),
('+919672299684', 'SSF2971833'),
('+918709456132', 'SSF2888467'),
('+919695846675', 'SSF2856928'),
('+919807208668', 'SSF2816431'),
('+916425498739', 'SSF2958064'),
('+919404240735', 'SSF2816428'),
('+919798222050', 'SSF2894715'),
('+918527440264', 'SSF3152711'),
('+918924922396', 'SSF4898152'),
('+917418830295', 'SSF4791683'),
('+917352444052', 'SID2125559720'),
('+916299264686', 'SSF2890910'),
('+916203565531', 'SSF3865841'),
('+916287112736', 'SSF2893653'),
('+917426982476', 'SSF3754432'),
('+917357574376', 'SID951376204032'),
('+917667151679', 'SSF3718764'),
('+917250041461', 'SSF4584749'),
('+917050784417', 'SSF4584689'),
('+917696938673', 'SSF3769817'),
('+917320035285', 'SSF3730894'),
('+918252006112', 'SSF2735159'),
('+918434191732', 'SSF3787019'),
('+918252693404', 'SSF4585566'),
('+918429596199', 'SSF3342717'),
('+919006693867', 'SID951376218649'),
('+919336140816', 'SSF2627473'),
('+919801075883', 'SSF3421181'),
('+919939067281', 'SSF4213479'),
('+919545486688', 'SSF3897823'),
('+919110015246', 'SSF3912282'),
('+919536535656', 'SSF3448736'),
('+919532076194', 'SID951375375734'),
('+919585318855', 'SSF3868243'),
('+917091107874', 'SSF4811042'),
('+919519311541', 'SSF4825836'),
('+918603253755', 'SSF4386192'),
('+919142972772', 'SSF5905607'),
('+919153526781', 'SSF5642971'),
('+918521072652', 'SSF5034134'),
('+916238885236', 'SSF3410843'),
('+917001890742', 'SSF3459333'),
('+917295867218', 'SSF3467340'),
('+919971887521', 'SSF2756462'),
('+919631650822', 'SID951374508821'),
('+919587587819', 'SID951375869985'),
('+916377963398', 'SSF4579796'),
('+917366832183', 'SSF3952673'),
('+918102069644', 'SSF4075165'),
('+918864019872', 'SSF4287589'),
('+919142032382', 'SSF3923600'),
('+919131161280', 'SSF4509857'),
('+919329984138', 'SSF4566144'),
('+916204649406', 'SSF3320984'),
('+916205303517', 'SSF3260490'),
('+916205401372', 'SSF3204918'),
('+916204673850', 'SSF2629770'),
('+916288363213', 'SSF3394986'),
('+917562082829', 'SSF3438633'),
('+917976797979', 'SSF3683526'),
('+917565889988', 'SSF2365002'),
('+918292238995', 'SSF3178117'),
('+918292169192', 'SSF3305261'),
('+918521948319', 'SSF3602370'),
('+918754545488', 'SSF3464185'),
('+918556464994', 'SSF3192726'),
('+918343587680', 'SSF3531803'),
('+918249757975', 'SSF3632368'),
('+918852726464', 'SSF3595429'),
('+919693587764', 'SSF3612712'),
('+919156765770', 'SSF3449834'),
('+919508382647', 'SSF2741134'),
('+919214532145', 'SSF3308061'),
('+919142242959', 'SSF3669886'),
('+919319026914', 'SSF3919520'),
('+919179871471', 'SID951375046017'),
('+919521445221', 'SSF3308059'),
('+919978840040', 'SSF3573349'),
('+919295595046', 'SSF3227458'),
('+919632428769', 'SSF3496276'),
('+919155178521', 'SSF3610581'),
('+919764944673', 'SID951374240114'),
('+916235412357', 'SID951375083953'),
('+919153159360', 'SID951375766525'),
('+919905529789', 'SSF2896082'),
('+919934339169', 'SID951373515703'),
('+916367702557', 'SSF3922052'),
('+916846645549', 'SSF3739037'),
('+917488396697', 'SSF3732799'),
('+917645008699', 'SSF3855972'),
('+917999253045', 'SSF4216825'),
('+917061001634', 'SSF5227856'),
('+918084392825', 'SSF3977361'),
('+918252501980', 'SSF3185037'),
('+919602451407', 'SSF4184187'),
('+919304731607', 'SSF4179129'),
('+919345494544', 'SSF3557142'),
('+919431518492', 'SSF3669522'),
('+919102494345', 'SSF5742547'),
('+916205162685', 'SSF3249003'),
('+916299882135', 'SSF3202939'),
('+916367605476', 'SSF5121635'),
('+917067883712', 'SSF3477726'),
('+917977977647', 'SSF3210098'),
('+917762821471', 'SSF3426845'),
('+917739556960', 'SSF3167121'),
('+917792286928', 'SSF3207386'),
('+918795412650', 'SSF3273327'),
('+918589494659', 'SSF3300043'),
('+918118838332', 'SSF3316099'),
('+918249648497', 'SSF3376346'),
('+918248484648', 'SSF3367927'),
('+919934735233', 'SSF3788270'),
('+919179435309', 'SSF3477727'),
('+919801589599', 'SSF3516551'),
('+919905559678', 'SSF3572747'),
('+919460164158', 'SSF3181092'),
('+919234627075', 'SSF3304626'),
('+919621446622', 'SSF3507738'),
('+919939800473', 'SSF3183182'),
('+919695231852', 'SID951375755834'),
('+919142508673', 'SSF3288699'),
('+919576814850', 'SSF3339167'),
('+918409160719', 'SSF5113518'),
('+919155011630', 'SSF5338751'),
('+917070953094', 'SSF4887783'),
('+918082254339', 'SSF4839853'),
('+919565092346', 'SSF5024192'),
('+918084815341', 'SSF4807389'),
('+917370920704', 'SSF4359508'),
('+916204828556', 'SSF3575416'),
('+917351386033', 'SSF3855704'),
('+919915697230', 'SSF2332543'),
('+919784299650', 'SSF2769589'),
('+917056497803', 'SID951376174932'),
('+919117752755', 'SSF3542071'),
('+918252111740', 'SSF2723029'),
('+919199313071', 'SSF3326718'),
('+916200279844', 'SID951373250026'),
('+917742767894', 'SSF3665253'),
('+917318301275', 'SSF3546855'),
('+918396020818', 'SID951376015617'),
('+919024852827', 'SSF3432807'),
('+919351078098', 'SSF3336181'),
('+919619834738', 'SSF2732698'),
('+918454232578', 'SSF3058758'),
('+918235811452', 'SSF3202058'),
('+919219042005', 'SSF3080301'),
('+919570586878', 'SID951374691326'),
('+919535965656', 'SSF3049226'),
('+919631258999', 'SSF3239008'),
('+918709682170', 'SSF3251642'),
('+919835830828', 'SSF3164356'),
('+917946464534', 'SSF3056311'),
('+919794578737', 'SSF3171398'),
('+916378467617', 'SSF2713928'),
('+916350782419', 'SSF3328270'),
('+918235237738', 'SSF3400130'),
('+917024868541', 'SSF2775099'),
('+919616538246', 'SSF3410324'),
('+919325584643', 'SSF2980790'),
('+918555843699', 'SSF2761333'),
('+919485706472', 'SSF3239894'),
('+918252570232', 'SSF3406474'),
('+919812145330', 'SSF2670184'),
('+919569733548', 'SSF2732634'),
('+919702719025', 'SSF3483995'),
('+919414157089', 'SSF2684094'),
('+917654700846', 'SSF3364408'),
('+917070869065', 'SSF2335135'),
('+919856746865', 'SSF2788909'),
('+919576628792', 'SSF2723265'),
('+918797906183', 'SSF2874754'),
('+916378612499', 'SSF2732896'),
('+916376847644', 'SSF2745045'),
('+919983254238', 'SSF2810130'),
('+916202327414', 'SSF2940128'),
('+918235546170', 'SSF2901505'),
('+919856755685', 'SSF2930210'),
('+919975466162', 'SSF2792869'),
('+917282034691', 'SSF2602001'),
('+918359359669', 'SSF2867658'),
('+917891924789', 'SSF2715515'),
('+919997997979', 'SSF2715516'),
('+919797787804', 'SSF3478427'),
('+916268289505', 'SID951376111924'),
('+917859624088', 'SSF3883761'),
('+917999896590', 'SSF3878637'),
('+918252210063', 'SSF4299239'),
('+919516948279', 'SSF3615222'),
('+919461217020', 'SSF5871411'),
('+919598583730', 'SSF6194379'),
('+917354282989', 'CID043201828'),
('+917023912010', 'SSF5333707'),
('+919983725929', 'SSF5578038'),
('+918769204252', 'SSF3554090'),
('+919467654436', 'SSF6274437'),
('+919570170841', 'SSF6061624'),
('+916361224313', 'SSF4794954'),
('+917604840976', 'SSF5818927'),
('+919661903123', 'SSF5094050'),
('+916396302917', 'SSF6398762'),
('+919262809608', 'SSF5700549'),
('+917541058517', 'SSF5908478'),
('+919140180510', 'SSF5699926'),
('+918756877680', 'SSF5465107'),
('+917294915702', 'SSF5137116'),
('+919523478176', 'SSF5713927'),
('+918521846647', 'SSF5603272'),
('+918603392691', 'SSF6247140'),
('+918696058604', 'SID951374376742'),
('+919817867909', 'SSF5552897'),
('+917895763452', 'SSF5827208'),
('+919142548500', 'SSF6001099'),
('+919368004356', 'SSF3931799'),
('+917488524543', 'SSF5842425'),
('+919258820408', 'SSF5986021'),
('+917766828844', 'SSF5393722'),
('+918305613698', 'SID951373428016'),
('+919570152191', 'SID951375547380'),
('+916265586929', 'SID951374561815'),
('+917408283134', 'SSF6022363'),
('+918999085627', 'SSF6223046'),
('+919950234936', 'SSF5121750'),
('+919199058202', 'SSF5776470'),
('+916350121416', 'SID951374849307'),
('+918319602141', 'SID951374908110'),
('+919102297747', 'SSF5465912'),
('+919153899905', 'SSF5224401'),
('+918003747149', 'SSF3961811'),
('+919993923347', 'CID218100430'),
('+918955198013', 'SID951375200663'),
('+919737575458', 'SID951374887930'),
('+917778951343', 'SID951374539595'),
('+917970117274', 'SID951373723125'),
('+917304122744', 'SID951374959661'),
('+919216732134', 'SID951374321764'),
('+918797316228', 'SSF5585613'),
('+919098577145', 'SID951375354825'),
('+917257865761', 'SSF5544647'),
('+918409322144', 'SSF3992893'),
('+919525928834', 'SSF5580983'),
('+919534716227', 'SSF4628793'),
('+919343915406', 'SSF5208324'),
('+918699422481', 'SSF5738815'),
('+916260294854', 'SSF2538681'),
('+919770326152', 'SSF3740052'),
('+919693493955', 'SSF3999736'),
('+917488023960', 'SSF5637770'),
('+918305429102', 'SID951374861209'),
('+917970694915', 'SSF5818713'),
('+919999999999', 'SID951376247972'),
('+916268996082', 'SID951373057618'),
('+918000788748', 'SSF5143891'),
('+919352883866', 'SID951375482216'),
('+919098256652', 'SID951374157778'),
('+919334742302', 'SSF5666761'),
('+919977974516', 'SID951376201527'),
('+919238275680', 'SSF2609211'),
('+918586048123', 'SSF4128172'),
('+917805066185', 'SSF2292071'),
('+917762834636', 'SSF5450098'),
('+919219045768', 'SSF5237091'),
('+918435765982', 'SID951374502407'),
('+918824602390', 'SSF4758231'),
('+918294053767', 'SSF3555027'),
('+916263228690', 'SID951374561299'),
('+919856644569', 'SID951375991269'),
('+919535488878', 'SSF2976995'),
('+918400337388', 'SID951374573539'),
('+918102844012', 'SSF5676765'),
('+917389269377', 'SID2125251185'),
('+919748759607', 'CID171506978'),
('+918889445715', 'SSF4333989'),
('+917826513185', 'SID2125557460'),
('+917753879812', 'SSF5231779'),
('+917693836353', 'CID219000886'),
('+919973345214', 'CID204501922'),
('+918115305763', 'SSF5840710'),
('+918302329087', 'SSF5349385'),
('+919956910275', 'SSF6306401'),
('+919508946859', 'SSF6221308'),
('+918789767419', 'SSF2317801'),
('+919752663392', 'SID951372962664'),
('+917644915984', 'SSF4320008'),
('+918959987279', 'SID951373608880'),
('+919559531948', 'SSF6074975'),
('+919080226428', 'SSF5833295'),
('+917870429753', 'SSF5755238'),
('+918429684833', 'SSF6237339'),
('+917880540796', 'SSF4989473'),
('+917088231994', 'SSF3800732'),
('+919507051827', 'SSF5285312'),
('+918602286107', 'SID951375170891'),
('+917409708597', 'SSF5679275'),
('+917492862940', 'SSF6396271'),
('+917795790453', 'SSF5478483'),
('+917209454493', 'SSF5661914'),
('+917004342972', 'SSF6332404'),
('+918084001038', 'SSF5062421'),
('+919031506622', 'SSF5320147'),
('+919422057239', 'SSF5380975'),
('+918797317567', 'SSF5691983'),
('+919320648186', 'SSF5260258'),
('+918869955555', 'SID951375728170'),
('+917509032542', 'SSF3936973'),
('+917050967470', 'SSF5736522'),
('+917986325785', 'SSF5467123'),
('+919799902379', 'SSF5728540'),
('+918218623391', 'SSF5202756'),
('+918294706857', 'SSF6190338'),
('+918120523806', 'SID951375043731'),
('+919996685486', 'SSF3428088'),
('+917877899629', 'SSF5279418'),
('+919779638740', 'SSF5315329'),
('+919559589843', 'SSF4210543'),
('+919779835418', 'SSF6152691'),
('+917257862475', 'SSF5034575'),
('+919569048670', 'SSF3397581'),
('+917633829886', 'SSF6105430'),
('+917991485517', 'SSF6240093'),
('+918053609613', 'SSF6004087'),
('+919534454972', 'SSF5271925'),
('+916201031872', 'SSF5282108'),
('+918290572785', 'SID951375416550'),
('+919303598884', 'CID135301745'),
('+917383358237', 'SSF5664606'),
('+917500571199', 'SSF5220458'),
('+919368711988', 'SSF4449125'),
('+917389363725', 'SID951373375611'),
('+919304153275', 'SSF4096475'),
('+917371050354', 'SSF5542774'),
('+918757533572', 'SSF5531908'),
('+919155907100', 'SSF2604725'),
('+919145235532', 'SSF6117572'),
('+917974911381', 'SID951375524355'),
('+919009476444', 'CID118111010'),
('+917022485548', 'SSF5551873'),
('+919329983876', 'SSF3613092'),
('+919263250551', 'SSF2617479'),
('+917804937207', 'SID951375979384'),
('+917545991272', 'SSF5700120'),
('+917340205097', 'SSF4556430'),
('+917209895690', 'SSF6248804'),
('+919691621392', 'SSF3608135'),
('+919977320305', 'CID069706727'),
('+918303648072', 'SID951376071529'),
('+917970815535', 'SSF5005563'),
('+917484060604', 'SSF5477334'),
('+918678859629', 'SSF6002820'),
('+919322625079', 'SSF4607360'),
('+919519370111', 'SSF6128910'),
('+919262301782', 'SSF6384898'),
('+919685183245', 'SSF4025814'),
('+917084913428', 'SSF5803988'),
('+918827305102', 'SSF3498013'),
('+916283606553', 'SSF4504317'),
('+919610118927', 'SSF4007814'),
('+919755561871', 'SSF5289571'),
('+919827773513', 'SID951373720815'),
('+917079827023', 'SSF5235390'),
('+919576023101', 'SSF5776896'),
('+917351152693', 'SSF6254293'),
('+917089603995', 'SID951373022677'),
('+916206768663', 'SSF5473258'),
('+918789204014', 'SID951375525949'),
('+919241164571', 'SSF6127839'),
('+917747951392', 'SID951374604270'),
('+917463080527', 'SID951375381128'),
('+917542980342', 'SSF5428525'),
('+919399919494', 'SID951374074922'),
('+919770549886', 'SID951373228514'),
('+918797168918', 'SSF5398958'),
('+917479983042', 'SSF5980517'),
('+917050759059', 'SSF4863169'),
('+919875661823', 'SSF2617862'),
('+916206782066', 'SSF5811245'),
('+918969107544', 'SSF4777624'),
('+917857952215', 'SSF4657864'),
('+917480063364', 'SSF5548324'),
('+918085631696', 'SSF5340556'),
('+918558598828', 'SID951374063878'),
('+919523317165', 'SSF2881834'),
('+919012585611', 'SSF5753284'),
('+918965966845', 'SID951373867801'),
('+919589146414', 'SID951375971225'),
('+919263218324', 'SSF2396580'),
('+919977116971', 'SSF5989470'),
('+917800028158', 'SSF6272999'),
('+919546261078', 'SSF5291989'),
('+919162342817', 'SID951375332121'),
('+919889696220', 'SSF4821956'),
('+917061409217', 'SSF5708470'),
('+918853061159', 'SSF5977380'),
('+916389646056', 'SSF2602737'),
('+919351377396', 'SID951375415968'),
('+917045369582', 'SSF4057579'),
('+918235846101', 'SSF5477612'),
('+919580182991', 'SSF4994764'),
('+916307989652', 'SSF6332967'),
('+917493830293', 'SSF5663355'),
('+919517590817', 'SSF2596020'),
('+918328116691', 'SSF3067211'),
('+918423627731', 'CID212301754'),
('+917905641766', 'SSF5566830'),
('+917634027026', 'SSF5718402'),
('+918051798504', 'SSF5792101'),
('+917762046187', 'SID951375992502'),
('+919500964236', 'SSF5265175'),
('+918817446869', 'SSF5275821'),
('+918696704662', 'SID951375393717'),
('+919799556627', 'SSF5455674'),
('+919770423525', 'SSF5033044'),
('+919171134540', 'SID951373304493'),
('+918294405988', 'SSF6411627'),
('+918815325834', 'SID951373271303'),
('+916206170856', 'SSF6105076'),
('+917309724668', 'SSF2491513'),
('+919835615976', 'SSF2838626'),
('+919693085737', 'SSF5756293'),
('+919403036390', 'SID951375551655'),
('+917763849389', 'SSF5687425'),
('+917828286699', 'SID951375936288'),
('+919098336986', 'SSF3214360'),
('+918540086577', 'SSF4213252'),
('+918294751703', 'SSF4301045'),
('+917463836532', 'SSF4898853'),
('+918700438165', 'SSF4244772'),
('+919234613386', 'SSF4983673'),
('+919263639203', 'SID951375783292'),
('+919416655767', 'SID951374953466'),
('+919572927176', 'SID951376187732'),
('+919009764733', 'SID951375890724'),
('+916201974682', 'SSF4082977'),
('+917367880884', 'SSF4056304'),
('+917362826387', 'SSF3052333'),
('+917294981318', 'SSF4018701'),
('+917073966960', 'SSF4048086'),
('+917023245987', 'SSF2503694'),
('+917763995923', 'SSF4390924'),
('+917506872967', 'SID951374068772'),
('+918815554299', 'SSF4798569'),
('+918863024591', 'SSF4037753'),
('+918739918463', 'SSF3808450'),
('+918709516354', 'SSF3621955'),
('+918294809178', 'SSF4303477'),
('+918603350638', 'SSF5178566'),
('+918767284911', 'SSF3941992'),
('+918002502680', 'SSF3947471'),
('+918800214566', 'SID951375984392'),
('+918955087078', 'SSF4298360'),
('+918114076910', 'SSF2804126'),
('+918107773401', 'SID951375997620'),
('+918073673749', 'SSF4053827'),
('+918982821252', 'SSF4044664'),
('+918409626562', 'SSF4000633'),
('+919572212931', 'SSF4061748'),
('+919122364215', 'SSF3958369'),
('+919685988000', 'SSF3604157'),
('+919685475809', 'SSF3630300'),
('+919565444211', 'SSF3028788'),
('+919934600564', 'SSF3747352'),
('+919509213389', 'SSF3801351'),
('+919616165676', 'SSF3783934'),
('+919523259935', 'SSF3976720'),
('+919798741355', 'SSF3976721'),
('+919264262268', 'SSF4043941'),
('+917463982196', 'SSF5044060'),
('+917275438370', 'SSF4639518'),
('+918081763017', 'SSF4289807'),
('+919279767719', 'SSF4887189'),
('+919973070108', 'SSF4996084'),
('+919241158541', 'SSF4845330'),
('+919264974231', 'SSF4961089'),
('+919044180721', 'SSF4664463'),
('+917318034813', 'SSF4080410'),
('+917484874788', 'SSF4954689'),
('+919905118411', 'SSF4877309'),
('+917500384556', 'SSF4992154'),
('+917054357610', 'SSF4813685'),
('+917068527012', 'SSF5227317'),
('+918534097148', 'SSF5263858'),
('+918427696372', 'SSF5113445'),
('+919536653865', 'SSF5686897'),
('+919667646985', 'SSF5820775'),
('+917903994743', 'CID212404680'),
('+916265140959', 'SSF3609159'),
('+916200098663', 'SSF4567818'),
('+916204543613', 'SSF4072787'),
('+916239217255', 'SSF3875543'),
('+917649494849', 'SSF3609770'),
('+917491896536', 'SSF3308978'),
('+917321076828', 'SSF3754266'),
('+917654358548', 'SSF3464892'),
('+917667542971', 'SSF4030043'),
('+917418686569', 'SSF3886347'),
('+917415882699', 'SSF3884821'),
('+917675768794', 'SSF3559742'),
('+917739276288', 'SSF3857657'),
('+917748935554', 'SSF3754186'),
('+917979066980', 'SSF4186782'),
('+918527545817', 'SSF3756265'),
('+918002803152', 'SSF3852047'),
('+918969738189', 'SID951376105526'),
('+918252326267', 'SSF4595402'),
('+918910706528', 'SSF3916014'),
('+918292481095', 'SSF4323752'),
('+918890608625', 'SSF3904186'),
('+919343446867', 'SSF3609168'),
('+919109848159', 'SSF4061665'),
('+919263429296', 'SSF4563424'),
('+919825465659', 'SSF3876811'),
('+919539844655', 'SSF3705340'),
('+919784649797', 'SSF3741024'),
('+919798044465', 'SSF4323010'),
('+919065835365', 'SSF3380314'),
('+919934985497', 'SSF3818507'),
('+919876546352', 'SID951375295570'),
('+919446488478', 'SSF3639409'),
('+919770088183', 'SSF4875879'),
('+919263501479', 'SSF3938750'),
('+919798836037', 'SSF3882605'),
('+919876868986', 'SSF3650941'),
('+916388009317', 'SSF4375177'),
('+919588537560', 'SSF5577894'),
('+917992448027', 'SSF4842222'),
('+918009641990', 'SSF4812665'),
('+918434620849', 'SSF4862687'),
('+916233385321', 'SSF3430196'),
('+918796767878', 'SSF3684019'),
('+918678025617', 'SSF3395153'),
('+919354546646', 'SSF3412543'),
('+919752603344', 'SSF4086285'),
('+917318373046', 'SSF4152235'),
('+917644043618', 'SID951376120763'),
('+917372082687', 'SSF4418438'),
('+917974137093', 'SSF4084227'),
('+918757929373', 'SSF4060616'),
('+919638525786', 'SSF3845594'),
('+919135079811', 'SSF4315553'),
('+917897184533', 'SSF4004515'),
('+919771687227', 'SSF4719092'),
('+919153690078', 'SSF4780652'),
('+918115661925', 'SSF4419716'),
('+916286797689', 'SSF3677030'),
('+916261253133', 'SSF3460877'),
('+916296564994', 'SSF2728565'),
('+916288359539', 'SSF3373102'),
('+916284645625', 'SSF2889811'),
('+916206407311', 'SSF3255548'),
('+916002362577', 'SSF3222543'),
('+916386633417', 'SSF2854421'),
('+916494643161', 'SSF3427410'),
('+916268005866', 'SSF3482452'),
('+916375649008', 'SSF3497401'),
('+916264699267', 'SSF4010819'),
('+916368019754', 'SSF3789231'),
('+916208589130', 'SSF3457149'),
('+916289063590', 'SID2125393712'),
('+917209086355', 'SSF3164033'),
('+917070621866', 'SSF3814888'),
('+917850930241', 'SSF3982965'),
('+917542865493', 'SSF4064301'),
('+917856049102', 'SSF3190097'),
('+917061500036', 'SSF3246449'),
('+917366998471', 'SID951376152827'),
('+917489137553', 'SSF3811761'),
('+917282471585', 'SSF3499544'),
('+917033649215', 'SSF3468149'),
('+917070330212', 'SSF3672127'),
('+917255035393', 'SSF3154463'),
('+917879190665', 'SSF3980918'),
('+918092602957', 'SSF3258996'),
('+918235574188', 'SSF3375156'),
('+918797730248', 'SSF3639348'),
('+918201065014', 'SSF3639383'),
('+918949130164', 'SSF2595869'),
('+918659494846', 'SSF3820318'),
('+918797952914', 'SSF3351365'),
('+918756023101', 'SSF2675307'),
('+918002332912', 'SSF3336168'),
('+918809774013', 'SSF3639998'),
('+918455581605', 'SSF3356295'),
('+918572425825', 'SSF3490673'),
('+919345946480', 'SSF3798822'),
('+919343347117', 'SSF4094335'),
('+919798974386', 'SSF3338577'),
('+919693002398', 'SSF3250422'),
('+919536535566', 'SSF3112928'),
('+919122623809', 'SSF2801441'),
('+919587878464', 'SSF3395954'),
('+919312548707', 'SSF3483975'),
('+919846548484', 'SID951375247463'),
('+919302608102', 'SSF2600560'),
('+919688555554', 'SSF3155314'),
('+919341162220', 'SSF3269257'),
('+919464661616', 'SID951373183079'),
('+919955131961', 'SSF3145784'),
('+919707648797', 'SSF3547646'),
('+919155485453', 'SSF3484067'),
('+919503438895', 'SSF3357942'),
('+919279825684', 'SSF3430792'),
('+919801936199', 'SSF3489072'),
('+919669850205', 'SSF3498942'),
('+919464848784', 'SID951376156747'),
('+919044142610', 'SSF3474094'),
('+916377932384', 'SSF3906906'),
('+917644003751', 'SSF4328395'),
('+918354056428', 'SSF4037221'),
('+916203284311', 'SSF3836101'),
('+916299214458', 'SSF3195186'),
('+916266700600', 'SSF3510313'),
('+916202988736', 'SSF3100793'),
('+916284687787', 'SID951375130299'),
('+917849975047', 'SSF3168095'),
('+917646737846', 'SSF3057604'),
('+917919499855', 'SSF3701933'),
('+917870764694', 'SSF3411912'),
('+917354056570', 'SSF3669484'),
('+917634064566', 'SSF3513116'),
('+917727921212', 'SSF3643043'),
('+917209684490', 'SSF2677309'),
('+917294032879', 'SSF2975714'),
('+917667914434', 'SSF3044802'),
('+917754087125', 'SSF3478112'),
('+918303283310', 'SSF2548421'),
('+918441897677', 'SSF3254083'),
('+918092504522', 'SSF2588959'),
('+918287019518', 'SSF2784592'),
('+918824578738', 'SSF3125628'),
('+918495959598', 'SSF2361926'),
('+918694987990', 'SID951375920382'),
('+918292183281', 'SSF3732001'),
('+918646543979', 'SSF3476064'),
('+919824778688', 'SSF3463770'),
('+919349536949', 'SSF3665211'),
('+919658034730', 'SSF3120522'),
('+919098521478', 'SSF3149999'),
('+919631589631', 'SID951375760805'),
('+919786186466', 'SSF3312572'),
('+919264171191', 'SSF3156079'),
('+919329336453', 'SSF3169715'),
('+919983522552', 'SSF3166174'),
('+919065652916', 'SID951375421649'),
('+919564694676', 'SSF3368185'),
('+919835358185', 'SSF3334983'),
('+919931411583', 'SSF3313439'),
('+917482946017', 'SSF5117465'),
('+919726554663', 'SSF4954905'),
('+919006699157', 'SSF5277189'),
('+916203932273', 'SSF5004745'),
('+917814762863', 'SSF5047703'),
('+919693370718', 'SSF5443861'),
('+917543099332', 'SSF5018856'),
('+919118371203', 'SSF4129868'),
('+919903333773', 'SSF4425262'),
('+916398909651', 'SSF5749465'),
('+917088585783', 'SSF5454301'),
('+918090759905', 'SSF4810628'),
('+918676870811', 'SSF4971468'),
('+919057984005', 'SSF5473817'),
('+919350165277', 'SSF4970593'),
('+918688387512', 'SSF5013136'),
('+919140064864', 'SSF4645218'),
('+917367875824', 'SSF4895023'),
('+919811587219', 'SSF4216518'),
('+919464694949', 'SSF3331069'),
('+919163882752', 'SSF3609578'),
('+917249771255', 'SSF4024286'),
('+919798332574', 'SSF3986895'),
('+919831854329', 'SSF3516704'),
('+919846490464', 'SSF3629259'),
('+919279285710', 'SID951376015277'),
('+916388840015', 'SSF3999527'),
('+917068675988', 'SSF4036706'),
('+919907137764', 'SSF4937526'),
('+919660575561', 'SSF4061746'),
('+916377231539', 'SSF4031602'),
('+919157418400', 'SSF4029353'),
('+919006131552', 'SSF3168708'),
('+919664613161', 'SSF3433696'),
('+919602185880', 'SID951375894483'),
('+919754843131', 'SSF3701436'),
('+919658713324', 'SSF3133369'),
('+919546975759', 'SID951376009696'),
('+918540089103', 'SSF3449966'),
('+919279178369', 'SSF2298058'),
('+917742453857', 'SSF3609888'),
('+918302341544', 'SSF4073558'),
('+918923346767', 'SSF3174338'),
('+917305903254', 'SSF3518494'),
('+916454846487', 'SSF3640327'),
('+918224903086', 'SSF3781936'),
('+916256874578', 'SSF3482342'),
('+918698068989', 'SSF3459359'),
('+917867687981', 'SSF3336395'),
('+917056081266', 'SSF2713288'),
('+919678754840', 'SSF3189714'),
('+918865545855', 'SSF2852673'),
('+919668125865', 'SSF2890884'),
('+918764986484', 'SSF2878970'),
('+918565455589', 'SSF2964689'),
('+916202404119', 'SSF3452689'),
('+916205776045', 'SSF2730564'),
('+919737496446', 'SID951375086599'),
('+917808025681', 'SSF3113582'),
('+919354264815', 'SSF3099164'),
('+917232891735', 'SSF2683828'),
('+917494880364', 'SSF2678490'),
('+919128727874', 'SSF2989836'),
('+917747002163', 'SSF2834115'),
('+916375356636', 'SSF2752309'),
('+919123464548', 'SSF2883734'),
('+918227960072', 'SSF2863556'),
('+919350259673', 'SSF2924159'),
('+916379798959', 'SSF3387709'),
('+917934979767', 'SSF2464110'),
('+918634297768', 'SSF2742284'),
('+917376692023', 'SSF3119648'),
('+917470349519', 'SSF3620886'),
('+918319326817', 'SSF3665070'),
('+919691965282', 'SSF3665069'),
('+919131455982', 'SSF3620887'),
('+916201785675', 'SSF4037683'),
('+916203037240', 'SSF3791420'),
('+917295936601', 'SSF4053581'),
('+917367024014', 'SSF4061766'),
('+917806052712', 'SSF4059001'),
('+917462021749', 'SSF4573238'),
('+918319244025', 'SSF4061792'),
('+918543827074', 'SSF4187801'),
('+918467957181', 'SSF4197685'),
('+919793561626', 'SSF3796070'),
('+919685489598', 'SSF3598611'),
('+919767648454', 'SSF3442853'),
('+919685423808', 'SSF3611147'),
('+919931968880', 'SSF3611107'),
('+916203433938', 'SSF4891790'),
('+917992008826', 'SSF4948384'),
('+917985783802', 'SSF4241243'),
('+917800585226', 'SSF5025600'),
('+919140368480', 'SSF5620754'),
('+916265283465', 'SSF3671678'),
('+916208537998', 'SSF3842254'),
('+916207937289', 'SSF3780251'),
('+916205751203', 'SSF3217369'),
('+916205986863', 'SSF3866927'),
('+916206597683', 'SSF3827742'),
('+916648979979', 'SSF3149549'),
('+916201048192', 'SSF3873647'),
('+917081660241', 'SSF3727592'),
('+917697528681', 'SSF4058725'),
('+917321014475', 'SSF4595401'),
('+918102394945', 'SSF4208211'),
('+918969597192', 'SSF3876826'),
('+918423135398', 'SSF3586662'),
('+918882645959', 'SSF3820912'),
('+918789851137', 'SSF3580773'),
('+918797387334', 'SSF3888839'),
('+918340236591', 'SSF3675010'),
('+918210216663', 'SSF3349547'),
('+919108034612', 'SSF4574822'),
('+919767576764', 'SSF3542670'),
('+919140264648', 'SSF3497650'),
('+919608803790', 'SSF3848637'),
('+919508535985', 'SSF3928843'),
('+919691608040', 'SSF4103687'),
('+919279374250', 'SSF4330649'),
('+919006178105', 'SSF3748745'),
('+919664340263', 'SSF3907441'),
('+919163410633', 'SSF4059233'),
('+919994944949', 'SSF3802919'),
('+919785262681', 'SSF3612277'),
('+918847216053', 'SSF4795832'),
('+919821858904', 'SSF5658605'),
('+919792886810', 'SSF4793426'),
('+916233523666', 'SSF3395338'),
('+917970879533', 'SSF3430243'),
('+918085494994', 'SSF3640771'),
('+918797251264', 'SSF3539866'),
('+919341638557', 'SSF3367665'),
('+917410502968', 'SSF4911320'),
('+917752921823', 'SSF4220418'),
('+917737623795', 'SSF4314059'),
('+917726872130', 'SSF4277347'),
('+917869074454', 'SSF4167882'),
('+918969379423', 'SSF4232182'),
('+918904950625', 'SSF4133719'),
('+919263170940', 'SSF4416309'),
('+919931657754', 'SSF4172079'),
('+919065878920', 'SSF4191313'),
('+917814866209', 'SSF4475785'),
('+916201164596', 'SSF3539436'),
('+916205625693', 'SSF3462300'),
('+916205625369', 'SSF3462337'),
('+916262656595', 'SID951376192623'),
('+916206634068', 'SSF3212202'),
('+916574456887', 'SSF3376109'),
('+916644694646', 'SSF3245529'),
('+916210932700', 'SSF3189947'),
('+916254354878', 'SSF3555102'),
('+917320906038', 'SSF3237965'),
('+917023888309', 'SSF3394317'),
('+917481979565', 'SSF3380348'),
('+917544054419', 'SSF4208366'),
('+917643914805', 'SSF3623284'),
('+917610642168', 'SID951374713243'),
('+918809339889', 'SSF3794973'),
('+918092391229', 'SSF3902629'),
('+918092907904', 'SSF3173552'),
('+918775976949', 'SSF3697778'),
('+918809824654', 'SSF3616119'),
('+918521173253', 'SSF3606587'),
('+918287036613', 'SSF3338757'),
('+918767764646', 'SSF3369587'),
('+918541040689', 'SSF3193679'),
('+918102457998', 'SSF3386054'),
('+918754213956', 'SSF3489073'),
('+918797251353', 'SSF3612371'),
('+918755688888', 'SSF3435019'),
('+919006156889', 'SSF3694401'),
('+919464688875', 'SSF3685244'),
('+919303518570', 'SID951376011566'),
('+919661782078', 'SSF3462438'),
('+919131247966', 'SSF3659658'),
('+919803324225', 'SID951375825443'),
('+919905227829', 'SID951374369717'),
('+919704948484', 'SSF3334337'),
('+919808658858', 'SSF3373603'),
('+919721812787', 'SSF3228763'),
('+919886082689', 'SSF3353865'),
('+919733154357', 'SSF3803938'),
('+919985588585', 'SSF3706615'),
('+919691897659', 'SSF3421392'),
('+919661334575', 'SSF2803567'),
('+919634584876', 'SSF3470887'),
('+919646548487', 'SSF3462338'),
('+919688547775', 'SSF3433050'),
('+919667878678', 'SSF3462274'),
('+919708762834', 'SSF3194758'),
('+919835948982', 'SSF3079040'),
('+919787644813', 'SSF3358424'),
('+919875463211', 'SSF3485836'),
('+919679876767', 'SSF3352602'),
('+919608478374', 'SSF3366697'),
('+919898656569', 'SSF3500012'),
('+919341566864', 'SSF3291642'),
('+919044142619', 'SSF3466613'),
('+917808815952', 'CID211100272'),
('+917667363909', 'SID951372956699'),
('+917999162017', 'SID951374985915'),
('+916239320500', 'SSF4341801'),
('+917004328087', 'SSF4033982'),
('+917970833979', 'SSF4426948'),
('+917000764761', 'SSF4392475'),
('+918271363320', 'SSF3045818'),
('+918224020040', 'SSF4071572'),
('+918839309918', 'SSF3752462'),
('+918292579296', 'SSF4513862'),
('+918077342723', 'SSF4043496'),
('+918409738007', 'SSF3943485'),
('+918595241294', 'SSF3973092'),
('+918434535906', 'SSF4315799'),
('+919279164186', 'SSF4374358'),
('+919905027022', 'SSF3126587'),
('+919229314173', 'SSF5270657'),
('+918092737096', 'SSF3853236'),
('+916367135856', 'SSF3467938'),
('+916206848659', 'SSF3809741'),
('+916852525225', 'SSF3395513'),
('+916201505114', 'SSF3569676'),
('+916294989499', 'SSF3327847'),
('+916201777839', 'SSF3089395'),
('+916245849438', 'SSF3034596'),
('+916235689558', 'SSF3254060'),
('+916208486797', 'SSF2603546'),
('+916287944860', 'SSF3255413'),
('+917888430351', 'SID951374111929'),
('+917050884279', 'SSF3382706'),
('+917068455621', 'SSF3438200'),
('+917686866666', 'SSF3351960'),
('+917634039359', 'SSF3140419'),
('+917887498797', 'SSF3131087'),
('+917858963834', 'SSF3140281'),
('+917004172058', 'SSF3295081'),
('+918107825585', 'SSF3102815'),
('+918003206983', 'SSF3722451'),
('+918855686647', 'SID951373869669'),
('+918673643679', 'SSF3337471'),
('+918511819172', 'SSF3356858'),
('+918690547541', 'SSF3973565'),
('+918889092098', 'SID951375042210'),
('+918409105034', 'SSF3455155'),
('+918292143469', 'SSF3424260'),
('+918825364420', 'SSF3088871'),
('+918310378558', 'SSF3211683'),
('+919854122555', 'SSF3458423'),
('+919199456410', 'SSF3238052'),
('+919564985656', 'SSF3155265'),
('+919263185265', 'SSF2496474'),
('+919987112884', 'SSF3193139'),
('+919263643524', 'SSF3516271'),
('+919670915001', 'SSF3367761'),
('+919649875749', 'SSF3425817'),
('+919535935653', 'SSF3139732'),
('+919635286484', 'SSF3065151'),
('+919507499327', 'SSF3604964'),
('+919651068060', 'SSF3290086'),
('+919784534617', 'SSF3305299'),
('+919153038887', 'SSF3454064'),
('+917479443294', 'SSF5270604'),
('+918168357062', 'SSF5323525'),
('+918299630267', 'SSF4583915'),
('+918862845201', 'SSF5442958'),
('+918859965876', 'SSF5749050'),
('+918127971068', 'SSF4648683'),
('+919835616122', 'SSF5016764'),
('+917546808384', 'SSF4813289'),
('+917671913542', 'SID951376238648'),
('+917321800632', 'SSF2780424'),
('+918302027739', 'SSF4285928'),
('+919846499565', 'SSF3516723'),
('+919842563221', 'SSF3743418'),
('+916268653835', 'SSF2771002'),
('+919521811042', 'SSF3810950'),
('+919262638403', 'SSF3280257'),
('+919658975689', 'SSF3371931'),
('+919608450995', 'SSF4566662'),
('+919965524478', 'SSF3148077'),
('+918690817563', 'SSF2675237'),
('+918546448464', 'SSF3467436'),
('+918148874500', 'SSF3402775'),
('+919966521478', 'SSF3604730'),
('+919654335621', 'SSF2897125'),
('+918318016418', 'SSF2771811'),
('+919058429887', 'SSF2857372'),
('+916299115174', 'SSF3099118'),
('+918092768113', 'SSF3013273'),
('+918120457869', 'SSF3324572'),
('+918764584645', 'SSF3230293'),
('+919306945663', 'SSF2497221'),
('+916205512713', 'SSF2939346'),
('+917737621998', 'SSF2827627'),
('+919692978227', 'SSF3740682'),
('+919772684031', 'SSF2901298'),
('+917739098050', 'SSF3048594'),
('+917258042123', 'SSF3170347'),
('+918865866589', 'SSF2860319'),
('+917231813697', 'SSF4071840'),
('+919928307738', 'SSF3993220'),
('+919708348488', 'SSF2830332'),
('+917967767767', 'SSF2647467'),
('+916377466926', 'SSF2930538'),
('+919661583761', 'SSF3184852'),
('+918578797675', 'SSF3014500'),
('+919166286044', 'SID951375779516'),
('+917000046465', 'SSF3619112'),
('+918821831109', 'SSF3619148'),
('+917493874992', 'SSF2985214'),
('+919798218857', 'SSF5339214'),
('+919617071885', 'CID070100697'),
('+919258771703', 'SSF5806421'),
('+917451945981', 'SSF6286050'),
('+919012741944', 'SSF5255615'),
('+917900342983', 'SSF6338541'),
('+919257614627', 'SSF2825438'),
('+917225842964', 'SSF5472831'),
('+916299141971', 'SSF5506589'),
('+916261782662', 'SSF4855136'),
('+917061897411', 'SSF5692261'),
('+919729612601', 'SSF5811418'),
('+919525336855', 'SSF5725835'),
('+918120903016', 'SSF5187237'),
('+917976944635', 'SSF5173738'),
('+919262503540', 'SSF5851343'),
('+917549762720', 'SSF6218817'),
('+917982443132', 'SSF5742133'),
('+918619109795', 'SSF3997523'),
('+917534841489', 'SSF6389371'),
('+918407845117', 'SSF5029639'),
('+918251091101', 'SSF3726996'),
('+919354235819', 'SSF5838472'),
('+919306407942', 'SSF5111786'),
('+919521308627', 'SSF4150307'),
('+917879477157', 'CID135107416'),
('+918252404906', 'SSF6435610'),
('+918935871729', 'SSF2847455'),
('+919845650342', 'SSF5666109'),
('+919955899042', 'SSF5732435'),
('+919335569260', 'SSF5248030'),
('+918969668820', 'SSF5465362'),
('+919918844292', 'SSF6259491'),
('+917990351686', 'SSF6102575'),
('+916268433573', 'SSF3754639'),
('+916207501527', 'SSF5723091'),
('+919508565510', 'SSF4556625'),
('+918000450245', 'SSF4290027'),
('+919116406644', 'SSF2616956'),
('+918858888986', 'SID951375419451'),
('+918102442680', 'SSF5684949'),
('+919079210819', 'SSF3246790'),
('+919328838824', 'SID951374517927'),
('+917250114604', 'SSF2403940'),
('+918521158558', 'SSF5852191'),
('+919667567411', 'SSF5452425'),
('+919608795534', 'SSF5441367'),
('+918092832013', 'SSF6258748'),
('+918340656281', 'SSF6378178'),
('+919653915614', 'SSF3318575'),
('+917759937034', 'SSF4784775'),
('+919929874147', 'SSF5047551'),
('+916388650394', 'SSF6317364'),
('+919120960758', 'SSF6300766'),
('+917007812657', 'SSF5073769'),
('+919109413193', 'SID36038'),
('+918873094452', 'SSF4896714'),
('+918931098825', 'SSF5226626'),
('+918807438847', 'SSF5782288'),
('+919709822978', 'SSF5674517'),
('+918871432705', 'SSF5166498'),
('+919546226074', 'SSF4667313'),
('+919097474685', 'SSF4000912'),
('+918890440219', 'SID951375772640'),
('+917060058134', 'SSF4688238'),
('+917428513146', 'SSF5409717'),
('+919136555989', 'SSF6344692'),
('+918209666896', 'SSF3913955'),
('+918400712132', 'SSF4020582'),
('+917667721302', 'SSF5851671'),
('+917226034637', 'SSF5640757'),
('+917898443330', 'CID093202847'),
('+917013562586', 'SSF3883010'),
('+919343207769', 'SID951373789756'),
('+919524695825', 'SID951375250309'),
('+919801138914', 'SSF4963583'),
('+917255070023', 'SSF5033613'),
('+917722981159', 'SSF4007176'),
('+919258713017', 'SSF5426110'),
('+917023758558', 'SSF4148329'),
('+917692053717', 'SSF5908383'),
('+919918107476', 'SSF2655253'),
('+916299557314', 'SSF2844708'),
('+918815237652', 'SSF4509568'),
('+917061766445', 'SSF5409395'),
('+919279852702', 'SSF2326380'),
('+917987640283', 'SID2125414068'),
('+917352037170', 'SID951375720520'),
('+916266983779', 'SSF4047407'),
('+918949436113', 'SSF5025343'),
('+916266929692', 'SID951373062554'),
('+919939095959', 'SSF4403049'),
('+918288094542', 'SSF5535824'),
('+919772458176', 'SID951374613463'),
('+919166675509', 'SSF2550485'),
('+918922911348', 'SSF2696030'),
('+917023205412', 'SID951375339842'),
('+917084966025', 'SSF5915656'),
('+919649965496', 'SID951374275764'),
('+919161023249', 'SSF5759651'),
('+918109906715', 'SSF6380859'),
('+918107081987', 'SSF2491023'),
('+917804806911', 'SSF5372417'),
('+918233315305', 'SID951374084358'),
('+918630113481', 'SSF5349223'),
('+919772135413', 'SSF5877846'),
('+918423886169', 'SSF5908669'),
('+918677931914', 'SSF5319270'),
('+919646454646', 'CID204900483'),
('+918210008918', 'SSF2376373'),
('+917748932393', 'SID951373892986'),
('+918307954760', 'SSF5724249'),
('+918260515230', 'SID951375505609'),
('+919982177228', 'SSF2565214'),
('+919584480066', 'SID2125676458'),
('+919244915730', 'SSF5969668'),
('+918235014582', 'SSF6007023'),
('+918840190384', 'SSF6042353'),
('+916200324261', 'SSF2622874'),
('+919009882323', 'SID951375795597'),
('+919905577188', 'SSF6396282'),
('+919102227224', 'SSF6142887'),
('+916287773534', 'SSF5480511'),
('+919675051755', 'SSF4103464'),
('+919155069181', 'SSF5686043'),
('+917440909371', 'SSF5495246'),
('+917489134735', 'SSF4394942'),
('+919098388807', 'SSF4395118'),
('+919643042519', 'SSF6077777'),
('+917453874664', 'SSF5125456'),
('+917635012870', 'SSF6073365'),
('+919131819810', 'SSF4768420'),
('+917870550148', 'SSF5142627'),
('+919631621859', 'SSF5555533'),
('+919279720438', 'SID951375395930'),
('+917060885077', 'SSF6451034'),
('+919301723445', 'SSF6388971'),
('+917632845164', 'SSF4938137'),
('+918409389812', 'SSF4625387'),
('+919955388923', 'SSF5805770'),
('+917715867852', 'SSF2544865'),
('+918521329195', 'SSF5224182'),
('+917372011097', 'SSF5805630'),
('+919977087812', 'SSF5473663'),
('+919235786564', 'SSF3693336'),
('+917023836170', 'SSF4354653'),
('+918541033474', 'SSF4553248'),
('+919157962881', 'SSF4044186'),
('+919120272462', 'SSF5866337'),
('+919588502119', 'SSF5252920'),
('+917880336383', 'SID951374236718'),
('+917082736265', 'SSF3510880'),
('+918459280251', 'SSF5368757'),
('+916868668656', 'SID951376171527'),
('+918881324503', 'SSF2988003'),
('+918690315979', 'SSF6369207'),
('+919801054148', 'SSF6393472'),
('+919153684739', 'SSF5725499'),
('+917542922263', 'SSF5632515'),
('+916388784511', 'SSF5704523'),
('+918755310493', 'SSF5834391'),
('+917351852767', 'SSF4932005'),
('+919102818100', 'SSF5555832'),
('+918320536843', 'SSF5080085'),
('+919472512730', 'SSF4362357'),
('+919565881890', 'SSF2680172'),
('+919065233839', 'SID951374536276'),
('+919508542389', 'SID951374741727'),
('+918002485363', 'SID951373482012'),
('+917587558856', 'SSF3373740'),
('+917366877223', 'SSF5487956'),
('+917070812839', 'SSF3174335'),
('+919767787576', 'SID951375204956'),
('+919301144673', 'SSF2471398'),
('+919098517369', 'SSF6273422'),
('+919990228359', 'SSF5521077'),
('+918516809780', 'SID951373410742'),
('+918360632993', 'SSF4160854'),
('+919155601245', 'SSF6423290'),
('+916395878484', 'SSF5756345'),
('+918305632195', 'SSF2456923'),
('+916394691192', 'SID951373072355'),
('+919650872443', 'SSF6097330'),
('+919065148155', 'SID951373963941'),
('+918544665535', 'SSF5353195'),
('+918298764111', 'SSF2573185'),
('+916203693196', 'SSF5531462'),
('+918529813941', 'SSF4238858'),
('+919098337652', 'SSF5004996'),
('+916201425936', 'SSF5477511'),
('+917387681703', 'SSF4122618'),
('+919753274264', 'SID2125636729'),
('+917209186232', 'SSF5768416'),
('+918084195920', 'SSF5853224'),
('+918581966912', 'SSF5134841'),
('+919016706240', 'SSF2402411'),
('+919663251448', 'SSF3130015'),
('+919060296526', 'SSF3047999'),
('+919009230594', 'SSF5149517'),
('+917461907682', 'SSF5154096'),
('+919272047801', 'SID951375907929'),
('+918128869713', 'SSF5818050'),
('+919373046513', 'SID951375256611'),
('+916204874998', 'SSF5957632'),
('+919520491356', 'SSF3740917'),
('+916260987796', 'SSF5838798'),
('+917463802145', 'SSF6008060'),
('+919142047368', 'SSF5679138'),
('+917209487915', 'SSF5817142'),
('+919343338273', 'SSF2786923'),
('+916205483942', 'SSF3886064'),
('+918092462803', 'SSF5698584'),
('+919044075404', 'SSF3303909'),
('+918081765598', 'SSF6251736'),
('+918966041429', 'SID951373170763'),
('+917645025591', 'SSF5714453'),
('+918057128148', 'SSF6399727'),
('+918958212135', 'SSF6356840'),
('+918431727069', 'SSF2415081'),
('+917079943446', 'SSF5478344'),
('+917547832556', 'SSF5122863'),
('+919685331989', 'SID951375191088'),
('+918864097764', 'SSF5106215'),
('+918009566568', 'SSF3280121'),
('+916264678631', 'SID951374309335'),
('+918081035044', 'SSF6286068'),
('+918521255477', 'SSF6328498'),
('+918235103781', 'SSF6331904'),
('+917558690314', 'SSF4757288'),
('+917999253052', 'SSF5329014'),
('+918817668833', 'SSF5319671'),
('+919256483322', 'SID951374788940'),
('+918862953816', 'SSF2693914'),
('+918210806174', 'SSF2554112'),
('+917870164340', 'SSF4399996'),
('+917292967934', 'SSF5543037'),
('+919528751195', 'SSF4393540'),
('+916203378484', 'SSF5139037'),
('+919151667576', 'SSF4470654'),
('+918521253070', 'SSF2332078'),
('+918825664483', 'SID951374427131'),
('+917724845814', 'SSF5732632'),
('+918651730047', 'SID951375693800'),
('+917209250018', 'SSF4878249'),
('+919934118207', 'SSF4612304'),
('+917073841438', 'SSF3423840'),
('+919955052081', 'SSF5147080'),
('+919829357956', 'SID951375955545'),
('+919131155055', 'SID951375083285'),
('+918052113877', 'SSF5789139'),
('+919199338945', 'SSF4441879'),
('+918393078084', 'SSF5684044'),
('+916263009082', 'SSF4928814'),
('+919113426632', 'SSF2493379'),
('+916260266983', 'SSF5511688'),
('+917828149087', 'SSF5819641'),
('+918103639148', 'SSF3478643'),
('+918435117140', 'CID191802125'),
('+918696754587', 'SSF3901844'),
('+919897729374', 'SSF4856202'),
('+918875425174', 'SSF4276272'),
('+916295558889', 'SSF3757446'),
('+918292006861', 'SSF5504792'),
('+919434843676', 'SSF3106242'),
('+919241979634', 'SSF4301884'),
('+919303742362', 'SSF4359486'),
('+918770928258', 'SID951375990763'),
('+917425890364', 'SID951375688039'),
('+919340496099', 'SID951374247972'),
('+917815073060', 'SSF5520462'),
('+916395662347', 'SSF5205261'),
('+919995699492', 'SSF5030494'),
('+917061790030', 'SID951374318262'),
('+919955563924', 'SSF5509984'),
('+916268926989', 'SSF4539656'),
('+919153947894', 'SSF6381966'),
('+918094305765', 'SID951375335171'),
('+917766092662', 'SSF5716893'),
('+918226834583', 'SSF5285756'),
('+917015290597', 'SSF5486162'),
('+917763024018', 'SSF5332800'),
('+918873568748', 'SSF6171659'),
('+916201544104', 'SSF5108891'),
('+917061817740', 'SSF5085470'),
('+917250316202', 'SSF4386001'),
('+917007478864', 'SSF4531704'),
('+917250444787', 'SSF5146214'),
('+918294973911', 'SSF5700072'),
('+918176964198', 'SSF4441246'),
('+918539842625', 'SSF5841548'),
('+919334008274', 'SSF4221802'),
('+918114533282', 'SID951373980788'),
('+918539065102', 'SID951374911419'),
('+916364182184', 'SSF5154579'),
('+916306216603', 'SSF6128438'),
('+917061028119', 'SSF5052245'),
('+917800326090', 'SSF5000326'),
('+917068107184', 'SSF4008841'),
('+919140195846', 'SSF4977147'),
('+919315422860', 'SSF4455233'),
('+919555172087', 'SSF4902515'),
('+919631842654', 'SSF4461943'),
('+919229581440', 'SSF5050795'),
('+919142902657', 'SSF5105733'),
('+916267331502', 'SSF3851234'),
('+916268883687', 'SSF4033893'),
('+917260962405', 'SSF4312307'),
('+917320983238', 'SSF3045416'),
('+917061446769', 'SSF3904130'),
('+917292801630', 'SSF2320146'),
('+917632011631', 'SSF2780014'),
('+917739270890', 'SSF3858096'),
('+917233828904', 'SSF4084021'),
('+917739979198', 'SID951375400278'),
('+917748965516', 'SSF4046974'),
('+918252073534', 'SSF4312460'),
('+918797027102', 'SSF4837118'),
('+918862356258', 'SSF3601123'),
('+918795444076', 'SSF3043340'),
('+918471054611', 'SSF4107727'),
('+919341871610', 'SSF4086329'),
('+919241145943', 'SSF3263219'),
('+919340852990', 'SSF4916371'),
('+919166176098', 'SSF5074355'),
('+919929300423', 'SSF3149617'),
('+919120606863', 'SSF3037814'),
('+919519720604', 'SSF4102082'),
('+919685586489', 'SSF4148626'),
('+917370910560', 'SSF5176190'),
('+917970386440', 'SSF5108312'),
('+918210678795', 'SSF4250880'),
('+919565875570', 'SSF4900499'),
('+919118539822', 'SSF4960146'),
('+919341255587', 'SSF5187360'),
('+919153638317', 'SSF5084910'),
('+917845982191', 'SSF5017463'),
('+918218581405', 'SSF5712421'),
('+919279256572', 'SSF5117143'),
('+917033091680', 'SSF5166231'),
('+917043233919', 'SSF5463215'),
('+918235386469', 'SID951374063146'),
('+916202230657', 'SID951374737747'),
('+916248434949', 'SSF3874854'),
('+916204351739', 'SSF3968933'),
('+916207219778', 'SSF4137942'),
('+916265162331', 'SSF3294505'),
('+916201861843', 'SID951372863879'),
('+916296866676', 'SSF3868808'),
('+916300468386', 'SSF3952058'),
('+916269797990', 'SSF3877998'),
('+916202953133', 'SSF4042331'),
('+916299206134', 'SSF4194630'),
('+917366835593', 'SSF3887810'),
('+917458952427', 'SSF3601384'),
('+917294056698', 'SSF3866550'),
('+917987033992', 'SSF3841751'),
('+917541033724', 'SSF3909013'),
('+918769777950', 'SSF4075108'),
('+918693653269', 'SID951374108661'),
('+918340407083', 'SSF4324900'),
('+918239685028', 'SSF3737474'),
('+918210215051', 'SSF3782680'),
('+919560328343', 'SSF4200361'),
('+919905402710', 'SSF5041048'),
('+919799040253', 'SSF3856488'),
('+919640523563', 'SSF3842284'),
('+919691264117', 'SSF5112642'),
('+919199739863', 'SID951373251154'),
('+919110984004', 'SSF2946287'),
('+916388456164', 'SSF4812408'),
('+919199681927', 'SSF4348566'),
('+916205904990', 'SSF4441647'),
('+917415856887', 'SSF2396375'),
('+917828576919', 'SSF3986728'),
('+918102634534', 'SSF4256206'),
('+918889984926', 'SSF4601030'),
('+919572564281', 'SSF4214704'),
('+919572534761', 'SSF4171928'),
('+919801080866', 'SSF4105765'),
('+919302353380', 'SSF4042379'),
('+919117911342', 'SSF4212956'),
('+918224923064', 'CID213100541'),
('+919343848242', 'CID076608385'),
('+919153429608', 'CID171506409'),
('+916213916191', 'SSF2909886'),
('+916280207165', 'SSF4644757'),
('+916263325018', 'SSF3432483'),
('+916266081722', 'SSF3683123'),
('+916306016255', 'SSF3547763'),
('+916203656372', 'SSF3537781'),
('+916200769160', 'SSF3651367'),
('+917676127637', 'SSF3822863'),
('+917254853904', 'SID951376028603'),
('+917319686889', 'SSF3743342'),
('+917647649797', 'SSF3787052'),
('+917849855054', 'SSF3017256'),
('+917250148595', 'SID951376211053'),
('+917289545632', 'SSF3638913'),
('+917772977253', 'SSF4186059'),
('+917739162998', 'SSF2958588'),
('+917491998634', 'SSF3698718'),
('+917477396903', 'SSF3698808'),
('+918490988941', 'SSF3599700'),
('+918294572579', 'SSF5013113'),
('+918252719523', 'SSF4644727'),
('+918754888899', 'SSF3435092'),
('+918676434664', 'SSF3805229'),
('+918969362650', 'SSF2722033'),
('+918770469749', 'SID951374909663'),
('+918690144259', 'SSF3595811'),
('+918264114899', 'SSF3535706'),
('+918541831193', 'SSF3388415'),
('+919009241506', 'SSF3719339'),
('+919351234417', 'SSF3402495'),
('+919523569401', 'SSF3617996'),
('+919875155956', 'SSF3554630'),
('+919646434353', 'SSF3631277'),
('+919523609640', 'SSF3599309'),
('+919499944949', 'SSF3691882'),
('+919082333569', 'SSF3890473'),
('+919334249741', 'SSF3580506'),
('+919123248678', 'SID951374907731'),
('+919329602040', 'SSF3697984'),
('+919767977994', 'SSF2557440'),
('+919939593976', 'SSF3651772'),
('+919302277602', 'SSF3927930'),
('+917761859055', 'SSF4213644'),
('+918318956290', 'SSF3942717'),
('+916768686868', 'SSF3724377'),
('+916898904588', 'SSF3470198'),
('+916379797778', 'SSF3447783'),
('+916737988986', 'SSF3481835'),
('+916299582919', 'SSF3679420'),
('+916207979787', 'SSF3222043'),
('+916206985650', 'SSF3679408'),
('+916424546844', 'SSF2595172'),
('+916203895164', 'SSF3251593'),
('+916564694941', 'SSF3640021'),
('+917759821364', 'SSF3875453'),
('+917070707070', 'SID951375537480'),
('+917646497949', 'SSF3165254'),
('+917643840554', 'SID951376101905'),
('+917366906843', 'SSF3627793'),
('+917858986277', 'SSF2495449'),
('+917461021049', 'SID951375617692'),
('+917544054318', 'SID951375415364'),
('+917292910821', 'SSF3288696'),
('+917667097056', 'SSF3383076'),
('+917489464976', 'SSF3616251'),
('+918078655656', 'SSF3718190'),
('+918003220657', 'SSF3621072'),
('+918437554348', 'SSF3658792'),
('+918521248628', 'SSF3326546'),
('+918809360785', 'SSF3605413'),
('+918448565056', 'SSF3594610'),
('+918165248528', 'SSF3245638'),
('+918441857585', 'SSF3729569'),
('+918294559739', 'SSF3231580'),
('+918754546949', 'SSF3230518'),
('+918434403828', 'SSF3612990'),
('+918867694399', 'SSF3595923'),
('+919787646646', 'SID951374470767'),
('+919772253558', 'SSF3715010'),
('+919634545545', 'SSF3573930'),
('+919637673497', 'SSF3488745'),
('+919142450792', 'SSF4096499'),
('+919610865568', 'SSF3463097'),
('+919119241780', 'SID951374749654'),
('+919632145625', 'SID951373995273'),
('+919786468646', 'SSF2942769'),
('+919509289156', 'SSF3385021'),
('+919672805923', 'SSF2709365'),
('+919554676888', 'SSF3246022'),
('+919536536666', 'SSF3314774'),
('+919214370882', 'SSF2895745'),
('+919592918182', 'SSF3349593'),
('+919508863421', 'SSF3460261'),
('+919508074230', 'SSF3533460'),
('+919995858586', 'SSF3494564'),
('+919801902134', 'SID951375554027'),
('+919878458623', 'SSF3191032'),
('+919343158410', 'SSF3986106'),
('+919487589294', 'SSF3174045'),
('+919646486448', 'SSF3263277'),
('+919216877297', 'SSF3495313'),
('+917362001719', 'SSF4812822'),
('+917633966729', 'SSF5311501'),
('+917208359936', 'SSF5512768'),
('+917061033182', 'SSF4935123'),
('+917060685026', 'SSF4796412'),
('+916204946522', 'SSF5147776'),
('+917759035013', 'SSF5048366'),
('+918294929631', 'SSF4838269'),
('+918090675841', 'SSF5794887'),
('+919234379745', 'SSF4838593'),
('+919975250792', 'SSF5634436'),
('+916202318163', 'SSF4889770'),
('+917061596936', 'SSF4666199'),
('+918006327084', 'SSF5866486'),
('+919350405681', 'SSF4786497'),
('+919817097123', 'SSF4786514'),
('+919306670763', 'SSF4761751'),
('+916207877389', 'SSF4161669'),
('+918809410565', 'SSF4179455'),
('+919645464846', 'SSF3552472'),
('+919142970779', 'SSF2790396'),
('+919355997535', 'SSF3389152'),
('+918920047559', 'SSF4078651'),
('+918271492126', 'SSF4073135'),
('+917565095990', 'SSF2968439'),
('+919569690513', 'SSF3858132'),
('+917843649487', 'SID951375793557'),
('+918233509276', 'SSF3510343'),
('+919263286149', 'SSF3969093'),
('+916130709159', 'SSF3500488'),
('+917426823738', 'SSF3766231'),
('+918541566955', 'SSF3415056'),
('+919950249757', 'SSF3403951'),
('+917633829680', 'SSF3463279'),
('+918432405075', 'SSF4098948'),
('+916203484348', 'SSF3475685'),
('+918302850442', 'SSF3456561'),
('+919905443238', 'SSF3612366'),
('+919340461601', 'SSF3686684'),
('+918353838683', 'SSF3660330'),
('+919649101134', 'SSF3359701'),
('+919082291558', 'SSF2766736'),
('+917404081903', 'SSF3277662'),
('+919034484239', 'SSF2715184'),
('+916375741482', 'SSF2803367'),
('+917004925918', 'SSF3659979'),
('+918674905741', 'SSF3555206'),
('+919728692570', 'SSF2682725'),
('+919958335755', 'SSF2489990'),
('+917752899515', 'SSF2698619'),
('+919754686483', 'SSF3657806'),
('+919998417866', 'SSF2951343'),
('+917854269873', 'SSF2949611'),
('+919643518554', 'SSF3053866'),
('+919769555886', 'SSF2796312'),
('+919174079792', 'SSF3356714'),
('+918248655895', 'SSF3014497'),
('+917087889688', 'SSF2425738'),
('+919548678767', 'SSF3242173'),
('+919548449469', 'SSF3284685'),
('+919728606319', 'SSF2938648'),
('+918950342133', 'SSF2792810'),
('+917898588946', 'SSF3277949'),
('+918787767769', 'SID951373647198'),
('+919135236723', 'SSF3106879'),
('+919835598599', 'SSF3168477'),
('+916377215983', 'SSF2730143'),
('+919155462038', 'SSF3339170'),
('+919949042890', 'SSF2842203'),
('+918443484464', 'SSF3157377'),
('+919734843484', 'SSF2796075'),
('+917247386320', 'SSF3759768'),
('+918252335237', 'SSF3266893'),
('+919346494346', 'SSF3100955'),
('+919279795429', 'SSF3305939'),
('+919843494649', 'SSF3268935'),
('+916377135264', 'SSF3462116'),
('+917654346461', 'SSF3284039'),
('+917654797664', 'SSF3301226'),
('+919125685975', 'SSF2766249'),
('+918817182123', 'SSF3338205'),
('+916203519006', 'SID951375834552'),
('+919343965773', 'SSF3589958'),
('+916734646545', 'SSF3718560'),
('+918607028161', 'SSF3124293'),
('+919856746886', 'SSF3094164'),
('+919708110720', 'SSF3208849'),
('+917870089575', 'SSF5297471'),
('+917310791350', 'SSF5086418'),
('+917070881753', 'SSF5222660'),
('+917739713939', 'SSF5202473'),
('+917007548871', 'SSF5203496'),
('+917510028415', 'SSF3914494'),
('+917903634022', 'SSF6006395'),
('+918545002593', 'SSF5445641'),
('+918271588356', 'SSF5287965'),
('+918755535161', 'SSF5875283'),
('+919149054774', 'SSF4920606'),
('+919369742164', 'SSF5827929'),
('+918770761828', 'SID951373703553'),
('+917779976076', 'SSF5095299'),
('+917294026375', 'SSF5133674'),
('+917409357502', 'SSF5661079'),
('+919263345148', 'SSF4996066'),
('+916202480964', 'SSF3968808'),
('+916306432629', 'SSF4001348'),
('+917828522757', 'SSF3945744'),
('+917023983851', 'SSF4010009'),
('+917645850809', 'SSF3598841'),
('+918619913042', 'SSF4289395'),
('+918905028832', 'SSF4011994'),
('+919301821539', 'SSF3258665'),
('+919511573201', 'SSF4312353'),
('+919234007813', 'SSF3817918'),
('+919263687226', 'SSF3944429'),
('+919617261151', 'SSF3961716'),
('+919358797276', 'SSF3850628'),
('+917842627149', 'SSF4813826'),
('+917667460177', 'SSF5587910'),
('+919263829800', 'SID2125006364'),
('+916454576464', 'SID951375537136'),
('+917719639844', 'SID951375715630'),
('+917665576408', 'SSF3488232'),
('+917091846716', 'SID951375026689'),
('+917667685733', 'SSF3957002'),
('+917800545376', 'SSF4219126'),
('+917976038878', 'SSF3795327'),
('+918603477058', 'SSF3529160'),
('+918292503580', 'SSF3842836'),
('+918969846845', 'SSF3871950'),
('+919257871494', 'SID951375754747'),
('+919801971425', 'SSF3243263'),
('+919206731243', 'SSF3657628'),
('+919798922155', 'SSF4006612'),
('+919263506423', 'SSF3957035'),
('+919998094153', 'SSF3908523'),
('+919263598695', 'SSF3875169'),
('+919142228126', 'SSF4062033'),
('+919905134897', 'SSF5265907'),
('+917761055279', 'SSF5718438'),
('+919835341393', 'SSF5378236'),
('+919034933664', 'SSF4994309'),
('+918874759563', 'SSF4481846'),
('+918409592937', 'SID951374659334'),
('+917070592394', 'SSF4210493'),
('+919198231032', 'SSF4560024'),
('+919102327723', 'SSF4124226'),
('+917805030411', 'CID090301662'),
('+918269454585', 'SID951373331806'),
('+919177229400', 'SID951373020556'),
('+916264665498', 'SSF3365271'),
('+916264676797', 'SID951375199290'),
('+916291080270', 'SSF3632828'),
('+916356665365', 'SSF3551232'),
('+916206767535', 'SSF4190278'),
('+917223033220', 'SSF3621973'),
('+917291884052', 'SID951374672226'),
('+917485821485', 'SSF3523655'),
('+917073645110', 'SSF4050046'),
('+917209131631', 'SSF3559475'),
('+917288863242', 'SSF3663547'),
('+917979779794', 'SSF3726053'),
('+917903638337', 'SSF3651771'),
('+917245128524', 'SSF3747817'),
('+917461857288', 'SSF3219316'),
('+918235394089', 'SSF3604430'),
('+918271763869', 'SSF3598437'),
('+918964866840', 'SSF3706760'),
('+918084012714', 'SSF2956789'),
('+918889754596', 'SSF2758288'),
('+918081588751', 'SSF3388943'),
('+918434739332', 'SSF4119050'),
('+918009949797', 'SSF3817524'),
('+918084949949', 'SSF3817669'),
('+919343266627', 'SSF3663506'),
('+919855554555', 'SSF3496229'),
('+919905795218', 'SSF3612779'),
('+919162211340', 'SID951376028599'),
('+919304279630', 'SSF4122161'),
('+919153799443', 'SSF2749824'),
('+919487846481', 'SSF3626817'),
('+919523700797', 'SSF3366157'),
('+919334499652', 'SID951373732090'),
('+919868745800', 'SSF3081575'),
('+919767840799', 'SSF3593323'),
('+919896464649', 'SSF3677655'),
('+919241310236', 'SSF4292667'),
('+919661683639', 'SSF3004640'),
('+919534287156', 'SSF3698831'),
('+919654874211', 'SSF3483121'),
('+919264199705', 'SSF4156965'),
('+919529283598', 'SSF2400792'),
('+916203362250', 'SSF5328457'),
('+917033260698', 'SSF4190674'),
('+917732978114', 'SSF3962833'),
('+918319980795', 'SSF4324304'),
('+918284029339', 'SSF3055126'),
('+918409128468', 'SSF2555442'),
('+918114580089', 'SSF2806880'),
('+918002812384', 'SSF4020083'),
('+919311048367', 'SSF4410110'),
('+919835228089', 'SSF3971962'),
('+919865252552', 'SID2125494857'),
('+919358809354', 'SSF4269318'),
('+919024652975', 'SID951376039766'),
('+919587553857', 'SSF3098933'),
('+919471360114', 'SSF2464566'),
('+917463014979', 'SSF5333625'),
('+917827204325', 'SSF5270614'),
('+918986937285', 'SSF5379845'),
('+919693643304', 'SSF5311476'),
('+916376820477', 'SID951374835815'),
('+916204772325', 'SSF3627732'),
('+916216738721', 'SID951375009229'),
('+916205493494', 'SSF3175515'),
('+916201390514', 'SSF3805897'),
('+916258963214', 'SSF3668502'),
('+916213825555', 'SSF3617394'),
('+916374827171', 'SID951375236788'),
('+916204772856', 'SSF3370901'),
('+916205787648', 'SSF3626172'),
('+916203537921', 'SSF3601209'),
('+917517603018', 'SSF3606119'),
('+917081014429', 'SSF4080068'),
('+917727462035', 'SSF3718966'),
('+917023683629', 'SSF3633708'),
('+917050472433', 'SSF3545242'),
('+917862362598', 'SSF3494326'),
('+917068899869', 'SSF3544418'),
('+917737724391', 'SSF3608136'),
('+918603276973', 'SID951374995065'),
('+918928148547', 'SSF2476886'),
('+918168968470', 'SSF3960564'),
('+918294640553', 'SSF3266342'),
('+918102342663', 'SSF3378059'),
('+918529863767', 'SSF3385022'),
('+918824011663', 'SSF3170204'),
('+918497978778', 'SSF3728496'),
('+918542546464', 'SSF3322037'),
('+918757906781', 'SID951374827209'),
('+918696605799', 'SSF3447495'),
('+919983652477', 'SSF3233350'),
('+919153606710', 'SSF3693933'),
('+919341815557', 'SSF3556819'),
('+919908536696', 'SSF3738561'),
('+919231584545', 'SSF3606440'),
('+919801267808', 'SSF3508532'),
('+919279705534', 'SSF3830422'),
('+919122081018', 'SSF3394193'),
('+919343646464', 'SSF3546510'),
('+919576780445', 'SSF2730381'),
('+919509856575', 'SID951376103128'),
('+919031755718', 'SID951374422359'),
('+919637875424', 'SSF2895744'),
('+919162570919', 'SSF3206659'),
('+919608817242', 'SSF3560024'),
('+919557285582', 'SSF3494544'),
('+919666558888', 'SSF3311905'),
('+916201462753', 'SSF4465060'),
('+918381920105', 'SSF5330650'),
('+918294408280', 'SSF4463046'),
('+918092037280', 'SSF5392731'),
('+919341167501', 'SSF5544019'),
('+918810721134', 'SSF5485455'),
('+917897985344', 'SSF4641692'),
('+916202858052', 'SSF5466157'),
('+918264789690', 'SSF5742540'),
('+919555811418', 'SSF4797364'),
('+917209450652', 'SSF4838285'),
('+919031174446', 'SSF4832256'),
('+917428213796', 'SSF5222866'),
('+919193247336', 'SSF5866427'),
('+916205884122', 'SSF4802952'),
('+916284803301', 'SSF4785625'),
('+919304221732', 'SSF3585686'),
('+919304483318', 'SSF5346961'),
('+916306608312', 'SSF3559453'),
('+919652177246', 'SSF3603721'),
('+916203042837', 'SID951372833976'),
('+919019481429', 'SSF2534491'),
('+917667299452', 'SSF3768687'),
('+918678891137', 'SSF4027734'),
('+917004665404', 'SSF3374183'),
('+918558596580', 'SSF3408417'),
('+919132326659', 'SSF3234167'),
('+919352051314', 'SSF3968120'),
('+919588554666', 'SSF3703074'),
('+918677875044', 'SSF3536342'),
('+919079116198', 'SSF3096691'),
('+919353066424', 'SSF4046934'),
('+919461230112', 'SSF3646713'),
('+917428665217', 'SSF3397272'),
('+919741528555', 'SSF3463199'),
('+919955616316', 'SID951374732414'),
('+916358987466', 'SSF3377432'),
('+919817583275', 'SSF2615564'),
('+917014638747', 'SSF3196915'),
('+917877527088', 'SID951374499755'),
('+916201834834', 'SSF3235324'),
('+919767846787', 'SSF3433790'),
('+918905276067', 'SSF2891638'),
('+919518149820', 'SSF2715423'),
('+919817595230', 'SSF2686349'),
('+917206134989', 'SSF2734658'),
('+918823464698', 'SSF3898478'),
('+919729513050', 'SSF2680891'),
('+918580832512', 'SSF2676195'),
('+916206736820', 'SSF2489861'),
('+919341112804', 'SSF2490070'),
('+919001646974', 'SSF2855350'),
('+919350549585', 'SSF2707213'),
('+919813519435', 'SSF2670738'),
('+918690120618', 'SSF3051190'),
('+918570027066', 'SID951375884558'),
('+919905891420', 'SSF2770310'),
('+918958647648', 'SSF2413173'),
('+917297864668', 'SSF3202231'),
('+919665663335', 'SSF3222378'),
('+916206898959', 'SSF3054804'),
('+919135917657', 'SSF3129801'),
('+918103532527', 'SSF4074010'),
('+918428446469', 'SSF3343702'),
('+918254465478', 'SSF3367929'),
('+918249465484', 'SSF3367928'),
('+917300124631', 'SSF2464945'),
('+919466330176', 'SSF2763788'),
('+916395248712', 'SSF3047544'),
('+919598277573', 'SID951376147318'),
('+919303639244', 'CID040201071'),
('+919680129574', 'SSF2959683'),
('+917056213215', 'SSF3058060'),
('+919650458639', 'SSF2522044'),
('+916265941438', 'SID951375481453'),
('+919799784237', 'SSF2681411'),
('+916266645521', 'SSF4352567'),
('+918963990352', 'SSF5539611'),
('+919770333843', 'SSF4455299'),
('+917828631834', 'SID951374412774'),
('+918384021106', 'SID951375712048'),
('+919135032577', 'SSF6329155'),
('+917000447550', 'SSF3140810'),
('+917091303378', 'SSF6087149'),
('+919166624730', 'SSF3539329'),
('+919334878951', 'SSF5516300'),
('+917426923534', 'SID951375208794'),
('+917004215401', 'SSF3049290'),
('+917833039859', 'SSF6267806'),
('+919838105692', 'SSF2846724'),
('+919279186326', 'SSF2860789'),
('+916207444820', 'SSF5720165'),
('+917564913794', 'SSF5502777'),
('+919131027638', 'SSF3542903'),
('+918875008162', 'SID951374352135'),
('+919568656866', 'SID951375426178'),
('+917566194207', 'SSF3957499'),
('+917070211782', 'SSF5195395'),
('+916287602071', 'SID951375318809'),
('+918839449306', 'SID951375689959'),
('+917691847949', 'SSF2364575'),
('+919506204853', 'SSF5355482'),
('+917224059135', 'SID951374242754'),
('+918742091974', 'SID951375944631'),
('+917070476072', 'SSF5931364'),
('+918193888023', 'SSF5488469'),
('+916265694938', 'SSF4986700'),
('+919129179103', 'SSF5005240'),
('+917050853858', 'SSF2281295'),
('+917828866836', 'SID951373853440'),
('+917250159090', 'SSF5434813'),
('+917815886573', 'SSF2854059'),
('+917368830090', 'SSF5543843'),
('+919799797664', 'SSF3653026'),
('+916204899433', 'SSF4748107'),
('+918797735516', 'SSF5708347'),
('+917632883528', 'SSF5866255'),
('+918445326312', 'SSF5314097'),
('+919351998651', 'SSF3348052'),
('+918932974798', 'SSF5610358'),
('+917070997916', 'SSF5845356'),
('+917091139584', 'SSF6271013'),
('+918002263318', 'SID951374802916'),
('+919572562211', 'SSF5788910'),
('+919837179062', 'SSF5471792'),
('+918209133380', 'SSF3180512'),
('+919241378932', 'SSF5060216'),
('+919801586678', 'SSF5798827'),
('+917970724511', 'SSF5985739'),
('+917348411252', 'SSF3326185'),
('+918006302567', 'SSF5339271'),
('+917056240771', 'SSF5872326'),
('+919123234516', 'SSF5240680'),
('+917355285980', 'SSF4903180'),
('+917985523694', 'SSF5540394'),
('+918175981698', 'SSF5893246'),
('+916261867952', 'SSF5787604'),
('+919142118948', 'SSF4864465'),
('+919798788048', 'SSF3917991'),
('+917070053448', 'SSF5840104'),
('+917023159647', 'SID951374359942'),
('+918602617806', 'SSF4916739'),
('+919473311928', 'SSF4260854'),
('+918815476369', 'SID951375990723'),
('+917724006237', 'CID072002207'),
('+919343470084', 'SSF5438600'),
('+917782952684', 'SSF6157470'),
('+917300905284', 'SSF5599730'),
('+919142174429', 'SSF3670411'),
('+919132587412', 'SSF2361470'),
('+919117338733', 'SSF5585162'),
('+916201281017', 'SSF2560749'),
('+919165913815', 'SID951374149779'),
('+917355325485', 'SSF5099759'),
('+918709597317', 'SSF5444566'),
('+918720856750', 'SID2125068877'),
('+918581858468', 'SSF3244608'),
('+918815940406', 'CID050404441'),
('+916268765507', 'SID2125234380'),
('+919770506003', 'SSF6477068'),
('+918804474332', 'SSF4858295'),
('+919956434023', 'SID951375557682'),
('+919155663014', 'SSF4482131'),
('+919060991543', 'SSF2917780'),
('+919238551472', 'CID061106544'),
('+919199135794', 'SSF5486974'),
('+919772831233', 'SSF4265219'),
('+918146273809', 'SSF5584522'),
('+919558731066', 'SSF5553804'),
('+917389744552', 'SSF2887117'),
('+918540020684', 'SSF5511769'),
('+917737510885', 'SSF5550628'),
('+917083901694', 'SID951375960311'),
('+918808508270', 'SSF3302981'),
('+918958833010', 'SSF6330413'),
('+917631414428', 'SSF6103552'),
('+917480042337', 'SID951374983521'),
('+919171906258', 'SSF2439120'),
('+918864036045', 'SSF4655916'),
('+917651954827', 'SSF5780204'),
('+916299566397', 'SSF5085119'),
('+919993794608', 'SSF2957294'),
('+919142259459', 'SSF3250182'),
('+918809856657', 'SSF2894203'),
('+917563943042', 'SID951375905098'),
('+918055146548', 'SSF5657472'),
('+919717892187', 'SSF3241728'),
('+919771348094', 'SSF4777759'),
('+919006873346', 'SSF5757550'),
('+918542846130', 'SSF5808245'),
('+918271472076', 'SSF5394707'),
('+918962039402', 'SSF5489579'),
('+919340537298', 'SID951375010294'),
('+919399395901', 'SSF6446002'),
('+918838448742', 'SSF5238622'),
('+918439368935', 'SSF5035984'),
('+919301961754', 'SSF5480199'),
('+917970545055', 'SSF3645270'),
('+918084087494', 'SSF5518760'),
('+916267430561', 'SID951372939139'),
('+918349396938', 'SID951375105044'),
('+918795233513', 'SSF5319294'),
('+918292263878', 'SID951374897005'),
('+917324848939', 'SSF4714481'),
('+917644020958', 'SSF5513583'),
('+919915014285', 'SSF5462692'),
('+919241680171', 'SID951375925916'),
('+919597713479', 'SSF5990168'),
('+917549917824', 'SSF5772164'),
('+916299228226', 'SSF6105545'),
('+919204959464', 'SSF5909515'),
('+918276950357', 'SSF4614656'),
('+917075328612', 'SID951373794316'),
('+918789283399', 'SSF6460835'),
('+918261022879', 'SID951375088648'),
('+919006263324', 'SSF4413539'),
('+918349440430', 'SSF3624590'),
('+917970911068', 'SSF5789857'),
('+919996205218', 'SSF2810546'),
('+917581873107', 'SID951373847735'),
('+919798809537', 'SSF5989056'),
('+917354850903', 'SID951373304753'),
('+919602587475', 'SSF2764181'),
('+919801575536', 'SSF5720222'),
('+919165973463', 'SID2125615524'),
('+916263562664', 'CID087111118'),
('+919234052612', 'SSF5238947'),
('+917004034060', 'SSF5604179'),
('+918409833768', 'SSF3447906'),
('+917239904035', 'SID951374944191'),
('+919065800711', 'SSF5833800'),
('+919828356366', 'SSF2568025'),
('+918585840706', 'SSF5650016'),
('+918009779658', 'SSF2549791'),
('+918305083267', 'SSF6211896'),
('+918889380171', 'SSF3292845'),
('+917781824350', 'SSF4962399'),
('+919566295249', 'SSF5594346'),
('+916232680731', 'SID951373137365'),
('+918085698684', 'SSF3103529'),
('+917739590786', 'SSF5161772'),
('+917838151976', 'SSF5161324'),
('+919795319152', 'SSF5639845'),
('+918810932811', 'SSF6151305'),
('+917250391134', 'SSF6221357'),
('+919631706300', 'SSF6144747'),
('+919770154416', 'SSF6121005'),
('+918269892344', 'CID061100851'),
('+919098178425', 'CID129109205'),
('+916392134016', 'SSF5016319'),
('+917070576882', 'SSF5468192'),
('+917247791474', 'SSF2787740'),
('+919193974948', 'SSF3933628'),
('+918750454792', 'SSF6310001'),
('+919905696098', 'SSF2706907'),
('+917633905156', 'SSF6126811'),
('+916204304961', 'SSF6419687'),
('+916260705572', 'SSF5757811'),
('+917643975987', 'SSF6088516'),
('+916266955828', 'SID951373034111'),
('+917876432041', 'SSF5303494'),
('+917739930470', 'SSF5615807'),
('+919335035549', 'SSF2493773'),
('+918757925250', 'SSF4958932'),
('+917828702411', 'SID951373814670'),
('+916202521577', 'SSF4449396'),
('+919570562837', 'SSF5434466'),
('+916209008645', 'SSF5829245'),
('+917803883224', 'SSF5732079'),
('+917482073934', 'SSF6084148'),
('+918084448169', 'SSF6084141'),
('+917280859512', 'SSF6270819'),
('+916202355997', 'SSF5144338'),
('+916262811406', 'SSF2662550'),
('+918601185930', 'SSF3124598'),
('+918968858056', 'SSF3442030'),
('+917667356161', 'SSF6442599'),
('+918097207533', 'SSF6186968'),
('+918894958946', 'SSF3557708'),
('+917879695326', 'SID951375889283'),
('+918982909618', 'SID951374905943'),
('+918084807929', 'SSF5005604'),
('+919546354682', 'SSF5647771'),
('+919515739495', 'SSF5765206'),
('+918521490128', 'SSF2573120'),
('+919608188959', 'SID951375705122'),
('+919627283442', 'SSF6097871'),
('+918002116703', 'SSF6145840'),
('+917906258169', 'SSF5223246'),
('+917620496806', 'SID951374889263'),
('+918251069591', 'SSF6075585'),
('+919343147052', 'SID951372932002'),
('+916263548673', 'SSF5302858'),
('+917462063813', 'SSF3138823'),
('+919079691927', 'SID951373996687'),
('+918757873696', 'SSF5804310'),
('+917815846508', 'SSF5663737'),
('+917742098974', 'SSF5401292'),
('+916201419374', 'SSF4058277'),
('+918532838771', 'SSF5287904'),
('+916264269036', 'SID951375153114'),
('+919058075212', 'SSF5027010'),
('+919810197082', 'SSF6217501'),
('+919166909010', 'SSF6395300'),
('+917761060350', 'SSF6310762'),
('+919797867436', 'CID044710555'),
('+919636500893', 'SSF5606946'),
('+918969615563', 'SSF5716062'),
('+916203760563', 'SSF6242953'),
('+919123698308', 'SSF5999377'),
('+916309920139', 'SSF5781269'),
('+919174018574', 'SID951374274618'),
('+919199001932', 'SSF5708070'),
('+918529138550', 'SSF4760746'),
('+919575484907', 'SID951375606350'),
('+917255851792', 'SSF4405884'),
('+917737305628', 'SSF5518097'),
('+918958223426', 'SSF5896250'),
('+917075610762', 'SSF5751462'),
('+919153736369', 'SSF4536504'),
('+916378096656', 'SSF5132608'),
('+919304528009', 'SID2125112424'),
('+918058225897', 'SID951374328164'),
('+916200632339', 'SSF4953380'),
('+919936253199', 'SSF5225364'),
('+917737938815', 'SSF3804073'),
('+917761062055', 'SSF6104847'),
('+918226816566', 'SSF3103134'),
('+917456818166', 'SSF6343030'),
('+919636503942', 'SSF2592762'),
('+918409775570', 'SSF5204225'),
('+919343505809', 'SSF3068187'),
('+918948283209', 'SSF4734136'),
('+919770144532', 'CID176207500'),
('+919525726587', 'SSF6326939'),
('+919111657849', 'SID951374472050'),
('+917763803784', 'SSF5460438'),
('+919625386180', 'SSF3170103'),
('+919263511705', 'SSF6086035'),
('+919905793022', 'SSF5771479'),
('+919234477052', 'SSF6312028'),
('+917610169250', 'SSF4403003'),
('+916204084381', 'SSF5168225'),
('+919905261547', 'SSF2282332'),
('+918120638940', 'SSF3358769'),
('+918461010383', 'SSF4858191'),
('+917070310551', 'SID951374571762'),
('+917828683063', 'SID106462'),
('+917371857885', 'SSF5701357'),
('+917782024251', 'SSF6329297'),
('+916205445061', 'SSF2997875'),
('+918271648433', 'SSF6291313'),
('+919473163574', 'SSF6105330'),
('+919608417554', 'SSF4813886'),
('+917770927346', 'SSF3332770'),
('+917549094076', 'SID951374086582'),
('+917738487074', 'SSF5394451'),
('+919118383539', 'SSF4915028'),
('+918084978618', 'SSF2950535'),
('+918000890254', 'SID951375045925'),
('+916306048937', 'SSF6064959'),
('+919389733179', 'SSF6186818'),
('+917357843873', 'SSF5329337'),
('+919771081306', 'SSF5301913'),
('+919229065952', 'SSF6157724'),
('+919708523323', 'SSF5167785'),
('+917783097721', 'SSF6343065'),
('+919351276682', 'SSF4208768'),
('+918076223575', 'SSF6441394'),
('+919279980210', 'SSF4733712'),
('+916266633875', 'SSF2886847'),
('+916260582754', 'SID951375575474'),
('+918757324817', 'SID951375077725'),
('+918839634503', 'SID951374125012'),
('+916207352140', 'SSF4417736'),
('+916287081713', 'SSF4439661'),
('+916268698720', 'SSF4194581'),
('+917518321955', 'SSF4505427'),
('+917485050228', 'SSF4170674'),
('+917061864022', 'SSF4933399'),
('+917870950924', 'SSF4217096'),
('+917209717003', 'SSF4487364'),
('+918103544267', 'SSF5217073'),
('+918862988641', 'SSF4219383'),
('+918092190545', 'SSF2806816'),
('+919587282183', 'SSF4325754'),
('+919516685624', 'SID951374537401'),
('+919341163949', 'SSF4441234'),
('+919140519798', 'SSF5312471'),
('+917320007872', 'SSF5310797'),
('+919262711389', 'SSF5356800'),
('+916266647525', 'CID084601403'),
('+917814016172', 'SSF5494404'),
('+918084959155', 'SSF5363717'),
('+916230178857', 'SSF5086469'),
('+919170275527', 'SSF5034163'),
('+919170824618', 'SSF5769098'),
('+919693728424', 'SSF4261811'),
('+919155625394', 'SSF6074427'),
('+919122836158', 'SSF5068406'),
('+916299618687', 'SID951375325176'),
('+917004387496', 'SSF2820195'),
('+918542082664', 'SID951375108598'),
('+916299994127', 'SSF3049355'),
('+916202995114', 'SSF4043438'),
('+916351582417', 'SSF4141105'),
('+916367670665', 'SSF4840977'),
('+916287027925', 'SSF2768089'),
('+916269142169', 'SSF4021195'),
('+916363351763', 'SSF4320348'),
('+916263945598', 'SSF4023807'),
('+916301439179', 'SSF5186671'),
('+916201791011', 'SSF4005107'),
('+917479886553', 'SSF4222437'),
('+917004874459', 'SSF5136138'),
('+917388624600', 'SSF4156015'),
('+917723057740', 'SSF3791270'),
('+917724056101', 'SSF4174405'),
('+917827237143', 'SSF4402910'),
('+917667975713', 'SSF4067045'),
('+917727836174', 'SSF2961276'),
('+918619590628', 'SSF4200121'),
('+918949303341', 'SSF3026908'),
('+918521078473', 'SSF4231999'),
('+918797299649', 'SSF4398582'),
('+918127327600', 'SSF4010977'),
('+918210875845', 'SSF4636790'),
('+918235150999', 'SSF4007622'),
('+918271230706', 'SSF4295003'),
('+918306881572', 'SSF5203676'),
('+918770834170', 'SSF5157148'),
('+918290343297', 'SSF4201755'),
('+918305004290', 'SSF3784891'),
('+918294144662', 'SSF2978896'),
('+918400380541', 'SSF4041454'),
('+919608537097', 'SSF4019090'),
('+919257198510', 'SSF4192782'),
('+919589973309', 'SSF4557951'),
('+919102200781', 'SSF3826955'),
('+919128330934', 'SSF3127653'),
('+919931858089', 'SSF3741605'),
('+919304098590', 'SSF4132996'),
('+919326849940', 'SSF2926526'),
('+919817455298', 'SSF4048283'),
('+919153899680', 'SSF4379777'),
('+919302659156', 'SSF4095234'),
('+919279387017', 'SSF4246865'),
('+919667204197', 'SSF4266789'),
('+919372057812', 'SSF4162516'),
('+919464348545', 'SSF3831360'),
('+919892409906', 'SSF4220935'),
('+919636855424', 'SSF3907116'),
('+919905511584', 'SID951374495356'),
('+919649602397', 'SSF3732171'),
('+919343108183', 'SSF4162339'),
('+917505604658', 'SSF5171545'),
('+917267867618', 'SSF5568803'),
('+917303618992', 'SSF4951140'),
('+917033350217', 'SSF4418984'),
('+918292982031', 'SSF4885986'),
('+918090370564', 'SSF5349557'),
('+918084249706', 'SSF5155662'),
('+918885107710', 'SSF4570883'),
('+919852461592', 'SSF4458481'),
('+919219749560', 'SSF5458370'),
('+919006480324', 'SSF5166503'),
('+919931273621', 'SSF5161323'),
('+919919606869', 'SSF5068504'),
('+919305642435', 'SSF5505854'),
('+916389880279', 'SSF5156464'),
('+917900664484', 'SSF5119126'),
('+918960236712', 'SSF4975562'),
('+918521309166', 'SSF5179281'),
('+919721310799', 'SSF4918294'),
('+917739920051', 'SSF4248167'),
('+917080683665', 'SSF4956310'),
('+918434923690', 'SSF4470092'),
('+917067734130', 'CID213701567'),
('+917652020939', 'SSF4262577'),
('+919897423864', 'SSF5462316'),
('+916203753796', 'SSF2752523'),
('+916202686479', 'SSF4423435'),
('+917410985213', 'SSF4010258'),
('+917470543181', 'SSF3961429'),
('+917250661113', 'SSF4016811'),
('+917763086792', 'SSF4187124'),
('+917780077624', 'SSF3966228'),
('+917070822306', 'SSF3871362'),
('+917849802984', 'SSF3803217'),
('+917726914046', 'SSF2772334'),
('+917061393680', 'SSF4012675'),
('+918651673367', 'SSF3055159'),
('+918120645155', 'SID83216'),
('+918797967856', 'SSF4019217'),
('+918406866768', 'SSF3972251'),
('+918825295159', 'SSF3952555'),
('+918209970276', 'SID951375276625'),
('+918271566232', 'SSF4101176'),
('+918890755841', 'SSF2800416'),
('+918102940428', 'SID951373445192'),
('+918210228811', 'SSF4162207'),
('+919617856324', 'SSF3704410'),
('+919351306862', 'SSF4000978'),
('+919931916463', 'SSF4496905'),
('+919142098789', 'SSF3880658'),
('+919234019412', 'SSF3937771'),
('+919771474698', 'SSF3975892'),
('+919303388292', 'SSF3979614'),
('+919263308697', 'SSF4403613'),
('+919006353465', 'SSF3999734'),
('+919142856157', 'SSF4967336'),
('+919199267781', 'SSF4703238'),
('+919693259736', 'SSF3983800'),
('+919162397517', 'SID951373793483'),
('+919835994262', 'SSF3956003'),
('+919985879765', 'SSF3823289'),
('+919120255353', 'SSF3996878'),
('+919858598888', 'SSF3582446'),
('+917762938318', 'SSF4168134'),
('+919012152239', 'SSF5465030'),
('+919193636127', 'SSF5231730'),
('+919818794529', 'SSF4275098'),
('+919234137202', 'SSF4961569'),
('+916328852136', 'SSF3600481'),
('+917648798748', 'SSF3758063'),
('+917499609837', 'SSF3766005'),
('+918002625253', 'SSF3813069'),
('+916260555753', 'SSF3188252'),
('+918540989014', 'SSF4666495'),
('+919430846305', 'SSF4222650'),
('+919024021503', 'SSF4050231'),
('+919238075170', 'SSF4065678'),
('+918405805666', 'SSF5039681'),
('+917000227822', 'SID951372936625'),
('+916562686568', 'SSF3492254'),
('+916249789498', 'SSF3593449'),
('+916464984438', 'SSF3741166'),
('+916206892189', 'SSF3356255'),
('+916202012065', 'SSF2772187'),
('+916203594887', 'SSF2799239'),
('+916234551518', 'SID951375822750'),
('+917607997908', 'SSF3802081'),
('+917543070418', 'SSF3628897'),
('+917406337042', 'SSF3609186'),
('+917366872170', 'SSF3347810'),
('+917023088513', 'SID951375974037'),
('+917903273960', 'SSF4076575'),
('+917215166454', 'SSF3449523'),
('+917250817906', 'SSF3314649'),
('+917479979728', 'SSF3330725'),
('+917488997001', 'SSF3185058'),
('+917240410773', 'SSF3351923'),
('+917664959940', 'SSF3403256'),
('+918675242366', 'SSF3829617'),
('+918235536197', 'SSF3419998'),
('+918873292583', 'SSF3785802'),
('+918521132907', 'SSF3621375'),
('+918874848494', 'SSF3473430'),
('+918114532189', 'SSF3978168'),
('+918589495613', 'SID951376245282'),
('+918521451423', 'SID951373952052'),
('+918109327806', 'SSF3635703'),
('+918935350452', 'SSF3314824'),
('+918355588455', 'SSF3733616'),
('+918797667870', 'SSF3684009'),
('+918221285655', 'SSF3441169'),
('+918467859289', 'SSF3754416'),
('+918102396858', 'SSF3535190'),
('+918271609580', 'SSF3590400'),
('+918957723673', 'SSF3733391'),
('+919109466235', 'SSF3635658'),
('+919801072996', 'SID951375032764'),
('+919128357038', 'SSF4178688'),
('+919280639017', 'SSF3393590'),
('+919546590474', 'SSF2464908'),
('+919791725749', 'SSF4844914'),
('+919294519968', 'SSF3656600'),
('+919458457864', 'SSF3713311'),
('+919572526291', 'SSF3732525'),
('+919006792385', 'SSF3483805'),
('+919707584840', 'SSF3512563'),
('+919060595604', 'SSF3752997'),
('+919229027571', 'SSF3575600'),
('+919875333267', 'SSF3981561'),
('+919341069607', 'SSF4028104'),
('+919576674004', 'SSF3613288'),
('+919525691686', 'SSF3185114'),
('+919462636031', 'SSF3692075'),
('+919955335706', 'SSF3367888'),
('+919693659800', 'SSF4679946'),
('+919472728592', 'SID951376194143'),
('+919669026447', 'SSF2607744'),
('+919738938679', 'SSF3375009'),
('+919001345480', 'SSF3003659'),
('+919782534516', 'SSF2950312'),
('+919938862869', 'SSF3660710'),
('+919546461611', 'SSF3734743'),
('+919973468799', 'SSF4945482'),
('+916294373528', 'SSF3191805'),
('+916204974519', 'SSF3716513'),
('+916349797797', 'SSF3677096'),
('+916375262750', 'SSF3370699'),
('+916386599562', 'SSF3576463'),
('+917357774217', 'SSF3344154'),
('+917742894215', 'SSF3493202'),
('+917061812010', 'SSF3191904'),
('+917061986699', 'SSF3625726'),
('+917645451518', 'SSF3166200'),
('+917352579491', 'SSF3422336'),
('+917986044264', 'SSF3206338'),
('+917600383463', 'SSF3305262'),
('+917820000361', 'SSF3288981'),
('+917050061824', 'SSF3272373'),
('+917543077432', 'SSF4213416'),
('+917368032526', 'SSF3423753'),
('+917323943877', 'SSF3172165'),
('+917567764848', 'SSF3689575'),
('+917533506060', 'SSF3465317'),
('+917330886788', 'SSF3293817'),
('+918085214563', 'SSF3692683'),
('+918052369880', 'SSF3559685'),
('+918085236980', 'SSF3634322'),
('+918045377967', 'SSF3267986'),
('+918696934903', 'SID951374867596'),
('+918827262389', 'SSF3415879'),
('+918228954472', 'SSF3267322'),
('+918987428631', 'SSF3743556'),
('+918554766426', 'SSF3624564'),
('+918824406135', 'SSF3674163'),
('+918976946994', 'SSF3595856'),
('+919945436313', 'SSF3376433'),
('+919263742375', 'SSF3493237'),
('+919671064731', 'SSF3606786'),
('+919263518461', 'SSF4569849'),
('+919153743484', 'SSF3262969'),
('+919858995559', 'SSF3791337'),
('+919955299511', 'SSF3464050'),
('+919001832711', 'SSF3782524'),
('+919142181467', 'SSF3290116'),
('+919672586465', 'SSF3762478'),
('+919123442371', 'SID951375155357'),
('+919123451475', 'SSF3298513'),
('+919006833912', 'SSF3305263'),
('+919684348843', 'SSF3472674'),
('+919494979797', 'SSF3277205'),
('+919846466464', 'SID951372948630'),
('+919934661960', 'SSF3367087'),
('+919508941044', 'SSF3367051'),
('+919117218039', 'SSF3581662'),
('+919983494656', 'SSF3198893'),
('+919636487575', 'SSF3766157'),
('+919660539869', 'SSF3299576'),
('+919636723590', 'SSF4329065'),
('+919464843404', 'SSF3710372'),
('+919854248388', 'SSF3477645'),
('+919341673206', 'SSF5324706'),
('+918235405901', 'SSF4777473'),
('+918969792602', 'SSF4606391'),
('+918521122112', 'SSF4406912'),
('+919621154951', 'SSF5366209'),
('+917739755530', 'SSF5037730'),
('+918756157274', 'SSF5215100'),
('+917033074696', 'SSF4875045'),
('+917632878616', 'SSF4512216'),
('+918385005740', 'SSF5498242'),
('+918920846672', 'SSF5866422'),
('+918601781093', 'SSF5121316'),
('+919971964356', 'SSF4749457'),
('+916206610227', 'SSF5094701'),
('+917070853325', 'SSF4796575'),
('+919621104241', 'SID951375673887'),
('+918999326163', 'SSF4335559'),
('+918809951509', 'SSF4183088'),
('+916286351783', 'SSF3752117'),
('+917230851243', 'SSF3913805'),
('+918092252349', 'SSF4183587'),
('+917260066414', 'SSF3445203'),
('+918528042916', 'SSF4152223'),
('+918799797879', 'SSF3901805'),
('+918877295253', 'SSF4206606'),
('+918112828334', 'SSF4135892'),
('+919571970246', 'SSF3275412'),
('+918960210562', 'SSF4215063'),
('+919335286558', 'SSF2690591'),
('+918565656464', 'SSF3166938'),
('+919116925776', 'SID951374673816'),
('+918965983293', 'SSF3780377'),
('+917496853270', 'SSF3738715'),
('+918815530883', 'SSF3784927'),
('+918463057514', 'SSF3487264'),
('+916284946555', 'SID951374669431'),
('+918965213053', 'SSF3649221'),
('+918235598480', 'SSF3562665'),
('+917412938108', 'SSF3759898'),
('+919875584587', 'SSF3305176'),
('+918495784508', 'SSF3788611'),
('+917230837755', 'SSF2986100'),
('+919772438545', 'SSF3300877'),
('+917568804295', 'SSF2832725'),
('+917296991008', 'SSF4030342'),
('+916354987546', 'SSF2316187'),
('+917258361985', 'SID951376040564'),
('+919933525547', 'SID951376167993'),
('+919826856756', 'SSF2572546'),
('+919262908708', 'SID951374948022'),
('+919685757586', 'SSF2909333'),
('+916261269012', 'SSF2987355'),
('+917559289330', 'SSF3253996'),
('+917042400604', 'SSF2943249'),
('+919657468526', 'SSF2874940'),
('+919827554856', 'SID951374750428'),
('+916203323949', 'SID951376245943'),
('+918541233544', 'SSF2775005'),
('+919654282335', 'SSF3136847'),
('+917320040559', 'SSF2975194'),
('+917525410804', 'SSF2947776'),
('+918052300124', 'SSF2992371'),
('+919646468684', 'SSF2976168'),
('+919828631824', 'SSF3265124'),
('+919950684046', 'SSF2960820'),
('+919576517195', 'SSF2944327'),
('+918889128627', 'SSF3651548'),
('+919375275459', 'SSF2865501'),
('+919571710717', 'SSF3248504'),
('+919683213482', 'SSF2828367'),
('+917485973887', 'SSF3261042'),
('+919679765888', 'SSF3154587'),
('+917542084254', 'SSF3275576'),
('+916689688958', 'SID951374688075'),
('+917250310812', 'CID262701311'),
('+919065674746', 'SID951375762132'),
('+918144469177', 'SSF2821756'),
('+919129199309', 'SSF2570027'),
('+919934710065', 'SSF2400527'),
('+919896834243', 'SID951376195549'),
('+916205995253', 'SSF4834816'),
('+916268791202', 'SSF4193723'),
('+916205323471', 'SSF4419539'),
('+916207881059', 'SSF4139030'),
('+916260854570', 'SSF3264254'),
('+917667279039', 'SSF4388362'),
('+917722896552', 'SID18792'),
('+917370059931', 'SSF4300177'),
('+917857872723', 'SSF4382536'),
('+917481855484', 'SSF4505211'),
('+917258081294', 'SSF4593923'),
('+917358358280', 'SSF3956501'),
('+917070605885', 'SSF4214670'),
('+917632844343', 'SSF4301255'),
('+917209542221', 'SSF4212883'),
('+917857886434', 'SSF3422330'),
('+917209554724', 'SSF3306197'),
('+917209528832', 'SSF4724756'),
('+917999619334', 'SSF4186730'),
('+917726852590', 'SSF4056645'),
('+917879429175', 'SSF4378003'),
('+917706964877', 'SSF3107395'),
('+917870111613', 'SSF4398571'),
('+917755015800', 'SSF3988165'),
('+917870134870', 'SSF4439662'),
('+918757925877', 'SSF4700920'),
('+918736882831', 'SSF4086055'),
('+918092536620', 'SSF4387998'),
('+918252647009', 'SSF4286282'),
('+918797763344', 'SSF4182878'),
('+918235089677', 'SSF4672296'),
('+918294115361', 'SSF4716116'),
('+918538928049', 'SSF4394846'),
('+918797320773', 'SSF2795333'),
('+918271338854', 'SSF4302683'),
('+918603195069', 'SSF4243815'),
('+918349053576', 'SSF3372630'),
('+918920011768', 'SSF4733395'),
('+919284425529', 'SSF4699761'),
('+919334777051', 'SSF4392639'),
('+919576512506', 'SSF4197267'),
('+919636831993', 'SSF5149405'),
('+919303993146', 'SSF3808342'),
('+919399719175', 'SSF4421700'),
('+919572060662', 'SSF3958683'),
('+919890141018', 'SSF4287613'),
('+919125194007', 'SSF3930806'),
('+919113438783', 'SSF4325285'),
('+919889608634', 'SSF4221668'),
('+919334861803', 'SSF4716126'),
('+919065889349', 'SSF4230419'),
('+919122382872', 'SSF4308450'),
('+919708429082', 'SSF4217294'),
('+919878075834', 'SSF4413886'),
('+919955866536', 'SSF4313052'),
('+919661894815', 'SSF4559178'),
('+919162044639', 'SSF5716761'),
('+919939799021', 'SSF4228899'),
('+916207715047', 'SSF5039563'),
('+917830753428', 'SSF5258241'),
('+918084694395', 'SSF5222708'),
('+917666932242', 'SSF5468772'),
('+917434089558', 'SSF4679754'),
('+918809719868', 'SSF4786718'),
('+918409490426', 'SSF5212242'),
('+918126099631', 'SSF5088653'),
('+918750090568', 'SSF5041307'),
('+919555166195', 'SSF5314109'),
('+919125388202', 'SSF4820795'),
('+919334730545', 'SSF5301728'),
('+919639754782', 'SSF5050620'),
('+919453836343', 'SSF5934045'),
('+918159095032', 'SSF5472758'),
('+919661654436', 'SSF4398476'),
('+916205593616', 'SSF4236008'),
('+917023311357', 'SSF4484013'),
('+917654501866', 'SSF5392560'),
('+917004296606', 'SSF4553507'),
('+918815273132', 'SSF3829912'),
('+918210287163', 'SSF4002448'),
('+918709728013', 'SSF4132484'),
('+918769929925', 'SSF3911057'),
('+919672601693', 'SSF3859477'),
('+919234191332', 'SSF4136806'),
('+919006070641', 'SSF4219263'),
('+919507498651', 'SSF4185753'),
('+919875890965', 'SSF4239130'),
('+919924294107', 'SSF5148647'),
('+919455317818', 'SSF4047341'),
('+919122538625', 'SSF4038712'),
('+917988756533', 'SSF5077937'),
('+919559009428', 'SSF5566669'),
('+919263771686', 'SSF5772578'),
('+916388158582', 'SSF5482274'),
('+917317748571', 'SSF4959998'),
('+917307744840', 'SSF5156231'),
('+919793275484', 'SSF4942037'),
('+919608533785', 'SSF5662547'),
('+918305745993', 'CID207303587'),
('+916287600959', 'SSF4986253'),
('+916839868998', 'SSF3898208'),
('+917667021342', 'SSF4061542'),
('+917643038167', 'SSF3025326'),
('+917355897425', 'SSF4246703'),
('+917828748617', 'SSF3183285'),
('+917667053964', 'SSF3944900'),
('+917481943809', 'SSF4216889'),
('+918252051086', 'SSF4799546'),
('+918292762239', 'SSF3804607'),
('+918925124202', 'SSF3880906'),
('+918521458048', 'SSF4028280'),
('+919135304825', 'SSF4165781'),
('+919339470805', 'SSF4054456'),
('+919054377579', 'SSF3949600'),
('+919128762778', 'SSF3973483'),
('+919162342573', 'SSF4053607'),
('+919153252932', 'SSF3977346'),
('+919807415272', 'SSF3960127'),
('+919153649721', 'SID951376135698'),
('+919155606133', 'SSF3881770'),
('+919973707658', 'SSF3950270'),
('+917267979529', 'SSF5940062'),
('+918294758584', 'SSF5068042'),
('+919006450276', 'SSF4890124'),
('+919155951060', 'SSF3657096'),
('+916267681942', 'SSF4369906'),
('+918792628148', 'SSF4518269'),
('+919570354126', 'SSF4425991'),
('+919263224301', 'SSF4498002'),
('+917209801083', 'SSF4663258'),
('+916280707079', 'SSF3885935'),
('+916260893061', 'SSF3635699'),
('+916397679798', 'SSF3833054'),
('+916289880999', 'SSF3740407'),
('+916249494694', 'SSF3710266'),
('+916208599999', 'SSF3575601'),
('+916280548999', 'SSF3674277'),
('+916398769025', 'SSF3581731'),
('+917877674294', 'SSF3811071'),
('+917858042962', 'SSF3470443'),
('+917033344910', 'SID951375234535'),
('+917676197697', 'SSF3508273'),
('+917970888941', 'SSF3716751'),
('+917970778131', 'SSF3443011'),
('+918423811018', 'SSF4856502'),
('+918969769450', 'SSF3787144'),
('+918228926974', 'SSF3350212'),
('+918084955863', 'SSF3712821'),
('+918521046516', 'SSF4218715'),
('+918652439799', 'SSF3509058'),
('+918797948372', 'SSF3202335'),
('+918454894684', 'SID951375997747'),
('+918949573673', 'SID951376111618'),
('+919179961208', 'SSF4391259'),
('+919122628137', 'SSF3743189'),
('+919301591348', 'SSF3668682'),
('+919632523331', 'SSF3258184'),
('+919332220193', 'SSF3545312'),
('+919341846078', 'SSF3393415'),
('+919445548466', 'SID951375193386'),
('+919885434616', 'SID951374559873'),
('+919437997389', 'SSF3811828'),
('+919123548774', 'SSF3320769'),
('+919304494559', 'SSF4019936'),
('+919566666656', 'SSF3780692'),
('+919006443748', 'SSF4001602'),
('+919680475005', 'SSF3217370'),
('+919576743650', 'SSF3737520'),
('+919753488304', 'SSF3494323'),
('+919341930488', 'SSF3451864'),
('+919123120661', 'SSF3676882'),
('+919572131866', 'SSF3737857'),
('+919354003662', 'SSF3699665'),
('+919668842258', 'SSF3442673'),
('+919464355480', 'SSF3688379'),
('+919098255041', 'SSF3816834'),
('+919340020606', 'SSF3534363'),
('+919636497020', 'SSF3501875'),
('+919930119326', 'SSF3410845'),
('+919976766868', 'SSF3365487'),
('+919576646464', 'SSF3789285'),
('+919348276498', 'SID951375100603'),
('+916376701793', 'SSF2400555'),
('+916287286567', 'SSF4305213'),
('+917089671683', 'SSF3725201'),
('+918252797556', 'SSF3962067'),
('+918294065609', 'SSF4188629'),
('+918340215184', 'SSF4231373'),
('+919216437145', 'SSF3418920'),
('+919644480705', 'SSF3818707'),
('+919102882934', 'SSF5136777'),
('+917428860144', 'SSF4946017'),
('+917368045871', 'SSF5480723'),
('+919934211688', 'SSF5266765'),
('+919234148039', 'SSF5341595'),
('+916299130633', 'SSF4857934'),
('+916200327878', 'SID951373450683'),
('+916206758489', 'SSF3190051'),
('+916203697441', 'SSF3772995'),
('+916206578523', 'SID951373658841'),
('+916367178239', 'SSF3465042'),
('+916377542216', 'SSF3559048'),
('+916375101893', 'SSF3317280'),
('+916354964854', 'SSF3681346'),
('+917761869766', 'SSF3687696'),
('+917033528489', 'SSF3000614'),
('+917587226484', 'SSF2744363'),
('+917762901014', 'SSF3543688'),
('+918102172383', 'SSF3866890'),
('+918690082681', 'SSF3854603'),
('+918817013026', 'SSF3379497'),
('+918619777289', 'SSF3456998'),
('+918873009741', 'SSF3174833'),
('+918654866358', 'SSF3518414'),
('+918297677679', 'SSF3004247'),
('+918856988850', 'SSF3338725'),
('+918890931933', 'SSF3709843'),
('+918319608201', 'SSF3814969'),
('+918328658865', 'SSF3213268'),
('+918852923747', 'SSF4245391'),
('+918966097327', 'SSF3429865'),
('+919632523586', 'SSF3498038'),
('+919693589704', 'SSF3552615'),
('+919798488421', 'SSF3532223'),
('+919767673454', 'SSF2301129'),
('+919494004949', 'SSF3440274'),
('+919509363686', 'SSF3722584'),
('+919004586365', 'SSF3393227'),
('+919128407743', 'SSF2941143'),
('+919385688885', 'SSF3465798'),
('+919060606912', 'SSF3791716'),
('+919006777058', 'SSF3183183'),
('+919341019713', 'SSF3272528'),
('+919771579063', 'SSF3302098'),
('+919958102733', 'SSF3339612'),
('+919521688337', 'SSF3686295'),
('+919772233024', 'SSF3753323'),
('+919153141272', 'SSF3755493'),
('+919334848832', 'SSF5482593'),
('+919161716331', 'SSF5665814'),
('+919334191643', 'SSF5257453'),
('+919695692616', 'SSF5324153'),
('+919263044780', 'SSF4606164'),
('+916248164845', 'SSF3334358'),
('+919763494359', 'SSF3398803'),
('+917518220127', 'SSF4026065'),
('+919621116487', 'SSF3963647'),
('+917260908777', 'SSF3771387'),
('+917946664646', 'SSF3760856'),
('+917737943112', 'SSF3782538'),
('+918654734869', 'SID951376049723'),
('+918600952672', 'SSF3750819'),
('+919351433078', 'SSF2878635'),
('+916350001906', 'SID951376040478'),
('+919759081554', 'SSF3736984'),
('+918103949017', 'SSF2960085'),
('+918581041192', 'SID951374624542'),
('+918896563509', 'SSF3067484'),
('+919263271495', 'SSF3117929'),
('+916262302218', 'SSF4019544'),
('+918284976764', 'SSF3014498'),
('+919464949469', 'SSF2883779'),
('+919632178415', 'SSF3134361'),
('+918538953956', 'SSF2977837'),
('+916205670634', 'SSF3028069'),
('+919976796496', 'SSF3434346'),
('+919324472536', 'SSF3334071'),
('+918000797967', 'SSF2373482'),
('+918579734490', 'SSF3316815'),
('+916377078851', 'SID951375882458'),
('+919155828554', 'SSF3303609'),
('+919646421361', 'SSF2854924'),
('+917488569858', 'SSF3234505'),
('+919992182776', 'SSF2959045'),
('+918895741525', 'SID951375922358'),
('+917889194551', 'SSF6175154'),
('+917067572594', 'SSF5763700'),
('+918789634911', 'SSF6040961'),
('+917319760184', 'SSF5413250'),
('+916393045082', 'SSF2719872'),
('+918207618556', 'SSF4538345'),
('+918143106216', 'SSF5480952'),
('+919244737601', 'SSF5367654'),
('+917357281895', 'SSF5523108'),
('+919045306101', 'SSF4796889'),
('+918830444203', 'SSF5246441'),
('+919125831871', 'SSF4815323'),
('+918002249362', 'SSF5612521'),
('+919241216142', 'SSF5657592'),
('+919699779693', 'SSF3799607'),
('+919608907369', 'SSF5932278'),
('+917541065759', 'SID951374584379'),
('+917319434734', 'SID951374281172'),
('+918797585584', 'SSF6163741'),
('+919828684979', 'SSF3977760'),
('+918426094165', 'SSF5265341'),
('+917461920463', 'SID951374985038'),
('+919770802367', 'SID951374661092'),
('+919770098507', 'SSF2510771'),
('+919279585729', 'SSF2592504'),
('+919060225025', 'SID951375282534'),
('+919009075307', 'SSF3240598'),
('+917879417180', 'SSF6400977'),
('+917568391418', 'SSF4335644'),
('+916201867118', 'SID951374496722'),
('+917398534217', 'SSF5551235'),
('+919174305140', 'CID140700606'),
('+919599686913', 'SSF6016836'),
('+916202553486', 'SSF4585169'),
('+918738085481', 'SSF2760871'),
('+918235553994', 'SSF5607199'),
('+918969817877', 'SSF2668722'),
('+918392826176', 'SSF5365033'),
('+919770924047', 'SSF5173341'),
('+917302539730', 'SSF5232376'),
('+918340639716', 'SID951375185169'),
('+918958409070', 'SSF5371557'),
('+916391675273', 'SSF5376506'),
('+917348646536', 'SSF5940151'),
('+919667189238', 'SSF5376300'),
('+917217615247', 'SSF6181139'),
('+919865686568', 'SSF2626481'),
('+918827369959', 'SSF3228244'),
('+919738054425', 'SSF4384708'),
('+917850892504', 'SSF5121108'),
('+919303980828', 'CID087401228'),
('+919801177526', 'SSF5115999'),
('+919835557186', 'SSF6188611'),
('+918228006903', 'SSF2754815'),
('+919109315430', 'SSF3975759'),
('+918294628520', 'SID951375692367'),
('+919835572337', 'SSF5346302'),
('+918271847463', 'SSF6237045'),
('+919056501442', 'SSF5776767'),
('+917247824719', 'SSF4593972'),
('+919798249275', 'SSF5793619'),
('+916238166451', 'SSF5661762'),
('+919123288733', 'SSF3924318'),
('+918826098016', 'SSF5567486'),
('+918957649880', 'SSF2946396'),
('+917737487969', 'SID951375513037'),
('+919096932656', 'SSF4150169'),
('+917067763913', 'SSF6423653'),
('+919263586293', 'SSF5912314'),
('+919102293719', 'SSF5518077'),
('+917459886284', 'SSF2521926'),
('+919140119204', 'SSF5808055'),
('+918208727400', 'SID951375381633'),
('+917348134483', 'SSF4675428'),
('+919120767869', 'SSF5703736'),
('+918057437821', 'SSF5952711'),
('+918299870017', 'SSF6054898'),
('+919509967420', 'SSF4013369'),
('+919256884372', 'SSF3798226'),
('+918275345824', 'SSF4783496'),
('+919508207485', 'SSF5842242'),
('+918088371186', 'SSF6014214'),
('+918717938940', 'SID951373363867'),
('+918306427138', 'SSF3632499'),
('+917062093414', 'SSF2576299'),
('+919549236225', 'SSF2509665'),
('+919142618447', 'SSF5619328'),
('+918890798446', 'SSF5177130'),
('+916268910713', 'SSF4198771'),
('+917061286875', 'SSF6153685'),
('+919572197908', 'SSF5316404'),
('+916203782690', 'SSF6056580'),
('+917568958694', 'SID951374569749'),
('+918545123565', 'SSF3098791'),
('+919151324643', 'SID951376046259'),
('+916391903217', 'SSF4005411'),
('+918448686762', 'SSF2345312'),
('+919701240452', 'SSF4973426'),
('+918016547597', 'SSF5657895'),
('+918002415375', 'SSF5209953'),
('+918114558828', 'SSF5801668'),
('+918434600061', 'SID951375236217'),
('+919329722413', 'SID951375886184'),
('+916263346215', 'SSF3149303'),
('+918052523554', 'SSF3926269'),
('+917091958464', 'SSF6073240'),
('+919060594878', 'SSF6138236'),
('+918878919946', 'SSF2381837'),
('+919262816943', 'SSF4715573'),
('+919838505129', 'SSF6038008'),
('+919329282146', 'SSF4822559'),
('+919709131550', 'SSF5561838'),
('+919328737101', 'SSF4885686'),
('+916265717215', 'SSF3113180'),
('+918102521026', 'SID951374342601'),
('+919234216367', 'SSF4566564'),
('+918542802853', 'SSF2450803'),
('+918251075850', 'SID2125722306'),
('+918120260095', 'SSF4169312'),
('+919353743292', 'SSF5746379'),
('+916287729682', 'SSF3104557'),
('+919515088721', 'SSF4802272'),
('+918546134897', 'SID951374827829'),
('+918207021967', 'SID951375763370'),
('+918271375523', 'SSF5071996'),
('+919263911153', 'SSF2675175'),
('+919244507467', 'SSF4007879'),
('+916209421069', 'SSF6021039'),
('+919870914884', 'SSF5859287'),
('+917281899165', 'SID951375044969'),
('+917060147514', 'SSF6410741'),
('+919528540748', 'SSF5368635'),
('+916206394295', 'SSF6365760'),
('+918294792095', 'SSF2817847'),
('+919828050798', 'SSF3245530'),
('+917480885889', 'SID951374770930'),
('+917317358340', 'SSF5143408'),
('+919758578558', 'SSF2437795'),
('+919770031697', 'SID951375202312'),
('+918128569791', 'SSF5300200'),
('+918826899684', 'SSF2729025'),
('+919993899204', 'SSF4264347'),
('+917719769526', 'SSF4565706'),
('+917302869640', 'SID951375842715'),
('+919263502360', 'SSF4743785'),
('+917543954759', 'SSF5723835'),
('+919771574015', 'SSF3278835'),
('+917070403390', 'SSF5467115'),
('+919608947535', 'SID951373142691'),
('+919565732465', 'SSF5656509'),
('+918302025352', 'SID951375650026'),
('+919327045729', 'SSF5892794'),
('+916375993007', 'SSF2507686'),
('+917470536375', 'SSF3075581'),
('+916352232099', 'SSF5125868'),
('+918409372141', 'SSF5842018'),
('+917728940719', 'SSF3911806'),
('+917861086524', 'SSF2365564'),
('+919511578799', 'SSF2569545'),
('+919166447336', 'SID951376052037'),
('+918252099984', 'SSF5499759'),
('+918383874674', 'SSF5161366'),
('+918871354062', 'CID093400440'),
('+918305710901', 'SSF2793940'),
('+919301283514', 'SID2125696143'),
('+917011532722', 'SSF4776347'),
('+917879881848', 'SSF3116869'),
('+917367826648', 'SSF4219273'),
('+917023059648', 'SID951374582360'),
('+919825634885', 'SID951376130426'),
('+918824702253', 'SSF5172551'),
('+919661934166', 'SSF4773166'),
('+919571946487', 'SID951374660702'),
('+916207051137', 'SSF3495059'),
('+916205121687', 'SSF5759271'),
('+919784722440', 'SSF5403938'),
('+917368905812', 'SSF4398489'),
('+917294812054', 'SSF5377652'),
('+916287007715', 'SSF6078094'),
('+918002843796', 'SID951374856818'),
('+918294344305', 'SSF5233539'),
('+917379229760', 'SSF6046896'),
('+918271273240', 'SID951374494292'),
('+919905129194', 'SSF5709849'),
('+919801796093', 'SSF5847839'),
('+919098801629', 'SSF5036058'),
('+916388691094', 'SSF3085633'),
('+919279895745', 'SSF5841095'),
('+917037243024', 'SSF5241137'),
('+919354415634', 'SSF4895413'),
('+919939096160', 'SSF4609296'),
('+918072016645', 'SSF5769330'),
('+918122185909', 'SSF5682373'),
('+919098291306', 'SID951376128140'),
('+919610965645', 'SSF4083118'),
('+919756654646', 'SID951375730059'),
('+917070274178', 'SSF5256218'),
('+919983764395', 'SID951374417242'),
('+916376545231', 'SSF2685500'),
('+916396961296', 'SSF5941290'),
('+919155713098', 'SSF5195332'),
('+917080414506', 'SSF5739473'),
('+917069774429', 'SID951375965067'),
('+918824122936', 'SSF2762031'),
('+919838012188', 'SSF5990586'),
('+916398447692', 'SSF4797016'),
('+918317082793', 'SSF5226780'),
('+916299540368', 'SSF3508728'),
('+917250396506', 'SSF3548775'),
('+919992084568', 'SSF3000871'),
('+917294017675', 'SSF3342923'),
('+918540961495', 'SSF5252350'),
('+919801655795', 'SID951373796272'),
('+918057007656', 'SSF4366828'),
('+917392006060', 'SSF5669586'),
('+917633889588', 'SSF5473462'),
('+917324995520', 'SSF5997542'),
('+919770098242', 'SID951373810570'),
('+917033792176', 'SSF5117405'),
('+917643833213', 'SSF2341892'),
('+918349939489', 'SSF2605956'),
('+918299641741', 'SSF4888562'),
('+918102553453', 'SID951375775954'),
('+916307251149', 'SSF5801858'),
('+917759853460', 'SSF2643431'),
('+918579929407', 'CID951376204340'),
('+917479486100', 'SSF3310686'),
('+917234017040', 'SSF2540945'),
('+918115000136', 'SSF5113740'),
('+919341721249', 'SSF5567643'),
('+919835025286', 'SSF4919473'),
('+918810355739', 'SSF5122889'),
('+918127923243', 'SSF3029394'),
('+919369613040', 'SSF3492933'),
('+919675515086', 'SSF5507772'),
('+918511733745', 'SID951376155143'),
('+919111592069', 'SSF4584635'),
('+919661075924', 'SSF5166390'),
('+918797749365', 'SSF2436035'),
('+917355696744', 'SSF4930960'),
('+916268857865', 'SID951374230401'),
('+919719941559', 'SSF5731132'),
('+917739491389', 'SID951374170020'),
('+917459087780', 'SSF2909018'),
('+919039820677', 'SSF2817585'),
('+919631836381', 'SSF4571675'),
('+916397167039', 'SSF5883803'),
('+917587436713', 'SSF6191972'),
('+918252107721', 'SSF5104648'),
('+917489764264', 'SID951375979812'),
('+918449796008', 'SSF6382184'),
('+918922033738', 'SSF6180967'),
('+919235384089', 'SSF6165431'),
('+918921378014', 'SSF5195359'),
('+919817042122', 'SSF5879107'),
('+917404590331', 'SSF5564034'),
('+919993283488', 'SID951375982040'),
('+918319569699', 'SSF2289054'),
('+919155312047', 'SID951374487839'),
('+916268030613', 'CID219405994'),
('+918986094827', 'SSF4624446'),
('+916375535384', 'SSF4676288'),
('+918208564799', 'SSF6072507'),
('+918677941807', 'SSF6257131'),
('+919234853902', 'SSF2926882'),
('+918235641100', 'SID951376193878'),
('+918294764834', 'SSF5712099'),
('+916202665712', 'SSF5377573'),
('+916262172118', 'SID951373040395'),
('+918789250278', 'SSF5991526'),
('+918979978730', 'SSF4999755'),
('+916232349413', 'SID951375418308'),
('+916595949494', 'SSF3144670'),
('+919580394660', 'SSF3566089'),
('+919241340317', 'SSF5695573'),
('+919865656565', 'SSF3292988'),
('+919709464826', 'SID951376149746'),
('+917409203438', 'SSF5440645'),
('+918651841776', 'SSF5798997'),
('+919301579209', 'SSF3728834'),
('+919303391809', 'SSF3007915'),
('+916305077820', 'SSF4391832'),
('+916378372146', 'SSF3952242'),
('+917250102460', 'SSF4922366'),
('+917223883247', 'SSF4091932'),
('+917321983354', 'SSF4832431'),
('+917482989469', 'SSF4374551'),
('+917461986035', 'SSF3734051'),
('+917631251324', 'SSF4699512'),
('+918507004424', 'SSF4490780'),
('+918969480720', 'SSF4509589'),
('+918936885455', 'SSF5233839'),
('+919123164301', 'SSF4340186'),
('+919142490938', 'SSF2519826'),
('+919546181714', 'SSF4707268'),
('+917392009144', 'SSF5763268'),
('+919118408024', 'SSF5231651'),
('+917528027889', 'SSF5620565'),
('+917320993848', 'SSF4328565'),
('+917004212451', 'SSF5528267'),
('+917542094108', 'SSF5507608'),
('+918084973222', 'SSF5356888'),
('+919955081005', 'SSF6223432'),
('+919006467679', 'SSF5969194'),
('+917869081184', 'SID2125276234'),
('+918817592394', 'SID951372818539'),
('+916266374616', 'SID2125736976'),
('+917976361694', 'SID951375241118'),
('+917479857597', 'SSF5124528'),
('+917068805066', 'SSF5154293'),
('+917479439133', 'SSF4313209'),
('+917856851055', 'SSF4221779'),
('+918800107646', 'SSF5585097'),
('+919772920574', 'SID951374584481'),
('+919262686846', 'SSF5124562'),
('+919519117382', 'SSF5665405'),
('+919155808717', 'SSF5952666'),
('+919608561499', 'SSF5413102'),
('+919102737904', 'SSF5600066'),
('+919120992834', 'SSF5257013'),
('+916203648199', 'SSF4492073'),
('+916205046857', 'SSF4489017'),
('+916266332626', 'SSF4317606'),
('+916266953896', 'SSF3874992'),
('+916261421680', 'SSF5214037'),
('+916387639330', 'SSF4108164'),
('+916207315163', 'SSF4416651'),
('+917600482911', 'SSF4516475'),
('+917802983237', 'SSF4465772'),
('+917067435789', 'SSF4813036'),
('+917524925350', 'SSF3231000'),
('+917979775780', 'SSF4521529'),
('+917986906142', 'SSF3680386'),
('+917727830423', 'SSF4316072'),
('+917091548379', 'SSF4349327'),
('+917488786645', 'SSF4113391'),
('+917976680451', 'SSF2855850'),
('+917061003814', 'SSF4010778'),
('+917041104157', 'SSF4029190'),
('+918602630364', 'SSF4098753'),
('+918434906620', 'SSF3120996'),
('+918604635957', 'SSF2825414'),
('+918235988571', 'SSF5559873'),
('+918853084744', 'SID951374841845'),
('+918604121938', 'SSF4527090'),
('+918306205317', 'SSF3959517'),
('+919279640285', 'SSF4143984'),
('+919934664197', 'SSF4700491'),
('+919098016274', 'SSF3400567'),
('+919234182251', 'SSF3241849'),
('+919162039034', 'SSF4120597'),
('+919965214855', 'SID951372939762'),
('+919130326094', 'SSF3455107'),
('+919113409351', 'SSF3965346'),
('+919131944952', 'SSF4079426'),
('+919559225943', 'SSF4053615'),
('+919109043055', 'SSF3065075'),
('+919973406635', 'SSF3799096'),
('+919636117136', 'SSF4027540'),
('+919102026133', 'SSF4120841'),
('+919576650866', 'SSF4238429'),
('+919009953734', 'SSF4655117'),
('+919905343455', 'SSF4273900'),
('+919549564893', 'SSF2989738'),
('+919905527449', 'SSF4207269'),
('+916388895920', 'SSF4221995'),
('+917054903059', 'SSF5049643'),
('+917292999782', 'SSF4386765'),
('+918957363279', 'SSF5049427'),
('+918303017392', 'SSF5397678'),
('+918126572452', 'SSF5037302'),
('+918429603003', 'SSF5211467'),
('+918298997468', 'SSF5376845'),
('+919651433828', 'SSF5512882'),
('+919580361134', 'SSF4641110'),
('+919570824024', 'SSF5166514'),
('+919279847059', 'SSF4619966'),
('+919241108852', 'SSF4768868'),
('+919113744902', 'SSF4831971'),
('+919076560567', 'SSF5277474'),
('+916205559809', 'SSF4966719'),
('+916207711415', 'SSF4966574'),
('+916389457568', 'SSF5257044'),
('+917992452168', 'SSF5074994'),
('+918058615604', 'SSF5877763'),
('+919241834803', 'SSF5185734'),
('+919536924819', 'SSF4484129'),
('+917858821716', 'SSF4323021'),
('+916389269428', 'SSF4389492'),
('+917985077157', 'SSF5042866'),
('+918858597404', 'SSF3930677'),
('+916264121902', 'CID213703421'),
('+916205478562', 'SSF3193843'),
('+916297849818', 'SSF3159599'),
('+916204551667', 'SSF3861118'),
('+916200755301', 'SSF3936503'),
('+916499469193', 'SSF3888205'),
('+917321003513', 'SSF4499024'),
('+917004273364', 'SSF4295012'),
('+917903384521', 'SSF4240829'),
('+917667089910', 'SSF4258536'),
('+917989750272', 'SSF4178566'),
('+917518510748', 'SSF2394078'),
('+917667128589', 'SSF3296328'),
('+917398101216', 'SSF2971698'),
('+917463075024', 'SSF4563914'),
('+917250689912', 'SSF4638534'),
('+917209391698', 'SSF4146074'),
('+917857099402', 'SSF3871372'),
('+917759036725', 'SSF4246836'),
('+917209069518', 'SSF4204197'),
('+918686868686', 'SSF3848550'),
('+918976796765', 'SSF3961766'),
('+918340727543', 'SSF4714618'),
('+918102955994', 'SSF3920043'),
('+918928519783', 'SSF4940886'),
('+918298867695', 'SSF4238508'),
('+918809087308', 'SSF2895313'),
('+918292430011', 'SSF3117494'),
('+919334379994', 'SSF3882548'),
('+919304404986', 'SSF3769159'),
('+919783115209', 'SSF4282752'),
('+919865655888', 'SSF3873997'),
('+919669387629', 'SSF3125853'),
('+919572886563', 'SSF4250468'),
('+919955335856', 'SSF4864252'),
('+919171503282', 'SSF2960846'),
('+919888757978', 'SSF3711552'),
('+919308773220', 'SID951374260194'),
('+919102310176', 'SSF4357334'),
('+919548650951', 'SSF5392073'),
('+919305825642', 'SSF4659929'),
('+916200532885', 'SSF3664751'),
('+919109948337', 'SSF4242085'),
('+919060885736', 'SSF2512922'),
('+919835423720', 'SSF4158060'),
('+919559326837', 'SSF4418308'),
('+916266593345', 'SSF3165109'),
('+917070509329', 'SSF4589843'),
('+917634040732', 'SSF4338681'),
('+918085152791', 'SSF5953118'),
('+918102957798', 'SSF4352602'),
('+919608687855', 'SSF4701847'),
('+916205590050', 'SID951375979047'),
('+916268144314', 'SID951374469451'),
('+916430494464', 'SSF3580228'),
('+916200580558', 'SSF3619692'),
('+916265809752', 'SID951374975382'),
('+916266643868', 'SSF3753048'),
('+916243119191', 'SSF3683165'),
('+916254689768', 'SSF3792719'),
('+917854652388', 'SID951374886894'),
('+917974874730', 'SSF3697671'),
('+917481008467', 'SSF3511841'),
('+917327567357', 'SSF3686895'),
('+917070411149', 'SID951375348229'),
('+917070369074', 'SSF3904204'),
('+918777855690', 'SID951375957229'),
('+918645469154', 'SSF3704805'),
('+918094246073', 'SSF3839231'),
('+918889033969', 'SSF4072903'),
('+918805937265', 'SSF3515587'),
('+918292584425', 'SID951375866284'),
('+918290571805', 'SSF3822395'),
('+918210032732', 'SSF3884108'),
('+918290862096', 'SSF3600229'),
('+918579707979', 'SSF3547647'),
('+918839552314', 'SSF3557516'),
('+918084892394', 'SSF4323843'),
('+918945264845', 'SSF3649613'),
('+919996767970', 'SID951376177796'),
('+919617979787', 'SSF3577894'),
('+919199727294', 'SSF3727074'),
('+919162547480', 'SSF3737619'),
('+919257807509', 'SSF3820001'),
('+919329144615', 'SSF3033137'),
('+919786498688', 'SSF3625873'),
('+919631337522', 'SID951375593157'),
('+919797979955', 'SSF3721947'),
('+919304013800', 'SSF3586491'),
('+919658682868', 'SSF3770451'),
('+919649787979', 'SSF3547673'),
('+919617877446', 'SSF3836543'),
('+919939503985', 'SID951373300330'),
('+919797968668', 'SSF3595462'),
('+919877131214', 'SSF4070081'),
('+919257809320', 'SSF3964611'),
('+917765070200', 'SID951375723497'),
('+919001624830', 'SSF2489553'),
('+917079570669', 'SSF4656647'),
('+916698223825', 'SSF3666059'),
('+916352852141', 'SSF3551657'),
('+916375438154', 'SSF3840883'),
('+916565656565', 'SSF3575658'),
('+916367498069', 'SSF3824891'),
('+916855470514', 'SID951375175259'),
('+916563868388', 'SSF3625245'),
('+916588588858', 'SSF3678112'),
('+917896541230', 'SSF3541186'),
('+917877742074', 'SID951374472534'),
('+917426024511', 'SSF3717016'),
('+917547089688', 'SSF2375278'),
('+917676676866', 'SSF3567348'),
('+917903288351', 'SSF2938244'),
('+917070889050', 'SID951375455271'),
('+917649484894', 'SID951376150474'),
('+917781926413', 'SID951375259438'),
('+917897348951', 'SSF3615194'),
('+917549101528', 'SSF3655284'),
('+917488610488', 'SSF3696862'),
('+917256847285', 'SSF3625052'),
('+917021494791', 'SSF3636629'),
('+918905735606', 'SSF4209822'),
('+918242354869', 'SSF3198890'),
('+918665477789', 'SSF3684074'),
('+918084701004', 'SSF3547942'),
('+918764155457', 'SSF3622903'),
('+918502336698', 'SSF2777098'),
('+918252390366', 'SSF3715766'),
('+918554551547', 'SSF3567340'),
('+918810662140', 'SSF4079764'),
('+918949054418', 'SSF3433486'),
('+918227908393', 'SSF3257513'),
('+919835795480', 'SSF3887837'),
('+919340492346', 'SSF4563030'),
('+919568676467', 'SID951376150263'),
('+919234871969', 'SSF3380621'),
('+919464649191', 'SSF3615196'),
('+919437975797', 'SSF3807048'),
('+919764646446', 'SSF3451508'),
('+919059175231', 'SSF3848836'),
('+919908513257', 'SSF3738590'),
('+919886695452', 'SSF3651309'),
('+919834646486', 'SSF3679133'),
('+919434649565', 'SSF2836882'),
('+919955586767', 'SSF3452305'),
('+919801033063', 'SSF3164832'),
('+919649454758', 'SSF3666402'),
('+919102571795', 'SSF3430354'),
('+919113172093', 'SSF3471010'),
('+919939355008', 'SSF3612781'),
('+919905596588', 'SSF3644026'),
('+919116874699', 'SSF3084929'),
('+919449494878', 'SSF3239823'),
('+919608874701', 'SSF3881777'),
('+919673757766', 'SSF3433234'),
('+919521820285', 'SSF2893560'),
('+919546398673', 'SSF3301925'),
('+918360268085', 'SSF4874713'),
('+919412850445', 'SSF4561908'),
('+916393337592', 'SSF4787454'),
('+919934906909', 'SSF4797315'),
('+919793646141', 'SSF4129658'),
('+919580329097', 'SSF4129657'),
('+917646040712', 'SSF5338691'),
('+918320511194', 'SSF4428958'),
('+917761893743', 'SSF5016083'),
('+918368312950', 'SSF5025730'),
('+918102561275', 'SSF5059287'),
('+918434435485', 'SSF5177324'),
('+916280026554', 'SSF5248790'),
('+918000180139', 'SSF4772383'),
('+919771212012', 'SSF5175232'),
('+917992170998', 'SSF4177074'),
('+916203423051', 'SSF4099234'),
('+918194867989', 'SSF3876076'),
('+918880008889', 'SSF3585866'),
('+919577638091', 'SSF3743562'),
('+919618900882', 'SSF3787328'),
('+918948812613', 'SSF3604766'),
('+918769789853', 'SSF3749518'),
('+919128656655', 'SID951375562338'),
('+919978845162', 'SID951375481467'),
('+919691322864', 'SSF4087173'),
('+919828545212', 'SSF3907111'),
('+916377040994', 'SID951375284005'),
('+919636948080', 'SSF3718327'),
('+917230927399', 'SSF3750745'),
('+918081865952', 'SSF3159165'),
('+918209381775', 'SSF3777765'),
('+918930379773', 'SSF2651144'),
('+917870158604', 'SSF2831734'),
('+917081519427', 'SSF2736344'),
('+919789979889', 'SSF2983924'),
('+918854865586', 'SSF3164968'),
('+917737805070', 'SSF2769261'),
('+918252341545', 'SSF2589043'),
('+918522500000', 'SSF2508586'),
('+919354358358', 'SSF2649894'),
('+919375456446', 'SSF2612390'),
('+919070033836', 'SSF3340484'),
('+918969909598', 'SID951375991790'),
('+919494949496', 'SSF3677949'),
('+919496097646', 'SSF2807781'),
('+918956232142', 'SSF3145603'),
('+919631637457', 'SSF3270752'),
('+919464943959', 'SSF3096147'),
('+918278634031', 'SSF3238322'),
('+919973494346', 'SSF3368905'),
('+917857848464', 'SSF2996990'),
('+919557756680', 'SSF3790218'),
('+919587752813', 'SSF2773027'),
('+919767679434', 'SID951376240064'),
('+919672800769', 'SSF2726593'),
('+918546656746', 'SSF3795497'),
('+918817118773', 'SSF3353088'),
('+918572835652', 'SSF3429903'),
('+919905300240', 'SSF3230608'),
('+919006215654', 'SSF2936125'),
('+919571764948', 'SSF2897035'),
('+919664219797', 'SSF2906072'),
('+918260504624', 'SSF3964945'),
('+916880868899', 'SID951375370280'),
('+918833284588', 'SID951375940870'),
('+918875075803', 'SSF3173609'),
('+919829160541', 'SSF3279927'),
('+919797948484', 'SSF3279875'),
('+919854312797', 'CID204501877'),
('+916299415103', 'SSF2877767'),
('+917260016332', 'SID951374149709'),
('+917639077493', 'SID951375936880'),
('+917318341455', 'SSF2419742'),
('+918210564631', 'SID951375057769'),
('+916207930678', 'SSF4659411'),
('+916204869160', 'SSF4658692'),
('+916268187444', 'SSF4168047'),
('+916206798568', 'SSF4327919'),
('+916209362251', 'SSF4107797'),
('+916201079069', 'SSF3630928'),
('+917357666009', 'SSF5158736'),
('+917318175324', 'SSF5746180'),
('+917067920044', 'SSF2450223'),
('+917480967054', 'SSF4560568'),
('+917033610037', 'SSF3315134'),
('+917260022143', 'SSF5944531'),
('+917319961792', 'SSF4433626'),
('+917739073132', 'SSF4718899'),
('+917061068095', 'SSF4609906'),
('+917782920488', 'SSF4143513'),
('+917808865004', 'SSF3586503'),
('+917070756406', 'SSF4607533'),
('+917033122719', 'SSF3239535'),
('+917250904652', 'SSF4888634'),
('+917858015718', 'SSF3180551'),
('+917061323238', 'SSF4120471'),
('+917766996220', 'SSF4548033'),
('+918521579667', 'SSF2998669'),
('+918527461430', 'SSF4970506'),
('+918409629040', 'SSF4443048'),
('+918252740478', 'SSF4658995'),
('+918084279088', 'SSF4421727'),
('+918210658270', 'SSF4494986'),
('+918252682301', 'SSF6051844'),
('+918452034899', 'SSF4370541'),
('+918409528138', 'SSF4530560'),
('+918809503434', 'SSF4692642'),
('+918252465340', 'SSF4890637'),
('+918409614998', 'SSF3059683'),
('+918800313664', 'SSF4199277'),
('+918629900129', 'SSF3763025'),
('+918809671911', 'SSF4707430'),
('+919122545222', 'SSF4505393'),
('+919263138976', 'SSF4602184'),
('+919031583457', 'SSF4530313'),
('+919801928183', 'SSF2904351'),
('+919102741155', 'SSF4647230'),
('+919606642251', 'SSF4570349'),
('+919693366991', 'SSF5375748'),
('+919572313841', 'SSF4364064'),
('+919098189887', 'SSF4045577'),
('+919919129566', 'SSF4504264'),
('+919934853915', 'SSF4117026'),
('+919110100532', 'SSF4594147'),
('+919279845280', 'SSF4082979'),
('+919118626435', 'SSF4118520'),
('+919905912845', 'SSF4325866'),
('+919934274362', 'SSF4183217'),
('+919835511022', 'SSF4502031'),
('+919122691943', 'SSF4132999'),
('+919304246364', 'SSF4560543'),
('+919028488356', 'CID224402533'),
('+919572502348', 'SSF5234233'),
('+919661100865', 'SSF4985713'),
('+919045276042', 'SSF5263791'),
('+917667260742', 'SSF5310770'),
('+917497817741', 'SSF6243602'),
('+917209166329', 'SSF5356354'),
('+917033736348', 'SSF5507349'),
('+919576217930', 'SSF5338246'),
('+919721443351', 'SSF5127638'),
('+919122089132', 'SSF5418722'),
('+919523130768', 'SSF5472506'),
('+919229133609', 'SSF6202803'),
('+917000856041', 'SID951373143001'),
('+917739504891', 'SSF5248124'),
('+917352132583', 'SSF5350763'),
('+918539919802', 'SSF5352295'),
('+919303932179', 'SID117623'),
('+919234130813', 'SSF5262760'),
('+919570813975', 'SSF5258720'),
('+916207944564', 'SSF4518028'),
('+916268938068', 'SSF3947948'),
('+917250586552', 'SID951374211987'),
('+917357437236', 'SID951376038566'),
('+917250220941', 'SSF4441685'),
('+917068567241', 'SSF4108182'),
('+917903882116', 'SSF4165009'),
('+917541800693', 'SSF3391087'),
('+918757709980', 'SID951376196668'),
('+918585895372', 'SSF3590484'),
('+918789324318', 'SSF4483157'),
('+918949799753', 'SSF4005441'),
('+918962958584', 'SSF2324368'),
('+919691154014', 'SSF5514685'),
('+919024363180', 'SSF3948932'),
('+919835500385', 'SSF4083058'),
('+919584419505', 'SSF5391316'),
('+919262770231', 'SSF4395693'),
('+919024623183', 'SSF4027794'),
('+916202836663', 'SSF5210136'),
('+917398428195', 'SSF5491016'),
('+917033574107', 'SSF6082720'),
('+919759496732', 'SSF5881962'),
('+916206820371', 'SSF3997182'),
('+916207904640', 'SSF4301475'),
('+916206645693', 'SSF4268004'),
('+916585865656', 'SID951373322091'),
('+916203831642', 'SID2125650890'),
('+916354559385', 'SID951374691666'),
('+916202217347', 'SSF4136210'),
('+916325689555', 'SID951374679055'),
('+917879170438', 'SID951373182742'),
('+917828237380', 'SSF4008834'),
('+917673027144', 'SID951375991848'),
('+917295099880', 'SSF4312378'),
('+917024617775', 'SSF4334571'),
('+917781891625', 'SID951375629103'),
('+917979024992', 'SSF4105835'),
('+917992314704', 'SSF3117490'),
('+918103358775', 'SSF4088696'),
('+918731974618', 'SID951376104583'),
('+918255245848', 'SSF3862683'),
('+918084421353', 'SSF4300574'),
('+918789356596', 'SSF4864242'),
('+918757461537', 'SSF3941756'),
('+918873639770', 'SSF4319740'),
('+918757947109', 'SSF2855849'),
('+919796494994', 'SSF3539836'),
('+919631828779', 'SID951375378352'),
('+919693803677', 'SSF2928253'),
('+919006057788', 'SSF4314546'),
('+919263495594', 'SSF4575500'),
('+919256158242', 'SSF4003918'),
('+919865383467', 'SSF2334325'),
('+919060590292', 'SSF4118322'),
('+917398431857', 'SSF3888308'),
('+917084335221', 'SSF4452847'),
('+918470878231', 'SSF3871141'),
('+918122254753', 'SSF4801865'),
('+919569512227', 'SSF4916501'),
('+917761093698', 'SSF5111781'),
('+919368834878', 'SSF5540910'),
('+916299808771', 'SSF4067860'),
('+918862947007', 'SSF4624232'),
('+918340280313', 'SSF2517617'),
('+919557957975', 'SSF3842980'),
('+918602380532', 'SID2125257011'),
('+916294984810', 'SSF3470050'),
('+916202916519', 'SSF3895886'),
('+916350875464', 'SSF3577344'),
('+916267256157', 'SSF3679626'),
('+916299017282', 'SSF3914648'),
('+916207618454', 'SSF4339599'),
('+917067080654', 'SSF3803806'),
('+917439096205', 'SSF3627711'),
('+917479824096', 'SSF2839224'),
('+917847888505', 'SSF3871489'),
('+917765476755', 'SSF3458180'),
('+917000898485', 'SSF2763518'),
('+918770617841', 'SSF4673615'),
('+918596584649', 'SSF3691350'),
('+918603345656', 'SSF3443093'),
('+918568866558', 'SID951376156486'),
('+918815037939', 'SSF3658134'),
('+918752545666', 'SSF3674465'),
('+918549581328', 'SID951375405903'),
('+918235175453', 'SSF2886623'),
('+918209756626', 'SSF3731220'),
('+918651574867', 'SSF3749957'),
('+918709521693', 'SID951375900344'),
('+919521052571', 'SSF5323353'),
('+919199728062', 'SSF2858045'),
('+919153549926', 'SID951375414013'),
('+919279446140', 'SSF3593358'),
('+919301675634', 'SSF3515444'),
('+919212495398', 'SID951375948625'),
('+919345021718', 'SSF4840063'),
('+919767548967', 'SSF3429254'),
('+919324967535', 'SSF3760634'),
('+919507411202', 'SSF3626540'),
('+919340329193', 'SSF4421089'),
('+916201471018', 'SSF3598756'),
('+917294030200', 'SSF4378215'),
('+918936048862', 'SSF4219425'),
('+918058878372', 'SSF3284539'),
('+918815495063', 'SSF3200612'),
('+918603283328', 'SSF4380026'),
('+918271816765', 'SSF4378226'),
('+918506897161', 'SSF3357728'),
('+919838774768', 'SSF4209667'),
('+919631593771', 'SSF3015487'),
('+919153755510', 'SSF5581803'),
('+919006532197', 'SSF3061958'),
('+918605242299', 'SID951373144906'),
('+916434243443', 'SSF2770594'),
('+916265669890', 'SID951376136964'),
('+916231949488', 'SSF3721962'),
('+916005917580', 'SSF3866928'),
('+916235868605', 'SSF3559313'),
('+916296526032', 'SSF3720649'),
('+916888525090', 'SSF3678068'),
('+917319856361', 'SSF3179864'),
('+917415765689', 'SSF3415999'),
('+917230846614', 'SSF3649671'),
('+917545802801', 'SSF3354437'),
('+917665877506', 'SSF3719013'),
('+917414235544', 'SSF2960190'),
('+917564937833', 'SSF3603937'),
('+917480933911', 'SSF3866977'),
('+917004994108', 'SID951374679056'),
('+917541099741', 'SSF3668695'),
('+917155498888', 'SSF3618575'),
('+917307995012', 'SSF3782462'),
('+918454532217', 'SSF3286086'),
('+918769555865', 'SSF3828852'),
('+918854976338', 'SID951375955351'),
('+918754642194', 'SSF3502474'),
('+918769013439', 'SSF3316117'),
('+918249346826', 'SSF3714961'),
('+918873898954', 'SSF3831833'),
('+918290248221', 'SSF3323799'),
('+918084884444', 'SSF3667169'),
('+918368120535', 'SSF3576355'),
('+918852085294', 'SSF4194163'),
('+918434958248', 'SSF3360148'),
('+918655575788', 'SSF3678246'),
('+919572335640', 'SID951373012478'),
('+919358396562', 'SSF3848069'),
('+919431944319', 'SSF2845076'),
('+919982135512', 'SSF3683158'),
('+919521708633', 'SSF3717053'),
('+919262938975', 'SSF3697066'),
('+919351937782', 'SID951375039348'),
('+919468484684', 'SID951375609261'),
('+919122216298', 'SSF3595699'),
('+919994845464', 'SSF3506969'),
('+919060177755', 'SSF4160716'),
('+919370740085', 'SSF3430185'),
('+919166094755', 'SSF3632447'),
('+919654123874', 'SSF3574811'),
('+919767643465', 'SID951375926578'),
('+919708465135', 'SSF3598091'),
('+919408734565', 'SSF3452178'),
('+919672043613', 'SSF3493512'),
('+919153797992', 'SSF3401329'),
('+919284548484', 'SSF3884580'),
('+919587878787', 'SSF3884579'),
('+919654848448', 'SSF3862214'),
('+916205047050', 'SSF5613352'),
('+918172957261', 'SSF4482275'),
('+918446997749', 'SSF4268075'),
('+918791903372', 'SSF5721809'),
('+916207287108', 'SSF5016038'),
('+919761549711', 'SSF5767768'),
('+919358668432', 'SSF5816953'),
('+918252056221', 'SSF5208505'),
('+917903607516', 'SSF4782347'),
('+918051307762', 'SSF4794184'),
('+919076958248', 'SSF3838603'),
('+918998959959', 'SSF3678023'),
('+919263276448', 'SSF4510633'),
('+919766767677', 'SSF3657260'),
('+918607165506', 'SID951376023039'),
('+918542697665', 'SSF3667757'),
('+919856321455', 'SSF3320664'),
('+918051876253', 'SSF3715693'),
('+918955904393', 'SSF2318538'),
('+917288456554', 'SID951376155070'),
('+919794949464', 'SSF3518978'),
('+919691384180', 'SSF4087195'),
('+919631472510', 'SSF3593957'),
('+919694722125', 'SSF4303374'),
('+918006883074', 'SSF2888838'),
('+919335488331', 'SSF3366687'),
('+919350700289', 'SID951376019616'),
('+919889797844', 'SID951375337916'),
('+918652246688', 'SSF3437130'),
('+917857864450', 'SSF4670506'),
('+919508537925', 'SSF4670479'),
('+919340753510', 'SID951376004283'),
('+918880000558', 'SSF2508557'),
('+918582043309', 'SSF3290107'),
('+919138646064', 'SSF3611304'),
('+916376816029', 'SSF2683893'),
('+916280395058', 'SSF3256106'),
('+918999022198', 'SID951374817327'),
('+917073085422', 'SSF3064025'),
('+919784478917', 'SSF2827513'),
('+919785469469', 'SSF3316644'),
('+918306729727', 'SSF3978265'),
('+917254820341', 'SSF2819380'),
('+917816139104', 'SSF3531822'),
('+919878797979', 'SSF2827736'),
('+919610523130', 'SSF3198593'),
('+918789599146', 'SSF3295212'),
('+919358515734', 'SID951375826767'),
('+919153484204', 'SSF3367089'),
('+919414454885', 'SSF2767548'),
('+917412848969', 'SSF2996932'),
('+919785468576', 'SSF2701997'),
('+918586995532', 'SSF3134152'),
('+919585649763', 'SSF3426731'),
('+919098575421', 'SSF3370750'),
('+919658854489', 'SSF3075942'),
('+919571456899', 'SSF2897036'),
('+919867349831', 'SSF3092689'),
('+917997966444', 'SSF3121785'),
('+918305164263', 'SSF3166536'),
('+919340248533', 'SID951376106370'),
('+916267234070', 'SSF5212791'),
('+919358751032', 'SID951374045921'),
('+919334956525', 'SID951374629293'),
('+917878978477', 'SID951375532928'),
('+919199875991', 'SSF4067940'),
('+917489730342', 'SSF4551370'),
('+918446123196', 'SSF6085827'),
('+919569767326', 'SSF3325676'),
('+919835808045', 'SSF4171994'),
('+916201238054', 'SSF4493908'),
('+919580902863', 'SSF5752647'),
('+916354639479', 'SSF4555827'),
('+918957409535', 'SSF5008937'),
('+918936863975', 'SSF5765190'),
('+917044292679', 'SSF5516799'),
('+919708347509', 'SID951375495976'),
('+917856981415', 'SSF5698361'),
('+917463904700', 'SSF6145732'),
('+918409591588', 'SSF6017469'),
('+917581016556', 'SSF5763316'),
('+919234738516', 'SSF4686402'),
('+918051597460', 'SSF5544115'),
('+918271558647', 'SSF5756461'),
('+917060723420', 'SSF6040309'),
('+919630976285', 'SID951374575509'),
('+918461098251', 'SSF4348147'),
('+917870336627', 'SSF6029204'),
('+919549634824', 'SSF4846240'),
('+916386999903', 'SSF6179721'),
('+917763024035', 'SSF5719653'),
('+917520328785', 'SID951374108371'),
('+918959749598', 'SSF3310218'),
('+917357471585', 'SID951374426559'),
('+918051540369', 'SSF6271529'),
('+919234321803', 'SSF5657852'),
('+918815326217', 'SSF4294888'),
('+918305897106', 'SSF5070363'),
('+917079961839', 'SSF5663341'),
('+918931052662', 'SSF2933991'),
('+917067727314', 'SSF4750479'),
('+919569121028', 'SSF5720449'),
('+919104983733', 'SSF5809274'),
('+917466987415', 'SSF6023076'),
('+917481909649', 'SSF5943404'),
('+917763945433', 'SID951375648700'),
('+919801579682', 'SSF6308167'),
('+917027334351', 'SSF6079121'),
('+918147915790', 'SSF5085041'),
('+919927912487', 'SSF5326377'),
('+918690383559', 'SID951374519765'),
('+916261104206', 'SID951376223658'),
('+919546104973', 'SSF5711410'),
('+916353357689', 'SID951374084355'),
('+919279918700', 'SSF5638560'),
('+917091523626', 'SSF5923141'),
('+917459012887', 'SSF5831505'),
('+918470818247', 'SSF5234092'),
('+919528908969', 'SSF5833164'),
('+918092445628', 'SSF4969054'),
('+917209518327', 'SSF6337973'),
('+916299389542', 'SSF5716136'),
('+917033655144', 'SSF5466054'),
('+918441829753', 'SID951374760824'),
('+919650016850', 'SSF6532213'),
('+919608634196', 'SSF6532139'),
('+918889867456', 'SSF4461991'),
('+919555621146', 'SSF5726135'),
('+918273302267', 'SSF5067468'),
('+918521017549', 'SID951375261033'),
('+918982012890', 'SSF6551541'),
('+919079068159', 'SSF6520162'),
('+919725641336', 'SSF5227289'),
('+919199101419', 'SSF5703285'),
('+919039545261', 'SID951375405699'),
('+918757318030', 'SSF6315302'),
('+919934768989', 'SSF5081290'),
('+919771160645', 'SSF6242825'),
('+919798272221', 'SSF6248659'),
('+919875767212', 'SSF3037753'),
('+917987653518', 'SSF5373150'),
('+919939288695', 'SSF6248768'),
('+918863867227', 'SSF4573582'),
('+919690179715', 'SSF6148550'),
('+917878013302', 'SSF4886413'),
('+916299225890', 'SSF6144394'),
('+919060396782', 'SSF3083460'),
('+916207765752', 'SID951374278486'),
('+917091970522', 'SSF5546517'),
('+917294812004', 'SID951373874694'),
('+916268381191', 'SSF5127517'),
('+917488598949', 'SSF4804337'),
('+918050275916', 'SSF6509138'),
('+918957180127', 'SSF5673630'),
('+918340133796', 'SSF5141662'),
('+917224973125', 'SID2125267454'),
('+919113116057', 'SSF6113998'),
('+916367224691', 'SSF6043172'),
('+919576901949', 'SSF5432699'),
('+919264245360', 'SSF5302321'),
('+919024648421', 'SID951374744960'),
('+919302381632', 'SSF2599651'),
('+918936842201', 'SID951375597330'),
('+919935136792', 'SSF5774251'),
('+919102716619', 'SSF5702379'),
('+917587373734', 'SSF6342294'),
('+918137911771', 'SID951373895100'),
('+919302469428', 'SID951375078062'),
('+918528612789', 'SSF5646666'),
('+918854994371', 'SSF3157440'),
('+917610164104', 'SID951375841954'),
('+917722959711', 'SID951373220311'),
('+919036344462', 'SSF3928471'),
('+917857965708', 'SID951375246448'),
('+919528786233', 'SSF5094037'),
('+918115547518', 'SSF4796802'),
('+917697670406', 'SSF6217468'),
('+917631530936', 'SSF5296257'),
('+917781994758', 'SSF5833343'),
('+917354322110', 'SID951376049778'),
('+918052502173', 'SSF5945141'),
('+917439062423', 'SID951374771337'),
('+918298873023', 'SSF4867036'),
('+916387649672', 'SSF5957885'),
('+916207259538', 'SSF6499526'),
('+917828727486', 'SSF4471226'),
('+917793041154', 'SSF2442083'),
('+916280055670', 'SSF5463254'),
('+918235456011', 'SID951373160498'),
('+919721103454', 'SSF3206210'),
('+919142600162', 'SSF5810838'),
('+917250492340', 'SSF5436757'),
('+917587493306', 'SID951375265755'),
('+916375002937', 'SSF3353436'),
('+919784838653', 'SSF3254700'),
('+919368775112', 'SSF4647701'),
('+919329202208', 'SSF6519497'),
('+919098720336', 'SSF6228969'),
('+916266277831', 'SID951375933561'),
('+918817803282', 'SSF6208674'),
('+918374292810', 'SID951375443588'),
('+918795273098', 'SID951374707260'),
('+916238917355', 'SID951374770601'),
('+919122670932', 'SSF5725166'),
('+919867342839', 'SSF6393500'),
('+919676189308', 'SSF5663378'),
('+918667696768', 'SSF6500124'),
('+918084015599', 'SSF5263950'),
('+917765980624', 'SSF3377175'),
('+918871819279', 'SSF6515217'),
('+917081350152', 'SSF2929604'),
('+917654318392', 'SID951375842719'),
('+918130809548', 'SSF5212922'),
('+919991170531', 'SSF6073668'),
('+919861096192', 'SSF4751967'),
('+917067271773', 'SID951374716037'),
('+919631816866', 'SSF5662584'),
('+919174215732', 'SSF4970821'),
('+917724807249', 'SID951376213998'),
('+916261667384', 'SID951373906436'),
('+918112778552', 'SSF4906617'),
('+919244263026', 'SID951375997211'),
('+919525613769', 'SSF6137901'),
('+918606867038', 'SSF6196062'),
('+917667891981', 'SSF4961465'),
('+919007800319', 'SSF5027909'),
('+918709780233', 'SSF5964219'),
('+918248767648', 'SSF3139173'),
('+918292759639', 'SSF6077841'),
('+917542984345', 'SSF5448982'),
('+918827268539', 'SID951375050028'),
('+917728956787', 'SSF5503867'),
('+917250237917', 'SSF4742877'),
('+919990606796', 'SSF5211209'),
('+917367882402', 'SSF5935256'),
('+917901708084', 'SSF5712903'),
('+919335542972', 'SSF6389820'),
('+919986534124', 'SSF5919625'),
('+917073786914', 'SSF2676709'),
('+916284787018', 'SSF5459618'),
('+917233859532', 'SSF2611409'),
('+919234262357', 'SSF3711241'),
('+919503843957', 'SSF5726602'),
('+919116287109', 'SSF5066354'),
('+918839876885', 'SSF5093017'),
('+919939727739', 'SSF5393924'),
('+919024878306', 'SSF4221827'),
('+919006353240', 'SSF6468249'),
('+917870256735', 'SSF5882730'),
('+918103543384', 'SSF2895516'),
('+919000973019', 'SSF6441339'),
('+919335431032', 'SSF2816690'),
('+919787340131', 'SSF3523054'),
('+919755987014', 'SID951375941334'),
('+917983947217', 'SSF5730331'),
('+919279302943', 'SSF5348589'),
('+917728815203', 'SSF4405955'),
('+918969149903', 'SSF5611185'),
('+919771229720', 'SSF6402978'),
('+917079501439', 'SSF5555621'),
('+919174225021', 'SSF3985589'),
('+916764646466', 'SID951375930534'),
('+919065256319', 'SSF5298970'),
('+919241932318', 'SID951375954447'),
('+916299289001', 'SID951372959632'),
('+917762995497', 'SSF6181104'),
('+916394807037', 'SSF5645999'),
('+918876794344', 'SID951376129684'),
('+918979406351', 'SSF5612484'),
('+916203831549', 'SSF6189666'),
('+918757290346', 'SSF5755897'),
('+919165904240', 'SID951375424841'),
('+919334052865', 'SSF5393547'),
('+917611143653', 'SID951372812560'),
('+919001424573', 'SID951374039510'),
('+917294136752', 'SSF5975638'),
('+919955148461', 'SSF5335965'),
('+918235578094', 'SSF6426220'),
('+919151167643', 'SSF2649856'),
('+917870199309', 'SSF6109956'),
('+917489231344', 'SSF4924441'),
('+917060842811', 'SSF4959605'),
('+917388537459', 'SSF5850343'),
('+918669800124', 'SSF3481706'),
('+919508007142', 'SSF5160587'),
('+918809643276', 'SID951376208130'),
('+916265969171', 'SSF6270502'),
('+916200458163', 'SSF4716465'),
('+917856959756', 'SSF5238606'),
('+918969594668', 'SSF6127700'),
('+919358399646', 'SSF4001920'),
('+916205628994', 'SSF5590080'),
('+917400215292', 'SSF4564146'),
('+917762992353', 'SSF6016643'),
('+917819892368', 'SID951374116622'),
('+919608895369', 'SSF5113679'),
('+916232808599', 'SSF3642376'),
('+919617973599', 'SID951375644033'),
('+918207521308', 'SSF6074013'),
('+916363480785', 'SSF4404091'),
('+916267421195', 'SSF2832625'),
('+917462096690', 'SSF6058127'),
('+917061020045', 'SSF5593083'),
('+917761096397', 'SSF3993227'),
('+916269452972', 'SID951373625953'),
('+918461913916', 'SID951375560797'),
('+918948820713', 'SSF4913915'),
('+918815912217', 'SID951375895011'),
('+916263647706', 'SID951374254678'),
('+919817619504', 'SSF5312012'),
('+919145465069', 'SSF5455240'),
('+919219727068', 'SSF6028147'),
('+916260235339', 'SSF3992472'),
('+917250984383', 'SSF4733323'),
('+918057582395', 'SSF4959194'),
('+916200851168', 'SSF6023470'),
('+917999839468', 'SID951373950233'),
('+918488093468', 'SSF4710726'),
('+918840635773', 'SSF5774206'),
('+919709748242', 'SSF5447879'),
('+917982105738', 'SSF6032989'),
('+916372588810', 'SSF6130299'),
('+918088208894', 'SSF6051033'),
('+918317716850', 'SSF5759560'),
('+917250050875', 'SSF2682966'),
('+917970386859', 'SSF6289832'),
('+917482053425', 'SSF5801464'),
('+917369048479', 'SSF3848320'),
('+919939100980', 'SID2125695721'),
('+919509476384', 'SID951373934235'),
('+919798177845', 'SSF2939853'),
('+918698854320', 'SSF4791872'),
('+917739946573', 'SSF3633599'),
('+916265929120', 'SID951374871837'),
('+919721803659', 'SSF5050903'),
('+918930772030', 'SSF2559778'),
('+919411863238', 'SSF6482040'),
('+917417302419', 'SSF4663814'),
('+919770499196', 'SSF5138910'),
('+919602404357', 'SID951375289320'),
('+918439820730', 'SSF5733111'),
('+919977165701', 'CID051411414'),
('+918392873639', 'SSF4517518'),
('+919534278023', 'SSF3477174'),
('+918059406057', 'SSF2552288'),
('+917225082950', 'SSF4780441'),
('+918797670420', 'SSF2341970'),
('+919554559684', 'SSF4060649'),
('+919984131908', 'SSF5004089'),
('+919691624868', 'SID951373797835'),
('+916207493450', 'SSF3203913'),
('+917067987172', 'SID2125719609'),
('+917079760162', 'SSF6010412'),
('+916464949494', 'SID2125077620'),
('+916297464977', 'SSF5253467'),
('+916280826148', 'SSF4196601'),
('+916260833253', 'SSF4633618'),
('+916203866359', 'SSF3241453'),
('+916203031359', 'SSF5015902'),
('+916202832236', 'SSF5266105'),
('+917722879200', 'SID2125759108'),
('+917292841826', 'SSF4484430'),
('+917479697943', 'SSF4487258'),
('+917010528136', 'SSF3147246'),
('+917631157345', 'SSF4468110'),
('+917654397469', 'SSF3868646'),
('+917549899247', 'SSF3999033'),
('+917463076730', 'SSF4850138'),
('+917481869046', 'SSF4153499'),
('+917765065035', 'SSF4611111'),
('+917742199296', 'SSF3892125'),
('+917323897296', 'SSF4024282'),
('+917050097403', 'SSF4195013'),
('+917766886610', 'SSF4206911'),
('+918079013075', 'SSF4259483'),
('+918292014660', 'SSF4216124'),
('+918210961457', 'SSF4206798'),
('+918530739049', 'SSF4232175'),
('+918291797566', 'SSF4198461'),
('+918603562819', 'SSF4326345'),
('+918864072931', 'SSF4152815'),
('+918340230295', 'SSF4055193'),
('+918969622808', 'SSF4059067'),
('+918521307251', 'SSF4513351'),
('+918002449541', 'SSF3216354'),
('+919632588888', 'SSF3891645'),
('+919126913541', 'SSF5286576'),
('+919279729385', 'SSF4323944'),
('+919693507702', 'SSF4323992'),
('+919142275497', 'SSF4337209'),
('+919562888885', 'SSF3636194'),
('+919341473121', 'SSF4053285'),
('+919797544324', 'SID951375052228'),
('+919798001677', 'SSF3979589'),
('+919065886735', 'SSF4158512'),
('+919608890668', 'SSF4190954'),
('+919798722449', 'SSF4123658'),
('+919294695731', 'SSF4059481'),
('+919516383689', 'SSF4013101'),
('+919546074270', 'SSF4080371'),
('+919905026585', 'SSF2315638'),
('+919835907189', 'SSF5015856'),
('+919030118069', 'SSF5265905'),
('+919341796732', 'SSF3936799'),
('+919891385886', 'SSF4053143'),
('+919162693226', 'SSF4205950'),
('+917294936911', 'SSF4778461'),
('+917739874233', 'SSF3896830'),
('+919234026279', 'SSF3432842'),
('+917500037621', 'SSF5283531'),
('+919241901824', 'SSF5418789'),
('+916263648753', 'SSF5364078'),
('+916202130833', 'SSF5704160'),
('+917091924632', 'SSF4528522'),
('+917004086582', 'SSF5601290'),
('+917480906171', 'SSF4059767'),
('+918092603822', 'SSF5418403'),
('+918130715633', 'SSF5452896'),
('+918778756970', 'SSF5376409'),
('+919939662190', 'SSF5258190'),
('+919608872268', 'SSF4586651'),
('+917033159207', 'SSF5521564'),
('+917061173508', 'SSF5427624'),
('+917464095173', 'SSF5464454'),
('+917209049165', 'SSF4131129'),
('+919219114291', 'SSF5036624'),
('+919279056652', 'SSF5220531'),
('+919939328986', 'SSF5443064'),
('+919821631959', 'SSF5311308'),
('+919794522591', 'SSF5756479'),
('+916598989989', 'SSF3544079'),
('+916488797497', 'SSF3756893'),
('+916268239731', 'SSF2816810'),
('+916264951255', 'SSF3751585'),
('+916207007450', 'SSF3796662'),
('+916797878767', 'SSF3606268'),
('+916245131818', 'SSF3715778'),
('+916248131818', 'SSF3685727'),
('+916248131181', 'SSF3827043'),
('+916297646191', 'SSF3827049'),
('+916248431801', 'SSF3827061'),
('+916532385686', 'SSF3586856'),
('+916284344848', 'SSF3828971'),
('+916248431840', 'SSF3683201'),
('+916484594584', 'SSF3710521'),
('+916532383568', 'SSF3580202'),
('+916268326721', 'SID951375535267'),
('+917091848678', 'SSF3884597'),
('+917024305789', 'SSF3560764'),
('+917067134718', 'SSF3699752'),
('+917366034495', 'SID951374455771'),
('+917272949413', 'SSF3651366'),
('+917783099673', 'SSF2610238'),
('+917667691034', 'SSF3831879'),
('+917068836992', 'SSF4393324'),
('+917479405852', 'SSF4531508'),
('+917997989556', 'SSF3698725'),
('+918454027410', 'SSF3971905'),
('+918757882482', 'SSF3146630'),
('+918292971616', 'SSF3814087'),
('+918002674152', 'SSF3515609'),
('+918197416224', 'SSF3729030'),
('+918252542801', 'SSF3623287'),
('+918532258884', 'SID951375472266'),
('+918982832079', 'SSF4608982'),
('+918085418657', 'SSF4882883'),
('+918305896033', 'SSF3967300'),
('+918862854061', 'SID951374811916'),
('+918574994459', 'SSF3593788'),
('+919256748151', 'SSF4228901'),
('+919256739049', 'SSF3628978'),
('+919241089935', 'SID951374305490'),
('+919982156450', 'SSF3613659'),
('+919953403382', 'SSF2706384'),
('+919523336851', 'SSF3884531'),
('+919495568464', 'SSF3623753'),
('+919801328554', 'SSF3756855'),
('+919341921793', 'SSF3890786'),
('+919834821473', 'SSF3863077'),
('+919797676768', 'SSF3655044'),
('+919263523346', 'SSF3904892'),
('+919838825682', 'SSF3648347'),
('+919334016667', 'SSF3320758'),
('+919686565655', 'SID951374661718'),
('+919556666544', 'SSF3374527'),
('+919162614392', 'SSF3661615'),
('+919608875178', 'SSF4134330'),
('+919455392916', 'SSF3770965'),
('+919956855758', 'SSF3741182'),
('+919934309669', 'SSF3777174'),
('+919632587419', 'SSF3817557'),
('+919648544884', 'SSF3826002'),
('+919435956595', 'SSF3534243'),
('+916203483926', 'SSF4861143'),
('+916388242293', 'SSF5959724'),
('+917522814788', 'SSF4262407'),
('+917013657653', 'SSF5261740'),
('+918309625316', 'SSF4476739'),
('+918081259287', 'SSF5425246'),
('+918148362798', 'SSF4342846'),
('+917045953564', 'SSF5329178'),
('+917061964005', 'SSF5379208'),
('+918953787588', 'SSF5499909'),
('+919006535980', 'SSF5233630'),
('+919508045766', 'SSF5210413'),
('+918920598219', 'SSF5074031'),
('+919817084231', 'SSF5263494'),
('+916764446649', 'SSF3454731'),
('+916206945829', 'SSF3730576'),
('+916465656656', 'SSF3595112'),
('+916354949404', 'SSF3767032'),
('+916268113352', 'SSF3540041'),
('+916205786488', 'SSF3459021'),
('+916565646488', 'SSF3786434'),
('+916521876789', 'SSF3361980'),
('+916565686566', 'SSF3827753'),
('+916682573523', 'SSF3452176'),
('+916265888552', 'SSF3395681'),
('+916208486488', 'SSF3662818'),
('+917862962668', 'SSF4053118'),
('+917250426411', 'SSF4635379'),
('+917781906252', 'SSF3637544'),
('+917877163828', 'SSF4064937'),
('+917739256072', 'SSF3568868'),
('+917061757511', 'SSF3364062'),
('+917858901703', 'SID951374717129'),
('+917781876720', 'SSF3595293'),
('+918829040569', 'SSF3796678'),
('+918787878575', 'SSF3737596'),
('+918434932903', 'SSF3794944'),
('+918302069342', 'SSF3650621'),
('+918102589660', 'SID951373530044'),
('+918875475032', 'SSF3762990'),
('+918289654855', 'SSF3827520'),
('+918557226845', 'SSF3666665'),
('+918304661198', 'SSF3540857'),
('+918097797979', 'SSF3673854'),
('+918002847997', 'SSF4090992'),
('+918665578746', 'SID951375600693'),
('+918084725148', 'SSF3500192'),
('+918754284858', 'SID951375479513'),
('+918852935720', 'SID951375952014'),
('+918359624095', 'SSF3409328'),
('+918431310485', 'SSF2958902'),
('+918000701265', 'SSF3160644'),
('+918207412934', 'SSF3574214'),
('+918542227647', 'SSF3543424'),
('+918815238497', 'SSF4234508'),
('+918549475755', 'SSF3537741'),
('+919494948448', 'SSF3357382'),
('+919799351122', 'SSF3450299'),
('+919632548599', 'SSF3721032'),
('+919034406930', 'SSF3789160'),
('+919198291078', 'SSF4526537'),
('+919279554484', 'SID951376133960'),
('+919464646438', 'SSF3724394'),
('+919508561940', 'SSF3257846'),
('+919074592974', 'SSF4034665'),
('+919977220601', 'SSF3429126'),
('+919806968689', 'SSF3678959'),
('+919263379094', 'SSF3679464'),
('+919128536716', 'SSF4329344'),
('+919572558420', 'SSF3692027'),
('+919128270798', 'SSF3691978'),
('+919653931757', 'SSF3759690'),
('+919708218566', 'SSF3467195'),
('+919631756110', 'SSF3277206'),
('+919846784884', 'SSF3563852'),
('+919602693759', 'SSF3620147'),
('+919102796761', 'SSF3618665'),
('+919903087721', 'SSF3908428'),
('+919761989494', 'SSF3403255'),
('+919794964848', 'SSF2854216'),
('+919263101945', 'SSF3615606'),
('+919764840794', 'SID951375479021'),
('+919600000009', 'SSF3615587'),
('+919464518487', 'SSF3377673'),
('+918538950832', 'SSF4993274'),
('+919631923158', 'SSF5412840'),
('+919572515533', 'SSF5067117'),
('+917545989127', 'SSF4529793'),
('+919335479617', 'SSF4820406'),
('+919696879522', 'SSF5105854'),
('+917631844613', 'SSF5494076'),
('+917936801284', 'SSF3480654'),
('+916201261753', 'SSF5662643'),
('+916232782219', 'SSF3759312'),
('+916538958567', 'SSF2313790'),
('+916201858549', 'SSF3472065'),
('+916376831929', 'SSF3489526'),
('+917654423802', 'SSF3429971'),
('+917877091616', 'SSF3088866'),
('+918767649464', 'SSF3708110'),
('+918949600870', 'SSF3405075'),
('+918553255651', 'SSF3013107'),
('+918434135500', 'SSF3398861'),
('+918767979797', 'SID951374973100'),
('+919737379604', 'SSF3291385'),
('+919464641361', 'SSF3078138'),
('+919767943464', 'SSF3100956'),
('+919431619461', 'SSF3064417'),
('+919661402636', 'SSF3432117'),
('+919548767874', 'SSF3220326'),
('+919571302348', 'SSF3133160'),
('+919399831784', 'SID951373632100'),
('+919794843481', 'SSF2882878'),
('+919348434843', 'SID951375079316'),
('+919784344381', 'SSF3625649'),
('+919113365549', 'SSF3167851'),
('+919086686464', 'SSF3115648'),
('+919764648484', 'SSF3280746'),
('+919369129658', 'SSF3335069'),
('+919026069566', 'SSF3316842'),
('+919373384196', 'SSF3153954'),
('+916261748183', 'SSF3436580'),
('+916796786589', 'SID951374824863'),
('+916265054269', 'SSF3724769'),
('+916202974811', 'SSF3861117'),
('+916202848840', 'SSF3692772'),
('+916065241106', 'SID951372980384'),
('+917887646797', 'SSF2547218'),
('+917061396079', 'SSF2979397'),
('+918085202201', 'SSF3163825'),
('+918003966067', 'SSF3035214'),
('+918776648764', 'SSF2944422'),
('+918305910600', 'SSF3700462'),
('+918045858549', 'SSF3280385'),
('+918766585362', 'SSF3120984'),
('+918946467919', 'SSF3124340'),
('+919672189462', 'SSF3159481'),
('+919637410852', 'SSF3108849'),
('+919631092170', 'SSF3134912'),
('+919131767255', 'SSF3818663'),
('+919384280783', 'SSF3283882'),
('+919797948443', 'SSF2928488'),
('+919586538655', 'SSF3310048'),
('+919782719980', 'SSF2820449'),
('+917389963828', 'SSF3189633'),
('+918120774815', 'SSF3243856'),
('+919279616576', 'SSF3247600'),
('+919631575166', 'SSF2900150'),
('+919764368965', 'SSF2964526'),
('+918735032567', 'SSF4950731'),
('+918409661814', 'SSF5771328'),
('+918210851020', 'SSF5396469'),
('+918084448096', 'SSF5340853'),
('+916287634765', 'SSF5479585'),
('+916280831479', 'SSF5754505'),
('+916200366745', 'SSF5754685'),
('+917632982513', 'SSF5616934'),
('+917250935454', 'SSF5644509'),
('+918603321451', 'SSF4883114'),
('+918178960120', 'SSF5596985'),
('+919044912370', 'SSF5210436'),
('+919334437324', 'SSF5575274'),
('+916299992634', 'SSF5364777'),
('+917549511105', 'SSF5274362'),
('+916207586221', 'SSF5636292'),
('+916205423195', 'SSF5592174'),
('+917050253051', 'SSF5478634'),
('+917857884516', 'SSF5211479'),
('+918809255984', 'SSF5223636'),
('+917479789270', 'SSF5236791'),
('+917409152911', 'SSF5866436'),
('+919627363901', 'SSF5866462'),
('+919219730211', 'SSF4716543'),
('+919263236467', 'SSF4558145'),
('+919031128772', 'SSF4786254'),
('+917082698711', 'SSF5224191'),
('+919341876798', 'SSF3132016'),
('+919023536245', 'SSF3133352'),
('+919658866988', 'SSF2839922'),
('+918581041193', 'SID951374578872'),
('+919102262045', 'SSF3090540'),
('+916268782227', 'SSF2892914'),
('+916202753567', 'SSF3613468'),
('+916287875702', 'SSF2601181'),
('+916209865076', 'SSF4170091'),
('+916207334781', 'SSF4323754'),
('+917673802240', 'SSF4143787'),
('+917388090395', 'SSF3036434'),
('+917295999694', 'SSF4223437'),
('+917054438875', 'SSF2284703'),
('+917319806084', 'SSF4180100'),
('+917876207998', 'SSF4109327'),
('+917739774827', 'SSF4431318'),
('+917667535185', 'SSF4005587'),
('+917321062739', 'SSF5079860'),
('+917739418862', 'SSF5266004'),
('+918809505240', 'SSF4180090'),
('+918789638071', 'SSF4083830'),
('+918597495831', 'SSF3163728'),
('+918677988403', 'SSF4369609'),
('+918824368069', 'SSF5019182'),
('+918234058825', 'SSF3861107'),
('+918298314965', 'SSF4301450'),
('+919572217942', 'SSF4143132'),
('+919534679035', 'SSF4317821'),
('+919696089889', 'SSF4055486'),
('+919199059573', 'SSF4311355'),
('+919466594918', 'SSF3326711'),
('+919187464884', 'SSF3845735'),
('+919973044050', 'SSF4447600'),
('+919801175566', 'SSF4323891'),
('+919279658158', 'SSF4323924'),
('+919353033914', 'SSF4124754'),
('+919169119119', 'SSF2658366'),
('+919661854369', 'SID951374875863'),
('+919508269128', 'SSF3296610'),
('+919354314914', 'SSF4182086'),
('+919507829260', 'SSF4132366'),
('+919123471973', 'SSF4162574'),
('+919153311477', 'SSF5015855'),
('+916287816646', 'SSF4892622'),
('+917055375259', 'SSF5263748'),
('+918445547623', 'SSF5166748'),
('+919927364008', 'SSF5263850'),
('+919279029697', 'SSF5028090'),
('+916456776677', 'SID951375888170'),
('+917037681622', 'SSF3899505'),
('+916206952322', 'SSF5239144'),
('+916299146371', 'SSF5295349'),
('+917209995056', 'SSF6036083'),
('+917764877230', 'SSF4766387'),
('+917317357938', 'SSF6080563'),
('+918797956026', 'SSF5772458'),
('+918651110179', 'SSF5514592'),
('+918757424221', 'SSF4939189'),
('+919905634227', 'SSF5501583'),
('+919235263847', 'SSF5215190'),
('+919153224945', 'SSF5012758'),
('+919142952774', 'SSF6101350'),
('+916207479323', 'SSF5335684'),
('+919693109793', 'SSF4180938'),
('+916267074981', 'CID078100762'),
('+917255930479', 'CID227400088'),
('+916266742607', 'SSF3790397'),
('+916201929807', 'SSF4126390'),
('+916200542122', 'SID951375438932'),
('+916764689868', 'SSF3138359'),
('+916375800677', 'SSF2676966'),
('+916261019881', 'SSF5095932'),
('+916287726294', 'SSF3650215'),
('+916248434940', 'SSF3684373'),
('+916253544233', 'SSF3684400'),
('+916375061636', 'SSF3849209'),
('+917073758906', 'SSF2992886'),
('+917292916096', 'SSF3736017'),
('+917061962615', 'SSF3822033'),
('+917061727110', 'SID951375367099'),
('+917232007019', 'SID951375265586'),
('+917737543048', 'SSF3374528'),
('+917352599041', 'SSF3632253'),
('+917879556865', 'SID2125189712'),
('+917352664785', 'SSF3613993'),
('+917050087289', 'SSF4059180'),
('+917068084128', 'SSF3812915'),
('+917061955145', 'SSF4068505'),
('+917489776019', 'SID951376091237'),
('+918529603415', 'SSF4092996'),
('+918987495400', 'SSF3825063'),
('+918290983721', 'SSF2878985'),
('+918955576912', 'SSF2413311'),
('+918210204054', 'SSF3641905'),
('+918894548797', 'SSF3593386'),
('+918789785588', 'CID239801322'),
('+918235599109', 'SSF3756424'),
('+918349683031', 'SSF3834621'),
('+918207723933', 'SSF3482761'),
('+918863816899', 'SSF3615750'),
('+918648948519', 'SSF3787584'),
('+918256978456', 'SID951375839033'),
('+918435347638', 'SSF3536414'),
('+918236057031', 'SSF3804702'),
('+919801452948', 'SSF3588857'),
('+919151774482', 'SSF3735899'),
('+919199428854', 'SSF3841481'),
('+919508118032', 'SSF3814073'),
('+919852176054', 'SSF3743329'),
('+919835857958', 'SSF3543016'),
('+919787966485', 'SSF3810487'),
('+919770337005', 'SSF4016126'),
('+919856875655', 'SID951375352590'),
('+919507006695', 'SSF3503189'),
('+919166933465', 'SSF3933298'),
('+919324889979', 'SSF2918948'),
('+919928839948', 'SSF3804932'),
('+919863464349', 'SSF3692120'),
('+919155578377', 'SSF3662568'),
('+919546878787', 'SSF3565318'),
('+919431976491', 'SSF3543605'),
('+919301079926', 'SSF2629474'),
('+919608834283', 'SSF2596242'),
('+919654554818', 'SSF3710520'),
('+919981331217', 'SSF3777099'),
('+919111354669', 'SSF3969187'),
('+919102115476', 'SSF3765315'),
('+919686566464', 'SSF3633224'),
('+919155561244', 'SSF5270204'),
('+917061887127', 'SSF5442660'),
('+917294161147', 'SSF5095253'),
('+918809475213', 'SID951372854320'),
('+916658625885', 'SSF3653982'),
('+916356877178', 'SSF3580461'),
('+916377415872', 'SSF3814878'),
('+916354693497', 'SSF3543002'),
('+916299040180', 'SSF3364224'),
('+917014381813', 'SSF3788938'),
('+917716541984', 'SSF3765382'),
('+917667352202', 'SSF3818972'),
('+917888683535', 'SSF3816960'),
('+917783871671', 'SSF2779020'),
('+917994676466', 'SSF3683879'),
('+917737058901', 'SSF3333191'),
('+917042586733', 'SSF3554988'),
('+917854865448', 'SID951376091528'),
('+918866139011', 'SSF3748251'),
('+918239538553', 'SSF3375189'),
('+918294039218', 'SID951374821347'),
('+918598686767', 'SSF3516538'),
('+918000562108', 'SSF3353030'),
('+918079979794', 'SSF3819860'),
('+918563974528', 'SSF3509712'),
('+918078683993', 'SSF3786975'),
('+918051417521', 'SID951375832406'),
('+918102738375', 'SID951375585206'),
('+918252290978', 'SSF4351043'),
('+918686686686', 'SID951375525928'),
('+918770946935', 'SSF2770059'),
('+919468404973', 'SSF3769835'),
('+919446236525', 'SSF3566195'),
('+919999454543', 'SSF3624292'),
('+919861956164', 'SSF3454769'),
('+919574828683', 'SID951375504390'),
('+919263170880', 'SSF3826647'),
('+919932477896', 'SSF3521588'),
('+919854251346', 'SSF3772058'),
('+919123105606', 'SSF3679498'),
('+919637576484', 'SSF3834299'),
('+919501860414', 'SSF3459748'),
('+919655414935', 'SSF3578231'),
('+919661697058', 'SID951375485783'),
('+919997873613', 'SSF3423879'),
('+919736433483', 'SSF3367081'),
('+919648464384', 'SSF3671576'),
('+919263172133', 'SSF3750511'),
('+919693729306', 'SSF2762814'),
('+919639636636', 'SSF2926042'),
('+919665588995', 'SSF3793346'),
('+919065640573', 'SSF3679313'),
('+918540036695', 'SSF4648806'),
('+918100445894', 'SSF5243469'),
('+919534247457', 'SSF5409043'),
('+917404713362', 'SSF5213676'),
('+917800662536', 'SSF5298097'),
('+917260090654', 'SSF5357142'),
('+918709814590', 'SSF4786198'),
('+919508244295', 'SSF5727621'),
('+916209582313', 'SSF3363671'),
('+918767854976', 'SSF3246824'),
('+916201681918', 'SSF3157373'),
('+917654357997', 'SSF3301155'),
('+917654399494', 'SSF3282348'),
('+917992319997', 'SSF3423382'),
('+917878986845', 'SSF3405676'),
('+918202210219', 'SSF3196573'),
('+918084721463', 'SSF2415542'),
('+918118873654', 'SID951375276543'),
('+918225993739', 'SSF3288028'),
('+918354995666', 'SSF3273329'),
('+918815159400', 'SSF2794006'),
('+918769708379', 'SSF2854296'),
('+918340352920', 'SSF3512221'),
('+918949189833', 'SSF3062638'),
('+918536965855', 'SSF3136049'),
('+918578777979', 'SSF3499976'),
('+918053412502', 'SSF3043583'),
('+919734484648', 'SSF3577886'),
('+919584678764', 'SSF3251917'),
('+919854846476', 'SSF3443097'),
('+919138170265', 'SSF2970960'),
('+919166762397', 'SSF3062688'),
('+919576224493', 'SSF3257719'),
('+919116928718', 'SSF2988375'),
('+919263930127', 'SSF3301987'),
('+919661704513', 'SSF3273774'),
('+919549507979', 'SSF4098909'),
('+919771602051', 'SSF2718623'),
('+919592925084', 'SSF3241359'),
('+919125603719', 'SID951375780258'),
('+916201197074', 'SSF2926249'),
('+916261265430', 'SSF3189740'),
('+916375190008', 'SSF2940435'),
('+917727015006', 'SSF3032118'),
('+917654722650', 'SSF2952253'),
('+917067897807', 'SSF3324693'),
('+917454223241', 'SSF3054101'),
('+918720123910', 'SSF3164064'),
('+918235555761', 'SSF2939328'),
('+918271872285', 'SSF3120681'),
('+919670769484', 'SSF3106697'),
('+919300346009', 'SSF3185384'),
('+919303002475', 'SSF3814949'),
('+919468434469', 'SSF3042316'),
('+919375119843', 'SSF3042314'),
('+919929648348', 'SSF3056346'),
('+919302505842', 'SSF3627395'),
('+917493892235', 'SSF5473211'),
('+917667863106', 'SSF5420691'),
('+917987073114', 'SSF2973578'),
('+918102744805', 'SID951375620251'),
('+919673434343', 'SSF2879523'),
('+917897414042', 'SSF4465888'),
('+916393748969', 'SSF5120925'),
('+916205295641', 'SSF5509968'),
('+916204853537', 'SSF5308840'),
('+916203833528', 'SSF4320094'),
('+917665430644', 'SSF4927745'),
('+917724048244', 'SSF5065268'),
('+917322024162', 'SSF5769445'),
('+917464064700', 'SSF3887523'),
('+918619107145', 'SSF2869805'),
('+917229935398', 'SSF6151012'),
('+919580788415', 'SSF5829954'),
('+918233746294', 'SSF5196115'),
('+919555433722', 'SSF4932817'),
('+919023176425', 'SSF5859521'),
('+917782815950', 'SSF3133168'),
('+919390834793', 'SSF5666723'),
('+916205760358', 'SSF3599494'),
('+916202312301', 'SSF2631458'),
('+919058821923', 'SSF4484123'),
('+919523453503', 'SSF5395777'),
('+916266757574', 'SSF2828040'),
('+918002157177', 'SSF3166980'),
('+918757037626', 'SID951373904310'),
('+916484446404', 'SSF3741231'),
('+918602736405', 'SSF3501061'),
('+919919224802', 'SSF5613284'),
('+917049521795', 'SID2125292605'),
('+919708306249', 'SSF5555717'),
('+917665135736', 'SSF3809234'),
('+919889224703', 'SSF5270980'),
('+919457254832', 'SSF6403067'),
('+919598438432', 'SSF2589619'),
('+919096531508', 'SSF3039613'),
('+918261974526', 'SID951375116006'),
('+919341636346', 'SID951375888931'),
('+919508454208', 'SSF3209625'),
('+919009126741', 'SSF2774541'),
('+917830670521', 'SSF6076397'),
('+917500038422', 'SSF5736392'),
('+918319721032', 'SSF2800835'),
('+918090430255', 'SID951373815867'),
('+916266045052', 'SSF3658760'),
('+919801026467', 'SSF6159939'),
('+916284554554', 'SID951376063912'),
('+919343268842', 'SID951375529101'),
('+919131485378', 'SSF3107729'),
('+919839317475', 'SSF6180234'),
('+919661546625', 'SID951375618440'),
('+917856997689', 'SSF6188275'),
('+918120931359', 'CID204602624'),
('+918005998644', 'SSF3060025'),
('+916261242961', 'SID2125697232'),
('+919572124609', 'SSF3275153'),
('+918318299218', 'SSF5001170'),
('+917383794123', 'SID951373900948'),
('+919111705991', 'SSF3290872'),
('+919956878101', 'SSF5825184'),
('+918602422902', 'SID2125151503'),
('+918102722674', 'SSF2967378'),
('+919241884882', 'SSF2308023'),
('+918874380621', 'SSF6090208'),
('+917079873108', 'SID951374758793'),
('+918527804686', 'SSF6396544'),
('+919548769819', 'SSF5842551'),
('+917667805532', 'SID951375489734'),
('+919771599231', 'SSF2358291'),
('+919630458385', 'SSF3502697'),
('+919005019180', 'SSF5329347'),
('+917696419201', 'SSF5886994'),
('+917024595505', 'SID951374568378'),
('+919389091763', 'SSF6263581'),
('+916295260737', 'SSF3043736'),
('+916200883784', 'SSF6175776'),
('+919589877297', 'SSF3491525'),
('+919801771285', 'SSF4512929'),
('+916207723355', 'SSF2661138'),
('+916268081531', 'SID951373030493'),
('+918128325599', 'SSF3344618'),
('+917317625241', 'SSF3501720'),
('+918521554264', 'SSF5169681'),
('+919771742841', 'SSF6087628'),
('+919334740004', 'SSF5166943'),
('+918960402194', 'SSF2990764'),
('+917004332347', 'SSF4779305'),
('+919801986207', 'SSF3652333'),
('+917877965808', 'SSF5601588'),
('+916399596359', 'SSF5910167'),
('+917354647915', 'SID2125665834'),
('+918102123690', 'SID951375451567'),
('+916267080750', 'SID2125651814'),
('+917742990761', 'SSF4018517'),
('+917678860050', 'SSF5356225'),
('+919883798139', 'SSF6005828'),
('+919587651955', 'SSF2753630'),
('+918112479268', 'SSF2775142'),
('+917631314167', 'SSF5477326'),
('+919329905470', 'SSF5641626'),
('+919905818740', 'SID951374679377'),
('+919065336455', 'SSF6169821'),
('+919098189369', 'SID951374093444'),
('+917870468560', 'SSF4598449'),
('+919122624530', 'SSF4789709'),
('+917310524119', 'SSF4911514'),
('+918103619590', 'SSF3428664'),
('+916202747306', 'SSF6344628'),
('+917049061507', 'SSF5251341'),
('+919306570621', 'SID951372864762'),
('+919329510791', 'SSF5740384'),
('+917563081502', 'SSF2363303'),
('+917462840121', 'SSF3269460'),
('+918815337240', 'SSF4904531'),
('+916375166488', 'SSF3982392'),
('+916367724703', 'SID951374926899'),
('+917061610815', 'SSF5179547'),
('+919790953913', 'SSF4671827'),
('+919303292128', 'SID951375340168'),
('+918923943843', 'SSF4848217'),
('+917587100250', 'SSF3018295'),
('+918128055174', 'SSF6550675'),
('+917987019688', 'SSF2790433'),
('+919340125969', 'SSF4173394'),
('+918809274122', 'SSF5818565'),
('+919519027322', 'SSF4068637'),
('+918319585383', 'SSF4489525'),
('+918103455387', 'SSF3326078'),
('+917339940174', 'SSF2621482'),
('+919824196152', 'SSF3348300'),
('+919026902139', 'SSF5444683'),
('+916205234428', 'SSF5386150'),
('+918603084941', 'SSF6169806'),
('+919793243568', 'SID951375020099'),
('+917974662419', 'SID2125474796'),
('+917255810792', 'SID951375270104'),
('+916219191994', 'SID951374572321'),
('+916381099746', 'SSF6572512'),
('+919113300490', 'SSF5795041'),
('+918434103823', 'SSF5555495'),
('+916268683024', 'SID951375318867'),
('+918439609085', 'SSF6025854'),
('+917488478278', 'SSF5764299'),
('+918450057715', 'SID951373726122'),
('+919905876686', 'SSF6313669'),
('+916146464848', 'SSF2486343'),
('+917258038642', 'SSF5807814'),
('+917903830045', 'SSF5498118'),
('+919672198428', 'SID951375538114'),
('+919571194024', 'SID951374466904'),
('+918084036591', 'SSF2305857'),
('+919555673413', 'SSF5792972'),
('+918107561119', 'SID951375406132'),
('+917482944709', 'SSF6146092'),
('+918887804215', 'SSF5828130'),
('+918252128669', 'SSF5317963'),
('+917205334667', 'SSF5259667'),
('+916200583981', 'SSF2477164'),
('+917318562193', 'SID951374754362'),
('+916307646269', 'SSF2449211'),
('+916206651199', 'SID951374962387'),
('+916350025923', 'SID951374965367'),
('+916287706769', 'SSF5094300'),
('+919005877932', 'SSF5056313'),
('+918284030398', 'SSF4536977'),
('+918287953192', 'SSF4988914'),
('+918757996624', 'SSF6188920'),
('+918084855324', 'SSF2416063'),
('+917644863386', 'SSF5271529'),
('+918768554087', 'SSF3164384'),
('+919229489567', 'SSF6339634'),
('+918355008132', 'SSF5744231'),
('+919801891454', 'SSF5881077'),
('+919648957888', 'SSF6024138'),
('+919302605882', 'SSF5873263'),
('+919065232348', 'SSF4864921'),
('+919372259305', 'SSF5568860'),
('+916266278182', 'SSF5710444'),
('+919587933705', 'SSF4093716'),
('+918873045083', 'SSF5780779'),
('+916200308310', 'SSF3001389'),
('+919580612337', 'SSF5276444'),
('+918092808426', 'SSF5616761'),
('+918292562362', 'SSF6395532'),
('+918839839489', 'SSF2386284'),
('+917759075587', 'SSF5785980'),
('+917879734686', 'CID084707700'),
('+918484974470', 'SID951373765865'),
('+918735958309', 'SID951375522217'),
('+918955801184', 'SSF2594723'),
('+917697536027', 'SSF3259790'),
('+917296897274', 'SSF5272177'),
('+917004397989', 'SSF4637626'),
('+917543986513', 'SSF5376584'),
('+916203823903', 'SSF3165139'),
('+918292333969', 'SSF2510188'),
('+919928438287', 'SSF4763049'),
('+918953683479', 'SSF4104110'),
('+919565061607', 'SSF5713209'),
('+918969739816', 'SSF5304720'),
('+919594522381', 'SSF6441418'),
('+919895730886', 'SSF2610269'),
('+917351648963', 'SSF4214490'),
('+919588064314', 'SSF3930729'),
('+919327768885', 'SSF5978390'),
('+917322902585', 'SSF5619597'),
('+918509195034', 'SSF6104024'),
('+919414703669', 'SID951375217411'),
('+918863886842', 'SID951375709626'),
('+918466595400', 'SID951374032860'),
('+919102181356', 'SID951376158074'),
('+919060434244', 'SSF2542035'),
('+919691856245', 'SSF3188735'),
('+917209757526', 'SSF6512817'),
('+919471450589', 'SSF5531341'),
('+919336103117', 'SSF6019855'),
('+917701991574', 'SID951372823776'),
('+919818303211', 'SSF6101894'),
('+917070434537', 'SSF6101270'),
('+917757948824', 'SSF6377511'),
('+917023920679', 'SSF3718976'),
('+917302931500', 'SSF5144430'),
('+917808727892', 'SSF3935773'),
('+918889495497', 'SSF5621547'),
('+917067555857', 'SID951373393837'),
('+919343594828', 'SID951376170147'),
('+919771930326', 'SSF2630748'),
('+916263003645', 'SID951372932366'),
('+917240424713', 'SID951374027347'),
('+917055191054', 'SSF4983755'),
('+919005123369', 'SSF3957281'),
('+918235446385', 'SSF5709798'),
('+919983096530', 'SSF4634399'),
('+918966983963', 'SID36012'),
('+918958575917', 'SSF4136377'),
('+916202084157', 'SSF6144191'),
('+917484979003', 'SSF5436942'),
('+919584790631', 'CID050214517'),
('+919653977480', 'SID951373760933'),
('+919665690110', 'SID951375536284'),
('+917742959653', 'SID951375056180'),
('+918120139347', 'SSF4584233'),
('+916268906174', 'SSF3602600'),
('+919905418154', 'SSF6140118'),
('+919056150775', 'SSF5909368'),
('+919057642361', 'SSF4809641'),
('+917061539732', 'SSF4507510'),
('+916464984848', 'SSF3439459'),
('+919508699482', 'SSF6030429'),
('+918797438215', 'SSF5025374'),
('+917354285642', 'SSF3278258'),
('+917024157984', 'SSF5001241'),
('+919352814207', 'SSF5300739'),
('+916205913654', 'SSF5285322'),
('+917796490176', 'SSF4413467'),
('+919931276429', 'SID951376189464'),
('+919356997925', 'SID951375338277'),
('+919076633273', 'SSF6043459'),
('+917764079313', 'SSF3190356'),
('+919827638188', 'SSF4536951'),
('+919509649626', 'SID951374181934'),
('+919656555858', 'SSF3353388'),
('+916299824619', 'SSF6295274'),
('+919155428522', 'SSF3139548'),
('+918271391690', 'SSF5687789'),
('+919670883096', 'SSF6111683'),
('+918120917182', 'SID951373737050'),
('+919165492328', 'SID951375299101'),
('+916200517072', 'SSF6342666'),
('+916268474497', 'SSF4574200'),
('+919122984836', 'SSF4405020'),
('+917870323960', 'SSF4856215'),
('+917568490763', 'SSF3200299'),
('+919201785780', 'SSF6561344'),
('+918957109801', 'SSF5121162'),
('+917067650675', 'CID213800368'),
('+917828880443', 'SSF5742312'),
('+918815256290', 'SID2125402703'),
('+919128230386', 'CID171506911'),
('+916382274121', 'SSF4336499'),
('+916200473922', 'SSF3278303'),
('+916266003019', 'SID951375180432'),
('+916003573783', 'SSF4178856'),
('+917856902260', 'SSF5322716'),
('+917068381336', 'SSF4485933'),
('+917073880652', 'SSF3677363'),
('+917856810642', 'SSF3217979'),
('+917992440863', 'SSF4421573'),
('+917079211623', 'SSF4529901'),
('+917994732501', 'SSF4643687'),
('+917738806178', 'SSF4501082'),
('+917858005816', 'SSF4298748'),
('+917319745209', 'SSF3963642'),
('+917425853977', 'SSF3967991'),
('+917491020288', 'SSF5527533'),
('+917292844067', 'SID951375999549'),
('+917722894320', 'SSF4089265'),
('+917258913238', 'SSF4243385'),
('+917061075019', 'SSF4128467'),
('+918236095624', 'SSF3961706'),
('+918084612015', 'SSF3699056'),
('+918709417630', 'SSF3108547'),
('+918651558825', 'SSF4486868'),
('+918325350649', 'SID951375668201'),
('+918604702855', 'SSF4057117'),
('+918434929266', 'SSF4434734'),
('+918085299091', 'SSF4485502'),
('+918809806319', 'SSF4062788'),
('+918114578590', 'SSF4412375'),
('+918409068821', 'SSF4348714'),
('+918383048622', 'SSF4518252'),
('+918757288251', 'SID951373899327'),
('+918002008283', 'SSF4525241'),
('+918603490085', 'SSF4243395'),
('+918651407550', 'SSF3824535'),
('+918389010486', 'SSF5266025'),
('+919234687475', 'SSF4764016'),
('+919006023194', 'SSF4498386'),
('+919104485576', 'SSF4520161'),
('+919523461620', 'SSF4489142'),
('+919589289535', 'SSF4395910'),
('+919801277651', 'SSF2509708'),
('+919973034856', 'SSF4305186'),
('+919304537077', 'SSF4483267'),
('+919572280401', 'SSF3156418'),
('+919034166932', 'SSF3969443'),
('+919123477719', 'SSF4434706'),
('+919155820735', 'SSF4698593'),
('+919905947266', 'SID951374521748'),
('+919304140220', 'SSF3996524'),
('+919669732108', 'SID951373891150'),
('+919546246717', 'SSF3336592'),
('+919602256213', 'SSF4018541'),
('+919798923447', 'SSF4164666'),
('+919327085581', 'SSF4215663'),
('+919031789956', 'SSF2524454'),
('+919985560121', 'SSF4015711'),
('+919142789907', 'SSF4123570'),
('+919895533173', 'SSF4308548'),
('+919098702413', 'SSF4570738'),
('+917024337037', 'SSF5201354'),
('+918288936858', 'SSF5155777'),
('+919931957935', 'SSF5475425'),
('+917484877053', 'SSF5539661'),
('+917011891409', 'SSF5562863'),
('+918521210794', 'SSF5333556'),
('+918007101540', 'SSF4708682'),
('+919229101566', 'SSF5441424'),
('+916284897159', 'SSF5444229'),
('+916207306865', 'SSF5666943'),
('+916287909815', 'SSF5599785'),
('+917545032212', 'SSF5278184'),
('+917633888703', 'SSF5640693'),
('+917541894424', 'SSF4556799'),
('+917297053521', 'SSF5541518'),
('+918092227980', 'SSF5031935'),
('+918102932942', 'SSF4210740'),
('+918271031045', 'SSF5450914'),
('+918287451418', 'SSF5640381'),
('+918340223945', 'SSF4790052'),
('+918294211043', 'SSF5490042'),
('+918102376893', 'SSF5528964'),
('+919835398503', 'SSF5544304'),
('+919226037887', 'SSF5840558'),
('+919234515988', 'SSF4868248'),
('+919608531922', 'SSF5243162'),
('+919199446026', 'SSF5025226'),
('+919608881751', 'SSF6057039'),
('+919199022191', 'SSF5719381'),
('+919911824887', 'SSF5578893'),
('+919525398727', 'SSF5682254'),
('+919867457726', 'SSF5687181'),
('+919241530729', 'SSF5450512'),
('+917549688116', 'SSF5381059'),
('+917717747202', 'SSF6347781'),
('+917991528296', 'SSF5309157'),
('+917897944961', 'SSF5463358'),
('+917988707218', 'SSF5438632'),
('+919565118816', 'SSF5529967'),
('+919162359141', 'SSF5449905'),
('+919305493191', 'SSF5920863'),
('+919798412895', 'SSF5521857'),
('+919123241420', 'SSF4223193'),
('+916207819287', 'SSF3560953'),
('+916798766994', 'SSF3636128'),
('+916260330006', 'SSF3143421'),
('+916268860512', 'SSF4080634'),
('+917389126911', 'SSF3798655'),
('+917427083423', 'SSF2563658'),
('+917282951585', 'SSF4063477'),
('+917878577877', 'SSF2325460'),
('+917489847835', 'SSF3729916'),
('+917868688835', 'SSF3747064'),
('+917061845267', 'SSF2747490'),
('+917061124764', 'SSF3926064'),
('+917014247021', 'SSF4084407'),
('+917384554611', 'SID951375631258'),
('+918603173603', 'SSF4070479'),
('+918690511476', 'SSF3784630'),
('+918890231552', 'SSF3042833'),
('+918719850781', 'SSF4241763'),
('+918292273716', 'SSF3797049'),
('+918966911011', 'SSF4055073'),
('+918496464849', 'SSF3768896'),
('+918319729259', 'SSF4102334'),
('+919631590611', 'SSF3727072'),
('+919508955863', 'SSF3449803'),
('+919334182956', 'SSF4047256'),
('+919608182698', 'SSF2921149'),
('+919669576306', 'SSF3758921'),
('+919462374176', 'SSF3905538'),
('+919341142305', 'SSF3272501'),
('+919174385559', 'SID951374054768'),
('+919521336518', 'SSF3918227'),
('+919787487618', 'SSF3842590'),
('+919546667656', 'SID951375242554'),
('+919303368729', 'SSF4060288'),
('+919302755795', 'SSF3024967'),
('+917417481118', 'SSF4499397'),
('+917347498266', 'SSF5163735'),
('+918948428499', 'SSF5997718'),
('+918172862347', 'SSF5952788'),
('+918840291826', 'SSF5273281'),
('+919334922701', 'SSF4876226'),
('+919936015939', 'SSF5219770'),
('+919129421265', 'SSF5315130'),
('+919151152380', 'SSF5324600'),
('+918102645900', 'SSF5489615'),
('+917451986440', 'SSF5210264'),
('+917991284517', 'SSF5107333'),
('+917740013979', 'SSF5243309'),
('+919229191781', 'SSF5358127'),
('+916205762691', 'SID951372821304'),
('+916287888788', 'SSF3754966'),
('+916494997376', 'SSF3722069'),
('+916200729392', 'SSF3936317'),
('+916236289643', 'SSF3411403'),
('+916292848784', 'SSF3766269'),
('+916389858168', 'SSF3661745'),
('+917976562771', 'SSF3608707'),
('+917357078725', 'SSF3912388'),
('+917061067951', 'SSF3954530'),
('+917070606155', 'SSF2593911'),
('+917073884521', 'SSF3692233'),
('+917864559988', 'SSF3721892'),
('+917870074559', 'SID951375108694'),
('+917568991216', 'SSF3216854'),
('+917987788212', 'SSF3591714'),
('+918107472410', 'SSF3918773'),
('+918603218339', 'SID951375826671'),
('+918434491285', 'SSF3596272'),
('+918890799114', 'SSF3908869'),
('+918825290018', 'SSF3984111'),
('+918432246252', 'SSF3913789'),
('+918340311881', 'SSF4020488'),
('+918052535455', 'SID951375750858'),
('+918180051179', 'SSF4735009'),
('+919827881689', 'SSF3796421'),
('+919109607065', 'SSF3522371'),
('+919646955545', 'SID951374851503'),
('+919511371078', 'SSF4212836'),
('+919982739378', 'SSF3786848'),
('+919341230982', 'SSF4034913'),
('+919631681799', 'SSF3363668'),
('+919119663196', 'SSF3895653'),
('+919865645317', 'SSF3776651'),
('+919631370396', 'SSF3795301'),
('+919905230421', 'SSF3616775'),
('+919351664477', 'SSF3720235'),
('+919693309216', 'SSF3913490'),
('+919999766488', 'SSF3493314'),
('+919209339021', 'SSF3888143'),
('+919142938580', 'SSF3639384'),
('+919685521463', 'SID951374852890'),
('+919783767392', 'SSF3330473'),
('+919708246988', 'SSF4051333'),
('+919848655559', 'SSF3551608'),
('+919648475545', 'SSF3120603'),
('+919183404482', 'SID951375920113'),
('+919767346494', 'SSF3369254'),
('+919877037076', 'SSF3759480'),
('+919633358895', 'SSF3544691'),
('+919547399370', 'SSF2653658'),
('+919279377884', 'SSF3052445'),
('+919774114755', 'SID951373951270'),
('+916299536959', 'SSF5820729'),
('+916394498402', 'SSF4805368'),
('+919219148994', 'SSF4032503'),
('+919501819519', 'SSF5825452'),
('+919801197900', 'SSF5391959'),
('+919798115676', 'SSF5441000'),
('+919030561452', 'SSF3738297'),
('+919138181837', 'SSF5413546'),
('+919153282064', 'SSF5012611'),
('+917388047978', 'SSF4912327'),
('+919988874556', 'SSF3334244'),
('+919264488584', 'SSF5164784'),
('+916281075406', 'SSF5712689'),
('+918756879727', 'SSF4475255'),
('+919008616476', 'SSF4801365'),
('+917463823762', 'SSF5046163'),
('+917545827366', 'SSF3363612'),
('+917748449484', 'SID951376113274'),
('+917742146850', 'SSF3083413'),
('+917424939015', 'SSF3443507'),
('+917073558915', 'SSF3394943'),
('+918269508369', 'SSF3546126'),
('+918432142585', 'SSF3476627'),
('+918739023645', 'SSF3476675'),
('+918882809565', 'SSF3356683'),
('+918306403520', 'SSF3557134'),
('+918875451454', 'SSF3337053'),
('+918890442707', 'SSF3489486'),
('+918584664544', 'SSF3504829'),
('+918233538754', 'SSF3652584'),
('+918555636886', 'SSF3498782'),
('+918290282068', 'SSF2532781'),
('+918698788569', 'SSF3818307'),
('+919636548721', 'SSF3560260'),
('+919854867378', 'SSF3691432'),
('+919995556999', 'SSF2407397'),
('+919199837857', 'SID951375332189'),
('+919279934138', 'SSF3376128'),
('+919856456864', 'SSF3021133'),
('+919636646494', 'SSF3226740'),
('+919955714509', 'SSF3612393'),
('+919354355455', 'SSF3661933'),
('+919693017997', 'SSF3823587'),
('+919684545548', 'SSF3457303'),
('+919399776276', 'SSF3763067'),
('+919464049404', 'SSF3682874'),
('+916853050689', 'SSF3577176'),
('+917887979494', 'SSF3446022'),
('+917742546638', 'SSF2675156'),
('+918557865795', 'SSF3789644'),
('+918284679797', 'SSF3607477'),
('+918578767758', 'SSF3346578'),
('+919668655585', 'SSF3396477'),
('+919575840466', 'SSF2998811'),
('+919558450479', 'SSF3789753'),
('+919249940924', 'SID951376056349'),
('+917828521312', 'SSF3414731'),
('+918109965363', 'SSF3621563'),
('+918305723595', 'SSF3719555'),
('+919431284878', 'SSF3377672'),
('+919828468510', 'SSF3081299'),
('+917778097195', 'SSF4888818'),
('+916207300289', 'SSF5633899'),
('+917091641220', 'SSF5617083'),
('+917782999604', 'SSF5435394'),
('+918595952957', 'SSF4661146'),
('+918210477727', 'SSF5532955'),
('+918968531443', 'SSF5594681'),
('+917016126569', 'SSF4788195'),
('+916201915425', 'SSF2923051'),
('+919992834244', 'SSF2997549'),
('+916396445846', 'SSF5882250'),
('+917398798289', 'SSF5103174'),
('+919648115338', 'SSF5530771'),
('+919149299525', 'SSF5411154'),
('+916200402147', 'SSF5230809'),
('+919142149364', 'SSF5392302'),
('+918429019585', 'SSF6094756'),
('+919785112136', 'SSF5398069'),
('+918092432923', 'SSF5055084'),
('+919965533896', 'SSF2956180'),
('+919949646446', 'SSF2906258'),
('+918557946494', 'CID204505236'),
('+918435605589', 'SID2125610477'),
('+916290126673', 'SSF4499982'),
('+916207029963', 'SSF4864253'),
('+916204307801', 'SSF4682174'),
('+916201112770', 'SSF4351090'),
('+916260135369', 'SID951376153558'),
('+917856972956', 'SSF4722114'),
('+917762047193', 'SSF4523667'),
('+917321837084', 'SSF4538418'),
('+917073926633', 'SSF4435241'),
('+917393021428', 'SSF4518195'),
('+917564823114', 'SSF4520614'),
('+917250487181', 'SSF4518258'),
('+917568045893', 'SSF4000586'),
('+917488702818', 'SSF4516973'),
('+917416050580', 'SSF4514521'),
('+917295877317', 'SSF4360579'),
('+917806075851', 'SSF3963030'),
('+918107475621', 'SSF4435234'),
('+918102752544', 'SSF5422331'),
('+918407030268', 'SSF4512642'),
('+918434490814', 'SSF4513614'),
('+918292678305', 'SSF4885193'),
('+918252194270', 'SSF4013764'),
('+918789342766', 'SSF4466468'),
('+918102122875', 'SSF2396149'),
('+918287007371', 'SSF4965712'),
('+918797103830', 'SSF2729068'),
('+918440073488', 'SSF3886420'),
('+918102485414', 'SSF2280850'),
('+919934454398', 'SSF4490882'),
('+919726976458', 'SID951375583983'),
('+919507359779', 'SSF4498430'),
('+919262643157', 'SSF4862691'),
('+919431063867', 'SSF3953419'),
('+919057282502', 'SSF4316748'),
('+919153381977', 'SSF4020409'),
('+919309402305', 'SSF4517607'),
('+919031551974', 'SSF4153476'),
('+919153824477', 'SSF4048700'),
('+917632897315', 'SSF2681938'),
('+918470962293', 'SSF5193494'),
('+919835770204', 'SSF5496080'),
('+919902540503', 'SSF5229392'),
('+916397361531', 'SSF5426126'),
('+917484840015', 'SSF5429625'),
('+917209685968', 'SSF5940274'),
('+917479689129', 'SSF5718762'),
('+917219564375', 'SSF5560380'),
('+917209162969', 'SSF5005982'),
('+917518198233', 'SSF5202391'),
('+918002852507', 'SSF5337668'),
('+918102899086', 'SSF5693058'),
('+919310788685', 'SSF5681024'),
('+919801952718', 'SSF5555794'),
('+919155288311', 'SSF5790696'),
('+919523031542', 'SSF5783866'),
('+919905429186', 'SSF4748227'),
('+919153495025', 'SSF5522690'),
('+919065072704', 'SSF5427138'),
('+919452705253', 'SSF5210902'),
('+917631266795', 'SSF5885858'),
('+919065869178', 'SSF5764354'),
('+918528866885', 'SID2125206334'),
('+916264726293', 'SSF4834926'),
('+916265944264', 'SSF4346731'),
('+916207596731', 'SID951376028730'),
('+916268171893', 'SSF2843496'),
('+916263334763', 'SSF4743312'),
('+916266249290', 'SSF4261776'),
('+916206354885', 'SID951372904032'),
('+916350559795', 'SSF3998913'),
('+917870016161', 'SSF3064809'),
('+917974990635', 'SID951375516202'),
('+917070177180', 'SID951373996033'),
('+917898760887', 'SSF4069262'),
('+917884644846', 'SSF2736257'),
('+917489008212', 'SSF2940041'),
('+917748875504', 'SSF3298936'),
('+918619004474', 'SSF5118842'),
('+918103544027', 'SSF4022676'),
('+918651870934', 'SSF4053557'),
('+918151534846', 'SSF3724131'),
('+918290812563', 'SSF3852268'),
('+918019202623', 'SSF3196769'),
('+918797035647', 'SSF3360490'),
('+918305825398', 'SSF4270682'),
('+918696190241', 'SSF3887763'),
('+918254165236', 'SID2125307686'),
('+918864949996', 'SSF3854198'),
('+919236582536', 'SSF3860971'),
('+919797876445', 'SSF3110113'),
('+919521178086', 'SSF4569321'),
('+919155398067', 'SSF4034513'),
('+919686466497', 'SID951375035482'),
('+919973550213', 'SSF3183154'),
('+919523779858', 'SSF3803274'),
('+919580853515', 'SSF4082463'),
('+919111483342', 'SSF3731154'),
('+919571029375', 'SSF3165618'),
('+919764911161', 'SSF3744334'),
('+919801358296', 'SSF4067529'),
('+919241386510', 'SSF3359381'),
('+919405974867', 'SID951374859513'),
('+919129478712', 'SSF3892256'),
('+919988524568', 'SSF3585892'),
('+918881982970', 'SSF5062685'),
('+919219974844', 'SSF5043297'),
('+917905069461', 'SSF4389401'),
('+917782016037', 'SSF5791502'),
('+917275368783', 'SSF5124177'),
('+919651674202', 'SSF5030108'),
('+919369287872', 'SSF4419687'),
('+919631503536', 'SID2125225507'),
('+916359210101', 'SSF3494057'),
('+916204490892', 'SSF2807564'),
('+916565678767', 'SSF3663339'),
('+916448468438', 'SSF3741333'),
('+916205716046', 'SSF4164869'),
('+916206373959', 'SSF2776157'),
('+916389496396', 'SSF2770532'),
('+917742138809', 'SSF3886746'),
('+917425681568', 'SSF3157922'),
('+917717752108', 'SSF3715483'),
('+917485074079', 'SSF4001313'),
('+917828436157', 'SSF3537260'),
('+917357579301', 'SSF3411457'),
('+918107321222', 'SSF3872724'),
('+918877742870', 'SSF4016369'),
('+918431105086', 'SSF4051288'),
('+918767844757', 'SSF3436694'),
('+919358360580', 'SSF3919896'),
('+919358286028', 'SSF3716853'),
('+919640646861', 'SSF3551098'),
('+919784352335', 'SSF3500190'),
('+919644994661', 'SID951376172246'),
('+919738938866', 'SSF3433543'),
('+919783421849', 'SSF3981595'),
('+919918929673', 'SSF3082495'),
('+919636550561', 'SSF3961442'),
('+919523569307', 'SSF4001210'),
('+919301805396', 'SSF3773148'),
('+919658927852', 'SSF2781020'),
('+919341183649', 'SSF3152071'),
('+919162742032', 'SSF4018336'),
('+919054324463', 'SSF3917458'),
('+919636508742', 'SSF2867904'),
('+919157025434', 'SSF2640811'),
('+919665486248', 'SSF3669555'),
('+919406235415', 'SSF3647980'),
('+917294199020', 'SSF3827438'),
('+918863005772', 'SSF4741293'),
('+919807498446', 'SSF4704802'),
('+918847322783', 'SSF5543601'),
('+918429972134', 'SSF5178005'),
('+918318291186', 'SSF4840916'),
('+919025014378', 'SSF5202827'),
('+917668377586', 'SSF4371914'),
('+919389547737', 'SSF4378881'),
('+919798000370', 'SSF5832574'),
('+917007750524', 'SSF4983590'),
('+919373413212', 'SID951375200660'),
('+919279390381', 'SSF5154578'),
('+916204016844', 'SSF3438823'),
('+916268852250', 'SSF3537898'),
('+916288458405', 'SSF3505390'),
('+916367252695', 'SSF3911634'),
('+917878253821', 'SSF3663159'),
('+917425918360', 'SSF3466895'),
('+917479913949', 'SSF4124139'),
('+917067561918', 'SSF3532862'),
('+918757354727', 'SSF2431959'),
('+918826608142', 'SSF3366164'),
('+918292249031', 'SSF3642422'),
('+918454364612', 'SSF3361217'),
('+918114482680', 'SSF3960607'),
('+918764949976', 'SSF3663326'),
('+918290160568', 'SSF4166144'),
('+918945679744', 'SSF3639306'),
('+918809957415', 'SSF3665205'),
('+918886966494', 'SSF3488936'),
('+918398066292', 'SSF3310651'),
('+918494649659', 'SSF3190698'),
('+918815858132', 'SSF3128159'),
('+919676787689', 'SSF3495076'),
('+919982247252', 'SSF3110066'),
('+919767874846', 'SSF3649341'),
('+919608569069', 'SSF3603250'),
('+919946868600', 'SSF3391357'),
('+919858645877', 'SSF3569803'),
('+919636123458', 'SSF2832997'),
('+919523509476', 'SSF3194714'),
('+919484641918', 'SSF3199849'),
('+919672654755', 'SSF3266591'),
('+916263943443', 'SSF3637922'),
('+916284643494', 'SSF3398709'),
('+917763051459', 'SSF2671717'),
('+917898368760', 'SSF3544053'),
('+918079424339', 'SSF3652799'),
('+918005046439', 'SSF3638704'),
('+918788221412', 'SSF3454398'),
('+919859757567', 'SID951375573236'),
('+919786454611', 'SSF2648438'),
('+919693142563', 'SSF3464244'),
('+919982383370', 'SSF2895677'),
('+919587325219', 'SSF2959656'),
('+918437025871', 'SSF5589829'),
('+919690502331', 'SSF5263897'),
('+916377394440', 'SSF3140612'),
('+918535692578', 'SSF3366547'),
('+919352814852', 'SSF2986025'),
('+919856748654', 'SSF2878991'),
('+919754536024', 'SID2125756801'),
('+919023990416', 'SSF5418574'),
('+919136227241', 'SSF5600261'),
('+918708304132', 'SSF5167285'),
('+919588007881', 'SSF5359733'),
('+917209605717', 'SSF5822121'),
('+917766851342', 'SSF5311493'),
('+919162803397', 'SSF5231288'),
('+916200723538', 'SSF5175289'),
('+919216727177', 'SSF5599903'),
('+918739014018', 'SSF3801612'),
('+918533097497', 'SSF4763164'),
('+916203684246', 'SSF2658449'),
('+918517805116', 'SSF5224626'),
('+919754716874', 'SSF2642570'),
('+918084511498', 'SSF5634546'),
('+917046101681', 'SID2125754653'),
('+919508742356', 'SSF3716341'),
('+919343422466', 'SSF3756685'),
('+918126996008', 'SSF6288424'),
('+917737392644', 'SSF3791491'),
('+918235540885', 'SSF5435761'),
('+919316017651', 'SSF4928992'),
('+919661339562', 'SSF5974850'),
('+919580854175', 'SSF4554848'),
('+917463093125', 'SSF4086227'),
('+916267521653', 'SSF2604440'),
('+919302847272', 'CID224400607'),
('+919628611006', 'SSF5906039'),
('+919826822516', 'CID128808422'),
('+919753167615', 'SID951374884238'),
('+918797221280', 'SSF5683376'),
('+918935822814', 'SSF5482826'),
('+919151313623', 'SSF3545721'),
('+918103996790', 'SID951374386055'),
('+918092399580', 'SSF6132830'),
('+918294471083', 'SSF5369119'),
('+917000110990', 'SID951373618724'),
('+919341785038', 'SSF5089537'),
('+917482952081', 'SSF4849989'),
('+918863827645', 'SSF6314522'),
('+918209619092', 'SSF5356139'),
('+917894946646', 'SSF2842287'),
('+917426941876', 'SSF4758115'),
('+919302807652', 'SSF3540679'),
('+918120349929', 'SSF3817944'),
('+917250898798', 'SSF6216166'),
('+916207508889', 'SSF5710529'),
('+918092032853', 'SSF5640703'),
('+918982757525', 'SSF3776794'),
('+916268732842', 'SID951374598960'),
('+919608111094', 'SID951375824474'),
('+918709674408', 'SSF5917210'),
('+918827033464', 'SID951373063245'),
('+917803984041', 'SID951376019864'),
('+918303489800', 'SSF2450271'),
('+918809888991', 'SID951375574398'),
('+918797799499', 'SSF4171704'),
('+918084512194', 'SSF5666774'),
('+918115433294', 'SSF2554718'),
('+916394511954', 'SSF5932026'),
('+916388091622', 'SSF6305575'),
('+919204288042', 'SSF3756902'),
('+919955058320', 'SSF6535783'),
('+917761953828', 'SID951374357842'),
('+918862802667', 'SSF2920853'),
('+919343528662', 'SSF4901610'),
('+919631570436', 'SSF5638642'),
('+918887988417', 'SSF2890893'),
('+916206295649', 'SSF2755616'),
('+918756469086', 'SSF5915593'),
('+918678464584', 'SSF2458245'),
('+919576347702', 'SSF5747581'),
('+919516218519', 'SID951375337840'),
('+917300044129', 'SSF5856945'),
('+919334759877', 'SSF5550660'),
('+919889947077', 'SSF5778819'),
('+918824868083', 'SSF6110855'),
('+918224083037', 'SSF4558237'),
('+919142370408', 'SSF5298066'),
('+917819037552', 'SSF5641329'),
('+919341149646', 'SID951374528138'),
('+917231907957', 'SID951375262681'),
('+919399427640', 'SSF4486945'),
('+917307692160', 'SSF6315030'),
('+918578862722', 'SSF5953856'),
('+918235327473', 'SSF5340856'),
('+919718272825', 'SSF5767610'),
('+919898309379', 'SSF5050661'),
('+917498461275', 'SSF6275412'),
('+919241912572', 'SSF5491828'),
('+917557718437', 'SSF4706274'),
('+919826457451', 'SID951374109170'),
('+917542070950', 'SSF4553280'),
('+918651709006', 'SSF5650744'),
('+916299720371', 'SSF4391600'),
('+919568339081', 'SSF4671847'),
('+917771960204', 'SSF2868431'),
('+916204626393', 'SSF2922683'),
('+919939329391', 'SID951373110884'),
('+919244909192', 'SSF6546897'),
('+918827884827', 'SSF6535129'),
('+917366048698', 'SSF6081253'),
('+917250238255', 'SSF5543365'),
('+918789325402', 'SSF5851504'),
('+918002043337', 'SSF6059393'),
('+917050778733', 'SSF4693529'),
('+917488408738', 'SSF5603146'),
('+918294708073', 'SSF6396083'),
('+919504890201', 'SID951373160398'),
('+916005811204', 'SSF6073790'),
('+919950799674', 'SSF5225306'),
('+916265607911', 'SID951372812902'),
('+919631623569', 'SSF4581143'),
('+918340109643', 'SSF2452731'),
('+917788757870', 'SID951375647057'),
('+917830143474', 'SSF5916304'),
('+917068346428', 'SSF4641851'),
('+918966929623', 'SID951374813303'),
('+917723889796', 'SID2125400624'),
('+918104904470', 'SSF4717214'),
('+917209076248', 'SSF3795670'),
('+916396097821', 'SSF5514857'),
('+919936798096', 'SSF6183962'),
('+918707210284', 'SSF4569414'),
('+917803930068', 'SSF4345241'),
('+919109566465', 'SID951373636217'),
('+916264665596', 'SID951373511074'),
('+917309154015', 'SSF4817048'),
('+917458976034', 'SSF6155480'),
('+919371501314', 'SSF2367682'),
('+919306953478', 'SID951376140712'),
('+918581966388', 'SSF5572712'),
('+917906749859', 'SSF5850716'),
('+918881345112', 'SSF5397934'),
('+918754123690', 'SSF3486636'),
('+918355848931', 'SSF5048289'),
('+918815378108', 'SID951375821186'),
('+916265625929', 'SID951372999021'),
('+918002024483', 'CID171505011'),
('+917061893631', 'SSF5900945'),
('+918949799499', 'SID951375062345'),
('+919797278875', 'SSF6071925'),
('+919335939837', 'SSF5737181'),
('+916287884316', 'SSF5092144'),
('+917463891372', 'SSF5844159'),
('+918084691820', 'SSF5813088'),
('+917209478988', 'SSF2373315'),
('+919198201413', 'SID2125498314'),
('+917830760537', 'SSF5495920'),
('+917071272173', 'SSF5133403'),
('+918521397206', 'SSF6367159'),
('+918827585289', 'SSF2380124'),
('+916207621194', 'SSF2710653'),
('+916355442722', 'SSF3790618'),
('+916386635829', 'SSF4929495'),
('+918092837276', 'SSF5570276'),
('+918398809325', 'SSF6274475'),
('+916399128721', 'SSF5288953'),
('+919399184285', 'SID951375684846'),
('+918305761790', 'SSF5480053'),
('+917063822821', 'SSF6040895'),
('+919098399064', 'SID951372836151'),
('+918009887920', 'SSF5441800'),
('+917697451988', 'SID2125133617'),
('+918815760518', 'SID951375310794'),
('+918969291087', 'SSF3058955'),
('+919058489386', 'SSF4069100'),
('+918103494973', 'SID951376109411'),
('+919496464656', 'SID951375642104'),
('+917300528156', 'SSF4774489'),
('+917357424459', 'SID951374548106'),
('+917320092939', 'SSF4153571'),
('+918541895612', 'SSF5238189'),
('+916367109737', 'SSF3831980'),
('+918521419515', 'SSF5821594'),
('+918815842651', 'CID261401051'),
('+918797262839', 'SSF3045727'),
('+918434023833', 'SSF3203245'),
('+919857887555', 'SID951376202421'),
('+919889073823', 'SSF3106983'),
('+918305917136', 'SID2125367037'),
('+916264427700', 'SID951375328549'),
('+919244687226', 'SSF3764162'),
('+919116851944', 'SSF5999199'),
('+916266600948', 'CID213100270'),
('+919780122640', 'SSF5845631'),
('+919125991570', 'SSF3712664'),
('+918177071404', 'SSF5626774'),
('+919534412989', 'SSF3270138'),
('+919754570205', 'SID951375794641'),
('+919897175628', 'SSF4899526'),
('+917257055131', 'SSF5427108'),
('+918269254516', 'CID135705216'),
('+919454978797', 'SID951374733952'),
('+916464840463', 'SSF3422507'),
('+917281965487', 'SID2125574149'),
('+919142551047', 'CID211201483'),
('+919772254624', 'SSF5330029'),
('+918530543152', 'SSF4090656'),
('+919604531205', 'SSF5509959'),
('+919201071870', 'SSF5467519'),
('+918002067369', 'SSF5657798'),
('+917061193558', 'SSF5936041'),
('+919324975599', 'SSF5869285'),
('+918306536163', 'SID951374830090'),
('+918797460682', 'SSF3418776'),
('+919304333057', 'SSF5956954'),
('+919468840030', 'SSF2567832'),
('+917268977460', 'SSF5913223'),
('+917278055020', 'SSF6267590'),
('+916264216774', 'SID951375543317'),
('+916306696330', 'SSF5908330'),
('+917759963058', 'SSF6163281'),
('+917067265839', 'CID207401943'),
('+917067133845', 'SSF2502941'),
('+918674827034', 'SSF4068489'),
('+916263359389', 'CID191400127'),
('+919166605284', 'SID951376053602'),
('+918292144736', 'SSF5170878'),
('+917281014657', 'SSF5657664'),
('+918809374672', 'SSF5239540'),
('+919798904464', 'SSF5167380'),
('+917903639034', 'SSF6232909'),
('+917992363296', 'SSF5936163'),
('+918541091651', 'SSF2817816'),
('+919939639757', 'SSF6298184'),
('+918795926290', 'SID2125404336'),
('+919162812660', 'SSF5166961'),
('+916264504364', 'SID951372931354'),
('+918756059127', 'SSF4502628'),
('+919169654086', 'SSF2559339'),
('+916299157957', 'SSF4057978'),
('+916202243048', 'SSF4437866'),
('+916287174909', 'SSF4326405'),
('+916207763976', 'SSF4582266'),
('+916203969420', 'SSF4358424'),
('+916206167445', 'SSF4120472'),
('+916202829702', 'SSF4643709'),
('+916202502854', 'SSF4339128'),
('+917488593496', 'SSF4624811'),
('+917033773455', 'SSF4351329'),
('+917509829890', 'SSF4356263'),
('+917462043158', 'SSF4513940'),
('+917857981589', 'SSF4583324'),
('+917909050954', 'SSF4819009'),
('+917050964553', 'SSF2723028'),
('+917856972688', 'SSF4629825'),
('+917070169573', 'SSF4591097'),
('+917783037071', 'SSF4593931'),
('+917755807738', 'SSF4569276'),
('+917991184824', 'SSF3949449'),
('+917766999365', 'SSF4494240'),
('+917484940180', 'SSF2738675'),
('+918235101184', 'SSF4596257'),
('+918360854508', 'SSF4411728'),
('+918210190288', 'SSF3602761'),
('+918955159387', 'SSF4410537'),
('+918229865894', 'SSF3915135'),
('+918591708436', 'SSF3278719'),
('+918591207898', 'SSF4550825'),
('+918969622291', 'SSF4599949'),
('+918084554132', 'SSF4428819'),
('+918708257658', 'SSF4205629'),
('+918955621791', 'SSF4559442'),
('+918292229631', 'SSF4618286'),
('+918825327840', 'SSF4973636'),
('+919826751354', 'SSF4044103'),
('+919199706854', 'SSF3904575'),
('+919024648441', 'SSF4760651'),
('+919798508837', 'SSF4505714'),
('+919358426166', 'SSF4450059'),
('+919973217814', 'SSF4354886'),
('+919508123464', 'SSF4543784'),
('+919801255992', 'SSF3968015'),
('+919973412566', 'SSF4043485'),
('+919303908588', 'SSF4615319'),
('+919537436097', 'SSF3319997'),
('+919341593558', 'SSF4564554'),
('+919199480985', 'SSF4704946'),
('+919691466725', 'SSF4261724'),
('+919589915033', 'SSF3371864'),
('+919117690164', 'SSF4651833'),
('+919123476965', 'SSF4712055'),
('+919892965576', 'SSF4487424'),
('+919262977959', 'SSF4530416'),
('+919631224097', 'SSF4602734'),
('+919341221875', 'SSF4643596'),
('+919559148380', 'SSF4621831'),
('+919279475519', 'CID212403665'),
('+916299074440', 'SSF3978220'),
('+916205231891', 'SSF4015387'),
('+916299627323', 'SSF4352352'),
('+916291209752', 'SSF4409757'),
('+916206646753', 'SSF4385751'),
('+916200525954', 'SSF4232752'),
('+916206915541', 'SSF4566182'),
('+916200080360', 'SSF3087288'),
('+916207706990', 'SSF4939294'),
('+917067758634', 'SSF4572496'),
('+917209995354', 'SSF4147292'),
('+917903846357', 'SSF3563011'),
('+917782834387', 'SSF4403863'),
('+917766021932', 'SSF4411718'),
('+917748855250', 'SSF4345316'),
('+917250847589', 'SSF4405067'),
('+917325090393', 'SSF4035729'),
('+917737281191', 'SSF4566383'),
('+917903851896', 'SSF4350756'),
('+917033088578', 'SSF3955186'),
('+917054714896', 'SSF2904199'),
('+917739823382', 'SSF4385968'),
('+917562085632', 'SSF4365169'),
('+917782866276', 'SSF4419948'),
('+918409644435', 'SSF4236095'),
('+918354032157', 'SSF4429087'),
('+918496937507', 'SID951376004159'),
('+918792187140', 'SSF4360523'),
('+918434246329', 'SSF4709214'),
('+918770906834', 'SSF4134943'),
('+918218840222', 'SSF3988410'),
('+918651563156', 'SSF4888053'),
('+918374259958', 'SSF4322446'),
('+918837755860', 'SSF4497057'),
('+918757508875', 'SSF4121853'),
('+918104415590', 'SSF2665936'),
('+918252865375', 'SSF4147057'),
('+918969249013', 'SSF4521745'),
('+918797369291', 'SSF4188870'),
('+918059252923', 'SSF3161202'),
('+918210426358', 'SSF4174351'),
('+918292049730', 'SSF4206884'),
('+919508802753', 'SSF5322582'),
('+919709684400', 'SSF4416931'),
('+919354405261', 'SSF4377912'),
('+919798322342', 'SSF4400104'),
('+919334956719', 'SSF5242617'),
('+919226962698', 'SSF4369648'),
('+919507586963', 'SSF4182659'),
('+919279118923', 'SSF5018569'),
('+919571374216', 'SSF3462796'),
('+919929740388', 'SSF4282293'),
('+919352301756', 'SSF4385497'),
('+919576973843', 'SSF4475687'),
('+919326784970', 'SSF4405747'),
('+919142319012', 'SSF4157968'),
('+919304210854', 'SSF4229005'),
('+919343577403', 'SSF2991637'),
('+919097240786', 'SSF4411589'),
('+919971417046', 'SSF4411683'),
('+919649404676', 'SSF2573041'),
('+919523771334', 'SSF4220075'),
('+917764928706', 'SSF2915771'),
('+917987891514', 'SSF2714856'),
('+919065055051', 'SSF4046776'),
('+916203399393', 'SSF5591709'),
('+917366942017', 'SSF5443161'),
('+919113017443', 'SSF5374193'),
('+916386556316', 'SSF4439827'),
('+916287533464', 'SSF4703714'),
('+916287870031', 'SSF5766742'),
('+917678313377', 'SSF5233139'),
('+917319749696', 'SSF5491549'),
('+917765898084', 'SSF5681178'),
('+917033756486', 'SSF5326890'),
('+917320844597', 'SSF5720521'),
('+917539913541', 'SSF5813016'),
('+917257984562', 'SSF5891957'),
('+917543800193', 'SSF5708894'),
('+918294621394', 'SSF5352827'),
('+918271341845', 'SSF5459649'),
('+918862965707', 'SSF4689532'),
('+918210828706', 'SSF5180456'),
('+918271014176', 'SSF5494864'),
('+918603829473', 'SSF5759189'),
('+918603885110', 'SSF5726355'),
('+918409568351', 'SSF5099165'),
('+918406959352', 'SSF5762947'),
('+919263177658', 'SSF5619542'),
('+919711743194', 'SSF5714636'),
('+919801328132', 'SSF4947584'),
('+919955772456', 'SSF5622222'),
('+919065333074', 'SSF5063740'),
('+919576971653', 'SSF5812704'),
('+919341636557', 'SSF6117486'),
('+919572925275', 'SSF5491100'),
('+919523587945', 'SSF4611524'),
('+917080719115', 'SSF5563034'),
('+917607401727', 'SSF3933819'),
('+917643019121', 'SSF5510177'),
('+917834843577', 'SSF4942522'),
('+918795687859', 'SSF5246459'),
('+919905178188', 'SSF5727948'),
('+919519319554', 'SSF5314047'),
('+919263487091', 'SSF5332993'),
('+919582175186', 'SSF5530163'),
('+917764094651', 'SID2125015500'),
('+919838885466', 'SID951372885479'),
('+916381136049', 'SSF3950472'),
('+916297111086', 'SSF4054361'),
('+916377694983', 'SSF2727784'),
('+917667069145', 'SSF3946863'),
('+917413018892', 'SSF4075767'),
('+917903262503', 'SSF2635164'),
('+917542467665', 'SID951374671247'),
('+917864986046', 'SSF3911579'),
('+917049249052', 'SSF3950492'),
('+917765839167', 'SSF2729543'),
('+917368004720', 'SSF3433051'),
('+917739643031', 'SSF3403157'),
('+917258061696', 'SID951375280166'),
('+917033079233', 'SID951376113814'),
('+917223879155', 'SID951375492056'),
('+918000843226', 'SSF3772324'),
('+918678578676', 'SSF3867708'),
('+918252963079', 'SID951375257913'),
('+918779782716', 'SSF4525042'),
('+918974377965', 'SID951375602851'),
('+918084604532', 'SSF4557086'),
('+918809709772', 'SSF4010854'),
('+918102023538', 'SSF4119452'),
('+918302825870', 'SSF4036471'),
('+918535565686', 'SSF2471599'),
('+919113390092', 'SSF3903965'),
('+919765754848', 'SSF3817331'),
('+919608129930', 'SID951375451603'),
('+919835985080', 'SSF3999733'),
('+919928968271', 'SSF3951278'),
('+919621461030', 'SID951375624690'),
('+919865325896', 'SSF3882862'),
('+919602883736', 'SSF4021197'),
('+919525281668', 'SSF3549467'),
('+919973905166', 'SSF3995441'),
('+919770463918', 'SSF3810416'),
('+919931397138', 'SSF4819186'),
('+919939065234', 'SSF3912707'),
('+919125961529', 'SSF2922224'),
('+919939263910', 'SID951375602217'),
('+919929738187', 'SSF3911321'),
('+919306135769', 'SSF4033019'),
('+919078005152', 'SSF3919161'),
('+916207560141', 'SSF5450006'),
('+916280903597', 'SSF5484952'),
('+917250472572', 'SSF5544504'),
('+917209698972', 'SSF5531334'),
('+918108824377', 'SSF5410094'),
('+918009715710', 'SSF4425862'),
('+918797302628', 'SSF5515658'),
('+919996311599', 'SSF5406944'),
('+919973284580', 'SSF5471913'),
('+919306140814', 'SSF5043845'),
('+919794055313', 'SSF4995868'),
('+919508675067', 'SSF5080301'),
('+919798461349', 'SSF5542763'),
('+919263341302', 'SSF5034896'),
('+916204524465', 'SSF5563032'),
('+917070666456', 'SSF5377144'),
('+918292376522', 'SSF5438215'),
('+919817804852', 'SSF5137068'),
('+919905150886', 'SSF5211625'),
('+917388093135', 'SSF3768144'),
('+918115334253', 'SSF4095665'),
('+917209717071', 'SSF4481011'),
('+919336219297', 'SSF5241105'),
('+916207972432', 'SSF4102339'),
('+916364946494', 'SSF3717505'),
('+916767676446', 'SSF3902840'),
('+916202119586', 'SSF3576767'),
('+916367209395', 'SSF3751986'),
('+916367497029', 'SSF3919375'),
('+916200700683', 'SSF3575975'),
('+917667161131', 'SSF3888127'),
('+917543455464', 'SSF3810742'),
('+917643055120', 'SSF3896854'),
('+917856855369', 'SID951375390147'),
('+917033709808', 'SID951373980790'),
('+917707029181', 'SSF3848734'),
('+917879464646', 'SSF3630130'),
('+917563971327', 'SSF3719941'),
('+917070297247', 'SSF4273495'),
('+917742649975', 'SSF3625612'),
('+917292972118', 'SSF2966096'),
('+917891045210', 'SSF3838987'),
('+917073784232', 'SSF3835347'),
('+918825129394', 'SSF3696560'),
('+918000379179', 'SSF3683422'),
('+918757799289', 'SSF3912451'),
('+918298671310', 'SSF4300247'),
('+918209488978', 'SSF2350303'),
('+918327702758', 'SSF3140785'),
('+918860890716', 'SID951375937597'),
('+918603412408', 'SSF3609539'),
('+918302388498', 'SSF3755068'),
('+918015319134', 'SID951375979899'),
('+918797506785', 'SSF2803608'),
('+918092143501', 'SSF3786057'),
('+918252685748', 'SSF3807906'),
('+918434109601', 'SSF3753608'),
('+918306889430', 'SSF4023128'),
('+918233823614', 'SSF3963772'),
('+918458802805', 'SSF3753166'),
('+918559887777', 'SSF3893659'),
('+919835894137', 'SSF3913057'),
('+919119329521', 'SID951375356959'),
('+919568556063', 'SSF3516568'),
('+919772217688', 'SSF3631878'),
('+919358392966', 'SID951374870165'),
('+919693012704', 'SSF3587662'),
('+919587331912', 'SSF4011532'),
('+919955336405', 'SSF2972313'),
('+919190578527', 'SID951376068173'),
('+919263511178', 'SSF3696308'),
('+919864846464', 'SSF3528003'),
('+919263122617', 'SSF3945216'),
('+919799078256', 'SSF3912915'),
('+919065035390', 'SSF3669746'),
('+919199498254', 'SSF3884349'),
('+919771708337', 'SSF3870456'),
('+919334529557', 'SSF3547098'),
('+919664219284', 'SSF3751972'),
('+919024296977', 'SSF3360623'),
('+919263397534', 'SSF3667057'),
('+919001629652', 'SSF4915614'),
('+919521235539', 'SSF4921561'),
('+919122749265', 'SSF3906707'),
('+919798775929', 'SSF3866929'),
('+919846754846', 'SSF3613165'),
('+919098424345', 'SSF4296000'),
('+919279894287', 'SSF4809701'),
('+919634840484', 'SSF3878516'),
('+919916535135', 'SSF3770892'),
('+919771576478', 'SID951376178672'),
('+919764964659', 'SID951376214494'),
('+919572751204', 'SSF3521889'),
('+919935808422', 'SSF3412438'),
('+919519662314', 'SSF3625307'),
('+919905629449', 'SSF3665138'),
('+917376575926', 'SSF5211892'),
('+918292654524', 'SSF5580402'),
('+918434567016', 'SSF5041217'),
('+916202749151', 'SSF5328922'),
('+918540078949', 'SSF5464096'),
('+919572139459', 'SSF5463278'),
('+917257816325', 'SSF3448982'),
('+917898087519', 'SSF3678466'),
('+918867614649', 'SSF3674234'),
('+919454467767', 'SSF3597036'),
('+919658586669', 'SID951373315614'),
('+916006617083', 'SSF3516571'),
('+916205357573', 'SSF3089118'),
('+916654423889', 'SSF3185920'),
('+916875577586', 'SSF3311020'),
('+917568147765', 'SSF4587565'),
('+917488816981', 'SSF3366153'),
('+917359182344', 'SID951376108214'),
('+917742895544', 'SSF3498570'),
('+917086586563', 'SSF3298291'),
('+918242090672', 'SSF3240458'),
('+918954286575', 'SSF3464088'),
('+918094157597', 'SID951375077233'),
('+918797008812', 'SSF3377890'),
('+918709693370', 'SSF3190130'),
('+918432464849', 'SSF3601243'),
('+918464678888', 'SSF3176122'),
('+918283965624', 'SSF3591969'),
('+918876546697', 'SSF3596260'),
('+919696459482', 'SSF3516562'),
('+919523620938', 'SSF3516866'),
('+919571108077', 'SSF3459898'),
('+919060805040', 'SSF3385751'),
('+919768086788', 'SSF3324319'),
('+919473486469', 'SSF2905268'),
('+919378966885', 'SSF3245135'),
('+919155847772', 'SSF3406247'),
('+919784288836', 'SSF2574223'),
('+919676497955', 'SSF3492752'),
('+919621897670', 'SSF3615158'),
('+919855434946', 'SSF3316111'),
('+919668686886', 'SID951376057328'),
('+919592949494', 'SSF3848358'),
('+919798593892', 'SSF5315870'),
('+916287847637', 'SSF3149734'),
('+917033830985', 'SSF3097574'),
('+917296802043', 'SSF3428456'),
('+917426856988', 'SSF3133493'),
('+917772855876', 'SSF3609730'),
('+917027958496', 'SSF3043582'),
('+918696488298', 'SSF3179268'),
('+918746531955', 'SSF3152000'),
('+918120521585', 'SSF3565324'),
('+918454213315', 'SID951375598259'),
('+919766494649', 'SSF3152594'),
('+919905233856', 'SID951373515394'),
('+919784782915', 'SSF3237241'),
('+919098524255', 'SSF3119823'),
('+919469749464', 'SSF3095824'),
('+919829311215', 'SSF3602365'),
('+919905341863', 'SSF3307644'),
('+919546830730', 'SSF3251253'),
('+919846468464', 'SSF3640087'),
('+916267172234', 'SSF3623094'),
('+916204396046', 'SSF3335019'),
('+918233597382', 'SSF3126163'),
('+919636854724', 'SSF2991594'),
('+919499485956', 'SSF2945671'),
('+917631752887', 'SSF4723279'),
('+916355560434', 'SSF5493991'),
('+918809639837', 'SSF5502264'),
('+918849113489', 'SSF5588681'),
('+918757928382', 'SSF5507970'),
('+919699645164', 'SSF5386217'),
('+918767964867', 'SSF3058988'),
('+918107151962', 'SSF2893940'),
('+919588383457', 'SSF2994472'),
('+919875656665', 'SSF3007540'),
('+916392297279', 'SSF5215142'),
('+919608630015', 'SSF4842822'),
('+919153768814', 'SSF5613200'),
('+917480904219', 'SSF4960963'),
('+918789198634', 'SSF5588771'),
('+919162872471', 'SSF5879030'),
('+919334323765', 'SSF5196448'),
('+919262314262', 'SSF5359734'),
('+919060202951', 'SSF5439215'),
('+918409329262', 'SSF4637727'),
('+919794794819', 'SSF4641518'),
('+919798293634', 'SSF3578604'),
('+919031273737', 'SSF2855407'),
('+919610926427', 'SSF2833212'),
('+917456883069', 'SSF3748046'),
('+916206765615', 'SSF4558388'),
('+916200460490', 'SSF4417901'),
('+916209578243', 'SSF4623915'),
('+916253828465', 'SID951375296773'),
('+916379076841', 'SSF4738936'),
('+917479815378', 'SSF2883272'),
('+917073915961', 'SSF4022077'),
('+917870715940', 'SSF4531227'),
('+917073176005', 'SSF4634931'),
('+917479938834', 'SSF4172211'),
('+917764001554', 'SSF4601416'),
('+918319353682', 'SSF4380450'),
('+918209151415', 'SSF4617850'),
('+918084526420', 'SSF4593418'),
('+918434624397', 'SSF4501990'),
('+918777397937', 'SSF3915162'),
('+918757340930', 'SSF4821470'),
('+918235997010', 'SSF4640570'),
('+919122840878', 'SSF4410972'),
('+919351846576', 'SSF4640712'),
('+919779138937', 'SSF4595856'),
('+919818750823', 'SSF4418429'),
('+919771037778', 'SSF4646773'),
('+919341922615', 'SSF4600487'),
('+919122421075', 'SSF4632320'),
('+919939580221', 'SSF4407571'),
('+919057661687', 'SSF2578072'),
('+916378868483', 'SSF4348960'),
('+916203013443', 'SSF4371905'),
('+916207372975', 'SSF3967034'),
('+916206468421', 'SSF4365168'),
('+916354765989', 'SSF4374693'),
('+917050141954', 'SSF4149884'),
('+917070982898', 'SSF4410208'),
('+917209229014', 'SSF4321546'),
('+917079789762', 'SSF4326943'),
('+917643908489', 'SSF4311777'),
('+917542901490', 'SSF4392608'),
('+917209319034', 'SSF5132298'),
('+917033901364', 'SSF4987024'),
('+917004088624', 'SSF4386612'),
('+917737008949', 'SSF4215177'),
('+917880248328', 'SSF4444570'),
('+917033700335', 'SSF4287310'),
('+918207531739', 'SSF4375573'),
('+918652410293', 'SID951375268437'),
('+918825138973', 'SSF4377779'),
('+918252396035', 'SSF4587468'),
('+918252402668', 'SSF4420353'),
('+918409478306', 'SSF4378482'),
('+918619092992', 'SSF4122943'),
('+918603113229', 'SSF3616701'),
('+918581963901', 'SSF4389098'),
('+919717692896', 'SSF3243280'),
('+919407961504', 'SSF4556527'),
('+919801226297', 'SSF4403919'),
('+919244104612', 'SSF4378873'),
('+919693042007', 'SSF3551144'),
('+919341534031', 'SSF4007737'),
('+919508801656', 'SSF4332221'),
('+919801350343', 'SSF3816066'),
('+919142364962', 'SSF5207989'),
('+919121428025', 'SSF3914851'),
('+919113438212', 'SSF4412954'),
('+919580632693', 'SSF2410144'),
('+919006842042', 'SSF4545647'),
('+919109055216', 'SID951375489924'),
('+919153031302', 'SSF5132324'),
('+919241557125', 'SSF5180938'),
('+919263518121', 'SSF5087053'),
('+919608709419', 'SSF4502589'),
('+919708836194', 'SSF4378441'),
('+919006754890', 'SSF4165044'),
('+919262237985', 'SSF4513892'),
('+919661075695', 'SSF4435616'),
('+919153074720', 'SSF3184866'),
('+919120427430', 'SSF4367060'),
('+919234730084', 'SSF2923458'),
('+919153206483', 'SSF4481985'),
('+916205410282', 'SSF5215972'),
('+916202706876', 'SSF6012344'),
('+917488106511', 'SSF4080454'),
('+917667390743', 'SSF5587612'),
('+917033361795', 'SSF5775759'),
('+917717775323', 'SSF5413680'),
('+917986166489', 'SSF5690675'),
('+917209685868', 'SSF5479152'),
('+917703019606', 'SSF5225772'),
('+918789988436', 'SSF5932475'),
('+918210835347', 'SSF5784555'),
('+918295683756', 'SSF5017120'),
('+918271088217', 'SSF5395596'),
('+918960723881', 'SSF5205881'),
('+919661605269', 'SSF5660591'),
('+919006066134', 'SSF5491648'),
('+919162419157', 'SSF5348418'),
('+919870031275', 'SSF5160661'),
('+919511034335', 'SSF5569937'),
('+919507354529', 'SSF5614146'),
('+919129320604', 'SSF5215001'),
('+916266531740', 'SSF3077725'),
('+916205568989', 'SSF5418256'),
('+917634973724', 'SSF5717258'),
('+918340550573', 'SSF5491569'),
('+918766312653', 'SSF5553933'),
('+918877851420', 'SSF5185646'),
('+919334723813', 'SSF5776518'),
('+919693577478', 'SSF5763120'),
('+918935880417', 'SSF5485445'),
('+919693575751', 'SSF4475900'),
('+916311615451', 'SID951374397759'),
('+916354987584', 'SSF3903529'),
('+916351343700', 'SID951375598097'),
('+917070106401', 'SSF3994124'),
('+917488642459', 'SID951372983430'),
('+917061772677', 'SSF3939318'),
('+917300386235', 'SSF2831597'),
('+917368087985', 'SSF4064914'),
('+917762079359', 'SSF2786308'),
('+917739891000', 'SSF4789261'),
('+917050693910', 'SSF3423540'),
('+917061312780', 'SID951374288559'),
('+917256099282', 'SSF3973640'),
('+917903320307', 'SSF4006476'),
('+917209488389', 'SSF4008174'),
('+917879553757', 'SSF4087450'),
('+917303043628', 'SSF4066413'),
('+918529619170', 'SSF3950893'),
('+918809155570', 'SSF2820119'),
('+918252957530', 'SSF3014509'),
('+918875096019', 'SID951375290688'),
('+918982314794', 'SSF4152431'),
('+918252735342', 'SSF2451293'),
('+918785465665', 'SID951374458264'),
('+918541009775', 'SID951375810145'),
('+918271652153', 'SSF3903492'),
('+918651733435', 'SSF3994244'),
('+918271414575', 'SSF4101414'),
('+918815691975', 'SSF3925354'),
('+919301124366', 'SSF5037667'),
('+919507941899', 'SID951375245113'),
('+919661629437', 'SSF4057678'),
('+919116361873', 'SID951374441656'),
('+919263675819', 'SSF4013637'),
('+919352557381', 'SSF3930138'),
('+919407923151', 'SSF4043655'),
('+919155727446', 'SSF3844905'),
('+919128413622', 'SSF3910328'),
('+919117323760', 'SSF3276494'),
('+919031880118', 'SID951375588084'),
('+919065848511', 'SSF3913361'),
('+919799659943', 'SSF3919351'),
('+919866856855', 'SID951374595901'),
('+919828617614', 'SSF3930099'),
('+919583690665', 'SID951375267410'),
('+919725560915', 'SSF3945267'),
('+919173530759', 'SSF3973773'),
('+919122884867', 'SSF3903511'),
('+919210568987', 'SID951376172991'),
('+919652147896', 'SSF3845708'),
('+919717978541', 'SSF3910887'),
('+919523265321', 'SSF4160487'),
('+919636499526', 'SSF3900515'),
('+919302699340', 'SSF3777417'),
('+919303473700', 'SSF2767890'),
('+919602357201', 'SSF4006422'),
('+916005147785', 'SSF4243816'),
('+917498836442', 'SSF5886244'),
('+917858859042', 'SSF4379635'),
('+918446795591', 'SSF3577254'),
('+918709685747', 'SSF5672903'),
('+918797135570', 'SSF4896175'),
('+919279196643', 'SSF5506531'),
('+918252222080', 'SSF5370596'),
('+917696424153', 'SSF4555347'),
('+918092689491', 'SSF5409932'),
('+919198942870', 'SSF5679334'),
('+916378836563', 'SID951374727664'),
('+916375834485', 'SSF4314020'),
('+916632887586', 'SSF3592627'),
('+916484879754', 'SID951375889013'),
('+916200774027', 'SSF3704624'),
('+916206484384', 'SSF3739534'),
('+916207630813', 'SSF3606335'),
('+916378977949', 'SSF3832260'),
('+916201171767', 'SSF3992589'),
('+916204434840', 'SSF3810132'),
('+916024585585', 'SSF3661842'),
('+916260706674', 'SSF3973306'),
('+916377158139', 'SSF2689121'),
('+917004793007', 'SSF4226951'),
('+917004553257', 'SSF3796501'),
('+917994994315', 'SSF3808170'),
('+917352295510', 'SSF3675416'),
('+917543917227', 'SSF3875533'),
('+917633030717', 'SSF3773118'),
('+917277991510', 'SSF3671558'),
('+917250253181', 'SSF3551938'),
('+917541939148', 'SSF3862624'),
('+917717740283', 'SSF3615677'),
('+918227814072', 'SSF3564703'),
('+918651013071', 'SSF4310630'),
('+918757334789', 'SID951375142805'),
('+918670466263', 'SSF4393930'),
('+918540875584', 'SSF3654083'),
('+918908465659', 'SSF3662042'),
('+918521313454', 'SSF3636506'),
('+918696519621', 'SSF4915820'),
('+918302660069', 'SSF2589777'),
('+918688808988', 'SSF3677310'),
('+919509722026', 'SSF2621233'),
('+919135835956', 'SSF3868653'),
('+919587347714', 'SSF3888597'),
('+919343198493', 'SSF2983455'),
('+919836838686', 'SSF3701013'),
('+919858568556', 'SSF3682635'),
('+919540698125', 'SSF3768489'),
('+919737439467', 'SID951375521407'),
('+919531616498', 'SSF2298057'),
('+919939133417', 'SSF3908884'),
('+917307202944', 'SSF5076749'),
('+919359210934', 'SSF5589999'),
('+919304383090', 'SSF4894338'),
('+919394375652', 'SSF4489062'),
('+917349878514', 'SSF5198453'),
('+918393881726', 'SSF6078753'),
('+919162461160', 'SSF5555636'),
('+918317050794', 'SSF5574873'),
('+919931328215', 'SSF5585823'),
('+919264978169', 'SSF3566595'),
('+916289575625', 'SSF3636271'),
('+918809678568', 'SSF3554940'),
('+919993298926', 'SSF3603872'),
('+919343552365', 'SSF3557603'),
('+919348053167', 'SSF5206762'),
('+916264739540', 'SSF3485153'),
('+916266539063', 'SSF3456996'),
('+916281840494', 'SSF3383198'),
('+916358461848', 'SSF3778774'),
('+917654226914', 'SSF3479438'),
('+917763867380', 'SSF3284127'),
('+917485853024', 'SID951375053696'),
('+917410984191', 'SSF4159056'),
('+917349944949', 'SSF3270901'),
('+917737983921', 'SSF3192938'),
('+918936050816', 'SSF3361165'),
('+918340572363', 'SSF3435290'),
('+918905121472', 'SSF3265950'),
('+918764846949', 'SSF3498663'),
('+918787940404', 'SID951375883893'),
('+919361599449', 'SSF3304804'),
('+919065427325', 'SSF3383976'),
('+919464048704', 'SSF3286424'),
('+919564648116', 'SSF3831814'),
('+919576800558', 'SSF3249005'),
('+919124254235', 'SSF3604646'),
('+919508061095', 'SSF4043761'),
('+919897766737', 'SSF3471921'),
('+919116597486', 'SSF2877684'),
('+919813879652', 'SSF3205551'),
('+919797646949', 'SSF3325452'),
('+916296867900', 'SSF3244845'),
('+916267859176', 'SSF3429491'),
('+916208576648', 'SSF3283618'),
('+916352959656', 'SSF3154788'),
('+917733861977', 'SSF2375198'),
('+917739419068', 'SSF3279591'),
('+918209617068', 'SSF3607883'),
('+918596857422', 'SSF3110571'),
('+918564646464', 'SSF3640064'),
('+919658548865', 'SID951375661835'),
('+919767946346', 'SSF3100952'),
('+919321432755', 'SSF3179055'),
('+919464664649', 'SSF3447497'),
('+919496946494', 'SSF3447603'),
('+919678535569', 'SSF3312243'),
('+919669836046', 'SSF3123378'),
('+919785469649', 'SSF3248055'),
('+919871380086', 'SSF3300066'),
('+917543809727', 'SSF5207644'),
('+917009441941', 'SSF5207645'),
('+917061048983', 'SSF5924688'),
('+917004905213', 'SSF5960008'),
('+918409716502', 'SSF5544969'),
('+919693596640', 'SSF5684558'),
('+917566552932', 'SSF3124577'),
('+917665106622', 'SSF2949916'),
('+919996467679', 'SSF2837935'),
('+919993323041', 'SSF3679682'),
('+919784513124', 'SSF3385006'),
('+919001540937', 'SSF2876621'),
('+917779927651', 'SSF5294397'),
('+917404868256', 'SSF5713800'),
('+919234171940', 'SSF5768669'),
('+918307960702', 'SSF2865129'),
('+918554865455', 'SSF2969754'),
('+918003474772', 'SSF2305245'),
('+919525430861', 'SSF3012598'),
('+917091713614', 'SSF5587906'),
('+917544079182', 'SSF5641860'),
('+919610214143', 'SSF5644374'),
('+918603024151', 'SSF5640564'),
('+916261388272', 'SSF2856267'),
('+918770893120', 'SSF3641182'),
('+917470320256', 'SSF3388531'),
('+919587904139', 'SSF5365028'),
('+918860109283', 'SSF3385052'),
('+919343096226', 'SID951374493352'),
('+918340711804', 'SID951375665595'),
('+919334539802', 'SID951373661917'),
('+917310286316', 'SSF5413100'),
('+919464548646', 'SSF3857271'),
('+919256409517', 'SSF4421310'),
('+919216710249', 'SSF6149595'),
('+919301065802', 'SSF3054717'),
('+917218763394', 'SSF3839396'),
('+918002758507', 'SSF4765964'),
('+916367673134', 'SID951376003057'),
('+917354273049', 'SSF4851124'),
('+917209928427', 'SSF5317077'),
('+918010287087', 'SSF4017141'),
('+918690445656', 'SID951374536868'),
('+919023025642', 'SSF5772820'),
('+919162142363', 'SSF5772824'),
('+919520100195', 'SSF6025244'),
('+916260367168', 'SID951374433391'),
('+919304931688', 'SSF5063628'),
('+919785553168', 'SSF5865688'),
('+919835347457', 'SSF5966297'),
('+919065118642', 'SID951376006575'),
('+918826778396', 'SSF6198398'),
('+917348778808', 'SSF4015678'),
('+919358136896', 'SID951375459478'),
('+919399804719', 'SID951375899767'),
('+918340620970', 'CID212400651'),
('+919838476440', 'SSF4728397'),
('+917607636960', 'SSF5755391'),
('+918877475513', 'SSF5892275'),
('+919509215547', 'SSF3850700'),
('+919633144455', 'SSF2924295'),
('+918252615260', 'SSF6285899'),
('+917761849571', 'SSF5528533'),
('+918797509150', 'SID951374938585'),
('+919006397134', 'SSF5953445'),
('+917700805482', 'SSF3090433'),
('+918252441712', 'SSF5941724'),
('+917310913892', 'SSF2769697'),
('+918235968352', 'SSF5163548'),
('+916380195865', 'SSF5316444'),
('+917905464406', 'SID951374964428'),
('+919165890696', 'SID951374179885'),
('+918448241193', 'SSF5437515'),
('+918273781376', 'SSF5705992'),
('+917909852894', 'SSF3622760'),
('+919131431248', 'SID951375646529'),
('+919931329465', 'SSF2669747'),
('+917870329773', 'SSF4059865'),
('+918755459858', 'SSF5390869'),
('+919876672713', 'SID951376056688'),
('+919060528324', 'SSF3594161'),
('+919993554028', 'SID951374601150'),
('+919835758345', 'SSF2680635'),
('+918690011597', 'SSF4305298'),
('+917489396075', 'SSF5390663'),
('+919644856279', 'SID951374244632'),
('+919110908039', 'SID951375559079'),
('+919758534251', 'SSF5657559'),
('+917634802902', 'SSF6196383'),
('+917484823708', 'SSF5733852'),
('+918871369127', 'SID951372818440'),
('+916377648808', 'SSF2901529'),
('+919669753223', 'SID951375129067'),
('+919783774101', 'SSF3411609'),
('+919934090660', 'SSF5145244'),
('+917073651905', 'SSF6061959'),
('+919523255095', 'SID951375680146'),
('+917294930660', 'SSF6140663'),
('+918948414132', 'SSF3662145'),
('+916205296254', 'SSF6273664'),
('+919006653082', 'SSF5953222'),
('+917078886186', 'SSF5952690'),
('+917581939706', 'SID951374992626'),
('+919625126071', 'SSF5055977'),
('+917479802146', 'SSF5693144'),
('+918696216865', 'SSF2880186'),
('+917724860372', 'SSF3067870'),
('+917543041069', 'SSF2514052'),
('+917739216495', 'SSF5809017'),
('+917428391772', 'SSF4396864'),
('+919546485589', 'SID951373437899'),
('+918757980813', 'SSF3088828'),
('+916307651577', 'SSF5022012'),
('+918519028344', 'SID951375098148'),
('+919973176902', 'SSF5511359'),
('+919815792254', 'SSF4840440'),
('+917389779649', 'SID951374345132'),
('+917440318296', 'SSF2440297'),
('+919852718190', 'SSF2796935'),
('+918252334362', 'SSF6179858'),
('+917970921203', 'SSF6216964'),
('+916260012986', 'CID084702019'),
('+919216686393', 'SID951373945637'),
('+917294048976', 'SSF2615082'),
('+916268946637', 'SSF3635018'),
('+918737887361', 'SID951374632936'),
('+918429085467', 'SSF5622661'),
('+916201231161', 'SSF3709303'),
('+918252728565', 'SID951374919756'),
('+919131324794', 'SID951375547586'),
('+918521048873', 'SSF5132749'),
('+917319694107', 'SSF5427211'),
('+918934844516', 'SSF3538023'),
('+917870329482', 'SSF5639788'),
('+917462875292', 'SSF4887095'),
('+919305756381', 'SSF2420026'),
('+919285231698', 'SID951373052504'),
('+917780839090', 'SSF3657180'),
('+917300445456', 'SID951375885512'),
('+919631287645', 'SSF5701987'),
('+919693650986', 'SSF4379985'),
('+916381530487', 'SSF5724175'),
('+919579521742', 'SSF2597657'),
('+919589348270', 'SID951375896691'),
('+917631704437', 'SSF5677110'),
('+917999840963', 'SID2125310912'),
('+919835220698', 'SSF6581633'),
('+918827771162', 'SSF3119362'),
('+919685948896', 'SSF3130591'),
('+919302415915', 'SID951375132382'),
('+917067750060', 'CID205603750'),
('+917909446742', 'SSF2909939'),
('+917542927439', 'SSF5691505'),
('+919580703960', 'SSF4862685'),
('+919301043395', 'SSF3738239'),
('+917340195134', 'SSF4587159'),
('+917667615503', 'SSF6591366'),
('+916264398078', 'SSF4024480'),
('+916263562345', 'SSF3718446'),
('+919341777464', 'CID212400587'),
('+919369244096', 'SSF5480439'),
('+917856847921', 'SSF5759191'),
('+917209118574', 'SSF4351431'),
('+918440950965', 'SSF3015986'),
('+919507946605', 'SSF4246318'),
('+917737533547', 'SSF3190657'),
('+919343078717', 'SSF2757782'),
('+919301348874', 'SID951373754652'),
('+918817926935', 'SSF2716529'),
('+918254565788', 'SID951375921398'),
('+917389829712', 'SID951375118513'),
('+918210544092', 'SSF4176165'),
('+919305371574', 'CID212300993'),
('+919660798266', 'SSF3361692'),
('+917725005621', 'SID951375503424'),
('+918187998097', 'SSF4301883'),
('+916200902090', 'SID951374546886'),
('+919630391166', 'SSF4558812'),
('+919893717656', 'SID951374305860'),
('+919406059376', 'SSF2687930'),
('+918002152285', 'SSF4250851'),
('+919111960837', 'SID951376029544'),
('+917857814227', 'SSF5165248'),
('+919413348494', 'SSF3810903'),
('+917970140254', 'SSF5086685'),
('+919631301337', 'SSF5350571'),
('+918235955055', 'SSF2570613'),
('+917488696979', 'SSF3674152'),
('+916267535221', 'SSF5984903'),
('+918112603142', 'SSF6079914'),
('+919305908890', 'SSF6156218'),
('+918305661979', 'CID206701312'),
('+918102885603', 'SSF2612377'),
('+917737715594', 'SSF6072683'),
('+919664140126', 'SSF5380269'),
('+916265341278', 'SSF2842137'),
('+918269933140', 'SID951375347546'),
('+919031401743', 'SSF5231999'),
('+917973074729', 'SID951375288897'),
('+919340290299', 'SSF3684974'),
('+917225998203', 'SSF2758254'),
('+918177048281', 'SSF3108717'),
('+919709393802', 'SSF5218878'),
('+919044636871', 'SSF5437393'),
('+919993849802', 'SSF4302335'),
('+919984522614', 'SSF5000949'),
('+919084429048', 'SSF6063724'),
('+917879795323', 'SID951374946247'),
('+919131048030', 'SSF4115138'),
('+916283778736', 'SID951375002122'),
('+917898932904', 'SID951374053908'),
('+916205083221', 'SID951375645322'),
('+919976949648', 'SSF3428050'),
('+918815411797', 'SID2125315140'),
('+917610489067', 'SSF4492992'),
('+917440439412', 'CID225200676'),
('+916376385298', 'SID951374724406'),
('+919076804439', 'SSF6045266'),
('+918084985109', 'SSF3547960'),
('+919713676373', 'SSF3322578'),
('+918641039203', 'SSF3032226'),
('+918051806826', 'SSF2744455'),
('+917827245855', 'SSF5489424'),
('+916206177160', 'SSF5869502'),
('+917999363263', 'SID951374324715'),
('+918003257028', 'SSF3813880'),
('+917742482159', 'SSF3109347'),
('+916367559782', 'SSF2663592'),
('+919344093050', 'SSF6579335'),
('+919509560796', 'SSF2506018'),
('+919329764997', 'SID951373341819'),
('+918962761311', 'SID951375930521'),
('+919525870814', 'SSF2894242'),
('+916265139054', 'SID951373792196'),
('+919516031671', 'SID951373458656'),
('+916261745314', 'SSF5605485'),
('+917488146242', 'SSF2844645'),
('+919977566957', 'SID951372921206'),
('+919549165574', 'SSF5395202'),
('+916299236920', 'SID951375704886'),
('+918092872702', 'SSF5833727'),
('+918982678615', 'SID951374949170'),
('+918305554663', 'CID050411397'),
('+919302541833', 'CID129109452'),
('+919165619112', 'SID951376022772'),
('+917781820563', 'SSF5665126'),
('+919651216126', 'SSF5121806'),
('+918963965373', 'CID072002316'),
('+917634034974', 'SSF5924669'),
('+919472709445', 'SID951374490137'),
('+919244307264', 'SSF5674779'),
('+918806704068', 'SID2125235390'),
('+919955919464', 'SSF2588103'),
('+917857025629', 'SID951374220264'),
('+917427067701', 'SID951375357312'),
('+918540972177', 'SID951375541547'),
('+919001223842', 'SID951375145390'),
('+919928082988', 'SID951374429971'),
('+916265555649', 'SSF2499177'),
('+916206816269', 'SSF2620438'),
('+917644003907', 'SSF2553479'),
('+919199345008', 'SSF2763896'),
('+916360090347', 'SSF4262734'),
('+916304912781', 'SSF4441896'),
('+916394054483', 'SSF3491185'),
('+916299065143', 'SSF4742118'),
('+916268761808', 'SSF4760477'),
('+916200575699', 'SSF5095155'),
('+916263088194', 'SSF4346721'),
('+916267337791', 'SSF4816806'),
('+917352827736', 'SSF4439920'),
('+917340262470', 'SSF4452833'),
('+917654211166', 'SSF4242757'),
('+917067322386', 'SSF3609833'),
('+917803094307', 'SSF4247519'),
('+917247368852', 'SSF5057122'),
('+917303110248', 'SSF4837119'),
('+917667673921', 'SSF4835815'),
('+917858939117', 'SSF3429210'),
('+917400319921', 'SSF4548532'),
('+917416086491', 'SSF4712060'),
('+918602625336', 'SSF4698453'),
('+918088647341', 'SSF4527564'),
('+918581004380', 'SSF4439927'),
('+918809999171', 'SSF4802469'),
('+918450893742', 'SSF4692885'),
('+918889560919', 'SSF4684537'),
('+918815438868', 'SSF3720654'),
('+918279274983', 'SSF4475530'),
('+918435993183', 'SSF4506467'),
('+918423605058', 'SSF4876235'),
('+918987506109', 'SSF4801683'),
('+918529838472', 'SSF4082294'),
('+918228802707', 'SSF4780567'),
('+918777767797', 'SSF3343177'),
('+918306370303', 'SSF4687489'),
('+918107635320', 'SID951375902202'),
('+918434601737', 'SSF4860618'),
('+918306040964', 'SSF3059912'),
('+918541079403', 'SSF4833949'),
('+918871384728', 'SSF4988239'),
('+919241265706', 'SSF3211313'),
('+919341267092', 'SSF4486815'),
('+919135394431', 'SSF4860381'),
('+919648687401', 'SSF4415333'),
('+919783357218', 'SSF5294114'),
('+919065077087', 'SSF4681055'),
('+919065884661', 'SSF3463692'),
('+919905874194', 'SSF3582629'),
('+919341012429', 'SSF4328447'),
('+919399839654', 'SSF4558268'),
('+919571732686', 'SSF3831194'),
('+919358683167', 'SSF4416061'),
('+919279586706', 'SSF5097162'),
('+919234545686', 'SSF4548709'),
('+919661829597', 'SSF4859992'),
('+919584744868', 'SSF5057396'),
('+919508401835', 'SSF4472849'),
('+919279911301', 'SSF4795720'),
('+919006545706', 'SSF4330773'),
('+919102520281', 'SSF4333761'),
('+919608675980', 'SID2125583022'),
('+916238594244', 'SSF4568549'),
('+916909704699', 'SSF4703640'),
('+916287925648', 'SSF4321187'),
('+916265181419', 'SSF4597290'),
('+916206604172', 'SSF3293170'),
('+916201685496', 'SSF3287099'),
('+916263726720', 'CID213814243'),
('+916264965918', 'SSF4648990'),
('+916201685357', 'SID951372971733'),
('+916265721161', 'SSF4216368'),
('+916351807006', 'SSF4374108'),
('+917874168390', 'SSF4103939'),
('+917672880994', 'SSF4147235'),
('+917903326106', 'SSF4710177'),
('+917070516890', 'SSF4598817'),
('+917297800676', 'SSF2286649'),
('+917044238659', 'SSF4950696'),
('+917462818709', 'SSF4896227'),
('+917764090137', 'SSF5778325'),
('+917827643571', 'SSF4682486'),
('+917070393895', 'SSF4313673'),
('+917482965390', 'SSF5809479'),
('+917383589257', 'SSF4689445'),
('+917869887731', 'SSF4617093'),
('+918797778556', 'SSF5353852'),
('+918271856600', 'SSF3827212'),
('+918210271580', 'SSF3805472'),
('+918290519035', 'SSF4631057'),
('+918340408301', 'SSF3211123'),
('+918709840292', 'SSF3054847'),
('+918305511890', 'SSF4634884'),
('+918982624998', 'SSF4803032'),
('+919351496695', 'SSF4099489'),
('+919997212688', 'SSF4876437'),
('+919753527693', 'SSF4708929'),
('+919939172487', 'SSF4342211'),
('+919234670149', 'SSF4367831'),
('+919006191774', 'SSF2587468'),
('+919771990846', 'SSF4925704'),
('+919835288163', 'SSF2732882'),
('+919955346018', 'SSF4964213'),
('+919546921807', 'SSF4630168'),
('+919572953613', 'SSF4302026'),
('+919265526690', 'SSF4172300'),
('+919801373452', 'SSF4586920'),
('+919771036003', 'SSF4578490'),
('+919060158290', 'SSF4240919'),
('+919031783481', 'SSF4574768'),
('+919960683023', 'SSF4406811'),
('+919661849532', 'SSF4790626'),
('+917700884162', 'SSF5339734'),
('+917562885838', 'SSF4306911'),
('+917462013920', 'SSF5571894'),
('+916299229264', 'SSF5522691'),
('+917676803081', 'SSF5669175'),
('+918409995266', 'SSF5718799'),
('+916290549625', 'SSF5541567'),
('+917261840238', 'SSF5426082'),
('+917973125099', 'SSF5535436'),
('+917781989513', 'SSF5832366'),
('+918102138841', 'SSF5418676'),
('+918298923508', 'SSF5830382'),
('+918877355735', 'SSF5389093'),
('+918447441137', 'SSF5574956'),
('+918002763206', 'SSF5375676'),
('+918603037574', 'SSF5434529'),
('+918603458768', 'SSF5708235'),
('+918084166200', 'SSF5712020'),
('+918292885350', 'SSF4971171'),
('+918826563440', 'SSF5766791'),
('+918051621766', 'SSF5589741'),
('+919034531701', 'SSF5089150'),
('+919241271518', 'SSF5565058'),
('+919142969726', 'SSF5498016'),
('+919334678068', 'SSF5325633'),
('+919508940496', 'SSF5544944'),
('+916283357265', 'SSF5698007'),
('+917260913389', 'SSF5449776'),
('+917644863621', 'SSF5714445'),
('+917494883755', 'SSF5933308'),
('+918825184529', 'SSF5575115'),
('+918084563970', 'SSF5582188'),
('+919664995018', 'SSF5667652'),
('+919076832596', 'SSF4476147'),
('+919263924472', 'SSF5630480'),
('+919792421863', 'SSF5992646'),
('+919241386403', 'SSF5439925'),
('+919519841021', 'SSF5463067'),
('+916348241848', 'SSF3852521'),
('+916263105986', 'SSF3970951'),
('+916294627649', 'SSF3868807'),
('+916206144651', 'SSF4223736'),
('+916267133126', 'SID951375724087'),
('+917671976900', 'SID951372921872'),
('+917489510567', 'SSF3983088'),
('+917781033435', 'SSF3951233'),
('+917033099912', 'SSF4209262'),
('+917258889732', 'SSF4314997'),
('+917230976751', 'SSF3926558'),
('+917024631980', 'SID951372890120'),
('+917991506965', 'SSF3941672'),
('+918873423540', 'SSF5562869'),
('+918235540876', 'SSF2590077'),
('+918674935941', 'SSF4386129'),
('+918873007874', 'SSF4320635'),
('+918210805446', 'SSF4270974'),
('+918002667653', 'SSF4258002'),
('+918252788701', 'SSF3871688'),
('+918120302625', 'SSF4023074'),
('+918252429285', 'SSF4845861'),
('+918271654811', 'SSF3090311'),
('+918875699239', 'SSF4228261'),
('+919572868119', 'SSF4312510'),
('+919279029873', 'SID951374219864'),
('+919508289704', 'SSF4391813'),
('+919770402119', 'SSF3841442'),
('+919341527380', 'SSF4242843'),
('+919313535856', 'SID951374935063'),
('+919672169314', 'SSF4352469'),
('+919064282010', 'SSF4311666'),
('+919647125579', 'SSF4408056'),
('+919098307285', 'SID951373075027'),
('+919495434663', 'SSF3845814'),
('+919631894329', 'SSF4191152'),
('+919199360363', 'SSF4191193'),
('+919534196064', 'SSF2301379'),
('+919608106438', 'SSF4278305'),
('+919522276998', 'SSF4140143'),
('+919039815256', 'SSF3996665'),
('+916287606630', 'SSF5420574'),
('+916203651197', 'SSF5643396'),
('+917571809936', 'SSF4773167'),
('+917042533958', 'SSF5016622'),
('+917355643306', 'SSF5270551'),
('+917782887149', 'SSF5384013'),
('+917061079978', 'SSF5631435'),
('+917870627576', 'SSF5719826'),
('+917633063726', 'SSF5643434'),
('+917563952234', 'SSF5586933'),
('+917490986796', 'SSF5281482'),
('+917033787547', 'SSF5516028'),
('+918789621289', 'SSF5410013'),
('+918355039088', 'SSF5760909'),
('+918429169571', 'SSF4436245'),
('+918521565187', 'SSF5643909'),
('+918004589508', 'SSF6208299'),
('+919919501427', 'SSF5630591'),
('+919120579391', 'SSF5693072'),
('+919628570205', 'SSF6188645'),
('+919031242776', 'SSF5544943'),
('+919695034225', 'SSF4516797'),
('+916205287848', 'SSF5676936'),
('+917880555227', 'SSF5137273'),
('+917644002203', 'SSF5548683'),
('+917717655402', 'SSF5633752'),
('+917267839185', 'SSF4425545'),
('+918168238635', 'SSF5706142'),
('+919794859004', 'SSF5500541'),
('+917827206432', 'SSF4898116'),
('+919162677994', 'SSF4196440'),
('+916666855666', 'SSF2896872'),
('+916375067408', 'SSF3641353'),
('+916464846446', 'SSF3738068'),
('+916366494694', 'SSF3690583'),
('+916209219009', 'SSF4152813'),
('+917297975315', 'SSF4094560'),
('+917481098594', 'SSF4097206'),
('+917368060051', 'SSF4048736'),
('+917667831635', 'SSF2993419'),
('+918092994348', 'SSF4204391'),
('+918971180395', 'SSF4292955'),
('+918619091830', 'SSF3627676'),
('+918963004098', 'SSF3784816'),
('+918619766772', 'SSF4011742'),
('+918292369728', 'SSF3743475'),
('+918409912840', 'SSF3747358'),
('+918084898896', 'SSF3700016'),
('+918851997289', 'SSF4717043'),
('+918507212045', 'SSF4000365'),
('+918824713088', 'SSF2774320'),
('+918102117304', 'SID951376131689'),
('+918817856271', 'SSF3280239'),
('+918952108946', 'SSF3751495'),
('+918871589144', 'SSF3049796'),
('+919263191773', 'SSF3959210'),
('+919680454379', 'SSF3815534'),
('+919216256515', 'SSF4053913'),
('+919798913522', 'SSF4489210'),
('+919060835064', 'SSF4078857'),
('+919561359419', 'SSF4049974'),
('+919155995624', 'SSF4368413'),
('+919610125983', 'SSF4226661'),
('+919494949799', 'SSF2691255'),
('+919786764468', 'SSF3831772'),
('+919862550687', 'SSF3602155'),
('+919565664646', 'SSF3645685'),
('+919153494351', 'SSF4092342'),
('+919981409867', 'SSF4152651'),
('+919509323570', 'SID951373806148'),
('+919658888552', 'SSF3730050'),
('+919973761523', 'SSF3976889'),
('+919199819585', 'SSF4123615'),
('+919166957759', 'SSF4324356'),
('+919835067253', 'SSF2588696'),
('+919509398328', 'SSF4075285'),
('+919660790503', 'SSF3791635'),
('+919572718444', 'SSF4202217'),
('+916287204687', 'SSF5427221'),
('+917479916886', 'SSF5511584'),
('+917318380270', 'SSF5427068'),
('+917739916427', 'SSF5551072'),
('+918521253426', 'SSF4874159'),
('+918678802610', 'SSF4575040'),
('+919346261864', 'SSF5484383'),
('+919060581601', 'SSF5544266'),
('+916206977560', 'SSF5696903'),
('+917903300648', 'SSF5724667'),
('+918292636081', 'SSF5471144'),
('+918148200374', 'SSF5599622'),
('+919661219256', 'SSF5419980'),
('+919142242499', 'SSF5479621'),
('+917739655645', 'SSF4568696'),
('+918434768148', 'SSF4271458'),
('+918178118936', 'SSF5463666'),
('+919872144512', 'SSF5531796'),
('+916464946494', 'SSF3692152'),
('+917689892572', 'SSF3480032'),
('+917855355242', 'SSF3712686'),
('+919343656899', 'SSF3735883'),
('+918797472991', 'SSF5136360'),
('+919693097031', 'SSF4397365'),
('+917992166089', 'SSF5510244'),
('+919984887223', 'SSF5068379'),
('+916267593376', 'SSF3654939'),
('+916264558192', 'SSF3600779'),
('+916203542809', 'SSF3615666'),
('+916208564862', 'SSF3443137'),
('+917541852225', 'SID951375247733'),
('+917296887359', 'SSF3449956'),
('+917354616427', 'CID261400850'),
('+917295053805', 'SSF3646013'),
('+918809483633', 'SSF4497228'),
('+918046466434', 'SID951374347399'),
('+918754646768', 'SSF3793922'),
('+918290529224', 'SSF2512834'),
('+918450764984', 'SSF3535953'),
('+918209524137', 'SSF3589061'),
('+918090909000', 'SSF3692451'),
('+919608521548', 'SSF3838152'),
('+919380320519', 'SSF3652436'),
('+919855345487', 'SSF3772121'),
('+919358093131', 'SSF3831487'),
('+919864548464', 'SSF3234960'),
('+919602868310', 'SSF3601196'),
('+919828412609', 'SSF3434691'),
('+919787076491', 'SSF3644875'),
('+919542121811', 'SSF3637646'),
('+919279488361', 'SSF3381212'),
('+919497949848', 'SSF3612876'),
('+916386703794', 'SSF3590741'),
('+917456783183', 'SID951374846783'),
('+917737163402', 'SSF3251392'),
('+918112281373', 'SSF3508889'),
('+918959231209', 'SSF3838793'),
('+918812551416', 'SSF3333368'),
('+918889906324', 'SSF3337824'),
('+918852478558', 'SSF3351587'),
('+919741258956', 'SSF3445883'),
('+919085800750', 'SSF3228990'),
('+919341949620', 'SSF3827803'),
('+919153473050', 'SSF3362909'),
('+919856774658', 'SSF3155980'),
('+919602316727', 'SSF2478283'),
('+917587382635', 'SSF3446280'),
('+919498404331', 'SSF3000628'),
('+919772153949', 'SSF3222795'),
('+916207991782', 'SSF5511700'),
('+919670158206', 'SSF4641679'),
('+919631463608', 'SSF5724198'),
('+917482083186', 'SSF5755819'),
('+917856830894', 'SSF5623250'),
('+918448852840', 'SSF5771159'),
('+918456133467', 'SSF3489274'),
('+918655577775', 'SSF3242247'),
('+919155481141', 'SSF5842382'),
('+916392985706', 'SSF4337669'),
('+919162447408', 'SSF5688853'),
('+919122973059', 'SSF5058796'),
('+916294004059', 'SSF5195670'),
('+918298588526', 'SSF5725438'),
('+919534578524', 'SSF5273744'),
('+919262528033', 'SSF5509111'),
('+919569623937', 'SSF5269553'),
('+919521512435', 'SSF5196165'),
('+919263638884', 'SSF4773087'),
('+917737466828', 'SSF2454011'),
('+919142713560', 'SID951375899750'),
('+916375426914', 'SSF4759785'),
('+916205899179', 'SSF4323097'),
('+916267989445', 'SSF4684298'),
('+916261391740', 'SSF4446049'),
('+917023246502', 'SSF4406254'),
('+917765882859', 'SSF4820453'),
('+917546908194', 'SSF4860396'),
('+917209884232', 'SSF2904009'),
('+917461032577', 'SSF4482432'),
('+918690718477', 'SSF4814275'),
('+919376594845', 'SSF3129133'),
('+919702526585', 'SSF4585214'),
('+919122634012', 'SSF3212994'),
('+919155072350', 'SSF4567681'),
('+919006153067', 'SSF4801192'),
('+919304196736', 'SSF5351062'),
('+919755861030', 'SSF2835639'),
('+919307192985', 'SSF4241691'),
('+916287607907', 'SSF3169896'),
('+916239113328', 'SSF4647534'),
('+917463023510', 'SSF4605945'),
('+917033079384', 'SSF4620035'),
('+917024513366', 'SSF4682429'),
('+917061920873', 'SSF4123382'),
('+917294961278', 'SSF4862359'),
('+917295945374', 'SSF3327180'),
('+917367974503', 'SSF5121474'),
('+917261088014', 'SSF4579437'),
('+917739217107', 'SSF4678949'),
('+917759819425', 'SSF5592809'),
('+917634860472', 'SSF4640085'),
('+918434897284', 'SSF4569131'),
('+918540825945', 'SSF4466954'),
('+918002596480', 'SSF4663315'),
('+918935917720', 'SSF4796811'),
('+918081043928', 'SSF2468931'),
('+919546878315', 'SSF4569185'),
('+919311264929', 'SSF4832469'),
('+919934340491', 'SSF2561486'),
('+919334136526', 'SSF4662945'),
('+919679991935', 'SSF4616091'),
('+919279781450', 'SSF4296180'),
('+919973577467', 'SSF4644489'),
('+919117954788', 'SSF4604233'),
('+919905634638', 'SSF4609404'),
('+919661292160', 'SID951375246451'),
('+919399636095', 'SSF3060402'),
('+919931039639', 'SSF4689435'),
('+918210024632', 'SSF3258354'),
('+916387663357', 'SSF5339891'),
('+916202130182', 'SSF5096748'),
('+916306005707', 'SSF5300322'),
('+917897090333', 'SSF5324968'),
('+917461991076', 'SSF5335235'),
('+917296075448', 'SSF5766149'),
('+917667518081', 'SSF5588870'),
('+917209113961', 'SSF5588871'),
('+917250924071', 'SSF5561848'),
('+919569734013', 'SSF5329859'),
('+919241817421', 'SSF5525061'),
('+919102046808', 'SSF5560197'),
('+919718041372', 'SSF5763546'),
('+916203316617', 'SSF5522692'),
('+916205840352', 'SSF5933704'),
('+917407698671', 'SSF5285503'),
('+917780473217', 'SSF5733664'),
('+917033880992', 'SSF5631568'),
('+917317064147', 'SSF5487816'),
('+918057671148', 'SSF6183142'),
('+918528798454', 'SSF4467691'),
('+918434477483', 'SSF5718943'),
('+918809309601', 'SSF5755511'),
('+918126861954', 'SSF5391585'),
('+918887512837', 'SSF5827790'),
('+919153293801', 'SSF4868544'),
('+919006432264', 'SSF5341488'),
('+919162490552', 'SSF5314666'),
('+919279749614', 'SSF5522693'),
('+919234916499', 'SSF5858027'),
('+919608748425', 'SSF5970217'),
('+917045339144', 'SSF5757493'),
('+917763928610', 'SSF5336287'),
('+919162951096', 'SSF5711226'),
('+919279126442', 'SSF5118760'),
('+919279665162', 'SSF4960047'),
('+917905691287', 'SSF5588065'),
('+918699488205', 'SSF5582235'),
('+918528435828', 'SSF5477333'),
('+918429109907', 'SSF5313371'),
('+919399874970', 'CID040216962'),
('+919060559162', 'SSF5113455'),
('+916268189100', 'SSF4051625'),
('+916307992307', 'SSF3051596'),
('+916265272289', 'SID951373820477'),
('+917765020905', 'SSF4299003'),
('+917480873191', 'SSF4320023'),
('+917909852515', 'SSF4091431'),
('+917869025378', 'SSF4267878'),
('+917061569517', 'SSF4191119'),
('+917295022859', 'SSF4269160'),
('+917739199074', 'SSF4107894'),
('+917488884304', 'SSF4320083'),
('+917739382286', 'SSF3862889'),
('+918092471575', 'SSF4084129'),
('+918235393179', 'SSF4224854'),
('+918233101492', 'SSF3960406'),
('+918207863068', 'SSF4362456'),
('+918797371824', 'SSF4242658'),
('+918871873051', 'SSF4478992'),
('+918759401036', 'SSF4102896'),
('+918002669798', 'SSF4213866'),
('+918092103478', 'SSF4245344'),
('+918670061215', 'SSF4370781'),
('+919166850257', 'SSF5103117'),
('+919343083739', 'SSF4476093'),
('+919341720083', 'SSF5051262'),
('+919973487344', 'SSF3313722'),
('+919661423210', 'SSF4171631'),
('+919507862564', 'SSF4748151'),
('+919199120788', 'SSF4309488'),
('+919931652224', 'SSF4280856'),
('+919153579002', 'SSF3356312'),
('+919109316780', 'SSF3996664'),
('+919635284122', 'SID951376088183'),
('+916200219855', 'SSF5507537'),
('+918603159130', 'SSF5624318'),
('+918320768413', 'SSF5217410'),
('+917497910949', 'SSF5664686'),
('+917233937572', 'SSF5135727'),
('+918299650834', 'SSF5323915'),
('+918303799070', 'SSF5527502'),
('+919129448076', 'SSF5661394'),
('+917667204878', 'SSF4196418'),
('+918757487377', 'SSF4768810'),
('+916287888888', 'SSF3737459'),
('+916350394118', 'SSF4108335'),
('+916377436538', 'SSF3556559'),
('+916754678409', 'SID951375487336'),
('+917575542442', 'SID951375369510'),
('+917764984653', 'SSF4220511'),
('+917488853366', 'SSF4094730'),
('+917836251788', 'SSF3824922'),
('+917260017762', 'SSF2919570'),
('+917294180898', 'SSF4012690'),
('+917804957875', 'SSF3537258'),
('+918080257180', 'SSF4075840'),
('+918102913029', 'SSF3734784'),
('+918102257246', 'SSF3747991'),
('+918107885205', 'SSF4050676'),
('+918521821712', 'SSF3303786'),
('+918770757680', 'SSF2828987'),
('+918434045712', 'SSF4202199'),
('+919549369912', 'SSF2839588'),
('+919685274638', 'SSF3687401'),
('+919162014166', 'SSF2543015'),
('+919523484880', 'SID951374483326'),
('+919762379464', 'SID951375273347'),
('+919630945957', 'SID951374431145'),
('+919039361447', 'SSF4177777'),
('+919166096287', 'SSF3819203'),
('+919669082036', 'SID951373330699'),
('+919341345176', 'SSF3939595'),
('+919065461993', 'SID951375729417'),
('+919302786973', 'SSF3760966'),
('+919648133494', 'SSF3643699'),
('+919509951064', 'SSF3835348'),
('+919588880205', 'SSF4046970'),
('+916287537486', 'SSF5089815'),
('+917880468872', 'SSF4894486'),
('+917319788238', 'SSF4911635'),
('+919931186352', 'SSF5507838'),
('+917505868110', 'SSF5586558'),
('+918557816596', 'SSF5067172'),
('+919305183466', 'SSF4941989'),
('+919973675138', 'SSF5045370'),
('+919555127540', 'SSF4589582'),
('+919162655734', 'SSF5532254'),
('+919628934159', 'SSF5298866'),
('+917408712175', 'SSF5020258'),
('+918092419226', 'SSF5013174'),
('+916379831626', 'SSF3288229'),
('+916267220721', 'SSF3486854'),
('+916555554455', 'SID951374665187'),
('+916287373694', 'SSF4061121'),
('+916468660066', 'SSF3481529'),
('+917079975214', 'SSF3364427'),
('+917229926857', 'SSF3840531'),
('+917888888888', 'SSF3462421'),
('+917070021977', 'SSF3615714'),
('+917050909738', 'SSF3636177'),
('+918809037402', 'SSF4053131'),
('+918251081459', 'SSF3555665'),
('+918787554554', 'SSF3725978'),
('+918928913726', 'SSF3692393'),
('+919788767686', 'SID951373899197'),
('+919340560790', 'SSF3765052'),
('+919166500498', 'SSF4140318'),
('+919570679531', 'SSF3477127'),
('+919764137194', 'SID951375901977'),
('+919741535588', 'SSF3568113'),
('+919636254789', 'SSF3499066'),
('+919023780428', 'SSF3654937'),
('+919358657965', 'SSF2789070'),
('+919155834923', 'SSF3615690'),
('+919414933334', 'SSF4759766'),
('+916900005009', 'SSF3692408'),
('+917415181986', 'SSF3543662'),
('+917380700259', 'SSF4388323'),
('+918957395083', 'SSF3561515'),
('+919098736144', 'SID951376032799'),
('+919783195773', 'SSF3673220'),
('+919145916582', 'SSF2357182'),
('+919153424950', 'SSF3827910'),
('+919464849464', 'SID951376192033'),
('+917761940501', 'SSF5561791'),
('+917389526426', 'SSF3655860'),
('+918555559999', 'SSF3199488'),
('+918373454578', 'SSF2577820'),
('+918305590819', 'SSF3264877'),
('+919575840222', 'SSF3000627'),
('+918401115102', 'SSF4651849'),
('+918676937515', 'SSF5055999'),
('+919660256230', 'SSF2932612'),
('+919983546654', 'SSF2601165'),
('+919835594450', 'SSF5987861'),
('+917549719234', 'SSF5659707'),
('+918709508339', 'SSF5197408'),
('+917481095988', 'SSF5766079'),
('+918292545410', 'SSF5326862'),
('+917543974834', 'SSF3903668'),
('+918688167113', 'SSF4613988'),
('+917889297853', 'SSF5060536'),
('+918228008289', 'SSF5722669'),
('+917814658525', 'SSF4976357'),
('+918700095991', 'SSF2793975'),
('+919244684605', 'SSF4929645'),
('+916265994705', 'SSF5524726'),
('+917294196227', 'SSF3567324'),
('+917667919134', 'SSF5384822'),
('+919879526835', 'SSF3732420'),
('+916067654946', 'SSF2425060'),
('+917895411520', 'SSF6150180'),
('+917089001512', 'SSF3946390'),
('+918051275652', 'SSF5264558'),
('+918817079415', 'SID951373467506'),
('+916203593330', 'SSF3042779'),
('+918529534769', 'SSF6124585'),
('+919771715108', 'SSF4896447'),
('+917073422894', 'SSF4925495'),
('+917762066524', 'SSF6431132'),
('+918006192034', 'SSF6024574'),
('+919799273081', 'SSF2739365'),
('+917325091987', 'SID951375779621'),
('+918305545213', 'SID951372856924'),
('+917300959398', 'SSF6170427'),
('+917247269194', 'SID951373798257'),
('+919131254445', 'SSF3368959'),
('+919234714059', 'SSF5714264'),
('+917023393437', 'SSF3170418'),
('+917240913592', 'SSF4117597'),
('+917764923227', 'SSF4456419'),
('+918102257247', 'SSF5989816'),
('+916281081262', 'SSF5724164'),
('+919935965762', 'SSF2570866'),
('+917828416315', 'SSF2824332'),
('+919874563214', 'CID093401053'),
('+919955898310', 'SID951373794139'),
('+919582805715', 'SID2125039603'),
('+918223890816', 'SID951374236477'),
('+919005429862', 'SSF4219534'),
('+916261318022', 'SSF3407709'),
('+919410363288', 'SSF5712191'),
('+918349945725', 'SSF4891927'),
('+919754395376', 'CID049913054'),
('+918699331216', 'SID951375469579'),
('+916397624100', 'SSF4920158'),
('+919523410050', 'CID119105155'),
('+917763885922', 'SSF6232934'),
('+917889567495', 'SSF4845992'),
('+916291109301', 'SSF2612271'),
('+917856910858', 'SSF3431973'),
('+919352885594', 'SSF3583272'),
('+918103796287', 'SID951373662193'),
('+919893545999', 'SID951375170477'),
('+919981649291', 'SID951373857309'),
('+919801738010', 'SID951373404572'),
('+917091482097', 'SSF6006613'),
('+917050442231', 'SSF6199927'),
('+919350222890', 'SSF2700608'),
('+919630677514', 'SID951374896036'),
('+917856970971', 'SID951376192225'),
('+918817674702', 'SSF3465141'),
('+919905714367', 'SID951375121412'),
('+918423402543', 'SSF4286921'),
('+916238237982', 'SSF2540047'),
('+917482075629', 'SSF6030900'),
('+917877595152', 'SSF4628542'),
('+916396816156', 'SSF5169469'),
('+917241176607', 'CID128705245'),
('+918815883554', 'SSF3608337'),
('+919162483074', 'SSF5756127'),
('+919117836686', 'SID951375214201'),
('+919680689883', 'SSF4730898'),
('+917646007952', 'SID951375537488'),
('+919302873608', 'SID951374017465'),
('+917060638556', 'SSF4916901'),
('+919579465659', 'SSF5518392'),
('+916232408326', 'SSF5835058'),
('+916206959474', 'SSF5718118'),
('+919571113541', 'SSF4322514'),
('+919798595598', 'SSF3709417'),
('+919302229357', 'SID951374238165'),
('+919425549913', 'SSF2813798'),
('+919399687309', 'SSF3124806'),
('+919122673477', 'SSF5849007'),
('+917052025325', 'SSF4468958'),
('+917375082176', 'SSF2638194'),
('+917013198994', 'SSF4967150'),
('+917340611303', 'SSF5055470'),
('+919770713023', 'SSF4989930'),
('+916267932653', 'SID951373223712'),
('+919507660526', 'SID951376170986'),
('+919380062813', 'SSF2814418'),
('+919351062238', 'SSF2773294'),
('+919955214772', 'SSF2317635'),
('+917366014356', 'SID951374430309'),
('+917412922672', 'SSF3625370'),
('+916269142584', 'SSF3480022'),
('+918409056974', 'SSF2694362'),
('+918252133722', 'SSF2511738'),
('+917509975514', 'SSF4095508'),
('+916264506427', 'SID951373949572'),
('+919026268066', 'SSF6224276'),
('+917426969036', 'SSF3341595'),
('+917340161277', 'SID951374948130'),
('+919755486808', 'SSF4871490'),
('+918603700327', 'SSF5677389'),
('+916391760166', 'SSF5346235'),
('+916299586697', 'SID951374603428'),
('+917853912613', 'SSF2458347'),
('+919826222542', 'SSF4196632'),
('+919939937480', 'SSF6020193'),
('+919995573520', 'SSF2902158'),
('+917454897320', 'SSF5154075'),
('+917045912465', 'SSF5893273'),
('+918815480644', 'SSF4768948'),
('+919931283635', 'SID951375128392'),
('+918935902296', 'SSF5451840'),
('+919340265741', 'SSF3733955'),
('+919343503727', 'SID951373397063'),
('+919113104287', 'SID951374758372'),
('+919399201826', 'SSF3991341'),
('+916205549480', 'SSF4318516'),
('+919993519734', 'SID2125045297'),
('+917974331947', 'SSF5548467'),
('+918317351023', 'SID951373315686'),
('+919216572926', 'SSF4255735'),
('+919796240044', 'SSF3892558'),
('+919546631732', 'SSF5495145'),
('+918817522326', 'SSF3198393'),
('+919140206749', 'SSF4836999'),
('+918318871985', 'SSF5362703'),
('+918875881419', 'SSF6132984'),
('+918545801942', 'SSF6417960'),
('+917870410846', 'SID951374376570'),
('+917759024116', 'SSF4166986'),
('+919131829750', 'SSF3850439'),
('+919644629358', 'SSF4918344'),
('+917004024005', 'SSF4794723'),
('+919162465225', 'SSF6282571'),
('+917970876727', 'SID951375729541'),
('+917869675925', 'SSF4455809'),
('+918294385972', 'SSF6137421'),
('+918305982876', 'SID2125243557'),
('+919557548641', 'SSF6149841'),
('+918175951196', 'SSF6212292'),
('+918758546374', 'SSF3369090'),
('+919584360477', 'SSF2710553'),
('+917441153398', 'SSF3370013'),
('+918271716749', 'SSF5419675'),
('+918114513043', 'SSF4803013'),
('+918084299633', 'SSF6101020'),
('+919301796820', 'CID261401811'),
('+918604859940', 'SSF2313895'),
('+917620989274', 'SSF6504018'),
('+916201709858', 'SID951374872342'),
('+918354040694', 'SSF4612942'),
('+919770218596', 'SID951374427887'),
('+916305118510', 'SSF6072558'),
('+916386850967', 'SSF3252184'),
('+917319814128', 'SSF3004644'),
('+918720390054', 'SID951374954606'),
('+918102716576', 'SSF6160988'),
('+919608220147', 'SID951373323445'),
('+919982480959', 'SID951375664507'),
('+918603670191', 'SSF5009985'),
('+918871327674', 'SSF3576475'),
('+919054565644', 'SSF5056405'),
('+917050309473', 'SSF6125528'),
('+916291806622', 'SSF6309863'),
('+919983912475', 'SSF6566499'),
('+918851951383', 'SSF5775502'),
('+919669313538', 'SSF2463699'),
('+919321246875', 'SSF2832618'),
('+919317119812', 'SSF6418103'),
('+919470452919', 'SSF6230311'),
('+918051891180', 'SSF6497663'),
('+918910439239', 'SSF5488605'),
('+919699827859', 'SID951374274429'),
('+917782098173', 'SSF3824488'),
('+918303265669', 'SID951374777781'),
('+919303437412', 'SID951374191349'),
('+916289861764', 'CID204504526'),
('+916200396019', 'SSF4990019'),
('+918210108037', 'SSF6118697'),
('+919559976904', 'SID951375715108'),
('+917770099379', 'SID951374799552'),
('+918602957231', 'SID951374925145'),
('+916362393500', 'SSF4884902'),
('+919358109457', 'SID951374755922'),
('+919764843815', 'SID951376005892'),
('+918407064439', 'SID951375932915'),
('+919576113828', 'SID951373202490'),
('+916267518772', 'SID951376156973'),
('+918009757055', 'SSF2571723'),
('+918769718954', 'SID951375353268'),
('+918742858552', 'SSF2573918'),
('+919120732569', 'SID951376147195'),
('+916287011142', 'SSF4782631'),
('+916206979027', 'SSF4782686'),
('+916378869686', 'SSF4622183'),
('+917050907785', 'SSF4744903'),
('+917870072958', 'SSF4647967'),
('+917209013186', 'SSF4560234'),
('+917879612316', 'SSF4616206'),
('+917587261297', 'SSF4723021'),
('+917250994247', 'SSF4965576'),
('+917505880552', 'SSF4782653'),
('+917250239014', 'SSF2736749'),
('+917856045796', 'SSF4753542'),
('+917050804237', 'SSF4783810'),
('+917541861211', 'SSF4726854'),
('+917742796449', 'SSF4134177'),
('+917568974295', 'SSF4212079'),
('+917667419188', 'SSF4634543'),
('+917771940496', 'SSF4574194'),
('+918434538561', 'SSF3059268'),
('+918542973691', 'SSF2576869'),
('+918292037691', 'SSF4728388'),
('+918002087120', 'SSF4519305'),
('+918167323956', 'SSF5052592'),
('+918904772436', 'SSF4725779'),
('+918269127336', 'SSF4657584'),
('+918734858055', 'SSF4738807'),
('+918651324377', 'SSF4579311'),
('+918502049629', 'SSF4345041'),
('+918290146032', 'SSF5059396'),
('+918269588978', 'SSF4844747'),
('+919102870159', 'SSF3552674'),
('+919801762359', 'SSF4732831'),
('+919546332373', 'SSF4560175'),
('+919279180648', 'SSF4248924'),
('+919871956175', 'SSF4764615'),
('+919431965034', 'SSF3049612'),
('+919263555949', 'SSF4458447'),
('+919905125611', 'SSF4604994'),
('+919685310437', 'SSF4594926'),
('+919234231679', 'SSF4717548'),
('+919234789418', 'SSF3009818'),
('+919838722057', 'SSF4795122'),
('+919098983239', 'SSF4464860'),
('+919692430424', 'SSF4082182'),
('+919569992882', 'SSF4556878'),
('+919522653173', 'SSF4844759'),
('+916468686868', 'SID951374549464'),
('+916205552661', 'SSF4483859'),
('+916207558596', 'SID951376087688'),
('+916287105339', 'SSF4547894'),
('+916299765726', 'SSF4021795'),
('+917479989946', 'SID951374855774'),
('+917050143270', 'SSF4860570'),
('+917974767257', 'SSF4564088'),
('+917651864943', 'SSF4099200'),
('+917061989809', 'SSF5274316'),
('+917255923204', 'SSF4640301'),
('+917857923047', 'SSF4347061'),
('+917724916499', 'SSF4639947'),
('+917209126295', 'SSF4733043'),
('+917488271381', 'SSF3087319'),
('+917764090488', 'SSF4312064'),
('+918102417879', 'SSF5322602'),
('+918815980979', 'SSF4616194'),
('+918084897256', 'SSF4591542'),
('+918102948076', 'SSF4635393'),
('+918306552473', 'SSF4313027'),
('+918252475848', 'SSF4545465'),
('+918115827042', 'SSF4527123'),
('+918757163655', 'SSF2490594'),
('+918688605564', 'SSF2490724'),
('+918094531140', 'SSF4499868'),
('+918002543825', 'SSF4567901'),
('+918827344197', 'SSF4546259'),
('+918709673388', 'SID951375267822'),
('+918434610519', 'SSF3999292'),
('+918676823498', 'SSF4130470'),
('+918102411290', 'SSF4618791'),
('+919898965448', 'SSF4381271'),
('+919608918672', 'SSF4831251'),
('+919113351218', 'SSF4597223'),
('+919955435635', 'SSF4841045'),
('+919334840729', 'SSF4127748'),
('+919973273264', 'SSF4547782'),
('+919546369394', 'SSF2976616'),
('+919313970781', 'SSF2512365'),
('+919939464292', 'SSF4566162'),
('+919835216764', 'SSF3372750'),
('+919631753422', 'SSF4428395'),
('+919835000760', 'SSF2970475'),
('+919117309370', 'SSF2865205'),
('+919759757967', 'SID951375054475'),
('+919973635588', 'SID951375193356'),
('+919835033436', 'SSF5333884'),
('+919404782362', 'SID951375287401'),
('+919565234223', 'SSF3184017'),
('+919709011508', 'SSF4603731'),
('+919142237624', 'SSF3238275'),
('+919069714640', 'SSF4626375'),
('+919113117358', 'SSF2957011'),
('+919508021147', 'SID951373848903'),
('+919117474985', 'SSF3512036'),
('+919001454639', 'SSF2491054'),
('+918757432646', 'SSF5412023'),
('+918521562085', 'SSF4451615'),
('+917858960859', 'SSF4062362'),
('+919798591887', 'SSF4114730'),
('+919608615782', 'SSF4222533'),
('+917544808218', 'SSF5752693'),
('+919877960714', 'SSF5778016'),
('+919123256020', 'SSF4703549'),
('+916202251047', 'SSF5728267'),
('+916201398495', 'SSF5731857'),
('+917058954582', 'SSF5730247'),
('+917319714827', 'SSF5999553'),
('+917070638896', 'SSF5518266'),
('+917050475447', 'SSF5710823'),
('+917482812406', 'SSF5717805'),
('+918160563325', 'SSF5478064'),
('+918252741556', 'SSF5585306'),
('+918294894240', 'SSF4327078'),
('+918434451470', 'SSF5586622'),
('+918788165135', 'SSF5723334'),
('+918298207660', 'SSF5724936'),
('+919263363819', 'SSF5678362'),
('+919631695211', 'SSF5920711'),
('+919661338259', 'SSF5578529'),
('+919060932747', 'SSF4284624'),
('+919341283067', 'SSF5325705'),
('+919572586618', 'SSF5736742'),
('+919162753610', 'SSF5624279'),
('+916207485929', 'SSF5453553'),
('+916284405739', 'SSF5562036'),
('+917480896913', 'SSF5585409'),
('+917209723483', 'SSF5719947'),
('+917050263162', 'SSF5632504'),
('+917254043791', 'SSF5721597'),
('+917257902750', 'SSF4976177'),
('+917634007848', 'SSF4196432'),
('+917352659847', 'SSF4509214'),
('+917071305440', 'SSF5338550'),
('+918130696817', 'SSF5727947'),
('+918288086138', 'SSF5733205'),
('+918809442321', 'SSF5449987'),
('+918867458735', 'SSF5750153'),
('+918540865863', 'SSF5453540'),
('+919060237591', 'SSF5484534'),
('+919279431445', 'SSF5720012'),
('+919608470164', 'SSF5453548'),
('+916350580787', 'SSF4764594'),
('+916209613092', 'SSF4015803'),
('+916299094081', 'SSF4157744'),
('+916232976325', 'SSF4081601'),
('+916377343170', 'SSF4047003'),
('+916265789017', 'SSF3390828'),
('+917292815260', 'SSF4018847'),
('+917665915291', 'SSF4100721'),
('+917970532112', 'SSF3982347'),
('+917858984799', 'SSF4679934'),
('+917368089342', 'SSF4064302'),
('+917463844934', 'SSF3906432'),
('+917050688991', 'SSF3975474'),
('+917986829564', 'SSF4643174'),
('+917070260275', 'SSF3959940'),
('+917903486489', 'SSF3959993'),
('+917250376357', 'SSF4394426'),
('+917366995653', 'SSF4067756'),
('+917764809618', 'SSF4067722'),
('+917654012840', 'SSF3670281'),
('+917546941332', 'SSF4048295'),
('+917209055583', 'SSF4125257'),
('+917858040871', 'SID951376098092'),
('+917091961105', 'SSF4513686'),
('+917541033223', 'SSF4053242'),
('+917828487873', 'SSF3981089'),
('+917992247495', 'SSF4260789'),
('+917903528173', 'SSF4522109'),
('+917255006226', 'SSF4159773'),
('+917974398708', 'SSF4065952'),
('+917461996785', 'SID951375766546'),
('+917870192520', 'SSF4141010'),
('+917587743630', 'SSF4168918'),
('+917667736749', 'SSF6338340'),
('+918829845714', 'SSF4389705'),
('+918404079797', 'SID951373802664'),
('+918271359296', 'SSF3984968'),
('+918434904468', 'SSF4232955'),
('+918784584549', 'SID951376220979'),
('+918383987769', 'SSF4051783'),
('+918875308954', 'SSF4051848'),
('+918107347306', 'SSF4144153'),
('+918298738059', 'SSF4078623'),
('+918148106758', 'SSF3935744'),
('+918271383349', 'SSF3994274'),
('+918962117414', 'SSF4016215'),
('+918810511358', 'SSF4159242'),
('+918340743851', 'SSF4141057'),
('+918235975338', 'SSF4118744'),
('+918092490449', 'SSF4016345'),
('+918578984071', 'SSF4016653'),
('+918239958977', 'SSF4035993'),
('+918946885457', 'SSF2543886'),
('+918349235703', 'SSF4081022'),
('+919589886745', 'SSF4011477'),
('+919304564418', 'SSF3950629'),
('+919939861565', 'SSF4186121'),
('+919693439680', 'SSF4191539'),
('+919867394559', 'SID951375648102'),
('+919508832954', 'SSF3310481'),
('+919128825515', 'SSF4191229'),
('+919521545568', 'SSF4068531'),
('+919234764467', 'SSF4493087'),
('+919934585587', 'SID951376006889'),
('+919413641201', 'SSF4489247'),
('+919631619449', 'SSF2392852'),
('+919179159018', 'SSF4094810'),
('+919523437533', 'SSF4051118'),
('+919120484312', 'SSF4039507'),
('+919636454212', 'SSF3862004'),
('+919117671856', 'SSF3958812'),
('+919608556272', 'SSF3910764'),
('+919532107895', 'SID951375375858'),
('+919534003003', 'SSF3911575'),
('+919589349997', 'SSF4654980'),
('+919279323250', 'SSF4490397'),
('+919817164285', 'SSF3848367'),
('+919155489218', 'SSF3591232'),
('+919934401987', 'SSF4482328'),
('+919122935500', 'SSF3998943'),
('+916205192319', 'SSF5058100'),
('+916388133257', 'SSF4070316'),
('+916201068627', 'SSF5309839'),
('+916203247679', 'SSF5737033'),
('+916397193245', 'SSF4568356'),
('+917050437891', 'SSF5058089'),
('+917050927884', 'SSF5024580'),
('+917759829075', 'SSF3948196'),
('+917762082175', 'SSF5033668'),
('+917631985224', 'SSF5828729'),
('+917398295993', 'SSF5633500'),
('+918340468498', 'SSF5094743'),
('+918303798554', 'SSF4811306'),
('+918465901365', 'SSF5733794'),
('+918092034399', 'SSF5033696'),
('+918744018827', 'SSF5605569'),
('+918677052448', 'SSF5376847'),
('+918271984317', 'SSF5732842'),
('+918409673635', 'SSF4749439'),
('+918738823465', 'SSF5052593'),
('+918423408730', 'SSF5533871'),
('+919801620861', 'SSF5153835'),
('+919939945048', 'SSF5058224'),
('+919695604665', 'SSF4435748'),
('+919065014043', 'SSF5687150'),
('+917033310570', 'SSF5853998'),
('+917645021125', 'SSF5642346'),
('+917488167384', 'SSF4618601'),
('+917369074783', 'SSF5476875'),
('+917783070349', 'SSF5550984'),
('+918252595616', 'SSF5651108'),
('+918084124699', 'SSF5753899'),
('+919519924903', 'SSF5606594'),
('+919718161907', 'SSF5854057'),
('+919572594130', 'SSF5506481'),
('+919508355391', 'SSF5550574'),
('+919145956761', 'SSF5437968'),
('+919065380245', 'SSF5306207'),
('+919798073636', 'SSF5552848'),
('+919681267769', 'CID219406567'),
('+917780012077', 'SSF5581154'),
('+918756452724', 'SSF5534377'),
('+919523742373', 'SSF5477321'),
('+916201345721', 'SSF3910459'),
('+916367340975', 'SSF3972124'),
('+916260568446', 'SSF2781217'),
('+916299693548', 'SSF3848521'),
('+916465664646', 'SSF3051615'),
('+916378903144', 'SSF4000231'),
('+916201148414', 'SSF3960356'),
('+916200314295', 'SSF3867395'),
('+916250872481', 'SSF3137853'),
('+917727052869', 'SSF4458562'),
('+917033424421', 'SSF4015346'),
('+917520476704', 'SID951374721765'),
('+917433028209', 'SSF3979356'),
('+917549547004', 'SSF4013173'),
('+917340213249', 'SID951374945142'),
('+917852812761', 'SSF4057639'),
('+917070848174', 'SSF3859053'),
('+917766896519', 'SSF4038100'),
('+917742822768', 'SSF4946378'),
('+917541941230', 'SSF4183158'),
('+917260865466', 'SSF3991985'),
('+917352253956', 'SSF4289912'),
('+917878946617', 'SSF4011899'),
('+917697017029', 'SSF4032043'),
('+917061931157', 'SSF3880251'),
('+917667959830', 'SSF3925108'),
('+918271350872', 'SID951373194481'),
('+918302101956', 'SSF3974044'),
('+918252802647', 'SSF3214885'),
('+918107530813', 'SSF3898045'),
('+918757667181', 'SSF4222652'),
('+918252338741', 'SSF3910434'),
('+918002318580', 'SSF3928662'),
('+918969651028', 'SSF2703774'),
('+918305254298', 'SSF4056818'),
('+918115495507', 'SSF3347230'),
('+918049857543', 'SSF3751956'),
('+918107506533', 'SSF4054064'),
('+918446381217', 'SSF3832980'),
('+918969836036', 'SSF2753457'),
('+918797754859', 'SSF4120555'),
('+918969307518', 'SID951375639178'),
('+918960340349', 'SSF3337745'),
('+918824324743', 'SSF3976211'),
('+919905915082', 'SSF3888544'),
('+919764846461', 'SSF3875634'),
('+919024719558', 'SSF3972257'),
('+919135428962', 'SSF4117174'),
('+919509558872', 'SSF4024264'),
('+919142960761', 'SSF4013161'),
('+919784843647', 'SSF4088976'),
('+919001861639', 'SSF4071438'),
('+919279704045', 'SSF4207629'),
('+919385394378', 'SSF3746479'),
('+919686433024', 'SSF4378430'),
('+919065744989', 'SSF3867032'),
('+919506662736', 'SSF3874199'),
('+919939825893', 'SSF3618664'),
('+919636589632', 'SSF3900521'),
('+919929521809', 'SSF4016490'),
('+919934697700', 'SSF3884062'),
('+919565047850', 'SSF3295659'),
('+919649840825', 'SSF3960642'),
('+919571677046', 'SID951375847323'),
('+919233249803', 'SSF4021372'),
('+919494372725', 'SID951375720622'),
('+919931602510', 'SSF3911183'),
('+916201073317', 'SSF5507650'),
('+917646027112', 'SSF5642495'),
('+918298808184', 'SSF5585178'),
('+919369887242', 'SSF5652187'),
('+919065500601', 'SSF4851589'),
('+917895827961', 'SSF5586554'),
('+918318046660', 'SSF3956494'),
('+919919163471', 'SSF5330066'),
('+919153450590', 'SSF5497618'),
('+919199754719', 'SSF5563733'),
('+919695689487', 'SSF3559724'),
('+917089466499', 'SSF3593591'),
('+919562394916', 'SSF3805259'),
('+919671112179', 'SSF3592095'),
('+919142271409', 'SSF2574285'),
('+916388547906', 'SSF4801279'),
('+918650209257', 'SSF5233309'),
('+918709882249', 'SSF5637757'),
('+919936183146', 'SSF5568136'),
('+916266717285', 'SSF3664441'),
('+916987878787', 'SSF3676516'),
('+916287978704', 'SSF3392008'),
('+916377946564', 'SID951375982237'),
('+916367382543', 'SSF3697634'),
('+916766467979', 'SSF3405099'),
('+916346434946', 'SSF2660123'),
('+917974231458', 'SSF3753147'),
('+917845164646', 'SSF3848532'),
('+917354663324', 'CID951376201717'),
('+917461934394', 'SSF4126389'),
('+917295948853', 'SSF3759013'),
('+917292892644', 'SSF3759514'),
('+917634864892', 'SSF3539204'),
('+917250279852', 'SSF3426640'),
('+917008542887', 'SSF3629885'),
('+917067235808', 'SSF3613604'),
('+918541973470', 'SSF3331345'),
('+918434229775', 'SSF3614548'),
('+918764949797', 'SSF2614025'),
('+918997186298', 'SSF3384992'),
('+918056464484', 'SSF3576308'),
('+918955915392', 'SSF3581112'),
('+918460435073', 'SSF3697035'),
('+918548497878', 'SID951375979587'),
('+918769634949', 'SSF3715538'),
('+918252750855', 'SSF3281111'),
('+918758249734', 'SSF3319418'),
('+918552596381', 'SSF3550760'),
('+918542615794', 'SSF3499836'),
('+918529513063', 'SSF3919116'),
('+918455558865', 'SSF3398652'),
('+918079984313', 'SSF3788988'),
('+918789737948', 'SSF3759031'),
('+918855560559', 'SID951375725794'),
('+918890807895', 'SID951375195998'),
('+918468588668', 'SSF3488876'),
('+919532223381', 'SSF3646102'),
('+919766794997', 'SSF3346755'),
('+919737484540', 'SSF3577885'),
('+919303278813', 'SSF3675014'),
('+919767649649', 'SSF3453700'),
('+919737946763', 'SSF3450137'),
('+919905494723', 'SSF3265254'),
('+919324697684', 'SSF3449924'),
('+919523367153', 'SSF3265310'),
('+919631230850', 'SID951376047884'),
('+919427549757', 'SSF3424763'),
('+919950248080', 'SSF3403782'),
('+919658567965', 'SSF3673646'),
('+919464649484', 'SSF3724366'),
('+919685665646', 'SSF3465274'),
('+919983804697', 'SSF3467562'),
('+919982442458', 'SSF3716869'),
('+919679494649', 'SSF3658551'),
('+919695596912', 'SSF3791168'),
('+919632514555', 'SSF3405590'),
('+919856345193', 'SSF3761987'),
('+919764648848', 'SSF3396050'),
('+919799484646', 'SSF3420001'),
('+919854913494', 'SSF3738792'),
('+919079151073', 'SID951375451196'),
('+919854319243', 'SSF3752760'),
('+919664637646', 'SSF3609763'),
('+919494646496', 'SSF3356320'),
('+916464548484', 'SID951376151353'),
('+916253106542', 'SSF3178553'),
('+916377300089', 'SSF2562968'),
('+917317837764', 'SSF3119746'),
('+918319656342', 'SSF3019992'),
('+918885757572', 'SID951375917144'),
('+918798693620', 'SSF3327718'),
('+918529891524', 'SSF3227258'),
('+918852211855', 'SSF3171223'),
('+918077906536', 'SSF3453995'),
('+919645039459', 'SSF3467260'),
('+919303869680', 'SSF3423983'),
('+919668423885', 'SID951375523348'),
('+919876543216', 'SSF3280508'),
('+919965888888', 'SSF2630789'),
('+919915185757', 'SSF3708984'),
('+919263314822', 'SSF3259359'),
('+919675243458', 'SSF3210570'),
('+919648452137', 'SSF3210572'),
('+919285572718', 'SSF2658888'),
('+919546932652', 'SSF3204917'),
('+919856858658', 'SSF3227507'),
('+919399987421', 'SSF3507686'),
('+919693031873', 'SSF3274389'),
('+919797668669', 'SSF3270208'),
('+919648549675', 'SSF3067439'),
('+919279491047', 'SSF4165901'),
('+919660049636', 'SSF2757963'),
('+919065292911', 'SSF3477541'),
('+919110165035', 'SSF3440300'),
('+917896453128', 'SSF2976339'),
('+917481817359', 'SID951374638852'),
('+918239115921', 'SSF3460578'),
('+918919573969', 'SSF3334153'),
('+918340546153', 'SSF3307555'),
('+918107958888', 'SSF3151058'),
('+918815257532', 'SSF3244638'),
('+919343996814', 'SID951374431256'),
('+919685479481', 'SSF3032722'),
('+919572039175', 'SSF3099146'),
('+919692263688', 'SSF3115473'),
('+919929310943', 'SSF3062791'),
('+919331142758', 'SID951375882496'),
('+919685487548', 'SSF3110630'),
('+919494818454', 'SSF2991926'),
('+919155481816', 'SSF5823746'),
('+919241410078', 'SSF5854368'),
('+919313377748', 'SSF4992443'),
('+917985543699', 'SSF3741230'),
('+918440910149', 'SSF3439642'),
('+919575840526', 'SSF3125745'),
('+919887564313', 'SSF3768989'),
('+919462921726', 'SSF3119541'),
('+919813457414', 'SSF3236777'),
('+919752923741', 'SSF3675901'),
('+919350570051', 'SSF3100756'),
('+919653687664', 'SSF3314507'),
('+917667100350', 'SSF5586101'),
('+918969933152', 'SSF5276210'),
('+919798429711', 'SSF5610740'),
('+917209700258', 'SSF5151832'),
('+918797996715', 'SSF5088594'),
('+919027268129', 'SSF4557102'),
('+919721724273', 'SSF5341418'),
('+917857828717', 'SSF5527513'),
('+919958592053', 'SSF5712005'),
('+916287208581', 'SSF5082764'),
('+918888555688', 'SSF3111894'),
('+919568431245', 'SID951374750586'),
('+918000976231', 'SID951374313035'),
('+916203530628', 'SSF4764756'),
('+917371968794', 'SSF4774109'),
('+917091162946', 'SSF4560213'),
('+917632885576', 'SSF2973160'),
('+917643900318', 'SSF4787487'),
('+917856850129', 'SSF3074948'),
('+917023565277', 'SSF4833505'),
('+917389037034', 'SSF4916430'),
('+918817966077', 'SSF4830825'),
('+918294045354', 'SSF5022665'),
('+918294309889', 'SSF5624924'),
('+919306993186', 'SSF3898103'),
('+919279551401', 'SSF4753659'),
('+919131944546', 'SSF4646384'),
('+919110160586', 'SSF4729003'),
('+919131758201', 'SSF3007896'),
('+916287254006', 'SSF4561036'),
('+916204796791', 'SSF4189814'),
('+916006436601', 'SSF3631792'),
('+916287056940', 'SSF4592879'),
('+916204744730', 'SSF4404113'),
('+917015422915', 'SSF4397313'),
('+917548899460', 'SSF4530554'),
('+917367834764', 'SSF4415617'),
('+917033750596', 'SSF2763016'),
('+917033679626', 'SID951373756721'),
('+917347358112', 'SSF4470293'),
('+917033686356', 'SSF4585977'),
('+917091592292', 'SSF3224559'),
('+917024792229', 'SSF4615399'),
('+917482810347', 'SSF4864204'),
('+917250560639', 'SSF4389166'),
('+917764934758', 'SSF4128468'),
('+918809703310', 'SSF4561273'),
('+918521647245', 'SSF3805595'),
('+918602895610', 'SSF4338730'),
('+918873098141', 'SSF4470352'),
('+918252371138', 'SSF4347186'),
('+918603553199', 'SSF4569049'),
('+918210027991', 'SSF4581009'),
('+918804552061', 'SSF4530446'),
('+918176951020', 'SSF3141496'),
('+919369340573', 'SSF4489399'),
('+919098501323', 'SSF4100267'),
('+919142372432', 'SSF4799714'),
('+919056903393', 'SSF4364885'),
('+919304423636', 'SSF5860939'),
('+919343224220', 'SSF3728383'),
('+919153790523', 'SSF4871912'),
('+919519884899', 'SSF4168613'),
('+919905569088', 'SSF4410656'),
('+919334391855', 'SSF4339348'),
('+918603780992', 'SSF5781267'),
('+916232487374', 'SSF4099887'),
('+917722076541', 'SSF2304021'),
('+917546958794', 'SID951373006852'),
('+918629963170', 'SSF4240478'),
('+916390552821', 'SSF5502018'),
('+917764096480', 'SSF5272545'),
('+917633977367', 'SSF5551883'),
('+917523074432', 'SSF5925883'),
('+918269820234', 'SSF5324936'),
('+916204526920', 'SSF5772386'),
('+917481957944', 'SSF5703482'),
('+917696220955', 'SSF5682777'),
('+917349907964', 'SSF5653802'),
('+917290875589', 'SSF5171614'),
('+917387550502', 'SSF5362996'),
('+918709307405', 'SSF5784702'),
('+918340332876', 'SSF5146716'),
('+918092958347', 'SSF5124044'),
('+918092776843', 'SSF5209907'),
('+918210385853', 'SSF5775526'),
('+918235908399', 'SSF5367614'),
('+919797806258', 'SSF5815921'),
('+919651801091', 'SSF5152247'),
('+919625887835', 'SSF5928947'),
('+919771577384', 'SSF5772366'),
('+919905376867', 'SSF5784698'),
('+919546403385', 'SSF5410170'),
('+917004535160', 'SSF5352880'),
('+917631549572', 'SSF5834172'),
('+917759889682', 'SSF5588010'),
('+918873304509', 'SSF5498136'),
('+918340208199', 'SSF5839665'),
('+918603466350', 'SSF5746566'),
('+919798614892', 'SSF5398686'),
('+919279280563', 'SSF5921684'),
('+919570961986', 'SSF5766985'),
('+919155379731', 'SSF4973641'),
('+919031704457', 'SSF5979981'),
('+919199315828', 'SSF5449927'),
('+916299211612', 'SSF4026679'),
('+916287154704', 'SSF4862655'),
('+916268878636', 'SSF4045401'),
('+916204895931', 'SSF4599442'),
('+917580845665', 'SSF4050992'),
('+917643815195', 'SSF4039327'),
('+917250060974', 'SSF3000488'),
('+917294959476', 'SSF4139633'),
('+917257838375', 'SSF3249128'),
('+917369084463', 'SSF4142533'),
('+917070126131', 'SSF3999224'),
('+917426938269', 'SSF3974929'),
('+917228085214', 'SSF3926291'),
('+917050589756', 'SSF4002564'),
('+917665634134', 'SSF4042739'),
('+917654364121', 'SSF3910773'),
('+917828325897', 'SSF2928606'),
('+917321034516', 'SSF4001200'),
('+917354983608', 'SSF4070371'),
('+918102546690', 'SSF4530491'),
('+918603155515', 'SSF4139604'),
('+918852845169', 'SSF4028541'),
('+918815956817', 'SSF4067263'),
('+918340375541', 'SSF2618022'),
('+918854545258', 'SID951376098426'),
('+918696730088', 'SSF3642646'),
('+918529089248', 'SSF4400738'),
('+918789447975', 'SSF4007363'),
('+918488448840', 'SSF2374920'),
('+918709445855', 'SSF4273017'),
('+918957088427', 'SSF4155667'),
('+918459154927', 'SID951376154372'),
('+918114589439', 'SSF3795008'),
('+918388925383', 'SSF4530657'),
('+918271769750', 'SSF2920522'),
('+918757363903', 'SID951373984118'),
('+918103206941', 'SSF4081535'),
('+918603207059', 'SSF4680293'),
('+918987956286', 'SSF3122595'),
('+918863865745', 'SID951374142027'),
('+919352778161', 'SSF4080329'),
('+919967579867', 'SSF3844704'),
('+919960683315', 'SSF4217008'),
('+919131591939', 'SSF3980466'),
('+919915820705', 'SID951375904198'),
('+919153778243', 'SSF4012376'),
('+919399324486', 'SSF4296539'),
('+919608771723', 'SSF5274150'),
('+919546021061', 'SSF4896887'),
('+919470207842', 'SSF4027708'),
('+919752364379', 'SSF4017769'),
('+919798580488', 'SID951376131197'),
('+919244062115', 'SSF3027264'),
('+919006343312', 'SSF3912245'),
('+919117266156', 'SSF4402478'),
('+919060226676', 'SSF3214488'),
('+919693071887', 'SSF4039009'),
('+919060994965', 'SSF4001041'),
('+919162341724', 'SSF4156910'),
('+917563859584', 'SSF5876643'),
('+917739617480', 'SSF5685616'),
('+918104585543', 'SSF4075041'),
('+919336835343', 'SSF5650173'),
('+919973967058', 'SSF5529656'),
('+916230524554', 'SSF4213200'),
('+917480948692', 'SSF5658480'),
('+917042432812', 'SSF5077617'),
('+917394860609', 'SSF4757654'),
('+917522055671', 'SSF5532657'),
('+918521380342', 'SSF4812934'),
('+916263649775', 'SSF3980051'),
('+916375043661', 'SSF3942912'),
('+916201039303', 'SSF3881462'),
('+916376242056', 'SID951375926555'),
('+916424554848', 'SID951376155941'),
('+917858086791', 'SSF4409320'),
('+917073304635', 'SSF3951129'),
('+917081563931', 'SSF4422292'),
('+917849811742', 'SSF3907461'),
('+917887404612', 'SSF3978014'),
('+917297060629', 'SSF3376229'),
('+917256952378', 'SSF3875943'),
('+917367902623', 'SSF4494604'),
('+917845623168', 'SSF2797925'),
('+917764850712', 'SSF4416501'),
('+917425871923', 'SSF3908021'),
('+917783023075', 'SSF4287251'),
('+917483577937', 'SSF2997811'),
('+917023042658', 'SSF3780394'),
('+918829098541', 'SSF3961889'),
('+918690311623', 'SSF3990696'),
('+918302430941', 'SSF3970440'),
('+918094743596', 'SSF4024213'),
('+918809008281', 'SSF4522576'),
('+918863049397', 'SSF2319899'),
('+918931249752', 'SSF3581537'),
('+918794615651', 'SID951375209329'),
('+918696773454', 'SSF3241853'),
('+918128407731', 'SSF3906624'),
('+918538889688', 'SSF2289134'),
('+918539977030', 'SSF3992136'),
('+918409632330', 'SSF4001144'),
('+918646056889', 'SSF2567248'),
('+918770344014', 'SSF4068542'),
('+918235598701', 'SSF4239654'),
('+918000932087', 'SSF3990437'),
('+919303707585', 'SSF3178597'),
('+919006760461', 'SSF3959887'),
('+919798738272', 'SSF3814911'),
('+919608359563', 'SSF4356155'),
('+919327264810', 'SSF3890404'),
('+919635865779', 'SSF3782565'),
('+919511394891', 'SSF2893012'),
('+919329195697', 'SSF4054718'),
('+919799512145', 'SSF4187390'),
('+919341916278', 'SSF4529637'),
('+919948767979', 'SID951374248493'),
('+919113466694', 'SSF3842496'),
('+919752926782', 'SSF4049961'),
('+919001611562', 'SSF3902856'),
('+919950368849', 'SSF2627618'),
('+919304559007', 'SSF3972659'),
('+919351299619', 'SSF3888625'),
('+919828562314', 'SSF3904925'),
('+919693923835', 'SSF4494481'),
('+917400394653', 'SSF5644001'),
('+917007439056', 'SSF5641791'),
('+918000287309', 'SSF5478904'),
('+917763946940', 'SSF5720348'),
('+917070665990', 'SSF4974788'),
('+918092290360', 'SSF4015224'),
('+919368863651', 'SSF5586611'),
('+919693190195', 'SSF5386362'),
('+919651199691', 'SSF5470803'),
('+916204963101', 'SSF5591384'),
('+917070575877', 'SSF5537167'),
('+919696856574', 'SSF5500191'),
('+917292812885', 'SSF2289129'),
('+919584572431', 'SSF3660101'),
('+919664465207', 'SSF3660150'),
('+919452368596', 'SSF3792862'),
('+919536625536', 'SSF3791086'),
('+919329827056', 'SSF3837863'),
('+919719040649', 'SSF5233238'),
('+919161218410', 'SSF5658731'),
('+917370062053', 'SSF4828473'),
('+917705889640', 'SSF5304426'),
('+918953273680', 'SSF5525979'),
('+918173045816', 'SSF4227112'),
('+918920269749', 'SSF5328595'),
('+919709801638', 'SSF5634178'),
('+919801376711', 'SSF5318056'),
('+916202310682', 'SSF3404620'),
('+916885754245', 'SSF3567828'),
('+916266750721', 'SSF3681846'),
('+916284559199', 'SSF2386088'),
('+917728021804', 'SSF3367283'),
('+917766825942', 'SID951376013040'),
('+917739826287', 'SSF3452832'),
('+917568241231', 'SSF3324088'),
('+917295888947', 'SSF3505369'),
('+917357203168', 'SSF3487818'),
('+917050694012', 'SID951373456036'),
('+917091661780', 'SSF3649698'),
('+917984594649', 'SSF3644822'),
('+917804643418', 'SSF3637726'),
('+917673438664', 'SSF3337205'),
('+917737315629', 'SSF2491014'),
('+918521968875', 'SSF3380441'),
('+918875286664', 'SSF3746149'),
('+918956527474', 'SSF3357161'),
('+918816083800', 'SID951376084576'),
('+918568745555', 'SSF3457622'),
('+918046494076', 'SSF3700565'),
('+918690233535', 'SSF3748094'),
('+918542446724', 'SSF3632356'),
('+918422469166', 'SSF3565058'),
('+919216864405', 'SSF3822347'),
('+919983421962', 'SSF3775499'),
('+919635855738', 'SSF3429860'),
('+919341076233', 'SSF3692016'),
('+919509476379', 'SSF3462738'),
('+919931916942', 'SSF3608856'),
('+919486754548', 'SSF3373141'),
('+919650824883', 'SSF3744160'),
('+919355648865', 'SSF3407038'),
('+919549059120', 'SSF3489720'),
('+919379898985', 'SSF3499338'),
('+919434215482', 'SSF3489058'),
('+919608310437', 'SSF3310519'),
('+919162867613', 'SSF3369156'),
('+919743167316', 'SSF3779287'),
('+919905016013', 'SSF3914270'),
('+919618349244', 'SSF3480818'),
('+916206403165', 'SSF3951294'),
('+916724516542', 'SSF3385685'),
('+916299304077', 'SSF2996692'),
('+916468346673', 'SSF3205550'),
('+916210546407', 'SSF3283454'),
('+917250261035', 'SSF3426352'),
('+917739568825', 'SSF3419822'),
('+917891125331', 'SSF3170107'),
('+917568241397', 'SID951375948287'),
('+917067456790', 'SSF3511917'),
('+917568695950', 'SSF3369358'),
('+917742854978', 'SSF3630610'),
('+918552412111', 'SSF3433989'),
('+918602829946', 'SSF3209487'),
('+918452012129', 'SSF3470897'),
('+918825453633', 'SSF3371499'),
('+918809294787', 'SSF2665906'),
('+918261054825', 'SSF3833374'),
('+919610124429', 'SSF2681600'),
('+919509669936', 'SSF3396916'),
('+919799267788', 'SSF3078242'),
('+919914385558', 'SSF3284657'),
('+919335574925', 'SSF3209427'),
('+919399838578', 'SSF3309039'),
('+919358544487', 'SSF3307340'),
('+919857846449', 'SSF3436150'),
('+919767649464', 'SSF3235328'),
('+919636065730', 'SSF3263171'),
('+919655765354', 'SSF3475434'),
('+919279696765', 'SSF3433393'),
('+916367670563', 'SSF3304383'),
('+916886677756', 'SSF2991925'),
('+918770530917', 'SSF3236949'),
('+918809421201', 'SSF3274390'),
('+918079154634', 'SSF3110257'),
('+919766890686', 'SSF3302671'),
('+919798544759', 'SSF3089187'),
('+919631221515', 'SID951375882464'),
('+919494676794', 'SSF2983194'),
('+919005227578', 'SSF4768433'),
('+917294967711', 'SSF5763042'),
('+918946376734', 'SSF2971286'),
('+918815525629', 'SSF3162695'),
('+918079676494', 'SSF3638703'),
('+919885434646', 'SSF3016562'),
('+918340726270', 'SSF5364365'),
('+918340240095', 'SSF5586264'),
('+919835374291', 'SSF5360355'),
('+919341340685', 'SSF5586326'),
('+918603051371', 'SSF5180055'),
('+919761880832', 'SSF5889592'),
('+917206594512', 'SSF2899032'),
('+919929685488', 'SSF2525358'),
('+919005076492', 'SSF4889961'),
('+919958877858', 'SSF2891717'),
('+919691122790', 'SSF2425290'),
('+919006783221', 'SSF3262510'),
('+919955154627', 'SSF5417378'),
('+917748839962', 'SSF3434420'),
('+918487643705', 'SSF3592096'),
('+919794404785', 'SSF3973110'),
('+917067318575', 'SID951375355813'),
('+918051413948', 'SSF3477194'),
('+917667811528', 'SSF2460326'),
('+918400991094', 'SSF2601852'),
('+916564989494', 'SSF3137059'),
('+916268127234', 'SID951375042726'),
('+919399451507', 'SSF4183057'),
('+919340169594', 'SID951375402649'),
('+919867595884', 'SID951374724985'),
('+919102823908', 'SSF5413256'),
('+919693315022', 'SSF6393076'),
('+918690541538', 'SSF2439728'),
('+918717919411', 'SSF4589173'),
('+917869007169', 'SID951373259174'),
('+919279182287', 'SSF3976542'),
('+918928470865', 'SID951373667222'),
('+919406346321', 'SID951374922507'),
('+919001107138', 'SID951374971925'),
('+919508293587', 'SID951375827762'),
('+918955314634', 'SSF4578628'),
('+917280868977', 'SSF4158602'),
('+916393240182', 'SSF6382972'),
('+919878976453', 'SSF2437797'),
('+919199627995', 'SSF5479722'),
('+917542878126', 'SSF2322128'),
('+917828606910', 'SID951375992782'),
('+919771222647', 'SSF6248732'),
('+919521883430', 'SSF4137857'),
('+916287975600', 'SSF6013488'),
('+916260146784', 'SSF3224390'),
('+919161540554', 'SSF6168143'),
('+919305165717', 'SSF6312434'),
('+917380542881', 'SSF5358873'),
('+919771262936', 'SSF3809231'),
('+917081118085', 'SSF3801754'),
('+919764946488', 'SSF3591600'),
('+919216948859', 'SSF4080255'),
('+919522276008', 'SSF4249799'),
('+919026417983', 'SSF5942021'),
('+917828131035', 'CID040308474'),
('+916266084117', 'SSF3280572'),
('+919244206154', 'SSF4479244'),
('+917610300248', 'SSF2766563'),
('+919361531835', 'SID951375883269'),
('+918882839662', 'SSF6553920'),
('+916266172276', 'SSF3783881'),
('+916266231029', 'SSF3380822'),
('+919471500274', 'CID212402865'),
('+919672920970', 'SSF6071399'),
('+917480958092', 'SSF3430944'),
('+917340207776', 'SSF4019075'),
('+919699079822', 'SSF5909243'),
('+918889692520', 'SSF4238772'),
('+917413982654', 'SSF2879458'),
('+918862969102', 'SSF6366652'),
('+917070312616', 'SSF5543736'),
('+917079081616', 'SSF2748618'),
('+919625250600', 'SSF4713457'),
('+919340570975', 'SSF3560267'),
('+918434809849', 'SID951374906036'),
('+918837638064', 'SSF2628130'),
('+916265262560', 'SID951373905246'),
('+918890383069', 'SSF3610504'),
('+919644090401', 'SID951374431551'),
('+918461842783', 'CID084403015'),
('+919162097843', 'SSF5618083'),
('+919979029767', 'SSF4786582'),
('+917724974534', 'SID951374290357'),
('+918709583170', 'SSF2930883'),
('+918081418470', 'SSF3446658'),
('+919122369238', 'CID204504910'),
('+916386919112', 'SSF2694873'),
('+919633682793', 'SSF3077793'),
('+917869894352', 'SSF4206747'),
('+917047726048', 'SSF2646540'),
('+919109844501', 'SSF3535924'),
('+919580230971', 'SSF5646258'),
('+917723903124', 'SSF2982900'),
('+917697985183', 'SID951373351640'),
('+918269100808', 'SID951373388254'),
('+918434509378', 'SSF4709921'),
('+919352367417', 'SSF6138911'),
('+916268012113', 'SSF5879949'),
('+918924893274', 'SSF3542909'),
('+919057514200', 'SSF3885465'),
('+917070658582', 'SID951374771357'),
('+917878631398', 'SID951375944781'),
('+917250188652', 'SID951375840672'),
('+917879563840', 'CID204901757'),
('+919399072037', 'SSF5402189'),
('+918644335555', 'SSF3291976'),
('+918306496910', 'SID951374863249'),
('+919949302490', 'SID951375929155'),
('+918305455292', 'SID2125528453'),
('+919335750833', 'SSF6027113'),
('+918092609723', 'SSF6018078'),
('+917509180846', 'SID951373011267'),
('+919955681729', 'SSF4870915'),
('+917870261247', 'SSF5754722'),
('+918806296418', 'SSF3986661'),
('+918619884204', 'SSF2587009'),
('+918429546802', 'SSF3018269'),
('+917541053897', 'SID951374238529'),
('+918003343697', 'SSF4012420'),
('+917380941418', 'SSF4863129'),
('+919693553864', 'SSF6146715'),
('+919993268657', 'SID951375444418'),
('+916260132542', 'SSF2964672'),
('+917980492730', 'SID951375289369'),
('+916260293584', 'SSF3414492'),
('+916232175004', 'SID951374901884'),
('+919835481413', 'SSF6050055'),
('+917542945736', 'SID951375698718'),
('+919955532333', 'SSF5263628'),
('+919256976645', 'SSF4149169'),
('+919621170221', 'SSF5248408'),
('+917073859610', 'SSF2781872'),
('+919548365156', 'SSF5370620'),
('+916267208736', 'SSF2650436'),
('+916299437288', 'SID951374621950'),
('+918878286532', 'SID951376176397'),
('+919658754589', 'SID951375460595'),
('+917080026987', 'SSF5735334'),
('+918252324812', 'SID951374452491'),
('+917492949129', 'SSF4982913'),
('+918375982038', 'SSF3707882'),
('+919305870805', 'CID135104322'),
('+918084410616', 'SSF2778771'),
('+917206848631', 'SSF6177821'),
('+919007553280', 'SSF3748476'),
('+918294093263', 'SSF5824148'),
('+918539919782', 'SSF5795227'),
('+918384044409', 'SSF3065138'),
('+917879674990', 'SSF3508021'),
('+919926820853', 'SSF3488943'),
('+919504210405', 'SSF6391336'),
('+918809736751', 'SSF3905869'),
('+919586547556', 'SSF2914476'),
('+919571037080', 'SID951375799197'),
('+919835263478', 'SID951375190692'),
('+918464646858', 'SSF2555518'),
('+919871223394', 'SSF5820669'),
('+918770670013', 'SSF4288975'),
('+919546569153', 'SID951375510275'),
('+917046824454', 'SSF3477604'),
('+918233507977', 'SSF3283034'),
('+918003759416', 'SSF3794443'),
('+919636818640', 'SSF2559021'),
('+919263952220', 'SSF6172905'),
('+918084670271', 'SSF3035557'),
('+918085057733', 'SID951373104334'),
('+916202104313', 'SSF3201367'),
('+918936064855', 'SSF5627260'),
('+919304456295', 'SSF4210456'),
('+919793322834', 'SID951375109487'),
('+917260055815', 'SSF5273338'),
('+919523699541', 'SSF5359182'),
('+918674817695', 'SID2125012292'),
('+917489361955', 'SID951373773441'),
('+918963959397', 'SID951373284981'),
('+918349207613', 'SID951373757717'),
('+918303377266', 'SSF5980262'),
('+917261214002', 'SID951373340975'),
('+916266239042', 'SSF5558090'),
('+919570378402', 'SSF6306318'),
('+918354800634', 'SSF6120442'),
('+916397669461', 'SSF5330837'),
('+918160910534', 'SID951374983329'),
('+918002782597', 'SSF3498931'),
('+919523525915', 'SSF2925732'),
('+919771640316', 'SSF2903289'),
('+918605257266', 'SSF4925371'),
('+916367420811', 'SSF3177325'),
('+917049064608', 'SID951375096232'),
('+919262637392', 'SSF5458917'),
('+919919210459', 'SSF3809127'),
('+919693403490', 'SSF2532339'),
('+918262040410', 'SID951374893228'),
('+916684266425', 'SSF2300366'),
('+917877532517', 'SID951374752404'),
('+917378272766', 'SSF4919269'),
('+917879407791', 'CID129412679'),
('+918269483640', 'SSF2562204'),
('+918651100598', 'SSF2797831'),
('+917319988095', 'SSF6038652'),
('+918540806217', 'SID951376095212'),
('+916201489655', 'SSF5151619'),
('+917870159061', 'SSF5176750'),
('+917542895185', 'SSF4881742'),
('+917362076954', 'SSF5271487'),
('+917033961850', 'SSF5187908'),
('+917808703650', 'SSF3307504'),
('+918521626840', 'SSF5204229'),
('+918603813345', 'SSF5261898'),
('+919023239824', 'SSF3304304'),
('+919589987591', 'SSF5455357'),
('+919516933901', 'CID204603660'),
('+919301615805', 'SSF3614386'),
('+919234251905', 'SSF2569595'),
('+919608495078', 'SSF4786421'),
('+916390401296', 'SSF5801301'),
('+919905952944', 'SSF6002959'),
('+919041489603', 'SSF5409193'),
('+918102418443', 'SSF5607409'),
('+918600252384', 'SSF5641150'),
('+918668513782', 'SSF4959699'),
('+919262289562', 'SSF5450004'),
('+919810786135', 'SSF5211869'),
('+917307794898', 'SID951373749949'),
('+916797890989', 'SID951375176252'),
('+919669756217', 'SID951373172547'),
('+919484840104', 'SID951374457568'),
('+917761906421', 'SSF5675972'),
('+917355344996', 'SSF5737757'),
('+918840742881', 'SSF5807325'),
('+919122011403', 'SSF5374743'),
('+916200708014', 'SSF4851492'),
('+916302370542', 'SSF4477559'),
('+916202477104', 'SSF4746047'),
('+916299214257', 'SSF4871607'),
('+917447082318', 'SSF2547114'),
('+917667067933', 'SSF5104416'),
('+917367847412', 'SSF5032153'),
('+917600533128', 'SSF4489507'),
('+917292975317', 'SSF2894591'),
('+917870762585', 'SSF5081688'),
('+917004741526', 'SSF4627868'),
('+917489080814', 'SSF5320380'),
('+917395010638', 'SSF4927891'),
('+917759967181', 'SSF3096382'),
('+917970947477', 'SSF4381791'),
('+917480942099', 'SSF4851606'),
('+917480893116', 'SSF3193171'),
('+917549586793', 'SSF3627215'),
('+917635066599', 'SSF4860875'),
('+918271938228', 'SSF4936897'),
('+918757176288', 'SSF4976017'),
('+918824266019', 'SSF4599964'),
('+918789940173', 'SSF4941160'),
('+918824602677', 'SSF3110967'),
('+918709904568', 'SSF4865697'),
('+918595543474', 'SSF4981592'),
('+918986895226', 'SSF4865180'),
('+918871470605', 'SSF4637314'),
('+918539054211', 'SSF2795223'),
('+918103704596', 'SSF4667785'),
('+918521017256', 'SSF4466391'),
('+918757092060', 'SSF4716656'),
('+918540841329', 'SSF5064429'),
('+918966028141', 'SID951372883541'),
('+918640057201', 'SSF3016538'),
('+918815123125', 'SSF4934130'),
('+918959226679', 'SSF3505804'),
('+919234547156', 'SSF4984602'),
('+919835854023', 'SSF4978339'),
('+919024436466', 'SSF4618138'),
('+919931479945', 'SSF4599946'),
('+919955889887', 'SSF4808236'),
('+919588203886', 'SSF4969891'),
('+919279877275', 'SID951375569972'),
('+919554927192', 'SSF4560128'),
('+919001512622', 'SSF4976163'),
('+919131339753', 'SSF5021191'),
('+919234920862', 'SSF4962180'),
('+919546730669', 'SSF4961396'),
('+919770446201', 'SSF2477020'),
('+919508173811', 'SSF4693386'),
('+919241363798', 'SSF5053559'),
('+919171535589', 'SSF5076085'),
('+919905731160', 'SSF5062223'),
('+919608061052', 'SSF5062018'),
('+919771050643', 'SSF4873913'),
('+919588585187', 'SSF5056813'),
('+919229046134', 'SSF5569209'),
('+919241067026', 'SSF4854619'),
('+919034438057', 'SSF4795940'),
('+919835468315', 'SSF3116338'),
('+919162986204', 'SSF4975014'),
('+919155837931', 'SSF3224143'),
('+919165971206', 'SSF4940697'),
('+919631640007', 'SSF4984090'),
('+919509746595', 'SSF3556249'),
('+919838869280', 'SSF5007767'),
('+919399731899', 'SSF5079940'),
('+919430578420', 'SSF5402670'),
('+919412646749', 'SSF5233408'),
('+918292616361', 'CID171506208'),
('+918409281063', 'CID211204641'),
('+918051782484', 'SSF5398107'),
('+916201563258', 'SID951374555736'),
('+917488027981', 'SSF3422640'),
('+917870866472', 'SSF4841688'),
('+917013231121', 'SSF4732647'),
('+917987173050', 'SSF4841617'),
('+917870491664', 'SSF3081100'),
('+917782818744', 'SSF4699906'),
('+917070485313', 'SSF4785634'),
('+917992371354', 'SSF4726407'),
('+917520760849', 'SSF4869896'),
('+917024056617', 'SSF2889955'),
('+917856088375', 'SSF4844283'),
('+918092437543', 'SID951375715783'),
('+918709323548', 'SSF4711456'),
('+918168085407', 'SSF4843852'),
('+918008918347', 'SSF4747771'),
('+918302512242', 'SSF4443093'),
('+918927930988', 'SSF3499323'),
('+918696856441', 'SSF2950432'),
('+919142930480', 'SSF4514998'),
('+919905184153', 'SID951374792866'),
('+919801976528', 'SSF4865452'),
('+919572676689', 'SSF4786711'),
('+919725981427', 'SSF5976070'),
('+919142366873', 'SSF4787142'),
('+919462027344', 'SSF4203920'),
('+919835542554', 'SID951374595033'),
('+919931767957', 'SSF4768547'),
('+919262247418', 'SSF4843812'),
('+919329826715', 'SSF4791480'),
('+919582801020', 'SSF4725071'),
('+919835766167', 'SSF4375891'),
('+919399811502', 'SSF4557698'),
('+919155043491', 'SSF4872515'),
('+919262683696', 'SSF4812573'),
('+919570159003', 'SSF4621398'),
('+919334946850', 'SSF5478834'),
('+917990179256', 'SSF5800474'),
('+919570837205', 'SSF5746851'),
('+919234731087', 'SSF4375685'),
('+918854053958', 'SSF5299768'),
('+917070487901', 'SSF6072958'),
('+916305663503', 'SSF5875130'),
('+917061908349', 'SSF5966526'),
('+917301089764', 'SSF5858713'),
('+917079727463', 'SSF6011930'),
('+917257935574', 'SSF4780171'),
('+917870958723', 'SSF5544178'),
('+917783043918', 'SSF5727264'),
('+917634902403', 'SSF5794572'),
('+917319716319', 'SSF5724245'),
('+917564929533', 'SSF5562133'),
('+918603502257', 'SSF5750934'),
('+918271160905', 'SSF5965742'),
('+918092642753', 'SSF5281360'),
('+918210050813', 'SSF5451856'),
('+919523228419', 'SSF6045894'),
('+919234638610', 'SSF5442365'),
('+919262272242', 'SSF5500867'),
('+919631180485', 'SSF5377287'),
('+919508409864', 'SSF5793721'),
('+919162082700', 'SSF6003707'),
('+919315681708', 'SSF5937112'),
('+919102474283', 'SSF5161633'),
('+919241850477', 'SSF5952835'),
('+916263095141', 'CID207400762'),
('+917321968819', 'SSF5777856'),
('+917488412594', 'SSF5869292'),
('+917258014617', 'SSF5940471'),
('+917022845150', 'SSF5805644'),
('+917858046084', 'SSF5645245'),
('+917301153492', 'SSF5792779'),
('+918541894820', 'SSF5745037'),
('+918541089541', 'SSF5877103'),
('+918076751162', 'SSF5324209'),
('+919031939244', 'SSF5746247'),
('+919973871095', 'SSF5679071'),
('+919138098665', 'SSF5845322'),
('+919508793969', 'SSF5602969'),
('+919779899869', 'SSF5783775'),
('+919523674811', 'SSF5438470'),
('+919870343414', 'SSF5048751'),
('+916267329711', 'SID951376223073'),
('+916367353488', 'SSF4484078'),
('+916264773181', 'SSF4969383'),
('+916201180729', 'SID951375238443'),
('+916299051386', 'SSF3970922'),
('+916202264793', 'SSF4306477'),
('+916261502516', 'SSF3944899'),
('+916376022959', 'SSF4516128'),
('+916266678133', 'SSF3349118'),
('+916239041128', 'SSF4323315'),
('+916232407042', 'SSF4189769'),
('+917004250634', 'SID951375321602'),
('+917724875385', 'SSF4004071'),
('+917049844935', 'SID951374313797'),
('+917208686295', 'SSF4377415'),
('+917779851108', 'SSF4817525'),
('+917408340911', 'SSF4371240'),
('+917860698098', 'SID951375867255'),
('+917509485067', 'SSF4520077'),
('+917357112140', 'SSF4144205'),
('+917689962907', 'SSF4490777'),
('+917209990675', 'SSF4346606'),
('+917703923790', 'SSF4320233'),
('+917727872379', 'SSF4660779'),
('+917763061881', 'SSF4395548'),
('+917764937400', 'SSF4271529'),
('+917369018793', 'SSF4266409'),
('+917970428618', 'SSF4260607'),
('+918092355826', 'SID951374701553'),
('+918873811814', 'SSF4466412'),
('+918409139292', 'SSF4025948'),
('+918229868265', 'SSF4613844'),
('+918920121801', 'SSF4300265'),
('+918458455481', 'SID951374304366'),
('+918804826330', 'SSF4263921'),
('+918651230535', 'SID951376006916'),
('+918292462321', 'SSF2900166'),
('+918233401657', 'SSF4017858'),
('+918450811797', 'SSF4369062'),
('+918084642740', 'SSF4525022'),
('+918210872901', 'SSF4380743'),
('+918541973117', 'SSF4203641'),
('+919608332512', 'SSF4530371'),
('+919780245853', 'SID951374921781'),
('+919931562875', 'SSF4639487'),
('+919354717992', 'SSF4525270'),
('+919399148640', 'SSF4397924'),
('+919511453308', 'SSF4365326'),
('+919525361954', 'SSF4256486'),
('+919341402317', 'SSF4373798'),
('+919793084645', 'SSF2633389'),
('+919279517644', 'SSF4263594'),
('+919784682841', 'SSF4083594'),
('+919569874612', 'SSF4293930'),
('+919846896595', 'SID951375428636'),
('+919827975985', 'SSF4487246'),
('+919209552585', 'SSF2796168'),
('+919770681461', 'SSF4160636'),
('+919234737849', 'SSF3616947'),
('+919142912409', 'SSF4125355'),
('+919279685072', 'SSF2833942'),
('+919262932584', 'SSF4238465'),
('+919506953633', 'SSF4178984'),
('+919523551601', 'SSF2696907'),
('+919852850810', 'SSF4411620'),
('+919155272465', 'SID951374645397'),
('+916299015254', 'SSF5948796'),
('+917281896730', 'SSF6227502'),
('+917461901436', 'SSF4865545'),
('+917859013349', 'SSF5804760'),
('+917646044135', 'SSF5631160'),
('+917209116682', 'SSF5711512'),
('+917061942916', 'SSF5692268'),
('+917061334592', 'SSF5780862'),
('+918341450266', 'SSF5673060'),
('+918603343239', 'SSF5733000'),
('+918210895625', 'SSF5940064'),
('+918405960760', 'SSF5459744'),
('+918009881186', 'SSF5435286'),
('+918252481743', 'SSF5781715'),
('+919709328174', 'SSF5208233'),
('+919150261450', 'SSF5669984'),
('+919102468097', 'SSF5130941'),
('+919559624507', 'SSF4574241'),
('+919935524971', 'SSF5933275'),
('+919155190077', 'SSF5408149'),
('+919135101384', 'SSF5258688'),
('+917309683787', 'SSF5509131'),
('+918406009352', 'SSF5644773'),
('+919279342975', 'SSF5346313'),
('+919341360840', 'SSF5712961'),
('+919724456635', 'SSF6199088'),
('+916201110921', 'SSF4057281'),
('+916287519491', 'SID951374852233'),
('+916296337441', 'SSF2898884'),
('+916205985143', 'SSF4185085'),
('+916376315891', 'SSF4240802'),
('+916232250788', 'SSF4239338'),
('+916287248604', 'SSF4123964'),
('+916353925292', 'SSF4334765'),
('+916565686599', 'SSF3899500'),
('+917014679478', 'SSF4094009'),
('+917054367646', 'SID951374520418'),
('+917543074126', 'SSF4258540'),
('+917294940249', 'SSF2729498'),
('+917357260393', 'SSF4076627'),
('+917879205173', 'SSF4189440'),
('+917303977325', 'SSF4295705'),
('+917321994979', 'SSF3633271'),
('+917319820330', 'SSF4242914'),
('+917761092529', 'SSF4366450'),
('+917485094722', 'SSF3805892'),
('+917029966204', 'SSF4054759'),
('+917050276988', 'SSF3853982'),
('+917667095034', 'SSF4246919'),
('+917366985908', 'SSF4190120'),
('+917229810469', 'SSF4075333'),
('+918233963907', 'SSF3403727'),
('+918890921494', 'SSF4210167'),
('+918949227912', 'SSF3620104'),
('+918619362816', 'SSF4140274'),
('+918306112539', 'SSF3871942'),
('+918809105844', 'SSF4312303'),
('+918809124461', 'SSF2710917'),
('+918756958184', 'SSF4115227'),
('+918093060960', 'SSF4604782'),
('+918853065954', 'SID951373647693'),
('+918107590811', 'SSF3835516'),
('+919390146087', 'SSF4170832'),
('+919351495860', 'SSF3929367'),
('+919993568627', 'SSF4488430'),
('+919341512778', 'SID951374812634'),
('+919461850296', 'SSF3843053'),
('+919341224820', 'SSF4200085'),
('+919054580884', 'SID951374925807'),
('+919608273080', 'SSF4346778'),
('+919672318493', 'SSF3973378'),
('+919635926167', 'SSF4154366'),
('+919950926290', 'SSF4304873'),
('+919216967567', 'SSF4263709'),
('+919602430030', 'SSF4269319'),
('+919060283220', 'SSF3192469'),
('+919352045708', 'SSF4354716'),
('+919179761290', 'SID951374550284'),
('+919752775359', 'SID951375923001'),
('+919352217159', 'SSF4049587'),
('+919279112779', 'SSF4218902'),
('+916200593686', 'SSF5669870'),
('+918173829617', 'SSF5886549'),
('+917091354108', 'SSF5669735'),
('+917319756658', 'SSF5669766'),
('+917762804699', 'SSF5602586'),
('+919958089638', 'SSF5669657'),
('+919351471103', 'SSF4400021'),
('+917977468082', 'SSF5415080'),
('+918235108255', 'SSF5379093'),
('+918235448131', 'SSF5531384'),
('+919526138876', 'SSF5539811'),
('+919934257481', 'SSF5532347'),
('+919335158255', 'SSF5678646'),
('+917042025378', 'SSF5254698'),
('+919835859800', 'SSF5227483'),
('+916376628664', 'SSF3991738'),
('+916200701919', 'SSF3550281'),
('+916554394655', 'SID951374778404'),
('+916383891600', 'SSF3803967'),
('+916203569367', 'SSF4000208'),
('+916350962789', 'SSF3906960'),
('+917211138574', 'SSF4463959'),
('+917903651053', 'SSF3855057'),
('+917905598990', 'SSF3832933'),
('+917597615591', 'SSF4942620'),
('+918619021345', 'SSF3763220'),
('+918464686749', 'SSF2730408'),
('+918255878597', 'SSF3284331'),
('+918654866877', 'SSF3895839'),
('+918503925459', 'SSF3387311'),
('+918755576375', 'SSF3875381'),
('+918292216927', 'SSF3484079'),
('+918424650887', 'SSF3344826'),
('+918561210040', 'SSF3606971'),
('+918619784542', 'SSF3368792'),
('+919680324964', 'SSF3795838'),
('+919858899888', 'SID951374728291'),
('+919153281075', 'SSF3876197'),
('+919564345594', 'SSF3691714'),
('+919835363159', 'SID951375083160'),
('+919636855698', 'SSF3907107'),
('+919928416824', 'SSF3917071'),
('+919875797575', 'SSF3896209'),
('+919602295940', 'SSF3896217'),
('+919575957597', 'SSF3896154'),
('+916249480488', 'SSF3793603'),
('+916200000090', 'SSF3614435'),
('+917599696967', 'SSF3842999'),
('+917877031801', 'SSF3812522'),
('+917645810298', 'SSF3615686'),
('+917491876653', 'SSF3621149'),
('+918955527192', 'SSF3581403'),
('+918500000000', 'SSF3630790'),
('+918696849679', 'SSF2384482'),
('+918095243484', 'SID2125391314'),
('+918290678404', 'SSF2503789'),
('+918164649977', 'SSF3577820'),
('+918757885195', 'SSF3551174'),
('+918292423352', 'SSF3560123'),
('+919646464667', 'SSF3346274'),
('+919867575575', 'SSF3615985'),
('+919345646546', 'SSF3236746'),
('+919983184667', 'SSF3685108'),
('+919199549441', 'SSF3440228'),
('+919279257158', 'SSF3453956'),
('+919543445155', 'SSF3630262'),
('+916201116412', 'SSF3194293'),
('+916268539741', 'SSF3510205'),
('+917400106795', 'SSF3318426'),
('+917525920537', 'SSF3630758'),
('+918485859565', 'SSF3439493'),
('+918956061986', 'SSF3607880'),
('+918799794948', 'SSF3183623'),
('+917763016890', 'SSF5240128'),
('+918541011392', 'SSF5103969'),
('+917096132176', 'SSF5766084'),
('+917070145930', 'SSF5771192'),
('+919198243497', 'SSF4677128'),
('+916494644948', 'SSF3339108'),
('+916424606042', 'SSF2981740'),
('+917319667634', 'SSF5715108'),
('+919709055763', 'SSF5512926'),
('+919065601245', 'SSF5406052'),
('+917870597895', 'SSF5040956'),
('+918863047447', 'SSF4122114'),
('+918084921252', 'SSF5443351'),
('+917505833604', 'SSF4757997'),
('+917541854686', 'SSF3285418'),
('+918290365892', 'SSF2887665'),
('+919685742536', 'SSF2823010'),
('+918827408529', 'SID951375614166'),
('+919009867006', 'SID951375558635'),
('+919973520670', 'SID951374649150'),
('+917318407872', 'SSF2462049'),
('+917742040039', 'SID951376097341'),
('+918210860343', 'SID951373847396'),
('+919113104138', 'SSF2329805'),
('+916265607094', 'SSF5081309'),
('+916289094799', 'SSF3899215'),
('+916206175499', 'SSF3571014'),
('+916207938706', 'SSF5070870'),
('+916202152242', 'SSF5527308'),
('+916207253896', 'SSF4958666'),
('+917645955377', 'SSF5307499'),
('+917633071457', 'SSF5060622'),
('+917488652764', 'SSF5172198'),
('+917803936046', 'SID951374749834'),
('+917600577622', 'SSF5299130'),
('+917067240180', 'SSF5083172'),
('+917632855089', 'SSF5295851'),
('+917004901022', 'SSF5267319'),
('+917061270938', 'SSF6137160'),
('+917004112316', 'SSF4866344'),
('+917209168308', 'SSF5013346'),
('+917970970756', 'SSF4632377'),
('+917667571373', 'SSF4735978'),
('+917079408582', 'SSF3265314'),
('+917484889683', 'SSF4973654'),
('+917541885935', 'SSF4888168'),
('+917970594806', 'SSF5026308'),
('+917319756772', 'SSF5164291'),
('+917043292171', 'SSF4642467'),
('+917325076554', 'SSF4752159'),
('+917370970676', 'SSF4778298'),
('+917371942162', 'SSF4720788'),
('+917368844604', 'SSF5052323'),
('+917061283484', 'SSF5046365'),
('+917389262572', 'SSF5080853'),
('+917070864407', 'SSF5969121'),
('+917091513259', 'SSF4734863'),
('+917903705946', 'SSF5024758'),
('+917418517916', 'SSF4877570'),
('+917667054767', 'SSF4564167'),
('+918340144429', 'SSF3358591'),
('+918521064942', 'SID951374602096'),
('+918002156948', 'SSF4644517'),
('+918539946361', 'SSF5482205'),
('+918839052341', 'SSF5226448'),
('+918789348410', 'SSF5475008'),
('+918092779562', 'SSF6032172'),
('+918298983526', 'SSF5034074'),
('+918789967045', 'SSF5026203'),
('+918178521248', 'SSF3468042'),
('+918404980063', 'SSF4984230'),
('+918976468852', 'SSF4243325'),
('+918235436155', 'SSF4715750'),
('+918409066596', 'SSF5231609'),
('+918102656728', 'SSF5066274'),
('+918889609385', 'SSF4017008'),
('+918709221905', 'SSF3376151'),
('+918229054108', 'SSF4605885'),
('+918866598667', 'SSF5991800'),
('+919523316793', 'SSF3449446'),
('+919131096998', 'SSF4925457'),
('+919006053463', 'SSF4489181'),
('+919120102227', 'SSF5001825'),
('+919608910195', 'SSF2740544'),
('+919430205610', 'SSF5209911'),
('+919305979692', 'SSF3715660'),
('+919798239422', 'SSF5510200'),
('+919262512575', 'SSF5320187'),
('+919241800337', 'SSF5221145'),
('+919031760789', 'SSF3118484'),
('+919831330448', 'SSF4714257'),
('+919608022171', 'SSF5089565'),
('+919748695622', 'SSF5702108'),
('+919950227001', 'SSF4581507'),
('+919546916906', 'SSF3432738'),
('+919060239376', 'SSF5074091'),
('+919546259766', 'SSF5276255'),
('+919279103289', 'SSF5226368'),
('+919306964449', 'SSF5168461'),
('+919507535650', 'SSF4871067'),
('+919142316380', 'SSF5026183'),
('+919334525386', 'SSF4870105'),
('+919031774107', 'SSF5130314'),
('+919399069284', 'SSF4847757'),
('+919576185583', 'SSF4777100'),
('+919783339837', 'SSF4590208'),
('+919344174386', 'SSF3385425'),
('+919216510234', 'SSF5001999'),
('+919931355641', 'SSF3159654'),
('+919508981589', 'SSF4410825'),
('+919117922789', 'SSF5074051'),
('+919303519539', 'SSF5079092'),
('+919661856971', 'SSF3129559'),
('+919755848599', 'SSF3837814'),
('+919109791190', 'SSF5265372'),
('+917781896984', 'SSF5060174'),
('+918960950792', 'SSF5713786'),
('+919258652024', 'SSF5564815'),
('+919060092124', 'SSF5650928'),
('+918789086673', 'SSF5633663'),
('+917759098106', 'SSF4973289'),
('+917250802502', 'SID951376190685'),
('+916383479262', 'SSF5441936'),
('+916206003698', 'SSF4456741'),
('+916345421548', 'SID951374844904'),
('+917349813036', 'SSF4975504'),
('+917068182152', 'SSF5057616'),
('+917091263912', 'SSF4931177'),
('+917388021504', 'SSF4852284'),
('+917481049932', 'SSF5012454'),
('+917089944215', 'SSF5259581'),
('+917079985357', 'SSF4451581'),
('+917410945013', 'SSF4566902'),
('+917487060481', 'SSF4372938'),
('+917000397687', 'SSF5038250'),
('+918081928199', 'SSF4567191'),
('+918873834291', 'SSF4742865'),
('+918789679009', 'SSF4923615'),
('+918298332116', 'SSF4987979'),
('+918434410067', 'SSF2660922'),
('+918103127612', 'SSF4664164'),
('+918103669719', 'SSF4544530'),
('+918815154142', 'SSF5090004'),
('+919341173631', 'SSF3689465'),
('+919322671837', 'SSF4965710'),
('+919065848849', 'SSF4899399'),
('+919117812538', 'SSF4983964'),
('+919006248676', 'SSF4983991'),
('+919199606424', 'SSF4715498'),
('+919193054643', 'SSF4840386'),
('+919523841056', 'SSF2995772'),
('+919153884154', 'SSF4439930'),
('+917870805359', 'SSF4894973'),
('+916396476054', 'SSF5248754'),
('+919012882866', 'SSF5286845'),
('+919199580828', 'CID211103889'),
('+917317286537', 'SSF5224666'),
('+918009871965', 'SSF5463020'),
('+919352759457', 'SSF5698095'),
('+916202261808', 'SSF4838256'),
('+916202291137', 'SSF4723903'),
('+916204520981', 'SSF4709264'),
('+917739682873', 'SSF4841638'),
('+917024955875', 'SSF4683389'),
('+917858821019', 'SSF3006641'),
('+917061198964', 'SSF4838827'),
('+917321886537', 'SSF4527549'),
('+917481839006', 'SSF3233210'),
('+917970631588', 'SSF4990273'),
('+917479552756', 'SID951375929067'),
('+917984412041', 'SSF4853802'),
('+917361817636', 'SSF4878402'),
('+917976664589', 'SSF4260883'),
('+918210526363', 'SSF4785648'),
('+918862848505', 'SID951375949221'),
('+918235674451', 'SSF3826697'),
('+918018370660', 'SSF2992572'),
('+918092067078', 'SSF4360135'),
('+918448915007', 'SSF4873175'),
('+918409463064', 'SSF2375265'),
('+919625552445', 'SSF4786374'),
('+919279222732', 'SSF4834468'),
('+919631846843', 'SSF4370015'),
('+919241401065', 'SSF3494949'),
('+919023719940', 'SSF4871349'),
('+919142624199', 'SSF3537289'),
('+919304909370', 'SSF4654455'),
('+919263143713', 'SSF5606791'),
('+919631101502', 'SSF4496901'),
('+919755154727', 'SSF4684072'),
('+919784531930', 'SSF4822615'),
('+919135472891', 'SSF4407817'),
('+919973580940', 'SSF4851253'),
('+919153755805', 'SSF5096235'),
('+918176032353', 'SSF5270026'),
('+916200755880', 'SSF5732683'),
('+918084871516', 'SSF4536753'),
('+919142455936', 'SSF5746598'),
('+919430143445', 'SSF4333926'),
('+916382351239', 'SSF5822773'),
('+916202836541', 'SSF5682793'),
('+916205062800', 'SSF5970191'),
('+917352667028', 'SSF5530595'),
('+917808749103', 'SSF5783968'),
('+917633031390', 'SSF5367605'),
('+918434614064', 'SSF5429064'),
('+918674902489', 'SSF5906187'),
('+918572850898', 'SSF5305124'),
('+919334522580', 'SSF5701420'),
('+919041864725', 'SSF5612270'),
('+919934030561', 'SSF6070037'),
('+916287385897', 'SSF5020011'),
('+916209379621', 'SSF5035633'),
('+917870834428', 'SSF5663622'),
('+917257928945', 'SSF5544293'),
('+917696283895', 'SSF5544177'),
('+919229652312', 'SSF6109990'),
('+919006280457', 'SSF5478074'),
('+919938510263', 'SSF5426200'),
('+916266442508', 'CID069705298'),
('+917010483842', 'SSF5066955'),
('+918434406640', 'SSF5780980'),
('+919709652800', 'SSF5719157'),
('+919234303308', 'SSF5630541'),
('+919122317516', 'SSF5325189'),
('+916302914882', 'SSF4345608'),
('+916200257049', 'SSF4220290'),
('+916267208587', 'SSF3032384'),
('+916303598185', 'SSF4532406'),
('+916427884040', 'SID2125708642'),
('+916266599390', 'SSF4276733'),
('+917229984541', 'SSF4054339'),
('+917856068768', 'SSF3102327'),
('+917903139747', 'SSF4489262'),
('+917050013346', 'SSF4514415'),
('+917562823270', 'SSF4403601'),
('+917631098251', 'SSF4352168'),
('+917361826424', 'SSF4256344'),
('+917415602974', 'SSF4234780'),
('+917229951290', 'SSF4897690'),
('+917878432483', 'SSF4283235'),
('+917759011058', 'SID951375275780'),
('+917870525496', 'SSF4287265'),
('+917079472577', 'SSF4342077'),
('+917319807247', 'SSF4504202'),
('+917542999662', 'SSF4411619'),
('+917739526112', 'SSF4347208'),
('+918955617436', 'SSF4007634'),
('+918107374726', 'SSF4231121'),
('+918789272846', 'SSF4311616'),
('+918540915938', 'SSF4222420'),
('+918789951944', 'SSF4515193'),
('+918523644555', 'SID951375268360'),
('+918757716298', 'SSF4363958'),
('+918757126323', 'SSF4525484'),
('+918789317454', 'SSF4300210'),
('+918797719584', 'SID951374342164'),
('+918084721967', 'SSF4203657'),
('+918434394818', 'SSF4436047'),
('+918969884565', 'SSF4421863'),
('+918629956780', 'SSF2904473'),
('+918809581741', 'SSF4306102'),
('+918092963980', 'SSF4065052'),
('+918789457841', 'SSF3802577'),
('+918409867659', 'SID951375664089'),
('+918809686387', 'SSF4308502'),
('+918102658246', 'SSF4375861'),
('+918290154015', 'SSF3953936'),
('+919116693896', 'SSF4354700'),
('+919153070128', 'SSF5102564'),
('+919166316378', 'SID951375385956'),
('+919234413647', 'SSF4251010'),
('+919771948263', 'SSF4309724'),
('+919680119335', 'SSF4320009'),
('+919054069293', 'SID951374516119'),
('+919622518344', 'SSF4356983'),
('+919334678439', 'SSF4352656'),
('+919572794134', 'SID951376187646'),
('+919667993454', 'SSF4120413'),
('+919310763061', 'SSF3907001'),
('+919142530053', 'SSF3553378'),
('+919155525063', 'SID951375928033'),
('+919216404392', 'SSF4310090'),
('+919955668691', 'SSF4368757'),
('+919341026321', 'SSF2738921'),
('+919602523441', 'SSF4046703'),
('+919555238453', 'SID951374886487'),
('+919828442157', 'SSF3942029'),
('+919508587038', 'SSF5202754'),
('+919523344800', 'SSF4318300'),
('+919865669565', 'SID951374455709'),
('+919955392444', 'SSF4231554'),
('+919117943267', 'SSF4320332'),
('+919576659947', 'SSF2573354'),
('+919340326617', 'SSF4244851'),
('+919508705536', 'SSF4347065'),
('+919770503762', 'SSF3803248'),
('+919399164980', 'SSF3966467'),
('+916206013664', 'SSF5685922'),
('+917070953952', 'SSF5585365'),
('+917673070326', 'SSF4848795'),
('+918766277571', 'SSF5765423'),
('+918400508336', 'SSF5619278'),
('+919871085347', 'SSF5493446'),
('+919771665700', 'SSF5644770'),
('+919905436466', 'SSF5401494'),
('+918866170752', 'SSF5388793'),
('+919172867337', 'SSF6199060'),
('+916204486505', 'SID2125043632'),
('+919523690816', 'SSF4538732'),
('+916378650867', 'SSF3915186'),
('+917851010393', 'SSF4237015'),
('+917856632952', 'SID951372792164'),
('+917357065954', 'SSF3969936'),
('+917878004696', 'SSF4191728'),
('+917668876091', 'SSF3865566'),
('+917667976767', 'SID951376048168'),
('+917568876091', 'SSF3872030'),
('+917654171345', 'SSF4379675'),
('+917357741837', 'SSF4257437'),
('+917050401691', 'SSF4209623'),
('+917324958780', 'SSF4399384'),
('+917903977374', 'SSF4395883'),
('+917694076380', 'SSF4059057'),
('+917742486320', 'SSF3933212'),
('+917061214376', 'SSF4188249'),
('+918769609776', 'SSF2585889'),
('+918107154124', 'SSF4237016'),
('+918529586655', 'SSF4849659'),
('+918529438093', 'SSF4294006'),
('+918529592935', 'SID951375721768'),
('+918207578522', 'SSF4317910'),
('+918102211868', 'SSF4413829'),
('+918969294228', 'SSF3888213'),
('+918789174251', 'SSF3710332'),
('+918787841937', 'SSF4286753'),
('+919602896981', 'SID951375124348'),
('+919161265932', 'SSF4372320'),
('+919561716129', 'SSF4151748'),
('+919510755994', 'SSF4358359'),
('+919661273258', 'SSF2729510'),
('+919257513661', 'SSF3879756'),
('+919967646292', 'SSF4250105'),
('+919801619576', 'SSF4166193'),
('+919570020137', 'SSF4411062'),
('+919074325945', 'SSF2748036'),
('+919509007135', 'SSF3930298'),
('+919950774059', 'SSF4225657'),
('+919771923763', 'SSF4360431'),
('+919521699385', 'SSF4066295'),
('+917739098107', 'SSF5605032'),
('+917258882325', 'SSF5561877'),
('+918789896605', 'SSF5777248'),
('+916239211394', 'SSF5587894'),
('+917986541262', 'SSF5036960'),
('+918809078584', 'SSF5601285'),
('+918471012656', 'SSF5925137'),
('+918394848606', 'SSF5103813'),
('+918755038085', 'SSF4815475'),
('+919771839648', 'SSF5531093'),
('+919973743998', 'SID2125260785'),
('+919693019887', 'SSF5413997'),
('+916350976789', 'SSF3898783'),
('+917970884189', 'SSF3841487'),
('+917568543185', 'SSF3746784'),
('+917999316520', 'SSF3825682'),
('+918608381811', 'SSF3565563'),
('+918815589172', 'SSF4449367'),
('+918265496139', 'SSF3656309'),
('+918260284357', 'SSF2612029'),
('+918435865568', 'SSF3870347'),
('+918905282906', 'SSF3907953'),
('+918209311612', 'SSF3867029'),
('+918078666267', 'SSF3865796'),
('+919680225865', 'SSF3621070'),
('+919928471637', 'SSF2460377'),
('+919533556825', 'SID951376003594'),
('+919905501365', 'SSF3560719'),
('+919931865862', 'SID951376004667'),
('+919931565666', 'SID951375999937'),
('+919110564676', 'SSF3801701'),
('+919974225806', 'SID951375451408'),
('+919118126597', 'SSF3702252'),
('+919934225659', 'SSF3872115'),
('+919254687521', 'SID951376097646'),
('+919908513256', 'SSF3738655'),
('+919865472853', 'SID951374201194'),
('+919865846483', 'SSF3687660'),
('+919680127434', 'SSF3695355'),
('+919424845404', 'SID951374048305'),
('+919279650162', 'SID951375611371'),
('+919306878244', 'SID951376057490'),
('+919767846566', 'SID951375383004'),
('+917555484189', 'SSF3704494'),
('+918664288999', 'SSF3055937'),
('+918675544095', 'SID951375670856'),
('+918209880119', 'SSF3674195'),
('+919608802283', 'SSF3623850'),
('+919341622986', 'SSF3134826'),
('+919829361245', 'SSF2682166'),
('+919331415616', 'SID951376142306'),
('+919022650197', 'SID951375482892'),
('+919434843484', 'SSF3710448'),
('+919858856984', 'SSF3715402'),
('+917986920389', 'SSF5947589'),
('+916350506363', 'SSF2759204'),
('+917990658542', 'SSF3682834'),
('+917428678456', 'SSF3451579'),
('+917321062708', 'SSF3376294'),
('+918002645758', 'SSF3233788'),
('+918458875577', 'SSF3576456'),
('+919771371682', 'SSF3376378'),
('+919845954916', 'SSF3145492'),
('+919799803822', 'SSF2575081'),
('+917070635822', 'SSF5059455'),
('+918969348602', 'SSF6204591'),
('+918235790113', 'SSF5917756'),
('+918521382675', 'SSF5725787'),
('+919153436822', 'SSF5173581'),
('+917015222137', 'SSF5102246'),
('+918464873407', 'SSF3339003'),
('+918461656498', 'SSF3885932'),
('+919755129826', 'SSF3378668'),
('+919351404945', 'SSF2586388'),
('+919872161631', 'SSF3349663'),
('+917739837341', 'SSF5192236'),
('+917070747677', 'SSF5162312'),
('+919263938010', 'SSF4761754'),
('+917568093345', 'SSF3121178'),
('+918853417154', 'SSF3048345'),
('+918767654545', 'SSF2917799'),
('+917830305943', 'SSF4758019'),
('+918171711545', 'SSF4763200'),
('+918394046897', 'SSF4757909'),
('+917891461171', 'SID951376047045'),
('+919131476060', 'SID951374312057'),
('+918935938369', 'SSF6447954'),
('+918949346524', 'SSF3835079'),
('+917240909669', 'SSF4282147'),
('+918002538343', 'SSF3025873'),
('+917440812324', 'SID951373465762'),
('+919179974568', 'SSF3113562'),
('+917601035708', 'SSF2726329'),
('+919006223952', 'SSF4616308'),
('+919648729031', 'SSF5923761'),
('+916209033572', 'SSF6229261'),
('+919479043690', 'SSF3389781'),
('+917461943206', 'SID951374512712'),
('+916205315866', 'SSF2612357'),
('+916201115215', 'SID951374208035'),
('+917974245081', 'SID951375985924'),
('+919464649494', 'SSF2959237'),
('+919031277751', 'SSF5575127'),
('+919660768223', 'SSF4080811'),
('+918092226942', 'SSF3598942'),
('+916267681710', 'CID207400657'),
('+916201058131', 'SSF3319854'),
('+919263172895', 'SSF4782555'),
('+916296271129', 'SID2125499849'),
('+919691192565', 'SSF3797934'),
('+919602524713', 'SSF4083947'),
('+918873022532', 'SSF6326239'),
('+917894944946', 'SID951374715520'),
('+919199710079', 'SSF5625860'),
('+917415018930', 'SSF2695879'),
('+916202835746', 'SSF3457057'),
('+918057451128', 'SSF4632408'),
('+919720726084', 'SSF3613241'),
('+916494444364', 'SSF2387176'),
('+919012154862', 'SSF5929038'),
('+918827956065', 'SID2125035990'),
('+919158273489', 'SID951374533755'),
('+916124844644', 'SSF3748020'),
('+916268523326', 'SSF3361018'),
('+916307473267', 'SID951373742276'),
('+919934232477', 'SSF6101434'),
('+919572745655', 'SID2125366646'),
('+918284022297', 'SSF6185389'),
('+917089323819', 'SSF5722196'),
('+919645878656', 'CID103103766'),
('+917582876011', 'SSF4375484'),
('+918319294569', 'SSF4011161'),
('+916268693829', 'SSF4085459'),
('+919111904738', 'SID951373144069'),
('+918955575747', 'SSF3159040'),
('+919630468955', 'SSF4883750'),
('+917541959058', 'SSF5057672'),
('+916203607349', 'SSF2885048'),
('+919359332282', 'SSF6563351'),
('+918956437659', 'SID951376058372'),
('+917309702254', 'SSF3111393'),
('+916261758414', 'SSF3691655'),
('+919006982844', 'SSF6054741'),
('+919918848497', 'SSF2571284'),
('+917894876246', 'SID951372950517'),
('+918292587008', 'SSF4812726'),
('+918052960830', 'SSF3587781'),
('+918239609926', 'SSF3565898'),
('+918949495705', 'SID951374617567'),
('+918720069669', 'SSF3672724'),
('+917631021857', 'SSF3397939'),
('+916201957650', 'SSF3201904'),
('+918619074252', 'SID951376113056'),
('+917869795326', 'SID951374787903'),
('+919574773923', 'SSF5113010'),
('+917761058872', 'SSF3734734'),
('+918051972634', 'SSF2814550'),
('+918192828178', 'SSF5385033'),
('+919926826389', 'SID951374213939'),
('+916370092149', 'SSF4064451'),
('+917319840954', 'SSF2837322'),
('+917828831197', 'SSF3254485'),
('+918450083248', 'SSF3092878'),
('+917366874477', 'SSF6501737'),
('+916269263782', 'CID261402178'),
('+916205799686', 'SSF3702415'),
('+918521508754', 'SSF3220891'),
('+916261285604', 'SSF2475263'),
('+919589123093', 'SID951373744206'),
('+918107733625', 'SSF4470055'),
('+918292643291', 'SSF5757098'),
('+919009069096', 'SSF6507548'),
('+918827789556', 'SSF2960433'),
('+919135912407', 'SSF3435847'),
('+916350435598', 'SID951375050645'),
('+917970587118', 'SSF5555480'),
('+919797669471', 'SSF2708243'),
('+919658856665', 'SSF2469047'),
('+919022678801', 'SID951374835905'),
('+918630170790', 'SSF6217478'),
('+919340811509', 'SID951374796198'),
('+917004307270', 'SID951373650265'),
('+916310875445', 'SID951374320548'),
('+919785161171', 'SSF5940210'),
('+917470890186', 'SSF3068589'),
('+916204163546', 'SSF5045010'),
('+918889435305', 'CID140609650'),
('+918085976147', 'SID951375710334'),
('+918529540248', 'SSF4046439'),
('+917764970954', 'SSF5571999'),
('+919576196013', 'SSF2953439'),
('+918248147957', 'SSF2662754'),
('+918889927081', 'SID951373352617'),
('+919950006244', 'SID951375129547'),
('+917307611367', 'SSF5244643'),
('+917060766468', 'SSF5248282'),
('+919653755691', 'SID951375413954'),
('+918579031726', 'SSF3563375'),
('+917352739420', 'SID951376051027'),
('+918862957425', 'SSF4349641'),
('+916204828554', 'SID951372983306'),
('+917378452274', 'SSF5398716'),
('+918754455455', 'SSF3596426'),
('+916393141838', 'SSF3392870'),
('+919024105254', 'SID951373746667'),
('+917015519784', 'CID084707286'),
('+919340679208', 'CID053202410'),
('+919238542480', 'SID951373038849'),
('+917488255970', 'SSF2613334'),
('+919516099078', 'SID951375328541'),
('+919263084499', 'SSF4899212'),
('+918171775911', 'SSF6019502'),
('+916201683291', 'SSF2880522'),
('+917765059616', 'SSF6442900'),
('+917080534826', 'SSF4641735'),
('+919523190361', 'SID951375160270'),
('+919691282354', 'CID206813133'),
('+917368009030', 'SID951375392093'),
('+919392721241', 'SID951375240816'),
('+918985687836', 'SSF2910443'),
('+917859074039', 'SID951376120623'),
('+917254897252', 'SSF3458833'),
('+916200782667', 'SID951375443099'),
('+918877732413', 'SSF6425751'),
('+919982553642', 'SID951375470688'),
('+917488962255', 'SSF4657985'),
('+919311849521', 'SSF5965988'),
('+918229859889', 'SSF5707817'),
('+917956164679', 'SID951374605966'),
('+918224094511', 'SID2125557558'),
('+918103325640', 'SID951375587683'),
('+917389142453', 'SSF3623204'),
('+918923254161', 'SSF5871147'),
('+916202725864', 'SSF6347248'),
('+917007109463', 'SSF4296036'),
('+916297496802', 'SID951375723377'),
('+917869814506', 'SSF5851877'),
('+916266682513', 'SSF5710835'),
('+917239034250', 'SSF5325765'),
('+917700883026', 'SSF5030762'),
('+919259061836', 'SSF4807166'),
('+919142417818', 'SSF5507002'),
('+918955052416', 'SID951375385399'),
('+919302313036', 'SID951373197822'),
('+919905168599', 'SSF3707760'),
('+918864032229', 'SSF5571986'),
('+919828137507', 'SSF4712819'),
('+919153427947', 'SSF3881478'),
('+917858285355', 'SID951374804852'),
('+917250441367', 'SSF3380239'),
('+917209087452', 'SSF5271105'),
('+918092271549', 'SSF5585091'),
('+919001564752', 'SSF4378351'),
('+919670658282', 'SID951375757168'),
('+919661259990', 'SSF4212672'),
('+919993923977', 'SSF3046281'),
('+919244295797', 'SSF2781399'),
('+917261852971', 'SSF5533508'),
('+916287683848', 'SSF6007429'),
('+916356720660', 'SSF3459642'),
('+918863030935', 'SSF5135514'),
('+918552831283', 'SSF4859218'),
('+919006926569', 'SSF5162746'),
('+919343617460', 'SSF3539779'),
('+919644074233', 'SSF5516235'),
('+919119979984', 'SSF3431899'),
('+919693306212', 'SSF4925745'),
('+919661245694', 'SSF4875422'),
('+919123449634', 'SSF4940763'),
('+919754981536', 'SSF3699295'),
('+916287384935', 'SSF5438176'),
('+919198124145', 'SSF5554280'),
('+919234327184', 'SSF5257685'),
('+917484840156', 'SSF5928607'),
('+917541915539', 'SSF5716960'),
('+918540904289', 'SSF5683734'),
('+918797472279', 'SSF5275934'),
('+919899944793', 'SSF5369977'),
('+919304290755', 'SSF5707884'),
('+919153356876', 'SSF5276028'),
('+916287806826', 'SSF5449802'),
('+917462965912', 'SSF5682755'),
('+917261046939', 'SSF5683061'),
('+917380845154', 'SSF5763387'),
('+917033097749', 'SSF5700908'),
('+918544458163', 'SSF5652108'),
('+919289207368', 'SSF5786248'),
('+917667230553', 'SID951375683442'),
('+918873367778', 'SID951375401437'),
('+917070497445', 'SSF5758864'),
('+917480945124', 'SSF5509193'),
('+917991747960', 'SSF5505762'),
('+917347002415', 'SSF5256678'),
('+919125940912', 'SSF3864820'),
('+919939604017', 'SSF5457467'),
('+919170279056', 'SSF2492022'),
('+919918871760', 'SSF2380375'),
('+919356593429', 'SSF2590061'),
('+916375615753', 'SSF5557786'),
('+916200864238', 'SSF5309948'),
('+916367152331', 'SSF4924143'),
('+916230163134', 'SSF5322248'),
('+916264927326', 'SSF3642680'),
('+916262662233', 'SID951375435457'),
('+916378864919', 'SSF5265206'),
('+917294118928', 'SID951372991192'),
('+917461074293', 'SSF5257923'),
('+917225044859', 'SSF4921825'),
('+917480097131', 'SSF2815410'),
('+917739281744', 'SSF3733014'),
('+917339946962', 'SSF4757035'),
('+917070625161', 'SSF5105672'),
('+917676435218', 'SSF5297108'),
('+917765931342', 'SSF2485638'),
('+918571025360', 'SSF4893926'),
('+918521649952', 'SSF5312179'),
('+918949295260', 'SSF5074739'),
('+918435407153', 'CID069700898'),
('+918769342581', 'SSF3096996'),
('+918709431259', 'SSF3787899'),
('+918320225900', 'SSF4395462'),
('+918207714957', 'SSF4763970'),
('+918507278666', 'SSF4880601'),
('+918603507821', 'SSF4985998'),
('+918651821894', 'SSF5119301'),
('+919661745697', 'SSF3262476'),
('+919131819860', 'SSF4891920'),
('+919303644140', 'SSF3318169'),
('+919306518114', 'SSF4723147'),
('+919798437926', 'SSF4869265'),
('+919764370017', 'SSF4849644'),
('+919329802207', 'SSF3388362'),
('+919973616897', 'SSF4307103'),
('+919110074650', 'SSF4925506'),
('+919341778825', 'SSF4782231'),
('+919065706102', 'SSF4871200'),
('+919256964132', 'SSF3077184'),
('+919279101165', 'SSF4750453'),
('+919829554825', 'SSF2862103'),
('+919238130389', 'SSF5320910'),
('+919399447534', 'SSF3123925'),
('+919984796510', 'SSF5134844'),
('+919229067907', 'SSF5706192'),
('+919511096774', 'SSF5299017'),
('+919580918082', 'SSF4156639'),
('+919453596896', 'SID951374070844'),
('+916006719914', 'SSF4048081'),
('+916201308265', 'SSF4875705'),
('+916205402839', 'SSF4601439'),
('+917339733717', 'SID951375683860'),
('+917014042103', 'SSF5066948'),
('+917739762857', 'SSF5098969'),
('+917879728296', 'SSF4561007'),
('+917975116057', 'SSF5020523'),
('+917623877281', 'SSF4934933'),
('+917073694403', 'SSF5033099'),
('+917858836224', 'SSF2970424'),
('+917766006311', 'SID951375540549'),
('+917543859630', 'SSF3175225'),
('+917294933205', 'SSF4637115'),
('+917667089351', 'SID951375429314'),
('+917783841099', 'SSF5015263'),
('+918122032714', 'SSF5095817'),
('+918120049585', 'SSF4933747'),
('+918521905838', 'SSF5252395'),
('+918984326562', 'SSF5072625'),
('+918235092035', 'SSF5035787'),
('+918292931152', 'SSF5326591'),
('+918292329112', 'SSF3192518'),
('+918797952871', 'SSF4715346'),
('+918340546200', 'SSF4741755'),
('+918409293838', 'SSF4897179'),
('+919523118524', 'SSF4728220'),
('+919336800985', 'SSF5024108'),
('+919171273085', 'SSF4966978'),
('+919022631227', 'SSF5066510'),
('+919102254940', 'SSF3141352'),
('+919098037379', 'SSF3482133'),
('+919523557615', 'SSF4561230'),
('+919693318719', 'SSF2888528'),
('+919060804357', 'SSF5250936'),
('+919065246052', 'SSF4564137'),
('+919718278141', 'SSF2970271'),
('+919523674578', 'SSF4728864'),
('+919693092418', 'SSF4973591'),
('+919509449283', 'SID951375125161'),
('+919234449329', 'SSF3238276'),
('+919390873532', 'SSF4390167'),
('+919031893223', 'SSF4875802'),
('+917482095485', 'SSF2778566'),
('+918910779710', 'SSF4380869'),
('+918434256873', 'SSF5660912'),
('+917061924037', 'SSF5977528'),
('+916376273259', 'SSF4790358'),
('+916203722959', 'SSF6037600'),
('+916205400464', 'SSF5798443'),
('+917632808355', 'SSF5605951'),
('+917631143056', 'SSF5584625'),
('+917281919791', 'SSF6203890'),
('+917369067927', 'SSF6048033'),
('+917296057763', 'SSF5685896'),
('+917482849764', 'SSF5934233'),
('+917782047410', 'SSF5452606'),
('+918521949943', 'SSF5696614'),
('+918862807987', 'SSF5730126'),
('+918360035089', 'SSF5059129'),
('+918178607975', 'SSF5519905'),
('+919818321864', 'SSF5756299'),
('+919534344999', 'SSF6203848'),
('+919321049742', 'SSF5598611'),
('+919693231539', 'SSF5469359'),
('+919311652807', 'SSF5908293'),
('+917042891229', 'SSF6199000'),
('+917054257898', 'SSF5802792'),
('+917979873959', 'SSF5163341'),
('+917856835765', 'SSF5476106'),
('+918002552619', 'SSF5639688'),
('+918102837267', 'SSF5662645'),
('+918235143423', 'SSF5556139'),
('+918002428599', 'SSF5341157'),
('+919315152503', 'SSF5943044'),
('+919709286898', 'SSF5353735'),
('+919060950209', 'SSF5565880'),
('+919060681366', 'SSF5547491'),
('+919939165926', 'SSF5365249'),
('+916386229046', 'SSF2847020'),
('+916313496761', 'SID951374642725'),
('+916377503951', 'SSF4047655'),
('+916265463961', 'SSF4442872'),
('+916354817401', 'SSF4125831'),
('+916265708265', 'SSF4114229'),
('+916206858595', 'SSF2927713'),
('+916269820540', 'SSF2821435'),
('+916299757976', 'SSF4404382'),
('+916264270407', 'SSF4381955'),
('+916203369564', 'SSF4179312'),
('+917879287761', 'SSF4189770'),
('+917295803662', 'SSF4143753'),
('+917878431879', 'SSF4197216'),
('+917459897064', 'SSF2538808'),
('+917970821554', 'SSF4197240'),
('+917479906530', 'SSF4191130'),
('+917857017972', 'SSF4633901'),
('+917876443098', 'SSF4252154'),
('+917488553082', 'SSF4157279'),
('+917070056792', 'SSF4123580'),
('+917663045141', 'SSF4226563'),
('+917481023974', 'SID951373984729'),
('+917415176443', 'SSF2505705'),
('+918529832546', 'SSF5531589'),
('+918271138986', 'SSF4683316'),
('+918873979250', 'SSF4172469'),
('+918209190205', 'SSF4963251'),
('+918521889563', 'SSF4173094'),
('+918298543099', 'SSF4038727'),
('+918409531124', 'SSF4715485'),
('+918005961829', 'SSF4215067'),
('+918815785162', 'SSF4172811'),
('+918305883244', 'SSF4143038'),
('+918825207359', 'SSF4310419'),
('+918049488843', 'SID951375920575'),
('+919691156922', 'SSF4569390'),
('+919525157176', 'SSF4341923'),
('+919799423108', 'SSF2869921'),
('+919664004939', 'SSF3981596'),
('+919153074886', 'SSF4111268'),
('+919117014238', 'SSF4264729'),
('+919509352801', 'SSF4275243'),
('+919835539663', 'SSF2781342'),
('+919693699493', 'SSF4128117'),
('+919430817995', 'SSF4762121'),
('+919060275240', 'SSF4128068'),
('+919631118047', 'SSF5335207'),
('+919199553732', 'SID951375524879'),
('+919060643476', 'SSF4198812'),
('+919608499121', 'SSF4106304'),
('+919279158340', 'SSF4507091'),
('+919234291757', 'SSF4267397'),
('+919798869319', 'SSF4696287'),
('+919936035035', 'SSF4194022'),
('+919501458347', 'SSF4191202'),
('+919523470626', 'SSF4225270'),
('+919939288865', 'SSF3708329'),
('+919507207628', 'SSF4095844'),
('+919153577691', 'SSF4335745'),
('+919031090349', 'SSF4162096'),
('+919065707524', 'SSF4195915'),
('+919142219879', 'SSF4099583'),
('+919565434051', 'SSF4196203'),
('+919262366542', 'SSF4130153'),
('+919973163825', 'SSF4123591'),
('+919576773200', 'SSF4111724'),
('+919312471540', 'SID951376026576'),
('+919616372226', 'SSF4198335'),
('+919040471775', 'SSF3000941'),
('+917050397800', 'SSF5057361'),
('+916201758325', 'SSF5658559'),
('+917018555383', 'SSF5556452'),
('+917320927343', 'SSF5887030'),
('+917766911034', 'SSF5586965'),
('+917235851526', 'SSF5832091'),
('+918298121041', 'SSF5243651'),
('+918521004164', 'SSF4865516'),
('+918521875160', 'SSF5782685'),
('+919199894677', 'SSF5599245'),
('+919608951600', 'SSF5925099'),
('+919060718680', 'SSF5435550'),
('+919548329048', 'SSF4635333'),
('+919905924653', 'SSF5684835'),
('+919334693414', 'SSF5194227'),
('+917814612856', 'SSF5854113'),
('+917033005194', 'SSF4966627'),
('+917257839472', 'SSF5552770'),
('+918789740596', 'SSF5293651'),
('+918745002770', 'SSF5365534'),
('+919263552922', 'SSF4405969'),
('+916203373107', 'SSF4109369'),
('+916376740989', 'SSF4472342'),
('+916377671969', 'SSF4270032'),
('+916376283849', 'SSF3260222'),
('+916284395389', 'SID951375692580'),
('+916378114216', 'SSF4069846'),
('+916307986771', 'SSF4021689'),
('+917849857102', 'SSF4073869'),
('+917357122716', 'SSF4005937'),
('+917970446721', 'SSF4085590'),
('+917739218186', 'SSF4635753'),
('+917258856743', 'SSF4524188'),
('+917325083584', 'SSF3975270'),
('+917357168231', 'SSF3943599'),
('+917765032366', 'SSF4618154'),
('+917394939529', 'SSF4009950'),
('+917023225191', 'SSF4115453'),
('+917426808654', 'SSF4058724'),
('+917050199336', 'SSF4386463'),
('+917257924071', 'SSF4057735'),
('+917209156023', 'SSF4508195'),
('+917737356755', 'SSF4049499'),
('+917633833073', 'SSF3953356'),
('+917737009235', 'SSF3165991'),
('+917976902058', 'SSF4091325'),
('+917006451608', 'SID951375975316'),
('+917877475394', 'SSF3934202'),
('+917061355200', 'SSF2993423'),
('+918824829335', 'SSF2832893'),
('+918619590283', 'SSF4058272'),
('+918529219370', 'SSF4132294'),
('+918306181090', 'SSF4158024'),
('+918318585603', 'SSF3697432'),
('+918209760356', 'SSF4199082'),
('+918871634414', 'SSF3933680'),
('+918306290538', 'SSF4031936'),
('+918948298233', 'SSF4075143'),
('+918409877727', 'SSF4056138'),
('+918290341372', 'SSF4089094'),
('+918434765829', 'SSF4117797'),
('+918839857557', 'SSF4062717'),
('+918690084741', 'SSF3910998'),
('+918603998324', 'SSF4043953'),
('+918707070788', 'SSF2364965'),
('+919153904315', 'SSF4000922'),
('+919319915728', 'SSF4139555'),
('+919001938652', 'SSF4156177'),
('+919579514981', 'SID951374737745'),
('+919664245838', 'SID951376065609'),
('+919954818828', 'SID951375089580'),
('+919693165721', 'SSF3332827'),
('+919324741717', 'SSF4629085'),
('+919351117539', 'SSF3510671'),
('+919508660348', 'SSF3898226'),
('+919257843442', 'SSF4011039'),
('+919303722077', 'SSF4192151'),
('+919640854656', 'SID951376122818'),
('+919060736096', 'SSF3966726'),
('+919770866578', 'SSF2908572'),
('+919358955471', 'SSF4147822'),
('+919509986511', 'SSF3913772'),
('+919793788618', 'SSF4000049'),
('+919341420526', 'SSF4492120'),
('+919661307809', 'SSF4387025'),
('+919636490710', 'SSF4042992'),
('+916204900813', 'SSF5820542'),
('+918795366241', 'SSF5356091'),
('+918660341935', 'SSF5813194'),
('+919235678425', 'SSF4844474'),
('+917050913809', 'SSF4963902'),
('+918074041748', 'SSF4873404'),
('+918409919336', 'SSF5614205'),
('+918824620564', 'SSF5622879'),
('+918582953404', 'SSF5940055'),
('+919135667133', 'SSF5194565'),
('+919334692764', 'SSF5595392'),
('+919918328410', 'SSF4999547'),
('+916334646494', 'SID951374718293'),
('+916367210922', 'SSF3953531'),
('+916263444559', 'SSF4203528'),
('+916394842138', 'SSF3586925'),
('+917357358871', 'SSF4411691'),
('+917683484549', 'SSF2620189'),
('+917737512475', 'SSF3789170'),
('+917004296009', 'SSF3754898'),
('+917033941035', 'SSF2864875'),
('+917033060191', 'SSF3746727'),
('+917597947362', 'SSF3682023'),
('+917230992716', 'SSF3519604'),
('+917916494948', 'SSF3896831'),
('+917004598810', 'SSF2776919'),
('+917994949959', 'SSF3698787'),
('+917627097293', 'SSF2571481'),
('+917426821064', 'SSF3614113'),
('+918949543566', 'SSF3801350'),
('+918815859307', 'SSF3708542'),
('+918966048533', 'SSF3540276'),
('+918255447745', 'SSF3669768'),
('+918965321407', 'SSF3837960'),
('+918209206045', 'SSF3829444'),
('+918831452212', 'SSF2859298'),
('+918056856087', 'SSF3298564'),
('+918890858358', 'SSF3695309'),
('+918932684849', 'SSF3778671'),
('+918852015758', 'SSF3739065'),
('+918741919586', 'SSF3019170'),
('+918754876948', 'SSF3535966'),
('+918233474659', 'SSF4343387'),
('+918559962832', 'SSF3857178'),
('+918784545464', 'SSF3765251'),
('+918889564648', 'SSF3657703'),
('+919675724840', 'SID951374498450'),
('+919632448665', 'SSF3708679'),
('+919854846464', 'SSF3577327'),
('+919627554865', 'SSF3593202'),
('+919680264036', 'SSF3590074'),
('+919471400730', 'SSF3688609'),
('+919976779797', 'SSF3756291'),
('+919784155414', 'SSF3539739'),
('+919001633223', 'SSF2803448'),
('+919689487358', 'SSF3558206'),
('+919521758539', 'SSF3676984'),
('+919122699330', 'SSF3801587'),
('+919610976576', 'SSF3748473'),
('+919079915682', 'SSF4086205'),
('+919672473296', 'SSF3653150'),
('+919958465849', 'SSF3624470'),
('+919166767245', 'SSF3776922'),
('+916378162358', 'SSF3332545'),
('+916204732479', 'SSF3614660'),
('+917739612600', 'SSF4242904'),
('+917481925223', 'SSF3368906'),
('+917761368611', 'SSF3386949'),
('+917468626545', 'SSF3235718'),
('+917667632763', 'SSF3827938'),
('+917877338207', 'SSF3751971'),
('+917357395847', 'SSF3745058'),
('+918489248635', 'SSF3337008'),
('+918523698788', 'SSF3454564'),
('+918559635884', 'SSF3173611'),
('+918787648767', 'SSF3498096'),
('+918824990751', 'SSF3788910'),
('+918809696162', 'SSF3827844'),
('+918078615010', 'SSF3847889'),
('+918268625956', 'SSF3767447'),
('+918056565656', 'SSF3767446'),
('+918529071939', 'SSF2867654'),
('+918817189884', 'SID951375769125'),
('+918982771764', 'SSF3828607'),
('+918619586472', 'SSF3705465'),
('+918555863887', 'SSF3463000'),
('+919262892128', 'SSF3735280'),
('+919632841457', 'SSF3431488'),
('+919858767646', 'SSF3542547'),
('+919303829248', 'SSF4091071'),
('+919587162235', 'SSF3897258'),
('+919672054686', 'SSF3046114'),
('+919329093880', 'SSF3969188'),
('+917488157102', 'SSF4255352'),
('+916268539721', 'SSF3294124'),
('+916351548630', 'SSF3250531'),
('+917421536571', 'SSF3189830'),
('+917878165500', 'SSF3068155'),
('+918865152545', 'SSF3236705'),
('+919122681592', 'SSF3256410'),
('+919771958013', 'SSF3247238'),
('+919304214814', 'SSF2911565'),
('+919875268103', 'SSF3333172'),
('+919884588598', 'SSF3313561'),
('+916290376978', 'SSF4970008'),
('+916209925235', 'SSF2785619'),
('+916203401250', 'SSF3084856'),
('+917414095980', 'SSF3067851'),
('+917852010765', 'SSF3650703'),
('+918199833592', 'SSF3242839'),
('+919981786050', 'SSF3233282'),
('+919509052028', 'SSF3195131'),
('+919608101417', 'SSF5931701'),
('+919006433249', 'SSF5953270'),
('+916398874917', 'SSF6024694'),
('+917701876357', 'SSF6024713'),
('+918294771758', 'SSF5105002'),
('+917808587265', 'SSF5552604'),
('+917379698299', 'SSF5676132'),
('+916378573971', 'SSF2478329'),
('+919166595784', 'SSF2936007'),
('+917070213069', 'SID951372971953'),
('+919770186210', 'CID213801652'),
('+918889504362', 'SID951375352578'),
('+918579986311', 'SID951375929390'),
('+918530050702', 'SID951375291732'),
('+918871191429', 'SID951375306856'),
('+919631873828', 'SID951375249894'),
('+917482826684', 'SID951376101471'),
('+918651091324', 'SSF2884946'),
('+919060679234', 'SSF2450319'),
('+919334519019', 'SSF2749782'),
('+917320862932', 'SSF5634130'),
('+919798569695', 'SSF5552027'),
('+919793523024', 'SSF5630505'),
('+916202206389', 'SSF5538334'),
('+916268189469', 'SSF4881811'),
('+916201390578', 'SSF4611382'),
('+916201271982', 'SSF5559340'),
('+916263472510', 'SSF3385490'),
('+916378575538', 'SSF4437320'),
('+916396118679', 'SSF5549648'),
('+916206240491', 'SSF3371295'),
('+916363834161', 'SSF2814223'),
('+916367585507', 'SSF4935292'),
('+916377983735', 'SSF3552923'),
('+916203312150', 'SSF5871770'),
('+916205514962', 'SSF5288781'),
('+917479881950', 'SSF4957135'),
('+917780086815', 'SSF4725221'),
('+917717780379', 'SSF4935053'),
('+917782862754', 'SSF5182534'),
('+917679818829', 'SSF5061440'),
('+917250482454', 'SID951375388630'),
('+917294863044', 'SSF4932822'),
('+917856855022', 'SSF5230003'),
('+917015587119', 'SSF3302171'),
('+917091144117', 'SSF3603111'),
('+917033469993', 'SSF4771089'),
('+917970822268', 'SSF4886799'),
('+917070191374', 'SSF3250085'),
('+917870708132', 'SSF5169105'),
('+917632049958', 'SSF4953743'),
('+917321884300', 'SSF4953809'),
('+917634049683', 'SSF4934586'),
('+917004519034', 'SSF4991167'),
('+917061193064', 'SSF5061253'),
('+917607791025', 'SSF2876956'),
('+917439864202', 'SSF5135779'),
('+917033198741', 'SSF4741497'),
('+917633962884', 'SSF4950507'),
('+917763022499', 'SSF4807929'),
('+917462803083', 'SSF5114901'),
('+917489706612', 'SSF4941863'),
('+917033942982', 'SSF4949042'),
('+917479655123', 'SSF5006960'),
('+917974760306', 'SSF4934599'),
('+917479697131', 'SSF4875295'),
('+917898421190', 'SSF4081534'),
('+918294785770', 'SSF3060984'),
('+918463068056', 'SSF5326869'),
('+918227953619', 'SSF5383441'),
('+918409605794', 'SSF3899939'),
('+918434783441', 'SSF5126916'),
('+918271328138', 'SSF5209170'),
('+918051130937', 'SSF4956982'),
('+918002754023', 'SSF5191649'),
('+918340219620', 'SSF5553211'),
('+918271250524', 'SSF3354731'),
('+918793770249', 'SSF4927652'),
('+918084540824', 'SSF4879867'),
('+918407958207', 'SSF4858974'),
('+918369376392', 'SSF4961727'),
('+918541933214', 'SSF5087130'),
('+918696435655', 'SSF5051789'),
('+918949618019', 'SSF5265398'),
('+918709504210', 'SSF5000974'),
('+918120576484', 'SSF2361104'),
('+918340602178', 'SSF4958385'),
('+918102111655', 'SSF3579403'),
('+918529600264', 'SSF4845027'),
('+918298798181', 'SSF5134713'),
('+918294692827', 'SSF5026080'),
('+918271287312', 'SSF4967474'),
('+919142900867', 'SSF6153737'),
('+919343642321', 'SSF3478987'),
('+919301603476', 'SSF3437306'),
('+919060179620', 'SSF4528181'),
('+919507421316', 'SSF3052985'),
('+919279943014', 'SSF4890311'),
('+919341433955', 'SSF4979577'),
('+919667250512', 'SID951375330469'),
('+919111965539', 'SSF5048880'),
('+919263801657', 'SSF5577240'),
('+919113365750', 'SSF4925820'),
('+919028171948', 'SSF4944387'),
('+919303888931', 'SSF3366890'),
('+919162533305', 'SSF5186736'),
('+919508889635', 'SSF6121227'),
('+919693106144', 'SSF3987825'),
('+919262379679', 'SSF4955907'),
('+919801400639', 'SSF4991260'),
('+919065027838', 'SSF4931037'),
('+919156942702', 'SSF4997043'),
('+919142618274', 'SSF4995603'),
('+919328417498', 'SSF5188945'),
('+919163305365', 'SSF2795129'),
('+919241238239', 'SSF4953759'),
('+919835953562', 'SSF4957929'),
('+919973098150', 'SSF4990760'),
('+919234096013', 'SSF4962252'),
('+919950777104', 'SSF4962264'),
('+919546514737', 'SSF5117571'),
('+919343985647', 'SSF4885305'),
('+919263969787', 'SSF5536652'),
('+919334886338', 'SSF4950454'),
('+919065074114', 'SSF5006132'),
('+919534080474', 'SSF4030697'),
('+919065962869', 'SSF4970165'),
('+919303382032', 'SSF4925633'),
('+919340814248', 'SSF5096584'),
('+916207273907', 'SSF5791841'),
('+919341964452', 'SSF5287134'),
('+919835838045', 'SSF5313253'),
('+919905771776', 'SSF3638756'),
('+919631260174', 'SSF5649096'),
('+919608996654', 'SSF5060094'),
('+919669565959', 'SID951374525852'),
('+919934472890', 'SID2125706778'),
('+916266754665', 'SSF5322442'),
('+917740895245', 'SSF4801743'),
('+917727056522', 'SSF4815715'),
('+917489182602', 'SSF4921801'),
('+917439559685', 'SSF5315519'),
('+917631229291', 'SSF5118552'),
('+917067177687', 'SSF3817136'),
('+918252316772', 'SSF5079380'),
('+918969141180', 'SSF5182830'),
('+918969643511', 'SSF4983856'),
('+918824049243', 'SSF4825197'),
('+919304604189', 'SSF2800986'),
('+919341936973', 'SSF3406575'),
('+919155469500', 'SSF3937877'),
('+919934568267', 'SSF4796323'),
('+919153869332', 'SSF5079731'),
('+918521884543', 'SID2125011163'),
('+916287145663', 'SSF4617052'),
('+916202852469', 'SSF5308027'),
('+916304600698', 'SSF5015419'),
('+917857068335', 'SSF5056595'),
('+917587261586', 'SSF4714737'),
('+917294868362', 'SSF3908853'),
('+917294962465', 'SSF5028069'),
('+917859052667', 'SSF4737953'),
('+917250881831', 'SSF5077846'),
('+917389864347', 'SSF4991352'),
('+917067970931', 'SSF4615601'),
('+917061022725', 'SSF5250953'),
('+918000910267', 'SSF5071203'),
('+918292350241', 'SSF4189815'),
('+918252538189', 'SSF5248835'),
('+918541827406', 'SSF4538296'),
('+918540910776', 'SSF4687917'),
('+918294318718', 'SSF2581375'),
('+919174549176', 'SSF5006311'),
('+919122885763', 'SSF3384542'),
('+919801778154', 'SSF4188559'),
('+919955614862', 'SSF4868299'),
('+919523783567', 'SSF4568028'),
('+919905709142', 'SSF2940061'),
('+919279125322', 'SSF4863514'),
('+919655669669', 'SID951374824664'),
('+919111736501', 'SSF4543285'),
('+919102032092', 'SSF4790287'),
('+918092408169', 'SSF5237866'),
('+919508197842', 'SSF5469636'),
('+919793686832', 'SSF5359435'),
('+919546940287', 'SSF4375629'),
('+917009023726', 'SSF5789463'),
('+916350540561', 'SSF5670431'),
('+917491025096', 'SSF6117354'),
('+917050035181', 'SSF5358120'),
('+917307242694', 'SSF5749496'),
('+917870261539', 'SSF4760740'),
('+918539809580', 'SSF6125061'),
('+918873286351', 'SSF5467156'),
('+918972931170', 'SSF5774045'),
('+918757222344', 'SSF5751203'),
('+919155750367', 'SSF6116805'),
('+917631162091', 'SSF6050507'),
('+917827521160', 'SSF5394130'),
('+917367975690', 'SSF5712045'),
('+918445036302', 'SSF5760240'),
('+919199191886', 'SSF5708331'),
('+916287057100', 'SSF4132480'),
('+916299179067', 'SSF4204166'),
('+916835698053', 'SID951375142910'),
('+916306626295', 'SSF4178650'),
('+916268965689', 'SSF4109775'),
('+916392906582', 'SSF4112775'),
('+916232358722', 'SSF4389747'),
('+916260628078', 'SSF3056133'),
('+917209537505', 'SSF4109728'),
('+917654741746', 'SSF4252303'),
('+917656018265', 'SSF3103448'),
('+917717796603', 'SSF2588650'),
('+917061782919', 'SSF5514936'),
('+917033876389', 'SSF5412776'),
('+917355186242', 'SSF4219451'),
('+917999522551', 'SSF4223796'),
('+917209549144', 'SSF4368674'),
('+917296010565', 'SSF4240278'),
('+917970751688', 'SSF4148376'),
('+917296014366', 'SSF3123688'),
('+918210337436', 'SSF4109455'),
('+918521035825', 'SID951373868731'),
('+918824361654', 'SSF4188635'),
('+918797181441', 'SSF4670365'),
('+918839289525', 'SSF4361027'),
('+918271496392', 'SID951372980203'),
('+918002065674', 'SSF2882801'),
('+918521394329', 'SSF4636680'),
('+918092898596', 'SSF3357756'),
('+918404826054', 'SSF4165311'),
('+918144083797', 'SSF4530729'),
('+918292208587', 'SSF4217141'),
('+918817167606', 'SSF4108613'),
('+919340402092', 'SSF4439293'),
('+919588684986', 'SID951375907568'),
('+919673646349', 'SID951374850764'),
('+919630521383', 'SSF4221248'),
('+919667827874', 'SSF4111286'),
('+919142128968', 'SSF4072876'),
('+919153932503', 'SSF4190162'),
('+919523561805', 'SID951376188476'),
('+919661507807', 'SSF5457522'),
('+919102188097', 'SSF3273026'),
('+919241880589', 'SSF4157764'),
('+919199562005', 'SSF4170142'),
('+919525769854', 'SSF4191661'),
('+919523732493', 'SSF4158515'),
('+919110136099', 'SSF4185611'),
('+919523175233', 'SSF4341462'),
('+919546887288', 'SSF4129069'),
('+919523229612', 'SSF4226549'),
('+919693467896', 'SSF4226576'),
('+919771981419', 'SSF4141606'),
('+917347590451', 'SSF5486997'),
('+917033214026', 'SSF5874866'),
('+917347753306', 'SSF5752765'),
('+917858819193', 'SSF5437640'),
('+917564850308', 'SSF5548053'),
('+918858712168', 'SSF5650364'),
('+919905491105', 'SSF5620547'),
('+919006527595', 'SSF5838665'),
('+917310201713', 'SSF5880087'),
('+919693538377', 'SSF5815773'),
('+919229040719', 'SSF4389426'),
('+916745284354', 'SSF3259674'),
('+916265659495', 'SID951373132604'),
('+916299319308', 'SSF4125952'),
('+916207099235', 'SID2125274256'),
('+917041667303', 'SSF2549533'),
('+917023248320', 'SSF4145794'),
('+917646977692', 'SSF4059293'),
('+917410929079', 'SSF4370916'),
('+917489495127', 'SSF4059432'),
('+917425810422', 'SSF4483321'),
('+917723045580', 'SSF3956894'),
('+917667435891', 'SSF4513652'),
('+917479629798', 'SSF3915553'),
('+917557786926', 'SSF4334104'),
('+917463978952', 'SSF4121863'),
('+917878570446', 'SSF3965856'),
('+917425869363', 'SSF2399636'),
('+917082067243', 'SSF2876776'),
('+917632073306', 'SSF4349810'),
('+917643093125', 'SSF4524178'),
('+917319604715', 'SSF4025924'),
('+918210306692', 'SSF4565635'),
('+918668963463', 'SID951376121951'),
('+918302596450', 'SSF4095841'),
('+918527612946', 'SSF4100692'),
('+918252360275', 'SSF4406535'),
('+918824366527', 'SID951375106895'),
('+918789903448', 'SSF4006377'),
('+918409162847', 'SSF4468630'),
('+918809484167', 'SSF3980197'),
('+918707007878', 'SSF2364966'),
('+918292581526', 'SSF4121967'),
('+918085045266', 'SSF4113645'),
('+919631190965', 'SSF4524813'),
('+919955034258', 'SSF3021042'),
('+919772394191', 'SSF4030180'),
('+919661147488', 'SSF3661595'),
('+919006200119', 'SSF3209540'),
('+919113763334', 'SSF4146552'),
('+919883440450', 'SSF4487676'),
('+919905071766', 'SSF3012568'),
('+919661859054', 'SSF4479798'),
('+919771054552', 'SSF4177103'),
('+919608298022', 'SSF4012649'),
('+919523492721', 'SSF4511785'),
('+919929062829', 'SSF4053897'),
('+919256909972', 'SSF3959659'),
('+919631125837', 'SSF4606262'),
('+919263748458', 'SSF4226518'),
('+919602228347', 'SSF3982319'),
('+919123294852', 'SSF4039432'),
('+919110101405', 'SSF3938418'),
('+919024292227', 'SSF3982221'),
('+919079855326', 'SSF3994336'),
('+919693915882', 'SSF4121999'),
('+919599824062', 'SSF3903568'),
('+919324495387', 'SSF4332259'),
('+917739072378', 'SSF5820768'),
('+917347432403', 'SSF4508135'),
('+918797174441', 'SSF5820525'),
('+918858027846', 'SSF6192832'),
('+917050862686', 'SSF5669753'),
('+919234263352', 'SSF5535019'),
('+917756879920', 'SSF5440260'),
('+919354434093', 'SSF5419422'),
('+917518077680', 'SSF5848599'),
('+918084250258', 'SSF5528387'),
('+918676087875', 'SSF5318399'),
('+916577845659', 'SSF3764644'),
('+916134648444', 'SSF2502229'),
('+917631459168', 'SSF3618355'),
('+917804097469', 'SSF3683384'),
('+917048057588', 'SSF3565859'),
('+917976578797', 'SSF2893635'),
('+917835816879', 'SSF2349016'),
('+917494064626', 'SSF4064731'),
('+918784543464', 'SSF3629542'),
('+918286588845', 'SSF3280930'),
('+918233469082', 'SSF3861944'),
('+919658472131', 'SSF2878659'),
('+919764994464', 'SSF3587684'),
('+919352651490', 'SSF2736246'),
('+919889867688', 'SSF3690495'),
('+919142846153', 'SSF3598761'),
('+919875431619', 'SSF3577370'),
('+919616494848', 'SSF3711909'),
('+919724515515', 'SSF3584897'),
('+919637655757', 'SSF3609710'),
('+919129375267', 'SSF3791240'),
('+919963247896', 'SID951375492210'),
('+919548495926', 'SSF3805309'),
('+919610339965', 'SSF3510432'),
('+919494949494', 'SSF3677350'),
('+919929365658', 'SSF3655084'),
('+916367208994', 'SSF3661321'),
('+916464649499', 'SSF3404633'),
('+917296053678', 'SSF3635614'),
('+917296465454', 'SSF3340990'),
('+917488562460', 'SSF3452858'),
('+918858885588', 'SSF3482873'),
('+918053511348', 'SSF3502297'),
('+918554447888', 'SSF3684034'),
('+918523987256', 'SSF3411142'),
('+918956352536', 'SSF3555489'),
('+918254554548', 'SSF3306568'),
('+918587555888', 'SSF3372876'),
('+919765421548', 'SSF3505078'),
('+919351075487', 'SSF3330171'),
('+919635872588', 'SSF3420632'),
('+919608970945', 'SSF3483816'),
('+919767554497', 'SSF3458620'),
('+919854867673', 'SSF3641426'),
('+919324853580', 'SSF3732429'),
('+919206247120', 'SSF3756883'),
('+919828375449', 'SSF3407523'),
('+919066735726', 'SID951376174989'),
('+916206733945', 'SSF5483528'),
('+916350689797', 'SSF3321526'),
('+917027660270', 'SSF3161135'),
('+918085976900', 'SSF3572291'),
('+919764354884', 'SSF3322265'),
('+919680310892', 'SSF3311240'),
('+919373848404', 'SSF3147434'),
('+919764645482', 'SSF3307594'),
('+918092330485', 'SSF4864360'),
('+919241399842', 'SSF5239787'),
('+917023388537', 'SSF2964760'),
('+917737353984', 'SSF3632502'),
('+917737393695', 'SSF2676049'),
('+917737344583', 'SSF3121522'),
('+918168757923', 'SSF3208659'),
('+918619508912', 'SSF3632453'),
('+919798901905', 'SSF6040404'),
('+919122550582', 'SSF5647107'),
('+918092753056', 'SSF4855602'),
('+919155584351', 'SSF5632361'),
('+918252375286', 'SSF5898594'),
('+919263313425', 'SSF5190643'),
('+916381852150', 'SSF4998115'),
('+918290715031', 'SSF2980000'),
('+919688466446', 'SSF3461387'),
('+919684297866', 'SSF3460915'),
('+919065424672', 'SID951375941423'),
('+919528862797', 'SSF4361155'),
('+919257370133', 'SID951374953061'),
('+918852824408', 'SSF2424049'),
('+916267468252', 'SSF3265628'),
('+919116570361', 'SSF4072866'),
('+917805017055', 'SID951375290191'),
('+919977050513', 'SSF3592991'),
('+918650431020', 'SSF4823031'),
('+917739857672', 'SSF3489784'),
('+918078695612', 'SID951375774281'),
('+917415070886', 'SSF2315716'),
('+916378979119', 'SID951374853724'),
('+918905524639', 'SSF3981629'),
('+919334635120', 'SSF2811042'),
('+917218599646', 'SSF4549437'),
('+919153095038', 'SSF3208962'),
('+916268026164', 'SSF3669444'),
('+917481945005', 'SSF5689753'),
('+919508651322', 'SSF5568949'),
('+916260584636', 'SSF4334389'),
('+918409398068', 'SSF4428211'),
('+919352390917', 'SID951375441338'),
('+919903562870', 'SID951373219501'),
('+916232523440', 'SID2125690021'),
('+917862050244', 'SID951374608896'),
('+917828333148', 'SID951373382089'),
('+919257186496', 'SSF5201417'),
('+919511349116', 'SID951375021408'),
('+918677072868', 'SSF5865133'),
('+918745125356', 'SSF3135591'),
('+917771880164', 'SSF5303840'),
('+918109629119', 'SSF3061133'),
('+917068049248', 'SSF5050808'),
('+917814014308', 'SSF3265505'),
('+918827512513', 'SID951374935486'),
('+916287157172', 'SSF2872414'),
('+919131521707', 'SSF3015593'),
('+919166086568', 'SID951375722056'),
('+917323081403', 'SSF2576907'),
('+917073708751', 'SID951374379978'),
('+917294083892', 'SID951374876315'),
('+919770181431', 'SID951374750488'),
('+919651609785', 'SSF5732248'),
('+916263101231', 'SID951372969385'),
('+917415072339', 'SID951373111028'),
('+919241792047', 'SSF6248611'),
('+918094852065', 'SID951375686535'),
('+918077499337', 'SSF6152077'),
('+917520515029', 'SSF5542498'),
('+916388672512', 'SSF5163233'),
('+918239770219', 'SSF3994557'),
('+918009856455', 'SSF3115572'),
('+918709961867', 'SSF6102470'),
('+918294670205', 'SSF3761643'),
('+918922891398', 'SSF6277407'),
('+916260587464', 'SID951373280032'),
('+918109875822', 'CID129501204'),
('+918651943633', 'SSF5561532'),
('+916206647177', 'SSF5322981'),
('+919026651195', 'SSF5623234'),
('+919497664988', 'SID951374543417'),
('+919691266503', 'SSF3534804'),
('+918603412902', 'SSF5330444'),
('+919523583584', 'SSF6139390'),
('+916378450802', 'SSF4588172'),
('+919113763030', 'SSF2493893'),
('+917818079342', 'SSF4695161'),
('+916261751464', 'SID951375257872'),
('+919162587760', 'SSF4476768'),
('+917999712421', 'SSF4408357'),
('+918780225402', 'SSF4268000'),
('+917627035638', 'SID951375790810'),
('+919302033742', 'SID2125697583'),
('+919552420997', 'SSF5985765'),
('+919571547135', 'SSF2944343'),
('+919616768190', 'SSF6249539'),
('+917019516314', 'SSF6497615'),
('+917470393815', 'SSF3650965'),
('+918949011723', 'SSF2634342'),
('+919755224484', 'CID135300333'),
('+917367810232', 'SID951375510209'),
('+919098253186', 'SSF3485992'),
('+918002271809', 'SID951373860729'),
('+919341284759', 'SSF6097032'),
('+919608851572', 'SSF4371941'),
('+918102574619', 'SID951375362011'),
('+919546142677', 'SID951374258143'),
('+919628098995', 'SSF2841091'),
('+918445341819', 'SSF5973978'),
('+919334213158', 'SSF3573419'),
('+917091460377', 'SSF3142169'),
('+916005164974', 'SSF2934591'),
('+919770515876', 'SSF3025188'),
('+919006803641', 'SID951375411250'),
('+918103488099', 'SSF2433670'),
('+918449505525', 'SSF5441691'),
('+918770891265', 'SSF4010722'),
('+917584584574', 'SSF3576398'),
('+919366819967', 'SSF6047649'),
('+919752323008', 'SSF4042442'),
('+916266284963', 'CID076210936'),
('+919661647093', 'SID951375612832'),
('+917739372650', 'SSF4872183'),
('+918736057159', 'SSF2901424'),
('+918349900234', 'SID2125175171'),
('+919784060854', 'SID951375267148'),
('+919241517789', 'SSF4973453'),
('+919113126296', 'SSF3639440'),
('+919060287561', 'SSF3024615'),
('+918239364423', 'SSF2756637'),
('+918878077607', 'SID951373524780'),
('+916388547247', 'SSF5429423'),
('+917073114344', 'SID951374555407'),
('+916388181276', 'SSF4952001'),
('+919575134237', 'SID951373227103'),
('+917800559580', 'SSF2567748'),
('+919024441920', 'SSF3590455'),
('+918757409469', 'SSF2640497'),
('+917033142200', 'SSF5510385'),
('+918905831135', 'SSF4291943'),
('+917023335620', 'SSF4196636'),
('+918519000171', 'SSF3451976'),
('+917765881449', 'SSF3187934'),
('+919878784513', 'SSF3694501'),
('+919166879763', 'SID951375295518'),
('+918528914306', 'SSF6237380'),
('+919516589541', 'SSF5718364'),
('+919646664665', 'SID951375265699'),
('+919065049949', 'SSF4145351'),
('+919977501248', 'SID951373772687'),
('+918506009598', 'SSF6174062'),
('+916204267467', 'SSF5946537'),
('+916395521848', 'SSF3624493'),
('+917357372720', 'SSF3361902'),
('+917877434765', 'SSF3419514'),
('+917489281308', 'CID093807167'),
('+917379699200', 'SSF5057135'),
('+918103269956', 'SID951375005371'),
('+918788236415', 'SSF3496549'),
('+919875873929', 'SSF3865755'),
('+917869722598', 'SSF3596533'),
('+919835413753', 'SSF6095155'),
('+917726932367', 'SSF2767224'),
('+919131261939', 'SID951374551723'),
('+919005994619', 'SSF5385272'),
('+916262740567', 'SID951373274153'),
('+918955023915', 'SID951374869222'),
('+917722917711', 'SID951375626948'),
('+916376659184', 'SID951376043617'),
('+919464648789', 'SSF3352883'),
('+919554814197', 'SID951376078477'),
('+918936093532', 'SSF2329881'),
('+916264720434', 'SID2125334314'),
('+917067494649', 'SID951374879583'),
('+918579881626', 'SSF4833484'),
('+918854455565', 'SID951374618397'),
('+916206484301', 'SID951376135885'),
('+918602461858', 'SID2125075146'),
('+917209411549', 'SID2125254209'),
('+919358198411', 'SSF2681830'),
('+917073855127', 'SSF3701259'),
('+917354733745', 'SSF4024826'),
('+916262365480', 'SID951375706020'),
('+918294259034', 'SSF6213888'),
('+917989666060', 'SSF4277578'),
('+916268132754', 'CID050401371'),
('+919528748972', 'SSF3284578'),
('+919661343883', 'SSF5394432'),
('+917461880950', 'SSF4613571'),
('+917479746910', 'SID951376072488'),
('+919229587466', 'SSF2554967'),
('+917352985114', 'SID951375668293'),
('+917462830201', 'SSF5905073'),
('+919244738035', 'SID951372895797'),
('+919229654026', 'SSF6268548'),
('+919608384790', 'SID951375119682'),
('+917805040487', 'SID27066'),
('+919600128072', 'SID951374737744'),
('+919279123246', 'SSF6241519'),
('+918176046031', 'SSF2736463'),
('+916202999146', 'SSF5540050'),
('+917856964974', 'SSF5292845'),
('+917633969177', 'SSF5392953'),
('+917482071150', 'SSF5438775'),
('+917667045121', 'SSF5544403'),
('+917295845103', 'SSF5501536'),
('+917709032673', 'SSF2345957'),
('+918676083801', 'SSF5392946'),
('+918085176140', 'SSF4933788'),
('+918252783374', 'SSF5350960'),
('+918874574685', 'SSF2302203'),
('+918349832885', 'SSF3190042'),
('+918235718759', 'SSF5124421'),
('+919102121721', 'SSF5380551'),
('+919905968806', 'SSF4941019'),
('+919798658469', 'SSF4943520'),
('+919279228296', 'SSF5424863'),
('+919835908626', 'SSF5249373'),
('+919060731627', 'SSF5376723'),
('+919253035916', 'SSF5466942'),
('+917078208251', 'SSF5404593'),
('+917779898706', 'SSF6251175'),
('+918084745894', 'SSF5991143'),
('+919599611426', 'SSF6000094'),
('+917836098978', 'SSF5839554'),
('+918210003949', 'SSF5533676'),
('+919155995299', 'SSF5839714'),
('+917986567466', 'SSF6083119'),
('+918168218309', 'SSF5757896'),
('+918601357040', 'SSF5505567'),
('+917724812870', 'SID951374410535'),
('+917484888937', 'SID951375037201'),
('+918083291582', 'SID951376126298'),
('+918235174265', 'SSF2763902'),
('+916207767568', 'SSF5129871'),
('+916287816247', 'SSF4975413'),
('+916206612474', 'SSF5234637'),
('+916299569655', 'SSF5084678'),
('+916377772009', 'SSF3901936'),
('+916201258510', 'SSF5102948'),
('+916287169223', 'SSF4539614'),
('+916266168819', 'SSF5302170'),
('+916268295760', 'SSF3217331'),
('+917480055841', 'SSF5065118'),
('+917080607581', 'SSF4497806'),
('+917761923853', 'SSF5210504'),
('+917766072164', 'SSF4750936'),
('+917250867002', 'SSF5719241'),
('+917987915190', 'SSF4913906'),
('+917779817648', 'SSF4941125'),
('+917255810517', 'SSF5166895'),
('+917339711974', 'SSF5162003'),
('+917463010559', 'SSF5158339'),
('+917543093938', 'SSF3183336'),
('+917739745924', 'SSF4728670'),
('+917029022692', 'SSF4912596'),
('+917722900983', 'SSF5242097'),
('+917903445719', 'SSF4941076'),
('+917455891319', 'SSF4636863'),
('+917970793607', 'SSF4646296'),
('+917739142376', 'SSF2376236'),
('+917230961799', 'SSF2898745'),
('+917024858084', 'SSF4788122'),
('+917426853251', 'SSF4758065'),
('+917974537886', 'SSF5027400'),
('+918340246573', 'SSF5132467'),
('+918603914479', 'SSF5188649'),
('+918603217984', 'SSF2609853'),
('+918122705692', 'SSF5205285'),
('+918207315264', 'SSF5028077'),
('+918603540075', 'SSF3212256'),
('+918529321730', 'SSF3265313'),
('+918306065188', 'SSF4715114'),
('+918340720446', 'SID951375928302'),
('+918462951427', 'SSF3749108'),
('+918809945474', 'SSF5030879'),
('+918421531706', 'SSF5206123'),
('+918827017671', 'SSF4998548'),
('+918226069286', 'SSF4539508'),
('+918948868092', 'SSF4972232'),
('+919826105629', 'SSF5018398'),
('+919165862373', 'SSF4834916'),
('+919031227068', 'SSF5111314'),
('+919546625083', 'SSF5164901'),
('+919153712010', 'SSF4535072'),
('+919262880530', 'SSF5135403'),
('+919301722079', 'SSF5173878'),
('+919351865032', 'SSF4766374'),
('+919155243448', 'SSF5182718'),
('+919508456909', 'SSF4333878'),
('+919341741059', 'SSF4603646'),
('+919955545160', 'SSF5029641'),
('+919931591254', 'SSF5215065'),
('+919302114043', 'SSF4920932'),
('+919135031641', 'SSF5218995'),
('+919304452132', 'SSF5300980'),
('+919234381388', 'SSF5173874'),
('+919955121454', 'SSF4973083'),
('+919334780730', 'SSF4322092'),
('+919572371594', 'SSF5233340'),
('+918542035826', 'SSF5791792'),
('+917859070567', 'SSF5011430'),
('+918669766294', 'SSF4196427'),
('+918969563809', 'SSF5095539'),
('+916392595670', 'SSF4693298'),
('+916232401384', 'SSF4769884'),
('+916206190835', 'SSF4975537'),
('+916203215549', 'SSF4978565'),
('+917267845937', 'SSF4915190'),
('+917479790204', 'SSF4889822'),
('+917632090751', 'SSF4599759'),
('+917858985260', 'SSF3100752'),
('+917970783998', 'SSF3605257'),
('+917805993477', 'SSF3539895'),
('+917292931484', 'SSF3614008'),
('+917667558098', 'SSF4588505'),
('+917255054761', 'SSF4631680'),
('+917292841426', 'SSF4973978'),
('+917654627111', 'SSF4389358'),
('+917739479281', 'SSF3215969'),
('+917725848710', 'SSF4986965'),
('+917462909738', 'SID951374005759'),
('+917250270989', 'SSF4557511'),
('+917631190314', 'SSF4226254'),
('+917488838181', 'SSF2687967'),
('+917004718798', 'SSF4543311'),
('+917633847281', 'SID951374536714'),
('+918521191280', 'SSF5022193'),
('+918862962031', 'SSF4879481'),
('+918401157696', 'SSF4860574'),
('+918002746099', 'SSF4741684'),
('+918757730454', 'SSF2885971'),
('+918102457995', 'SSF3534427'),
('+918092379188', 'SSF4922154'),
('+918825388135', 'SSF5147050'),
('+918851249405', 'SSF4551723'),
('+918434922714', 'SSF4612310'),
('+918302439957', 'SSF4660716'),
('+918434612676', 'SSF4894756'),
('+918116326077', 'SID951376130058'),
('+918210975294', 'SSF4720352'),
('+918889477413', 'SSF4536021'),
('+918359814834', 'SSF4967592'),
('+919279466780', 'SSF4889531'),
('+919155614586', 'SSF3167482'),
('+919297701768', 'SSF4674453'),
('+919694536863', 'SID951375532528'),
('+919653172022', 'SSF4876544'),
('+919128134920', 'SSF4576043'),
('+919122562742', 'SSF4886691'),
('+919135903337', 'SSF4930879'),
('+919199585756', 'SSF4927429'),
('+919304289923', 'SSF4702801'),
('+919570973886', 'SSF4968741'),
('+919060678831', 'SSF4873502'),
('+919931059699', 'SSF3342551'),
('+919257743530', 'SSF4829847'),
('+919926157250', 'SSF5097449'),
('+919039970991', 'SSF4467412'),
('+919709916070', 'SSF4569312'),
('+919102146312', 'SSF4728630'),
('+919529142597', 'SSF4774140'),
('+919341329728', 'SSF2963052'),
('+919279761799', 'SSF4975274'),
('+918950869286', 'SSF5712953'),
('+918271759436', 'SSF5523896'),
('+919101800709', 'SSF5358115'),
('+918757374650', 'SSF3729868'),
('+916206450351', 'SSF6047027'),
('+916204222360', 'SSF5670879'),
('+917260876943', 'SSF5701744'),
('+917764811771', 'SSF5519825'),
('+918757724080', 'SSF6101397'),
('+918084191451', 'SSF5750487'),
('+918809805620', 'SSF5756484'),
('+918799810432', 'SSF5735356'),
('+918603940775', 'SSF4542447'),
('+919370698558', 'SSF6077717'),
('+919570549035', 'SSF5972800'),
('+919546237330', 'SSF5727097'),
('+919162245951', 'SSF5973209'),
('+919973283017', 'SSF5872367'),
('+919162613641', 'SSF5670582'),
('+916204811003', 'SSF4695089'),
('+916377521561', 'SSF5990879'),
('+917762926510', 'SSF5740822'),
('+917646053496', 'SSF5975729'),
('+917634090158', 'SSF5605594'),
('+917543869445', 'SSF5858306'),
('+917808634098', 'SSF5870296'),
('+917004624165', 'SSF5616372'),
('+918409451069', 'SSF4355341'),
('+918797078175', 'SSF5734104'),
('+918603293103', 'SSF5485990'),
('+918538962552', 'SSF5421352'),
('+918867734307', 'SSF5616446'),
('+919523337629', 'SSF5971083'),
('+919110918240', 'SSF5429381'),
('+919080866237', 'SSF5429765'),
('+918305866096', 'CID061105208'),
('+919343174325', 'SID25276'),
('+916205201682', 'SSF2315989'),
('+916200883925', 'SSF4447402'),
('+916203873931', 'SSF3098327'),
('+916287365315', 'SSF4344638'),
('+916265027954', 'SSF4480825'),
('+916264374527', 'SSF4681289'),
('+916202716656', 'SSF2822382'),
('+916261010969', 'SSF4457180'),
('+916205000690', 'SSF4668929'),
('+916203181681', 'SID951376063582'),
('+916299207923', 'SSF2833943'),
('+916206100068', 'SSF4595884'),
('+917483953445', 'SSF4722112'),
('+917646454848', 'SID951374809602'),
('+917654862535', 'SSF4252563'),
('+917070628589', 'SSF4406864'),
('+917987894233', 'SID951375289027'),
('+917000862084', 'SSF4597172'),
('+917258840218', 'SSF5025183'),
('+917804901596', 'SSF4409450'),
('+917870429271', 'SSF4396887'),
('+917223027407', 'SSF4457907'),
('+917870775860', 'SSF4576059'),
('+917987164595', 'SSF4032026'),
('+917254097560', 'SSF4392512'),
('+917903958170', 'SSF4575412'),
('+917481046173', 'SSF4347216'),
('+918660759830', 'SSF4666208'),
('+918536917082', 'SID951376134258'),
('+918541929816', 'SSF4405368'),
('+918271091795', 'SSF4334956'),
('+918920300173', 'SSF4454724'),
('+918543826826', 'SID951375707704'),
('+918564646446', 'SSF2392850'),
('+918651530161', 'SSF4502835'),
('+918459591514', 'SSF4411725'),
('+918434027635', 'SSF4387940'),
('+918875405010', 'SSF4500121'),
('+918858552355', 'SSF4557503'),
('+918969542317', 'SSF2486993'),
('+918002248682', 'SSF4496817'),
('+918056312086', 'SSF4374091'),
('+918298402389', 'SSF4631804'),
('+918539892372', 'SSF4567184'),
('+918409010488', 'SSF4516452'),
('+918470916626', 'SSF3107394'),
('+918252299398', 'SSF4591957'),
('+918409482338', 'SSF4443341'),
('+919257387619', 'SID951375928356'),
('+919693042370', 'SSF4737464'),
('+919024838315', 'SSF4376242'),
('+919329012150', 'SSF4642861'),
('+919142081953', 'SSF4401286'),
('+919341231548', 'SSF4572611'),
('+919931398645', 'SSF4343746'),
('+919835179034', 'SSF4514387'),
('+919340562212', 'SSF4539871'),
('+919341514861', 'SSF4455142'),
('+919340429378', 'SSF2941021'),
('+919006771091', 'SSF4359995'),
('+919484884848', 'SID951374536589'),
('+919572006458', 'SSF4381701'),
('+919285445582', 'SSF3536119'),
('+919098471656', 'SSF4635116'),
('+919199034219', 'SSF3352017'),
('+919754115212', 'SSF4681038'),
('+919801036987', 'SSF4373698'),
('+919080600355', 'SSF4457094'),
('+919171688513', 'SSF4552613'),
('+919939238650', 'SSF4567229'),
('+919508782797', 'SSF2373436'),
('+919484845949', 'SSF2299356'),
('+919494946644', 'SSF2471664'),
('+919648014577', 'SSF4611665'),
('+919708624414', 'SSF4383718'),
('+919205848131', 'SSF4380425'),
('+919696920891', 'SSF2365416'),
('+919472053321', 'SSF4141059'),
('+919026687321', 'SSF4399296'),
('+919031749448', 'SSF4347207'),
('+916387880981', 'SSF5659533'),
('+916207623683', 'SSF5781537'),
('+916287860993', 'SSF6057078'),
('+916353218828', 'SSF5646732'),
('+918081556745', 'SSF5574986'),
('+918521579567', 'SSF5880799'),
('+918837630142', 'SSF6197583'),
('+918305324813', 'SSF5772585'),
('+918920614404', 'SSF5985074'),
('+918051295554', 'SSF5459233'),
('+919798784335', 'SSF5959500'),
('+919661453798', 'SSF5725895'),
('+919125594100', 'SSF6188324'),
('+916390665773', 'SSF5527421'),
('+918303140142', 'SSF5481580'),
('+918084728923', 'SSF4998977'),
('+919693670563', 'SSF5447247'),
('+917366094132', 'SSF5388470'),
('+918521215368', 'SSF5626560'),
('+919341022237', 'SSF5708855'),
('+916378182471', 'SID951376168739'),
('+916375730181', 'SSF4319057'),
('+916248464049', 'SID2125753921'),
('+916367013410', 'SSF4212586'),
('+916378721811', 'SSF4524614'),
('+916378176022', 'SSF4289264'),
('+916299021462', 'SSF4211732'),
('+917014182725', 'SSF4384461'),
('+917679624091', 'SSF4333441'),
('+917324881527', 'SSF4386481'),
('+917079242620', 'SSF4215640'),
('+917584909950', 'SSF4137669'),
('+917461831162', 'SSF4378383'),
('+917979949449', 'SID951375738635'),
('+917357789672', 'SSF4220614'),
('+917033889069', 'SSF2289132'),
('+917488701145', 'SSF3947735'),
('+917258912673', 'SSF4323857'),
('+917352604903', 'SSF4153300'),
('+917295828021', 'SID951375788843'),
('+917014943705', 'SSF4408524'),
('+917880724048', 'SSF3531975'),
('+917024450798', 'SSF4564259'),
('+918643853434', 'SSF2484024'),
('+918302531416', 'SSF4523432'),
('+918209114419', 'SSF4263698'),
('+918969509138', 'SSF4011247'),
('+918000272980', 'SSF4311521'),
('+918209122121', 'SSF4308793'),
('+918539039453', 'SSF4483777'),
('+918541800822', 'SSF4364935'),
('+918789123585', 'SSF4220221'),
('+918120233876', 'SSF3239050'),
('+919334039089', 'SSF4872547'),
('+919263533780', 'SID951375963101'),
('+919413928744', 'SSF4258449'),
('+919546904552', 'SSF2980959'),
('+919758985828', 'SID951375371795'),
('+919216585109', 'SSF4414528'),
('+919631529332', 'SSF4722099'),
('+919658658786', 'SSF2376465'),
('+919358394463', 'SSF4523909'),
('+919325665825', 'SSF4361915'),
('+919794944949', 'SID951375949395'),
('+919155083942', 'SSF4344799'),
('+919257985425', 'SSF4392880'),
('+919413908098', 'SSF3340961'),
('+919672247811', 'SSF2371298'),
('+919523169046', 'SSF4305722'),
('+919508530598', 'SSF4824905'),
('+919199193067', 'SSF4411732'),
('+919783387127', 'SSF2877375'),
('+919263525236', 'SSF4230350'),
('+919508461439', 'SSF4387724'),
('+919546231252', 'SID951375758039'),
('+919771057116', 'SID951373458677'),
('+919304416968', 'SSF4222356'),
('+919023669055', 'SSF2888579'),
('+919661414990', 'SSF4292992'),
('+919738634656', 'SID951376152703'),
('+919155343886', 'SSF4224336'),
('+919341643554', 'SID951375640324'),
('+919801516275', 'SSF2989694'),
('+918405881970', 'SSF5473091'),
('+916280859295', 'SSF5509983'),
('+919956647477', 'SSF4521342'),
('+918000463657', 'SSF4062028'),
('+918693256988', 'SSF2397439'),
('+919588214851', 'SSF4086262'),
('+917856887458', 'SSF5631184'),
('+918532953092', 'SSF5471526'),
('+919871233917', 'SSF5461581'),
('+916397902836', 'SSF3896550'),
('+916200216772', 'SSF3929777'),
('+916205990924', 'SSF3935592'),
('+916280270168', 'SSF3423799'),
('+916232885671', 'SSF2784426'),
('+916331194979', 'SID951375950570'),
('+917979841936', 'SSF4047239'),
('+917489841943', 'SSF4107892'),
('+917023731162', 'SSF3967679'),
('+917419345766', 'SID951376175303'),
('+917043721516', 'SSF4069868'),
('+917549027226', 'SSF4287171'),
('+917091704247', 'SSF4042952'),
('+917250970718', 'SSF3956829'),
('+917339877198', 'SSF3986124'),
('+917014423565', 'SSF3532911'),
('+917412758606', 'SID951376113222'),
('+918249634245', 'SSF3903711'),
('+918456349326', 'SSF3639332'),
('+918302927119', 'SSF3910230'),
('+918935994305', 'SSF3895994'),
('+918957203287', 'SSF4067111'),
('+918875169894', 'SSF3914054'),
('+918618218824', 'SSF4058197'),
('+918271979238', 'SSF3828397'),
('+918107790589', 'SSF3911284'),
('+918529387766', 'SSF3986102'),
('+919929885046', 'SSF3642208'),
('+919460545758', 'SSF3904225'),
('+919656688666', 'SID951375951995'),
('+919631901759', 'SSF3980047'),
('+919469484679', 'SID951375996647'),
('+919166573429', 'SSF4613510'),
('+919764646464', 'SSF3852391'),
('+919592174619', 'SSF3320863'),
('+919795144416', 'SSF3273324'),
('+919467649494', 'SSF3656341'),
('+919955448299', 'SID951374628946'),
('+919523719214', 'SSF3790020'),
('+919079757997', 'SSF4502016'),
('+919304843929', 'SSF3888427'),
('+919983401062', 'SSF3972872'),
('+919006769761', 'SSF4035119'),
('+919508744025', 'SSF3995500'),
('+919661899490', 'SSF3962540'),
('+919649658226', 'SSF2429636'),
('+919983552379', 'SSF3935329'),
('+919828546879', 'SSF3926727'),
('+916201056813', 'SSF3488437'),
('+916398550000', 'SSF3749997'),
('+916464458484', 'SSF3325488'),
('+917061835038', 'SSF3789012'),
('+917688878761', 'SSF4024154'),
('+917357621140', 'SSF4030012'),
('+917859085583', 'SSF3851158'),
('+918569900067', 'SSF3314841'),
('+918959132050', 'SSF3467878'),
('+918969865565', 'SSF3419469'),
('+919461113727', 'SSF3516980'),
('+919302889125', 'SSF4017372'),
('+919343317448', 'SSF3980567'),
('+919672067686', 'SSF3691540'),
('+919660198895', 'SSF2651019'),
('+919352869192', 'SSF4024168'),
('+919842153458', 'SSF3372348'),
('+919926644390', 'SSF3984987'),
('+919982490414', 'SSF3389119'),
('+919039844464', 'SSF4023624'),
('+919768985888', 'SID951375936526'),
('+919465860988', 'SSF3473007'),
('+919767946494', 'SSF3872625'),
('+919265778343', 'SSF4007682'),
('+919098497850', 'CID261401954'),
('+919898899889', 'SSF3738415'),
('+917455868764', 'SSF3234626'),
('+918685558556', 'SSF3518610'),
('+918507712600', 'SSF3612631'),
('+919856438708', 'SSF3641996'),
('+919102339239', 'SSF3275022'),
('+919116782391', 'SSF3674182'),
('+919006322295', 'SSF3505327'),
('+916201398982', 'SSF5996257'),
('+919608666714', 'SSF6196877'),
('+916265754890', 'SSF3589029'),
('+917073548891', 'SSF3407561'),
('+917357473548', 'SSF3467060'),
('+918003071044', 'SSF3542793'),
('+918449848784', 'SSF3307524'),
('+919166148592', 'SSF3673680'),
('+919919636658', 'SSF5974163'),
('+919534164184', 'SSF5688331'),
('+919229134896', 'SSF6095706'),
('+919648473765', 'SSF5349284'),
('+919216835112', 'SSF4772623'),
('+916287874848', 'SSF3238086'),
('+916200346768', 'SSF3234876'),
('+916377180563', 'SSF3215571'),
('+918769860813', 'SSF3208192'),
('+919981786072', 'SSF3162360'),
('+916367387528', 'SSF2855716'),
('+917783077803', 'SSF3123421'),
('+917739162427', 'SSF3123841'),
('+917877500214', 'SSF2716741'),
('+917258830045', 'SSF3276825'),
('+917091778759', 'SSF3276768'),
('+918556645956', 'SSF3246348'),
('+919523882845', 'CID211200964'),
('+917970019102', 'CID224400357'),
('+919575798750', 'SID951373557240'),
('+919131518915', 'SID951375009113'),
('+916207198218', 'SSF2928106'),
('+916204837571', 'SID951376098389'),
('+917079271134', 'SID951375548578'),
('+918319653282', 'SID951375131902'),
('+919631106966', 'SID951373490544'),
('+919334376139', 'SSF2721775'),
('+916204762998', 'SSF5406107'),
('+916393459822', 'SSF3139192'),
('+916204485120', 'SSF3621239'),
('+916205142974', 'SSF4714470'),
('+916204194670', 'SSF5524071'),
('+917485843975', 'SSF5059581'),
('+917067379213', 'SSF3714151'),
('+917704088241', 'SSF3808555'),
('+917489925782', 'SSF5503712'),
('+917070372058', 'SSF5458883'),
('+917654084570', 'SSF4985753'),
('+917091974858', 'SSF4755177'),
('+917542805948', 'SSF5157901'),
('+917061390719', 'SSF5168585'),
('+917013303163', 'SSF3538981'),
('+917764074238', 'SSF5541580'),
('+917462836769', 'SSF5006458'),
('+917079481579', 'SSF5334610'),
('+917254818327', 'SSF3906193'),
('+917994026863', 'SSF5194100'),
('+917739812668', 'SSF5175080'),
('+917808310079', 'SSF5209929'),
('+917999899004', 'SSF3833476'),
('+917543881678', 'SSF5432842'),
('+917047713903', 'SSF5169600'),
('+917209573183', 'SSF5293698'),
('+917541817921', 'SSF2598955'),
('+917518611621', 'SSF5158407'),
('+917255829571', 'SSF5346412'),
('+917990329657', 'SSF5399085'),
('+917568294625', 'SSF3566568'),
('+917004654498', 'SSF5386723'),
('+917080521828', 'SSF5209754'),
('+917257936472', 'SSF5198656'),
('+917562065236', 'SSF3232432'),
('+917633044066', 'SSF5386776'),
('+917483207392', 'SSF5122122'),
('+917303451721', 'SSF5525171'),
('+918294536555', 'SSF3554432'),
('+918987569036', 'SSF5106049'),
('+918757990486', 'SSF5418729'),
('+918084698734', 'SSF5311305'),
('+918433043523', 'SSF5227326'),
('+918210310638', 'SSF6135633'),
('+918969436863', 'SSF5177549'),
('+918207755828', 'SSF5246260'),
('+918235369735', 'SSF5353674'),
('+918340603528', 'SSF4958246'),
('+918521983035', 'SSF5540147'),
('+918287181533', 'SSF5259733'),
('+918797130713', 'SSF5347706'),
('+918873250882', 'SSF3481364'),
('+918969298579', 'SSF6021422'),
('+918305476349', 'SSF5118492'),
('+918539047625', 'SSF5105477'),
('+918528964064', 'SSF5138834'),
('+918757006532', 'SSF5370174'),
('+918603695397', 'SSF5341571'),
('+918235044010', 'SSF5290930'),
('+918271448328', 'SSF5434557'),
('+918541846145', 'SSF5386706'),
('+918002994589', 'SSF5550095'),
('+918627840634', 'SSF5386703'),
('+918757579554', 'SSF5311741'),
('+918294930419', 'SSF3083461'),
('+918271731030', 'SSF5232194'),
('+918253051965', 'SSF3565959'),
('+918521906220', 'SSF5407880'),
('+918797541642', 'SSF4771867'),
('+918092729205', 'SSF5407721'),
('+919031443707', 'SSF5392993'),
('+919691130407', 'SSF5708808'),
('+919525223642', 'SSF5392904'),
('+919798053285', 'SSF6156672'),
('+919301221447', 'SSF5262328'),
('+919523019219', 'SSF5492723'),
('+919234514102', 'SSF4231198'),
('+919471909873', 'SSF5523245'),
('+919102560930', 'SSF3699149'),
('+919302813066', 'SSF5648147'),
('+919340208351', 'SSF5285688'),
('+919016947036', 'SSF3404686'),
('+919263640561', 'SSF3199530'),
('+919801322250', 'SSF4958298'),
('+919102040098', 'SSF3283453'),
('+919798542170', 'SSF5180533'),
('+919065600887', 'SSF5192870'),
('+919162480558', 'SSF5290016'),
('+919060986959', 'SSF5491716'),
('+919508280797', 'SSF5455802'),
('+919771961171', 'SSF5514603'),
('+919905017747', 'SSF5384859'),
('+919131129635', 'SSF5121349'),
('+919608495142', 'SSF3765661'),
('+919117367174', 'SSF5275668'),
('+919867872843', 'SSF5395991'),
('+919155363275', 'SSF5464193'),
('+919523500779', 'SSF5443035'),
('+919572236350', 'SSF5301201'),
('+919669346100', 'SSF5366030'),
('+919934705111', 'SSF5479042'),
('+916202902513', 'SSF6019705'),
('+918726481440', 'SSF6213550'),
('+919554468986', 'SSF5487685'),
('+919934876516', 'SSF5483896'),
('+919936208366', 'SSF4479967'),
('+916204624310', 'SSF3821880'),
('+917722872020', 'SSF5239495'),
('+917715028635', 'SSF2725848'),
('+917739532015', 'SID951374277457'),
('+917070641407', 'SSF5215670'),
('+918109539837', 'SSF4913413'),
('+918210281460', 'SSF5153636'),
('+918887822283', 'SSF5201114'),
('+918302320964', 'SSF3486915'),
('+918969789328', 'SSF5227357'),
('+918305882981', 'SSF5030878'),
('+919102369230', 'SSF5219144'),
('+919155257674', 'SSF5212439'),
('+919691547512', 'SSF5239237'),
('+919109368624', 'SSF5268656'),
('+917042613100', 'SSF6082730'),
('+919608763699', 'SSF5008115'),
('+918102046163', 'SSF5668643'),
('+916201812232', 'SSF5716084'),
('+919771764933', 'SSF5011514'),
('+919670063741', 'SSF5676724'),
('+916287233057', 'SSF4967162'),
('+916287684990', 'SSF4950660'),
('+916291834918', 'SID951376107271'),
('+916260365571', 'SSF5008793'),
('+916266844576', 'SSF4988554'),
('+917440916764', 'SSF3088340'),
('+917319653616', 'SSF5101904'),
('+917258860501', 'SSF2356633'),
('+917033762406', 'SSF4599963'),
('+917323006880', 'SID951376038175'),
('+917339941187', 'SSF4630145'),
('+917067902926', 'SSF2449715'),
('+917260960081', 'SSF4876299'),
('+917879585179', 'SSF4905371'),
('+917633057557', 'SSF4331536'),
('+917870248962', 'SSF4720297'),
('+917858862271', 'SSF4986985'),
('+917738114649', 'SSF4944339'),
('+917091671773', 'SSF4726555'),
('+917461060602', 'SSF4963827'),
('+917999066298', 'SSF4918786'),
('+918871802627', 'SSF4883282'),
('+918284995031', 'SSF4808841'),
('+918750416913', 'SSF4950617'),
('+918294101489', 'SSF4415144'),
('+918083591508', 'SSF4871904'),
('+918275345404', 'SSF4840818'),
('+918540053601', 'SSF4720292'),
('+918207502848', 'SSF4976222'),
('+918290647924', 'SSF2471403'),
('+919006705008', 'SSF4442403'),
('+919893485636', 'SSF4964529'),
('+919801774140', 'SSF4536039'),
('+919279619012', 'SSF2400723'),
('+919157921761', 'SSF4993476'),
('+919060654908', 'SSF4397772'),
('+919234191803', 'SSF3449427'),
('+919142317395', 'SSF5248413'),
('+919263220754', 'SSF4989085'),
('+919301364389', 'SSF4832885'),
('+919135727684', 'SID951375760619'),
('+919801508733', 'SSF5177745'),
('+919110917172', 'SSF4720293'),
('+919153740075', 'SSF4846850'),
('+919155576645', 'SSF4755058'),
('+919525373132', 'SSF4986134'),
('+918084006471', 'SSF5349792'),
('+919161862791', 'SSF5562717'),
('+919759808770', 'SSF5709815'),
('+919151378911', 'SSF5933833'),
('+917209450322', 'SSF5639770'),
('+918953668632', 'SSF6050467'),
('+919472943429', 'SSF5413864'),
('+919534310564', 'SID951374921032'),
('+916394532397', 'SSF5546744'),
('+917050598721', 'SSF6148479'),
('+918809253442', 'SSF5943537'),
('+919162992210', 'SSF5751989'),
('+919019143105', 'SSF4996729'),
('+919523234469', 'SSF5911111'),
('+919835459737', 'SSF5991070'),
('+919693345283', 'SSF6059592'),
('+916203710238', 'SSF6149986'),
('+917292984411', 'SSF5792795'),
('+916386366334', 'SID951375465412'),
('+916260733645', 'SSF4353267'),
('+916203255942', 'SSF3437523'),
('+916207696811', 'SSF4514384'),
('+916266571363', 'SSF4400492'),
('+916202005303', 'SSF3799442'),
('+916268005109', 'SSF4361851'),
('+916267141383', 'SSF3204561'),
('+917644978275', 'SSF4362254'),
('+917004110085', 'SSF4553539'),
('+917067985694', 'SSF4601316'),
('+917804056683', 'SSF4433762'),
('+917725953465', 'SSF4683873'),
('+917985522089', 'SSF4489762'),
('+917488154229', 'SSF3214090'),
('+917061760385', 'SID951373720231'),
('+917250988380', 'SSF4447499'),
('+917970741241', 'SSF4447610'),
('+917488845278', 'SSF4535180'),
('+917023531573', 'SSF3983551'),
('+917542022116', 'SSF4046991'),
('+917479903743', 'SSF4360666'),
('+917667537831', 'SSF4388048'),
('+917340270120', 'SSF4276458'),
('+917463901968', 'SSF4393443'),
('+917307563067', 'SSF4856049'),
('+917842878445', 'SSF4379589'),
('+917067634093', 'SSF3126275'),
('+917004438960', 'SSF4389955'),
('+918092981129', 'SSF4514671'),
('+918564564786', 'SID951373803572'),
('+918799758981', 'SSF4314667'),
('+918955033297', 'SSF4371257'),
('+918792703802', 'SSF4499549'),
('+918540990289', 'SSF4377543'),
('+918298380297', 'SSF4514036'),
('+918112693057', 'SSF3296973'),
('+918210163641', 'SSF4601369'),
('+918815427321', 'SSF3852151'),
('+918002517988', 'SSF4676525'),
('+918155843267', 'SSF4221522'),
('+918434894160', 'SSF4611981'),
('+918246449444', 'SSF2305509'),
('+919584939325', 'SSF4087322'),
('+919060820256', 'SSF4705901'),
('+919525399273', 'SSF4571680'),
('+919782371118', 'SSF4581493'),
('+919263978338', 'SSF2730393'),
('+919340031730', 'SSF4638478'),
('+919140071642', 'SID951376078885'),
('+919479944804', 'SID951374535990'),
('+919523968493', 'SSF4497340'),
('+919934209930', 'SSF2690965'),
('+919116329626', 'SSF4494736'),
('+919124580625', 'SID951376147100'),
('+919516458534', 'SSF4388421'),
('+919608338012', 'SSF4470565'),
('+919928107312', 'SSF4455163'),
('+919006668924', 'SSF5037929'),
('+919827023010', 'SSF4496843'),
('+919693234930', 'SSF4558691'),
('+919343926159', 'SSF4007916'),
('+919027412687', 'SSF4598040'),
('+919525866205', 'SSF4608287'),
('+919992957962', 'SSF3670471'),
('+919839976440', 'SSF4379464'),
('+919334193574', 'SSF4405084'),
('+919875395766', 'SSF4612653'),
('+919636140229', 'SSF4324603'),
('+919006493397', 'SSF3734350'),
('+919973891897', 'SSF4568974'),
('+919399211464', 'SSF2960827'),
('+919934100924', 'SID951375960647'),
('+919329344874', 'SSF4737699'),
('+919060185292', 'SSF5824776'),
('+919304177515', 'SSF5419117'),
('+919956675964', 'SSF5571341'),
('+919263977465', 'SSF5703660'),
('+916203813088', 'SSF5106607'),
('+918130368059', 'SSF5669522'),
('+918405800934', 'SSF5594149'),
('+916203190647', 'SID951373899203'),
('+916377519653', 'SSF4323473'),
('+916350245179', 'SSF4437227'),
('+916207251834', 'SSF4368978'),
('+917851850866', 'SSF4393944'),
('+917260974678', 'SID951375266210'),
('+917742805820', 'SSF4388843'),
('+917061095073', 'SSF4371078'),
('+917858815232', 'SSF3670552'),
('+917857911480', 'SSF4559318'),
('+917895643231', 'SSF2797928'),
('+917547003339', 'SSF2980553'),
('+917091454303', 'SSF4565743'),
('+917091918124', 'SSF4829696'),
('+917464025726', 'SSF2956634'),
('+917426916270', 'SSF4399134'),
('+918058446123', 'SSF2806231'),
('+918299632963', 'SID951373317297'),
('+918800961294', 'SSF4415869'),
('+918290480738', 'SSF4250782'),
('+918674854923', 'SSF3481850'),
('+918878179632', 'SSF2713745'),
('+918524646151', 'SSF2348698'),
('+918504087573', 'SSF4371413'),
('+918434482848', 'SID951374890546'),
('+918757785753', 'SSF3996235'),
('+918271047308', 'SSF4532286'),
('+918298446116', 'SSF4303147'),
('+918905507281', 'SSF4206181'),
('+918409064489', 'SSF4165008'),
('+918429172343', 'SSF4156949'),
('+918969520642', 'SSF4300216'),
('+918054646454', 'SID951375144670'),
('+918233614701', 'SSF4021846'),
('+918235153875', 'SSF4220286'),
('+919955566372', 'SSF4407193'),
('+919785248511', 'SID951375750516'),
('+919926253353', 'SSF4363866'),
('+919931505605', 'SSF3858472'),
('+919234193814', 'SSF4540727'),
('+919754369875', 'SID951374676160'),
('+919535648841', 'SID951376101873'),
('+919521745510', 'SSF4332592'),
('+919466499999', 'SSF3356866'),
('+919663254147', 'SID951374431889'),
('+919304580063', 'SSF4464443'),
('+919351390219', 'SSF4312689'),
('+919608305258', 'SSF2803568'),
('+919580873345', 'SSF4520301'),
('+919026604342', 'SSF4461424'),
('+919888656556', 'SID951374364342'),
('+919621441726', 'SSF4467057'),
('+919935914754', 'SSF4106528'),
('+917324942839', 'SSF5324328'),
('+917484995468', 'SSF4858783'),
('+917488628431', 'SSF5534140'),
('+918102081775', 'SSF5921480'),
('+918928193912', 'SSF5659848'),
('+916376271265', 'SSF4032111'),
('+917209759237', 'SSF2683734'),
('+919724897380', 'SSF2959827'),
('+918429862602', 'SSF4475171'),
('+919335741934', 'SSF5925763'),
('+916378521278', 'SSF3935535'),
('+916204425558', 'SSF3994111'),
('+916541555269', 'SSF3639062'),
('+916465758816', 'SID951375670713'),
('+916206544568', 'SSF3284128'),
('+916376249175', 'SSF3917003'),
('+916205694926', 'SSF4000154'),
('+917067845089', 'SSF4059433'),
('+917723866776', 'SSF4131696'),
('+917727987498', 'SSF4073911'),
('+917727951106', 'SSF3886130'),
('+917850916623', 'SSF3917171'),
('+917397293227', 'SSF3890738'),
('+918094688849', 'SSF3081411'),
('+918815793752', 'SSF4003761'),
('+918003569371', 'SSF4055563'),
('+918107962407', 'SSF4091529'),
('+918890699677', 'SSF4033635'),
('+918148865478', 'SSF4015446'),
('+918209068199', 'SSF3798590'),
('+918529139350', 'SSF4000467'),
('+918905912476', 'SSF3890270'),
('+918947974169', 'SSF3970661'),
('+918239610803', 'SSF3912274'),
('+918003361728', 'SSF4701948'),
('+919928195055', 'SSF3870201'),
('+919768646146', 'SSF3852727'),
('+919829715797', 'SSF3626630'),
('+919610446061', 'SSF3886017'),
('+919929589332', 'SSF4000468'),
('+919119254302', 'SSF4057269'),
('+919546327895', 'SSF3901578'),
('+919571967419', 'SSF3896668'),
('+919571007448', 'SSF3896232'),
('+919695655785', 'SSF3654875'),
('+916352923722', 'SSF4401353'),
('+916794949449', 'SSF3877808'),
('+916376094617', 'SSF2555020'),
('+916268880970', 'SSF3783030'),
('+917415616295', 'SSF3443135'),
('+917568189827', 'SSF2353205'),
('+917023554725', 'SSF3792725'),
('+918268855588', 'SSF3632774'),
('+918809475246', 'SSF3658783'),
('+918094138201', 'SSF3639024'),
('+918079796434', 'SSF2738678'),
('+919358357255', 'SSF3508336'),
('+919636728856', 'SSF2688301'),
('+919785469439', 'SSF3691501'),
('+919834843266', 'SSF3881038'),
('+919571184388', 'SSF3740598'),
('+919321237662', 'SSF3899485'),
('+919261524562', 'SSF3798630'),
('+919669789697', 'SSF3838323'),
('+919301062596', 'SSF3826061'),
('+919893533063', 'SSF3819146'),
('+916462584155', 'SSF3836968'),
('+917488601708', 'SSF3701181'),
('+917828696245', 'SSF2817768'),
('+918256467678', 'SSF3659765'),
('+918290598452', 'SSF3786961'),
('+918434021139', 'SSF3379293'),
('+919785128544', 'SSF3591400'),
('+919967646484', 'SSF3740595'),
('+919351879054', 'SSF3221667'),
('+919856887296', 'SSF3342461'),
('+919056700797', 'SSF6205751'),
('+919153498268', 'SSF6276685'),
('+916202987349', 'SSF5240115'),
('+917575542242', 'SSF3497738'),
('+918657456887', 'SSF3681006'),
('+919772540589', 'SSF2599882'),
('+919670393839', 'SSF5349137'),
('+918877153271', 'SSF5778762'),
('+919263408149', 'SSF5493628'),
('+918521670321', 'SSF5763665'),
('+917380919014', 'SSF4536034'),
('+919517694239', 'SSF5304983'),
('+918298938546', 'SSF5409592'),
('+918396915679', 'SSF3194806'),
('+919792418504', 'SID951375420248'),
('+919469464946', 'SSF3046816'),
('+917742038164', 'SSF3235800'),
('+919934854823', 'SSF2863837'),
('+918000856962', 'SSF4266933'),
('+917033591573', 'SID951374458196'),
('+917257952748', 'SSF3992606'),
('+918874284758', 'SSF2943816'),
('+918085938096', 'SID951375700259'),
('+916203689833', 'SSF5613532'),
('+919174798028', 'SID951375998217'),
('+919617452931', 'SSF3000165'),
('+917999704162', 'SID951374527622'),
('+919301864781', 'SID951374110619'),
('+918878467868', 'SID2125629902'),
('+916206134397', 'SID951375663231'),
('+919546044287', 'SSF4808789'),
('+916582452555', 'SID951374543433'),
('+917595889882', 'SSF6186122'),
('+919006887925', 'SSF6285196'),
('+916391654755', 'SSF6316542'),
('+919234572862', 'SSF5335310'),
('+919219022352', 'SSF5267369'),
('+916204927379', 'SSF4590280'),
('+917667842032', 'SSF5812723'),
('+919693411795', 'SSF3016126'),
('+919672630885', 'SID951374832903'),
('+917073294803', 'SSF2327115'),
('+918449661090', 'SSF4926102'),
('+919165638037', 'CID054002899'),
('+919587807732', 'SID951374545130'),
('+916280226188', 'SSF5638044'),
('+919118108079', 'SSF5095596'),
('+917250075186', 'SSF3369536'),
('+917610120800', 'SID951373159017'),
('+918092168632', 'SSF6060218'),
('+919571312119', 'SID951374587240'),
('+918889613373', 'SID32956'),
('+916264829308', 'SSF2501920'),
('+919826110716', 'SID951373365576'),
('+916260655608', 'SSF3055158'),
('+918000192595', 'SID951375352825'),
('+917067541451', 'SID2125246878'),
('+919983906236', 'SID951374183361'),
('+919753037197', 'SID2125474070'),
('+918103036356', 'SSF2471447'),
('+917764089191', 'SSF4631497'),
('+919616162506', 'SSF4328723'),
('+917719754263', 'SSF6283602'),
('+919265832008', 'SID951374858086'),
('+917693889845', 'SSF3430960'),
('+919151560911', 'SSF5847474'),
('+917300427356', 'SID951374870168'),
('+919691771051', 'SSF5955207'),
('+917404094232', 'SSF4555233'),
('+918429967620', 'SID951372904526'),
('+918234034963', 'CID048006543'),
('+918090978293', 'SSF6319180'),
('+917707051142', 'SSF4212151'),
('+917004081495', 'SID951375312190'),
('+917879672671', 'SSF3692933'),
('+917489155095', 'SSF2704559'),
('+919955918073', 'SID951373164964'),
('+917654792404', 'SID951375286562'),
('+919301653117', 'CID213101276'),
('+917073250652', 'SID951375116278'),
('+919131183240', 'SSF3508417'),
('+919516894530', 'SID951374774598'),
('+919016901187', 'CID078100838'),
('+919389927686', 'SSF5257074'),
('+917999834945', 'SID951375033266'),
('+919654648464', 'SID951375076221'),
('+916265819727', 'CID062500511'),
('+918602065887', 'SID951374380837'),
('+919511476991', 'SSF4463204'),
('+917699239544', 'SSF4868358'),
('+916260976830', 'SID2125737560'),
('+918839909210', 'CID044210799'),
('+917234981706', 'SSF3159129'),
('+919767487249', 'SID951376058317'),
('+919165574183', 'CID086901751'),
('+919756635854', 'SSF6592433'),
('+918432206731', 'SSF3771555'),
('+917294161426', 'SSF4850159'),
('+919302851047', 'SID951375382922'),
('+918839947497', 'SID951373076304'),
('+917566253191', 'SSF5869766'),
('+918271278152', 'SSF5829066'),
('+919685591584', 'SID951376241035'),
('+917209449027', 'SSF6298308'),
('+919632894662', 'SID2125293985'),
('+919304931421', 'SSF4850004'),
('+917078646616', 'SSF5288850'),
('+918543494846', 'SSF3802515'),
('+918340794034', 'SID951375214493'),
('+918825223188', 'SSF2855301'),
('+918810814019', 'SSF5239501'),
('+919244827866', 'SSF3316832'),
('+919770686585', 'SID2125281279'),
('+917454832465', 'SSF5791435'),
('+918235688036', 'SSF5669647'),
('+919302796424', 'SID951373037571'),
('+919150881636', 'SSF5874779'),
('+918235227159', 'SSF6305446'),
('+918349955919', 'SID951373943047'),
('+919939066329', 'SID951374437180'),
('+918839264738', 'SID951375075639'),
('+918302485247', 'SSF5558302'),
('+917489151953', 'SSF4891972'),
('+919304139715', 'SID951374342041'),
('+918651282910', 'SSF3044097'),
('+916264289993', 'SID2125470242'),
('+918521395175', 'SSF3110425'),
('+917096862077', 'SSF4764422'),
('+919102315652', 'SSF4848337'),
('+919692978251', 'SID951375371049'),
('+917462079680', 'SSF3967897'),
('+919263331689', 'SSF5665859'),
('+918521635329', 'SSF5665943'),
('+918271347394', 'SSF5084306'),
('+919001487729', 'SSF3917196'),
('+919630362026', 'SID951373411357'),
('+918544892232', 'SSF4726410'),
('+919244743959', 'SSF6067413'),
('+916377426908', 'SID951374687896'),
('+919977925370', 'CID129501712'),
('+919517029285', 'SSF2785856'),
('+919122382235', 'SSF2706758'),
('+918640005236', 'SID951373481878'),
('+919065476808', 'SSF2776466'),
('+918770861414', 'SID951372901471'),
('+916299697733', 'SSF3146409'),
('+917489748571', 'SID951373228163'),
('+917419117544', 'SSF3986435'),
('+917209066991', 'SSF5341483'),
('+918817751087', 'SSF5111535'),
('+918889839183', 'SID951374035145'),
('+919691875905', 'SID951373122593'),
('+919341430573', 'SSF5434678'),
('+918540046638', 'SSF5635679'),
('+916204695075', 'SID951374566419'),
('+919102730699', 'SSF4839426'),
('+917878069241', 'SSF3034683'),
('+917891606812', 'SID951375652691'),
('+918306270980', 'SID951375936974'),
('+917562813313', 'SSF2890679'),
('+917643847325', 'SID951374500825'),
('+917462096180', 'SID951375612883'),
('+919068598197', 'SSF5532307'),
('+917645925106', 'SID951374273803'),
('+918109067871', 'SSF3606105'),
('+919031873957', 'SSF5477762'),
('+917384655840', 'SID951375123617'),
('+918302723729', 'SSF4133791'),
('+919166373154', 'SID951375056178'),
('+919980459972', 'SSF3850013'),
('+918462905017', 'SID951373721116'),
('+918188972124', 'SID951375107256'),
('+919737873494', 'SSF3094860'),
('+918887926039', 'SSF3009400'),
('+917239843061', 'SSF5438132'),
('+917240905631', 'SSF3159414'),
('+917240829305', 'CID051410642'),
('+917620400320', 'SID951374364084'),
('+916386673170', 'SSF5732196'),
('+916300437213', 'SSF6066078'),
('+918084541288', 'SID951376186080'),
('+916263522061', 'SID951376013107'),
('+917987834523', 'SSF2445833'),
('+919661698026', 'SSF2399855'),
('+919973225885', 'SSF4520763'),
('+919589728427', 'CID057509803'),
('+916266400397', 'SID951375124819'),
('+919981574542', 'SSF3055615'),
('+918269748715', 'SSF3510743'),
('+917878048344', 'SSF6332810'),
('+919262618419', 'SSF3748279'),
('+919164427340', 'SSF4251437'),
('+919661876685', 'SSF5532277'),
('+917049284842', 'SID951374957425'),
('+918349963152', 'SID2125197295'),
('+919798764994', 'SID951375974681'),
('+918225872241', 'SSF4380198'),
('+919783194903', 'SSF2358415'),
('+919005095649', 'SSF3462470'),
('+919122250431', 'SID951376117571'),
('+919983082689', 'SSF4170917'),
('+918529487381', 'SSF4258445'),
('+919617673129', 'SID951374386582'),
('+919608125189', 'SSF4796072'),
('+917404109648', 'SSF4259547'),
('+919555826638', 'SSF2389249'),
('+919955597910', 'SSF2531865'),
('+916261238738', 'SSF5481655'),
('+916265835946', 'SSF5493141'),
('+916207022128', 'SSF5445025'),
('+916204745028', 'SSF5813027'),
('+916268152085', 'SSF5480372'),
('+917079709885', 'SSF3360932'),
('+917479911207', 'SSF5386038'),
('+917545923565', 'SSF5499149'),
('+917808856986', 'SSF5751775'),
('+917870119577', 'SSF5721382'),
('+917209714384', 'SSF6136947'),
('+917761978392', 'SSF5262873'),
('+917484904618', 'SSF5306663'),
('+917499257325', 'SSF5335128'),
('+917643085278', 'SSF5419056'),
('+917705934832', 'SSF3375472'),
('+917588268572', 'SSF5286970'),
('+917461833660', 'SSF3582920'),
('+917250131277', 'SSF5561158'),
('+917294908258', 'SSF5435807'),
('+917521852258', 'SSF5302095'),
('+917869592597', 'SSF5292561'),
('+917764965592', 'SSF5350708'),
('+917061994802', 'SSF5464478'),
('+917367961440', 'SSF3618392'),
('+918875166450', 'SSF5269544'),
('+918677901398', 'SSF5751782'),
('+918294524926', 'SSF5369760'),
('+918084027605', 'SSF5956565'),
('+918839390030', 'SSF3769011'),
('+918233244951', 'SSF5249464'),
('+918252312973', 'SSF5031872'),
('+918235551211', 'SSF5346097'),
('+918882844131', 'SSF5301803'),
('+918873153511', 'SSF5775313'),
('+918409775578', 'SSF4006218'),
('+918595878283', 'SSF5782981'),
('+918757325533', 'SID951375137375'),
('+918873721543', 'SSF5368267'),
('+918102884606', 'SSF5545661'),
('+918809163584', 'SSF5769172'),
('+919098070387', 'SSF5738545'),
('+919257990584', 'SSF5285523'),
('+919775028813', 'SSF3546965'),
('+919122420583', 'SSF5414990'),
('+919199046664', 'SSF5799643'),
('+919262520079', 'SSF5806608'),
('+919279933791', 'SSF5412545'),
('+919076641658', 'SSF5346167'),
('+919311496760', 'SSF5779393'),
('+919340084740', 'SSF5375372'),
('+919151170080', 'SSF3185030'),
('+919024451337', 'SSF5223309'),
('+919157291487', 'SSF5193754'),
('+919234114194', 'SSF5322472'),
('+919241387221', 'SSF5215148'),
('+919631383663', 'SSF5270295'),
('+919977826344', 'SSF4018389'),
('+919341481030', 'SSF5745879'),
('+919875150248', 'SSF3714878'),
('+919124173395', 'SSF5298824'),
('+919241170780', 'SSF5813051'),
('+919065334914', 'SSF5546225'),
('+919303199819', 'SSF5779218'),
('+919329414071', 'SSF5799302'),
('+919301709344', 'SSF5475002'),
('+917870180976', 'SSF6128725'),
('+916264401452', 'SSF5032863'),
('+917870967552', 'SSF5142956'),
('+917398314317', 'SSF3356461'),
('+917696872315', 'SSF3240981'),
('+917024596483', 'SSF5140083'),
('+917209667930', 'SSF3315179'),
('+917697107452', 'SSF5190853'),
('+918075008337', 'SSF5809305'),
('+918092002670', 'SSF5117497'),
('+918542986100', 'SSF5286377'),
('+919129182980', 'SSF3715756'),
('+919316259957', 'SSF5982359'),
('+919199186907', 'SSF3105473'),
('+919241764776', 'SSF5103726'),
('+917260831783', 'SSF5550187'),
('+918228951941', 'SSF5276889'),
('+919006813226', 'SSF5572151'),
('+916388948426', 'SSF5751945'),
('+917463992632', 'SSF5666991'),
('+917070025464', 'SSF5788239'),
('+917209061758', 'SSF5487996'),
('+917762906775', 'SSF5779873'),
('+918292278376', 'SSF5675431'),
('+919153407657', 'SSF5784633'),
('+919939797022', 'SSF5779577'),
('+916361688965', 'SSF5804515'),
('+916207972946', 'SSF5476580'),
('+916201013257', 'SSF5741989'),
('+917845180224', 'SSF5468144'),
('+917209956585', 'SSF5450197'),
('+918417902370', 'SSF5830869'),
('+918235272860', 'SSF5651269'),
('+919065397221', 'SSF5736970'),
('+919920319862', 'SSF4977071'),
('+919169193451', 'SSF5960608'),
('+919153856960', 'SSF5741983'),
('+917766832015', 'SSF5754901'),
('+917764863239', 'SSF5754558'),
('+917080576499', 'SSF5833446'),
('+918873220891', 'SSF5375916'),
('+918610435229', 'SSF5708078'),
('+916267930883', 'SID951374974873'),
('+917479619022', 'SID951375322464'),
('+918603227492', 'SID951375909826'),
('+916350480093', 'SSF5557695'),
('+916287804852', 'SSF4788601'),
('+916287241137', 'SSF5510085'),
('+916284643310', 'SSF4854236'),
('+917617361121', 'SSF4883177'),
('+917667437825', 'SSF5529471'),
('+917209849073', 'SSF6062654'),
('+917742733648', 'SSF4936708'),
('+917667746219', 'SSF6071997'),
('+917542091847', 'SSF5486701'),
('+917033982475', 'SSF4908007'),
('+917987090358', 'SSF3216830'),
('+917294824401', 'SSF4955495'),
('+917352857708', 'SSF5503789'),
('+917000817058', 'SSF5480225'),
('+917667678092', 'SSF5524454'),
('+917067667179', 'SSF4965539'),
('+918603162821', 'SSF5484349'),
('+918696959612', 'SSF5404783'),
('+918235798648', 'SSF5779289'),
('+918107589177', 'SSF3283645'),
('+918271649445', 'SSF5532362'),
('+918949065869', 'SSF3898368'),
('+918470834685', 'SSF4944977'),
('+918707370714', 'SSF5351775'),
('+918825352445', 'SSF4888263'),
('+918969326485', 'SSF4878534'),
('+918115092839', 'SSF5198872'),
('+918797605059', 'SSF4972779'),
('+918252437224', 'SSF4445479'),
('+918603357361', 'SSF5520085'),
('+918340508433', 'SSF4869407'),
('+919110067784', 'SSF5061121'),
('+919771378451', 'SSF5655347'),
('+919649393711', 'SSF4948117'),
('+919508578077', 'SSF5545250'),
('+919835628744', 'SSF3537381'),
('+919301323935', 'SSF5000710'),
('+919935587870', 'SSF5467220'),
('+919662489763', 'SSF3558605'),
('+919009836839', 'SSF3815068'),
('+919696777540', 'SSF5857328'),
('+919587479248', 'SSF4948729'),
('+919329104582', 'SID951374341497'),
('+919340226154', 'SSF5795668'),
('+919358749115', 'SSF3578165'),
('+919234093228', 'SSF5378434'),
('+919238199387', 'SSF5615283'),
('+919755605505', 'SSF5684444'),
('+919931831716', 'SSF5486733'),
('+919053715738', 'SSF4923118'),
('+919109576438', 'SSF3226991'),
('+919155332911', 'SSF5488782'),
('+919031132933', 'SSF5082003'),
('+919216591398', 'SSF3694711'),
('+919939238556', 'SSF5456237'),
('+919974458267', 'SSF5958460'),
('+919165857209', 'SSF3520438'),
('+919054397012', 'SSF5558222'),
('+919636468989', 'SSF3870348'),
('+919027024942', 'SSF4928099'),
('+918235770356', 'SSF5946735'),
('+918235477228', 'SSF5435148'),
('+918674885267', 'SSF5667567'),
('+919110917189', 'SSF5703486'),
('+917678843074', 'SSF4599325'),
('+918969022444', 'SSF5441637'),
('+919661958688', 'SSF5469601'),
('+916393343437', 'SSF4300827'),
('+916287640454', 'SSF2989857'),
('+917781026477', 'SID951374947712'),
('+917990697852', 'SSF5419890'),
('+917762009384', 'SSF5212430'),
('+917295092296', 'SSF5301096'),
('+917061823675', 'SSF5020909'),
('+917634066781', 'SID951375159472'),
('+917261857323', 'SSF5296102'),
('+917782880096', 'SSF5544621'),
('+917404811828', 'SSF5247957'),
('+917903334645', 'SSF3260612'),
('+917541984705', 'SSF3701761'),
('+917325880846', 'SSF4810991'),
('+917257827176', 'SSF5189997'),
('+917389011733', 'SSF2960124'),
('+917667080516', 'SSF4894365'),
('+917564071415', 'SID951375188558'),
('+918809734205', 'SSF5297908'),
('+918210702186', 'SSF5178448'),
('+918177087581', 'SSF4421738'),
('+918540011426', 'SSF5215324'),
('+918709852995', 'SSF5297841'),
('+918540924569', 'SID951375146740'),
('+918292285976', 'SSF5286479'),
('+918084355356', 'SSF4701235'),
('+918539036286', 'SSF5302106'),
('+918847230677', 'SSF3204472'),
('+918407840144', 'SSF5166652'),
('+918105306220', 'SID951376179194'),
('+919755711163', 'SSF5351849'),
('+919981699663', 'SSF5343747'),
('+919708650432', 'SSF5301314'),
('+919128251925', 'SSF5239906'),
('+919708040938', 'SSF5239543'),
('+919669785079', 'SSF5305367'),
('+919835596729', 'SSF5297483'),
('+919113185615', 'SSF5247524'),
('+919241727064', 'SSF5139837'),
('+919031257692', 'SSF5235553'),
('+919216734131', 'SSF4904219'),
('+919358939799', 'SSF4823459'),
('+919771945915', 'SSF3561188'),
('+919031306200', 'SSF4862771'),
('+919263722915', 'SSF3342445'),
('+919660414388', 'SSF4361167'),
('+916389655830', 'SSF5567689'),
('+917897055314', 'SSF5520220'),
('+918578046044', 'SSF5413402'),
('+919065283644', 'SSF5413495'),
('+919076572136', 'SSF4752633'),
('+917644819717', 'SSF5631379'),
('+917397119175', 'SSF5990692'),
('+916202913145', 'SSF5087573'),
('+919661637992', 'SSF5970697'),
('+916299265602', 'SSF6049623'),
('+916209579837', 'SSF6305533'),
('+916239924711', 'SSF5544219'),
('+917992475985', 'SSF5655189'),
('+917545073041', 'SSF5680190'),
('+917319692061', 'SSF5459129'),
('+917783864695', 'SSF6191784'),
('+917349826306', 'SSF5995216'),
('+917295880529', 'SSF6043505'),
('+917870671376', 'SSF6090088'),
('+918434293107', 'SSF5775581'),
('+918434771758', 'SSF5218393'),
('+918873286956', 'SSF5995214'),
('+918298400434', 'SSF5714428'),
('+919570652787', 'SSF5972928'),
('+919955162991', 'SSF5835956'),
('+919006112317', 'SSF6104470'),
('+919016754902', 'SSF5640237'),
('+919306416923', 'SSF6104486'),
('+919905640119', 'SSF5754846'),
('+917070399234', 'SSF5931150'),
('+917261078814', 'SSF5841247'),
('+917645018720', 'SSF5724471'),
('+918918564996', 'SSF6050139'),
('+918102303190', 'SSF5732010'),
('+918271105976', 'SSF6095575'),
('+919028564885', 'SSF6073375'),
('+916203006479', 'SSF4714347'),
('+916565659446', 'SID951375377717'),
('+916206570684', 'SSF4376058'),
('+916204998128', 'SSF4865582'),
('+917380747723', 'SSF4782854'),
('+917659823437', 'SID951373800990'),
('+917643097439', 'SID951376250356'),
('+917765923583', 'SSF4351855'),
('+917562860948', 'SSF3981777'),
('+917061471726', 'SID951374253990'),
('+917759874849', 'SSF3629191'),
('+917425963132', 'SSF4819928'),
('+917463096225', 'SSF4873706'),
('+917367921594', 'SSF4271180'),
('+917227825354', 'SSF4853760'),
('+918529346050', 'SSF4299776'),
('+918769125686', 'SSF4456149'),
('+918969392008', 'SSF3459723'),
('+918434329650', 'SID951374977203'),
('+918815782423', 'SSF4406349'),
('+918003155467', 'SSF4556422'),
('+918226878861', 'SSF3016415'),
('+918969475882', 'SSF2907632'),
('+918292598850', 'SSF4802566'),
('+918809555840', 'SSF4862318'),
('+918434702164', 'SID951375798897'),
('+918102681734', 'SSF4927117'),
('+919532688558', 'CID951376202491'),
('+919358736474', 'SSF4611363'),
('+919864656566', 'SID951374635231'),
('+919508011796', 'SSF4378640'),
('+919835679751', 'SSF4766316'),
('+919770516787', 'SSF4408215'),
('+919234824230', 'SSF3441820'),
('+919669062008', 'SSF4708637'),
('+919771206695', 'SSF4822893'),
('+919034838872', 'SSF4839857'),
('+919155829031', 'SID951374803323'),
('+919523845853', 'SSF4864415'),
('+919692154835', 'SSF4487210'),
('+919771157339', 'SSF4583795'),
('+919040389181', 'SSF4516955'),
('+919801133662', 'SSF4330871'),
('+919572948612', 'SSF4869620'),
('+919301786963', 'SSF4531523'),
('+919523030336', 'SSF4385885'),
('+919341014241', 'SSF4801159'),
('+919644623877', 'SSF4880296'),
('+919993140091', 'SSF4271045'),
('+919835119948', 'SSF4325357'),
('+919039601341', 'SSF2861222'),
('+919035769498', 'SSF4336057'),
('+919065899533', 'SSF4332332'),
('+917250909200', 'SSF5332390'),
('+917764916585', 'SSF6139420'),
('+917392048733', 'SSF5730031'),
('+918797231847', 'SSF5471948'),
('+918092054924', 'SSF5644519'),
('+919263163330', 'SSF5730235'),
('+919199897059', 'SSF6080729'),
('+919306209510', 'SSF5500717'),
('+919102036538', 'SSF5486989'),
('+919915374112', 'SSF5710347'),
('+919234797045', 'SSF5705423'),
('+919934092675', 'SSF5780648'),
('+919631390709', 'SSF5575693'),
('+917541969208', 'SSF5612230'),
('+918294845747', 'SSF5803551'),
('+919608485482', 'SSF5765826'),
('+919263069030', 'SSF5658323'),
('+919880298019', 'SSF5481836'),
('+918429456019', 'SSF5940794'),
('+918541091688', 'SSF5749638'),
('+916377522393', 'SSF4414146'),
('+916201686398', 'SSF3190985'),
('+916377560503', 'SSF4460573'),
('+916207033052', 'SSF4782736'),
('+916367349713', 'SSF2680071'),
('+917489434553', 'SSF4607881'),
('+917781991791', 'SSF3291310'),
('+917726027061', 'SSF4092748'),
('+917742458027', 'SID951375907456'),
('+917875681236', 'SID951375715139'),
('+917804817467', 'SSF4160685'),
('+917340160276', 'SSF4153818'),
('+917633839135', 'SID951374951019'),
('+917073458066', 'SSF4212576'),
('+917079246309', 'SSF4185312'),
('+917240164697', 'SSF4244496'),
('+917367084239', 'SSF4117799'),
('+917878682670', 'SSF4499435'),
('+918092551135', 'SSF2805540'),
('+918094813142', 'SID951375826402'),
('+918210175312', 'SSF4781276'),
('+918302458962', 'SSF4462985'),
('+918319786975', 'SSF4625296'),
('+918709137208', 'SSF4707713'),
('+918271461756', 'SSF4127207'),
('+918797088214', 'SSF4208281'),
('+918235258986', 'SSF4708638'),
('+918409959492', 'SSF4793846'),
('+918003306513', 'SSF4834849'),
('+918052343445', 'SID951375059117'),
('+918690450162', 'SSF4126557'),
('+918292709489', 'SSF4148377'),
('+918955881965', 'SSF4318731'),
('+918209121882', 'SSF2710065'),
('+918252050834', 'SSF4394356'),
('+918539913095', 'SSF4216097'),
('+919304219686', 'SSF4419762'),
('+919106438460', 'SSF4830336'),
('+919784033735', 'SSF4836163'),
('+919973507545', 'SSF4782737'),
('+919216317934', 'SSF4652707'),
('+919829684769', 'SSF3982224'),
('+919649464845', 'SID951376154088'),
('+919153929780', 'SSF3399305'),
('+919988622412', 'SID951375571551'),
('+919302825243', 'SSF3775292'),
('+919122814153', 'SSF4711393'),
('+919031760510', 'SSF4747764'),
('+919661768440', 'SSF4747883'),
('+919608417426', 'SSF4141203'),
('+919928689850', 'SID951374633205'),
('+919511353825', 'SSF4176899'),
('+919794541594', 'SSF4517922'),
('+919877281637', 'SID951375641351'),
('+919135974119', 'SSF4251513'),
('+919166970521', 'SSF4403060'),
('+919572759675', 'SSF4124671'),
('+919632580928', 'SID951374576960'),
('+919636758053', 'SSF3147394'),
('+919341805337', 'SSF4524787'),
('+919784151293', 'SSF3904155'),
('+917888470660', 'SSF4864592'),
('+918407030273', 'SSF5354272'),
('+918000698131', 'SSF4831984'),
('+917461031572', 'SSF5676640'),
('+917520986033', 'SSF5780106'),
('+917209553929', 'SSF5990235'),
('+919279552071', 'SSF5037126'),
('+916203739745', 'SSF5994848'),
('+917858850831', 'SSF5863544'),
('+919794496576', 'SSF4520913'),
('+919173083504', 'SSF5930272'),
('+916260639427', 'SSF4015901'),
('+918815998470', 'SSF4905856'),
('+918271434342', 'SSF4488464'),
('+919934360861', 'SSF4001083'),
('+917081957212', 'SSF5356893'),
('+919065756005', 'SSF5837713'),
('+916209593658', 'SSF3829206'),
('+916269230867', 'SSF3944942'),
('+916203040103', 'SID951376091384'),
('+916204318434', 'SID951376041485'),
('+916248848848', 'SSF3753356'),
('+916377067847', 'SSF4096085'),
('+917717479452', 'SSF4319988'),
('+917321916873', 'SSF3267204'),
('+917014979526', 'SSF4225412'),
('+917061804615', 'SSF4213515'),
('+917349945181', 'SSF4205828'),
('+917547021464', 'SSF4287620'),
('+917542921753', 'SSF4361615'),
('+917665933749', 'SSF3851345'),
('+917462018531', 'SSF4235341'),
('+917320856897', 'SSF4205369'),
('+917862029288', 'SSF4272878'),
('+918873304508', 'SSF4192341'),
('+918651148108', 'SSF4234856'),
('+918131898599', 'SSF4293559'),
('+918003831318', 'SSF3621991'),
('+918690148408', 'SSF4086137'),
('+918905745927', 'SSF4196996'),
('+919001764691', 'SSF4224990'),
('+919057244032', 'SSF4237208'),
('+919835180619', 'SID951374600356'),
('+919798400894', 'SSF4016527'),
('+919664182374', 'SSF2684815'),
('+919648134681', 'SSF3873632'),
('+919509669402', 'SSF3882321'),
('+919645481549', 'SSF3882326'),
('+919079689932', 'SSF2855713'),
('+919931097953', 'SSF4208715'),
('+919660355978', 'SSF4255361'),
('+919005796799', 'SSF3860288'),
('+919122897521', 'SSF4320042'),
('+919352584647', 'SSF4272848'),
('+919523285430', 'SSF5479545'),
('+916494946740', 'SSF3656962'),
('+916394499082', 'SSF3732095'),
('+916436434944', 'SSF3690672'),
('+917484548484', 'SSF3744821'),
('+917339850231', 'SSF3773669'),
('+917568062269', 'SSF4246078'),
('+917364584477', 'SSF3678546'),
('+918955365559', 'SSF3517623'),
('+918444949494', 'SSF3744866'),
('+918495858484', 'SSF3744762'),
('+918794464648', 'SSF3581416'),
('+918292101270', 'SSF3580705'),
('+918109290185', 'SSF3985423'),
('+918521463954', 'SSF3518479'),
('+919636721157', 'SSF3773618'),
('+919886689588', 'SSF3680880'),
('+919358255994', 'SSF3663402'),
('+919265900882', 'SID951375683198'),
('+919928303941', 'SSF4389301'),
('+919660311896', 'SSF3773602'),
('+919653891917', 'SSF3762298'),
('+919303954428', 'SSF4178060'),
('+919399271524', 'SSF4050668'),
('+919001850774', 'SSF3872091'),
('+919828457575', 'SSF3772401'),
('+919610616828', 'SSF3701943'),
('+919636168097', 'SSF4074023'),
('+919636095571', 'SSF3778945'),
('+919858464949', 'SSF3753470'),
('+919772349457', 'SSF3622585'),
('+916258965907', 'SSF3513690'),
('+916385787562', 'SSF3333802'),
('+918542369854', 'SSF3334384'),
('+918511105073', 'SSF3771845'),
('+918784546464', 'SSF3343372'),
('+919215478963', 'SSF3442591'),
('+919784546464', 'SSF3567949'),
('+919660546855', 'SSF2596830'),
('+918052283413', 'SSF5496587'),
('+917488735429', 'SSF6296584'),
('+916378984867', 'SSF3394942'),
('+917988300672', 'SSF3283119'),
('+918824629933', 'SSF3385163'),
('+918824768823', 'SSF3196914'),
('+919234617745', 'SSF5667080'),
('+919155379149', 'SSF5262172'),
('+919905468901', 'SSF5529222'),
('+919667406873', 'SSF5704326'),
('+919304788127', 'SSF6072538'),
('+916375260790', 'SSF3637859'),
('+917052574269', 'SSF3674165'),
('+918429434154', 'SSF3626614'),
('+918464949948', 'SSF3078403'),
('+918579259289', 'SSF3566467'),
('+919823183146', 'SSF3676848'),
('+919766464648', 'SSF3634644'),
('+919571157766', 'SSF3061784'),
('+918448374356', 'SSF2288456'),
('+919427643151', 'SSF2959934'),
('+916201085924', 'SSF2490507'),
('+917398518206', 'SSF2579944'),
('+917672889776', 'SSF2554471'),
('+918051233952', 'SSF2956772'),
('+919523311346', 'SID951376020450'),
('+916375241455', 'SSF5285347'),
('+916299279848', 'SSF3621618'),
('+916264836415', 'SSF5926208'),
('+916202413405', 'SSF5385588'),
('+916200315102', 'SSF4534904'),
('+916375715591', 'SSF5311762'),
('+916263818913', 'SSF5759375'),
('+916205772478', 'SSF3357874'),
('+917484080298', 'SSF3665653'),
('+917479651931', 'SSF5647300'),
('+917361832160', 'SSF5306816'),
('+917366827245', 'SSF4172106'),
('+917762094163', 'SSF3580809'),
('+917970551063', 'SSF5409399'),
('+917631491191', 'SSF5806683'),
('+917546965123', 'SSF5485725'),
('+917856920129', 'SSF5812235'),
('+917282834582', 'SSF5322490'),
('+917903063620', 'SSF5998858'),
('+917779858927', 'SSF5351361'),
('+917657988237', 'SSF5321541'),
('+917370885456', 'SSF5161212'),
('+917470436200', 'SSF5285939'),
('+917061352547', 'SSF5338337'),
('+917439276503', 'SSF3967976'),
('+917340385757', 'SSF5254524'),
('+917988407705', 'SSF5327446'),
('+918434585571', 'SSF5455510'),
('+918957731360', 'SSF3557298'),
('+918959270596', 'SSF5467593'),
('+918016121963', 'SSF5301394'),
('+918509303437', 'SSF5438849'),
('+918817615751', 'SSF3147184'),
('+918789933228', 'SSF5800131'),
('+918540852827', 'SSF5714399'),
('+918809239829', 'SSF5487734'),
('+918227870801', 'SSF5354109'),
('+918797762988', 'SSF5336006'),
('+918603443810', 'SSF5517846'),
('+918521691530', 'SSF5787874'),
('+919973127621', 'SSF3646108'),
('+919472661873', 'SSF5789089'),
('+919060205180', 'SSF5541056'),
('+919508800671', 'SSF5296561'),
('+919241455324', 'SSF5192884'),
('+919279081434', 'SSF5725340'),
('+919381223767', 'SSF3617182'),
('+919358806941', 'SSF5393014'),
('+919123234688', 'SSF5306639'),
('+919835490788', 'SSF5640494'),
('+919873154626', 'SSF5326195'),
('+919693388612', 'SSF3344553'),
('+919721044716', 'SSF5181944'),
('+919263010119', 'SSF5439202'),
('+919142385628', 'SSF5817154'),
('+919342592889', 'SSF3958070'),
('+919685189521', 'SSF5413460'),
('+919135426877', 'SSF5367129'),
('+919153449308', 'SSF3591685'),
('+917900054668', 'CID211100502'),
('+919304519321', 'SSF5598740'),
('+916268586563', 'SID951374737204'),
('+917805879500', 'SID951375546647'),
('+918521641646', 'SID2125544187'),
('+919691592521', 'SID951375703905'),
('+919608590792', 'SID951375585547'),
('+916203464508', 'SSF2653814'),
('+916299525812', 'SID951376099699'),
('+917643834251', 'SSF2499358'),
('+917765883336', 'SSF2305101'),
('+917295000396', 'SSF2448115'),
('+919839638642', 'SSF2300407'),
('+919024656966', 'SID951376104216'),
('+916267232041', 'SSF5134373'),
('+916302687181', 'SSF5054812'),
('+916204467548', 'SSF5169384'),
('+916203679083', 'SSF3832499'),
('+916392773401', 'SSF5367099'),
('+916239314326', 'SSF3392184'),
('+916205017124', 'SSF4402459'),
('+917366871366', 'SSF5064865'),
('+917644921775', 'SSF5192929'),
('+917461918771', 'SSF5394555'),
('+917545092014', 'SSF5298030'),
('+917297924844', 'SSF3848549'),
('+917258925986', 'SSF5787547'),
('+917494063977', 'SSF5167797'),
('+917070701997', 'SSF5928655'),
('+917980602443', 'SSF3772073'),
('+917505918629', 'SSF5141252'),
('+917814722556', 'SSF5141254'),
('+917352601480', 'SSF5720612'),
('+917858933693', 'SSF5201508'),
('+917488149429', 'SSF5215827'),
('+917667614408', 'SSF5170702'),
('+917354592437', 'SSF3448322'),
('+917549446997', 'SSF5140046'),
('+917644046226', 'SSF3601336'),
('+917070676538', 'SSF5283134'),
('+917449671760', 'SSF5127462'),
('+917033139011', 'SSF5076114'),
('+917654572699', 'SSF5227122'),
('+917878092653', 'SSF5274923'),
('+917258058935', 'SSF5185067'),
('+917260914180', 'SSF5321501'),
('+917970381308', 'SSF5123333'),
('+918877764987', 'SSF5199411'),
('+918009753396', 'SSF3573786'),
('+918470820476', 'SSF5199302'),
('+918252011492', 'SSF5150784'),
('+918603245611', 'SSF3105480'),
('+918092141661', 'SSF5030362'),
('+918092797546', 'SSF5158607'),
('+918539035843', 'SSF5532245'),
('+918294431757', 'SSF3181195'),
('+918409576329', 'SSF5732038'),
('+918102175388', 'SSF5159627'),
('+918434794045', 'SSF5675026'),
('+918873974733', 'SSF5167833'),
('+918981964824', 'SSF5016050'),
('+918651833122', 'SSF5769114'),
('+918619519683', 'SSF5140410'),
('+918519050785', 'SSF5402091'),
('+918757657336', 'SSF5261936'),
('+918282913785', 'SSF3171689'),
('+918521133005', 'SSF3618246'),
('+918521112731', 'SSF5751727'),
('+918051704434', 'SSF5083841'),
('+918252485004', 'SSF5201609'),
('+918228851748', 'SSF5147089'),
('+918789936922', 'SSF5302787'),
('+918177901348', 'SSF5188660'),
('+918579912150', 'SSF5370888'),
('+918809039275', 'SSF3211581'),
('+919153321297', 'SSF5557677'),
('+919708208676', 'SSF5154334'),
('+919801573464', 'SSF3247472'),
('+919142491309', 'SSF3612684'),
('+919285132008', 'SSF5106639'),
('+919153863890', 'SSF5382371'),
('+919602594542', 'SSF5030314'),
('+919155317390', 'SSF3420119'),
('+919801629759', 'SSF5159699'),
('+919771595621', 'SSF5143861'),
('+919006638163', 'SSF5146109'),
('+919693255208', 'SSF5154116'),
('+919113080589', 'SSF2814245'),
('+919955221243', 'SSF5129711'),
('+919771502606', 'SSF5348804'),
('+919608640311', 'SSF5159178'),
('+919241113435', 'SSF5173672'),
('+919835704706', 'SSF5145335'),
('+919356405801', 'SSF5177310'),
('+919330010086', 'SSF5133143'),
('+919341130938', 'SSF4701425'),
('+919302829685', 'SSF3417695'),
('+919241096620', 'SSF5141665'),
('+919234009422', 'SSF5157540'),
('+919263457465', 'SID2125713982'),
('+919343912033', 'SSF5274486'),
('+917760156208', 'SSF5466971'),
('+917783042482', 'SSF5765191'),
('+917209895468', 'SSF4604267'),
('+919570679536', 'SSF6080058'),
('+919661143405', 'SSF5742667'),
('+917782040969', 'SSF5378990'),
('+917739707872', 'SSF5960711'),
('+918936847829', 'SSF5676534'),
('+918709278978', 'SSF5453358'),
('+918968819284', 'SSF5606444'),
('+918003834481', 'SID951375937631'),
('+918969501543', 'SSF2400856'),
('+916200133132', 'SSF5579227'),
('+917209895132', 'SSF5446941'),
('+917050026274', 'SSF5718253'),
('+917543864298', 'SSF4970256'),
('+917470700959', 'SSF3719599'),
('+917766901136', 'SSF4959229'),
('+917992464097', 'SSF3058493'),
('+917828722403', 'SSF5642401'),
('+918757033020', 'SSF5580439'),
('+918084763388', 'SSF5544602'),
('+918002216266', 'SSF5438869'),
('+919771314662', 'SSF4992977'),
('+919153810837', 'SSF2714475'),
('+919934860007', 'SSF4742811'),
('+919785232950', 'SSF3549677'),
('+919934954312', 'SSF5665377'),
('+919546205934', 'SSF4854092'),
('+919262727685', 'SSF4468612'),
('+919939425846', 'SSF5148977'),
('+918271719715', 'SID2125253403'),
('+918305086234', 'CID061105725'),
('+917033570277', 'SSF5755804'),
('+918081517534', 'SSF4376530'),
('+916204650783', 'SSF5181019'),
('+916201689482', 'SSF2304275'),
('+917033871156', 'SSF5281617'),
('+917992449584', 'SSF4716684'),
('+917370990464', 'SSF5297784'),
('+917295835838', 'SSF3423504'),
('+917542842829', 'SSF5186784'),
('+917352274213', 'SSF3660115'),
('+917562871658', 'SSF5185656'),
('+917033770938', 'SSF4894991'),
('+917667518312', 'SSF5206504'),
('+917389094293', 'SSF4811221'),
('+918521635129', 'SSF5265481'),
('+918292337065', 'SSF2286238'),
('+918235132894', 'SSF5004220'),
('+918825208908', 'SSF5295010'),
('+918001750018', 'SSF3434889'),
('+918092674217', 'SSF5257125'),
('+918865321255', 'SID951375457509'),
('+918109948398', 'SSF4833867'),
('+918797924305', 'SSF3287074'),
('+919558245575', 'SSF5239218'),
('+919607256475', 'SSF3242446'),
('+919931460341', 'SSF4272322'),
('+919110955226', 'SSF5564434'),
('+919162129211', 'SSF5187903'),
('+919571598068', 'SSF4703834'),
('+919316871924', 'SSF5529046'),
('+919256951372', 'SSF5244554'),
('+919584770688', 'SSF5261998'),
('+919507483003', 'SSF4723493'),
('+919905593791', 'SSF4886541'),
('+919661832517', 'SSF5226310'),
('+918299351586', 'SSF5353883'),
('+918927228802', 'SSF3194208'),
('+919931977922', 'SID951375068984'),
('+916203004251', 'SSF5942439'),
('+917739357606', 'SSF5821812'),
('+917081080978', 'SSF5857258'),
('+917321996063', 'SSF6176898'),
('+917070958723', 'SSF5960785'),
('+918002041947', 'SSF6293378'),
('+918533942723', 'SSF5836498'),
('+918294902603', 'SSF5398823'),
('+919576459182', 'SSF6081340'),
('+919065711976', 'SSF5909711'),
('+916205689749', 'SSF5682835'),
('+918969104994', 'SSF5724254'),
('+919905181251', 'SSF6104457'),
('+919735355688', 'CID218101217'),
('+917671043071', 'SSF5694024'),
('+918874721949', 'SSF5769879'),
('+916205328741', 'SSF4688282'),
('+916268556166', 'SSF4537383'),
('+916207340373', 'SSF4732817'),
('+916204222496', 'SSF4853563'),
('+916200295855', 'SSF4380380'),
('+917488461865', 'SSF4869140'),
('+917482058861', 'SSF4894112'),
('+917374916020', 'SID951375211566'),
('+917368010048', 'SSF4873656'),
('+917292945359', 'SSF4740047'),
('+917485804847', 'SSF4680622'),
('+917209842058', 'SSF4789907'),
('+917970929047', 'SSF4320417'),
('+917050329662', 'SSF4385169'),
('+917726024633', 'SSF4869359'),
('+917067025822', 'SSF4515348'),
('+918005523172', 'SSF4800170'),
('+918905718518', 'SSF4557612'),
('+918877471112', 'SID951376035997'),
('+918294868893', 'SID951375103881'),
('+918769462949', 'SSF4480130'),
('+918750435257', 'SSF4498824'),
('+918290263219', 'SSF4227642'),
('+918461863433', 'SSF4828605'),
('+918890304227', 'SSF4318699'),
('+918003588931', 'SID951374547176'),
('+918890672264', 'SSF4449754'),
('+918002198625', 'SSF4710933'),
('+918769218082', 'SSF4652006'),
('+918877687236', 'SSF4375528'),
('+918260607835', 'SID951373970751'),
('+919031436202', 'SSF4358698'),
('+919343822787', 'SSF4106044'),
('+919279170275', 'SSF2727988'),
('+919263020748', 'SSF2722788'),
('+919145914800', 'SID951375980517'),
('+919340417595', 'SSF4324002'),
('+919303570069', 'SID951372900246'),
('+919799259725', 'SSF4450340'),
('+919279910048', 'SSF4798912'),
('+919339300419', 'SSF3381337'),
('+919156410563', 'SSF4862418'),
('+919279181238', 'SSF4345582'),
('+919122807956', 'SSF4865588'),
('+919508954264', 'SSF2828488'),
('+919329223671', 'SSF3126273'),
('+919199330540', 'SSF4705127'),
('+918825149104', 'SSF5485719'),
('+918295960571', 'SSF6033839'),
('+919608357379', 'SSF5040414'),
('+918756219822', 'SSF4894981'),
('+919989694018', 'SSF5742596'),
('+916355687194', 'SSF4764891'),
('+916350099166', 'SSF4649514'),
('+916377959214', 'SSF3923454'),
('+916202136899', 'SSF4832428'),
('+916288968658', 'SID951374983464'),
('+916204012388', 'SSF4569505'),
('+917426969872', 'SSF4079208'),
('+917023230977', 'SSF4468993'),
('+917781864014', 'SSF3423854'),
('+917209387266', 'SSF3863440'),
('+917666609776', 'SSF4126597'),
('+917879821658', 'SID951375460516'),
('+917014675024', 'SSF4149992'),
('+918780580688', 'SSF4079181'),
('+918809023954', 'SSF4615824'),
('+918690924233', 'SSF4374853'),
('+918305205368', 'SSF4641925'),
('+918690609217', 'SSF4162963'),
('+918454898551', 'SSF4129303'),
('+918709974154', 'SSF4605524'),
('+918579857167', 'SSF4123224'),
('+918102024822', 'SSF4145072'),
('+918521780074', 'SSF3874161'),
('+918603665203', 'SSF2784302'),
('+918103736689', 'SSF4596876'),
('+919649449700', 'SID951374962926'),
('+919303628511', 'SSF4029465'),
('+919074548307', 'SSF4564355'),
('+919661108984', 'SSF4657427'),
('+919116818293', 'SSF4356933'),
('+919257734593', 'SSF4774259'),
('+919122005853', 'SSF4046490'),
('+919024539879', 'SSF4246087'),
('+919571799267', 'SSF4208348'),
('+919518293413', 'SSF4796451'),
('+919508346370', 'SSF4135889'),
('+919587467024', 'SID951376160221'),
('+919155119496', 'SSF4085409'),
('+919153904058', 'SSF4135659'),
('+919694623778', 'SSF4672529'),
('+919798764887', 'SID951375165368'),
('+919106177189', 'SSF4171843'),
('+919057272542', 'SSF4128421'),
('+919857946464', 'SSF3195452'),
('+919584828632', 'SSF4529670'),
('+919174868020', 'SSF4531223'),
('+919653706506', 'SSF4132785'),
('+919631098855', 'SSF4666659'),
('+919931988608', 'SSF3177752'),
('+917903954092', 'SSF6015457'),
('+918987073590', 'SSF4952881'),
('+918271098867', 'SSF6109899'),
('+917631472279', 'SSF4372491'),
('+918709310557', 'SSF5262243'),
('+919931283069', 'SSF5149753'),
('+916353967742', 'SSF5095957'),
('+917856901657', 'SSF5842642'),
('+918102857724', 'SSF6017719'),
('+918264063576', 'SSF6127954'),
('+919334638405', 'SSF6017742'),
('+919341925074', 'SSF6017738'),
('+919599171845', 'SSF5496029'),
('+916202898479', 'SSF5680188'),
('+917081821217', 'SSF5550524'),
('+916386912651', 'SSF5834294'),
('+919102048354', 'SSF4000569'),
('+919153921880', 'SSF4362482'),
('+917070208443', 'SSF3875311'),
('+917050259409', 'SSF5827648'),
('+918271645350', 'SSF5832512'),
('+916209142617', 'SSF3214073'),
('+916299820309', 'SSF3143295'),
('+916378321556', 'SSF4272861'),
('+917878127020', 'SSF2823032'),
('+917568543086', 'SSF3938449'),
('+917727095328', 'SSF3968026'),
('+917339868171', 'SSF3882327'),
('+917021773534', 'SSF4240448'),
('+917634033582', 'SSF4172693'),
('+917878636036', 'SSF4272894'),
('+918676870913', 'SSF4297716'),
('+918855869780', 'SID951375147375'),
('+918905020832', 'SSF4191212'),
('+918540010706', 'SSF4248662'),
('+918540969580', 'SSF4213490'),
('+918233960254', 'SSF4225057'),
('+918319215428', 'SSF4189829'),
('+918696509679', 'SSF4227008'),
('+918664927879', 'SID951376142293'),
('+919122939027', 'SSF4317120'),
('+919571321813', 'SSF4225106'),
('+919694725594', 'SID951375431032'),
('+919279924892', 'SSF4313731'),
('+919717182404', 'SSF3848633'),
('+919352276899', 'SSF2650909'),
('+919928422505', 'SSF3860496'),
('+919166757989', 'SSF3838967'),
('+919867846498', 'SSF3860276'),
('+919079300490', 'SSF2593610'),
('+916531316464', 'SSF3842959'),
('+916676776765', 'SSF3683795'),
('+916240879499', 'SSF3589786'),
('+916261876437', 'SSF3725987'),
('+917876279978', 'SSF3717533'),
('+917667231602', 'SSF4084376'),
('+917542034279', 'SSF3699140'),
('+917725932329', 'SSF3729643'),
('+918649868399', 'SSF3663401'),
('+918005584622', 'SSF3551310'),
('+919464887979', 'SSF2643260'),
('+919559959959', 'SSF3670657'),
('+919950977253', 'SSF4318350'),
('+919341835350', 'SSF3517063'),
('+919110172824', 'SID951374978421'),
('+919316064763', 'SSF5172509'),
('+918877570361', 'SSF5239788'),
('+916398542170', 'SSF3593694'),
('+916324704415', 'SSF3557161'),
('+917023453309', 'SSF3909783'),
('+917089849088', 'SSF3980936'),
('+917458666542', 'SSF3348712'),
('+918655585855', 'SSF3710455'),
('+918290774403', 'SSF3492842'),
('+919982687248', 'SSF3419597'),
('+917688808880', 'SSF3677339'),
('+918754544545', 'SSF3230823'),
('+919886566568', 'SSF3619562'),
('+919638542684', 'SSF3245886'),
('+916201776624', 'SSF5087912'),
('+917070499550', 'SSF3096158'),
('+919785469464', 'SSF3523633'),
('+919765364864', 'SSF3397316'),
('+919769425885', 'SSF3669594'),
('+919548484848', 'SSF3669577'),
('+919216784388', 'SSF3673786'),
('+919894678865', 'SSF3661722'),
('+919817944146', 'SSF3157974'),
('+919358549497', 'SSF3377429'),
('+919683484634', 'SSF3146978'),
('+919009399063', 'SID951376119629'),
('+916262572193', 'SSF5620726'),
('+917389774115', 'SSF5324569'),
('+917772039851', 'SSF5629965'),
('+918154022809', 'SSF5250983'),
('+918057214563', 'SSF3767757'),
('+919408766166', 'SSF3137565'),
('+919257256342', 'SID951374476873'),
('+919060624410', 'SSF5618872'),
('+917067248078', 'SSF3319651'),
('+916377046710', 'SID951375683416'),
('+919708465793', 'SSF4714712'),
('+918962644584', 'SSF2836159'),
('+919711313661', 'SSF2711165'),
('+917804973244', 'SSF5466569'),
('+919263533093', 'SSF6202594'),
('+918084294585', 'SSF4995620'),
('+919631006982', 'SID951375124386'),
('+917388909378', 'SSF2502593'),
('+918931077754', 'SSF2502093'),
('+919755344661', 'SID2125044252'),
('+918817240396', 'SID951373249253'),
('+916351549530', 'SSF6395908'),
('+919263510178', 'SSF2894646'),
('+917667450832', 'SSF3229430'),
('+918002580954', 'SSF2581209'),
('+919122542131', 'SSF4769866'),
('+919628216719', 'SSF5504307'),
('+917015047697', 'SSF3037063'),
('+916202866215', 'SSF3379986'),
('+918854246640', 'SID951373150926'),
('+917000963145', 'SID2125041708'),
('+917320875334', 'SSF3053628'),
('+918115758561', 'SSF5034770'),
('+918905633540', 'SSF3803995'),
('+916265515685', 'SSF2818630'),
('+919244321987', 'CID213601088'),
('+919024522561', 'SSF2873874'),
('+919024158368', 'SID951373650011'),
('+919238773961', 'SSF3965470'),
('+919867853989', 'SID951375584865'),
('+917742368219', 'SSF5250398'),
('+919560260494', 'SSF6313398'),
('+918809795980', 'SSF5325948'),
('+919708868063', 'SSF3359477'),
('+916395900647', 'SSF5464797'),
('+919754163893', 'SID951374228650'),
('+917050614277', 'SSF2415424'),
('+917828060310', 'SSF3936305'),
('+918603788300', 'SID951374645986'),
('+917909628380', 'SID951373556593'),
('+918956231285', 'SID951373112795'),
('+918827039212', 'SSF3548150'),
('+919752204797', 'SSF2601012'),
('+916367008843', 'SID951375167690'),
('+919244567762', 'SSF3633449'),
('+918982131012', 'SSF3243630'),
('+919234309198', 'SSF5722227'),
('+919302464035', 'SSF3366733'),
('+918958647701', 'SSF6114512'),
('+917782837207', 'SSF2786125'),
('+918854896340', 'SSF2390111'),
('+917877891417', 'SSF3028262'),
('+918555581148', 'SID951375037176'),
('+919302636633', 'SSF4247418'),
('+917251001442', 'SSF4070838'),
('+919541763087', 'SID951375883775'),
('+918958394461', 'SSF5324673'),
('+919516161542', 'SSF3473155'),
('+916232710090', 'SSF2998494'),
('+917525897285', 'SSF5383286'),
('+916204249692', 'CID204500814'),
('+918809876391', 'SSF3139176'),
('+917410828747', 'SSF2582185'),
('+918084080688', 'SSF5768625'),
('+916207594704', 'SSF3569478'),
('+916265632257', 'SID951373793688'),
('+919155204785', 'SSF3101462'),
('+919329184219', 'SSF5235651'),
('+917877913590', 'SSF4093366'),
('+919039128023', 'SSF3420853'),
('+919555870680', 'SSF3334830'),
('+919696190474', 'SSF3808483'),
('+918839601839', 'SSF3591297'),
('+917441181624', 'SSF2870578'),
('+917723956286', 'SSF2696932'),
('+917987184784', 'SSF3079790'),
('+917357960229', 'SSF2442088'),
('+916387786128', 'SSF3990204'),
('+917880242546', 'SSF3333652'),
('+916375843903', 'SSF3660952'),
('+919770856487', 'SSF3487337'),
('+919887545336', 'SSF3371655'),
('+917869154131', 'SSF3859325'),
('+918454818928', 'SID951375456112'),
('+919131010268', 'SSF4172650'),
('+917852028041', 'SSF2475590'),
('+919117767790', 'SSF2432629'),
('+918269548519', 'SID951374781442'),
('+919784183472', 'SSF4559805'),
('+917805822250', 'SID951373985605'),
('+918603138565', 'SSF2332694'),
('+916200504667', 'SSF3366974'),
('+919117504001', 'SSF3302621'),
('+918233103945', 'SID951375150795'),
('+919302440355', 'SSF3136711'),
('+918839722364', 'SSF3177168'),
('+919009330254', 'SID951373041892'),
('+917794854381', 'SSF2933757'),
('+918103123165', 'SID951374679157'),
('+916392994404', 'SSF5006406'),
('+919120321920', 'SSF4142122'),
('+917568020102', 'SID951374799391'),
('+919343582983', 'SID2125132854'),
('+919039150125', 'SID951373077662'),
('+916201078807', 'SSF3352820'),
('+917984012717', 'SID951376182528'),
('+917023258933', 'SSF4019748'),
('+916207778121', 'SSF3216752'),
('+918122850360', 'SSF5837056'),
('+917394002203', 'SSF5609301'),
('+918770018966', 'SID951374787012'),
('+919755811710', 'SSF3822948'),
('+917489274586', 'SID951374708652'),
('+919241177997', 'SSF5619652'),
('+917849976563', 'SID951375343318'),
('+917520230917', 'SSF5339291'),
('+916204272660', 'SSF5318511'),
('+919216378820', 'SID951375687986'),
('+919981974118', 'CID064700770'),
('+917766812910', 'SSF3537427'),
('+918409496935', 'SID951374511505'),
('+918052015459', 'SSF4675156'),
('+917583017590', 'SID951375940512'),
('+919889036922', 'SSF3695218'),
('+917976451485', 'SSF2464345'),
('+918382819885', 'SSF4978425'),
('+919669450855', 'SID951373667129'),
('+918827036451', 'CID218100356'),
('+917378993880', 'SSF5250319'),
('+918565325486', 'SID951374197805'),
('+918810906578', 'SSF3103431'),
('+917803970496', 'SID951373146416'),
('+917061135408', 'SID951375867293'),
('+917479549867', 'SSF3533887'),
('+919508261157', 'SSF5471532'),
('+917566906019', 'SSF3060883'),
('+918719906105', 'SID2125390534'),
('+918602738407', 'SSF3830534'),
('+919199822144', 'SSF4865952'),
('+919420024174', 'SSF5020388'),
('+917870026167', 'SID951374431033'),
('+917654663675', 'SSF2859660'),
('+919973804253', 'SID951376023356'),
('+919064080065', 'SSF2894232'),
('+916353765037', 'SSF5840110'),
('+916268255087', 'SSF5784634'),
('+916200136418', 'SSF5688977'),
('+916376552931', 'SSF5195188'),
('+916299869018', 'SSF5754795'),
('+916261127539', 'SSF5733827'),
('+916353063662', 'SSF5922278'),
('+916280543081', 'SSF4190084'),
('+916287103287', 'SSF5927945'),
('+917338096744', 'SSF5591848'),
('+917879268710', 'SSF5175087'),
('+917806094664', 'SSF3326717'),
('+917909881335', 'SSF5602738'),
('+917404298463', 'SSF4524430'),
('+917549971519', 'SSF5727659'),
('+917739620522', 'SSF5718577'),
('+917416582389', 'SSF4659310'),
('+917260910452', 'SSF5662369'),
('+917388328751', 'SSF5585885'),
('+917033928139', 'SSF5631841'),
('+917766838711', 'SSF5712251'),
('+917619382904', 'SSF5651700'),
('+917061169897', 'SSF3301183'),
('+917549114086', 'SSF5709117'),
('+917366912851', 'SSF5334264'),
('+917294978626', 'SSF5715676'),
('+917856036974', 'SSF5907344'),
('+917280053654', 'SSF5649364'),
('+917651876435', 'SSF5772433'),
('+917050598601', 'SSF5618599'),
('+918787434043', 'SSF5711060'),
('+918595421417', 'SSF5710855'),
('+918294924809', 'SSF5706917'),
('+918757686662', 'SSF5727641'),
('+918873177606', 'SSF5727628'),
('+918207622719', 'SSF5692301'),
('+918521719573', 'SSF5765474'),
('+918815486864', 'SSF4347523'),
('+918002750588', 'SSF5919515'),
('+918292807414', 'SSF3353400'),
('+918757416195', 'SSF5627481'),
('+918797368734', 'SSF5767348'),
('+919263209438', 'SSF3580808'),
('+919575424125', 'SSF5547008'),
('+919529913620', 'SSF3860105'),
('+919977232557', 'SSF3555973'),
('+919905554290', 'SSF5566218'),
('+919306822066', 'SSF5698572'),
('+919641966931', 'SSF5738404'),
('+919608503358', 'SSF5745322'),
('+919801399838', 'SSF5380569'),
('+919234970145', 'SSF5647129'),
('+919801153906', 'SSF5676358'),
('+919131213988', 'SSF5190694'),
('+919142069552', 'SSF5583273'),
('+919241463513', 'SSF5624807'),
('+919263998553', 'SSF5102095'),
('+919234199710', 'SSF5668342'),
('+919399206923', 'SSF3528772'),
('+919279159238', 'SSF5621093'),
('+919302243647', 'SSF5729040'),
('+919244965370', 'SSF3631460'),
('+919128659733', 'SSF5706922'),
('+919801262764', 'SID951375665036'),
('+919065840743', 'SSF3940123'),
('+919241159020', 'SSF5759732'),
('+919128068006', 'SSF5641495'),
('+919905135244', 'SSF5775751'),
('+919516545136', 'SSF5698860'),
('+919199901173', 'SSF5788782'),
('+919794741096', 'SSF5550738'),
('+919508127013', 'SSF5686591'),
('+917389805083', 'SID951373573683'),
('+919399912788', 'SID951375879556'),
('+916266299045', 'SSF3577935'),
('+917292921230', 'SSF5584136'),
('+917970969103', 'SSF5500066'),
('+917479454425', 'SSF5402073'),
('+917654559731', 'SSF5303428'),
('+917480976682', 'SSF3356600'),
('+917587885267', 'SSF3436687'),
('+917856917463', 'SSF5717180'),
('+918269922604', 'SSF4041975'),
('+918690587317', 'SSF5862219'),
('+918271368091', 'SSF5618438'),
('+918920519451', 'SSF5563027'),
('+919229066250', 'SSF4071310'),
('+919817446385', 'SSF5643804'),
('+919973708887', 'SSF5611174'),
('+919117525486', 'SSF5646796'),
('+919798901428', 'SSF3413447'),
('+919800584425', 'SSF3056608'),
('+919523792675', 'SSF5552526'),
('+919936801418', 'SSF5918443'),
('+917549957281', 'SSF5722120'),
('+919122638742', 'SSF5771098'),
('+919199985010', 'SSF5672751'),
('+919559928394', 'SSF4071074'),
('+916204174960', 'SSF5449648'),
('+917070941092', 'SSF6073109'),
('+918603926092', 'SSF5700920'),
('+918235845151', 'SSF6042026'),
('+918837630095', 'SSF6048845'),
('+918491948573', 'SSF5356385'),
('+919304884820', 'SSF5722551'),
('+919350210751', 'SSF5504371'),
('+919014919270', 'SSF6105353'),
('+919031873484', 'SSF5375498'),
('+917347069584', 'SSF5477699'),
('+917667447214', 'SSF5450451'),
('+918052802535', 'SSF5806860'),
('+918757515365', 'SSF5777476'),
('+919711368561', 'SSF4210283'),
('+919162962462', 'SSF5478101'),
('+917000628027', 'CID224401918'),
('+918603561323', 'SID951374604127'),
('+916207849251', 'SSF2598314'),
('+918839102329', 'SSF2458904'),
('+919205443040', 'SID951376169583'),
('+917061291708', 'SSF5428697'),
('+917783083171', 'SSF5776115'),
('+917050517992', 'SSF5934703'),
('+917321826585', 'SSF5339321'),
('+917398631718', 'SSF5921852'),
('+918579019761', 'SSF5644911'),
('+918756645352', 'SSF6209269'),
('+918252488411', 'SSF5576522'),
('+919104095312', 'SSF5867603'),
('+919955440706', 'SSF5934700'),
('+916350534274', 'SSF5299329'),
('+916201039558', 'SSF3259879'),
('+916201248049', 'SSF5340747'),
('+916263298694', 'SSF5157130'),
('+916202423839', 'SSF5418869'),
('+916394791758', 'SSF5419294'),
('+917991938044', 'SSF5256966'),
('+917879201413', 'SSF5213989'),
('+917644923427', 'SSF5394180'),
('+917321033324', 'SSF5375718'),
('+917462012999', 'SSF4927701'),
('+917974555609', 'SSF5319030'),
('+917322945052', 'SSF5166743'),
('+917898344338', 'SSF3782374'),
('+917050296639', 'SSF5268574'),
('+917041171945', 'SSF5533658'),
('+917320907279', 'SSF4990926'),
('+917250644114', 'SSF5277466'),
('+918298112562', 'SSF5170910'),
('+918002920112', 'SSF5323493'),
('+918873099260', 'SSF5408681'),
('+918409786669', 'SSF5319365'),
('+918769923155', 'SSF3628596'),
('+918955484055', 'SSF5351817'),
('+918797485660', 'SSF5157026'),
('+918770983304', 'SSF3409125'),
('+918770742321', 'SSF4930885'),
('+918651399434', 'SSF5178768'),
('+918986836155', 'SSF2552563'),
('+918084666202', 'SSF4782604'),
('+918651511408', 'SSF5176626'),
('+918233317721', 'SSF3620382'),
('+918092010121', 'SSF5261039'),
('+919153955214', 'SSF5353653'),
('+919570613914', 'SSF3011583'),
('+919031784023', 'SSF5339297'),
('+919631992806', 'SSF5330105'),
('+919153206705', 'SSF3184905'),
('+919023259329', 'SSF5188947'),
('+919234922881', 'SSF5321579'),
('+919628337110', 'SSF3619938'),
('+919244706697', 'SSF5380678'),
('+919770492839', 'SID951375372492'),
('+919234700947', 'SSF5559178'),
('+919993195805', 'SSF3635030'),
('+919329074861', 'SSF5333612'),
('+919279531230', 'SSF5204245'),
('+919199820277', 'SSF5977220'),
('+919016037024', 'SSF5248912'),
('+919122934718', 'SSF3079170'),
('+919304704456', 'SSF5210937'),
('+919279985613', 'SSF5278686'),
('+919934732272', 'SSF5784773'),
('+918757332823', 'SSF5606002'),
('+919798026743', 'SSF4966631'),
('+918757591989', 'SID2125011165'),
('+917033512809', 'SSF6183506'),
('+917461887987', 'SSF5364518'),
('+918081467218', 'SSF6044952'),
('+918207458264', 'SSF5254367'),
('+919198953078', 'SSF5149678'),
('+916204226166', 'SSF5134050'),
('+916287548464', 'SID951374353995'),
('+916206956713', 'SID951374100041'),
('+916206009447', 'SSF4540195'),
('+916207466361', 'SID951376217237'),
('+916375450131', 'SSF5088589'),
('+916207756599', 'SSF5807215'),
('+917061952097', 'SSF4927589'),
('+917061620284', 'SSF5611446'),
('+917633822757', 'SSF4961637'),
('+917033870152', 'SSF5138170'),
('+917644926431', 'SSF4959446'),
('+917070573699', 'SSF2743711'),
('+917667798828', 'SSF5222626'),
('+917070819459', 'SSF4117412'),
('+917488351983', 'SSF4929164'),
('+917547043617', 'SSF5207237'),
('+918434052023', 'SSF5163681'),
('+918102943339', 'SSF4187642'),
('+918092766058', 'SSF5168486'),
('+918949408087', 'SSF5012389'),
('+918102807772', 'SSF4878710'),
('+918252907722', 'SSF5159515'),
('+918873211084', 'SSF5125595'),
('+918174929095', 'SSF4926307'),
('+918092882019', 'SSF5192908'),
('+919653494836', 'SSF4552899'),
('+919993009020', 'SSF3041630'),
('+919329860389', 'SSF2661027'),
('+919153725328', 'SSF3108268'),
('+919680052063', 'SSF5141365'),
('+919065185701', 'SSF5138106'),
('+919784186738', 'SSF5132202'),
('+919153175760', 'SSF3878035'),
('+919798986181', 'SSF4983267'),
('+919905118184', 'SSF5151627'),
('+919304568121', 'SSF4677004'),
('+919153270150', 'SSF5103629'),
('+919608283594', 'SID951372822573'),
('+919009826108', 'SSF4892397'),
('+919939927093', 'SSF5134740'),
('+919060443503', 'SSF3907353'),
('+917033429762', 'SSF5483933'),
('+918090277172', 'SSF5804876'),
('+917050426995', 'SSF6003661'),
('+917070030640', 'SSF4792517'),
('+919835803596', 'SSF4623946'),
('+919334867732', 'SSF3363924'),
('+919279104620', 'SSF5989666'),
('+918102364696', 'SSF5335409'),
('+917542985337', 'SSF5976799'),
('+917667014820', 'SSF6277466'),
('+918757189566', 'SSF6227619'),
('+918578861065', 'SSF6033067'),
('+919279119576', 'SSF4957054'),
('+919570246217', 'SSF6295057'),
('+919570524107', 'SSF6306413'),
('+919155827514', 'SSF6190063'),
('+919631979827', 'SSF6187426'),
('+918102973853', 'SID2125140185'),
('+916207309832', 'SSF4621506'),
('+916204066288', 'SSF5048061'),
('+917728069078', 'SID951374729671'),
('+917737904505', 'SSF4606173'),
('+917231050790', 'SSF4452313'),
('+917631531148', 'SSF4243505'),
('+917978219707', 'SSF4552485'),
('+917000439021', 'SSF4165157'),
('+917209403379', 'SSF5096899'),
('+917470727543', 'SSF4539867'),
('+917388646541', 'SSF4544527'),
('+917979956990', 'SID951375385290'),
('+917879838554', 'SSF4684867'),
('+917426965293', 'SSF4305017'),
('+917491877189', 'SSF4655883'),
('+917067890343', 'SSF3463149'),
('+917803943783', 'SSF4638607'),
('+917368991985', 'SSF4559092'),
('+917366019380', 'SSF4724487'),
('+917070850550', 'SSF4556770'),
('+917667060965', 'SSF4654297'),
('+917318189723', 'SSF4196204'),
('+917393987128', 'SSF4536511'),
('+917294174322', 'SSF4613485'),
('+917041030044', 'SSF4627106'),
('+917050941782', 'SSF4662621'),
('+918003358535', 'SSF4449978'),
('+918080661494', 'SSF5007247'),
('+918239694845', 'SSF5214859'),
('+918235135099', 'SSF4568715'),
('+918092604242', 'SSF4392919'),
('+918102130775', 'SSF4572644'),
('+918757278771', 'SSF3487113'),
('+918209756209', 'SSF4795051'),
('+918757981365', 'SSF4698726'),
('+918815090227', 'SSF5319657'),
('+918298129637', 'SSF4628736'),
('+918770019064', 'SSF5190578'),
('+918358037028', 'SSF4836855'),
('+918827338913', 'SSF4590937'),
('+918521343846', 'SSF4741806'),
('+919610355191', 'SSF5266668'),
('+919764689959', 'SID951375453064'),
('+919166452341', 'SSF4559874'),
('+919006374682', 'SID951375292092'),
('+919306960261', 'SSF3449735'),
('+919680199682', 'SSF4554038'),
('+919155737136', 'SSF4321185'),
('+919065947478', 'SSF4558720'),
('+919171734081', 'SSF4760194'),
('+919709001843', 'SSF4545085'),
('+919770254909', 'SSF4831819'),
('+919340283464', 'SSF3508893'),
('+919771112105', 'SSF3191804'),
('+919244504587', 'SSF4729149'),
('+919117910358', 'SSF4655957'),
('+919131909822', 'SSF4648086'),
('+919303312671', 'SSF4727119'),
('+919365301957', 'SSF4603365'),
('+919142476774', 'SSF4738774'),
('+919336683723', 'SSF3196215'),
('+919525356397', 'SSF4567696'),
('+919560938560', 'SSF4315712'),
('+919631299819', 'SSF4732897'),
('+919826651698', 'SID951375032242'),
('+919307553251', 'SSF4558007'),
('+919026539419', 'SSF3156844'),
('+919955627010', 'SSF4480223'),
('+916307263661', 'SSF6158468'),
('+916206346691', 'SSF6056360'),
('+916287562140', 'SSF5544251'),
('+917717646305', 'SSF5583394'),
('+917091443591', 'SSF5544244'),
('+918858029084', 'SSF6119514'),
('+918218980354', 'SSF5975360'),
('+919548218253', 'SSF5849918'),
('+919725962645', 'SSF5977962'),
('+919905596351', 'SSF6003485'),
('+918084710092', 'SSF4202446'),
('+916351597855', 'SSF5603414'),
('+917909721134', 'SSF5979493'),
('+917479801492', 'SSF5556041'),
('+918619531033', 'SSF5973410'),
('+918076162830', 'SSF5434049'),
('+919162214100', 'SSF5745969'),
('+919234039226', 'SSF5699652'),
('+919592477928', 'SSF5943245'),
('+918173999394', 'SSF6165953'),
('+919931627273', 'SSF6034475'),
('+916376451022', 'SSF4349866'),
('+916296453547', 'SSF3352067'),
('+916207546903', 'SID951373393797'),
('+916204353886', 'SSF4411531'),
('+916375291781', 'SSF2913065'),
('+916375324592', 'SSF4356545'),
('+916377585016', 'SSF4356569'),
('+916209899025', 'SSF4599202'),
('+916376526449', 'SSF4482168'),
('+916395285625', 'SID951376070539'),
('+916204854443', 'SSF4404792'),
('+916299168466', 'SSF4146672'),
('+916205953165', 'SSF4331173'),
('+916367103132', 'SSF4394287'),
('+916268343693', 'SSF4530472'),
('+916350290498', 'SSF4148368'),
('+917479426592', 'SSF3761641'),
('+917091520759', 'SSF3016574'),
('+917258879069', 'SSF4578622'),
('+917908797602', 'SSF3401521'),
('+917987452674', 'SSF4437250'),
('+917545893858', 'SSF5015107'),
('+917568010463', 'SSF4453810'),
('+917016221936', 'SSF5264872'),
('+917733721259', 'SSF2690453'),
('+917033997708', 'SSF4569395'),
('+917091623604', 'SSF4557209'),
('+917413006543', 'SSF4393922'),
('+917646087952', 'SSF4515967'),
('+917203268438', 'SID951375386505'),
('+917482969923', 'SSF4614078'),
('+917067204757', 'SID951375455519'),
('+917427859217', 'SSF4362349'),
('+917543029656', 'CID951376207826'),
('+917772924248', 'SSF4255971'),
('+917895784924', 'SSF4322666'),
('+917807608854', 'SSF3907994'),
('+917818997191', 'SSF4567148'),
('+917366802134', 'SSF4568014'),
('+917277097864', 'SSF4551287'),
('+918305285646', 'SSF3704209'),
('+918103339408', 'SSF4511893'),
('+918104390323', 'SID951376049447'),
('+918619831461', 'SSF4724983'),
('+918962968284', 'SSF4634718'),
('+918696360616', 'SSF4966182'),
('+918890305553', 'SSF2949427'),
('+918538936731', 'SSF3015934'),
('+918529603662', 'SSF2490046'),
('+918852057722', 'SSF4287694'),
('+918504947715', 'SSF4086421'),
('+918115864738', 'SSF4463012'),
('+918797009665', 'SSF4331157'),
('+918484078495', 'SID951376135882'),
('+918409801074', 'SSF4332819'),
('+918949104426', 'SSF4449210'),
('+918955543563', 'SSF4571778'),
('+918809644812', 'SSF2508682'),
('+918235295407', 'SSF4319861'),
('+918875243540', 'SSF4392649'),
('+918434085245', 'SSF2315640'),
('+919950482388', 'SSF4412404'),
('+919653972457', 'SID951376011799'),
('+919770967187', 'SSF4530274'),
('+919113401497', 'SSF4394430'),
('+919636164634', 'SSF4905469'),
('+919256939276', 'SSF3978413'),
('+919279713332', 'SSF4574408'),
('+919334851010', 'SSF4359968'),
('+919162942840', 'SSF4417051'),
('+919983124804', 'SSF4097788'),
('+919244137455', 'SID951373618622'),
('+919303765177', 'SSF4476106'),
('+919931714243', 'SSF4560902'),
('+919106794483', 'SSF4562451'),
('+919170683972', 'SSF4021108'),
('+919334500388', 'SSF4415818'),
('+919636996339', 'SSF2390580'),
('+919199385783', 'SSF2915091'),
('+919872934118', 'SSF4388640'),
('+919399708299', 'SSF4540148'),
('+919153414279', 'SSF4780068'),
('+919660126358', 'SSF4592663'),
('+919078754664', 'SSF2328455'),
('+919257915539', 'SSF4375179'),
('+919507699795', 'SID951375171959'),
('+919828374761', 'SSF4316986'),
('+919065968292', 'SSF4407317'),
('+917033911559', 'SSF6069944'),
('+917463955121', 'SSF5649675'),
('+919905662472', 'SSF6024027'),
('+919344261031', 'SSF4805443'),
('+917039693769', 'SSF5975995'),
('+917060133278', 'SSF5833004'),
('+918421942398', 'SSF5975896'),
('+919199988341', 'SSF5332310'),
('+916387632451', 'SSF4951348'),
('+918271868667', 'SSF6021221'),
('+919852056373', 'SSF6047922'),
('+919546078996', 'SSF6022328'),
('+917783065563', 'SSF4299850'),
('+918875713992', 'SSF4162181'),
('+919510706625', 'SSF4385314'),
('+919252410570', 'SSF4237426'),
('+919691681587', 'SSF4231209'),
('+917518709332', 'SSF4478617'),
('+919140562458', 'SSF4557212'),
('+917897263602', 'SSF5948498'),
('+918381912760', 'SSF5926600'),
('+918051840612', 'SSF5734655'),
('+916205902127', 'SSF4137668'),
('+916378949566', 'SSF4054345'),
('+916350391952', 'SSF4108636'),
('+916201063290', 'SSF4473387'),
('+916375436826', 'SSF4065205'),
('+917482810279', 'SSF4034366'),
('+917091918908', 'SSF4028357'),
('+917737132449', 'SSF3317851'),
('+917489635574', 'SSF4019014'),
('+917340117158', 'SSF3991757'),
('+917739541010', 'SSF4307013'),
('+917985873799', 'CID951376208468'),
('+917665035189', 'SSF2572948'),
('+917976847545', 'SSF4173586'),
('+917849962016', 'SSF4051173'),
('+917091117019', 'SSF3252311'),
('+917340420505', 'SSF4482955'),
('+917878592204', 'SSF4473111'),
('+917339929570', 'SSF4459488'),
('+917850066020', 'SSF4351651'),
('+918619399443', 'SSF4191730'),
('+918103118393', 'SSF4073517'),
('+918003188384', 'SSF4061086'),
('+918541866957', 'SSF4015394'),
('+918577030692', 'CID951376208471'),
('+918209140282', 'SSF4033431'),
('+918959812434', 'SSF4050209'),
('+918094729632', 'SSF4036365'),
('+918890549621', 'SSF4761253'),
('+918005630192', 'SSF3979595'),
('+918603330576', 'SSF4123619'),
('+918409775791', 'SSF4388645'),
('+918302099105', 'SSF4024776'),
('+918094523847', 'SSF4121321'),
('+918529276903', 'SSF4405390'),
('+918708208890', 'SSF2575423'),
('+918529652262', 'SSF3943143'),
('+919026706991', 'SSF4082558'),
('+919142373823', 'SSF4207295'),
('+919162800565', 'SSF2994953'),
('+919155742906', 'SSF4484645'),
('+919602773932', 'SSF3991775'),
('+919024118071', 'SSF3917346'),
('+919929296681', 'SID951374874409'),
('+919587291395', 'SSF4061075'),
('+919653916517', 'SSF4293773'),
('+919840697513', 'SSF4035477'),
('+919658445853', 'SSF3651418'),
('+919376194204', 'SSF4041506'),
('+919166753893', 'SSF3786752'),
('+919257149128', 'SSF4131535'),
('+919982237346', 'SSF3783821'),
('+919256234512', 'SSF4006916'),
('+919974491791', 'SSF4008668'),
('+919119248036', 'SSF4071033'),
('+919001191486', 'SSF4481008'),
('+919998148998', 'SID951376029637'),
('+919602411357', 'SSF3917886'),
('+919772235217', 'SSF4050223'),
('+919601611027', 'SSF3959658'),
('+919554434217', 'SSF4514400'),
('+916665556665', 'SSF3895803'),
('+916377266439', 'SSF3969963'),
('+917878215608', 'SSF2527888'),
('+917357697961', 'SSF3933341'),
('+917737624944', 'SSF3989594'),
('+917073608389', 'SSF4040203'),
('+917891163950', 'SSF3902954'),
('+917461841256', 'SSF3901315'),
('+917549825985', 'SSF3578274'),
('+917414889751', 'SSF3779496'),
('+918655558858', 'SSF3650809'),
('+918567679979', 'SSF3603955'),
('+918578467648', 'SID951375565037'),
('+918302795701', 'SSF3967275'),
('+918815624718', 'SSF4393774'),
('+918233481190', 'SSF3881279'),
('+918107196237', 'SSF3098521'),
('+918852975883', 'SSF4072466'),
('+918809690773', 'SID951375908812'),
('+918654668478', 'SSF3895747'),
('+918078618998', 'SSF3165016'),
('+918563217962', 'SID951374517322'),
('+918461013446', 'SSF3578249'),
('+918696046821', 'SSF3851272'),
('+918596745263', 'SSF2505397'),
('+919263210331', 'SSF3874465'),
('+919646010127', 'SSF3885899'),
('+919256875828', 'SSF4040238'),
('+919079396663', 'SSF3927212'),
('+919257747425', 'SSF3891962'),
('+919279169118', 'SSF3839665'),
('+919658967489', 'SSF3534903'),
('+919111707082', 'SSF3779597'),
('+919828453551', 'SSF3862335'),
('+919279515738', 'SSF4310432'),
('+919958471552', 'SSF3980786'),
('+919560394815', 'SID951375061863'),
('+919509196725', 'SSF4076427'),
('+916351633580', 'SSF3400564'),
('+917024215403', 'SSF4201231'),
('+918349943385', 'SSF4318376'),
('+918875727123', 'SSF3578639'),
('+918709794649', 'SSF3366921'),
('+918696501583', 'SSF2362809'),
('+919794949499', 'SSF3600318'),
('+919734818457', 'SSF3424157'),
('+919343779750', 'SSF3973465'),
('+919179085693', 'SSF4035570'),
('+918603644723', 'SSF3248382'),
('+916565868699', 'SSF3663495'),
('+916688388989', 'SSF3663493'),
('+916367558371', 'SSF3598726'),
('+917764013175', 'SSF3544969'),
('+917686838383', 'SSF3663313'),
('+917979797997', 'SSF3744785'),
('+917551698536', 'SSF3318790'),
('+917869834420', 'SSF5215226'),
('+918888888888', 'SSF2547961'),
('+918233931341', 'SSF3804130'),
('+918464646838', 'SSF3663315'),
('+918784512156', 'SSF3707094'),
('+918003223797', 'SSF3723840'),
('+919602662892', 'SSF3844038'),
('+919498656164', 'SSF3654415'),
('+919946755775', 'SSF3403738'),
('+919365941623', 'SSF3574566'),
('+919825416536', 'SSF3051694'),
('+919654854498', 'SSF3743838'),
('+919735518945', 'SSF3374250'),
('+919882672677', 'SSF3630224'),
('+919549708447', 'SSF4037116'),
('+919685328885', 'SSF2353802'),
('+919928496328', 'SSF3781902'),
('+917367086349', 'SSF5188398'),
('+919798117006', 'SSF6073289'),
('+917479901603', 'SSF5413998'),
('+917206230855', 'SSF5936706'),
('+917296983572', 'SSF5868341'),
('+918953608299', 'SSF4352633'),
('+918340149549', 'SSF5514102'),
('+917461855687', 'SSF5527474'),
('+918862996507', 'SSF3469629'),
('+917655349994', 'SSF3371471'),
('+918254879874', 'SSF3272155'),
('+918619481581', 'SSF3761116'),
('+918307126164', 'SSF3324918'),
('+919852542858', 'SSF3444757'),
('+919523558875', 'SSF3373026'),
('+919952252155', 'SSF3372915'),
('+919080803318', 'SSF3366253'),
('+919636352496', 'SSF3375930'),
('+919768799798', 'SSF3574784'),
('+917785787737', 'SSF3354928'),
('+918059808909', 'SSF3099361'),
('+919546166089', 'SID951375838937'),
('+917042086623', 'SSF2798476'),
('+917224916749', 'SSF2950653'),
('+917310392523', 'SSF2419741'),
('+917488814865', 'SSF2780226'),
('+918108954069', 'SSF2492023'),
('+918292955918', 'SSF2619870'),
('+916265696781', 'SSF5736066'),
('+916206574462', 'SSF5912062'),
('+916287243412', 'SSF5664273'),
('+916204181730', 'SSF5431824'),
('+916388010507', 'SSF5672973'),
('+916203404051', 'SSF5551925'),
('+917366012992', 'SSF5311687'),
('+917396642863', 'SSF5938770'),
('+917748845223', 'SSF5467550'),
('+917498380676', 'SSF5827848'),
('+917763841991', 'SSF5720199'),
('+917091617142', 'SSF3189688'),
('+917061252841', 'SSF5664783'),
('+917856901486', 'SSF3378001'),
('+917480005059', 'SSF5483825'),
('+917461069758', 'SSF5715635'),
('+917631823824', 'SSF5709261'),
('+917543048798', 'SSF5763465'),
('+917033171246', 'SSF5702847'),
('+917654819927', 'SSF5647689'),
('+917070656647', 'SSF5697077'),
('+917545835890', 'SSF5586099'),
('+917367014384', 'SSF5115127'),
('+917319713812', 'SSF5841555'),
('+918873900467', 'SSF5708288'),
('+918000120859', 'SSF5715666'),
('+918284099254', 'SSF5727626'),
('+918809201640', 'SSF3770853'),
('+918595477567', 'SSF2756529'),
('+918873044397', 'SSF5617019'),
('+918809337311', 'SSF5590542'),
('+918002869945', 'SSF5738986'),
('+918434766148', 'SSF5782662'),
('+918579810026', 'SSF5644534'),
('+918235733918', 'SSF5646019'),
('+918102833128', 'SSF5638246'),
('+918294943610', 'SSF5709348'),
('+918333077432', 'SSF3363086'),
('+918102920952', 'SSF5861800'),
('+918603420859', 'SSF5651209'),
('+919693054265', 'SSF3831689'),
('+919801346709', 'SSF5644852'),
('+919798094352', 'SSF5576404'),
('+919905476892', 'SSF5582443'),
('+919311514062', 'SSF5674293'),
('+919661923193', 'SSF5739377'),
('+919931484216', 'SSF3679492'),
('+919608744797', 'SSF2705960'),
('+919327496054', 'SSF3223528'),
('+919234329725', 'SSF5638499'),
('+919754041517', 'SSF5921056'),
('+919835909903', 'SSF5206247'),
('+919352135712', 'SSF5657141'),
('+919343119662', 'SSF5734845'),
('+919065240855', 'SSF5709454'),
('+919102508215', 'SSF5906299'),
('+919199478929', 'SSF5440172'),
('+919023041794', 'SSF5767337'),
('+917061066918', 'SID951374913508'),
('+917258056241', 'SID951375228015'),
('+917696375370', 'SID951374804276'),
('+918409886289', 'SSF2281509'),
('+919334557386', 'SSF2557975'),
('+916264613783', 'SSF4192753'),
('+916266040971', 'SSF5411009'),
('+916393268037', 'SSF5399152'),
('+916299967780', 'SSF5585981'),
('+916268932708', 'SSF5354460'),
('+916287617099', 'SSF5441408'),
('+916266547943', 'SSF5594363'),
('+916205954247', 'SSF3898265'),
('+916204865801', 'SSF4872169'),
('+917580822919', 'SSF5716849'),
('+917828090879', 'SSF3708661'),
('+917974271186', 'SSF5750653'),
('+917004798237', 'SSF5620113'),
('+917970934852', 'SSF5321405'),
('+917857059099', 'SSF5522638'),
('+917482997170', 'SSF3199511'),
('+917323985534', 'SSF5716490'),
('+917054979927', 'SSF5733537'),
('+917667281647', 'SSF5182150'),
('+917488934237', 'SSF5716583'),
('+917247476630', 'SSF6547670'),
('+917479632129', 'SSF2361914'),
('+917250235350', 'SSF3348503'),
('+917479419042', 'SSF5741241'),
('+917992709471', 'SSF5355603'),
('+917888497746', 'SSF5472781'),
('+917545845215', 'SSF5476031'),
('+917870873450', 'SSF5635762'),
('+917294996619', 'SSF5479455'),
('+917667505097', 'SSF5857713'),
('+917828635790', 'SSF5526358'),
('+917722967346', 'SSF4648122'),
('+917904868890', 'SSF5413601'),
('+917033130927', 'SSF5380273'),
('+917041063433', 'SSF5385759'),
('+917488860097', 'SSF5460899'),
('+917766887560', 'SSF5699588'),
('+917870023316', 'SSF5282067'),
('+917479974527', 'SSF5434944'),
('+917070530957', 'SSF5497921'),
('+917294913988', 'SSF5404117'),
('+917700894769', 'SSF4935486'),
('+917488625304', 'SSF5653429'),
('+917250912628', 'SSF5335384'),
('+917739426889', 'SSF5611395'),
('+917349916181', 'SSF2381009'),
('+917878535158', 'SSF5386546'),
('+917488081931', 'SSF5574129'),
('+917739215114', 'SSF5386753'),
('+917765824559', 'SSF5620631'),
('+917070831488', 'SSF5518791'),
('+917319885402', 'SSF4687392'),
('+917870101803', 'SSF5630579'),
('+917484893775', 'SSF5552200'),
('+918092651652', 'SSF5466685'),
('+918127882295', 'SSF5737009'),
('+918010977804', 'SSF5542035'),
('+918109182703', 'SSF4531365'),
('+918809281003', 'SSF5736234'),
('+918092776873', 'SSF5427163'),
('+918007575626', 'SSF4871776'),
('+918856927401', 'SSF5468946'),
('+918818833962', 'SSF6544843'),
('+918603299107', 'SSF5388354'),
('+918319336588', 'SSF5327508'),
('+918302804585', 'SSF5167865'),
('+918780859395', 'SSF5892535'),
('+918088541266', 'SSF5428241'),
('+918210324360', 'SSF5372801'),
('+918084650115', 'SSF5384626'),
('+918292667634', 'SSF5685192'),
('+918521311361', 'SSF5701400'),
('+918434098591', 'SSF5515322'),
('+918340362760', 'SSF4174797'),
('+918651110688', 'SSF5414088'),
('+918292037970', 'SSF5612612'),
('+919241603731', 'SSF5546734'),
('+919472547833', 'SSF5382333'),
('+919905037095', 'SSF4226805'),
('+919241864691', 'SSF5537972'),
('+919199297687', 'SSF5408351'),
('+919341443743', 'SID951374457570'),
('+919329694119', 'SSF3299548'),
('+919817063979', 'SSF5716843'),
('+919234593936', 'SSF3768168'),
('+919602520285', 'SSF5104834'),
('+919142539533', 'SSF5420696'),
('+919006537072', 'SSF5208696'),
('+919345168705', 'SSF4848829'),
('+919472328106', 'SSF4048586'),
('+919241748771', 'SSF4699447'),
('+919516741001', 'SSF6545536'),
('+919241397987', 'SSF5368568'),
('+919534027754', 'SSF4523984'),
('+919155580705', 'SSF5510307'),
('+919631170426', 'SSF5134292'),
('+919279424822', 'SSF3534075'),
('+919155214292', 'SSF5432346'),
('+919399723936', 'SSF4480882'),
('+919155909628', 'SSF5466586'),
('+919279707474', 'SSF4510170'),
('+919279925086', 'SSF5515040'),
('+919871176071', 'SSF5506473'),
('+919128753307', 'SSF5366220'),
('+919890752618', 'SSF5335282'),
('+919031548617', 'SSF5335285'),
('+919102772183', 'SSF5610968'),
('+919279636491', 'SSF5439778'),
('+919102281163', 'SSF5335520'),
('+919233259926', 'SSF3539900'),
('+919105598023', 'SSF2942941'),
('+919113480313', 'SSF5161197'),
('+919572587241', 'SSF5429094'),
('+919523173535', 'SSF5707613'),
('+919771017383', 'SSF5096918'),
('+919059513282', 'SSF4316237'),
('+919510086490', 'SSF5794431'),
('+919238681710', 'SSF5287298'),
('+919060496579', 'SSF5552148'),
('+919155741250', 'SSF5534387'),
('+917903173501', 'SSF6047414'),
('+918382967103', 'SSF5977763'),
('+919934763752', 'SSF5622050'),
('+916206013185', 'SSF6037398'),
('+917643987967', 'SSF5697171'),
('+917488967030', 'SSF5580425'),
('+917292944868', 'SSF4681358'),
('+918287618025', 'SSF5610983'),
('+918877703537', 'SSF5722113'),
('+918528693203', 'SSF5741778'),
('+918318302054', 'SSF5685277'),
('+919429768485', 'SSF5767124'),
('+917033511236', 'SSF6167882'),
('+919570632422', 'SSF5294411'),
('+919234007512', 'SSF5477597'),
('+919036439352', 'SSF5748740'),
('+917626879395', 'SSF5545085'),
('+917463896384', 'SSF5496990'),
('+918540840130', 'SSF5467825'),
('+919304957663', 'SSF4639968'),
('+918769717586', 'SID951375181956'),
('+919523301469', 'SID951374864773'),
('+919680922034', 'SID951374951789'),
('+919329365404', 'SID2125596678'),
('+919670244690', 'SSF2420025'),
('+918009856411', 'SSF5693847'),
('+916267883436', 'SSF5326278'),
('+916392978058', 'SSF2864577'),
('+916267177510', 'SSF2986834'),
('+917488681286', 'SSF2689357'),
('+917389559155', 'SSF5077297'),
('+917645046556', 'SSF2686450'),
('+917907317114', 'SSF5389046'),
('+918209431099', 'SSF5446160'),
('+918294021414', 'SSF2300484'),
('+918757603256', 'SSF3214043'),
('+918604805989', 'SSF2844330'),
('+919234650886', 'SSF5338150'),
('+919334548473', 'SSF5326349'),
('+919125883586', 'SSF2285940'),
('+919125881511', 'SSF5393380'),
('+919155886306', 'SSF5336206'),
('+919472944503', 'SSF5409192'),
('+919207661363', 'SSF5389008'),
('+919508070912', 'SSF5413021'),
('+919229080829', 'SSF5981042'),
('+919166997938', 'SSF5467174'),
('+919303254480', 'SSF5629792'),
('+919509483633', 'SSF5179956'),
('+919327214537', 'SSF4855587'),
('+919351542554', 'SSF4855468'),
('+919354716232', 'SSF5095730'),
('+919264104207', 'SSF5377826'),
('+916201460073', 'SSF2610544'),
('+916202595429', 'SSF2610542'),
('+916206366526', 'SSF5157510'),
('+916206439498', 'SSF3499326'),
('+916203406438', 'SSF5239322'),
('+917295052996', 'SSF5174737'),
('+917361059725', 'SSF5168648'),
('+917318195087', 'SSF4481680'),
('+917432825989', 'SSF3384405'),
('+917091043488', 'SSF3537480'),
('+917587261504', 'SSF4722854'),
('+917727092710', 'SSF5136392'),
('+917070918302', 'SSF5175048'),
('+917563855126', 'SSF5176226'),
('+917371083972', 'SSF5168386'),
('+917645073072', 'SSF5125607'),
('+917903093859', 'SSF5132136'),
('+917061964338', 'SSF5158413'),
('+917782981887', 'SSF4242037'),
('+917488875093', 'SSF5222405'),
('+918294907093', 'SSF2723026'),
('+918235063179', 'SSF3380470'),
('+918541965568', 'SSF5181235'),
('+918239313312', 'SSF5218734'),
('+918382001253', 'SID951375176836'),
('+918604802958', 'SSF2526794'),
('+918434672194', 'SID951375146744'),
('+918853972682', 'SID951375665308'),
('+919199849264', 'SID951373890765'),
('+919060589896', 'SSF5319026'),
('+919636429979', 'SSF5180760'),
('+919608317013', 'SSF5776804'),
('+919131496989', 'SSF4921908'),
('+919120717625', 'SSF3316128'),
('+919576737825', 'SSF5169517'),
('+919019241943', 'SSF5113918'),
('+919905895206', 'SSF5158202'),
('+919256741611', 'SSF5089183'),
('+919142714985', 'SSF4938560'),
('+919128365330', 'SSF2411923'),
('+919065648709', 'SSF4959588'),
('+919199154642', 'SSF5182620'),
('+919341222381', 'SSF5999044'),
('+919508756771', 'SSF5166151'),
('+919625404170', 'SSF5272058'),
('+919508868447', 'SSF5174499'),
('+919335005306', 'SSF5131629'),
('+919031793838', 'SSF5698800'),
('+918294444874', 'SSF5497801'),
('+919414345221', 'SSF5315995'),
('+919297712778', 'SSF5689801'),
('+919695059482', 'SSF4220516'),
('+917857085805', 'SSF5072336'),
('+917870848926', 'SSF4817709'),
('+917079637038', 'SSF3075322'),
('+917992486258', 'SSF5963446'),
('+917044506704', 'SSF6080186'),
('+917632048257', 'SSF6183485'),
('+919122373573', 'SSF5828687'),
('+917292050419', 'SSF6222885'),
('+919523959757', 'SSF5712628'),
('+916263838920', 'SSF4749472'),
('+916375695674', 'SSF4640526'),
('+916378353704', 'SSF4621946'),
('+916287723021', 'SSF4821154'),
('+916200694831', 'SSF4572044'),
('+916205495348', 'SSF4570270'),
('+916268040930', 'SID2125744943'),
('+916207808764', 'SSF4650487'),
('+917697591152', 'SSF2506000'),
('+917061176023', 'SSF4655565'),
('+917869437952', 'SSF4806348'),
('+917001750993', 'SSF4539619'),
('+917646965054', 'SSF4350505'),
('+917980245853', 'SSF5221559'),
('+917783826540', 'SSF4616204'),
('+917479607436', 'SSF4701079'),
('+917352112393', 'SSF3773920'),
('+917643985983', 'SID951373786996'),
('+917877910937', 'SSF4323928'),
('+917765852840', 'SSF2897325'),
('+917482912318', 'SID951376006782'),
('+917079716557', 'SSF4564510'),
('+917091453510', 'SSF4488480'),
('+917903774317', 'SSF4633355'),
('+917999521788', 'SSF4563819'),
('+918602095979', 'SSF4633592'),
('+918863093217', 'SSF4736829'),
('+918093835745', 'SID951374268824'),
('+918292864380', 'SSF4695099'),
('+918917648566', 'SSF3305536'),
('+918084674562', 'SSF4885568'),
('+918123216745', 'SSF4628779'),
('+918319245254', 'SSF4680231'),
('+918102270508', 'SSF4218124'),
('+918714657578', 'SSF4550345'),
('+918756554566', 'SID951375194290'),
('+918871017431', 'SSF5063808'),
('+918873704681', 'SSF3048541'),
('+918294372625', 'SSF4530762'),
('+918815580603', 'SSF4563763'),
('+919329047796', 'SSF3803891'),
('+919006896131', 'SSF3374393'),
('+919519174427', 'SSF3289802'),
('+919301922091', 'SSF4563743'),
('+919685760362', 'SSF4778091'),
('+919430696914', 'SSF4628934'),
('+919576975810', 'SSF4721626'),
('+919602237972', 'SSF4798799'),
('+919060939115', 'SSF4566636'),
('+919602640344', 'SSF4837007'),
('+919024237831', 'SSF4781777'),
('+919234826021', 'SSF4639133'),
('+919608051227', 'SSF3356516'),
('+919939926219', 'SSF5077913'),
('+919162156574', 'SSF4573405'),
('+919065864111', 'SSF4544836'),
('+919549685244', 'SSF3417945'),
('+919685231615', 'SSF4573321'),
('+919263752886', 'SSF4627503'),
('+919341079485', 'SSF4704364'),
('+919315786137', 'SSF4610475'),
('+919110935277', 'SID951373897206'),
('+919135080685', 'SSF4338150'),
('+919406000762', 'SSF4685697'),
('+919546968757', 'SSF4557961'),
('+919939253937', 'SSF2542262'),
('+919955266613', 'SSF5075493'),
('+919631385181', 'SID951372831046'),
('+917970856756', 'SSF5575609'),
('+917992313602', 'SSF6231138'),
('+917091384747', 'SSF5866481'),
('+917323932994', 'SSF5827128'),
('+919279780189', 'SID951372845561'),
('+916394684200', 'SSF2547586'),
('+916266921618', 'SSF4601798'),
('+916203717475', 'SSF3054900'),
('+916206404843', 'SID951376135897'),
('+916246546446', 'SID951375421680'),
('+916287547511', 'SSF4780124'),
('+916209445593', 'SSF4335278'),
('+916207967810', 'SSF4552291'),
('+916267356456', 'SID951375978870'),
('+917723020527', 'SSF3810437'),
('+917091201974', 'SSF4609779'),
('+917275614051', 'SSF4570002'),
('+917323099861', 'SSF4558228'),
('+917859973040', 'SSF4970080'),
('+917723929105', 'SSF4626635'),
('+917974068630', 'SSF4723508'),
('+917778938341', 'SSF4356575'),
('+917857973751', 'SSF4942390'),
('+917852895390', 'SSF4312298'),
('+917340651173', 'SSF3469612'),
('+917878759488', 'SID951374302432'),
('+917070318665', 'SSF4022422'),
('+917739050681', 'SSF4386325'),
('+917357505886', 'SSF2496415'),
('+917033685658', 'SSF4492313'),
('+917665655945', 'SSF2524882'),
('+917479532438', 'SSF4345745'),
('+917999184333', 'SSF4315959'),
('+917804930782', 'SSF4410576'),
('+917357945152', 'SSF2552080'),
('+918319853319', 'SSF4607966'),
('+918102886982', 'SSF4486369'),
('+918780247831', 'SSF4568130'),
('+918409282244', 'SID951376181996'),
('+918233777682', 'SSF4396602'),
('+918000289133', 'SSF4414409'),
('+918102399681', 'SSF5076533'),
('+918696412259', 'SSF4385342'),
('+918829086293', 'SSF2882263'),
('+918005814346', 'SSF4133850'),
('+918271857254', 'SSF4559302'),
('+918294989940', 'SSF4876876'),
('+918427932629', 'SSF4377163'),
('+918252624920', 'SSF4392453'),
('+918863031096', 'SSF2510452'),
('+918102079776', 'SSF4466680'),
('+918002090503', 'SSF4420261'),
('+918582043796', 'SSF3472671'),
('+918969790350', 'SSF4456285'),
('+919060506178', 'SID951375266184'),
('+919589211106', 'SSF4616150'),
('+919508679004', 'SSF4754612'),
('+919001935624', 'SSF4471309'),
('+919977584469', 'SID951375275956'),
('+919508620597', 'SSF5031691'),
('+919060063305', 'SSF3292044'),
('+919835801485', 'SID951374330547'),
('+919102285094', 'SSF5001681'),
('+919636171995', 'SSF3604915'),
('+919602982538', 'SSF4356566'),
('+919341412710', 'SSF4630375'),
('+919939914463', 'SSF4411519'),
('+919504603457', 'SSF4368959'),
('+919783447314', 'SSF4385281'),
('+919199133631', 'SSF2727415'),
('+919507136444', 'SSF4559286'),
('+919610388208', 'SID951374971039'),
('+919351644594', 'SSF4415961'),
('+919546993346', 'SSF4415807'),
('+919983596092', 'SSF4421445'),
('+919038643484', 'SSF2904019'),
('+919306501039', 'SSF4470678'),
('+919646648667', 'SID951376122144'),
('+919142262850', 'SSF4381570'),
('+919381149635', 'SSF4474014'),
('+919595998889', 'SID951376141508'),
('+919772552786', 'SSF4437875'),
('+919261158555', 'SSF4342271'),
('+919934786991', 'SID951376197535'),
('+919983355359', 'SSF4342425'),
('+919031581521', 'SSF4466514'),
('+919661480137', 'SSF4555419'),
('+919798771691', 'SSF3197446'),
('+919102978380', 'SSF3267605'),
('+919835269805', 'SSF4600497'),
('+917522025062', 'SSF4797923'),
('+918601027511', 'SSF5442778'),
('+916206037848', 'SSF4180356'),
('+916266810272', 'SSF4195550'),
('+919304419417', 'SSF3292005'),
('+916360197167', 'SSF4044153'),
('+916205159947', 'SSF4205132'),
('+916375293735', 'SSF4053542'),
('+916355211902', 'SSF3867013'),
('+916376632109', 'SSF4047222'),
('+916265598668', 'SID951375194521'),
('+916378792183', 'SSF4158658'),
('+916367809640', 'SSF4158706'),
('+917339807174', 'SSF4035118'),
('+917568774785', 'SSF4023250'),
('+917976707597', 'SSF4036558'),
('+917781920898', 'SID951375991553'),
('+917250374699', 'SSF4015410'),
('+917727913548', 'SSF4660397'),
('+917742934897', 'SSF4134944'),
('+917073196740', 'SSF3891928'),
('+917231997364', 'SSF4274720'),
('+917023954501', 'SSF3926514'),
('+917014829953', 'SSF3988009'),
('+917340556027', 'SSF4062772'),
('+917742944672', 'SID951374996437'),
('+917340290341', 'SSF3903593'),
('+917477247238', 'SSF4431767'),
('+918583885858', 'SSF2785620'),
('+918853518401', 'SSF2817205'),
('+918770659352', 'SSF4472177'),
('+918905213703', 'SSF3964990'),
('+918107996903', 'SSF4036537'),
('+918769230782', 'SSF4139603'),
('+918434692629', 'SSF3979033'),
('+918824352759', 'SSF3930809'),
('+918890372799', 'SSF3971292'),
('+918619511070', 'SSF4078241'),
('+918572869604', 'SSF4117219'),
('+918955872320', 'SSF4080699'),
('+918239189935', 'SSF4056716'),
('+918795640997', 'SSF4015825'),
('+918529955099', 'SSF4139095'),
('+918302418154', 'SSF4032634'),
('+918955668257', 'SSF4002329'),
('+918866681640', 'SSF3937405'),
('+918306831526', 'SSF4405804'),
('+919186037153', 'SSF3854041'),
('+919631923479', 'SSF4226209'),
('+919352864476', 'SSF3975368'),
('+919304028630', 'SSF4015372'),
('+919549387937', 'SSF4004251'),
('+919199648803', 'SSF3090575'),
('+919672120957', 'SSF4139105'),
('+919351286575', 'SSF4078813'),
('+919079293186', 'SSF3340715'),
('+919522787504', 'SSF3838902'),
('+919116348614', 'SSF3518028'),
('+919799871723', 'SSF4023713'),
('+919302433910', 'SSF4113866'),
('+919001912655', 'SSF3998609'),
('+919971618393', 'SID951376092929'),
('+919635255898', 'SID951376026672'),
('+918252857407', 'SSF5567206'),
('+916376639124', 'SSF4609623'),
('+916375481212', 'SSF3876331'),
('+917976383411', 'SSF3881754'),
('+917728830546', 'SSF3962508'),
('+917488325997', 'SSF3875450'),
('+917725862399', 'SID951373056739'),
('+917974388397', 'SSF4313757'),
('+917646197846', 'SID951376019443'),
('+918854940571', 'SSF3860379'),
('+918959132794', 'SSF3610137'),
('+918905772808', 'SSF2745873'),
('+918005854483', 'SSF3970015'),
('+918696659208', 'SSF3918478'),
('+918690043186', 'SSF3911584'),
('+918287600052', 'SSF3980760'),
('+918209687457', 'SSF3882569'),
('+919636849588', 'SSF2567466'),
('+919343759615', 'SSF3857086'),
('+919564949484', 'SSF3610128'),
('+919588250760', 'SSF3580997'),
('+919521708356', 'SSF3986623'),
('+919521374933', 'SSF3927708'),
('+919784735495', 'SSF3752827'),
('+919928276892', 'SSF3897121'),
('+917852463552', 'SSF3885628'),
('+918000773662', 'SSF3831926'),
('+919263371694', 'SSF3807171'),
('+919608662489', 'SSF3736232'),
('+919464979677', 'SSF3000881'),
('+919735219757', 'SSF3442978'),
('+919986565577', 'SSF3773646'),
('+917283021532', 'SSF5674791'),
('+918298129854', 'SSF5235867'),
('+916398542187', 'SSF3586994'),
('+916686898683', 'SSF3663314'),
('+917997796766', 'SSF3744867'),
('+917568368251', 'SSF3709788'),
('+919680534228', 'SSF3587716'),
('+919929199282', 'SSF3804023'),
('+919588940625', 'SSF3770214'),
('+919636644977', 'SSF3371324'),
('+919113786342', 'SSF5926509'),
('+916375684949', 'SSF5868514'),
('+918095851160', 'SSF5405948'),
('+919264152206', 'SSF5222117'),
('+918456467586', 'SSF3309302'),
('+918767316767', 'SID951376066260'),
('+919173949733', 'SID951374589778'),
('+919668886358', 'SSF3433507'),
('+919024196007', 'SSF3077139'),
('+919352498154', 'SSF3257321'),
('+919783885616', 'SSF4332813'),
('+917970795385', 'SSF3382051'),
('+918757846799', 'SSF3338509'),
('+918591724149', 'SSF3220196'),
('+919728145208', 'SSF3344174'),
('+919125085335', 'SSF2981943'),
('+916267147500', 'SSF4121772'),
('+916268714560', 'CID206702557'),
('+917974845650', 'SID951375476609'),
('+919399018905', 'SID951373510755'),
('+919145363954', 'SSF2465437'),
('+916261520362', 'SSF5968534'),
('+916264595948', 'SSF3638049'),
('+916260454366', 'SSF5928174'),
('+916266785726', 'SSF5843256'),
('+917568554056', 'SSF5634799'),
('+917805877412', 'SSF3690032'),
('+917223046135', 'SSF5140400'),
('+917389631517', 'SSF3813159'),
('+917340562347', 'SSF3630436'),
('+917974426813', 'SSF5712760'),
('+917987369019', 'SSF4512753'),
('+917089019053', 'SSF5683925'),
('+918269946131', 'SSF3616466'),
('+918602981876', 'SSF5950627'),
('+918109088678', 'SSF3654236'),
('+918355985819', 'SSF5609765'),
('+919171804663', 'SSF4382371'),
('+919329974318', 'SSF4014443'),
('+919569247146', 'SSF5819580'),
('+919669111525', 'SSF5788317'),
('+919926604424', 'SSF3554786'),
('+919009824323', 'SSF5665424'),
('+919340807973', 'SSF5776781'),
('+917440722723', 'CID043201251'),
('+919140314790', 'SSF2454811'),
('+919978456123', 'SSF3221226'),
('+916268713934', 'SID951374775064'),
('+919358799303', 'SSF4491005'),
('+917827905037', 'SSF3900155'),
('+917804912388', 'SSF5679118'),
('+919679797999', 'SID951373629146'),
('+918538815602', 'SSF3491292'),
('+918969147950', 'SID951375392401'),
('+918108954237', 'SSF2427652'),
('+919009583486', 'CID190102908'),
('+918171637791', 'SSF5657402'),
('+918603323624', 'SSF3068520'),
('+919263847962', 'SSF4587367'),
('+919116363466', 'SID951375878582'),
('+919263775449', 'SSF4746217'),
('+916207662346', 'SID951374549395'),
('+919570459496', 'SSF3444795'),
('+919835675699', 'SSF5640898'),
('+916260603893', 'SSF3368221'),
('+919522462062', 'SSF5740898'),
('+919691751181', 'CID129001930'),
('+919934485713', 'SSF4703848'),
('+918091734196', 'SSF3146138'),
('+916267522270', 'SSF5051001'),
('+916267768052', 'SSF4173388'),
('+918287789592', 'SSF3248659'),
('+916287548115', 'SSF3001211'),
('+917974903232', 'SID2125770167'),
('+919661088082', 'SSF4822620'),
('+919575660437', 'SID951375401341'),
('+919827457116', 'CID080714359'),
('+919767346769', 'CID086912031'),
('+919783851073', 'SSF2682901'),
('+918109791451', 'SSF2854795'),
('+919343440579', 'SID951374504473'),
('+917493865055', 'SSF5590775'),
('+919234786538', 'SID951375075064'),
('+919039116608', 'SSF3632662'),
('+917891001762', 'SID951374962505'),
('+917462016315', 'SSF4509502'),
('+919458053485', 'SID951374225058'),
('+918651137182', 'SSF4696963'),
('+917723931417', 'SSF2387693'),
('+917739870456', 'SID951376107410'),
('+919407920742', 'SID951374935667'),
('+919691210251', 'SSF4905414'),
('+918305959751', 'SID951374922453'),
('+916262101107', 'CID129404938'),
('+918279758154', 'SSF5429133'),
('+917223040034', 'SSF3693311'),
('+918587030431', 'SSF6227820'),
('+916377223249', 'SID951375968729'),
('+918103502745', 'SSF3319635'),
('+917319767412', 'SID951375348461'),
('+919340325261', 'SSF4195515'),
('+917488699491', 'SSF2796376'),
('+918817662630', 'SSF3416559'),
('+916299023578', 'SID951372959627'),
('+919950168863', 'SSF3683899'),
('+919198920165', 'SSF5425888'),
('+919341122455', 'SSF6084601'),
('+919103872764', 'SSF5051038'),
('+918451058269', 'SSF4407024'),
('+919234274980', 'SSF5775883'),
('+919120254272', 'SSF4278523'),
('+919001707778', 'SSF5596816'),
('+916394888989', 'SID951374081881'),
('+919262389656', 'SSF3493667'),
('+919068848219', 'SSF4757485'),
('+916205490441', 'SSF3064968'),
('+919279064190', 'SID951375201423'),
('+917987239021', 'CID040019979'),
('+916266681956', 'SID2125669341'),
('+916260934038', 'SID951373309350'),
('+917078115065', 'SSF5136151'),
('+919536765600', 'SSF4105882'),
('+919931949783', 'SSF3982017'),
('+917869891430', 'SSF3793551'),
('+918839843853', 'SID951375077166'),
('+917277462562', 'SID951376217728'),
('+919340583935', 'CID084700904'),
('+916200006929', 'SID951374506079'),
('+918294422090', 'SID951375164065'),
('+917461962296', 'SID951373477470'),
('+918109748722', 'SID951376107146'),
('+918789342084', 'SSF2682160'),
('+918319193181', 'SID951374108408'),
('+917000193790', 'SID951375776585'),
('+919113189276', 'SSF3263389'),
('+918434761562', 'SSF3992209'),
('+919616115063', 'SSF6073382'),
('+919369031218', 'SSF6071385'),
('+919315152994', 'SSF4622615'),
('+919955543092', 'SSF4623086'),
('+919936919423', 'SSF4588678'),
('+917233945221', 'SSF3918641'),
('+918319388872', 'SID951373827341'),
('+919110095801', 'SID951375267788'),
('+919301033432', 'SID951374973200'),
('+918736936804', 'SID951376058627'),
('+916203060879', 'SSF3708841'),
('+918125004352', 'SSF6227605'),
('+917974508035', 'SID951375538036'),
('+919368649587', 'SSF5223053'),
('+917231957479', 'SSF3746267'),
('+917080304689', 'SSF4539881'),
('+919165191466', 'SID951373411725'),
('+917571097367', 'SSF5532288'),
('+916200506236', 'CID262501609'),
('+918871701813', 'SID951376108551'),
('+917644089930', 'SID951376176133'),
('+919279429149', 'SSF4096977'),
('+918248219366', 'SID951375216565'),
('+917061962474', 'SID951376237779'),
('+917853978443', 'SID2125692875'),
('+918103848283', 'SID951375386858'),
('+919057064280', 'SID951375458816'),
('+919984501918', 'SSF4391566'),
('+916262178076', 'SID951375919951'),
('+918225917457', 'SID951373540840'),
('+919721799496', 'SSF3656133'),
('+918399023849', 'SSF6370100'),
('+918854831451', 'SID951375105964'),
('+916380784135', 'SSF3533480'),
('+919129982025', 'SSF5783274'),
('+917970266398', 'SID951374882686'),
('+917080195121', 'SSF2450810'),
('+918274930327', 'SSF5601831'),
('+917828576487', 'SID2125239671'),
('+917389651822', 'SID951374300365'),
('+919651665026', 'SSF4315917'),
('+917041600177', 'SSF3469803'),
('+918307358260', 'SID951375726451'),
('+916267705378', 'SID951375934605'),
('+917722996430', 'SSF5836035'),
('+918149287185', 'SSF2788371'),
('+917000929747', 'SID951376014677'),
('+918290374430', 'SSF3563199'),
('+916266465562', 'SID2125344651'),
('+919341479294', 'SID951375070508'),
('+919103263030', 'SSF2419738'),
('+916261105231', 'SSF5455423'),
('+916205099436', 'SSF3003553'),
('+916201666708', 'SSF5648243'),
('+916205724773', 'SSF5614518'),
('+916204160517', 'SSF5978702'),
('+917634990062', 'SSF5584385'),
('+917722933532', 'SSF5601609'),
('+917358209342', 'SSF5482202'),
('+917857065985', 'SSF5452191'),
('+917667459032', 'SSF5394871'),
('+917676758146', 'SSF5454029'),
('+917033439101', 'SSF6050947'),
('+917033217297', 'SSF5682426'),
('+917209365751', 'SSF5996870'),
('+917870129468', 'SSF3645678'),
('+917654682497', 'SSF5543842'),
('+917691978523', 'SSF6134742'),
('+918569829669', 'SSF5315622'),
('+918815583520', 'SSF5968117'),
('+918420032171', 'SSF5505352'),
('+918817016917', 'SSF5543720'),
('+918709206102', 'SSF5994138'),
('+918319175535', 'SSF5970466'),
('+918678060759', 'SSF5946662'),
('+919149546860', 'SSF5585426'),
('+919630253362', 'SSF5374720'),
('+919122311406', 'SSF5583578'),
('+919102360933', 'SSF5941604'),
('+919019048831', 'SSF5665695'),
('+919234416515', 'SSF5733688'),
('+919334973980', 'SSF5406702'),
('+919229126665', 'SSF5626475'),
('+919125560044', 'SSF5437166'),
('+919199700908', 'SSF6099980'),
('+919669729753', 'SSF5647942'),
('+919179506991', 'SSF5950492'),
('+919770782387', 'SSF5253985'),
('+919302865689', 'SSF5674985'),
('+919343510147', 'SSF5977285'),
('+919801095846', 'SSF3498901'),
('+919608243397', 'SSF3591519'),
('+919302853101', 'SSF5487435'),
('+919065203927', 'SSF5526469'),
('+919238045870', 'SID372'),
('+917908190301', 'SID951376152204'),
('+916300416984', 'SSF5710914'),
('+916206249643', 'SSF5337769'),
('+917762822333', 'SSF6063498'),
('+917727965977', 'SSF3512301'),
('+917828867727', 'SSF5494110'),
('+917748948578', 'SSF5817126'),
('+917632898407', 'SSF5885587'),
('+918809159465', 'SSF5409127'),
('+918889949228', 'SSF5948828'),
('+918073856018', 'SSF3705278'),
('+918002396418', 'SSF5954917'),
('+918875420583', 'SSF5180323'),
('+918640050292', 'SSF5734105'),
('+919523485343', 'SSF5996899'),
('+919343791005', 'SSF5817441'),
('+919122629251', 'SSF5428669'),
('+919005217793', 'SSF5599617'),
('+919608105347', 'SSF5695766'),
('+919651263794', 'SSF4670763'),
('+916205282210', 'SSF5560868'),
('+917818930066', 'SSF6100536'),
('+919065540146', 'SSF5560309'),
('+919031413340', 'SSF6034594'),
('+919102311378', 'SSF5782958'),
('+919341415751', 'SSF6069705'),
('+917991125835', 'SSF6167615'),
('+917856867141', 'SSF6134568'),
('+917464013169', 'SSF5540263'),
('+918797663131', 'SSF5967594'),
('+919334867531', 'SSF5748580'),
('+919102652844', 'SSF5860896'),
('+919815716037', 'SSF5466734'),
('+917828013467', 'SID951372999151'),
('+918529493931', 'SID951374206320'),
('+919831934943', 'SID951373720361'),
('+917294929961', 'SSF5514582'),
('+917631204414', 'SSF5583864'),
('+917050040430', 'SSF5491489'),
('+917366804894', 'SSF5659765'),
('+917068663490', 'SSF4856855'),
('+917295802721', 'SSF5608949'),
('+918521830080', 'SSF5924952'),
('+919241081507', 'SSF5676468'),
('+919234762683', 'SSF5842024'),
('+916391625655', 'SSF2364833'),
('+916207855393', 'SSF5708493'),
('+916203951697', 'SSF5779225'),
('+916269960377', 'SSF5234296'),
('+916201153770', 'SSF4808001'),
('+916202344316', 'SSF3063649'),
('+916267340225', 'SSF5761075'),
('+916305109320', 'SSF5744953'),
('+917632806455', 'SSF5671381'),
('+917815984470', 'SSF5207187'),
('+917014629430', 'SSF3087283'),
('+917667495319', 'SSF5858434'),
('+917023783943', 'SSF5216209'),
('+917497831257', 'SSF3423106'),
('+917091586926', 'SSF5769211'),
('+917607475429', 'SSF5502338'),
('+917758044370', 'SSF5789729'),
('+917633024063', 'SSF5227807'),
('+917856027133', 'SSF5753320'),
('+917803978656', 'SSF5743212'),
('+918103433882', 'SSF5675965'),
('+918292989137', 'SSF5638323'),
('+918357815808', 'SSF5404062'),
('+918815837867', 'SSF5275649'),
('+918005600953', 'SSF5169847'),
('+918890391085', 'SSF5339033'),
('+918757019556', 'SSF3716931'),
('+918516905569', 'SSF5219081'),
('+918709063066', 'SSF5356540'),
('+918440937621', 'SSF5752445'),
('+918797903670', 'SSF5726139'),
('+918390861373', 'SSF5500774'),
('+919725668449', 'SSF5564152'),
('+919229104045', 'SSF5713111'),
('+919835238040', 'SSF5711263'),
('+919523109429', 'SSF5470439'),
('+919649922487', 'SSF5045373'),
('+919262886641', 'SSF5028352'),
('+919301272764', 'SSF5233673'),
('+919616716495', 'SSF4845365'),
('+919399263590', 'SSF5492943'),
('+919794063471', 'SSF3540417'),
('+919931047632', 'SID951375526963'),
('+919575044393', 'SSF5378262'),
('+919006040085', 'SSF5171602'),
('+919329696100', 'SSF3145234'),
('+919305632672', 'SSF5737207'),
('+919079608083', 'SSF5683988'),
('+919875707045', 'SSF3046876'),
('+919993247728', 'SSF5721013'),
('+919263066856', 'SSF5753204'),
('+919399040358', 'SSF2954471'),
('+918002151709', 'SSF5166742'),
('+918957974625', 'SSF6157803'),
('+919532253073', 'SSF5802769'),
('+919628523613', 'SSF5000927'),
('+918271891493', 'SSF5866516'),
('+919060641400', 'SSF5749524'),
('+918726374989', 'SSF5671092'),
('+918102757209', 'SSF6094598'),
('+918603549700', 'SSF5346713'),
('+918969759053', 'SSF5477803'),
('+918797651223', 'SSF5477709'),
('+919905667325', 'SSF5460764'),
('+919877808388', 'SSF5364531'),
('+917050426144', 'SID2125252918'),
('+916204288863', 'SSF2303052'),
('+916205475903', 'SSF5402719'),
('+916264748166', 'SSF4934042'),
('+916201193623', 'SSF4876304'),
('+916232069086', 'SSF4896628'),
('+917079257975', 'SSF5399334'),
('+917463854949', 'SSF5279097'),
('+917079370136', 'SSF4343924'),
('+917903599580', 'SSF5557404'),
('+917600322818', 'SSF5396514'),
('+917895355132', 'SSF5369317'),
('+917632065831', 'SSF5561914'),
('+917209192034', 'SSF3274208'),
('+917088896813', 'SSF5483864'),
('+917644863011', 'SSF5319184'),
('+917634902128', 'SSF5399135'),
('+917079060045', 'SSF5659748'),
('+917488829357', 'SSF2369503'),
('+917645043001', 'SSF5390444'),
('+917400300322', 'SSF4873429'),
('+917645039467', 'SSF5385829'),
('+917479607675', 'SSF5336990'),
('+918084360043', 'SSF4982376'),
('+918235154135', 'SSF5320291'),
('+918271032604', 'SSF5505778'),
('+918581075828', 'SSF5505656'),
('+918629998033', 'SSF4899982'),
('+918539944853', 'SSF3338096'),
('+918847269270', 'SSF5052983'),
('+919102136565', 'SSF5414817'),
('+919971968590', 'SSF5001740'),
('+919341840163', 'SSF5450899'),
('+919060327102', 'SSF5467999'),
('+919508257741', 'SSF3887150'),
('+919341470249', 'SSF5348655'),
('+919905982074', 'SSF5403997'),
('+919693294467', 'SSF5403446'),
('+919570885429', 'SSF5539516'),
('+919693286612', 'SSF5483854'),
('+919905688414', 'SSF4949815'),
('+919199166292', 'SSF5591713'),
('+919958640765', 'SSF5373618'),
('+919304531756', 'SSF3477651'),
('+919905519281', 'SSF3469183'),
('+919304072889', 'SSF5564988'),
('+919279341980', 'SSF5565474'),
('+919690024135', 'SSF5472493'),
('+919244509892', 'SID951375398856'),
('+919571976678', 'SSF4888961'),
('+919234948287', 'SSF5269900'),
('+917061953155', 'SSF5781849'),
('+918948634080', 'SSF6122373'),
('+917378529752', 'SSF4517449'),
('+918009204275', 'SSF5762368'),
('+917317326661', 'SSF6176160'),
('+917482901101', 'SSF5068952'),
('+917542828147', 'SSF6237918'),
('+918271010875', 'SSF4790332'),
('+918294595221', 'SSF6107722'),
('+919113172340', 'SSF6073918'),
('+919801096454', 'SSF6123971'),
('+919279090959', 'SSF6111177'),
('+919289901295', 'SSF5411186'),
('+919546649404', 'SSF6093340'),
('+919262518480', 'SSF5709702'),
('+917766869141', 'SSF5727451'),
('+918595555363', 'SSF5723092'),
('+918409892245', 'SSF6031489'),
('+918409122840', 'SSF6160810'),
('+918809570488', 'SSF5129098'),
('+919709939911', 'SSF5732000'),
('+919310436795', 'SSF6050993'),
('+916265774717', 'SSF5249544'),
('+916202992461', 'SID951374921033'),
('+916209485425', 'SSF3999226'),
('+916299120177', 'SSF2964711'),
('+916206419499', 'SSF4765987'),
('+916203643546', 'SSF4748473'),
('+916268578746', 'SSF3651379'),
('+917772023979', 'SSF3155160'),
('+917023443421', 'SSF4606980'),
('+917371048442', 'SSF2815225'),
('+917542970050', 'SSF4885324'),
('+917683051194', 'SSF4871362'),
('+917804966675', 'SSF4485425'),
('+917000614399', 'SSF4996906'),
('+917000439458', 'SSF5017717'),
('+917858891618', 'SSF4882855'),
('+917261846658', 'SSF4999585'),
('+917667582812', 'SSF2748973'),
('+917489426715', 'SSF4548651'),
('+917366855138', 'SSF4467503'),
('+917240301483', 'SSF4607581'),
('+917870422577', 'SSF4797919'),
('+917739529014', 'SSF4474757'),
('+917545091536', 'SSF4745049'),
('+917362822612', 'SSF3058820'),
('+917489901486', 'SSF3541681'),
('+917722948568', 'SID951375989462'),
('+917091513074', 'SSF4880428'),
('+917725014061', 'SSF4977205'),
('+918709315094', 'SSF4461581'),
('+918651546196', 'SSF4637537'),
('+918434425454', 'SSF4875468'),
('+918083883883', 'SSF2539071'),
('+918002459482', 'SSF4447644'),
('+918815772810', 'SID951376015248'),
('+918000202058', 'SSF4721581'),
('+918434624596', 'SSF4794412'),
('+918603814546', 'SSF4871602'),
('+918509799958', 'SSF4955250'),
('+918962573304', 'SSF4444576'),
('+918271109308', 'SSF4876080'),
('+918239746324', 'SSF4901788'),
('+918969424278', 'SSF4938498'),
('+918709721223', 'SSF5062546'),
('+918878111237', 'SSF4470858'),
('+919955649428', 'SSF4415467'),
('+919625097478', 'SSF4482744'),
('+919343814255', 'SSF4979071'),
('+919263631636', 'SSF4989763'),
('+919835781470', 'SID951373932448'),
('+919693494488', 'SSF4813496'),
('+919771652523', 'SID951375729193'),
('+919770145733', 'SSF4943104'),
('+919334632706', 'SSF4775868'),
('+919303823268', 'SSF4920946'),
('+919708436082', 'SSF4457024'),
('+919343574828', 'SSF4832962'),
('+919399803276', 'SSF4898504'),
('+919799445685', 'SSF2927768'),
('+919835691622', 'SSF4967533'),
('+919608771735', 'SSF4776240'),
('+919304951133', 'SSF4751914'),
('+919302778288', 'SSF4167293'),
('+919934112721', 'SSF5037072'),
('+919934838673', 'SSF5035772'),
('+919939078262', 'SSF4862243'),
('+919399541669', 'SSF4462963'),
('+919991994622', 'SSF5055492'),
('+919798776507', 'SSF4957690'),
('+919983948610', 'SSF5064301'),
('+919104456329', 'SSF4782132'),
('+919341489619', 'SSF4997876'),
('+919955206136', 'SSF4950594'),
('+919244743726', 'SSF4892689'),
('+917634871478', 'SSF5727304'),
('+918368265550', 'SSF5810431'),
('+918797491955', 'SSF6068925'),
('+918360847563', 'SSF5719563'),
('+918292560397', 'SSF6004288'),
('+918780595869', 'SSF5751171'),
('+918709910745', 'SSF5753103'),
('+919034830761', 'SSF6009864'),
('+919852189871', 'SSF6199514'),
('+919693882162', 'SSF5804170'),
('+919155794873', 'SSF5739521'),
('+919910536980', 'SSF3931518'),
('+919065003746', 'SSF5710182'),
('+919508926351', 'SSF5639747'),
('+918104587650', 'SSF6121247'),
('+919264939091', 'SSF4600248'),
('+919122421751', 'SSF5669278'),
('+918789570639', 'SSF5705043'),
('+918404946981', 'SSF6058401'),
('+919304607352', 'SSF5845477'),
('+916360264410', 'SSF4679490'),
('+916287934587', 'SSF4864427'),
('+916267505827', 'SSF4815532'),
('+916909118810', 'SSF4748701'),
('+917759854060', 'SSF4836946'),
('+917091053685', 'SSF2433866'),
('+917992375151', 'SSF4324669'),
('+917325019593', 'SSF4834527'),
('+917463853296', 'SSF2540223'),
('+917633905226', 'SSF4741151'),
('+917897564345', 'SSF2989910'),
('+917814516313', 'SSF4764021'),
('+917667264394', 'SSF4780070'),
('+917050526299', 'SSF4343580'),
('+917231979779', 'SSF4452924'),
('+917568630137', 'SSF3733930'),
('+918829878020', 'SSF4269910'),
('+918815724065', 'SSF4832968'),
('+918789794650', 'SSF4869417'),
('+918435993085', 'SID951376106730'),
('+918235774081', 'SID951374754748'),
('+918235857615', 'SSF4668989'),
('+918271970843', 'SSF4648832'),
('+919511306191', 'SID951375198209'),
('+919549909398', 'SSF4444346'),
('+919772097132', 'SSF4554782'),
('+919571514023', 'SSF4553888'),
('+919752297955', 'SSF4679278'),
('+919358182127', 'SSF4810165'),
('+919104102543', 'SSF2961222'),
('+919530050841', 'SSF4902507'),
('+919279500925', 'SSF2870329'),
('+919508817962', 'SID951375938514'),
('+919131660415', 'SSF4804942'),
('+919376896070', 'SSF5379264'),
('+919784363137', 'SSF3797973'),
('+919973958583', 'SSF4826599'),
('+919117671551', 'SSF4667290'),
('+919693722665', 'SSF4874548'),
('+919955247532', 'SSF4824848'),
('+919199779707', 'SSF4743233'),
('+919279726828', 'SSF4975686'),
('+919303493300', 'SSF4814376'),
('+919352319911', 'SSF4588371'),
('+919351641479', 'SSF4697188'),
('+919370907563', 'SID951375698333'),
('+917543970029', 'SSF4600784'),
('+919508548671', 'SSF5712843'),
('+918052783970', 'SSF5187050'),
('+916206777073', 'SSF6085483'),
('+917547037956', 'SSF5703659'),
('+919235313678', 'SSF4528810'),
('+916200294895', 'SSF5651864'),
('+917806060679', 'SSF4112231'),
('+919060613594', 'SSF5803741'),
('+918092258375', 'SSF5479796'),
('+916263513847', 'SSF4371450'),
('+916266365445', 'SSF4128990'),
('+916367643023', 'SSF4257067'),
('+916377533432', 'SSF4435749'),
('+917489907870', 'SID951374711269'),
('+917383634119', 'SSF4497058'),
('+917766959500', 'SSF4435450'),
('+917415865686', 'SID951375789337'),
('+917073090867', 'SSF4272995'),
('+918824777790', 'SSF4356556'),
('+918128129980', 'SSF4376842'),
('+918107077890', 'SSF4370489'),
('+918709153624', 'SSF4418339'),
('+918849795238', 'SSF4424283'),
('+918207408349', 'SSF4236103'),
('+918905605322', 'SSF4624967'),
('+918102131582', 'SSF4365636'),
('+919119343401', 'SSF4371492'),
('+919655578464', 'CID207403368'),
('+919680851574', 'SSF4435045'),
('+919110415894', 'SSF4026806'),
('+919327082346', 'SSF3951193'),
('+919257142712', 'SSF4327568'),
('+919602858852', 'SSF3987581'),
('+919001401511', 'SSF4429927'),
('+919166608146', 'SSF4311116'),
('+919672304419', 'SSF4328373'),
('+919653721782', 'SSF4457393'),
('+917632829373', 'SSF5761327'),
('+916378285646', 'SSF3861024'),
('+917462860682', 'SSF3982504'),
('+917735930775', 'SSF4551213'),
('+917061614542', 'SID951374256434'),
('+918953615455', 'SSF3872912'),
('+918797678764', 'SID951376155045'),
('+918306934394', 'SSF3839288'),
('+918107860637', 'SSF3838647'),
('+918757222588', 'SSF4241918'),
('+919572507489', 'SSF4211457'),
('+919508119298', 'SSF3134913'),
('+919587730677', 'SID951374658403'),
('+919827171999', 'SSF4367763'),
('+916249879948', 'SSF3597059'),
('+916264878949', 'SSF3554475'),
('+916375569304', 'SSF3912845'),
('+917428665455', 'SSF3608175'),
('+917727861404', 'SSF4061666'),
('+917742903328', 'SSF2335468'),
('+918884800888', 'SSF3723105'),
('+919674945456', 'SSF3610268'),
('+919587611618', 'SSF3759468'),
('+919636395998', 'SSF3613793'),
('+919799428125', 'SSF3935315'),
('+919351281462', 'SSF3993722'),
('+918340777426', 'SSF6160375'),
('+916260885689', 'SSF3355944'),
('+917340300774', 'SSF3886755'),
('+919896386855', 'SSF3377342'),
('+919653951966', 'SSF3899419'),
('+919784613151', 'SID951376046089'),
('+916203849696', 'SSF6117329'),
('+917617040171', 'SSF4309310'),
('+917466996762', 'SSF6259128'),
('+918476986766', 'SSF6259227'),
('+919258606554', 'SSF6259164'),
('+919259191392', 'SSF6263957'),
('+919267940317', 'SSF6263786'),
('+917484898918', 'SSF3601181'),
('+916858525809', 'SSF3678264'),
('+917568959888', 'SSF3002645'),
('+917766847973', 'SSF2809010'),
('+917357760047', 'SSF3408184'),
('+919643438484', 'SSF3805985'),
('+919256828809', 'SSF3804044'),
('+916268067337', 'SID2125392473'),
('+916207613746', 'SID951375697967'),
('+919304088020', 'SID951375424246'),
('+919031224078', 'SID951375450816'),
('+919721342818', 'SSF2325111'),
('+919771842090', 'SID951375984590'),
('+916268665467', 'SSF4073774'),
('+916367763043', 'SSF3438499'),
('+916205962543', 'SSF5552879'),
('+916386292611', 'SSF5674513'),
('+916287010196', 'SSF5631292'),
('+917597451782', 'SSF5444183'),
('+917597552520', 'SSF5397105'),
('+917417759770', 'SSF6146259'),
('+917033978822', 'SSF5630879'),
('+917091081139', 'SSF5777441'),
('+917742623449', 'SSF3212316'),
('+917543913642', 'SSF5416014'),
('+917635061872', 'SSF6035739'),
('+917352059547', 'SSF6041602'),
('+917992479352', 'SSF5643111'),
('+917545867422', 'SSF6144613'),
('+917281036581', 'SSF6136891'),
('+917033310209', 'SSF5154784'),
('+917779817430', 'SSF5610690'),
('+917493991488', 'SSF5935032'),
('+918434794538', 'SSF5461633'),
('+918953130584', 'SSF4172744'),
('+918292450120', 'SSF5560488'),
('+918084698077', 'SSF5487426'),
('+918271908719', 'SSF5942692'),
('+918873469789', 'SSF5887188'),
('+918429978072', 'SSF6131630'),
('+918651691546', 'SSF5573990'),
('+918797784342', 'SSF6052067'),
('+919608053802', 'SSF5456502'),
('+919770613549', 'SSF5665493'),
('+919142225627', 'SSF5501087'),
('+919516005167', 'SSF6067550'),
('+919303361253', 'SSF5483912'),
('+919039165458', 'SSF5944275'),
('+919026207012', 'SSF3483293'),
('+919893254982', 'SSF5358045'),
('+919835745209', 'SSF3060971'),
('+919238092354', 'SSF5409206'),
('+919128294722', 'SSF3029856'),
('+919975132278', 'SSF5089676'),
('+919770875158', 'SSF5984246'),
('+919124529885', 'SSF6002641'),
('+919238315719', 'SSF6136418'),
('+919661876190', 'SSF5656527'),
('+916267673019', 'CID050409844'),
('+918809713904', 'SID951374064287'),
('+917643011089', 'SID951375008782'),
('+917084737384', 'SID951374656478'),
('+918252627845', 'SID951374856204'),
('+918435652926', 'SID951374839913'),
('+919801400490', 'SID951375334237'),
('+919117354132', 'SID951374717501'),
('+919898649385', 'SSF2783521'),
('+919838929943', 'SSF2462444'),
('+919835549810', 'SID951374916286'),
('+919150405724', 'SSF2351132'),
('+916206729887', 'SSF5322483'),
('+916351915054', 'SSF3559795'),
('+916268173402', 'SSF5710663'),
('+916265875558', 'SSF3325438'),
('+916375128508', 'SSF3773668'),
('+916261342973', 'SSF5801689'),
('+916299736561', 'SSF5750023'),
('+916268806747', 'SSF5494436'),
('+917070942772', 'SSF5325373'),
('+917752986614', 'SSF3566549'),
('+917858976504', 'SSF3422131'),
('+917697805535', 'SSF6002756'),
('+917854083027', 'SSF5923425'),
('+917597234184', 'SSF3505885'),
('+917597215173', 'SSF5444312'),
('+917488504193', 'SSF5935154'),
('+917489176259', 'SSF4293809'),
('+917566115632', 'SSF4087160'),
('+917004281626', 'SSF5199215'),
('+917891513989', 'SSF5483747'),
('+917488180107', 'SSF6001830'),
('+917070067944', 'SSF2940300'),
('+917258043053', 'SSF5769901'),
('+917870711852', 'SSF5323720'),
('+917255058496', 'SSF5769323'),
('+917061177226', 'SSF5981144'),
('+917082546952', 'SSF5822058'),
('+917463987276', 'SSF3306800'),
('+917814042660', 'SSF5412151'),
('+917634048579', 'SSF5102993'),
('+917879551257', 'SSF3488564'),
('+917488033010', 'SSF5990089'),
('+917079863894', 'SSF5339224'),
('+917571819221', 'SSF5533059'),
('+917281995737', 'SSF5717989'),
('+917000083294', 'SSF5591447'),
('+918853856547', 'SSF5787333'),
('+918275419297', 'SSF2820840'),
('+918051362224', 'SSF5923230'),
('+918084502330', 'SSF5812162'),
('+918817934490', 'SSF3623901'),
('+918002006608', 'SSF5952263'),
('+918815911091', 'SSF5342075'),
('+918340791356', 'SSF5339636'),
('+918817038921', 'SSF6065903'),
('+918271514716', 'SSF3517297'),
('+918789370856', 'SSF5412550'),
('+918521080867', 'SSF5134873'),
('+918235692933', 'SSF3604379'),
('+918863065150', 'SSF5548146'),
('+918825111323', 'SSF5733575'),
('+918521246062', 'SSF5781641'),
('+918292629891', 'SSF5596712'),
('+918207593513', 'SSF5300550'),
('+918084310468', 'SSF5562745'),
('+918529185714', 'SSF3507370'),
('+919669504716', 'SSF5942216'),
('+919523367758', 'SSF5563747'),
('+919302009423', 'SSF5455325'),
('+919301896482', 'SSF5949224'),
('+919616262440', 'SSF5739884'),
('+919162764532', 'SSF5552178'),
('+919350801026', 'SSF5922362'),
('+919131599253', 'SSF5798828'),
('+919042747624', 'SSF6245659'),
('+919718596334', 'SSF5989488'),
('+919199601689', 'SSF3595710'),
('+919002295080', 'SSF3968836'),
('+919256139548', 'SSF3512323'),
('+919303985547', 'SSF5345503'),
('+919006484694', 'SSF5309906'),
('+919241224838', 'SSF5001796'),
('+919691352448', 'SSF5501480'),
('+919935997004', 'SSF5749720'),
('+919685469150', 'SSF5493172'),
('+919905760638', 'SSF5769391'),
('+919031504236', 'SSF5333897'),
('+919341332013', 'SSF5860641'),
('+919199165444', 'SSF5771041'),
('+919361812245', 'SSF5759898'),
('+919905909826', 'SSF5770516'),
('+919602914256', 'SSF3463907'),
('+919669509799', 'SSF3719548'),
('+919279397088', 'SSF5324485'),
('+919137498863', 'SSF3721870'),
('+919360558195', 'SSF5412153'),
('+919155185827', 'SSF5933360'),
('+919588612335', 'SSF6114017'),
('+919263891043', 'SID951375762158'),
('+919608324379', 'SSF5298406'),
('+919234325994', 'SSF5374584'),
('+919693839882', 'SSF3678988'),
('+917970340038', 'SSF5771082'),
('+918699252282', 'SSF5706299'),
('+918467852258', 'SSF5814960'),
('+919634853415', 'SSF4797189'),
('+919554372950', 'SSF6207513'),
('+919651997232', 'SSF6207564'),
('+919523692314', 'SSF5973118'),
('+918809137418', 'SSF5659738'),
('+919835612763', 'SSF5747542'),
('+919174782741', 'SID951373976406'),
('+919354311368', 'SID951375798891'),
('+919693138180', 'SID2125779204'),
('+916204704984', 'SSF5613385'),
('+916394624414', 'SSF6064662'),
('+919572711269', 'SSF6076197'),
('+917877215511', 'SSF2680507'),
('+916206760789', 'SSF5675407'),
('+917903853371', 'SSF5514405'),
('+917209333773', 'SSF5682917'),
('+917323943822', 'SSF3496532'),
('+917479622044', 'SSF5806688'),
('+917739373389', 'SSF3218427'),
('+917008293875', 'SSF5991282'),
('+917054839833', 'SSF5733432'),
('+917355595279', 'SSF5751061'),
('+917742798015', 'SSF5401803'),
('+917488301471', 'SSF5321878'),
('+917493023581', 'SSF5647419'),
('+918271574539', 'SSF5347530'),
('+918825377904', 'SSF2922920'),
('+918877102542', 'SSF5770616'),
('+919708754092', 'SSF5640469'),
('+919508147989', 'SSF5809959'),
('+919931975595', 'SSF3221636'),
('+919125331443', 'SSF5685167'),
('+919696022387', 'SSF5702832'),
('+919839763729', 'SSF5193819'),
('+919234530539', 'SSF5753420'),
('+917355273038', 'SSF4564957'),
('+917070623144', 'SSF5664463'),
('+919110963840', 'SSF5666694'),
('+918130467419', 'SSF5477775'),
('+919451787818', 'SSF5672734'),
('+917856928591', 'CID212403652'),
('+916205712004', 'SID951374447036'),
('+916209169397', 'SSF5403020'),
('+916203734908', 'SSF4987663'),
('+916207021069', 'SSF5506147'),
('+916202125065', 'SSF4865069'),
('+916296431557', 'SSF5061511'),
('+916206023950', 'SSF5417474'),
('+917230021855', 'SSF5055040'),
('+917488310059', 'SSF5388399'),
('+917666463813', 'SSF5322223'),
('+917781076747', 'SSF5386595'),
('+917250085223', 'SID951374338627'),
('+917633977527', 'SSF6038938'),
('+917371957804', 'SSF5556507'),
('+917415645016', 'SSF5303273'),
('+917498231797', 'SSF3519606'),
('+917542851793', 'SSF5444479'),
('+917759933200', 'SSF5543193'),
('+917482033429', 'SSF5409284'),
('+917970450928', 'SSF4979012'),
('+917489264644', 'SSF5267443'),
('+918207585264', 'SSF5505544'),
('+918298260791', 'SSF5215384'),
('+918651525103', 'SSF2939076'),
('+918235602488', 'SSF4928800'),
('+918757945907', 'SSF5554354'),
('+919709738496', 'SSF5393743'),
('+919334706845', 'SSF3535611'),
('+919471878740', 'SSF4403534'),
('+919608474766', 'SSF5515448'),
('+919216730764', 'SSF5384216'),
('+919754865962', 'SSF3430662'),
('+919310032114', 'SSF5341471'),
('+919525244780', 'SSF4865070'),
('+919695942483', 'SSF4877715'),
('+919334565056', 'SSF5406927'),
('+919205244581', 'SSF5442861'),
('+919708727875', 'SSF5434410'),
('+919708980090', 'SSF4819927'),
('+919329831806', 'SSF5060794'),
('+919113370660', 'SSF5479666'),
('+919934133372', 'SSF4791039'),
('+919205068508', 'SSF4938525'),
('+919171531419', 'SSF4928594'),
('+919555689277', 'SSF5456041'),
('+919153414033', 'SSF5413618'),
('+918294304015', 'SSF5653531'),
('+919708273980', 'SSF5467764'),
('+918092242334', 'SSF5678151'),
('+918409569378', 'SSF5550291'),
('+917398205080', 'SSF6138210'),
('+918294195476', 'SSF6082557'),
('+918521085324', 'SSF6082150'),
('+919135362265', 'SSF6061074'),
('+918540877797', 'SSF6337667'),
('+919199911275', 'SSF6095322'),
('+917569145451', 'SSF6111203'),
('+918540904053', 'SSF6090827'),
('+917061314704', 'SSF6200533'),
('+918709900479', 'SSF6210192'),
('+916468664644', 'SID2125248415'),
('+918523964215', 'SID2125641345'),
('+918252662612', 'SID951372912972'),
('+916207440091', 'SSF4785574'),
('+916267732502', 'SSF4898534'),
('+916267189130', 'SSF4468583'),
('+916200658962', 'SSF4871514'),
('+916265225361', 'SSF2821536'),
('+917004867604', 'SID951375715465'),
('+917258852397', 'SSF4873623'),
('+917828382826', 'SSF4804598'),
('+917761928863', 'SSF4471381'),
('+917488765369', 'SSF4690584'),
('+917635049614', 'SSF6365827'),
('+917004028918', 'SSF5029904'),
('+917987363718', 'SSF5100271'),
('+917091811748', 'SSF2455360'),
('+917600552941', 'SSF4905837'),
('+917647095348', 'SSF3316474'),
('+917250468493', 'SSF5051536'),
('+917250817756', 'SSF4491181'),
('+917389074983', 'SSF4880913'),
('+917987867957', 'SSF3422987'),
('+918298148548', 'SSF5017339'),
('+918252526580', 'SSF4470114'),
('+918292979866', 'SSF4607633'),
('+918002193956', 'SSF4741466'),
('+918540947156', 'SSF4882284'),
('+918319430841', 'SSF4841284'),
('+918809644356', 'SSF4866235'),
('+918092640968', 'SSF5074894'),
('+918515987445', 'SSF4784270'),
('+918409338067', 'SSF4784341'),
('+918950736936', 'SSF5062593'),
('+918287140615', 'SSF4940206'),
('+918210027729', 'SSF4858509'),
('+918103881893', 'SSF4893783'),
('+918789767848', 'SID951373365008'),
('+919576532401', 'SSF2554825'),
('+919155328579', 'SSF4990498'),
('+919234770715', 'SSF4472103'),
('+919905528938', 'SSF4393054'),
('+919264215360', 'SSF4933683'),
('+919797997989', 'SSF3725160'),
('+919608858824', 'SSF4870005'),
('+919334430638', 'SSF2947679'),
('+919770094355', 'SSF4679179'),
('+919691492672', 'SSF4446417'),
('+919301751283', 'SSF4832728'),
('+919770318214', 'SSF4552462'),
('+919341143466', 'SSF5025236'),
('+919546922805', 'SSF4926159'),
('+919315648266', 'SSF4858237'),
('+919534468752', 'SSF2542521'),
('+919955818319', 'SSF4784171'),
('+919109269809', 'SID951376222950'),
('+919142353801', 'SSF4821308'),
('+919135864016', 'SSF4950776'),
('+919709169683', 'SSF4947106'),
('+916297472474', 'SSF6069737'),
('+916268474105', 'SSF4827576'),
('+916267686496', 'SSF4846643'),
('+916209560288', 'SSF4793900'),
('+916207217086', 'SSF4775291'),
('+917804817587', 'SSF4679264'),
('+917759043769', 'SSF4240244'),
('+917061935795', 'SSF4743110'),
('+917491863758', 'SSF4762867'),
('+917209784565', 'SSF4848313'),
('+917982478148', 'SSF4807677'),
('+917735994197', 'SSF2784943'),
('+917033169319', 'SSF4720437'),
('+917877609548', 'SSF4813516'),
('+917033662674', 'SSF4752889'),
('+917023930309', 'SSF4418437'),
('+918094583393', 'SSF2901811'),
('+918827517192', 'SSF4833277'),
('+918696352987', 'SSF4836070'),
('+918400482628', 'SSF4806656'),
('+918355655568', 'SID951373426219'),
('+918092769796', 'SSF4874423'),
('+918264988379', 'SSF4440429'),
('+918769668680', 'SSF4328900'),
('+919256553654', 'SSF2947354'),
('+919521761478', 'SSF4902167'),
('+919358630779', 'SSF4792431'),
('+919279162172', 'SSF4791664'),
('+919162490709', 'SSF4667314'),
('+919764646979', 'SID951375438927'),
('+919631376323', 'SSF4728839'),
('+919523945701', 'SSF4683071'),
('+919931041215', 'SSF2923055'),
('+919973628517', 'SSF4681088'),
('+919754937922', 'SSF2754038'),
('+918809498233', 'SSF5430268'),
('+918712396330', 'SSF6099588'),
('+919541613908', 'SSF5410945'),
('+918601852167', 'SSF5767106'),
('+917974753495', 'SID951375206104'),
('+917361877705', 'SSF5398502'),
('+916299331462', 'SSF4364056'),
('+916393466518', 'SSF4401870'),
('+916378097116', 'SSF4285849'),
('+916377285130', 'SSF4356501'),
('+917089101015', 'SSF2855867'),
('+917070374728', 'SSF4310906'),
('+917082616675', 'SSF2405197'),
('+917745944207', 'SID951375964655'),
('+917851890326', 'SSF4146224'),
('+917357104570', 'SSF3956991'),
('+917597107980', 'SSF4293839'),
('+917014781098', 'SSF2601202'),
('+917091306126', 'SSF4308761'),
('+917665478037', 'SSF4452110'),
('+917737342159', 'SSF4349923'),
('+917482950263', 'SSF4070434'),
('+918529922935', 'SSF4404682'),
('+918625040922', 'SID951375685289'),
('+918290765355', 'SSF4319206'),
('+918302823327', 'SSF2593994'),
('+919630312575', 'SSF4271487'),
('+919508946272', 'SSF4327653'),
('+919352237137', 'SSF4573854'),
('+919509146542', 'SSF4525435'),
('+919982261454', 'SSF4450186'),
('+919898515582', 'SSF4382058'),
('+919602908534', 'SSF4510195'),
('+919771479231', 'SSF4369342'),
('+919334112091', 'SSF5761259'),
('+916261100568', 'SSF3944966'),
('+917209883715', 'SID951374477620'),
('+917884467879', 'SID951373669633'),
('+918720080185', 'SSF4291450'),
('+918949883065', 'SSF4257369'),
('+919594538565', 'SSF3886910'),
('+919111979385', 'SSF4290727'),
('+919304588326', 'SID951375258276'),
('+919352385351', 'SSF4295264'),
('+919079878589', 'SSF4295243'),
('+916397548849', 'SSF3678252'),
('+916249849494', 'SSF3709963'),
('+917480798112', 'SSF3599374'),
('+917587849935', 'SID951375273041'),
('+918839311171', 'SSF4277221'),
('+918951807268', 'SSF3575467'),
('+918306072197', 'SSF3759659'),
('+918350697218', 'SSF3723605'),
('+918005728441', 'SSF3960591'),
('+918878654306', 'SSF4396810'),
('+918769290635', 'SSF2656543'),
('+919764986898', 'SSF3587696'),
('+919991943301', 'SSF2637200'),
('+917073574800', 'SSF3886760'),
('+917854646656', 'SSF3608196'),
('+919610104139', 'SSF3903802'),
('+919602914285', 'SSF3804450'),
('+919636713695', 'SID951374641463'),
('+917691925355', 'SSF2398886'),
('+916268240001', 'SSF5446595'),
('+917742651577', 'SSF5537356'),
('+918817382782', 'SSF5376950'),
('+918226008293', 'SSF5715939'),
('+919575784014', 'SSF5481523'),
('+919770873182', 'SSF5999959'),
('+919399721747', 'SSF5956303'),
('+916378368826', 'SSF2400558'),
('+919664057769', 'SID951375059519'),
('+918357840896', 'SID951375283780'),
('+917485020515', 'SSF5254733'),
('+919801437459', 'SSF4455543'),
('+919799986770', 'SID951374768069'),
('+917879810503', 'CID129108425'),
('+918839053957', 'CID076606553'),
('+918878140944', 'SID951374827603'),
('+919039412849', 'SSF3541122'),
('+918866628546', 'SID951374772909'),
('+917981464485', 'SSF4411979'),
('+918290089290', 'SID951375106224'),
('+917607108889', 'SSF6595488'),
('+917050849727', 'SSF5962690'),
('+917070028011', 'SID951375253016'),
('+918109692686', 'SID2125289092'),
('+918292881409', 'SID951376120251'),
('+919918245011', 'SSF5025830'),
('+916454245912', 'SID951375172048'),
('+918818858014', 'SID951373389831'),
('+919340609340', 'SSF3254567'),
('+919380284215', 'SSF6315249'),
('+919993946289', 'SID951374277094'),
('+916254955484', 'SSF3246559'),
('+919950021105', 'SID951375157161'),
('+917357580126', 'SSF6193461'),
('+917974656904', 'SSF6020557'),
('+919773552166', 'SSF5524582'),
('+916256328654', 'SSF3394381'),
('+916268186409', 'SID951375591486'),
('+917587116620', 'SID951374578657'),
('+919399983967', 'CID213802004'),
('+918651047638', 'SSF4993793'),
('+916206300180', 'SID951375353146'),
('+919523221868', 'SID951375645165'),
('+917067916769', 'SID951374676011'),
('+917028728067', 'SID951376017643'),
('+917597764907', 'SID951376052645'),
('+918604989301', 'SSF4151768'),
('+917307183973', 'SID951374134270'),
('+916393811350', 'SSF3673871'),
('+916958425453', 'SSF3625643'),
('+917827051983', 'SSF4809506'),
('+918305180493', 'SSF2957849'),
('+918102253116', 'SSF2416065'),
('+919621551665', 'SSF5470154'),
('+918000244273', 'SSF3893373'),
('+917880257528', 'SID951374970959'),
('+919755518206', 'CID191604927'),
('+917987065833', 'SSF6143928'),
('+919097732878', 'SSF3814015'),
('+919942688532', 'SSF4026713'),
('+916205218811', 'SID951375222854'),
('+919113365905', 'SID951375493619'),
('+917079332938', 'SSF5343114'),
('+918305754743', 'SSF3969566'),
('+919753086610', 'SID2125493246'),
('+919461861305', 'SSF4762002'),
('+919352036845', 'SID951375152985'),
('+916299587645', 'SSF3446126'),
('+919329079102', 'CID084608599'),
('+916206100321', 'SSF4049516'),
('+919302149718', 'CID129108927'),
('+919931865699', 'SID2125465259'),
('+919238944023', 'SSF6083605'),
('+919575446306', 'SSF3310847'),
('+918825358448', 'SID951374475577'),
('+918298836401', 'SID951374713263'),
('+917415731354', 'SSF5473996'),
('+919984363584', 'SSF3902221'),
('+916376576638', 'SID951375223050'),
('+919584290492', 'SID951374519492'),
('+917067857493', 'SID951373139408'),
('+918720878117', 'CID118113115'),
('+919555841545', 'SSF3625735'),
('+917879882336', 'SSF2719597'),
('+917061471370', 'SSF6141455'),
('+919201458447', 'SSF3722992'),
('+919672386458', 'SID951375355442'),
('+916387411715', 'SSF4074286'),
('+917803093549', 'SSF3916193'),
('+919325159419', 'SID951375088649'),
('+918229061027', 'SSF3384626'),
('+916264017534', 'SID951373766348'),
('+919178927561', 'SSF3393731'),
('+916266281887', 'SID951373766490'),
('+917987006894', 'SID951374372572'),
('+919799288549', 'SSF4919982'),
('+919752328084', 'SID2125162791'),
('+919131014123', 'SSF2435852'),
('+919691938470', 'CID239800923'),
('+919798639061', 'SSF2924996'),
('+917415876199', 'SID951375394471'),
('+919584393061', 'CID128802426'),
('+918458820122', 'SID951376159116'),
('+919919446720', 'SSF3172532'),
('+919559823678', 'SSF4249053'),
('+916394878768', 'SSF5328973'),
('+919589524567', 'CID038502987'),
('+919019860154', 'SSF3681165'),
('+919279614031', 'SSF3668839'),
('+917367022030', 'SSF3545923'),
('+919532831028', 'SSF4084927'),
('+919098314941', 'SID951373641161'),
('+916260589479', 'SSF4336351'),
('+918709967438', 'SID951375469422'),
('+918603391943', 'SSF5732812'),
('+919983752408', 'SSF2691309'),
('+916264373522', 'CID135301040'),
('+918174857248', 'SSF5533786'),
('+916299337694', 'SID951375678119'),
('+917879893067', 'SID2125486548'),
('+918084689544', 'SSF5683345'),
('+917724921124', 'SID2125266537'),
('+919157518271', 'SSF4629007'),
('+917494872756', 'SID951375697057'),
('+919754700571', 'SSF3210326'),
('+919244920575', 'SID951375597192'),
('+917828109258', 'SID951375479236'),
('+918305692730', 'SID951374711915'),
('+919576158682', 'SSF2366013'),
('+919263828089', 'SID951374672746'),
('+917050791175', 'SSF3808959'),
('+919651080585', 'SSF3547746'),
('+917992487886', 'SSF5056183'),
('+918002894569', 'SSF3077679'),
('+916263509806', 'SID2125624864'),
('+916200420972', 'CID211203914'),
('+918359003010', 'CID038502361'),
('+919238482263', 'SSF4557981'),
('+919546494897', 'CID171505847'),
('+919079667527', 'SSF2828049'),
('+916243495275', 'SSF3545836'),
('+917488235108', 'SID951374022575'),
('+919971054521', 'SID951375108937'),
('+919390614082', 'SSF3935837'),
('+917091101441', 'SSF3667474'),
('+917379917828', 'SSF3124575'),
('+919516827813', 'SSF2728628'),
('+919065550729', 'SID951375846116'),
('+916264983096', 'SID951375323203'),
('+919169610019', 'SSF4677137'),
('+919606654413', 'SSF2546105'),
('+918809983706', 'SSF4462718'),
('+919343712204', 'SID951374895802'),
('+918858819532', 'SSF4370979'),
('+916325413256', 'SID951376125431'),
('+917667979464', 'SID951373296309'),
('+919162436214', 'SSF3303364'),
('+919973576790', 'SSF3179084'),
('+919096112871', 'SID951375053725'),
('+918957583160', 'SSF2598973'),
('+919752341845', 'SID951375384751'),
('+916265919629', 'SID951375617876'),
('+917489276975', 'SID951375881759'),
('+918435928795', 'SID951374325213'),
('+918114588965', 'SID951374720680'),
('+919691356182', 'SID951375072972'),
('+916266020873', 'SSF2351766'),
('+917700039052', 'SSF2453094'),
('+917061895866', 'SSF2960602'),
('+917426839157', 'SID951376155421'),
('+918252050052', 'SID951376015800'),
('+918714671539', 'SSF2554833'),
('+919931091031', 'SSF2589630'),
('+919153062343', 'SSF2436177'),
('+916265810784', 'SSF3816763'),
('+916205534981', 'SSF5879602'),
('+916202319073', 'SSF5828147'),
('+916266271764', 'SSF5665693'),
('+916390610577', 'SSF5618163'),
('+916378550353', 'SSF5835919'),
('+916394551852', 'SSF5922503'),
('+916386725514', 'SSF6083611'),
('+916265540898', 'SSF3976027'),
('+916204247304', 'SSF5758158'),
('+916291755169', 'SSF5946055'),
('+916203215779', 'SSF3202799'),
('+917425850061', 'SSF3174882'),
('+917746817279', 'SSF5939124'),
('+917739338436', 'SSF5861327'),
('+917667656542', 'SSF5844959'),
('+917250105844', 'SSF5829716'),
('+917499249009', 'SSF5853358'),
('+917800201100', 'SSF3268177'),
('+917241195322', 'SSF3798251'),
('+917974237646', 'SSF5312209'),
('+917704914235', 'SSF5912069'),
('+917033634520', 'SSF5740306'),
('+917782939030', 'SSF6066485'),
('+917631433658', 'SSF5932301'),
('+917542073474', 'SSF5881865'),
('+917007526850', 'SSF5930292'),
('+917978174178', 'SSF5815740'),
('+918541808139', 'SSF6197196'),
('+918340776448', 'SSF6004999'),
('+918294661550', 'SSF3999225'),
('+918888119332', 'SSF3364329'),
('+918340181742', 'SSF3898541'),
('+918529478543', 'SSF3260781'),
('+918521103317', 'SSF4247921'),
('+918709769810', 'SSF6230174'),
('+918092849966', 'SSF5783708'),
('+919608672053', 'SSF5828286'),
('+919006404124', 'SSF5761848'),
('+919693388521', 'SSF5608491'),
('+919693933308', 'SSF5854458'),
('+919142913928', 'SSF5882551'),
('+919670588506', 'SSF5831766'),
('+919555146616', 'SSF5905864'),
('+919131391668', 'SSF5864572'),
('+919279432495', 'SSF5590385'),
('+919340872878', 'SSF5947043'),
('+919060938268', 'SSF3588808'),
('+919340862696', 'SSF5653298'),
('+919151073759', 'SSF6083251'),
('+919263383452', 'SSF3249444'),
('+919662476324', 'SSF5887092'),
('+919984766380', 'SSF5858238'),
('+919032254834', 'SSF6139363'),
('+919931788773', 'SSF5844107'),
('+918789192484', 'SSF2689402'),
('+919128784298', 'SID951376162906'),
('+916266197955', 'SSF3818527'),
('+916203140144', 'SSF5840205'),
('+917782074438', 'SSF6045036'),
('+917004549809', 'SSF5697690'),
('+917061252913', 'SSF5706143'),
('+917070328060', 'SSF3858043'),
('+917223861285', 'SSF5872889'),
('+917415363237', 'SSF5871482'),
('+918470923309', 'SSF3108886'),
('+918789240952', 'SSF5621667'),
('+918252499815', 'SSF5602287'),
('+918294660505', 'SSF3934123'),
('+919801896823', 'SSF3306988'),
('+919279191754', 'SSF3115429'),
('+919153682911', 'SSF5654946'),
('+919958172747', 'SSF5711280'),
('+919354025531', 'SSF3131262'),
('+919162481523', 'SSF5719612'),
('+919685575751', 'SSF5883135'),
('+919546730283', 'SSF3574205'),
('+919572304550', 'SSF5913696'),
('+916202655641', 'SSF6031391'),
('+916205855493', 'SSF5640421'),
('+918511712931', 'SSF6144652'),
('+919229127831', 'SSF5441949'),
('+919821839374', 'SSF5421729'),
('+919508632919', 'SSF6069994'),
('+919798849841', 'SSF6331700'),
('+919608746447', 'SSF5608277'),
('+917489928040', 'CID076602034'),
('+916390357785', 'SSF6209618'),
('+918051589449', 'SSF6199493'),
('+918409483959', 'SSF5522523'),
('+918235437578', 'SSF5365143'),
('+919279953439', 'SSF4672958'),
('+919939170761', 'SSF5748138'),
('+919725241944', 'SSF5506761'),
('+918092831376', 'CID204505385'),
('+916209342641', 'SSF5420877'),
('+917250518586', 'SSF5702620'),
('+917634031031', 'SSF5812307'),
('+917482824619', 'SSF6102369'),
('+918881503204', 'SSF5808880'),
('+918355913941', 'SSF6067571'),
('+919901822356', 'SSF5724388'),
('+919835501068', 'SSF5613381'),
('+919263013639', 'SSF6159155'),
('+919142186986', 'SSF5626899'),
('+919102599711', 'SSF5703610'),
('+916284993529', 'SSF2573686'),
('+917050844303', 'SSF2620043'),
('+918121990270', 'SSF2407197'),
('+919534940119', 'SSF2794722'),
('+916376990653', 'SSF3014597'),
('+916205960801', 'SSF5388451'),
('+916268083507', 'SSF5319116'),
('+916263363072', 'SSF3190513'),
('+917292927823', 'SSF3290926'),
('+917396626210', 'SSF3840068'),
('+917861858943', 'SSF5707763'),
('+917091673941', 'SSF5410820'),
('+917052992236', 'SSF5392549'),
('+917748967334', 'SSF3597602'),
('+917294026253', 'SSF5487783'),
('+917764925364', 'SSF5439752'),
('+917081513726', 'SSF5526826'),
('+917360852838', 'SSF5143767'),
('+917549443997', 'SSF5441661'),
('+917357289525', 'SSF2793193'),
('+917023619481', 'SSF5288345'),
('+918235293143', 'SSF6450318'),
('+918899166080', 'SSF4000200'),
('+918262857591', 'SSF5935410'),
('+918271696434', 'SSF5335131'),
('+918961523281', 'SSF5416433'),
('+918814926747', 'SSF5438193'),
('+918829829069', 'SSF5512675'),
('+918604850246', 'SSF5617510'),
('+918601588319', 'SSF3507418'),
('+918817982032', 'SSF5410946'),
('+918757839814', 'SSF5576065'),
('+918757407562', 'SSF5375594'),
('+918890121984', 'SSF5613880'),
('+918815841527', 'SSF5454934'),
('+918269369349', 'SSF3321550'),
('+919875722872', 'SSF3149065'),
('+919939056368', 'SSF5574598'),
('+919123491271', 'SSF5426984'),
('+919660102314', 'SSF5434102'),
('+919507509277', 'SSF2730382'),
('+919334705981', 'SSF3131701'),
('+919905750254', 'SID951374276202'),
('+919617682394', 'SSF5245539'),
('+919166213065', 'SSF2307874'),
('+919131599462', 'SID951375426040'),
('+919905851174', 'SID951374278662'),
('+919199199252', 'SSF5464533'),
('+919199423048', 'SSF5463508'),
('+919523143869', 'SSF5998377'),
('+919608342210', 'SSF5599577'),
('+919304582223', 'SSF5559825'),
('+919171761984', 'SSF5600590'),
('+919031916491', 'SSF3352487'),
('+919511590224', 'SSF5298413'),
('+916205291887', 'SSF5667193'),
('+919511470265', 'SSF5918447'),
('+919041316939', 'SSF5692284'),
('+916201831449', 'SID951374608078'),
('+917974480741', 'SSF5236372'),
('+917667017415', 'SSF3048113'),
('+917722813508', 'SSF5515526'),
('+917739612780', 'SSF4137598'),
('+917362076261', 'SSF5577952'),
('+917870954121', 'SSF5524560'),
('+917631271988', 'SSF5161160'),
('+917697389740', 'SSF5318995'),
('+917645989109', 'SSF5374711'),
('+918757154484', 'SSF3499099'),
('+918734009631', 'SSF4775514'),
('+918228007980', 'SSF5746756'),
('+918538913042', 'SSF4789955'),
('+918210620994', 'SSF4652936'),
('+918002218852', 'SID951375228030'),
('+919794189673', 'SSF5811040'),
('+919708779211', 'SSF3248028'),
('+919234083882', 'SSF5376902'),
('+919234984459', 'SSF5374622'),
('+919521400357', 'SSF5324358'),
('+919771611424', 'SSF5808169'),
('+919060543043', 'SSF2766129'),
('+919153662861', 'SSF5321836'),
('+919304242357', 'SSF5487249'),
('+919708140161', 'SSF5742546'),
('+919973320815', 'SSF5347592'),
('+919693470954', 'SSF5350612'),
('+919006101024', 'SSF5170979'),
('+919229127972', 'SSF5708096'),
('+919817679353', 'SSF2911104'),
('+919631844959', 'SSF2679779'),
('+919534873189', 'SSF5155535'),
('+919179387359', 'SSF5358235'),
('+919608734821', 'SSF5445046'),
('+917091794165', 'SSF4879103'),
('+918102008462', 'SSF4964053'),
('+916207230582', 'SSF4778867'),
('+917700822063', 'SSF6244962'),
('+918920909508', 'SSF5941122'),
('+918581853366', 'SSF6026109'),
('+918292551517', 'SSF6157121'),
('+918002756665', 'SSF6213117'),
('+918360126749', 'SSF6157435'),
('+919153642977', 'SSF6225170'),
('+916267812822', 'CID207300777'),
('+916204321924', 'SSF4681395'),
('+916395357706', 'SSF4794813'),
('+916208688880', 'SSF3593388'),
('+916267950945', 'SSF4743601'),
('+916376654224', 'SSF4972381'),
('+916262765885', 'SSF3322093'),
('+916266751901', 'SSF4413000'),
('+916367053232', 'SSF4938160'),
('+916263497217', 'SSF5277919'),
('+916205276307', 'SSF6294997'),
('+916377489262', 'SID951374883630'),
('+916203050632', 'SID951376093548'),
('+917488346425', 'SSF4780445'),
('+917340633369', 'SSF5230634'),
('+917665841918', 'SSF4774303'),
('+917209849966', 'SSF3189694'),
('+917544869986', 'SSF6256671'),
('+917292992716', 'SSF5406828'),
('+917202005153', 'SSF4656627'),
('+917322953904', 'SSF2730032'),
('+917049805769', 'SSF2336008'),
('+917654097229', 'SSF3458913'),
('+917372810775', 'SSF5097999'),
('+917879224624', 'SSF4773246'),
('+917742512249', 'SSF4743415'),
('+917061468881', 'SSF4732549'),
('+917742715326', 'SSF5307055'),
('+917724814113', 'SSF3224244'),
('+917898577279', 'SSF4711971'),
('+917322011124', 'SSF2946862'),
('+917893528565', 'SSF4662050'),
('+917427844643', 'SSF4786677'),
('+918084362166', 'SID951375610471'),
('+918094258188', 'SID951375160177'),
('+918409920693', 'SSF2633458'),
('+918235320231', 'SSF4863234'),
('+918810254860', 'SSF4693901'),
('+918319490156', 'SSF5219488'),
('+918770232253', 'SSF4058595'),
('+918837754655', 'SSF6249801'),
('+918917847811', 'SSF6275145'),
('+918261824772', 'SSF5188968'),
('+918294321039', 'SSF4714125'),
('+918128801871', 'SSF3095623'),
('+918355938385', 'SID951376169961'),
('+918085100357', 'SSF4761343'),
('+918539870963', 'SSF4988720'),
('+918423284155', 'SSF3999138'),
('+918423325306', 'SSF5161898'),
('+919709176211', 'SSF3133791'),
('+919165293027', 'SSF4825481'),
('+919102139689', 'SSF2855847'),
('+919343559523', 'SSF4798644'),
('+919319789293', 'SSF4798268'),
('+919663254125', 'SID951375368972'),
('+919165996470', 'SSF3243888'),
('+919709194325', 'SSF4765604'),
('+919279902881', 'SSF2657508'),
('+919244581675', 'SSF4760181'),
('+919680483505', 'SSF4823895'),
('+919301421148', 'SID2125345094'),
('+919635668656', 'SID951374538673'),
('+919098285751', 'SSF4766293'),
('+919111051869', 'SID951375636474'),
('+919545210533', 'SID951375752620'),
('+919532816458', 'SID951375372747'),
('+919131872072', 'SSF4290636'),
('+919241740015', 'SSF5172690'),
('+919784031600', 'SID951375981445'),
('+919303815493', 'SSF4920944'),
('+919498484919', 'SID951374987334'),
('+919109450069', 'SSF5320788'),
('+919098676633', 'SID951375416795'),
('+919128698557', 'SSF4743247'),
('+919508532378', 'SSF4725243'),
('+919341481733', 'SSF6317185'),
('+918863997381', 'SSF5716618'),
('+919016286154', 'SSF5520913'),
('+919118852441', 'SSF4837177'),
('+919798085451', 'SSF5783401'),
('+919554519931', 'SSF6170357'),
('+918298834855', 'SSF5436100'),
('+916207703852', 'SSF5166019'),
('+918757420825', 'SID951373457959'),
('+919936760979', 'CID212300001'),
('+916232423542', 'SSF4568556'),
('+916260710610', 'SSF5027589'),
('+916387603399', 'SSF5001649'),
('+916299231243', 'SSF4565313'),
('+916209579766', 'SSF6209435'),
('+916204651624', 'SSF6214056'),
('+916264759320', 'SSF6066763'),
('+916201169610', 'SSF3026969'),
('+916261387897', 'SSF5004155'),
('+917544059520', 'SSF4530852'),
('+917362097758', 'SSF4560211'),
('+917416922807', 'SSF5081500'),
('+917544839904', 'SSF4154783'),
('+917838432649', 'SSF6137239'),
('+917352773951', 'SSF2460272'),
('+917479880737', 'SSF4560783'),
('+917491015687', 'SSF6178434'),
('+917827873665', 'SSF4560802'),
('+917310732267', 'SSF5083821'),
('+917367972075', 'SSF5089646'),
('+917488698413', 'SSF4328924'),
('+917903941325', 'SSF4564549'),
('+917240442469', 'SSF3454335'),
('+917634940855', 'SSF4592481'),
('+917739262473', 'SSF5059879'),
('+917488317719', 'SSF4711490'),
('+917805078411', 'SSF4351107'),
('+918905396956', 'SSF5195955'),
('+918235768504', 'SSF6188649'),
('+918797757311', 'SSF4451557'),
('+918305426251', 'SSF4719156'),
('+918269035415', 'SSF4506965'),
('+918949633433', 'SSF5039224'),
('+918233779111', 'SSF4762592'),
('+918207528556', 'SSF6174565'),
('+918252862490', 'SSF6178639'),
('+918227983181', 'SSF6178755'),
('+918769661825', 'SSF5069946'),
('+918890024036', 'SSF5033626'),
('+918305484929', 'SSF4556227'),
('+918000649746', 'SSF5231413'),
('+918406096598', 'SSF6182177'),
('+918126280578', 'SSF6194156'),
('+918252376198', 'SSF4560256'),
('+918093751419', 'SSF3568053'),
('+918409223351', 'SSF3224673'),
('+918788552356', 'SSF4702356'),
('+918789426829', 'SSF4689499'),
('+918333859078', 'SSF4486005'),
('+918306780760', 'SSF4759146'),
('+918302514919', 'SSF4640410'),
('+918235736488', 'SSF4936121'),
('+918949131503', 'SSF4329066'),
('+918539097371', 'SSF4617099'),
('+918084517002', 'SSF3267604'),
('+918064635996', 'SSF3600998'),
('+918064644848', 'SSF3601005'),
('+919792711426', 'SSF3216226'),
('+919311673896', 'SSF4591080'),
('+919024741612', 'SSF4412279'),
('+919587222195', 'SSF4336298'),
('+919905497806', 'SSF4574304'),
('+919805454256', 'SSF4719104'),
('+919334923877', 'SSF6173134'),
('+919950675578', 'SSF4468913'),
('+919632214780', 'SID951375454704'),
('+919983028189', 'SSF3333725'),
('+919257620628', 'SSF4518877'),
('+919263199014', 'SSF5180540'),
('+919117737920', 'SSF6189125'),
('+919045147228', 'SSF2954993'),
('+919934452012', 'SSF4650591'),
('+919523402507', 'SSF4576936'),
('+919334392676', 'SSF4140527'),
('+919693189959', 'SSF4361139'),
('+919238169987', 'SSF6066768'),
('+919057546062', 'SSF4472814'),
('+919650949646', 'SID951375521450'),
('+919934835754', 'SSF4867608'),
('+919024507516', 'SSF3451983'),
('+919119100337', 'SSF3451984'),
('+919648490552', 'SSF4504985'),
('+919799612275', 'SSF4581320'),
('+919905980822', 'SSF4530072'),
('+919142774006', 'SSF4520169'),
('+919783621284', 'SSF2847834'),
('+919523513758', 'SSF4468523'),
('+919353686089', 'SSF4616988'),
('+919784616565', 'SSF3174047'),
('+919799754370', 'SSF4542909'),
('+919695533622', 'SSF3022032'),
('+917079983840', 'SSF5354193'),
('+919835821017', 'SSF5765674'),
('+918604435221', 'SSF6163815'),
('+919279437255', 'SSF4718348'),
('+917518573829', 'SSF5021588'),
('+919302019844', 'SSF6161376'),
('+916287952996', 'SSF4439192'),
('+917463904429', 'SSF6003875'),
('+917654305352', 'SSF2800129'),
('+918544099050', 'SSF4406896'),
('+919928211348', 'SSF4412695'),
('+919986523987', 'SSF3451121'),
('+919693915991', 'SSF4240219'),
('+919102312016', 'SSF4343255'),
('+919388008777', 'SID951376056779'),
('+919102216878', 'SSF2517318'),
('+918081453201', 'SSF5513573'),
('+916367298215', 'SSF4688267'),
('+916377990428', 'SSF3993389'),
('+916375030430', 'SSF4200429'),
('+916267204457', 'SSF4471017'),
('+916209556203', 'SSF4209821'),
('+916263429514', 'SSF4158436'),
('+917014054373', 'SSF2878658'),
('+917600709684', 'SSF4131193'),
('+917737913017', 'SSF4599251'),
('+917909975340', 'SID951374538854'),
('+917803880150', 'SSF4471974'),
('+917761016502', 'SSF4623332'),
('+917426970199', 'SSF2550643'),
('+917340543567', 'SSF4420816'),
('+917357987962', 'SSF4645543'),
('+917091409188', 'SSF4243146'),
('+917352715951', 'SSF4286731'),
('+917770892196', 'SSF4517649'),
('+917340404830', 'SSF4263221'),
('+917999613631', 'SSF4471977'),
('+917023334876', 'SSF4444571'),
('+917369031017', 'SSF4180848'),
('+917257952693', 'SSF4208714'),
('+917209523224', 'SSF3259998'),
('+917986296049', 'SSF4688802'),
('+917240842657', 'SSF4158933'),
('+917875576483', 'SID951375724859'),
('+917970364855', 'SSF4165462'),
('+917828818554', 'SID951375388350'),
('+918003032316', 'SSF4671044'),
('+918854037161', 'SSF4356587'),
('+918000126969', 'SSF4671015'),
('+918570000287', 'SID951376025639'),
('+918349567181', 'SSF4634609'),
('+918839384483', 'SSF4637663'),
('+918306883407', 'SSF5292660'),
('+918233893937', 'SSF4468013'),
('+918875621454', 'SSF5921596'),
('+918769741987', 'SSF4477050'),
('+918875350726', 'SSF4000073'),
('+918847430463', 'SID951375437836'),
('+918854062151', 'SSF4077667'),
('+918058129558', 'SSF4245171'),
('+918824468664', 'SSF4143972'),
('+918003487672', 'SID951375988081'),
('+919692282495', 'SSF4249544'),
('+919334743007', 'SSF4121227'),
('+919334531395', 'SSF4677391'),
('+919507028949', 'SSF5942636'),
('+919973673725', 'SSF4707885'),
('+919468662884', 'SSF4683912'),
('+919079856989', 'SSF4380657'),
('+919680974899', 'SSF4293552'),
('+919905344622', 'SSF4383394'),
('+919638580658', 'SSF2544332'),
('+919116357335', 'SSF4677038'),
('+919984465067', 'SSF2722778'),
('+919435953956', 'SSF2563175'),
('+919216132788', 'SSF4660682'),
('+919602340150', 'SSF4114694'),
('+919680252031', 'SSF4141166'),
('+919891465554', 'SSF4286754'),
('+919341334038', 'SSF4246179'),
('+919587868429', 'SSF4463730'),
('+919123271042', 'SSF3240750'),
('+919523838315', 'SSF3227960'),
('+919340643137', 'SSF4431103'),
('+919554596487', 'SSF5780079'),
('+919521410416', 'SSF4518402'),
('+919358267393', 'SSF4562702'),
('+919875700742', 'SSF5879749'),
('+919257452710', 'SSF4542801'),
('+919928234563', 'SSF3657706'),
('+919668635456', 'SSF2613422'),
('+916378071814', 'SSF3968719'),
('+916377463131', 'SSF2744266'),
('+916376753736', 'SSF4017914'),
('+916267175037', 'SSF3994157'),
('+916377559368', 'SSF5799871'),
('+916266096927', 'SSF4096553'),
('+916377308957', 'SSF4002656'),
('+916378965707', 'SSF3960674'),
('+917742710319', 'SSF2754327'),
('+917827581928', 'SSF3986383'),
('+917667091106', 'SSF4068322'),
('+917426848891', 'SSF3902585'),
('+918302647624', 'SSF3344031'),
('+918690704846', 'SSF4040245'),
('+918239854290', 'SSF4017817'),
('+918824133998', 'SSF4031658'),
('+918079734243', 'SSF2821158'),
('+918278676366', 'SSF4062874'),
('+918290648138', 'SSF4015278'),
('+919636874201', 'SID951375575090'),
('+919244193787', 'SSF5607900'),
('+919122304617', 'SSF4031205'),
('+919653752965', 'SSF3926054'),
('+919165632313', 'SSF4039933'),
('+919219125376', 'SSF4012646'),
('+919257959255', 'SSF4036493'),
('+919571721145', 'SSF4099272'),
('+919798683516', 'SID951374802694'),
('+919024044147', 'SSF2424291'),
('+919928934757', 'SSF4034472'),
('+916266679874', 'SSF3623155'),
('+916464545484', 'SSF3737669'),
('+916865656565', 'SSF3571220'),
('+917725986878', 'SSF3894849'),
('+917976682647', 'SSF5126348'),
('+917849972763', 'SSF5326183'),
('+917665092783', 'SSF5454274'),
('+917737950308', 'SSF3824733'),
('+917878977848', 'SSF3879426'),
('+917851081049', 'SSF3877226'),
('+917231993003', 'SSF3916937'),
('+917976014132', 'SSF4286202'),
('+917742957284', 'SSF3917829'),
('+918114213531', 'SSF5368889'),
('+918104558230', 'SSF3433957'),
('+918635748778', 'SSF3305316'),
('+918826186199', 'SSF5067386'),
('+918296202121', 'SSF3726020'),
('+918690122310', 'SSF2377770'),
('+918769479463', 'SSF5436481'),
('+918003030377', 'SSF3824012'),
('+918209239372', 'SSF2788994'),
('+919166327655', 'SSF5413284'),
('+919794019410', 'SSF5357743'),
('+919509720578', 'SSF5343476'),
('+919908078008', 'SID951375622108'),
('+919977995023', 'SSF2880596'),
('+919783022919', 'SSF5340762'),
('+919214715687', 'SSF5045735'),
('+919352630896', 'SSF3820373'),
('+919664164489', 'SSF4277179'),
('+919864959911', 'SSF3684039'),
('+919024808412', 'SSF3870506'),
('+917766984730', 'SSF5413549'),
('+918797432540', 'SSF5652345'),
('+918707324267', 'SSF5523576'),
('+917543874817', 'SSF6123711'),
('+919241743377', 'SSF4288731'),
('+919162677564', 'SSF5376216'),
('+916464688958', 'SSF3650043'),
('+916377890452', 'SSF5094783'),
('+916367772988', 'SSF5196843'),
('+916565646646', 'SSF3764944'),
('+917851836051', 'SSF5152876'),
('+917023943579', 'SSF2408260'),
('+917850947780', 'SSF4130332'),
('+917568194982', 'SSF5205029'),
('+917859983417', 'SSF5027147'),
('+917568901945', 'SSF5205199'),
('+917878820756', 'SSF5107253'),
('+917851982841', 'SSF5107158'),
('+917878753323', 'SSF5100953'),
('+917877343085', 'SSF3802197'),
('+917877810134', 'SSF5127030'),
('+918005845108', 'SSF5096131'),
('+918690299871', 'SSF5186872'),
('+918233565795', 'SSF5113250'),
('+918854831191', 'SSF5197432'),
('+918306365517', 'SSF5107390'),
('+918824516681', 'SSF5107152'),
('+918949122571', 'SSF5016894'),
('+918290794882', 'SSF5117107'),
('+918856888885', 'SSF3587862'),
('+918107353673', 'SSF3751038'),
('+919661803697', 'SID951373836911'),
('+919672822039', 'SSF5055464'),
('+919660634361', 'SSF5187139'),
('+919950091784', 'SSF5205045'),
('+919466095889', 'SSF3832693'),
('+919301410296', 'SSF5163663'),
('+919352805804', 'SSF5196948'),
('+919054967300', 'SSF5196913'),
('+919680508050', 'SSF3623585'),
('+919929734079', 'SSF2578322'),
('+919509807406', 'SSF5099809'),
('+919494946464', 'SSF3607353'),
('+919216809740', 'SSF5216765'),
('+919784170891', 'SSF3485150'),
('+919632536164', 'SSF3661142'),
('+919446985768', 'SSF2563989'),
('+919352336258', 'SSF3367317'),
('+918953673125', 'SSF5805028'),
('+919120285081', 'SSF5996025'),
('+917050586800', 'SSF5859647'),
('+919670579293', 'SSF5246545'),
('+916824488888', 'SSF3677232'),
('+917357414042', 'SSF3801086'),
('+917891490350', 'SSF3760745'),
('+918890141174', 'SSF3638914'),
('+918770982574', 'SSF3614404'),
('+918174875390', 'SID951374859454'),
('+919163458764', 'SSF3362655'),
('+919464649401', 'SSF3664874'),
('+919866868875', 'SSF3454372'),
('+919399194123', 'SSF3682960'),
('+919414432820', 'SSF3487192'),
('+919588918375', 'SSF4840044'),
('+917060214595', 'SSF5044065'),
('+918464349443', 'SSF2739845'),
('+919334325908', 'SSF2549831'),
('+919057220815', 'SID951375925128'),
('+919955625782', 'SSF3463779'),
('+919934552822', 'SSF2891763'),
('+917503940808', 'SSF4681834'),
('+917070330086', 'SSF4128175'),
('+916287907842', 'SID951373277405'),
('+917667103352', 'SSF2665985'),
('+917091058251', 'SID951376094750'),
('+919794905981', 'SSF2347259'),
('+919335349688', 'SSF2864578'),
('+919977658419', 'SSF2961216'),
('+916201838778', 'SSF5926266'),
('+916379600349', 'SSF5869965'),
('+916388186573', 'SSF4136270'),
('+916200821852', 'SSF5940567'),
('+916287702214', 'SSF3377490'),
('+917320990955', 'SSF5826091'),
('+917065100735', 'SSF3714031'),
('+917999150297', 'SSF6009425'),
('+917782095864', 'SSF5879350'),
('+917050246627', 'SSF5886928'),
('+917076242704', 'SSF5853589'),
('+917879890388', 'SSF5845119'),
('+917999765227', 'SSF3202495'),
('+917070351424', 'SSF6340966'),
('+917405713283', 'SSF2367268'),
('+917509920236', 'SSF3514729'),
('+918149652614', 'SSF5827194'),
('+918210644762', 'SSF5840386'),
('+918434864163', 'SSF5329608'),
('+918969493970', 'SSF5327108'),
('+918815489682', 'SSF4092197'),
('+918603949965', 'SSF5864348'),
('+918603141366', 'SSF5936202'),
('+918327785738', 'SSF3671915'),
('+918857891708', 'SSF5881936'),
('+919329879927', 'SSF4022120'),
('+919302701778', 'SSF5937135'),
('+919877714361', 'SSF2983740'),
('+919547995152', 'SSF2802902'),
('+919608816428', 'SSF5968762'),
('+919508529138', 'SSF5874436'),
('+919905363499', 'SSF5853646'),
('+919685421824', 'SSF6219414'),
('+919616561431', 'SSF5860131'),
('+919310970226', 'SSF5842785'),
('+919939819844', 'SSF5805438'),
('+919981281600', 'SSF6258220'),
('+919241029677', 'SSF5934346'),
('+919329562137', 'SSF5784507'),
('+919199862650', 'SSF5766397'),
('+919060450974', 'SSF5743207'),
('+919507187632', 'SSF5924677'),
('+919406057292', 'SSF4016772'),
('+919171693821', 'SSF5787255'),
('+919302515241', 'SSF5926412'),
('+919155927078', 'SSF5704979'),
('+919102547640', 'SSF5887278'),
('+919301454145', 'SSF6002943'),
('+916204426673', 'SID951375641710'),
('+917352972511', 'SID951374367937'),
('+917905055620', 'SSF6148954'),
('+917324918559', 'SID951376174105'),
('+917999134476', 'SSF2306609'),
('+918789348107', 'SSF2915045'),
('+919257662485', 'SSF2567995'),
('+916267820577', 'SSF4445730'),
('+916204357107', 'SSF5788499'),
('+916260595509', 'SSF3307384'),
('+916287118377', 'SSF5552653'),
('+916287373066', 'SSF5621506'),
('+916289079923', 'SSF5556916'),
('+916200098113', 'SSF5614197'),
('+916383947315', 'SSF5773021'),
('+916205614635', 'SSF5592313'),
('+916203736143', 'SSF3558919'),
('+916389574541', 'SSF5593577'),
('+916268891569', 'SSF3604376'),
('+916202808566', 'SSF6029882'),
('+916290588982', 'SSF5741935'),
('+917725876113', 'SSF5705330'),
('+917370053883', 'SSF5638360'),
('+917004417577', 'SSF2550026'),
('+917061335615', 'SSF5830353'),
('+917869528425', 'SSF4194793'),
('+917970494761', 'SSF5657668'),
('+917667462545', 'SSF5829844'),
('+917384010081', 'SSF3026578'),
('+917857886401', 'SSF3026577'),
('+917706943399', 'SSF2538204'),
('+917292969834', 'SSF5611334'),
('+917763937158', 'SSF3294276'),
('+917542987033', 'SSF5815982'),
('+917024010726', 'SSF6564574'),
('+917324875289', 'SSF5642924'),
('+917033528878', 'SSF5727988'),
('+917050608344', 'SSF5716023'),
('+917004242243', 'SSF5656661'),
('+917782852774', 'SSF5585640'),
('+917634991451', 'SSF5761806'),
('+917856820965', 'SSF5774482'),
('+917033808933', 'SSF5536322'),
('+917225069973', 'SSF4317895'),
('+917762997459', 'SSF5655063'),
('+917999395648', 'SSF3803214'),
('+917765017543', 'SSF5863453'),
('+917696542655', 'SSF2561413'),
('+917044466463', 'SSF5561261'),
('+917061221994', 'SSF5665353'),
('+917739952047', 'SSF5573695'),
('+917657897386', 'SSF5611654'),
('+917564025248', 'SSF3352008'),
('+917858965930', 'SSF4198392'),
('+917050831334', 'SSF5668177'),
('+917762046170', 'SSF5650655'),
('+917368840628', 'SSF5632280'),
('+917070510027', 'SSF5886067'),
('+917828556391', 'SSF5564837'),
('+917870047941', 'SSF3236231'),
('+917632984991', 'SSF5718596'),
('+918210521199', 'SSF2968441'),
('+918839656518', 'SSF5687329'),
('+918298334324', 'SSF5789472'),
('+918177966269', 'SSF5736022'),
('+918092892719', 'SSF5580971'),
('+918438195597', 'SSF5443409'),
('+918757330083', 'SSF5800009'),
('+918271698635', 'SSF6546340'),
('+918986342663', 'SSF5713288'),
('+918409438313', 'SSF5697940'),
('+918810560189', 'SSF5650225'),
('+918235185234', 'SSF5551609'),
('+918084481362', 'SSF5622484'),
('+918127337363', 'SSF5608997'),
('+918817640825', 'SSF6534653'),
('+918966999571', 'SSF5753367'),
('+918252162332', 'SSF5818547'),
('+918002279075', 'SSF5640188'),
('+918603420947', 'SSF5630267'),
('+918252636033', 'SSF5644570'),
('+918770123219', 'SSF5242559'),
('+918797012454', 'SSF5677183'),
('+919110146421', 'SSF5548441'),
('+919279086611', 'SSF5539231'),
('+919783230642', 'SSF5724077'),
('+919934441531', 'SSF5897048'),
('+919905119020', 'SSF5648519'),
('+919546509190', 'SSF5828919'),
('+919264415600', 'SSF3189695'),
('+919065283057', 'SSF5712976'),
('+919382295928', 'SSF3972250'),
('+919835833931', 'SSF5545149'),
('+919939644809', 'SSF3460238'),
('+919241026995', 'SSF3770533'),
('+919098690098', 'SSF5645801'),
('+919861387693', 'SSF5722535'),
('+919562397696', 'SSF5620916'),
('+919661528764', 'SSF5939766'),
('+919244876387', 'SSF6564655'),
('+919162352339', 'SSF5730402'),
('+919801578029', 'SSF5691785'),
('+919711557693', 'SSF5727977'),
('+919403659832', 'SSF3527327'),
('+919635328140', 'SSF5196322'),
('+919507892632', 'SSF5574586'),
('+919229155855', 'SSF5485504'),
('+919098955859', 'SSF3704351'),
('+919905838039', 'SSF3628530'),
('+919801915230', 'SSF5637400'),
('+919835997065', 'SSF5619552'),
('+919060174288', 'SSF5579444'),
('+919693304743', 'SSF5619852'),
('+919234907318', 'SSF5494529'),
('+919241263825', 'SSF5733637'),
('+919572921117', 'SSF5607795'),
('+919162045752', 'SSF5505838'),
('+919241455038', 'SSF5647068'),
('+919262634292', 'SSF5817894'),
('+919199714466', 'SSF5713377'),
('+919340429524', 'SSF6569782'),
('+919279165893', 'SSF5720533'),
('+919065347419', 'SSF5331113'),
('+919691487169', 'SSF4096502'),
('+919602714615', 'SSF5853280'),
('+916390992941', 'SSF6252644'),
('+916307289803', 'SSF6111896'),
('+917464904757', 'SSF6304390'),
('+917856821573', 'SSF6257802'),
('+918252679745', 'SSF5938384'),
('+918090680958', 'SSF6287294'),
('+919044058935', 'SSF6286269'),
('+919162079817', 'SSF6060229'),
('+919523327928', 'SSF6195200'),
('+917070921567', 'SSF5638381'),
('+918084655126', 'SSF5782667'),
('+919507165721', 'SSF3848920'),
('+917739718427', 'SID951374976353'),
('+916299766759', 'SSF2786365'),
('+916375342820', 'SSF5790013'),
('+916355622781', 'SSF5574704'),
('+916203734095', 'SSF5310583'),
('+917320830335', 'SSF5343464'),
('+917364806867', 'SSF5349870'),
('+917050091150', 'SSF5411361'),
('+917879442061', 'SSF5646815'),
('+917067101022', 'SSF5328138'),
('+918707403924', 'SSF5453129'),
('+918209220402', 'SSF2546591'),
('+918294129753', 'SID951375794739'),
('+918468862104', 'SSF5418562'),
('+918306346836', 'SSF5468154'),
('+919352341744', 'SSF5465276'),
('+919161088070', 'SSF5486837'),
('+919279981514', 'SID951374279505'),
('+919653864872', 'SSF5385320'),
('+919244861718', 'SSF5342584'),
('+916386640357', 'SSF5918309'),
('+916287720895', 'SSF5734008'),
('+916205863351', 'SID951374404492'),
('+916261834804', 'SSF5727692'),
('+917879474324', 'SSF3403133'),
('+917294123545', 'SSF5818437'),
('+917765888163', 'SSF3152474'),
('+917859061386', 'SSF3926732'),
('+917352995558', 'SSF4763946'),
('+917765970291', 'SSF3678915'),
('+917645053236', 'SSF5202434'),
('+917050069590', 'SSF5326093'),
('+917837464687', 'SSF5216208'),
('+918305893104', 'SSF3293635'),
('+918340316328', 'SSF5796379'),
('+918521812960', 'SSF6445863'),
('+918579973490', 'SSF5732872'),
('+918084508443', 'SSF2329153'),
('+918603565626', 'SSF5801840'),
('+918292403359', 'SID951375632630'),
('+918434592125', 'SSF2679778'),
('+919661844668', 'SSF5746222'),
('+919329199216', 'SSF5512982'),
('+919631529774', 'SID951373237908'),
('+919608915349', 'SSF5921679'),
('+919918504791', 'SSF3296450'),
('+919006103935', 'SSF3636440'),
('+919199515748', 'SSF5350591'),
('+919354336018', 'SSF2770088'),
('+919755002287', 'SSF5190343'),
('+919334616512', 'SSF5166646'),
('+919234852792', 'SSF5906827'),
('+919652437039', 'SSF5951623'),
('+919771547953', 'SSF5686612'),
('+919931279383', 'SSF5211780'),
('+919162068210', 'SSF5769662'),
('+918294790010', 'SSF5558910'),
('+919709556807', 'SSF6004666'),
('+917033789615', 'SSF6293076'),
('+918757579552', 'SSF6287210'),
('+918409197731', 'SSF4794810'),
('+918296558742', 'SSF5058286'),
('+917988420824', 'SSF5515874'),
('+918271864704', 'SSF6212666'),
('+918051247142', 'SSF6176963'),
('+918676005657', 'SSF6264751'),
('+919150160015', 'SSF5773030'),
('+919263602929', 'SSF6177100'),
('+918839375641', 'SID2125277507'),
('+919329861448', 'CID090306533'),
('+918676016765', 'SSF6175999'),
('+916261960004', 'SSF4927193'),
('+916260558300', 'SSF4818607'),
('+916207192994', 'SSF4714241'),
('+916266277268', 'SSF4766606'),
('+916207758359', 'SID951376163704'),
('+916267901785', 'SSF4371783'),
('+916209159164', 'SSF2891204'),
('+917440792787', 'SSF2424348'),
('+917494057985', 'SSF5235433'),
('+917000909154', 'SSF4782576'),
('+917321040146', 'SSF6308069'),
('+917808579868', 'SSF6281232'),
('+917067168832', 'SSF2891124'),
('+917987725287', 'SSF3614384'),
('+917742395978', 'SSF4972051'),
('+917909603779', 'SSF4743538'),
('+917061667991', 'SSF4748831'),
('+917007858156', 'SSF2951990'),
('+918306760318', 'SSF2417312'),
('+918817339923', 'SSF3469543'),
('+918252693680', 'SSF5242574'),
('+918340728356', 'SSF5072987'),
('+918603751060', 'SSF4837019'),
('+918271887040', 'SSF4785492'),
('+918567658958', 'SID951373490111'),
('+918757129737', 'SSF5257546'),
('+918504811624', 'SID951374389187'),
('+918102429158', 'SSF6283071'),
('+918271214926', 'SSF5261992'),
('+918340526776', 'SSF3042675'),
('+918252200676', 'SSF2526542'),
('+918797608749', 'SSF4795084'),
('+918873354268', 'SSF4773700'),
('+918292321124', 'SSF6260881'),
('+918409460115', 'SSF4744604'),
('+918210128695', 'SSF3655444'),
('+919263989264', 'SSF3302319'),
('+919972905641', 'SSF4775312'),
('+919508033353', 'SSF5050228'),
('+919783384103', 'SSF5067603'),
('+919358232855', 'SSF4771904'),
('+919407674001', 'SSF4942731'),
('+919993901706', 'SSF3714512'),
('+919162603022', 'SSF2354638'),
('+919079156139', 'SSF3029766'),
('+919135338446', 'SSF4732649'),
('+919785693124', 'SSF4937847'),
('+919571142952', 'SSF4914518'),
('+919065014793', 'SSF4714070'),
('+919918230974', 'SSF6317360'),
('+919918427622', 'SSF6317380'),
('+919516021569', 'SSF4568338'),
('+919977716944', 'SSF3622804'),
('+919523265477', 'SSF4751353'),
('+919279363918', 'SSF4755503'),
('+919109820147', 'SID951375593516'),
('+919131863787', 'SID951374948404'),
('+919399874617', 'SSF4935922'),
('+919341306130', 'SSF4689770'),
('+919797967686', 'SID951374828539'),
('+919630152509', 'SSF2699486'),
('+919977473653', 'SSF4452701'),
('+919658682849', 'SSF2725493'),
('+917070037457', 'SSF5855011'),
('+918271540904', 'SSF5546886'),
('+919709579436', 'SSF5166110'),
('+919012670098', 'SSF4561935'),
('+916264819978', 'SSF3747494'),
('+916260484783', 'SSF5000744'),
('+916350463097', 'SSF5158474'),
('+916260538379', 'SSF4408408'),
('+916266451601', 'SSF6066743'),
('+916287588678', 'SSF4876928'),
('+916388932372', 'SSF5042019'),
('+917746885157', 'SSF4563075'),
('+917739649493', 'SSF6191293'),
('+917737467263', 'SSF5146156'),
('+917737649368', 'SSF5132850'),
('+917367909588', 'SSF4584122'),
('+917087315514', 'SSF4894204'),
('+917544835711', 'SSF6178873'),
('+917259001618', 'SSF2846435'),
('+917488670450', 'SSF6205813'),
('+917324877583', 'SSF6174346'),
('+917260049764', 'SSF3053631'),
('+917368916359', 'SSF6199628'),
('+917970733406', 'SSF4015682'),
('+917389122410', 'SSF5038909'),
('+918696314743', 'SSF4706169'),
('+918503855264', 'SSF5005629'),
('+918294593512', 'SSF4648809'),
('+918287928297', 'SSF6199226'),
('+918815646741', 'SSF4905891'),
('+918092379372', 'SSF4603093'),
('+918058521040', 'SSF4468848'),
('+918290313587', 'SSF4370533'),
('+918291871543', 'SSF4658385'),
('+918084432763', 'SSF4563388'),
('+918209078125', 'SSF5285801'),
('+918228996867', 'SSF6175164'),
('+918078688060', 'SSF5024638'),
('+918651644036', 'SSF4517017'),
('+918227913378', 'SSF4577129'),
('+918235573437', 'SSF5078942'),
('+918863965369', 'SSF3338233'),
('+918264944776', 'SSF5049476'),
('+918571070138', 'SSF3236445'),
('+918298438669', 'SSF4666562'),
('+918209250363', 'SSF4580968'),
('+918825186138', 'SSF4199439'),
('+919931683536', 'SSF4648765'),
('+919799126841', 'SSF3234398'),
('+919098747539', 'SSF4016982'),
('+919588898227', 'SID951375723786'),
('+919257274599', 'SSF4485225'),
('+919602639766', 'SSF5228749'),
('+919838424024', 'SID951375829001'),
('+919576132257', 'SSF4569396'),
('+919973169798', 'SSF4549143'),
('+919608327869', 'SSF3138496'),
('+919166994587', 'SSF5122195'),
('+919663557885', 'SID951375427550'),
('+919756034128', 'SSF6191515'),
('+919693929582', 'SSF4462402'),
('+919006253283', 'SSF4413902'),
('+919521515339', 'SSF4565416'),
('+919065816114', 'SSF4922746'),
('+919983646701', 'SSF4400361'),
('+919650897161', 'SSF4519222'),
('+919669357638', 'SSF4530279'),
('+919153623549', 'SSF4567476'),
('+919279066155', 'SSF4520836'),
('+919006702684', 'SSF4596087'),
('+919066316846', 'SSF4584862'),
('+919737694949', 'SID951375951099'),
('+919301274399', 'SSF4999990'),
('+919329493408', 'SSF5022800'),
('+917563934740', 'SSF5871568'),
('+917761823568', 'SSF6294045'),
('+917543052410', 'SSF5712106'),
('+917004910200', 'SSF5718484'),
('+918987889724', 'SSF5702278'),
('+919693692732', 'SSF6085842'),
('+919908513316', 'SID2125042350'),
('+916265911323', 'SSF4380139'),
('+917632893413', 'SSF4374933'),
('+918764946494', 'SSF3195398'),
('+918235515675', 'SSF4360257'),
('+918235694851', 'SID951376094886'),
('+917762919272', 'SSF4256689'),
('+916206953973', 'SSF4239777'),
('+916287021569', 'SSF4682799'),
('+916386327620', 'SSF5517169'),
('+916377169576', 'SSF4207241'),
('+916200313464', 'SSF4342578'),
('+916290846788', 'SID951375661660'),
('+916263904485', 'SSF4517121'),
('+916367926401', 'SSF4221089'),
('+916239100670', 'SSF4209688'),
('+916350142732', 'SSF4216865'),
('+917665074545', 'SSF4645981'),
('+917023376015', 'SSF3693799'),
('+917070656480', 'SSF4430606'),
('+917061256102', 'SSF4208282'),
('+917263013826', 'SSF5864719'),
('+917976196994', 'SSF4136783'),
('+917568265486', 'SSF3655108'),
('+917771897853', 'SSF3542331'),
('+918079065849', 'SSF4203632'),
('+918128584906', 'SSF4639752'),
('+918078696684', 'SID951375064170'),
('+918889927869', 'SSF4521990'),
('+918233719628', 'SSF4323709'),
('+918690800623', 'SSF4351685'),
('+918521512764', 'SSF4214596'),
('+918084721475', 'SID951372855090'),
('+918529283459', 'SSF4410122'),
('+918565745654', 'SSF3631051'),
('+918829979618', 'SSF4063959'),
('+918875064785', 'SSF4146158'),
('+918107010886', 'SSF4221126'),
('+918003551020', 'SSF4377987'),
('+918521489307', 'SSF4328962'),
('+918955364875', 'SSF3657705'),
('+919024984324', 'SSF4350469'),
('+919636488094', 'SSF4592912'),
('+919784707269', 'SSF2763686'),
('+919631578885', 'SSF4383410'),
('+919798424104', 'SSF3518639'),
('+919587737495', 'SSF4075766'),
('+919098475310', 'SSF4178028'),
('+919244127956', 'SSF4558092'),
('+919303033018', 'SSF4552637'),
('+919216718246', 'SSF4641671'),
('+919304835493', 'SSF3121723'),
('+919009382015', 'SSF4470992'),
('+919813752964', 'SSF2651136'),
('+919263458505', 'SSF4111064'),
('+919929184858', 'SSF4207436'),
('+919877348071', 'SSF4209657'),
('+919694192779', 'SSF4111957'),
('+919009269161', 'SSF5903538'),
('+919506488526', 'SSF3559813'),
('+919826586467', 'SSF3655104'),
('+919549164501', 'SSF2597473'),
('+916261269955', 'SSF3443134'),
('+916264816436', 'SSF4060614'),
('+917665436238', 'SSF4167576'),
('+917426948031', 'SSF4020606'),
('+917073584797', 'SSF4010752'),
('+917568047508', 'SSF4010824'),
('+917734060353', 'SSF4151965'),
('+917023096466', 'SSF3977011'),
('+917728940648', 'SSF3985034'),
('+917319725826', 'SSF3828347'),
('+917339968195', 'SSF4484205'),
('+918769852377', 'SSF4020569'),
('+918690217639', 'SSF3169036'),
('+918947025359', 'SSF3098255'),
('+918829926446', 'SSF4196000'),
('+918875918554', 'SSF4047633'),
('+918905648550', 'SSF4093103'),
('+918209852016', 'SSF3933250'),
('+918290500665', 'SSF4056872'),
('+918385829299', 'SSF4078962'),
('+918955524252', 'SSF4089911'),
('+918827360271', 'SID951375349574'),
('+919509701007', 'SSF3249164'),
('+919320662265', 'SSF5606924'),
('+919602749950', 'SSF4040204'),
('+919263248584', 'SSF3950393'),
('+919610023343', 'SSF3933451'),
('+919929235531', 'SSF4059538'),
('+916377742045', 'SSF5320193'),
('+916448644864', 'SSF3737743'),
('+916267924189', 'SSF4041324'),
('+916930555555', 'SSF3692438'),
('+917340591980', 'SSF3919927'),
('+917742418195', 'SSF4264128'),
('+917665476643', 'SSF3124114'),
('+917024643091', 'SSF4004036'),
('+918890921950', 'SSF4023251'),
('+918631645445', 'SSF3305317'),
('+918949312302', 'SSF3892765'),
('+918969663747', 'SSF3128839'),
('+918349554943', 'SSF3725517'),
('+918890259897', 'SSF5333136'),
('+918890880092', 'SSF3933523'),
('+918890359237', 'SSF2510335'),
('+918934248794', 'SSF3544669'),
('+918769825803', 'SSF3890555'),
('+919352590902', 'SSF4084986'),
('+919983783145', 'SSF2575150'),
('+919145876156', 'SSF3886761'),
('+919358511360', 'SSF2551285'),
('+919636577998', 'SSF3829557'),
('+919571130455', 'SSF5333590'),
('+919587311653', 'SSF5376345'),
('+919509000931', 'SSF4286825'),
('+919668575555', 'SSF2554377'),
('+919827801216', 'SSF4046076'),
('+919911960927', 'SSF5512583'),
('+916205960067', 'SSF4552078'),
('+916376180648', 'SSF5082730'),
('+916375761293', 'SSF5317603'),
('+916378158588', 'SSF5197370'),
('+916377244056', 'SSF5094589'),
('+916350634920', 'SSF5163643'),
('+916367911007', 'SSF5186936'),
('+916890527535', 'SSF3606492'),
('+917878511607', 'SSF5196897'),
('+917426913848', 'SSF5187014'),
('+917742013159', 'SSF5205230'),
('+917891062415', 'SID951376109483'),
('+917878902290', 'SSF5216733'),
('+917976515891', 'SSF2877353'),
('+918306892660', 'SSF3671961'),
('+918209056778', 'SSF5088208'),
('+918003363275', 'SSF5094285'),
('+918905905731', 'SSF5107183'),
('+918233091772', 'SSF5267050'),
('+918003227337', 'SSF4419129'),
('+919775110910', 'SSF3795837'),
('+919024169063', 'SSF5159542'),
('+919216601157', 'SSF5152773'),
('+919636846232', 'SSF5085530'),
('+919350203158', 'SID951375895576'),
('+919079237773', 'SSF5205164'),
('+919257347264', 'SSF5027273'),
('+919799656078', 'SSF5187030'),
('+919166963120', 'SSF5094183'),
('+919462934309', 'SSF5186973'),
('+919352404091', 'SSF5196961'),
('+919982501834', 'SSF5196868'),
('+919166309118', 'SSF5197495'),
('+919256254488', 'SSF5205322'),
('+919687548484', 'SSF3658948'),
('+919356855876', 'SSF3581384'),
('+919887869261', 'SSF5273872'),
('+919828632369', 'SSF5264474'),
('+919842197648', 'SSF3892273'),
('+916267545495', 'SSF3288715'),
('+916595959599', 'SSF3716922'),
('+916565959565', 'SSF3718516'),
('+916350643494', 'SSF2682465'),
('+917023765568', 'SSF3788276'),
('+917851875750', 'SSF4891396'),
('+918254555555', 'SSF3434020'),
('+918930381352', 'SSF3321617'),
('+918306029823', 'SSF3810949'),
('+918085585758', 'SSF3677251'),
('+918558888854', 'SSF3678077'),
('+918000943069', 'SSF3769356'),
('+918559959124', 'SSF3358721'),
('+919654852456', 'SSF3591359'),
('+919642543887', 'SSF3233233'),
('+919734644346', 'SSF2633922'),
('+919785145315', 'SSF3760961'),
('+919667320302', 'SSF4839875'),
('+917543886907', 'SSF4712319'),
('+917487845556', 'SSF2749746'),
('+918855860191', 'SSF4794510'),
('+919430584980', 'SSF2885228'),
('+919523972439', 'SID951375976794'),
('+919955263584', 'SSF3373465'),
('+919887088253', 'SSF3402739'),
('+917049396682', 'SSF2952834'),
('+916268012397', 'SSF5927978'),
('+917566080951', 'SSF5692270'),
('+917828388516', 'SSF6079433'),
('+917415076722', 'SSF5993570'),
('+917775958739', 'SSF5871564'),
('+917803962274', 'SSF3066428'),
('+918602864922', 'SSF5503823'),
('+918269614768', 'SSF5736410'),
('+918964952973', 'SSF3507820'),
('+919644350286', 'SSF5824012'),
('+919098032256', 'SSF3590655'),
('+919685608136', 'SSF5805226'),
('+919512472982', 'SSF3277859'),
('+918511004935', 'SSF3657860'),
('+919340319946', 'SSF3548456'),
('+918720806689', 'SSF3039884'),
('+919399335472', 'SSF3528986'),
('+919155830184', 'SSF3316289'),
('+917646907249', 'SID951375058329'),
('+918770497713', 'SID951375037070'),
('+917067508103', 'SSF3550665'),
('+917000702205', 'SSF3136805'),
('+919834152623', 'SSF5320278'),
('+916262445029', 'SSF3459185'),
('+918577839915', 'SSF4286490'),
('+918957687391', 'SSF6262122'),
('+919630313055', 'SID951373412579'),
('+917525827100', 'SSF2469630'),
('+919506267087', 'SSF3764320'),
('+918797512227', 'SSF6065434'),
('+918319581577', 'SSF4136238'),
('+916556886956', 'SID951373505531'),
('+917974186248', 'SSF3525035'),
('+918959797732', 'CID140901748'),
('+918738649457', 'SID951375488514'),
('+919199629786', 'SSF2504001'),
('+918817601953', 'SSF4237901'),
('+917281874074', 'SSF5010450'),
('+919576119081', 'SSF4647037'),
('+916200311934', 'SSF4733999'),
('+918917858618', 'SSF4991111'),
('+917049540005', 'SSF3410311'),
('+919724136760', 'SID951374641633'),
('+919545389889', 'SID951373456953'),
('+919236672115', 'SSF4206058'),
('+919399565138', 'SSF4228535'),
('+917061689344', 'SSF5033609'),
('+919931368455', 'SSF5016534'),
('+919162310701', 'SID951375236778'),
('+919649212470', 'SID951376045126'),
('+919636200651', 'SSF2743583'),
('+919644299530', 'SSF3740815'),
('+919111205094', 'SID2125606194'),
('+917724090039', 'SSF3563336'),
('+919171308804', 'SID951375110030'),
('+919589539243', 'CID135602694'),
('+916262786251', 'SSF3824631'),
('+919171997214', 'SSF2328940'),
('+919729191295', 'SSF2865721'),
('+917700811783', 'SSF3766665'),
('+918770431691', 'SSF3813963'),
('+916266598091', 'SID2125478292'),
('+919344964770', 'SSF4231742'),
('+917258992645', 'SID951373309392'),
('+918815164499', 'SSF2962499'),
('+916387584994', 'SSF2581334'),
('+917023238657', 'SSF3579137'),
('+918400426345', 'SSF4805680'),
('+916205372616', 'SID951373561319'),
('+919934212967', 'SSF4953691'),
('+916299470795', 'SSF3306260'),
('+918540082033', 'SID951375195180'),
('+919026584276', 'SID951373674468'),
('+918827166160', 'SID951373689482'),
('+916209822419', 'SSF5275477'),
('+917557790311', 'SSF6161547'),
('+917354354922', 'SID951372976753'),
('+919608575952', 'SSF2964214'),
('+919691756581', 'CID128806963'),
('+916264004489', 'SSF3266206'),
('+917903582551', 'SID951374297427'),
('+919993501064', 'SSF3998999'),
('+919479704970', 'SID951373282574'),
('+916267577446', 'SID951373556788'),
('+919931788213', 'SSF4117798'),
('+916200744984', 'SSF2609278'),
('+917748822522', 'SID2125071524'),
('+917024203753', 'CID052902209'),
('+916203483140', 'SID951373613267'),
('+918294829446', 'SSF3639073'),
('+918002339995', 'SID951374565897'),
('+916268505988', 'SSF4317930'),
('+919905756319', 'SSF2327669'),
('+918404917189', 'SSF2885706'),
('+916204578464', 'SID951375029121'),
('+918085732369', 'SSF2457926'),
('+918797266972', 'SSF2508535'),
('+917389829193', 'SID951374673150'),
('+919871793833', 'SID951376153449'),
('+918766434549', 'SID951375998951'),
('+918757367592', 'SID951376099947'),
('+917426078130', 'SSF3604400'),
('+917068915162', 'SSF5517414'),
('+919555917898', 'SSF5583020'),
('+919691474344', 'SID2125747053'),
('+919602727445', 'SSF3890825'),
('+918839181249', 'SID951376175912'),
('+917091628955', 'SSF2741780'),
('+919031761251', 'SSF3699089'),
('+918115390616', 'SSF5669385'),
('+919644742707', 'CID048005976'),
('+916201722376', 'SSF4659436'),
('+919165486412', 'SID951375921902'),
('+918965094603', 'SSF3387256'),
('+919376497160', 'SSF5942602'),
('+918815354203', 'SSF3159201'),
('+918271421998', 'SSF2554693'),
('+918235571554', 'SID951374988502'),
('+918120281943', 'SID951374956795'),
('+918581983095', 'SID951375259532'),
('+919825658780', 'SSF2832377'),
('+919838478414', 'SSF3705541'),
('+919793256066', 'SID951376167069'),
('+917352461697', 'SSF4604207'),
('+919340979642', 'SID951375302040'),
('+918352975607', 'SSF2839843'),
('+919302542660', 'SSF2781989'),
('+919651600436', 'SSF4948149'),
('+917518063068', 'SID951375041959'),
('+919983034879', 'SSF3077186'),
('+917037513503', 'SSF5450408'),
('+919693212312', 'SSF2902684'),
('+919329659261', 'SSF3475233'),
('+916265813704', 'SID951373023901'),
('+917859045634', 'SID951374501504'),
('+917783078721', 'SID951375944048'),
('+916391418915', 'SSF2967780'),
('+917762890824', 'SSF2396582'),
('+917870756285', 'SSF2314495'),
('+917488427024', 'SSF2950329'),
('+918252107420', 'SSF2473401'),
('+918891541461', 'SSF2944376'),
('+919905625051', 'SSF2540726'),
('+919508602678', 'SSF2635919'),
('+916267538477', 'SSF5804626'),
('+916207223271', 'SSF6123534'),
('+916201779061', 'SSF2995302'),
('+916398167068', 'SSF3654152'),
('+916206867172', 'SSF6065745'),
('+916260051781', 'SSF6087092'),
('+916203133007', 'SSF5839166'),
('+916386670477', 'SSF6139693'),
('+916262915351', 'SSF5830823'),
('+916261344090', 'SSF5720375'),
('+916206791279', 'SSF6061208'),
('+917767092237', 'SSF3850825'),
('+917070344556', 'SSF6074860'),
('+917528809168', 'SSF6124261'),
('+917296009962', 'SSF5998098'),
('+917645872341', 'SSF2996119'),
('+917724059619', 'SSF4042852'),
('+917870904816', 'SSF6109924'),
('+917488023808', 'SSF5816156'),
('+917880710056', 'SSF6082103'),
('+917857823761', 'SSF5886437'),
('+917257049112', 'SSF6069234'),
('+917898485781', 'SSF6034354'),
('+917080758439', 'SSF3994715'),
('+917379453226', 'SSF6102654'),
('+917600970394', 'SSF3534399'),
('+917380556620', 'SSF3816984'),
('+918269904500', 'SSF6117047'),
('+918728846934', 'SSF3638613'),
('+918235127503', 'SSF6092821'),
('+918002727425', 'SSF6078962'),
('+918102742630', 'SSF5723295'),
('+918810642258', 'SSF6090086'),
('+918601584719', 'SSF6015491'),
('+918235136599', 'SSF6102185'),
('+918080673062', 'SSF4080091'),
('+918815954015', 'SSF3780362'),
('+918797642627', 'SSF6142941'),
('+918503918049', 'SSF3816433'),
('+918307994322', 'SSF5667559'),
('+918084267677', 'SSF5652036'),
('+918271334107', 'SSF2646915'),
('+918092630348', 'SSF6029565'),
('+919329156840', 'SSF3291804'),
('+919170813718', 'SSF6088681'),
('+919303621031', 'SSF5089994'),
('+919855363286', 'SSF6078230'),
('+919229099297', 'SSF5880629'),
('+919128242764', 'SSF6105594'),
('+919508274137', 'SSF6043914'),
('+919341120962', 'SSF5933817'),
('+919329051656', 'SSF3523577'),
('+919303784431', 'SSF6052195'),
('+919334473345', 'SSF6067464'),
('+919838925084', 'SSF6066148'),
('+919931206644', 'SSF4393071'),
('+919508365702', 'SSF6146842'),
('+919263056209', 'SSF6105120'),
('+919006675451', 'SSF6093303'),
('+919835474527', 'SSF6117524'),
('+919235492108', 'SSF5822063'),
('+919956962847', 'SSF3633646'),
('+919503726996', 'SSF6188896'),
('+919199716278', 'SSF6032608'),
('+919257638959', 'SSF3848362'),
('+919588451618', 'SSF6030153'),
('+917004062636', 'SID951374192339'),
('+917987184939', 'SID951375187365'),
('+916200527587', 'SSF5717227'),
('+916207431877', 'SSF3900695'),
('+917004999459', 'SSF3910247'),
('+917367034175', 'SSF6000140'),
('+917463096136', 'SSF3408642'),
('+917501540538', 'SSF5998879'),
('+918319440620', 'SSF6082437'),
('+918085575506', 'SSF6137535'),
('+919934585037', 'SSF5848954'),
('+919798196923', 'SSF4386030'),
('+919905330491', 'SSF5911152'),
('+919905557361', 'SSF6052531'),
('+919110892516', 'SSF6139281'),
('+917258984750', 'SSF6169913'),
('+917209532154', 'SSF6118720'),
('+919693758344', 'SSF6195699'),
('+919199038641', 'SSF6322040'),
('+919905992649', 'SSF6130003'),
('+917739039986', 'SSF6166709'),
('+918235627780', 'SSF5484437'),
('+918873946192', 'SSF5638488'),
('+918826638718', 'SSF6069684'),
('+918294584586', 'SSF6047286'),
('+919263019229', 'SSF6015991'),
('+919122478705', 'SSF6171405'),
('+916299287004', 'SSF4629232'),
('+917091299511', 'SSF6128821'),
('+917050512768', 'SSF5865237'),
('+917654171675', 'SSF6249078'),
('+918726329539', 'SSF6184381'),
('+918847693224', 'SSF5833948'),
('+918303888701', 'SSF6020849'),
('+918936012579', 'SSF5567688'),
('+918252575990', 'SSF4855283'),
('+918757397871', 'SSF5909341'),
('+918340117750', 'SSF5756822'),
('+919140114632', 'SSF6144296'),
('+919973002040', 'SSF5885624'),
('+917485003225', 'SID951374883548'),
('+919608433039', 'SID951375082391'),
('+919687678990', 'SID951374736224'),
('+917209395065', 'SSF2829616'),
('+917462983446', 'SSF2894996'),
('+916230154634', 'SSF5843573'),
('+916391922655', 'SSF5897316'),
('+916201988302', 'SSF5862202'),
('+916202882652', 'SSF5917974'),
('+916264977675', 'SSF5839189'),
('+917542986017', 'SSF5941952'),
('+917739761542', 'SSF5830217'),
('+917000393410', 'SSF5940414'),
('+917209729932', 'SSF5878572'),
('+917903420371', 'SSF5700440'),
('+917693048437', 'SSF3474822'),
('+917700803438', 'SSF5700229'),
('+917070722535', 'SSF5716024'),
('+917255034996', 'SSF5823010'),
('+917209748319', 'SSF5795501'),
('+917033782731', 'SSF5768772'),
('+917987767424', 'SSF5889556'),
('+917999482085', 'SSF5838059'),
('+917389466733', 'SSF5889712'),
('+917067979705', 'SID2125708922'),
('+918511342030', 'SSF5870544'),
('+918434670622', 'SSF5738920'),
('+918969542808', 'SSF2885113'),
('+918462903135', 'SSF5754193'),
('+918102984668', 'SSF5693429'),
('+918235846886', 'SSF5700230'),
('+918273569818', 'SSF5756059'),
('+918294106735', 'SSF3407199'),
('+918441930629', 'SSF5390553'),
('+918848343801', 'SSF5838252'),
('+918319839977', 'SSF5838731'),
('+918741016673', 'SSF5097902'),
('+919199433813', 'SSF5995518'),
('+919006170977', 'SSF5880048'),
('+919026189868', 'SSF5361348'),
('+919931423418', 'SSF5413132'),
('+919644516369', 'SSF4092367'),
('+919102112460', 'SSF5836741'),
('+919122528005', 'SSF5706518'),
('+919006324894', 'SSF5751747'),
('+919661109587', 'SSF5700321'),
('+919648249068', 'SSF5927399'),
('+919351806880', 'SSF5290348'),
('+919065856315', 'SSF2960998'),
('+919263783341', 'SSF5741466'),
('+919174280587', 'SSF5923305'),
('+919227048381', 'SSF5839407'),
('+919238055397', 'SSF5838445'),
('+919519237620', 'SSF5516585'),
('+919244350512', 'SSF5879690'),
('+917362066961', 'SSF5630216'),
('+917070906587', 'SSF5517469'),
('+918826252477', 'SSF6121332'),
('+918797973053', 'SSF6074650'),
('+918851258362', 'SSF6095585'),
('+919142987344', 'SSF6174917'),
('+919334718336', 'SSF4721122'),
('+916206553647', 'SSF5550139'),
('+916204404188', 'SSF5442577'),
('+916369067457', 'SSF5608400'),
('+917227850382', 'SSF3451637'),
('+917297911447', 'SSF5625999'),
('+917275265279', 'SSF3615848'),
('+917903286440', 'SSF5645206'),
('+917739731167', 'SID951374212787'),
('+917898138488', 'SSF4023335'),
('+917416676992', 'SSF3539224'),
('+917061370365', 'SSF5619985'),
('+917004780951', 'SSF5688870'),
('+917463829478', 'SSF5528168'),
('+917995935307', 'SSF3022137'),
('+918922867196', 'SSF2698903'),
('+918529219948', 'SSF5380750'),
('+918252917946', 'SSF5654065'),
('+918084099553', 'SSF5196071'),
('+918869991197', 'SSF3147384'),
('+918092711525', 'SSF3155286'),
('+918823825551', 'SSF3391351'),
('+918235777951', 'SSF5526492'),
('+919835914369', 'SSF3422056'),
('+919779325337', 'SSF5414462'),
('+919987410853', 'SSF3270125'),
('+919546699950', 'SSF3194747'),
('+919516250374', 'SSF3664309'),
('+919199622268', 'SSF5574587'),
('+919302564184', 'SSF5202150'),
('+919905228038', 'SSF5616199'),
('+919798099801', 'SSF5590761'),
('+919060663098', 'SSF5587424'),
('+919631443258', 'SSF5710875'),
('+919970048050', 'SSF5602428'),
('+919352505317', 'SSF2497144'),
('+919616072877', 'SSF2964400'),
('+919241074683', 'SSF5161152'),
('+919508868046', 'SSF5639798'),
('+919834387634', 'SSF5324239'),
('+919198796879', 'SID951374938518'),
('+919244587988', 'SSF4105529'),
('+917209328794', 'SSF6110323'),
('+918969333556', 'SSF5664322'),
('+919661936245', 'SSF4779665'),
('+917091241755', 'SSF4566156'),
('+917762857253', 'SSF6187344'),
('+917903311608', 'SSF5053606'),
('+918102745364', 'SSF6316686'),
('+918051141857', 'SSF6187368'),
('+919304542906', 'SSF5008919'),
('+917783004126', 'SSF4747211'),
('+917258057947', 'SSF6217536'),
('+919631348494', 'SSF6145586'),
('+916394437776', 'SSF2405778'),
('+916261721217', 'SSF5086172'),
('+916263289501', 'SSF3058482'),
('+917023601442', 'SSF3293869'),
('+917292874435', 'SSF4888898'),
('+917322842282', 'SSF2464238'),
('+917368080283', 'SSF4899742'),
('+917549533540', 'SSF3426064'),
('+917870136087', 'SSF5552277'),
('+917869809125', 'SSF5029039'),
('+917061049447', 'SSF4894842'),
('+917368840816', 'SSF2317376'),
('+917974789471', 'SID951375690243'),
('+917000798072', 'SSF4962468'),
('+917319749001', 'SSF5000079'),
('+917520189969', 'SSF5118574'),
('+917870847091', 'SSF4967757'),
('+917970115357', 'SSF5007420'),
('+917257860598', 'SSF2582688'),
('+918003051261', 'SID951375345742'),
('+918305224831', 'SSF4904170'),
('+918629943965', 'SSF5071129'),
('+918569840386', 'SSF5011687'),
('+918815222640', 'SSF4743325'),
('+918102776736', 'SID951375200634'),
('+918875244677', 'SSF4995307'),
('+918829839252', 'SSF4995332'),
('+918102720234', 'SSF5078370'),
('+918349413048', 'SSF3325375'),
('+919413551112', 'SSF4940380'),
('+919928745935', 'SSF5122437'),
('+919162215017', 'SSF5558409'),
('+919691244202', 'SSF4950859'),
('+919135894046', 'SID951374919663'),
('+919303327363', 'SSF4886019'),
('+919503428043', 'SSF5207640'),
('+919343424562', 'SSF5198590'),
('+919571509644', 'SSF2471485'),
('+919643099340', 'SSF4938846'),
('+919234064234', 'SSF5215669'),
('+919977434295', 'SSF4918663'),
('+919950180118', 'SSF2356373'),
('+917054772459', 'SSF6162875'),
('+918757579928', 'SSF6156729'),
('+919472585771', 'SSF6209203'),
('+919044698662', 'SSF5463947'),
('+919356532587', 'SSF6203827'),
('+919315729700', 'SSF6197626'),
('+919334581239', 'SSF5420996'),
('+917800460488', 'SSF5834445'),
('+919769049502', 'SSF6030883'),
('+917905047299', 'SSF4507187'),
('+919129671069', 'SSF3476386'),
('+916352466801', 'SID951374759507'),
('+916207264097', 'SSF3333636'),
('+916207447764', 'SSF4942752'),
('+916204257321', 'SSF4905655'),
('+916284001350', 'SSF4930763'),
('+916364596745', 'SSF2977540'),
('+916263640150', 'SSF4954967'),
('+916287810302', 'SID951376019150'),
('+917987932482', 'SSF5000935'),
('+917568511677', 'SSF5006834'),
('+917325070092', 'SSF2421463'),
('+917725079076', 'SSF4895244'),
('+917909041613', 'SSF4948297'),
('+917634878520', 'SSF4927207'),
('+917903392477', 'SSF2801587'),
('+917903546527', 'SSF4855480'),
('+917488665012', 'SSF4753272'),
('+917093791630', 'SSF4931809'),
('+917032301510', 'SSF4466740'),
('+917878871798', 'SSF4813686'),
('+917091661689', 'SSF4778108'),
('+917240712137', 'SSF4792283'),
('+918875901554', 'SSF5546071'),
('+918002535116', 'SSF4960459'),
('+918084329617', 'SSF4785338'),
('+918084401636', 'SSF4882694'),
('+918728036854', 'SSF4873833'),
('+918955155699', 'SSF4945809'),
('+918102476408', 'SSF2577925'),
('+919608789022', 'SSF4949515'),
('+919304420792', 'SSF5436145'),
('+919041881823', 'SSF4951109'),
('+919302973814', 'SSF4962799'),
('+919131783919', 'SSF5005881'),
('+919226060929', 'SSF5495713'),
('+919983390580', 'SSF4795126'),
('+919162603543', 'SSF4781642'),
('+919783332881', 'SSF4829566'),
('+919579922385', 'SSF4750969'),
('+919340749609', 'SSF4931805'),
('+919257763890', 'SSF4083036'),
('+919560780829', 'SSF4860747'),
('+919636100651', 'SSF4259864'),
('+919079858043', 'SSF4813600'),
('+919521472863', 'SSF4909989'),
('+919929532251', 'SSF4798287'),
('+916205684488', 'SSF6099120'),
('+919306966530', 'SSF5766068'),
('+919110977590', 'SSF5559259'),
('+917858941120', 'SSF5879469'),
('+918521793644', 'SSF4887260'),
('+918409700380', 'SSF5810697'),
('+919060952256', 'SSF5632551'),
('+917870785968', 'SSF6215684'),
('+917643095078', 'SSF4693657'),
('+918829060332', 'SSF4600277'),
('+918407801982', 'SSF3345333'),
('+918147959457', 'SSF6138994'),
('+917705823194', 'SSF6002014'),
('+918002821359', 'SSF5622276'),
('+916532659898', 'SID951375204630'),
('+916476676766', 'SID951375951276'),
('+916355608810', 'SSF4467974'),
('+916355365094', 'SSF4383417'),
('+916200714885', 'SSF3234348'),
('+916290283768', 'SSF4342731'),
('+916376553445', 'SSF4435456'),
('+916375461066', 'SSF4577724'),
('+917878681079', 'SSF4468763'),
('+917858845633', 'SSF4494395'),
('+917772907434', 'SSF2763603'),
('+917976005572', 'SSF4610231'),
('+917764044354', 'SSF4485974'),
('+917544966209', 'SSF4421009'),
('+917742184851', 'SSF4329357'),
('+917727835609', 'SSF4412895'),
('+917850826928', 'SSF4320314'),
('+917320016780', 'SSF4323271'),
('+917091816235', 'SSF4396218'),
('+917992084289', 'SSF4395324'),
('+917634813142', 'SSF4545410'),
('+917079830955', 'SSF4333299'),
('+917791037786', 'SSF4481052'),
('+917357702991', 'SSF4518279'),
('+917023488734', 'SID951375164552'),
('+917410964822', 'SSF4365196'),
('+918290959944', 'SSF4405834'),
('+918709569217', 'SSF4383431'),
('+918092665174', 'SSF4480425'),
('+918252007989', 'SSF4591756'),
('+918854083795', 'SSF4507357'),
('+918852859938', 'SSF4528861'),
('+918207500624', 'SSF4588677'),
('+918873286883', 'SSF4402970'),
('+918102312224', 'SSF2806671'),
('+918964955802', 'SSF3438381'),
('+918003679893', 'SSF4349876'),
('+918696971192', 'SSF4406369'),
('+918595422074', 'SSF4468481'),
('+918209023443', 'SSF4630717'),
('+919653879658', 'SSF4606872'),
('+919065564156', 'SSF4577929'),
('+919570922494', 'SSF2895381'),
('+919508621597', 'SID951375631523'),
('+919771567965', 'SSF4333963'),
('+919122076718', 'SSF4219505'),
('+919098655590', 'SSF2763602'),
('+919508390739', 'SSF4470111'),
('+919905446597', 'SSF4342912'),
('+919358988338', 'SSF4528871'),
('+919303297026', 'SSF4414066'),
('+919119262855', 'SSF4565745'),
('+919508463630', 'SSF4501219'),
('+919510008763', 'SSF4464005'),
('+919737554012', 'SID951375725852'),
('+919234487469', 'SSF4407321'),
('+919693465248', 'SSF4332300'),
('+919587100309', 'SID951375255049'),
('+919166891103', 'SSF4158705'),
('+919636490700', 'SSF4589654'),
('+917486062921', 'SSF4423276'),
('+917073924655', 'SSF2567384'),
('+917425698822', 'SID951376198882'),
('+917584807954', 'SSF2702493'),
('+917300343112', 'SID951374325428'),
('+917295840610', 'SSF4316919'),
('+918905935308', 'SSF4382693'),
('+918854931974', 'SSF4219476'),
('+918709570903', 'SSF4321193'),
('+918797679467', 'SID951373442058'),
('+918962697091', 'SSF4567048'),
('+918827792133', 'SSF3819144'),
('+918294292087', 'SSF4209762'),
('+918207834909', 'SSF4209738'),
('+918539906094', 'SSF4220247'),
('+919745123685', 'CID951376209341'),
('+919636121118', 'SSF4040246'),
('+919608879872', 'SID951376151617'),
('+916367509475', 'SSF4148698'),
('+917073524282', 'SSF2581943'),
('+917851969241', 'SSF4206426'),
('+918354052985', 'SID951376228861'),
('+918817305933', 'SID951374325383'),
('+919896762695', 'SSF3014848'),
('+919772363677', 'SSF4225717'),
('+916377606822', 'SSF3991800'),
('+916380089746', 'SSF3877240'),
('+917728801047', 'SSF3879332'),
('+917850889838', 'SSF3984130'),
('+917568621640', 'SSF3966455'),
('+917296953817', 'SSF4061294'),
('+918078621545', 'SSF3653774'),
('+918905286094', 'SSF4003698'),
('+918107839031', 'SSF2587136'),
('+919166103363', 'SSF3914111'),
('+919162332683', 'SSF5176621'),
('+916375381385', 'SSF2649647'),
('+916375426079', 'SSF2623000'),
('+918657755589', 'SID951375946582'),
('+918115741547', 'SSF3841239'),
('+918995548982', 'SSF3894059'),
('+919542525365', 'SSF3723538'),
('+919466446040', 'SSF3734413'),
('+919351682988', 'SSF3868728'),
('+919140109929', 'SSF3865293'),
('+919724290057', 'SSF3801179'),
('+919196022642', 'SID951374702234'),
('+918966888999', 'SSF3030650'),
('+918053066368', 'SSF2583232'),
('+919693643793', 'SSF3211784'),
('+919813535552', 'SSF3195564'),
('+919302525807', 'SID2125585493'),
('+917765899829', 'SID951375293499'),
('+917091629148', 'SID951373142687'),
('+917368039059', 'SSF2614195'),
('+917479640987', 'SSF2623582'),
('+917849993215', 'SSF2716008'),
('+919571957515', 'SSF2677274'),
('+919973653525', 'SSF2652137'),
('+919670957924', 'SSF2934162'),
('+919794213657', 'SSF2579873'),
('+919065515972', 'SSF2916205'),
('+916266477117', 'SSF5804567'),
('+916375148576', 'SSF5606286'),
('+916205293501', 'SSF6021275'),
('+916265491271', 'SSF6051819'),
('+916204644085', 'SSF6137253'),
('+916265358615', 'SSF5860416'),
('+917428081358', 'SSF6048189'),
('+917992394294', 'SSF6125149'),
('+917974140312', 'SSF5581529'),
('+917061132459', 'SSF6057639'),
('+917067088670', 'SSF5901068'),
('+917654435060', 'SSF5726220'),
('+917082669436', 'SSF6053661'),
('+917543934776', 'SSF5942130'),
('+917543842365', 'SSF6119228'),
('+917070273034', 'SSF6074652'),
('+917564017548', 'SSF6057360'),
('+917067178186', 'SSF5688839'),
('+918235549645', 'SSF6227196'),
('+918840044204', 'SSF6141503'),
('+918405862467', 'SSF3460681'),
('+918121834815', 'SSF6061494'),
('+918718067455', 'SSF5715507'),
('+918864006263', 'SSF3732237'),
('+918603443304', 'SSF5720819'),
('+918824428557', 'SSF5740085'),
('+918826784375', 'SSF6091471'),
('+918305719370', 'SSF6084083'),
('+918102688130', 'SSF4004595'),
('+918815938857', 'SSF6105819'),
('+918409315488', 'SSF6057963'),
('+919534852895', 'SSF5882845'),
('+919931045818', 'SSF2972803'),
('+919109866944', 'SSF5598171'),
('+919128811897', 'SSF6042655'),
('+919534658902', 'SSF5683127'),
('+919919210267', 'SSF3778074'),
('+919873188764', 'SSF6071506'),
('+919770856676', 'SSF6105406'),
('+919343210735', 'SSF5700524'),
('+919754270072', 'SSF6110437'),
('+919450695113', 'SSF6104710'),
('+919135315952', 'SSF5678315'),
('+919117911637', 'SSF6070586'),
('+919565553268', 'SSF6104429'),
('+919793488204', 'SSF5726334'),
('+919244308214', 'SSF6073426'),
('+919341148761', 'SSF3002410'),
('+919279570810', 'SSF6053237'),
('+919575214305', 'CID224400600'),
('+919241284576', 'SID951373960898'),
('+919162949906', 'SSF6181847'),
('+917070302351', 'SID951374593298'),
('+917089004151', 'SID951373651856'),
('+916204600263', 'SID951376098525'),
('+917479479716', 'SSF2828950'),
('+917479616582', 'SSF2795710'),
('+918809866805', 'SSF2918377'),
('+918541877217', 'SSF2883851'),
('+919302164962', 'SSF2800279'),
('+919608672297', 'SSF2478030'),
('+916306003792', 'SSF3976208'),
('+916378989710', 'SSF5392919'),
('+916206215351', 'SSF5905632'),
('+916202320594', 'SSF3125738'),
('+916369925119', 'SSF3712258'),
('+916299854260', 'SSF3279936'),
('+916299324171', 'SSF3228957'),
('+916205718682', 'SSF5699661'),
('+916209831914', 'SSF5765346'),
('+916206360827', 'SSF6016896'),
('+916379515464', 'SSF3391914'),
('+917250850130', 'SSF3784342'),
('+917362080063', 'SSF6093208'),
('+917547843102', 'SSF6034299'),
('+917295841989', 'SSF5883741'),
('+917033217100', 'SSF5701306'),
('+917723904790', 'SSF3543065'),
('+917667306943', 'SSF5924974'),
('+917879354059', 'SSF3206597'),
('+917061939365', 'SSF5925708'),
('+917439085707', 'SSF6085063'),
('+917549175125', 'SSF5946566'),
('+917255948942', 'SSF6116310'),
('+917838880449', 'SSF6077305'),
('+917384501348', 'SSF6111581'),
('+918948294241', 'SSF3717001'),
('+918252388289', 'SSF4134621'),
('+918603724946', 'SSF3668000'),
('+918207830794', 'SSF5932197'),
('+918530608343', 'SSF3901170'),
('+918809405894', 'SSF6064118'),
('+918582057784', 'SSF6073429'),
('+918084015341', 'SSF5990817'),
('+918102270884', 'SSF6134772'),
('+918271751846', 'SSF5925533'),
('+918294396335', 'SSF6115822'),
('+918809745076', 'SSF5974948'),
('+918235114763', 'SSF5925629'),
('+918910792560', 'SSF3759780'),
('+918521582117', 'SSF5940205'),
('+918651510094', 'SSF6086901'),
('+918619041638', 'SSF5617808'),
('+918480586135', 'SSF5908214'),
('+918969842467', 'SSF6033477'),
('+918540869945', 'SSF6113840'),
('+918252904500', 'SSF5414173'),
('+918340712006', 'SSF5959003'),
('+919334314413', 'SSF3442288'),
('+919006583855', 'SSF5593662'),
('+919509540405', 'SSF5615374'),
('+919415525093', 'SSF3400555'),
('+919010976538', 'SSF6034936'),
('+919660147277', 'SSF5863385'),
('+919955103731', 'SSF5662567'),
('+919771660358', 'SSF3566643'),
('+919343934106', 'SSF5916727'),
('+919915038145', 'SSF6134790'),
('+919234900689', 'SSF5666825'),
('+919162577031', 'SSF3346686'),
('+919109524460', 'SSF3738564'),
('+919931966906', 'SSF5439310'),
('+919043187316', 'SSF2941562'),
('+919341977602', 'SSF5380125'),
('+919693918648', 'SSF5412150'),
('+919229168366', 'SSF6035447'),
('+919991754405', 'SSF6116772'),
('+919631413684', 'SSF4723870'),
('+919591278243', 'SSF2950921'),
('+919686126849', 'SSF5580895'),
('+919580068134', 'SSF3371481'),
('+919608475026', 'SSF5940517'),
('+917480007807', 'SSF5532458'),
('+917644043422', 'SSF6174278'),
('+918969927781', 'SSF5712262'),
('+918808689926', 'SSF5984051'),
('+918757033787', 'SSF6070084'),
('+919555257036', 'SSF6151301'),
('+919234903612', 'SSF4679964'),
('+919034883437', 'SSF5967272'),
('+919971990314', 'SSF5904491'),
('+919031934172', 'SSF5458177'),
('+916284552346', 'SSF5909367'),
('+917654173740', 'SSF6246979'),
('+919326329451', 'SID2125629852'),
('+918100620707', 'SSF2735040'),
('+916287327484', 'SSF3798255'),
('+916389565720', 'SSF5869201'),
('+916203499224', 'SSF5708838'),
('+917992080235', 'SSF5869613'),
('+917258848916', 'SSF5740097'),
('+917250843218', 'SSF5722921'),
('+917725838751', 'SSF5763478'),
('+917989315606', 'SSF5815877'),
('+917050399285', 'SSF5940913'),
('+918809676187', 'SSF3591816'),
('+918010658141', 'SSF5839749'),
('+918797308463', 'SSF5624464'),
('+918629953403', 'SSF5340115'),
('+918349792262', 'SSF5333672'),
('+918010331635', 'SSF6011003'),
('+919165433175', 'SSF5601781'),
('+919631006875', 'SSF5827702'),
('+919279690425', 'SSF5841670'),
('+919651867388', 'SSF5915842'),
('+919798957269', 'SSF5616696'),
('+919571453858', 'SSF5181987'),
('+919006444300', 'SSF5497094'),
('+919241039171', 'SSF5791938'),
('+919122127975', 'SSF5705531'),
('+919521834402', 'SSF5135744'),
('+919151186832', 'SSF4622416'),
('+919896628694', 'SSF5920589'),
('+916387503647', 'SSF5612914'),
('+917568330493', 'SID951374550892'),
('+917870835437', 'SSF2745520'),
('+917000483025', 'SSF5723556'),
('+917852031235', 'SID951376107438'),
('+917563812938', 'SSF5585739'),
('+917737056745', 'SSF5073286'),
('+917903014132', 'SSF2477214'),
('+918529499935', 'SSF5373730'),
('+918084509626', 'SSF5167697'),
('+918092392410', 'SSF5618178'),
('+918084592293', 'SSF2766276'),
('+918434909022', 'SSF5507273'),
('+918434002437', 'SSF5728215'),
('+919675634654', 'SSF5713056'),
('+919589638174', 'SSF5213262'),
('+919022200904', 'SSF5713817'),
('+919934134395', 'SSF2477573'),
('+919691386332', 'SSF5290923'),
('+919199369823', 'SSF2575333'),
('+919508041348', 'SSF4224062'),
('+919241004183', 'SSF5647385'),
('+919570683390', 'SSF5558879'),
('+919334756835', 'SSF2665898'),
('+919608222073', 'SID951373498069'),
('+917631598123', 'SSF5857253'),
('+919262640830', 'SSF5314229'),
('+919065589067', 'SSF4812997'),
('+919012555625', 'SSF6010699'),
('+919570260432', 'SSF6243415'),
('+919102538959', 'SSF5443186'),
('+916209733809', 'SSF6295922'),
('+916203272057', 'SSF6149981'),
('+916269228086', 'SSF4798830'),
('+916263178753', 'SSF5151161'),
('+916205946647', 'SSF4950561'),
('+916307174126', 'SSF3016954'),
('+916205394216', 'SSF5195775'),
('+916264144877', 'SSF5097008'),
('+916261028520', 'SSF4962067'),
('+916200778630', 'SSF3251859'),
('+916267842536', 'SSF5014660'),
('+917646863051', 'SSF3942139'),
('+917070245245', 'SID951374672597'),
('+917762029104', 'SSF4953659'),
('+917250202680', 'SSF5057543'),
('+917631571835', 'SSF4895112'),
('+917033142642', 'SSF5102054'),
('+917367038283', 'SSF4596962'),
('+917725898697', 'SID951373907281'),
('+917479705790', 'SSF4983237'),
('+917321987397', 'SSF5215665'),
('+918290360713', 'SID951375894010'),
('+918409115572', 'SSF2400183'),
('+918817546129', 'SSF4920678'),
('+918102545028', 'SSF5563750'),
('+918815281643', 'SSF5060736'),
('+918271947564', 'SSF2591070'),
('+918103630663', 'SSF3045299'),
('+918200955631', 'SSF5075086'),
('+918601107158', 'SSF5053093'),
('+918092526277', 'SSF3100329'),
('+918420145196', 'SSF5102068'),
('+918107509168', 'SSF3314514'),
('+918840827023', 'SID951375465219'),
('+918210679393', 'SSF4878943'),
('+919660319964', 'SSF4752837'),
('+919897476393', 'SSF5092811'),
('+919303986728', 'SID951375225339'),
('+919343043862', 'SSF5164287'),
('+919341484388', 'SSF3413970'),
('+919471993895', 'SSF4255827'),
('+919546454287', 'SSF5152378'),
('+919263751423', 'SSF4896889'),
('+919871948647', 'SSF5013560'),
('+919153742646', 'SID951376150742'),
('+919155856032', 'SSF3596675'),
('+919244234547', 'SSF5061826'),
('+919234134265', 'SSF5040131'),
('+919801491441', 'SSF5118562'),
('+919511254976', 'SID951375577761'),
('+919244543328', 'SSF4703500'),
('+919523601848', 'SSF4969250'),
('+919755579181', 'SSF4993666'),
('+919244712780', 'SSF4904381'),
('+919329935587', 'SSF4945907'),
('+919165800679', 'SSF5023606'),
('+919279154829', 'SSF4981428'),
('+919691437831', 'SSF5002191'),
('+919770282638', 'SSF4933485'),
('+919031171587', 'SSF4948315'),
('+917547853495', 'SSF4332559'),
('+917905603761', 'SSF6156981'),
('+919256756115', 'SSF5552921'),
('+918889452789', 'SID2125387859'),
('+917897741649', 'SSF3335212'),
('+918957162593', 'SSF5766527'),
('+916377397264', 'SSF4763847'),
('+916202005827', 'SSF2950448'),
('+916204757012', 'SSF2429801'),
('+916206892057', 'SSF4378797'),
('+916202984808', 'SSF4860802'),
('+916201430059', 'SSF4496998'),
('+916375316552', 'SSF5484423'),
('+916377812128', 'SSF4814396'),
('+917878267129', 'SSF4906061'),
('+917852076352', 'SSF4767591'),
('+917742112177', 'SSF4757338'),
('+917209310814', 'SSF3118485'),
('+917418256065', 'SID951375716063'),
('+917073115025', 'SSF4795050'),
('+917562905981', 'SSF4923934'),
('+917856951049', 'SID951375525353'),
('+917426052635', 'SSF5499373'),
('+917067625400', 'SSF4931990'),
('+917306938242', 'SSF4978619'),
('+917766932955', 'SID2125776484'),
('+918103936082', 'SSF4962416'),
('+918815845381', 'SSF5001009'),
('+918431771559', 'SSF4746949'),
('+918434400737', 'SSF4868916'),
('+918540897498', 'SSF4855544'),
('+918000119282', 'SSF5435500'),
('+918092525645', 'SID951374515967'),
('+918987329219', 'SSF4794650'),
('+918797216891', 'SSF4893039'),
('+918890298549', 'SSF4316999'),
('+919279203896', 'SSF4620411'),
('+919256559051', 'SSF4411141'),
('+919950833808', 'SSF4761834'),
('+919329059272', 'SSF5012274'),
('+919798944672', 'SSF5005432'),
('+919205376640', 'SSF4629773'),
('+919098403185', 'SSF2495640'),
('+919580032044', 'SSF4963860'),
('+919835076926', 'SSF4889516'),
('+919572736762', 'SSF4783291'),
('+919511073518', 'SSF3290249'),
('+919939326861', 'SSF4848033'),
('+919905427363', 'SSF4800670'),
('+919024677379', 'SSF4813463'),
('+918958359874', 'SSF6036935'),
('+918789864037', 'SSF6098224'),
('+918252292897', 'SSF5765604'),
('+918237464291', 'SSF6150852'),
('+918092242421', 'SSF5756115'),
('+916287105198', 'SSF4693823'),
('+917362049197', 'SSF4657363'),
('+917654129989', 'SSF4694614'),
('+919709651860', 'SSF6095570'),
('+916287254399', 'SSF2321507'),
('+916367541794', 'SSF4356581'),
('+917597654632', 'SSF4371544'),
('+917986758372', 'SSF4383455'),
('+917547074721', 'SSF4417237'),
('+917357326243', 'SSF4252206'),
('+917627055479', 'SSF4529974'),
('+917067117164', 'SSF4414042'),
('+917428634602', 'SSF4448567'),
('+917250054041', 'SSF4516811'),
('+917665751596', 'SSF4617381'),
('+917568464942', 'SSF4273814'),
('+918239471553', 'SSF4573118'),
('+918434902524', 'SSF4505200'),
('+918779024390', 'SSF4605634'),
('+918709598464', 'SSF4400179'),
('+918306447819', 'SSF4553261'),
('+918890661403', 'SSF4570218'),
('+918769647831', 'SSF4323911'),
('+918318651183', 'SSF4468828'),
('+918278656860', 'SSF4349895'),
('+919877994584', 'SSF4390210'),
('+919509741108', 'SSF4353969'),
('+919461432696', 'SSF4322098'),
('+919162827295', 'SSF4534842'),
('+919347226869', 'SSF4480289'),
('+919508831400', 'SSF4403977'),
('+919691657773', 'SSF4392062'),
('+919079290971', 'SSF4506778'),
('+919351713839', 'SSF4506951'),
('+919155911674', 'SSF4400098'),
('+919680090359', 'SSF4570742'),
('+919119150362', 'SSF4342201'),
('+919216432622', 'SSF4171835'),
('+919352464415', 'SSF4409005'),
('+919341814112', 'SSF2770747'),
('+919257423817', 'SSF2674644'),
('+919799624848', 'SID951375406101'),
('+919265877113', 'SSF4570164'),
('+919772863947', 'SSF4455318'),
('+919079618132', 'SSF4365195'),
('+916264213896', 'SSF4340495'),
('+917877702378', 'SSF4113025'),
('+917877575056', 'SSF4308440'),
('+918209221785', 'SSF4040159'),
('+918875666699', 'SID951373669642'),
('+918949907494', 'SSF4472293'),
('+918000234873', 'SSF3960673'),
('+918207830649', 'SSF4313848'),
('+919343818519', 'SID951374353756'),
('+919131433471', 'SSF4340560'),
('+919928724139', 'SSF4236494'),
('+919302358713', 'SSF4351355'),
('+919928071682', 'SSF4017185'),
('+919928925195', 'SSF4348921'),
('+919256506321', 'SSF4232817'),
('+919784291637', 'SSF4193644'),
('+919166984778', 'SSF4057673'),
('+917098099086', 'SSF3734943'),
('+917340278767', 'SSF2777550'),
('+917878003155', 'SSF3945463'),
('+918094276124', 'SSF3830746'),
('+918239561748', 'SSF4021698'),
('+919828983785', 'SSF3967114'),
('+919649952945', 'SSF4021699'),
('+919636493030', 'SSF3966194'),
('+919784388947', 'SSF3897247'),
('+919509475536', 'SSF3152892'),
('+919464664946', 'SSF3819098'),
('+919563986555', 'SSF3765004'),
('+918684072697', 'SSF2495047'),
('+919799324840', 'SSF3669050'),
('+917509808443', 'SSF2325240'),
('+917470743823', 'SSF2422446'),
('+918349307435', 'SSF2288243'),
('+918955137610', 'SSF2288242'),
('+919343113354', 'SSF2813388'),
('+916268100618', 'SSF5909663'),
('+916264242489', 'SSF3589240'),
('+916354196925', 'SSF5631562'),
('+917828163934', 'SSF6009916'),
('+917905260817', 'SSF3581151'),
('+917985293205', 'SSF5932262'),
('+917869061402', 'SSF6102615'),
('+918821012770', 'SSF6117282'),
('+919755677013', 'SSF3440651'),
('+919993460110', 'SSF5611631'),
('+919630262854', 'SSF6111004'),
('+919174262874', 'SSF2864086'),
('+919554870761', 'SSF4483058'),
('+918252286912', 'SSF3482266'),
('+919580940579', 'SID951374681622'),
('+919893883870', 'SID2125606160'),
('+916205572180', 'SID951375280931'),
('+917974420164', 'SSF2918144'),
('+918827472692', 'SID951373702407'),
('+918830240538', 'SID951375379868'),
('+919341247185', 'SSF4996875'),
('+919155481425', 'SID951375702972'),
('+916398015407', 'SSF4807360'),
('+916393395381', 'SSF5926952'),
('+919122575250', 'SID951375828320'),
('+919302478662', 'SID951373804651'),
('+918000251715', 'SSF2779195'),
('+916201052091', 'SSF5345472'),
('+918797961930', 'SSF3384625'),
('+919766090834', 'SSF4814006'),
('+916264125523', 'SID951373891960'),
('+918210160507', 'SID951375674232'),
('+917004881836', 'SSF5621329'),
('+918094358451', 'SSF3330001'),
('+918109170075', 'SSF3129640'),
('+916264731608', 'SID951373533265'),
('+918418965017', 'SSF2601854'),
('+916265123136', 'CID064700600'),
('+919174489322', 'SSF4564729'),
('+919784550178', 'SID951374330301'),
('+918085672642', 'SID2125726082'),
('+916262485168', 'SSF2992463'),
('+918875568566', 'SID951372975427'),
('+919660762898', 'SID951375798765'),
('+918770119421', 'SSF3797879'),
('+919302586849', 'SSF2334364'),
('+917033985269', 'SID951375621232'),
('+917898819868', 'CID093406307'),
('+917257016375', 'SSF4167335'),
('+919981784452', 'CID142806648'),
('+916260218071', 'SSF3294142'),
('+917725865471', 'SSF2833853'),
('+918085395239', 'SID951375283543'),
('+918409860504', 'SID951375455691'),
('+918874502033', 'SSF3007421'),
('+916267011960', 'SID114184'),
('+919039734627', 'SSF3844198'),
('+919555410780', 'SSF3027698'),
('+919116280259', 'SSF4134357'),
('+919517024166', 'SSF3394748'),
('+917050143850', 'SSF5774002'),
('+917518731724', 'SSF3194083'),
('+916287317950', 'SID951374058016'),
('+919685513638', 'SID951374880821'),
('+919753975278', 'SSF3794527'),
('+918235545746', 'SID951374687383'),
('+918962875398', 'SID951375389026'),
('+917024341079', 'SSF2463925'),
('+917782029025', 'SID951374629007'),
('+917067556792', 'SSF4508095'),
('+919534561598', 'SSF4839114'),
('+917728959435', 'SSF2334688'),
('+918780181687', 'SSF3049925'),
('+919752772783', 'CID206804261'),
('+917073588698', 'SSF3882027'),
('+917321933727', 'SSF2963114'),
('+919835665659', 'SSF3488380'),
('+917489619765', 'SSF3322418'),
('+916260535293', 'SID951375750344'),
('+917726814400', 'SSF3743882'),
('+917783013853', 'SID951372797279'),
('+917050663089', 'SSF4960044'),
('+917322051479', 'SSF5771739'),
('+919983923853', 'SSF2977126'),
('+919307685332', 'SSF4910468'),
('+919555968721', 'SSF5167255'),
('+917654396061', 'SSF4201330'),
('+918295362754', 'SSF5083046'),
('+919793617145', 'SSF4807202'),
('+919102482595', 'SID951376100201'),
('+919517046559', 'SSF4952723'),
('+918875649956', 'SSF2465616'),
('+917739009407', 'SSF4350659'),
('+917703076373', 'SSF3188364'),
('+919009125817', 'SID2125169689'),
('+917440792876', 'SID951376213330'),
('+919801980732', 'SSF3260029'),
('+919303337095', 'SSF4008867'),
('+919931256877', 'SID951375285317'),
('+919244263951', 'SID951374608440'),
('+919494949495', 'SID951374881051'),
('+919407443416', 'SSF3123071'),
('+919153056994', 'SSF6280588'),
('+919057945867', 'SID951374979478'),
('+919279749123', 'SSF3460056'),
('+919257314773', 'SSF4836365'),
('+917723048016', 'SID951374173061'),
('+919617350259', 'SSF3137220'),
('+917004707915', 'SSF4269597'),
('+919244317913', 'CID951376202345'),
('+919713446124', 'SSF3388102'),
('+919399050560', 'SSF2823405'),
('+919833126199', 'SID951374852086'),
('+917023521540', 'SID951374944201'),
('+919905545648', 'SID951374181552'),
('+918305264366', 'SSF2686198'),
('+919631253108', 'SSF5765699'),
('+919799001382', 'SSF2631966'),
('+918745847535', 'SSF4920162'),
('+917380738711', 'SID951375280641'),
('+917704037973', 'SSF3821964'),
('+919554642503', 'SID951374292980'),
('+918090779821', 'SSF5600531'),
('+916351768038', 'SSF2523915'),
('+918874054743', 'SID951375000388'),
('+917257812566', 'SSF4302304'),
('+918629933784', 'SID951375562499'),
('+919801058123', 'SSF4005166'),
('+918709553951', 'SID951375128259'),
('+918959946862', 'SID951375731343'),
('+917828023596', 'SID951375013790'),
('+918955699581', 'SID951376161351'),
('+918603526644', 'SSF4865635'),
('+918529835579', 'SSF3809708'),
('+919508636621', 'SSF4506812'),
('+919630782187', 'SSF6171833'),
('+916263507639', 'SSF4921549'),
('+919918775443', 'SSF2476465'),
('+917489529658', 'SID951374171265'),
('+919111468875', 'SID2125221691'),
('+919340306540', 'SSF3537050'),
('+916203229774', 'SID951375600891'),
('+916264580125', 'SID951375505764'),
('+917073226310', 'SID951374958191'),
('+916299094641', 'SSF2529792'),
('+917255042179', 'SSF2483723'),
('+916287733568', 'SSF6352500'),
('+917379946987', 'SSF6019753'),
('+917033029482', 'SSF3275069'),
('+917536092650', 'SSF6015929'),
('+917004911261', 'SSF3009801'),
('+918051451933', 'SID951375838525'),
('+918235128739', 'SSF5701920'),
('+918878161009', 'SSF6325108'),
('+919102016262', 'SSF6181090'),
('+919864481143', 'SSF6226543'),
('+919006752968', 'SSF6087073'),
('+919939007626', 'SSF3609684'),
('+919685287726', 'SSF5947544'),
('+919088691664', 'SSF3253731'),
('+919680399355', 'SSF5878708'),
('+919981348345', 'SSF6264419'),
('+919369940748', 'SSF6101691'),
('+919177651547', 'SSF3649570'),
('+919142754984', 'SSF6261472'),
('+919771212047', 'SSF6343121'),
('+919098987571', 'SSF4708946'),
('+919660425356', 'SSF5932812'),
('+919753592182', 'SSF3475997'),
('+918447064363', 'SSF2364149'),
('+916204300345', 'SSF5655614'),
('+916264678735', 'SSF6023598'),
('+917859013982', 'SSF5721035'),
('+917972090696', 'SSF5354029'),
('+917667152239', 'SSF5835848'),
('+917759967896', 'SID951375952120'),
('+918697588478', 'SSF5845028'),
('+918409910350', 'SSF6032182'),
('+918084486321', 'SSF5962999'),
('+918935903019', 'SSF6136424'),
('+919302732761', 'SSF4275999'),
('+919973127159', 'SSF6135446'),
('+919302786378', 'SID951374124341'),
('+919905431346', 'SSF3391826'),
('+919591137145', 'SSF5835543'),
('+919828322140', 'SSF5674111'),
('+917739514185', 'SSF6263058'),
('+919693698797', 'SSF5735786'),
('+919102065668', 'SSF6225525'),
('+917782090517', 'SSF6070663'),
('+917260836283', 'SSF6125045'),
('+919304908468', 'SSF5676938'),
('+919305683440', 'SSF6158852'),
('+919036702541', 'SID951374539978'),
('+917510045834', 'SSF2817559'),
('+917388515593', 'SSF2701452'),
('+917366819276', 'SSF2509706'),
('+918010053731', 'SSF2769706'),
('+918601644856', 'SSF2784020'),
('+919006395990', 'SID951376177253'),
('+919636163103', 'SSF2465794'),
('+918651557300', 'SSF6205178'),
('+918797841129', 'SSF3931733'),
('+918528629507', 'SSF6136387'),
('+918757729794', 'SSF4672577'),
('+919648891852', 'SSF6079443'),
('+919279125399', 'SSF5179268'),
('+919234009105', 'SSF5910673'),
('+916203696906', 'SID951375790243'),
('+916207175262', 'SSF5349883'),
('+916206679427', 'SSF5670050'),
('+917764937181', 'SSF3218502'),
('+917779813009', 'SSF5464880'),
('+917779822839', 'SSF5430910'),
('+917209891874', 'SSF6084495'),
('+917670944547', 'SSF6121768'),
('+917260897612', 'SSF3350178'),
('+917000592405', 'SSF6091819'),
('+917851806591', 'SSF5397963'),
('+917008613403', 'SSF6098256'),
('+917257936063', 'SSF5802564'),
('+917339750348', 'SSF5522257'),
('+917079215301', 'SSF5567227'),
('+917850940119', 'SSF5717890'),
('+917879540179', 'SSF3862477'),
('+918827173055', 'SSF3808309'),
('+918409220556', 'SSF6067014'),
('+918434174741', 'SSF3048850'),
('+918409932834', 'SSF5632255'),
('+918252681487', 'SSF5631512'),
('+918925177610', 'SSF5652379'),
('+918107873422', 'SSF3581016'),
('+919241556992', 'SSF6005363'),
('+919057569662', 'SSF3841246'),
('+919981154542', 'SSF3492436'),
('+919771666718', 'SSF6092988'),
('+919667973321', 'SSF6116268'),
('+919523392070', 'SSF5547868'),
('+919234210823', 'SSF6230544'),
('+919262989919', 'SSF5531945'),
('+919229451146', 'SSF6128190'),
('+919918142807', 'SSF5549922'),
('+919304233241', 'SSF5727578'),
('+919244316568', 'SSF6160586'),
('+919302271211', 'SSF5572545'),
('+919155012183', 'SSF3623515'),
('+919601844297', 'SSF6078990'),
('+919534656573', 'SSF5582426'),
('+919106476420', 'SSF5415844'),
('+917463015421', 'SSF5821080'),
('+917631570563', 'SSF5939055'),
('+919919299780', 'SSF5891819'),
('+919336039884', 'SSF6203611'),
('+919572264723', 'SSF5545046'),
('+916370515031', 'SSF5371854'),
('+916266286867', 'SSF5915111'),
('+916206530682', 'SID951375994343'),
('+916264801339', 'SSF3581074'),
('+916203709955', 'SSF5800262'),
('+917870611774', 'SSF5978938'),
('+917566615066', 'SSF3683815'),
('+917903746612', 'SSF3981923'),
('+917209704579', 'SSF5566797'),
('+917766968224', 'SSF2410085'),
('+917464002827', 'SSF5930749'),
('+917067896489', 'SSF3515003'),
('+918603752457', 'SSF2792174'),
('+918252789951', 'SID951374727312'),
('+918795830267', 'SSF3718266'),
('+918936801634', 'SSF3405841'),
('+918528676327', 'SSF3668964'),
('+918877464944', 'SSF5459174'),
('+918677801130', 'SSF5987145'),
('+918252653907', 'SSF5997277'),
('+918797642380', 'SSF5932102'),
('+918435062744', 'SSF3776038'),
('+919608599980', 'SSF3199545'),
('+919982711017', 'SID951375283874'),
('+919262235788', 'SSF3956999'),
('+919304506574', 'SSF2747404'),
('+919305214412', 'SSF3790338'),
('+919508856882', 'SSF5712775'),
('+919799065885', 'SSF5301286'),
('+919241692275', 'SSF5922181'),
('+919302367839', 'SSF3649464'),
('+919162564163', 'SSF3515878'),
('+919128259325', 'SSF2633380'),
('+919279609360', 'SSF5561083'),
('+919693056703', 'SSF2965598'),
('+919752574105', 'SSF3678042'),
('+919279926298', 'SSF4179645'),
('+919263876251', 'SSF3576354'),
('+919341943032', 'SSF3576002'),
('+919523637151', 'SSF5617293'),
('+918757862109', 'SSF5728422'),
('+917667350526', 'SSF5718767'),
('+919263729337', 'SSF5668828'),
('+917209829029', 'SSF5487720'),
('+918434478317', 'SSF6176617'),
('+917739615747', 'SSF4584317'),
('+918874860728', 'SSF6135121'),
('+918920473434', 'SSF6239554'),
('+918961395122', 'SSF5815305'),
('+918287281402', 'SSF6256745'),
('+916263256464', 'SID951374154611'),
('+918767576484', 'SID2125576963'),
('+918294445048', 'SSF6358056'),
('+919311734977', 'SSF6137809'),
('+916261083728', 'SSF5178677'),
('+916266472437', 'SSF4888315'),
('+916202098631', 'SSF4572813'),
('+916205053570', 'SSF2920529'),
('+916279084123', 'SID951374857560'),
('+917740885980', 'SSF5502787'),
('+917742118446', 'SSF4992743'),
('+917089671605', 'SSF5174214'),
('+917878677691', 'SSF5134868'),
('+917489157758', 'SSF5057973'),
('+917079372951', 'SSF3464186'),
('+917255983272', 'SSF4088613'),
('+917292997830', 'SID951375897155'),
('+918529110871', 'SSF5342198'),
('+918696634434', 'SSF5122136'),
('+918252360763', 'SSF3039459'),
('+918092295303', 'SSF5381301'),
('+918092075242', 'SSF4998708'),
('+918249815262', 'SSF5534984'),
('+918690488631', 'SSF5047832'),
('+918251035055', 'SSF4952971'),
('+918963958073', 'SSF4880156'),
('+918271769821', 'SSF2880339'),
('+918092826115', 'SSF4949014'),
('+918102903682', 'SSF5385296'),
('+918582809981', 'SSF5432490'),
('+918092263088', 'SSF4931389'),
('+918757984531', 'SSF5439565'),
('+918890670096', 'SSF5342366'),
('+919934140409', 'SSF5472958'),
('+919572750208', 'SSF4896032'),
('+919771773081', 'SSF5134453'),
('+919935793843', 'SID951374930690'),
('+919149868637', 'SSF5494363'),
('+919109345924', 'SSF3325888'),
('+919608112749', 'SSF5338885'),
('+919572214005', 'SID2125676989'),
('+919340059191', 'SSF5465883'),
('+919828875718', 'SSF5350342'),
('+919060611225', 'SSF5335494'),
('+919179069167', 'SSF5333284'),
('+919119236548', 'SID951374972389'),
('+919263130767', 'SSF4646383'),
('+919060758765', 'SSF4865456'),
('+919128818493', 'SSF5445751'),
('+919102374288', 'SSF5542347'),
('+919664693983', 'SSF2809953'),
('+919315222869', 'SSF3706542'),
('+919302189482', 'SSF5310477'),
('+919772261722', 'SSF5418939'),
('+916287825054', 'SSF6243373'),
('+918340475637', 'SSF6213057'),
('+919628716909', 'SSF6194344'),
('+916399787823', 'SSF5841563'),
('+919199443559', 'SSF4700314'),
('+916263422047', 'SSF3664440'),
('+917905747868', 'SSF2682221'),
('+917239969852', 'SID951375383333'),
('+917469534888', 'SID951375055070'),
('+917877526690', 'SSF2774270'),
('+917073038078', 'SSF2599578'),
('+917091641581', 'SSF4680598'),
('+917250581673', 'SSF5136465'),
('+918849528791', 'SSF4721667'),
('+918949183529', 'SSF5190657'),
('+918824238772', 'SSF2589831'),
('+918003094190', 'SSF4722265'),
('+918002611565', 'SSF4831808'),
('+918770717950', 'SSF3648091'),
('+918949896500', 'SSF2877489'),
('+919983150425', 'SSF4553823'),
('+919065813285', 'SID951375084906'),
('+919982657216', 'SSF5058063'),
('+919460226118', 'SSF5288506'),
('+919263434114', 'SSF2555137'),
('+919256737251', 'SSF5205092'),
('+919896331260', 'SSF5288790'),
('+919155043295', 'SSF4816505'),
('+919024549212', 'SSF5185009'),
('+919460895215', 'SSF5301749'),
('+919102290156', 'SSF4945468'),
('+919783072970', 'SSF5160634'),
('+918877429662', 'SSF5691389'),
('+917410920394', 'SSF4503711'),
('+919784157910', 'SSF2560693'),
('+916353255526', 'SSF4718952'),
('+916376044022', 'SSF4288584'),
('+916367992125', 'SSF4483546'),
('+917470822804', 'SSF4778685'),
('+917425831615', 'SSF2807222'),
('+917568734079', 'SSF4774472'),
('+917976435346', 'SSF3351665'),
('+917479977989', 'SSF4764095'),
('+917976584482', 'SSF4779238'),
('+917976347319', 'SSF4694341'),
('+917209171072', 'SSF4732253'),
('+917033098506', 'SSF4732048'),
('+917043995746', 'SSF4689071'),
('+917665847830', 'SSF4769169'),
('+918000447955', 'SSF4778670'),
('+918769303020', 'SSF4790542'),
('+918538991403', 'SSF4707517'),
('+918302819360', 'SSF4768613'),
('+918797303799', 'SSF2779302'),
('+919636292870', 'SSF4774523'),
('+919857567979', 'SSF2592700'),
('+919770245597', 'SSF4728066'),
('+919982943984', 'SSF4757335'),
('+919610408139', 'SSF4288546'),
('+919828303461', 'SSF4288094'),
('+919991959731', 'SID951376188847'),
('+919462555186', 'SSF4669049'),
('+919508038844', 'SSF4335258'),
('+917572972556', 'SSF4089248'),
('+917300371510', 'SSF4380596'),
('+917851869388', 'SSF4673457'),
('+917562951276', 'SSF4501251'),
('+918852021400', 'SSF4210067'),
('+918305076383', 'SSF4085558'),
('+918829856146', 'SSF4168292'),
('+918969245202', 'SSF4743487'),
('+919166474124', 'SSF3886995'),
('+919256153498', 'SSF4135196'),
('+917727930528', 'SSF3974160'),
('+918269548309', 'SSF3686658'),
('+918058305558', 'SSF4034473'),
('+919348252108', 'SSF4031701'),
('+919303789919', 'SID2125778698'),
('+917742290149', 'SSF3839328'),
('+917339945136', 'SSF4138474'),
('+918306642236', 'SSF4167058'),
('+918758898868', 'SSF3879811'),
('+919509827627', 'SSF3954716'),
('+919001595851', 'SID951375869978'),
('+916378772433', 'SSF4031299'),
('+916566565656', 'SSF3572213'),
('+916367899072', 'SSF3977289'),
('+918658448649', 'SID951374691268'),
('+918858174908', 'SID2125323369'),
('+919412565555', 'SSF3446739'),
('+919765083935', 'SSF4042543'),
('+919772068139', 'SSF4004158'),
('+919897979494', 'SSF3674681'),
('+919956165516', 'SSF3457970'),
('+919303850364', 'SSF3727481'),
('+917898805524', 'SID2125354133'),
('+918757229963', 'SID951375501659'),
('+919279486768', 'SID951375948349'),
('+917081560206', 'SSF2763941'),
('+918148625705', 'SSF2800499'),
('+919341812898', 'SSF2769503'),
('+916205215141', 'SSF6055824'),
('+916268191822', 'SSF3611319'),
('+916264769729', 'SSF6283438'),
('+916393145252', 'SID951374667001'),
('+917974762314', 'SSF6068802'),
('+917091089269', 'SSF6006509'),
('+917292828321', 'SSF5945783'),
('+917079411295', 'SSF3758118'),
('+917489851749', 'SSF6039369'),
('+917001306403', 'SID951372997940'),
('+917869767075', 'SSF5897003'),
('+917067734758', 'SSF6016007'),
('+917300916684', 'SSF3738477'),
('+917480965443', 'SSF6251514'),
('+918296971631', 'SSF6083141'),
('+918226074838', 'SSF3998636'),
('+918757531295', 'SSF6236643'),
('+918789739812', 'SSF6057597'),
('+919198255897', 'SSF3595305'),
('+919102373663', 'SSF6105986'),
('+919793957284', 'SSF6013458'),
('+919303944470', 'SSF6015985'),
('+919905413611', 'SSF6092382'),
('+919399031948', 'SSF5942149'),
('+919955234941', 'SSF3911452'),
('+919341623019', 'SSF3861013'),
('+919065104879', 'SSF6155589'),
('+919752634992', 'SSF5893210'),
('+919871960480', 'SSF6017965'),
('+916264923821', 'CID261401204'),
('+918863836064', 'SID951373291356'),
('+917485054561', 'SID951374813702'),
('+917765067700', 'SID951373185399'),
('+917992044258', 'SSF2462046'),
('+917318536472', 'SSF2757194'),
('+917368848361', 'SSF2744694'),
('+917898003470', 'SSF2665267'),
('+918780029965', 'SSF2907151'),
('+918092205131', 'SSF2405855'),
('+919628533049', 'SSF2771190'),
('+919693225847', 'SSF2511650'),
('+919352116031', 'SID951376057640'),
('+919955593948', 'SSF2810595'),
('+916203276748', 'SSF3935057'),
('+916287775928', 'SSF5629195'),
('+916391637343', 'SSF5845862'),
('+916269484303', 'SSF5807345'),
('+916260320796', 'SSF5627715'),
('+917704054244', 'SSF3717126'),
('+917979891651', 'SSF5655034'),
('+917676128741', 'SSF5861807'),
('+917633939843', 'SSF5943380'),
('+917488122427', 'SSF5835610'),
('+917034963918', 'SSF5870504'),
('+917859001728', 'SSF5855631'),
('+917602490729', 'SSF5882027'),
('+917050700559', 'SSF5870541'),
('+917643908038', 'SSF4074828'),
('+917857072147', 'SSF3609325'),
('+917488230421', 'SSF5939904'),
('+917489332579', 'SSF5816994'),
('+917828835830', 'SSF6273558'),
('+917999123352', 'SSF3497017'),
('+917257070920', 'SSF3008169'),
('+917061923552', 'SSF5773016'),
('+917845900519', 'SSF5880896'),
('+917050717075', 'SSF5685569'),
('+917632075881', 'SSF6256882'),
('+917479832611', 'SSF5560383'),
('+917070820735', 'SSF5618060'),
('+917808926358', 'SSF5936576'),
('+917317301059', 'SSF5844946'),
('+917275322104', 'SSF5835453'),
('+917645924606', 'SSF5926131'),
('+918660021267', 'SSF5776565'),
('+918294036878', 'SSF4000259'),
('+918809924806', 'SSF3901373'),
('+918276824289', 'SSF3900682'),
('+918409896463', 'SSF5845401'),
('+918541022606', 'SSF5605908'),
('+918271018471', 'SSF5611985'),
('+918252460769', 'SSF5858632'),
('+918757701349', 'SSF5629807'),
('+918434712420', 'SSF3499581'),
('+918955156762', 'SSF5862250'),
('+918982933314', 'SSF3826019'),
('+918226887103', 'SSF5844563'),
('+918819853588', 'SSF3834245'),
('+919302800073', 'SSF5743015'),
('+919106580750', 'SSF5741439'),
('+919341345969', 'SSF5866448'),
('+919234187433', 'SSF6051225'),
('+919798177003', 'SSF6112509'),
('+919341455383', 'SSF5835161'),
('+919931184262', 'SSF5912820'),
('+919297834240', 'SSF3430680'),
('+919244684837', 'SSF3839181'),
('+919508558347', 'SSF5880718'),
('+919572859393', 'SSF5930216'),
('+919631317441', 'SSF4076790'),
('+919353254953', 'SSF2897180'),
('+919905830272', 'SSF5940655'),
('+919241103307', 'SSF5935538'),
('+919889061068', 'SSF3644297'),
('+919279339419', 'SSF5939126'),
('+919162874226', 'SSF5629870'),
('+919111038815', 'SSF5833188'),
('+919341719767', 'SSF5818507'),
('+919060810386', 'SSF5618456'),
('+919511675895', 'SSF5630945'),
('+919519213867', 'SSF5843149'),
('+919576253571', 'SSF5647330'),
('+919835825113', 'SSF5630021'),
('+919662892511', 'SSF5871364'),
('+919753072710', 'SSF4109776'),
('+919651763598', 'SSF5834196'),
('+919905728680', 'SSF5620436'),
('+919343560086', 'SSF5789224'),
('+919063282096', 'SSF5800112'),
('+917480053016', 'SSF5955105'),
('+917707030486', 'SSF6089721'),
('+916379786890', 'SSF5756160'),
('+918541015997', 'SSF6070135'),
('+918529915102', 'SSF6079212'),
('+919031304442', 'SSF5668596'),
('+918962703191', 'CID084702121'),
('+916201440922', 'SSF6180856'),
('+917667925944', 'SID951373502278'),
('+917985989030', 'SSF2769844'),
('+917408770967', 'SID951376078426'),
('+917091002721', 'SSF2792270'),
('+917320822108', 'SID951376131992'),
('+918881113276', 'SSF2745675'),
('+919508253563', 'SSF5179187'),
('+916261322596', 'SSF3581851'),
('+916260341599', 'SSF3836661'),
('+917974322381', 'SSF4882198'),
('+917398655371', 'SSF3586380'),
('+917004027828', 'SSF6090125'),
('+919102564544', 'SSF5793230'),
('+919060971686', 'SSF5509495'),
('+919754672206', 'SID951375491861'),
('+919335563914', 'SSF3036186'),
('+919770503755', 'SSF5574669'),
('+917562833118', 'SSF5919306'),
('+919749167367', 'SID2125643177'),
('+916204796531', 'SSF5335489'),
('+916204619713', 'SSF3422772'),
('+916267262520', 'SID951374385055'),
('+916201813918', 'SSF6012430'),
('+916204733445', 'SSF3811087'),
('+917633077201', 'SSF5335750'),
('+917761826405', 'SID951375008042'),
('+917463872680', 'SSF2995935'),
('+917543048337', 'SSF5517439'),
('+917549296239', 'SSF5616292'),
('+918416819989', 'SSF3431789'),
('+918229868202', 'SSF5922741'),
('+919244572965', 'SSF5348951'),
('+919122352154', 'SSF5535009'),
('+919708406840', 'SSF5947563'),
('+919872863045', 'SSF5954691'),
('+919773724145', 'SSF3274677'),
('+919990032814', 'SSF6001256'),
('+919693182697', 'SSF6000038'),
('+919525726318', 'SSF5940912'),
('+919244738519', 'SSF5549421'),
('+919399837140', 'SSF5873937'),
('+919006241787', 'SSF5397870'),
('+919771002594', 'SSF3944673'),
('+919693913642', 'SSF5384512'),
('+919153661186', 'SSF5840998'),
('+918176047533', 'SSF4889115'),
('+918808097051', 'SSF4717632'),
('+917667324017', 'SSF5357278'),
('+919534118161', 'SSF5488665'),
('+916379370295', 'SSF4934318'),
('+916201249320', 'SSF2371475'),
('+917023800588', 'SSF5423981'),
('+917610680173', 'SSF2414769'),
('+917898932997', 'SSF4908462'),
('+917091608212', 'SSF5350147'),
('+917050101180', 'SSF5508535'),
('+917999548232', 'SSF5281636'),
('+917879129563', 'SSF4903824'),
('+917697035640', 'SSF4934810'),
('+917987072759', 'SSF5533194'),
('+917061306645', 'SSF4878645'),
('+917250652567', 'SSF5483793'),
('+917488698564', 'SSF5465605'),
('+917488523392', 'SSF5389199'),
('+917631460437', 'SSF5413655'),
('+918145724026', 'SSF5535385'),
('+918000451124', 'SSF5437471'),
('+918815798113', 'SSF5177095'),
('+918815915149', 'SSF5403745'),
('+918789008509', 'SSF3042028'),
('+918360940772', 'SID951375729271'),
('+918084241190', 'SSF5510042'),
('+918521520337', 'SSF5389060'),
('+918542136578', 'SID951375793123'),
('+918602718614', 'SSF5574654'),
('+918521862397', 'SSF4776805'),
('+919810481264', 'SSF3695893'),
('+919617071987', 'SSF3059449'),
('+919508597551', 'SSF4878474'),
('+919926926423', 'SSF4926607'),
('+919576785586', 'SSF4882177'),
('+919153552802', 'SSF4901798'),
('+919617434570', 'SSF4927325'),
('+919343485689', 'SSF5543001'),
('+919399040940', 'SSF5510243'),
('+919770048028', 'SSF3445149'),
('+919631681511', 'SSF5389210'),
('+919905551830', 'SSF5339514'),
('+919301257863', 'SSF4940459'),
('+919328439894', 'SSF5439577'),
('+916398749629', 'SSF5076374'),
('+917462095419', 'SSF5999705'),
('+919693428168', 'SSF6124804'),
('+918382994466', 'SSF5920042'),
('+916287807346', 'SSF5917759'),
('+917633838928', 'SSF5430049'),
('+916377367580', 'SSF5041511'),
('+916206502439', 'SSF4736384'),
('+916206470089', 'SSF4726365'),
('+916268350851', 'SSF5181738'),
('+916367068115', 'SSF5505463'),
('+916264260498', 'SSF3086452'),
('+916205891367', 'SID951376113237'),
('+916261314174', 'SSF5308463'),
('+917427819625', 'SID951375223383'),
('+917427890801', 'SSF4748031'),
('+917740994507', 'SSF2819644'),
('+917209298686', 'SSF4733313'),
('+917091578921', 'SSF2616187'),
('+917050840894', 'SSF4854347'),
('+917973357244', 'SSF4731799'),
('+917004966429', 'SSF2450315'),
('+917256981877', 'SSF4668756'),
('+918696885681', 'SSF5151059'),
('+918690261512', 'SID951375153409'),
('+918890812483', 'SSF5080121'),
('+918002354983', 'SSF2395238'),
('+918757738796', 'SID951373336965'),
('+918294190825', 'SSF4715649'),
('+918406029181', 'SSF5198080'),
('+918824863774', 'SSF5326503'),
('+918302948368', 'SSF5266817'),
('+919342692686', 'SSF5130852'),
('+919631264238', 'SID951375437351'),
('+919521515702', 'SID951375185878'),
('+919664341677', 'SSF5133442'),
('+919955385223', 'SSF3479362'),
('+919353588589', 'SSF5403649'),
('+919153472592', 'SSF5259550'),
('+919835210490', 'SSF5259431'),
('+919142472950', 'SSF5259648'),
('+919631152550', 'SSF4423229'),
('+919572831858', 'SSF5045061'),
('+919576064955', 'SSF4689707'),
('+919302338491', 'SSF4846491'),
('+919878755688', 'SID951376091921'),
('+919875719313', 'SSF5327637'),
('+919661636074', 'SSF5269978'),
('+919097863512', 'SSF5134741'),
('+916394747844', 'SSF3925038'),
('+917481926095', 'SSF5717757'),
('+919315607327', 'SSF5786088'),
('+919348158870', 'SSF5670057'),
('+919235861297', 'SSF5801769'),
('+916375525340', 'SSF4778932'),
('+916350468409', 'SSF4501090'),
('+916261391515', 'SSF4800947'),
('+917368949592', 'SSF4031904'),
('+917856975987', 'SSF4369086'),
('+917737323937', 'SSF4758087'),
('+917231031513', 'SID951375435673'),
('+917461062528', 'SSF4796365'),
('+917070656570', 'SSF4743508'),
('+917878029622', 'SSF4788404'),
('+917851852450', 'SSF2401081'),
('+918825349956', 'SSF4800406'),
('+918000167190', 'SSF2742860'),
('+918058374348', 'SSF4288153'),
('+918603585007', 'SSF4781542'),
('+918005805832', 'SSF4421404'),
('+919610754868', 'SSF4215609'),
('+919098399794', 'SSF4197347'),
('+919347441690', 'SSF2428309'),
('+919835374451', 'SSF4342667'),
('+919131841208', 'SSF4727847'),
('+919784116194', 'SSF2553436'),
('+919643655479', 'SSF4407309'),
('+919798240128', 'SID951376117233'),
('+916261299527', 'SSF4108709'),
('+916367497358', 'SSF3383455'),
('+916203347525', 'SSF4746676'),
('+917023110564', 'SSF3314683'),
('+917742974322', 'SID951375192512'),
('+917067350514', 'SSF2985619'),
('+917250109621', 'SSF4138840'),
('+917563049066', 'SSF4501476'),
('+919509735937', 'SSF4666741'),
('+919024759617', 'SSF4219900'),
('+919352864985', 'SSF3994271'),
('+919631104121', 'SSF4441636'),
('+919636724354', 'SSF4094350'),
('+919835498928', 'SSF4629163'),
('+919907820007', 'SSF2459515'),
('+919301658809', 'SSF4100104'),
('+917061653753', 'SSF4262795'),
('+917733878154', 'SSF2680753'),
('+917805879775', 'SSF3053369'),
('+918094521822', 'SSF2393626'),
('+919079977109', 'SSF4008557'),
('+919660693647', 'SSF3979084'),
('+916378448235', 'SSF3813096'),
('+917425062928', 'SSF3931735'),
('+918114409091', 'SSF4246538'),
('+919351042701', 'SSF3919420'),
('+919407905572', 'SSF2789535'),
('+917850894271', 'SSF4039240'),
('+917877331342', 'SSF2560683'),
('+917404955943', 'SSF4080802'),
('+918676860667', 'SSF3668607'),
('+918504869478', 'SSF3763747'),
('+918219999467', 'SSF2561714'),
('+918879451313', 'SSF3765242'),
('+919950245887', 'SSF3403849'),
('+919351626803', 'SSF3981650'),
('+919558166295', 'SSF3801297'),
('+919856328437', 'SSF3772584'),
('+919982670092', 'SSF4079201'),
('+916294359838', 'SSF3326945'),
('+917023016843', 'SSF3403917'),
('+918946532864', 'SSF3643594'),
('+919766795884', 'SSF3509646'),
('+919487876949', 'SSF3316971'),
('+919303010306', 'SID951373741683'),
('+916261144708', 'SID951374764687'),
('+917089125141', 'SSF2969151'),
('+918827804293', 'SSF2303229'),
('+917722857103', 'SSF4169710'),
('+918103622282', 'SSF3415874'),
('+919522510306', 'SSF6028699'),
('+919329724488', 'SSF3169037'),
('+919131749705', 'SSF3648871'),
('+919310523893', 'SSF5859759'),
('+918959108719', 'SSF3986836'),
('+916204234736', 'SSF4064166'),
('+918434641059', 'SSF2679900'),
('+919829098697', 'SSF2677472'),
('+919771338272', 'SSF5961544'),
('+919813806361', 'SID951375995121'),
('+917452451310', 'SSF2916695'),
('+917631609385', 'SSF3303650'),
('+917563903023', 'SSF3350217'),
('+919652484588', 'SSF3343724'),
('+919615787578', 'SSF3383814'),
('+919672717848', 'SSF3343679'),
('+919955753588', 'SSF3352686'),
('+919671575487', 'SSF3343511'),
('+919675248488', 'SSF3343487'),
('+919286456465', 'SSF2607157'),
('+918809836180', 'SSF3307037'),
('+919671245848', 'SSF3383815'),
('+919945438012', 'SSF3352858'),
('+919942301358', 'SSF3352687'),
('+919483845348', 'SSF3352857'),
('+919636659557', 'SSF3349320'),
('+919303876584', 'SSF4039138'),
('+919780115242', 'SSF3022128'),
('+919835606624', 'CID263600403'),
('+918319955547', 'CID076602179'),
('+918824338057', 'SID951373404599'),
('+916263534301', 'SID951375365362'),
('+919119350245', 'SSF2986380'),
('+919174043419', 'SID951375627061'),
('+918294461114', 'SSF3959911'),
('+919241561671', 'SSF2965392'),
('+918120441122', 'SID951375610736'),
('+916265428520', 'SID951375496489'),
('+919926979733', 'SID951375837310'),
('+918539985514', 'SID951373866516'),
('+917668780294', 'SSF4757432'),
('+919554111620', 'SSF2866322'),
('+917739975602', 'SID951375827139'),
('+919982800711', 'SSF2554998'),
('+919752949056', 'SID951375010877'),
('+916266939363', 'SID951375405506'),
('+917067865890', 'SSF5101017'),
('+918797827619', 'SSF3275776'),
('+919691012360', 'SID951373621490'),
('+918438976313', 'SID951374906276'),
('+916263263657', 'SID2125625115'),
('+919589300360', 'SID951372970555'),
('+919369824367', 'SID951374341199'),
('+919507523730', 'SID951373936711'),
('+919572515865', 'SSF6149681'),
('+917742377992', 'SID951374872357'),
('+918969581909', 'SSF5786769'),
('+917771043326', 'SID951373438422'),
('+917974787994', 'SSF3970259'),
('+918839108581', 'SSF4775107'),
('+918826746657', 'SID951375644840'),
('+916202014988', 'SSF2837708'),
('+917869297503', 'SSF2971123'),
('+917766023082', 'SSF2575475'),
('+918434891377', 'SSF5393796'),
('+916201393695', 'SSF3423338'),
('+919523153257', 'SSF5038869'),
('+918827177970', 'SSF2987095'),
('+917067778617', 'SSF3347418'),
('+919868648448', 'SSF3315698'),
('+919113913148', 'SSF2572482'),
('+918957088672', 'SSF2454810'),
('+917742777093', 'SSF4073142'),
('+918875150485', 'SID951374148428'),
('+918949581802', 'SSF2296676'),
('+919691589082', 'SSF3689042'),
('+919301251035', 'SSF4283288'),
('+916262356070', 'SSF3077445'),
('+919827144926', 'SID951374047804'),
('+917772991264', 'SSF3647046'),
('+919340269354', 'SSF4879548'),
('+918825176891', 'SSF3194843'),
('+919955356748', 'SSF2867504'),
('+918738824012', 'SSF3790119'),
('+919398935631', 'SSF2894363'),
('+919907689045', 'SSF4759631'),
('+917069307433', 'SSF4451114'),
('+916350253304', 'SSF2780358'),
('+918209432679', 'SSF3111929'),
('+919098154413', 'SSF2763271'),
('+917719635330', 'SSF5305910'),
('+919950548414', 'SSF4012788'),
('+919340937892', 'SSF2836058'),
('+917999714661', 'SID951374013204'),
('+919174857213', 'SID951375256610'),
('+919559008418', 'SSF2366312'),
('+919171894982', 'SSF2969001'),
('+918292356728', 'SSF5410921'),
('+917804038298', 'SID951375026130'),
('+917979834354', 'SID951373508606'),
('+919363349065', 'SSF3617218'),
('+919317297705', 'SSF5471535'),
('+919060209101', 'SSF2713319'),
('+918112238126', 'SSF4080351'),
('+918120549528', 'SSF3590635'),
('+918946346484', 'SID2125075955'),
('+917306493537', 'SID951374656161'),
('+919800682905', 'SSF3154211'),
('+918149816904', 'SSF2598776'),
('+919165940236', 'SID951374986406'),
('+917061635420', 'SSF5096912'),
('+919955756371', 'SSF5610370'),
('+919770756554', 'SSF3729678'),
('+919755717056', 'CID135501294'),
('+919031397038', 'CID951376207143'),
('+919335758211', 'SSF4274255'),
('+917617288713', 'SSF4045295'),
('+917061543081', 'SSF2801436'),
('+916263362177', 'SSF3124952'),
('+918656636988', 'SSF3422250'),
('+919279258144', 'SSF4662078'),
('+919754728397', 'SSF3656626'),
('+918269543975', 'SSF3728917'),
('+919985698866', 'SID951374345838'),
('+917805023667', 'SID2125218946'),
('+919546548384', 'SID951375235986'),
('+916268984871', 'SID951376054531'),
('+919534679348', 'SSF3103070'),
('+919653943980', 'SSF4067850'),
('+917667815413', 'SSF4089550'),
('+919264215073', 'SID951375353515'),
('+919399406059', 'SSF4354184'),
('+918449119809', 'SSF5940689'),
('+919005092820', 'SSF2403422'),
('+918797719520', 'SSF4338636'),
('+919784142609', 'SID951375112655'),
('+918120308328', 'SID2125347584'),
('+917806013656', 'SSF3046416'),
('+917000191490', 'SSF3114140'),
('+919179526286', 'SSF2690673'),
('+918602982072', 'CID076112490'),
('+917677717572', 'SID951375961326'),
('+919636415635', 'SID951374768869'),
('+917354225059', 'SSF3810829'),
('+919724861231', 'SSF4898497'),
('+918103399564', 'SSF3496415'),
('+919982792885', 'SSF3189799'),
('+917697961702', 'SID951375785042'),
('+917250631897', 'SSF3917756'),
('+918577916921', 'SSF5742395'),
('+919797667337', 'SSF2700390'),
('+919163477809', 'SSF4747889'),
('+917667910263', 'SSF3170129'),
('+919241362745', 'SSF5791961'),
('+916266709869', 'SID951374201496'),
('+919424212671', 'CID191605751'),
('+918292647553', 'SSF3250030'),
('+919303142220', 'SID951373519960'),
('+916205953899', 'SID951375543687'),
('+917723937973', 'SID951375308289'),
('+917981429156', 'SSF2578684'),
('+917388908146', 'SSF2865605'),
('+917764922411', 'SSF2508614'),
('+917492813747', 'SSF2890998'),
('+919508525781', 'SSF2755257'),
('+919153056052', 'SSF2433136'),
('+919167723962', 'SSF2819722'),
('+916206676910', 'SSF6160288'),
('+916299230194', 'SSF3120394'),
('+916299154318', 'SSF3800995'),
('+916206124532', 'SSF6207264'),
('+916239757968', 'SSF5856099'),
('+916394567072', 'SSF6157247'),
('+916393002745', 'SSF6137950'),
('+916207858405', 'SSF6013687'),
('+916394747521', 'SSF6140859'),
('+917905305923', 'SSF3179632'),
('+917888501138', 'SSF6160196'),
('+917268951401', 'SSF6221211'),
('+917371835363', 'SSF6164360'),
('+917563067214', 'SSF6160129'),
('+917827985815', 'SSF6196081'),
('+917070146395', 'SSF6191998'),
('+917209830363', 'SSF2443159'),
('+917095728893', 'SSF6249499'),
('+918462060002', 'SSF6198970'),
('+918292822549', 'SSF6192253'),
('+918700878024', 'SSF6179517'),
('+918210381323', 'SSF6262205'),
('+918698070912', 'SSF6193648'),
('+918789810874', 'SSF3863140'),
('+918962185385', 'SSF6159548'),
('+918269548270', 'SSF4413680'),
('+918177086137', 'SSF6200403'),
('+918102186442', 'SSF4213713'),
('+918102293743', 'SSF3357171'),
('+918271522883', 'SSF6156912'),
('+918815850269', 'SSF6229930'),
('+918210076612', 'SSF6199415'),
('+919098742781', 'SSF4071618'),
('+919098824134', 'SSF3473930'),
('+919199311921', 'SSF6160928'),
('+919125891072', 'SSF3682502'),
('+919608850038', 'SSF3626033'),
('+919693141545', 'SSF3721396'),
('+919120016082', 'SSF6130424'),
('+919685032246', 'SSF6191775'),
('+919546201276', 'SSF4048555'),
('+919329091779', 'SSF4056853'),
('+919554560224', 'SSF6275396'),
('+919301389072', 'SSF5828911'),
('+919919241886', 'SSF6137708'),
('+919102678435', 'SID951375603684'),
('+917909412059', 'SID951374299634'),
('+916201042871', 'SID951375451568'),
('+919695833079', 'SID951374581214'),
('+916350393001', 'SID951376057299'),
('+918699756819', 'SSF2337771'),
('+916291763098', 'SSF5840958'),
('+916202194370', 'SSF5840366'),
('+917489266179', 'SSF6182436'),
('+917491843947', 'SSF6196755'),
('+917986033390', 'SSF6180506'),
('+918637032747', 'SSF4243035'),
('+918409745149', 'SSF5863750'),
('+919984211253', 'SSF3140445'),
('+919155685155', 'SSF6067002'),
('+919973573116', 'SSF3283640'),
('+919301205162', 'SSF6337528'),
('+919341620360', 'SSF5939728'),
('+919669813051', 'CID224400975'),
('+916287920034', 'SSF6051461'),
('+917323032072', 'SSF6295101'),
('+917485002561', 'SSF6386237'),
('+919872780441', 'SSF6227379'),
('+918051941911', 'SSF6128238'),
('+916261010521', 'SID951373394141'),
('+919234045720', 'SID951374919345'),
('+919142586883', 'SID951374708646'),
('+917050827852', 'SID951376033632'),
('+917209959646', 'SSF2687069'),
('+917667429881', 'SSF2602573'),
('+917050808211', 'SSF6171645'),
('+917081987207', 'SSF5741175'),
('+918051193656', 'SSF4814418'),
('+919905314859', 'CID951376208656'),
('+919611007645', 'SSF6083028'),
('+919031877922', 'SSF5834057'),
('+919503273138', 'SSF4470778'),
('+916265519977', 'SID951374781090'),
('+916204093026', 'SSF4510080'),
('+916266201583', 'SSF6063356'),
('+917673018512', 'SSF3257274'),
('+917283042466', 'SSF6057361'),
('+917398399186', 'SSF5304421'),
('+917250584390', 'SSF3254810'),
('+917766886186', 'SSF5484542'),
('+917742103291', 'SSF5358274'),
('+918271627674', 'SSF5973921'),
('+918756789139', 'SSF6027360'),
('+918390338988', 'SSF5949064'),
('+918887215442', 'SSF5557719'),
('+918849999706', 'SSF6093560'),
('+918294615232', 'SSF6041167'),
('+919883159816', 'SSF5890258'),
('+919060092441', 'SSF5966034'),
('+919993074595', 'SSF3089650'),
('+919219150916', 'SSF5582836'),
('+919369382076', 'SSF5684306'),
('+919460555028', 'SSF3509143'),
('+919153339424', 'SSF6030649'),
('+919798192258', 'SSF6017866'),
('+919534874121', 'SSF6102382'),
('+919304734654', 'SSF3784663'),
('+919782966477', 'SSF5516790'),
('+918726839788', 'SSF4842063'),
('+917485885860', 'SSF4495686'),
('+918789381972', 'SSF6104384'),
('+916392723883', 'SSF4344427'),
('+919935448317', 'SSF6193071'),
('+918002941455', 'SID2125271923'),
('+916202940522', 'SSF5649643'),
('+917067191154', 'SSF2306607'),
('+917645994533', 'SSF3367992'),
('+917665685706', 'SSF3385086'),
('+918539818487', 'SSF5346758'),
('+918340101137', 'SSF3537642'),
('+918102661869', 'SSF5817876'),
('+918292083176', 'SID951374614672'),
('+918797675523', 'SSF5843946'),
('+919351569053', 'SSF3188003'),
('+919340116028', 'SID951375924459'),
('+919305899238', 'SID951374685913'),
('+919905071602', 'SSF3794396'),
('+919060007250', 'SSF5885997'),
('+919199197910', 'SSF4466415'),
('+919931644978', 'SSF5939981'),
('+919817748178', 'SSF2959593'),
('+919803526781', 'SSF6106626'),
('+919334120221', 'SSF2612837'),
('+919341624194', 'SSF3510801'),
('+919661306645', 'SSF4370104'),
('+919117451834', 'SSF6095514'),
('+916266849581', 'SSF3602884'),
('+919546359359', 'SSF5408613'),
('+917398486785', 'SSF5049249'),
('+919330430300', 'SSF5420043'),
('+917602211968', 'SSF4353707'),
('+917070964189', 'SSF4892558'),
('+918757376924', 'SSF4556793'),
('+918827551610', 'SID2125280481'),
('+916268294735', 'SSF2365088'),
('+916267024183', 'SSF5323829'),
('+916266941077', 'SSF5177496'),
('+916261564027', 'SSF5280755'),
('+916294949949', 'SID951375734540'),
('+916287252565', 'SSF5172808'),
('+916268091739', 'SSF2440446'),
('+916264894067', 'SSF5282851'),
('+917728884023', 'SID951375758177'),
('+917000503518', 'SSF3513112'),
('+917568101563', 'SSF5159132'),
('+917987632660', 'SSF3719161'),
('+917987733655', 'SSF3477510'),
('+917426878719', 'SSF5406309'),
('+917742102918', 'SID951374860368'),
('+917541938242', 'SSF5638868'),
('+917782019044', 'SSF2450321'),
('+917049335415', 'SSF5639272'),
('+917717759164', 'SSF5639767'),
('+917874350010', 'SID951375088617'),
('+917257904998', 'SSF2409409'),
('+917033662215', 'SSF5152104'),
('+917728920775', 'SSF5143370'),
('+917209992850', 'SSF5123237'),
('+917879939734', 'SSF4831221'),
('+918233897827', 'SSF5223351'),
('+918305451876', 'SSF5138767'),
('+918955223543', 'SSF5386545'),
('+918529646168', 'SSF5158932'),
('+918948798736', 'SSF5759770'),
('+918890054426', 'SSF5204768'),
('+918824270753', 'SSF5256236'),
('+918817892034', 'SSF5137933'),
('+918409268126', 'SSF5771454'),
('+918292608331', 'SSF4483259'),
('+918271228472', 'SSF5202915'),
('+919652525898', 'SID951374328940'),
('+919509092258', 'SSF5289193'),
('+919329131299', 'SSF3080436'),
('+919624734102', 'SSF5274037'),
('+919256674861', 'SSF5217917'),
('+919572332911', 'SSF5227470'),
('+919522754701', 'SSF5345256'),
('+919693382443', 'SSF5143152'),
('+919009629251', 'SSF3929014'),
('+919113460661', 'SSF5122666'),
('+919304192231', 'SSF5296196'),
('+919608909754', 'SID951375089421'),
('+919636679820', 'SSF5137059'),
('+919219811656', 'SSF5058962'),
('+919199179965', 'SSF5177301'),
('+919935073978', 'SSF3281269'),
('+919241154157', 'SSF5062576'),
('+919102554518', 'SSF3048972'),
('+919351449250', 'SSF5118820'),
('+919508715448', 'SSF5165611'),
('+919325146629', 'SID951375152240'),
('+919279028711', 'SSF5352492'),
('+919279134138', 'SSF5120793'),
('+919572419855', 'SSF5176551'),
('+919631617855', 'SSF5126112'),
('+919244745206', 'SSF5089427'),
('+919608173907', 'SSF2475787'),
('+918210345244', 'SSF6027407'),
('+919534665753', 'SSF4587042'),
('+916299803168', 'SSF6258923'),
('+916281638871', 'SSF5825336'),
('+919369187044', 'SSF3951240'),
('+916352399344', 'SSF4804439'),
('+916377103491', 'SSF3611118'),
('+916367550260', 'SSF4317189'),
('+916209454946', 'SSF5700976'),
('+916367460870', 'SSF4913075'),
('+916377566686', 'SSF5080562'),
('+916383967484', 'SSF4983049'),
('+916261504895', 'SID951375489800'),
('+917740904539', 'SSF3086524'),
('+917247464750', 'SSF4921353'),
('+917742027388', 'SID951374693257'),
('+917964656526', 'SID951376150062'),
('+917737865086', 'SSF5506630'),
('+917851988408', 'SSF5258203'),
('+917050247881', 'SSF5665372'),
('+917357561305', 'SID951374703136'),
('+917484860298', 'SSF4981945'),
('+917061132846', 'SSF4960718'),
('+917742792992', 'SSF4989494'),
('+918209580932', 'SSF5098463'),
('+918789559764', 'SID951375936858'),
('+918239039310', 'SSF5101760'),
('+918757221603', 'SID951376200773'),
('+918969987045', 'SSF4962668'),
('+918709915525', 'SSF5090153'),
('+918603745412', 'SSF4941809'),
('+918287474931', 'SSF4889854'),
('+918949448268', 'SSF4939404'),
('+918468012612', 'SSF4004433'),
('+918797153902', 'SSF3672447'),
('+919785428252', 'SSF4906925'),
('+919285524063', 'SSF4888643'),
('+919602253896', 'SID951374754406'),
('+919241735096', 'SSF5180222'),
('+919216845711', 'SSF3085191'),
('+919302386087', 'SSF3093420'),
('+919576223498', 'SSF5606687'),
('+919507662654', 'SSF5556115'),
('+919241405137', 'SSF5113373'),
('+919549413116', 'SSF3077167'),
('+919684948675', 'SID951376025898'),
('+919329435726', 'SSF3633001'),
('+919559551441', 'SSF2519439'),
('+919877216654', 'SSF4880317'),
('+919001604644', 'SSF5665346'),
('+919351298216', 'SSF3044315'),
('+919572192579', 'SID951375618762'),
('+919935955899', 'SSF3037590'),
('+919905783400', 'SSF5591465'),
('+919798625908', 'SSF4663433'),
('+917093748850', 'SSF5583372'),
('+919999206046', 'SSF5583502'),
('+916378369744', 'SSF4800253'),
('+917727992687', 'SSF4803368'),
('+917383454523', 'SSF4819584'),
('+918955926374', 'SSF4701886'),
('+919989589494', 'SSF3159952'),
('+919770281670', 'SSF4773795'),
('+916576758575', 'SID951375322969'),
('+916376682036', 'SSF4702924'),
('+916265878070', 'SSF4459878'),
('+916377012290', 'SSF4684066'),
('+917348737835', 'SSF3104617'),
('+917070536926', 'SSF4051505'),
('+917737060253', 'SSF4391287'),
('+917631088953', 'SSF4978714'),
('+917033132891', 'SSF4567774'),
('+917877065526', 'SSF4400512'),
('+917690817212', 'SSF4390674'),
('+917067044758', 'SSF5009247'),
('+918407828028', 'SID951376161008'),
('+918728443579', 'SID951375964490'),
('+918560854625', 'SSF4520715'),
('+918809656619', 'SSF4589350'),
('+918603227271', 'SSF4615445'),
('+918935995981', 'SSF3985232'),
('+918686876898', 'SID951374843799'),
('+918949140272', 'SSF4457193'),
('+918054865459', 'SID951375652254'),
('+918107794263', 'SSF4931850'),
('+919783346294', 'SSF4260505'),
('+919023929392', 'SSF3440860'),
('+919343218816', 'SSF4555757'),
('+919660890134', 'SID951375355914'),
('+919653819066', 'SSF5006047'),
('+919549841907', 'SSF4565223'),
('+919024743984', 'SSF5006001'),
('+919939127112', 'SID951375514011'),
('+919023827564', 'SSF4405670'),
('+919691423826', 'SSF4459638'),
('+919313379077', 'SID951375443276'),
('+919631893303', 'SSF3117560'),
('+919784892186', 'SSF4591415'),
('+919244351543', 'SSF5057193'),
('+919523726771', 'SID951374815661'),
('+919216579962', 'SSF4633144'),
('+919329813983', 'SID951375603941'),
('+919340089449', 'SSF4692459'),
('+919352746004', 'SSF4951561'),
('+916378800884', 'SSF3820606'),
('+916378841881', 'SSF4408222'),
('+916287835277', 'SSF2757364'),
('+917489769244', 'SSF4400583'),
('+917033554538', 'SSF4494724'),
('+917250478144', 'SSF4388113'),
('+917542871500', 'SSF4341326'),
('+917054075319', 'SSF4400531'),
('+917878317668', 'SSF4395588'),
('+917878610988', 'SID951374814011'),
('+918709420882', 'SID2125753113'),
('+918290788413', 'SSF4519203'),
('+918739825963', 'SSF3235015'),
('+918852902314', 'SSF4412389'),
('+918955624470', 'SSF3233305'),
('+918349053496', 'SSF4443832'),
('+918226008704', 'SSF4443718'),
('+918824728454', 'SSF4489012'),
('+918290339375', 'SSF4225122'),
('+918290783187', 'SSF4439200'),
('+919521019797', 'SSF4335697'),
('+919893319266', 'SSF4529702'),
('+919571480046', 'SSF4294078'),
('+919693225856', 'SID951373079790'),
('+919691628554', 'SSF3643299'),
('+919256978748', 'SSF4395477'),
('+919799779725', 'SSF2683887'),
('+919302218891', 'SSF4437236'),
('+919868468467', 'SID951375235457'),
('+919776948876', 'SID951375727688'),
('+919587769740', 'SSF4384533'),
('+919304833163', 'SSF4361131'),
('+917791828951', 'SSF4096013'),
('+917357978923', 'SSF4057672'),
('+917665824878', 'SSF4244821'),
('+918809740516', 'SID951374235944'),
('+918386086932', 'SSF4514118'),
('+918290070912', 'SSF4152361'),
('+919794635682', 'SSF3116362'),
('+919024531712', 'SSF4098666'),
('+919660330046', 'SSF4302327'),
('+919313786532', 'SSF4009802'),
('+919467549797', 'SSF3458587'),
('+919649148797', 'SSF4147619'),
('+919950797350', 'SSF4328376'),
('+919982389752', 'SID951376065348'),
('+919875724473', 'SSF4100161'),
('+917266838521', 'SSF2282077'),
('+917728910847', 'SSF4097466'),
('+917849825227', 'SSF3931780'),
('+917891759276', 'SSF4012783'),
('+917340591326', 'SSF3933215'),
('+918290535477', 'SID951375975047'),
('+918824924698', 'SSF4205166'),
('+919414826113', 'SSF4378145'),
('+919602886502', 'SSF4191724'),
('+919549815878', 'SSF3975349'),
('+919509239652', 'SSF4178630'),
('+916288487588', 'SID951376157106'),
('+917725913267', 'SID951375009043'),
('+917461077060', 'SID951374068402'),
('+918000972950', 'SSF3921390'),
('+918432565569', 'SSF4282517'),
('+918502960572', 'SID951375130992'),
('+918852920815', 'SSF3895073'),
('+918546294235', 'SSF3811049'),
('+919696683466', 'SSF3865238'),
('+919660065790', 'SSF3745748'),
('+917549040882', 'SSF2936107'),
('+918572033865', 'SSF2689052'),
('+919955621924', 'SID2125146839'),
('+919935035413', 'SID951374840150'),
('+916201358675', 'SSF2306484'),
('+917257886856', 'SSF2552919'),
('+917004862360', 'SSF2498737'),
('+918969570819', 'SSF2950573'),
('+918629935415', 'SSF2881037'),
('+918602490568', 'SID951376162776'),
('+919263982458', 'SSF2779173'),
('+919835079361', 'SSF2631183'),
('+916205491701', 'SSF6196347'),
('+916267802619', 'SSF3115825'),
('+916261420568', 'SSF4133372'),
('+916390362541', 'SSF6191055'),
('+916204616530', 'SSF3093729'),
('+917665442329', 'SSF3909942'),
('+917974475493', 'SSF3993686'),
('+917209333748', 'SSF6221998'),
('+917019436625', 'SSF6200295'),
('+917654237285', 'SSF3008165'),
('+917739331893', 'SSF6270307'),
('+917068121963', 'SSF5830771'),
('+917869670116', 'SSF6218016'),
('+917666104295', 'SSF6110488'),
('+917302980022', 'SSF6194246'),
('+917354913652', 'SSF6163857'),
('+917209109121', 'SSF6204532'),
('+918305226134', 'SSF5816790'),
('+918942834912', 'SSF6182180'),
('+918434116754', 'SSF3903160'),
('+918968983675', 'SSF6160114'),
('+918577040362', 'SSF6200990'),
('+918102249498', 'SSF5854155'),
('+918400517006', 'SSF6161776'),
('+918817893938', 'SSF6263843'),
('+918769375207', 'SSF5813098'),
('+919770904902', 'SSF3790372'),
('+919508469932', 'SSF4175732'),
('+919835115019', 'SSF6160065'),
('+919244715356', 'SSF4016559'),
('+919430444244', 'SSF6251669'),
('+919870244617', 'SSF6184435'),
('+919279594944', 'SSF4310004'),
('+919241678983', 'SID951373476793'),
('+919131074513', 'SSF4453787'),
('+919721577350', 'SSF6215029'),
('+919244149745', 'SSF5844891'),
('+919301122027', 'SSF6270134'),
('+919118830690', 'SSF6168690'),
('+919340052017', 'SSF3772084'),
('+919050230872', 'CID040215415'),
('+917544091795', 'SID951373666974'),
('+917587474985', 'SID951374554246'),
('+918757430186', 'SID951374734698'),
('+919116162670', 'SID951374320369'),
('+919301343582', 'SID951375895856'),
('+919241593820', 'SID951375621957'),
('+916260732487', 'SSF2697940'),
('+917257818404', 'SSF2554602'),
('+917562035481', 'SSF2857966'),
('+917079016531', 'SSF2883850'),
('+918210411936', 'SSF2809986'),
('+918115572161', 'SSF2284701'),
('+918092829213', 'SSF2810662'),
('+918490969570', 'SID951376142150'),
('+918002776217', 'SSF2417043'),
('+919125795703', 'SSF2631203'),
('+919635189141', 'SSF2886248'),
('+919153772185', 'SSF2498370'),
('+919835512833', 'SSF2763120'),
('+919523212938', 'SSF2729161'),
('+919576092532', 'SSF6194051'),
('+916201708565', 'SSF3478398'),
('+916371266976', 'SSF6025150'),
('+916268640077', 'SSF6122363'),
('+917369026368', 'SSF6044153'),
('+917723842816', 'SSF6053130'),
('+917541993229', 'SSF5839451'),
('+917717723090', 'SSF6043988'),
('+917033164836', 'SSF6023786'),
('+917683824373', 'SSF6007542'),
('+917543894007', 'SSF4286729'),
('+917354558727', 'SSF4135603'),
('+918175815032', 'SSF4526773'),
('+918084473241', 'SSF6135955'),
('+918809590296', 'SSF3269263'),
('+918924849912', 'SSF6126587'),
('+918092266801', 'SSF5986621'),
('+918409513237', 'SSF3065147'),
('+918509854508', 'SSF5838014'),
('+918936072962', 'SID951375544966'),
('+918434906983', 'SID951376019157'),
('+918877872080', 'SSF2965535'),
('+918101002715', 'SSF6247341'),
('+918294875820', 'SSF6292240'),
('+918434988274', 'SSF3301810'),
('+918210423040', 'SSF5650703'),
('+918618510971', 'SSF5971056'),
('+918303745083', 'SSF2942361'),
('+918603483624', 'SSF6076867'),
('+918092805417', 'SSF3459554'),
('+918969232532', 'SSF5649739'),
('+918409797083', 'SSF6098532'),
('+919693584370', 'SSF6143243'),
('+919693638456', 'SSF3811979'),
('+919931968061', 'SSF6186712'),
('+919006897619', 'SSF6066507'),
('+919773827568', 'SSF5839372'),
('+919263101620', 'SSF3024274'),
('+919123462182', 'SSF3189762'),
('+919399493649', 'SSF3962020'),
('+919129112381', 'SSF6008911'),
('+919905233429', 'SSF6135266'),
('+919508781825', 'SSF5831708'),
('+919831095399', 'SSF6086966'),
('+919034381429', 'SSF3066126'),
('+919234383367', 'SSF2945235'),
('+919818920041', 'SSF6026747'),
('+919507868117', 'SSF6140887'),
('+919329540737', 'SSF6073558'),
('+919572534794', 'SSF6148016'),
('+919648235949', 'SSF6269420'),
('+919630411183', 'SSF3681014'),
('+919244535305', 'SSF3516823'),
('+919798641379', 'SSF6138586'),
('+919973619743', 'SSF4699929'),
('+919793758503', 'SSF6288141'),
('+919892071058', 'SSF4814810'),
('+917295030642', 'SID951375695201'),
('+917542820345', 'SSF5757723'),
('+919628545137', 'SSF4081247'),
('+917275895125', 'SSF5731657'),
('+917260054585', 'SSF3760254'),
('+918292897943', 'SSF5297409'),
('+919508616439', 'SSF3634472'),
('+919142028879', 'SSF6072923'),
('+919199012571', 'SSF3442261'),
('+919115673053', 'SSF3638590'),
('+919891993524', 'SSF3757823'),
('+919345480837', 'SSF6023697'),
('+919571520514', 'SSF5821570'),
('+917800700109', 'SSF6008454'),
('+917700852026', 'SSF6091448'),
('+917521811139', 'SSF6175985'),
('+919793285848', 'SSF4506528'),
('+916202091131', 'CID211102423'),
('+916263480238', 'SSF3367152'),
('+917974128725', 'SID951373999879'),
('+917766844048', 'SSF5383182'),
('+917004181612', 'SID951375632883'),
('+917991889012', 'SSF2843991'),
('+917631988447', 'SSF5965337'),
('+917267833871', 'SSF3434624'),
('+917842293423', 'SSF5233789'),
('+917261824536', 'SSF2874185'),
('+917870095404', 'SID951374860627'),
('+917232899313', 'SSF2571553'),
('+918770455697', 'SSF5626156'),
('+918789196126', 'SSF3540201'),
('+918209224312', 'SSF3329216'),
('+918863877763', 'SID951376144135'),
('+918827863718', 'SSF5873900'),
('+919771940209', 'SSF3904779'),
('+919329880448', 'SSF3163221'),
('+919082614417', 'SSF2795342'),
('+919508112199', 'SSF5885894'),
('+919508928145', 'SID951375928414'),
('+919771177597', 'SSF5822841'),
('+919340015872', 'SSF5375107'),
('+919262837204', 'SSF5775586'),
('+919713426190', 'SID2125040829'),
('+919234562874', 'SSF5780398'),
('+917870290026', 'SSF5452867'),
('+918309739117', 'SSF5984952'),
('+918789337642', 'SSF4663600'),
('+919955993842', 'SSF5013257'),
('+919797546431', 'CID050408633'),
('+919693386203', 'CID139304082'),
('+916265668014', 'SSF5333674'),
('+916287952963', 'SSF3050552'),
('+916267030121', 'SSF5160137'),
('+916263520565', 'SSF3650009'),
('+916248431181', 'SID2125004384'),
('+916203218673', 'SSF5425334'),
('+916260223890', 'SID951375983618'),
('+917545961372', 'SSF5108471'),
('+917970347499', 'SSF5138870'),
('+917898983487', 'SSF3722269'),
('+917050349805', 'SSF5208907'),
('+917762032402', 'SSF5118593'),
('+917250474504', 'SSF5114900'),
('+917024789621', 'SID951374166093'),
('+917340433490', 'SSF5308355'),
('+917255977989', 'SSF5762439'),
('+917633925280', 'SSF5757323'),
('+918890452259', 'SSF5344132'),
('+918298700631', 'SSF4070045'),
('+918655575055', 'SID951375029847'),
('+918107289780', 'SSF4830885'),
('+918114542066', 'SSF5692071'),
('+918546754972', 'SID951374352101'),
('+918305452852', 'SID951373347563'),
('+918349186344', 'SSF5308679'),
('+918235091948', 'SSF5757324'),
('+919162556008', 'SSF3057065'),
('+919931131255', 'SSF5227374'),
('+919234602841', 'SSF5135527'),
('+919031599939', 'SSF5202796'),
('+919905755766', 'SSF5268194'),
('+919613615464', 'SID951375496685'),
('+919264116036', 'SSF5150576'),
('+919328818726', 'SSF2512761'),
('+919233667727', 'SSF2509317'),
('+919576075450', 'SID951374511839'),
('+919263724310', 'SSF5394617'),
('+919913435310', 'SSF5160743'),
('+919918610800', 'SSF5133227'),
('+919263775453', 'SSF5198773'),
('+919279426069', 'SSF5683081'),
('+919691368013', 'SSF5411106'),
('+919584584287', 'SID951376022383'),
('+918434727295', 'SID951373057380'),
('+919508241371', 'SSF6004894'),
('+916287023146', 'SSF5571962'),
('+916367742728', 'SSF5062360'),
('+917717757716', 'SSF5815868'),
('+917742191120', 'SSF5040323'),
('+917851945568', 'SID951375408128'),
('+917610820000', 'SSF3248614'),
('+917726883109', 'SSF4632910'),
('+917805992331', 'SSF5135100'),
('+917870608336', 'SID951374974229'),
('+917691852347', 'SSF4836719'),
('+917807385755', 'SID951376064287'),
('+917362854354', 'SSF5606629'),
('+917255991344', 'SSF4782180'),
('+917091826614', 'SSF4981997'),
('+918875625124', 'SSF5298807'),
('+918529097196', 'SSF4626520'),
('+918083232683', 'SSF5152544'),
('+918003017793', 'SSF4937875'),
('+918457884879', 'SID951375251897'),
('+918809088169', 'SSF5572016'),
('+918797185593', 'SSF2527336'),
('+918890924584', 'SSF5080558'),
('+918962023177', 'SID951375895586'),
('+919589473282', 'SSF4885983'),
('+919636465729', 'SSF5041034'),
('+919382349734', 'SSF5467093'),
('+919244632015', 'SSF4911122'),
('+919601317247', 'SSF2902466'),
('+919835285799', 'SID951375321220'),
('+919693929054', 'SSF4957778'),
('+919691785020', 'SSF4960566'),
('+919473138641', 'SSF5093150'),
('+919256569573', 'SSF3780254'),
('+919546193401', 'SSF4982441'),
('+919079138401', 'SSF5003893'),
('+919334753343', 'SSF4991564'),
('+919827975192', 'SSF4789624'),
('+919571593585', 'SSF4930827'),
('+919571981646', 'SSF4891532'),
('+918877931343', 'SSF5375777'),
('+917267939910', 'SSF3067863'),
('+916207716695', 'SSF2736318'),
('+916267470626', 'SSF4459595'),
('+916261169561', 'SSF4093566'),
('+916375987624', 'SSF4664851'),
('+917857055761', 'SSF4603489'),
('+917781832233', 'SSF2918760'),
('+917348734536', 'SSF2337904'),
('+917665116393', 'SSF4991790'),
('+917462989724', 'SID951375502913'),
('+917014865190', 'SSF4695119'),
('+918595544930', 'SSF4460591'),
('+918092247634', 'SSF4775653'),
('+918949469671', 'SSF4454028'),
('+918824588124', 'SSF4469953'),
('+918294551974', 'SSF4703436'),
('+918294210097', 'SSF4599726'),
('+918718004843', 'SID2125341029'),
('+918921136954', 'SID951375092182'),
('+918690963248', 'SSF3103699'),
('+918171570922', 'SSF5068600'),
('+919672332696', 'SID951375755655'),
('+919279265184', 'SSF4637027'),
('+919631905230', 'SSF4634466'),
('+919521836383', 'SSF3109157'),
('+919928051823', 'SSF4553612'),
('+919521180354', 'SSF4457572'),
('+919588754455', 'SID951375887619'),
('+919112524917', 'SSF3175939'),
('+919263237306', 'SID951375119812'),
('+919587833197', 'SSF2554376'),
('+916377175513', 'SSF4437149'),
('+916202940884', 'SSF4395402'),
('+916459868900', 'SID951375494762'),
('+917425936814', 'SID951375478358'),
('+917970703723', 'SSF4494873'),
('+917679737373', 'SSF3137896'),
('+917878734911', 'SSF4287928'),
('+917250048284', 'SSF4395608'),
('+918053748637', 'SSF2971033'),
('+918905121614', 'SSF4123454'),
('+918239020610', 'SSF4352502'),
('+918659768497', 'SID951375726471'),
('+918279273391', 'SSF4417169'),
('+918102963445', 'SSF4396108'),
('+919024289945', 'SID951376201095'),
('+919304469211', 'SSF4364041'),
('+919753782776', 'SSF3576295'),
('+919571820318', 'SSF4335031'),
('+919895646489', 'SSF3187745'),
('+918646564646', 'SSF3067781'),
('+918290171417', 'SSF4254573'),
('+918769813555', 'SSF4260048'),
('+918000846997', 'SSF4100174'),
('+918949729353', 'SSF4105768'),
('+919351512686', 'SSF4257392'),
('+919787784645', 'SSF3560580'),
('+919001129974', 'SSF4413365'),
('+919950118451', 'SSF4219557'),
('+919116481318', 'SSF4397844'),
('+919216730710', 'SSF4227587'),
('+919660425898', 'SSF4237654'),
('+916797948484', 'SSF3523925'),
('+917572964569', 'SSF4215352'),
('+918160719327', 'SSF3966532'),
('+919352636440', 'SSF4073397'),
('+917078252637', 'SSF3165649'),
('+918821923992', 'SSF3186842'),
('+918529168270', 'SSF3862011'),
('+918233535506', 'SSF3915121'),
('+918949901540', 'SSF3932992'),
('+918464840049', 'SID951375479852'),
('+919729158112', 'SSF2680675'),
('+919257172813', 'SSF3968670'),
('+917607093034', 'SSF6113525'),
('+917782025011', 'SSF3261233'),
('+919886855855', 'SSF3794823'),
('+919034453044', 'SSF3014853'),
('+917067362905', 'SID951373570149'),
('+918871261329', 'SID951374203973'),
('+916268262851', 'SSF2671141'),
('+919918366465', 'SSF2634568'),
('+919826351731', 'SSF2456521'),
('+917389757673', 'SSF6208475'),
('+918817543380', 'SSF2778800'),
('+918602450317', 'SSF5388801'),
('+918871933836', 'SSF5827476'),
('+918959783136', 'SSF3895465'),
('+919589204133', 'SSF6221752'),
('+919098478616', 'SSF3085819'),
('+919170119568', 'SSF3043678'),
('+919691140737', 'SSF6045888'),
('+919516004908', 'SSF5960084'),
('+919354837277', 'SSF3330994'),
('+919981607082', 'SSF2919004'),
('+917518552279', 'SSF5215897'),
('+916265387727', 'SSF3187112'),
('+919131197644', 'CID098102939'),
('+918002032503', 'CID212400878'),
('+919630931619', 'SID951373569721'),
('+919304555714', 'SID951373444149'),
('+917724981118', 'SID951373903851'),
('+917870813033', 'SID951375702353'),
('+918690068479', 'SSF3239079'),
('+918085035551', 'CID093211582'),
('+918097804454', 'SSF4538338'),
('+919399205348', 'SID951373577689'),
('+919302913003', 'CID043401051'),
('+919919663736', 'SSF5612968'),
('+919672996724', 'SSF2589810'),
('+918292043634', 'SID951373764277'),
('+919102793311', 'SSF2805592'),
('+918797776677', 'SSF2911729'),
('+916266440336', 'SSF4102920'),
('+917054870593', 'SSF3033899'),
('+918269255584', 'SSF3271450'),
('+918292607265', 'SSF2697526'),
('+919302841728', 'SID951375114639'),
('+919399765702', 'SID951375702136'),
('+919366887851', 'SSF4495940'),
('+917068527995', 'SSF2934969'),
('+919335998011', 'SSF3630735'),
('+917852856670', 'SID951374845394'),
('+916268324479', 'SSF4220866'),
('+919648577762', 'SSF4039218'),
('+919857646349', 'SID951375190469'),
('+919926718788', 'SID951373717755'),
('+918400738850', 'SSF2929882'),
('+918739808744', 'SSF2577517'),
('+918853736900', 'SSF3786919'),
('+919219476136', 'SSF2538622'),
('+917828513393', 'CID064701565'),
('+917870355079', 'SSF2543415'),
('+917488347842', 'SSF3692340'),
('+916264900129', 'SID951375664138'),
('+917898856668', 'SSF2500640'),
('+917440315179', 'SID951376158257'),
('+917091828975', 'SID951374619909'),
('+919484646494', 'SSF3306252'),
('+919982826630', 'SID951375949321'),
('+916200767959', 'SSF3154344'),
('+919256509440', 'SSF3081880'),
('+916262738529', 'SSF2617528'),
('+917759825421', 'SSF4311013'),
('+917869308965', 'SSF3703679'),
('+916261911460', 'SSF5862401'),
('+919685696440', 'SID951375022882'),
('+919980795552', 'SID951375996149'),
('+918102200683', 'SSF2740532'),
('+919784248678', 'SID951375995133'),
('+916266698281', 'SSF3510774'),
('+918567285558', 'CID081013551'),
('+917089032431', 'SSF3594076'),
('+918208030753', 'SSF4630272'),
('+917049252305', 'SSF3695390'),
('+916367150903', 'SSF3323850'),
('+919006033657', 'SID951375653828'),
('+919301683868', 'SID951374366303'),
('+918709772752', 'CID119106685'),
('+917307295377', 'SSF5465240'),
('+919982129956', 'SSF3916205'),
('+919696021641', 'SSF5218064'),
('+919630077752', 'SID951374675630'),
('+918302143091', 'SID951375122433'),
('+917542817540', 'SSF3383538'),
('+917489357922', 'SSF2926002'),
('+918189002608', 'SID951373963607'),
('+917739794193', 'SID951374739612'),
('+918269597279', 'SSF5318718'),
('+917903186839', 'SSF6078116'),
('+917261850520', 'SID951374247328'),
('+919792501268', 'SSF4403993'),
('+918445850857', 'SSF5268874'),
('+918540816689', 'SID951375794195'),
('+918576884136', 'SID951372969026'),
('+919587599261', 'SSF4480118'),
('+918127631794', 'SSF5108244'),
('+919950734848', 'SSF2330491'),
('+918358074350', 'SSF2849852'),
('+918252065059', 'SSF3869807'),
('+919140028174', 'SSF2581732'),
('+916378651925', 'SID951375373547'),
('+917697924680', 'CID191601797'),
('+917999331927', 'CID213600573'),
('+917479663956', 'SSF5999189'),
('+917828012421', 'SID2125538660'),
('+918000193378', 'SID951374465337'),
('+919981784288', 'SID2125683614'),
('+919982332311', 'SSF2345610'),
('+917484095180', 'SSF3700102'),
('+918946465535', 'SID2125607537'),
('+918239593676', 'SID951374854503'),
('+917772038450', 'SSF4025745'),
('+919926347876', 'SSF3228596'),
('+918171735326', 'SSF5732067'),
('+919140442396', 'SSF5046667'),
('+917240924909', 'SSF4297783'),
('+917905441742', 'SID951373895566'),
('+917049942825', 'SID951373361675'),
('+916267860744', 'SSF3062186'),
('+916260948461', 'SSF2358755'),
('+919644121778', 'SID951373436692'),
('+919589509730', 'CID128612727'),
('+917645089145', 'SSF3245832'),
('+916267410394', 'SID951374688405'),
('+919721375639', 'SSF5301347'),
('+918683096609', 'SSF2574857'),
('+919661753514', 'SID951374682661'),
('+919658535562', 'SID951373361163'),
('+918052513169', 'SSF6106604'),
('+917723045324', 'SID951374611044'),
('+918092907992', 'SID951374612074'),
('+917878418768', 'SID951375334840'),
('+918827416717', 'SID951375967691'),
('+918539912478', 'SSF2727318'),
('+919905346559', 'SID951376017152'),
('+917610135035', 'SID951374391684'),
('+918503978846', 'SID951375279437'),
('+916262059501', 'SID951374600082'),
('+917441122754', 'SSF2983962'),
('+917781876412', 'SSF5575984'),
('+918431092402', 'SSF2325766'),
('+919142785801', 'SID2125173100'),
('+916207474410', 'SID951375907839'),
('+919142634974', 'SID951375798228'),
('+917814415437', 'SSF2709468'),
('+917488602858', 'SID951373509376'),
('+918294519855', 'SSF2908290'),
('+918340638245', 'SID951376237932'),
('+919835440650', 'SSF2694426'),
('+916260167004', 'SSF2333506'),
('+916209547239', 'SSF6319510'),
('+917349914264', 'SSF6190584'),
('+917355231224', 'SSF6041915'),
('+917069703013', 'SSF6332737'),
('+917033605288', 'SSF6298922'),
('+917634959978', 'SSF6080007'),
('+918885491861', 'SSF6330171'),
('+918757332474', 'SSF4414900'),
('+918263046301', 'SSF6027632'),
('+918767338902', 'SSF4103803'),
('+918264649627', 'SSF6178560'),
('+919153137283', 'SSF6197142'),
('+919279961059', 'SSF6115025'),
('+919967621750', 'SSF6171054'),
('+919235463325', 'SSF6319682'),
('+917367014733', 'SID951373948521'),
('+917842605498', 'SSF6308720'),
('+918858504200', 'SSF3752294'),
('+919153455362', 'SID951375152094'),
('+917558298148', 'SSF4689368'),
('+917070158015', 'SSF6166681'),
('+917543910386', 'SID951373504968'),
('+918298982801', 'SSF5904032'),
('+919305479445', 'SSF6190404'),
('+916268267666', 'SID951375956545'),
('+918866708144', 'SID951375529674'),
('+916205869780', 'SSF2786072'),
('+917481894993', 'SSF2393539'),
('+917398686266', 'SSF2287435'),
('+917827508793', 'SSF2409833'),
('+917255028491', 'SSF2640749'),
('+916394110524', 'SSF4998990'),
('+916206718923', 'SSF2737820'),
('+916264689140', 'SSF5642424'),
('+916262961808', 'SSF3695107'),
('+917356839821', 'SSF6184096'),
('+917320917021', 'SID951375776065'),
('+917321898545', 'SSF3648723'),
('+917835921882', 'SSF3394148'),
('+917024540060', 'SSF6073341'),
('+917260857738', 'SSF3403656'),
('+917739503784', 'SSF3460353'),
('+917400635477', 'SSF6209037'),
('+918210244287', 'SSF6157072'),
('+918003535910', 'SSF3379119'),
('+918726293201', 'SSF3567870'),
('+918603135213', 'SSF3670660'),
('+918709212728', 'SSF6251661'),
('+918840497042', 'SSF3121084'),
('+918252612012', 'SSF6195853'),
('+918092387478', 'SSF5782954'),
('+918955726369', 'SSF5689601'),
('+918962084380', 'SSF5846488'),
('+919234445059', 'SSF6188609'),
('+919304066086', 'SSF3566954'),
('+919113353550', 'SSF4241398'),
('+919022275956', 'SSF6197740'),
('+919608583600', 'SSF6193260'),
('+919608786549', 'SID951375897197'),
('+919162854134', 'SSF5629434'),
('+919380136979', 'SSF6114905'),
('+919279644286', 'SSF6115043'),
('+919534453154', 'SSF6262493'),
('+919784497807', 'SSF3658742'),
('+916287918251', 'SSF5961129'),
('+916392091552', 'SSF3716941'),
('+916367776996', 'SSF5471957'),
('+917992492347', 'SSF6010423'),
('+917766066151', 'SID951375982769'),
('+917542072583', 'SSF3504975'),
('+917498794665', 'SSF2916782'),
('+917759822827', 'SSF2297956'),
('+917050999359', 'SSF3061033'),
('+917368073853', 'SSF2283789'),
('+918905059545', 'SSF2640237'),
('+918002046651', 'SSF5649495'),
('+918207733182', 'SSF6046934'),
('+918122358061', 'SSF2437841'),
('+918002150710', 'SSF3078180'),
('+919303017072', 'SSF3009777'),
('+919348334986', 'SSF3633472'),
('+919117431288', 'SSF6101998'),
('+919234622371', 'SSF3538435'),
('+919343301305', 'SSF3568844'),
('+919508764311', 'SSF3595519'),
('+919798508231', 'SID951376110061'),
('+919065338506', 'SSF3007125'),
('+919199153049', 'SID951373474612'),
('+919547899507', 'SID951375632649'),
('+919343388957', 'SSF3152868'),
('+919507836993', 'SSF3574278'),
('+919109312018', 'SSF2447213'),
('+918757106921', 'SSF5980344'),
('+917352021749', 'SSF4608244'),
('+918102302818', 'SSF4779082'),
('+918252773594', 'SSF3629994'),
('+917692949407', 'SID2125211845'),
('+916202130940', 'SSF5482694'),
('+916280964178', 'SSF5419421'),
('+916307413839', 'SID951376145512'),
('+916267187986', 'SSF3056118'),
('+917499272206', 'SSF5533719'),
('+917976999820', 'SSF5439110'),
('+917879412151', 'SSF5593778'),
('+917979768459', 'SSF5617614'),
('+917261084970', 'SSF5628140'),
('+917569210641', 'SSF3063522'),
('+917643959433', 'SSF5536653'),
('+918519080972', 'SSF5136893'),
('+918092896113', 'SID951375619631'),
('+918815940889', 'SSF3536435'),
('+918969578311', 'SSF5389305'),
('+918769451055', 'SID951374353260'),
('+918757992060', 'SSF5217988'),
('+918298885590', 'SID951372876540'),
('+918815931053', 'SSF5589426'),
('+918986960207', 'SSF3159653'),
('+919685245565', 'SID951375463895'),
('+919694258255', 'SSF3059093'),
('+919775713067', 'SSF3318212'),
('+919234515630', 'SSF3864954'),
('+919753258484', 'SSF3440347'),
('+919301092190', 'SSF5102877'),
('+919399475314', 'SSF3454642'),
('+919301978026', 'SSF3315945'),
('+919752850981', 'SID951375797401'),
('+919241817841', 'SSF5482522'),
('+919693881688', 'SSF5410053'),
('+919302183986', 'SSF5189713'),
('+917367008449', 'SSF4647162'),
('+918051967438', 'SSF6213022'),
('+918112715996', 'SSF6158537'),
('+919506704626', 'SSF4685197'),
('+919350146529', 'SSF4852789'),
('+919718324585', 'SSF4389558'),
('+916200773017', 'SSF3098455'),
('+916201149857', 'SSF5466399'),
('+916204729577', 'SSF5213173'),
('+916363107924', 'SID951376130347'),
('+916377879478', 'SSF5539689'),
('+917489936047', 'SSF5177456'),
('+917023806202', 'SSF5182333'),
('+917974349857', 'SID951375932214'),
('+917737892438', 'SSF5205570'),
('+917023026686', 'SSF5262641'),
('+917209301861', 'SSF5426842'),
('+917082871949', 'SSF5477233'),
('+917370974516', 'SSF5438236'),
('+917898553286', 'SID951375264727'),
('+918696464078', 'SSF5264791'),
('+918085086972', 'SSF5177749'),
('+918292636323', 'SSF3214285'),
('+918448543617', 'SID951375756194'),
('+918252015480', 'SSF5226347'),
('+918129901370', 'SSF5228442'),
('+918690105574', 'SSF4825102'),
('+918298707585', 'SSF5395537'),
('+918905156510', 'SSF5180629'),
('+919509416510', 'SID951375750479'),
('+919828786208', 'SSF5435249'),
('+919799985374', 'SSF2820836'),
('+919521341851', 'SSF3280494'),
('+919576269593', 'SSF2926305'),
('+919216662105', 'SSF5258708'),
('+919971742832', 'SID951375332229'),
('+919798678261', 'SSF4965593'),
('+919340387443', 'SID951372938015'),
('+919799156769', 'SID951375120015'),
('+919708383783', 'SSF5542103'),
('+919571850436', 'SSF4902374'),
('+919351225164', 'SSF5374494'),
('+919621682587', 'SID951374139233'),
('+917700864156', 'SSF4648785'),
('+917849909783', 'SSF2781268'),
('+918107744871', 'SSF5012881'),
('+917297898085', 'SSF2591075'),
('+917742371807', 'SID951375496130'),
('+917023565050', 'SSF4813296'),
('+917878027320', 'SSF4792645'),
('+917023681297', 'SSF4854292'),
('+917665116126', 'SSF4820528'),
('+917742761892', 'SSF4931729'),
('+917763066557', 'SSF4708831'),
('+917426092947', 'SSF4931816'),
('+917320046356', 'SSF4721255'),
('+917807459463', 'SSF4721139'),
('+917070798263', 'SSF4796364'),
('+917023398001', 'SSF4737050'),
('+918112288667', 'SSF4889501'),
('+918824976845', 'SSF4760816'),
('+918797008441', 'SID951374462631'),
('+918696912035', 'SSF4791885'),
('+918899784415', 'SSF4737804'),
('+918854906771', 'SSF4931899'),
('+918955609837', 'SSF3027212'),
('+918875394059', 'SSF4713746'),
('+918740805324', 'SSF4449643'),
('+918226066019', 'SSF4935494'),
('+919928102061', 'SSF4889238'),
('+919950705752', 'SSF4770620'),
('+919413231319', 'SID951375500443'),
('+919929790913', 'SSF4821987'),
('+919770010409', 'SID2125093683'),
('+919955953961', 'SSF4462748'),
('+919664041281', 'SSF4931836'),
('+919352820960', 'SSF4855262'),
('+919521549654', 'SSF4931759'),
('+919256261760', 'SSF4931684'),
('+919895255544', 'SID951376153569'),
('+916204385685', 'SID951374490394'),
('+917850005765', 'SSF4742481'),
('+918233826597', 'SSF4704931'),
('+919680947037', 'SSF4307696'),
('+919693890438', 'SSF3094661'),
('+919256785561', 'SSF4192471'),
('+919189550112', 'SID951374993496'),
('+919983488434', 'SSF2731085'),
('+919103019781', 'SSF4330158'),
('+917633860730', 'SSF4175871'),
('+918294772196', 'SSF4175844'),
('+919358256451', 'SSF4506624'),
('+919119149537', 'SSF4423726'),
('+919341523963', 'SSF4141571'),
('+919352277180', 'SSF2633122'),
('+916375426817', 'SSF2324907'),
('+917296958614', 'SSF4007286'),
('+919587802713', 'SSF2617129'),
('+919351632771', 'SSF4288022'),
('+919553784648', 'SSF3196001'),
('+917665801975', 'SSF2909893'),
('+919257849035', 'SSF4033833'),
('+918810916173', 'SSF3962624'),
('+919138853286', 'SSF3553019'),
('+919845846734', 'SID951376132591'),
('+916266682722', 'SID951373367461'),
('+919229065279', 'SID951374455731'),
('+918009474123', 'SSF2853964'),
('+916206962094', 'SSF6136088'),
('+916205821531', 'SSF6286982'),
('+916367247768', 'SSF4599121'),
('+917524066934', 'SSF3830884'),
('+917482906503', 'SSF3968754'),
('+917379772789', 'SSF6077147'),
('+917877869655', 'SSF3827560'),
('+917762037094', 'SSF2516921'),
('+918839525563', 'SSF6176468'),
('+918235454326', 'SSF6322212'),
('+918002021874', 'SSF6158832'),
('+918423078337', 'SSF6314383'),
('+918173817565', 'SSF2897043'),
('+919905486308', 'SSF6374336'),
('+919122783638', 'SSF6149040'),
('+919037605447', 'SSF3009403'),
('+919216656284', 'SSF5976345'),
('+919501907425', 'SSF6084869'),
('+919302928129', 'SSF4375195'),
('+919302051852', 'SSF3280608'),
('+919685992584', 'SSF4313488'),
('+919660356528', 'SSF4356429'),
('+919198381106', 'SSF6314306'),
('+919360219793', 'SSF6338175'),
('+919360511616', 'SID951375928401'),
('+917858974959', 'SSF6283407'),
('+916200238987', 'SSF2803866'),
('+917070134926', 'SSF2511730'),
('+919265720080', 'SSF2763858'),
('+919006139980', 'SSF2901888'),
('+919263069681', 'SSF2682410'),
('+919199554610', 'SSF2456469'),
('+916267488794', 'SSF5896785'),
('+916266305943', 'SSF4014411'),
('+916205229805', 'SSF5878721'),
('+916282064076', 'SSF6317912'),
('+916200692826', 'SSF2981184'),
('+917999815958', 'SSF3851486'),
('+917779930376', 'SSF3477129'),
('+917992203964', 'SSF3203895'),
('+917081387833', 'SSF6038555'),
('+917309910381', 'SSF6317312'),
('+917309910486', 'SSF6317329'),
('+917839835484', 'SSF6025245'),
('+917309299105', 'SSF6317260'),
('+917545895568', 'SSF5846752'),
('+917319757679', 'SSF5823967'),
('+917398817256', 'SSF6313620'),
('+917521871804', 'SSF6318047'),
('+918103671160', 'SSF5939781'),
('+918114515984', 'SSF3006062'),
('+918827681972', 'SSF4162994'),
('+918319477417', 'SSF4055325'),
('+918294904353', 'SSF6253858'),
('+918890168155', 'SSF6198604'),
('+918002508718', 'SSF6309640'),
('+918075869006', 'SSF5927404'),
('+918173872409', 'SSF6317677'),
('+918175873498', 'SSF6314750'),
('+918271780838', 'SSF6093286'),
('+918271253058', 'SSF5958988'),
('+918770745126', 'SSF6260739'),
('+919297913825', 'SSF6323924'),
('+919798997803', 'SSF4187099'),
('+919918845629', 'SSF6246692'),
('+919798891652', 'SSF6028440'),
('+919919402784', 'SSF6317353'),
('+919918942398', 'SSF6317302'),
('+919771129516', 'SSF5933538'),
('+919919284723', 'SSF6315885'),
('+919229809133', 'SSF6251185'),
('+919939083018', 'SSF6315972'),
('+919717852172', 'SSF6318131'),
('+919074991094', 'SSF6317968'),
('+919580230829', 'SSF6318052'),
('+919889183991', 'SSF6318233'),
('+919117556864', 'SSF3805941'),
('+919888494106', 'SSF6313562'),
('+919661613137', 'SSF5548163'),
('+919845275868', 'SSF6105148'),
('+919708338074', 'SSF5877191'),
('+919060153287', 'SSF4767467'),
('+917369914321', 'SSF6248483'),
('+919279577863', 'SSF6305101'),
('+919162783050', 'SSF4825676'),
('+919661538294', 'SID951373093145'),
('+917739147355', 'SSF3261552'),
('+917498304867', 'SSF6028488'),
('+917620785116', 'SSF3777389'),
('+918852856332', 'SSF3822706'),
('+918862846084', 'SID951375990915'),
('+918207636820', 'SSF6208769'),
('+919241197959', 'SSF6187185'),
('+919571483423', 'SSF5586319'),
('+916204582528', 'SID2125049308'),
('+916266256998', 'SSF4022394'),
('+916200504827', 'SSF6035788'),
('+917654500799', 'SSF3822419'),
('+917367096891', 'SSF6015934'),
('+917292866448', 'SSF3752505'),
('+917091312899', 'SSF2896349'),
('+918292254736', 'SID951374759502'),
('+918235401965', 'SSF5623031'),
('+918877526602', 'SSF6022810'),
('+918302359060', 'SSF5669040'),
('+918003877218', 'SSF2653126'),
('+919307961992', 'SID951375902996'),
('+919142752177', 'SSF6006844'),
('+919199342335', 'SSF2696758'),
('+919572642130', 'SSF3078266'),
('+919798284609', 'SSF6204154'),
('+917050988324', 'SSF4157845'),
('+917800137958', 'SSF3947234'),
('+919062158217', 'SSF6389663'),
('+918269814863', 'SID951373194894'),
('+916266551739', 'SID951372945322'),
('+916267834937', 'SSF5107926'),
('+916201583528', 'SSF5574498'),
('+916367490887', 'SID951376181215'),
('+917224002570', 'SSF5333669'),
('+917049406537', 'SSF5351152'),
('+917999723221', 'SSF5494604'),
('+917067933877', 'SSF5226255'),
('+917461098262', 'SSF3288893'),
('+917254023694', 'SID951375485050'),
('+917479636432', 'SSF5591028'),
('+917858096011', 'SSF5590574'),
('+917361065509', 'SSF5720902'),
('+917828143462', 'SID951375890464'),
('+917643083474', 'SSF5567819'),
('+917487975032', 'SSF5581028'),
('+917987003626', 'SSF5692437'),
('+918340107003', 'SID951376031607'),
('+918115746859', 'SSF3213886'),
('+918815310992', 'SSF5513954'),
('+918306867086', 'SID951375357119'),
('+919576126082', 'SSF5675475'),
('+919592937286', 'SSF5437046'),
('+919340313602', 'SSF5747931'),
('+919340932479', 'SSF5119287'),
('+919171326562', 'SSF3291343'),
('+919709838831', 'SSF5720906'),
('+919523793808', 'SSF3340589'),
('+919080476206', 'SID951376211150'),
('+919329967487', 'SSF5376619'),
('+919754145710', 'SSF4943787'),
('+919044828663', 'SSF4524211'),
('+919616622369', 'SSF6181811'),
('+918174892072', 'SSF4670595'),
('+917307558565', 'SSF4138534'),
('+916206269022', 'SID951374817475'),
('+916266977480', 'SID951375940022'),
('+917992319861', 'SID951375488114'),
('+917737605025', 'SSF5009428'),
('+917479446335', 'SSF3200076'),
('+917597130359', 'SID951374425145'),
('+917209634166', 'SID951374011019'),
('+917463911016', 'SSF5388419'),
('+917300267690', 'SSF2593594'),
('+917415893124', 'SSF3575716'),
('+917033118706', 'SSF2989146'),
('+918889272450', 'SSF5302411'),
('+918227009121', 'SSF5259462'),
('+918434902574', 'SSF5436382'),
('+918696549951', 'SSF5131970'),
('+918000540633', 'SSF2773021'),
('+919343627442', 'SSF3285966'),
('+919784686822', 'SSF5310297'),
('+919166275471', 'SSF5122575'),
('+919303025661', 'SID951374475171'),
('+919341670980', 'SSF2876930'),
('+919576144313', 'SSF5432650'),
('+919587398889', 'SSF5339350'),
('+919602615499', 'SSF5425568'),
('+919263555414', 'SSF3130006'),
('+919216672296', 'SSF5339893'),
('+919023543626', 'SSF5131547'),
('+919588095825', 'SSF5326760'),
('+919694758595', 'SSF5505606'),
('+918005783750', 'SSF2758491'),
('+916350434288', 'SSF2855715'),
('+917679464313', 'SID951375639791'),
('+917742820311', 'SSF4760823'),
('+917737157550', 'SSF4854325'),
('+917352321373', 'SSF3089672'),
('+917737462279', 'SSF4932036'),
('+917461920647', 'SSF4709004'),
('+917976390985', 'SSF4932051'),
('+917625486365', 'SSF2721879'),
('+918873573360', 'SSF2542947'),
('+918770752946', 'CID951376201181'),
('+918877509833', 'SID951376041900'),
('+918674948402', 'SSF4870896'),
('+918709442764', 'SSF3122484'),
('+918769319195', 'SSF4760012'),
('+918619052814', 'SSF4813547'),
('+918306596724', 'SSF4933902'),
('+919116947138', 'SSF4889302'),
('+919257580718', 'SSF4774549'),
('+919351790672', 'SSF4793081'),
('+919399545532', 'SSF4838020'),
('+919784579701', 'SSF4854404'),
('+919549204307', 'SSF4728305'),
('+919602168807', 'SSF4854512'),
('+919549202449', 'SSF4854315'),
('+919976767944', 'SID951374559414'),
('+919079962094', 'SID951375346165'),
('+919521472037', 'SSF4910497'),
('+916304161905', 'SSF4322068'),
('+918949593730', 'SSF4574630'),
('+919568686565', 'SID951375710643'),
('+919511536961', 'SSF4670449'),
('+919351261760', 'SSF4343223'),
('+919829723117', 'SSF4330237'),
('+919256377094', 'SSF4343235'),
('+919498899898', 'SID951376088927'),
('+919680534299', 'SSF4484256'),
('+919934774672', 'SID951375649036'),
('+916376854856', 'SSF4398093'),
('+916350278872', 'SSF4354747'),
('+917587355912', 'SSF4068708'),
('+917221817057', 'SSF2555017'),
('+918839833530', 'SID951375532440'),
('+918690819913', 'SSF4408599'),
('+919356669888', 'SSF2578818'),
('+917232054955', 'SSF2324910'),
('+916503862965', 'SSF3811050'),
('+917014147913', 'SID951374381006'),
('+918840322423', 'CID211604408'),
('+919057060421', 'SSF4139216'),
('+919929052014', 'SSF4033131'),
('+916261636727', 'SSF3763615'),
('+917387450253', 'SID951375899391'),
('+917665901775', 'SSF3718257'),
('+919688684296', 'SSF3709271'),
('+917879330478', 'SID951374392512'),
('+917999436148', 'SSF5841583'),
('+918982170710', 'SSF3582189'),
('+918359950456', 'SSF6089823'),
('+919981927185', 'SSF3820766'),
('+919098658141', 'SSF6005015'),
('+919098226785', 'SSF3467173'),
('+919109060119', 'SSF3920511'),
('+917746099751', 'CID044711658'),
('+918959030722', 'SID951374771996'),
('+919955077856', 'SSF2487931'),
('+918696992216', 'SSF3338649'),
('+919305485044', 'SSF3258520'),
('+916268500182', 'SSF2790146'),
('+917999656117', 'SSF2817958'),
('+917257860736', 'SID951375812027'),
('+916261696216', 'SSF3752917'),
('+919770193802', 'SID951374910206'),
('+918358993215', 'SSF3571782'),
('+919672293646', 'SID951376096758'),
('+919648452375', 'SSF5095124'),
('+918002635762', 'SID951374697707'),
('+919571704516', 'SSF3621141'),
('+917541931270', 'SSF3438007'),
('+919336408112', 'SSF5388052'),
('+919926060128', 'SSF3650435'),
('+918000015826', 'SID951374098775'),
('+919199777783', 'SSF3856292'),
('+919110129293', 'SID951374265437'),
('+918236973980', 'SID951374896742'),
('+919302789190', 'SSF5282525'),
('+917879455810', 'SSF3195906'),
('+916262503262', 'SID951374941073'),
('+917879571887', 'SID951373775942'),
('+917747906673', 'CID120710672'),
('+919001132262', 'SSF3404703'),
('+918085907411', 'SID951373713285'),
('+917803003791', 'SID2125735604'),
('+918319301379', 'SID951374788905'),
('+919506147451', 'SSF4141868'),
('+917764881210', 'SID951375572741'),
('+919238345570', 'SSF4841102'),
('+917047508217', 'SSF5225534'),
('+919009816101', 'SID951374322467'),
('+918227804125', 'SSF3053643'),
('+916204812948', 'SSF3605108'),
('+919950519163', 'SSF3325214'),
('+917575099073', 'SSF3477633'),
('+918461964328', 'SID951373266236'),
('+918957640514', 'SSF2548995'),
('+919569176546', 'SID951373849643'),
('+917296024387', 'SID951375886344'),
('+917724857576', 'SSF3028982'),
('+917416410537', 'SSF4249211'),
('+919696198020', 'SSF4667319'),
('+917566703107', 'SID951375788677'),
('+918298952744', 'SSF3134373'),
('+919608400325', 'SSF3313936'),
('+919523313013', 'SID951375394663'),
('+917710733526', 'SSF4731951'),
('+919511828146', 'SSF5594819'),
('+917771090362', 'SID951373855046'),
('+918827272073', 'SID951373937898'),
('+919235428667', 'SSF3344880'),
('+917061447960', 'SID951375714984'),
('+919905584379', 'SSF3825070'),
('+916200426728', 'SSF3825071'),
('+919981202038', 'SID951375133809'),
('+916264871557', 'SID951375101755'),
('+919794502784', 'SID951375466542'),
('+919264412454', 'SID951374734306'),
('+918267906408', 'SSF6090107'),
('+918962912658', 'SID951373584593'),
('+919516950046', 'SSF5024295'),
('+918969436948', 'SID951374815698'),
('+917048914269', 'SSF5341329'),
('+917481868029', 'SID951374670304'),
('+917509717565', 'SID951375686128'),
('+916260779274', 'SID951375209407'),
('+916266026923', 'SSF3545326'),
('+919572355207', 'SID951372945832'),
('+918305501972', 'SSF3575133'),
('+918292669056', 'SSF2518606'),
('+918174884194', 'SSF5597290'),
('+917050026081', 'SSF2899200'),
('+916202922974', 'SID951373052037'),
('+917229924116', 'SID951375196177'),
('+916268979960', 'SSF4601165'),
('+919967405429', 'SSF4856647'),
('+919974939417', 'SSF3099738'),
('+916307735098', 'SSF4516376'),
('+917061309449', 'SSF3650543'),
('+919174512203', 'SSF3943202'),
('+918084173413', 'SSF3251099'),
('+919755117168', 'SID951373540517'),
('+917209181850', 'SSF5387419'),
('+919682280316', 'SSF4755612'),
('+917580828178', 'SID951373758505'),
('+917897010981', 'SSF4970438'),
('+919303465395', 'SSF4631000'),
('+917319710986', 'SSF3173055'),
('+917371038842', 'SSF5137194'),
('+919340749243', 'SID951374167683'),
('+918817626424', 'SID951373207811'),
('+919229450315', 'SSF5182492'),
('+917484036854', 'SSF3129029'),
('+919039731414', 'SID951373065189'),
('+918815783384', 'SID951375756885'),
('+919335000756', 'SSF4687364'),
('+919522227652', 'SSF3021289'),
('+919166458825', 'SID951374042735'),
('+918850183860', 'SID951373248991'),
('+917879723586', 'SSF3515816'),
('+916393030221', 'SSF5447427'),
('+917205481299', 'SSF3144164'),
('+918467075031', 'SSF2463743'),
('+919556270121', 'SSF3297818'),
('+916265334264', 'SSF3256952'),
('+919680677646', 'SSF2936941'),
('+918252764181', 'SSF2359181'),
('+919508655471', 'SSF2353703'),
('+918562117866', 'SID951372829330'),
('+917389667367', 'SSF2425883'),
('+919112558148', 'SSF3018685'),
('+919691184402', 'SSF2744914'),
('+917857073125', 'SID951374491965'),
('+918294853823', 'SSF2902900'),
('+918449497878', 'SID951376103108'),
('+917856099242', 'SSF3174631'),
('+916261200997', 'SSF2457457'),
('+918085280710', 'SID951374474931'),
('+918305822103', 'SSF4534720'),
('+919664242890', 'SSF2649900'),
('+918889200428', 'SID951372994790'),
('+917061582263', 'SSF3048617'),
('+919905433349', 'SSF3511254'),
('+916394071424', 'SSF5129031'),
('+919301483535', 'SID951373003395'),
('+919302874383', 'SID951374184502'),
('+919523481769', 'SID951373308388'),
('+916206796969', 'SID951375173618'),
('+918935925004', 'SID951375760373'),
('+919263424953', 'SID951374886193'),
('+919006052130', 'SID951375651226'),
('+919244214759', 'SID951375558248'),
('+917050474338', 'SSF2556908'),
('+917765035130', 'SSF2285777'),
('+919631460703', 'SSF2716590'),
('+917048314254', 'SSF3261654'),
('+917782947283', 'SSF3296092'),
('+917654590215', 'SSF3310319'),
('+917897193435', 'SSF6307090'),
('+917209325425', 'SSF3129608'),
('+917987521569', 'SSF5320621'),
('+917745907137', 'SSF4016916'),
('+917870968745', 'SSF4410119'),
('+917367005423', 'SSF3313563'),
('+917462970891', 'SSF6192212'),
('+918797662239', 'SSF6284806'),
('+918809711743', 'SSF3046572'),
('+918090883310', 'SSF6303726'),
('+918294715112', 'SSF6247123'),
('+918953723898', 'SSF6305798'),
('+918521679510', 'SSF6306909'),
('+918187994133', 'SSF6305883'),
('+918890227381', 'SSF3162003'),
('+918603554794', 'SSF6273766'),
('+918809003281', 'SSF6245991'),
('+918292264248', 'SSF2968760'),
('+918815462609', 'SSF3982429'),
('+919770604743', 'SSF4003151'),
('+919006564332', 'SSF4196078'),
('+919179552006', 'SSF4208643'),
('+919693751359', 'SSF6244958'),
('+919931750266', 'SSF3016576'),
('+919199009477', 'SSF3041197'),
('+919631903910', 'SSF6311117'),
('+919343886785', 'SSF6335861'),
('+919399870836', 'SSF6290383'),
('+919928427242', 'SSF3046869'),
('+919110091028', 'SSF3244178'),
('+919555600955', 'SSF3094880'),
('+919634085271', 'SSF6308988'),
('+919525252553', 'SSF6204788'),
('+919523367816', 'SSF6278290'),
('+917209024544', 'SSF2868996'),
('+918935890267', 'SSF2883436'),
('+919931013320', 'SSF2444164'),
('+917061032379', 'SSF3245273'),
('+917992297712', 'SSF3068023'),
('+918770002702', 'SSF3245869'),
('+917022044019', 'SSF5196609'),
('+916284728329', 'SSF6339857'),
('+916207100501', 'SSF6074370'),
('+917091981401', 'SSF4529709'),
('+918969283255', 'SSF6214505'),
('+917762091639', 'SSF6295382'),
('+917857895727', 'SSF2416611'),
('+917408832290', 'SSF2741486'),
('+917858805268', 'SSF2407401'),
('+918107482090', 'SSF2863313'),
('+919708576835', 'SID951376162122'),
('+916263215385', 'SSF6072977'),
('+916265028488', 'SSF6018654'),
('+916264162387', 'CID213702685'),
('+917485071607', 'SSF4164610'),
('+917489422017', 'SSF3222604'),
('+917033397588', 'SSF4164573'),
('+917091903408', 'SSF3082163'),
('+917828075386', 'SSF3104711'),
('+917379319695', 'SSF2410508'),
('+917070138783', 'SSF3241720'),
('+917992445854', 'SSF5570172'),
('+917974977291', 'SSF4357708'),
('+918875354435', 'SSF3808808'),
('+918789738703', 'SSF3945640'),
('+918881762106', 'SSF3123007'),
('+919453838508', 'SSF2914431'),
('+919907039147', 'SSF6208431'),
('+919335340689', 'SSF4243823'),
('+916394098824', 'SSF2796006'),
('+916268375537', 'SSF5934268'),
('+917745969688', 'SID951374530209'),
('+917295945467', 'SID951373722614'),
('+917488335785', 'SID951376215760'),
('+917033108851', 'SSF2739746'),
('+917489504245', 'SSF3989299'),
('+917770851834', 'SSF5927150'),
('+917541003150', 'SID951375426128'),
('+917631578025', 'SSF2646463'),
('+917440546290', 'SSF5967504'),
('+918229075217', 'SSF3611709'),
('+918002210602', 'SID951374661332'),
('+918228853287', 'SSF2343988'),
('+918955303744', 'SSF3247842'),
('+919006642805', 'SSF2614521'),
('+919199106835', 'SSF3904888'),
('+919244233866', 'SSF6098651'),
('+919179017835', 'SSF6016048'),
('+918887981853', 'SSF4622876'),
('+918809869914', 'SID951375185334'),
('+919771182497', 'SSF5514302'),
('+919109785552', 'SSF5590041'),
('+919534779517', 'SSF3477858'),
('+917250534916', 'SSF4801517'),
('+917463825840', 'SSF5764610'),
('+919693213924', 'SSF6412269'),
('+917489115289', 'SID2125701135'),
('+919162287057', 'CID204504314'),
('+916204207370', 'SSF6303546'),
('+916287667449', 'SSF5318920'),
('+916266988086', 'SSF3527178'),
('+916260553606', 'SSF2805332'),
('+916202510224', 'SSF5490905'),
('+917355417883', 'SSF3051724'),
('+917879323351', 'SSF3613352'),
('+917771003379', 'SSF3482712'),
('+917766090492', 'SSF3148488'),
('+917850929296', 'SSF5347742'),
('+918210116412', 'SSF5319754'),
('+918603938436', 'SID951376091523'),
('+918854851877', 'SSF5277186'),
('+918445976735', 'SID951376103546'),
('+918083191713', 'SSF3027576'),
('+918107087537', 'SID951375934752'),
('+919661853818', 'SSF3184865'),
('+919117660073', 'SSF5495128'),
('+919080311338', 'SSF5383554'),
('+919399587257', 'SID951375926141'),
('+919737956179', 'SSF4157800'),
('+919303065381', 'SSF5473787'),
('+919234196009', 'SSF5364376'),
('+919161398640', 'SSF6162186'),
('+916376173353', 'SSF5201742'),
('+916207479992', 'SSF2449939'),
('+916200223524', 'SSF3135009'),
('+917737655749', 'SSF5146655'),
('+917023136848', 'SSF5098453'),
('+917070985509', 'SSF5299893'),
('+917986569311', 'SID951374981935'),
('+917054689025', 'SSF5193764'),
('+918619412082', 'SSF3076700'),
('+918955218139', 'SSF5107149'),
('+918809904579', 'SSF2508497'),
('+918210025981', 'SID951373840588'),
('+918529625233', 'SSF5082222'),
('+918757686980', 'SSF3175413'),
('+918690268627', 'SSF5177110'),
('+919216736740', 'SSF5204989'),
('+919636000146', 'SSF5163761'),
('+919116998335', 'SSF5217708'),
('+919116476844', 'SSF5163746'),
('+919142541806', 'SSF3405293'),
('+919773384471', 'SSF5107093'),
('+919162140037', 'SSF3835864'),
('+919064963060', 'SSF3381339'),
('+919263047525', 'SID951375623974'),
('+919660041568', 'SSF5117137'),
('+919649792789', 'SID951374557026'),
('+919241836268', 'SSF5153619'),
('+919096665979', 'SSF3125530'),
('+919905243138', 'SID951374405861'),
('+919234792622', 'SSF5191030'),
('+917007794575', 'SSF6046246'),
('+919782644751', 'SSF4931917'),
('+919135504519', 'SSF3211133'),
('+916205813632', 'SSF5719099'),
('+916261078279', 'SSF2416518'),
('+916319643344', 'SID951376154396'),
('+917782885813', 'SID951375535465'),
('+917877853105', 'SSF4696331'),
('+917229955063', 'SID951376126799'),
('+918953054566', 'CID951376205612'),
('+918651321458', 'SID951375422755'),
('+918302238942', 'SSF2483713'),
('+918307610788', 'SSF4656040'),
('+919059821264', 'SSF4773338'),
('+919680282568', 'SID951374846781'),
('+919784688032', 'SSF2356547'),
('+919699494964', 'SID951375769969'),
('+919636755105', 'SSF4906371'),
('+919509624935', 'SSF2855712'),
('+919684884848', 'SID951375628027'),
('+919660463539', 'SSF4757640'),
('+917828294103', 'SID951375937687'),
('+917828300963', 'SID951375387111'),
('+917878089650', 'SSF4623602'),
('+917347010317', 'SSF2587948'),
('+918890425306', 'SID951375587595'),
('+918815855407', 'SSF3480843'),
('+918092548424', 'SSF2673636'),
('+919178223585', 'SSF4566158'),
('+919116645345', 'SSF4457741'),
('+919216704469', 'SSF4623420'),
('+919828426808', 'SSF4591279'),
('+919950851250', 'SSF2559699'),
('+916377859831', 'SSF4383280'),
('+919983655850', 'SSF2530026'),
('+916377585978', 'SSF4136152'),
('+918003981280', 'SSF4219456'),
('+919799841601', 'SSF3916789'),
('+919648531684', 'CID951376209813'),
('+919001306976', 'SID951375883832'),
('+917073881472', 'SSF4158358'),
('+919335234487', 'SID951376059554'),
('+919812075067', 'SID951376043102'),
('+918745830095', 'SID951373870765'),
('+917050323664', 'SID951375630708'),
('+917739568525', 'SID951374551731'),
('+919636532346', 'SID951374973476'),
('+919136504262', 'SID951375688105'),
('+917067219533', 'SID951375950488'),
('+917223046619', 'SSF2841423'),
('+917543001989', 'SID951374515908'),
('+918303952639', 'SSF2959469'),
('+918290309156', 'SSF2718608'),
('+919931176824', 'SID951376137034'),
('+916207117432', 'SSF6349381'),
('+916299788608', 'SSF3011681'),
('+916299274400', 'SSF6307986'),
('+916376571684', 'SSF6205468'),
('+916267710042', 'SSF4079477'),
('+916260879019', 'SSF3639530'),
('+917070071616', 'SSF6230942'),
('+917367998906', 'SSF6344212'),
('+917496017673', 'SSF6276383'),
('+917050892780', 'SSF3084941'),
('+917765913365', 'SSF6293837'),
('+917557764133', 'SSF6118676'),
('+918528247303', 'SSF6288727'),
('+918931824488', 'SSF6288027'),
('+918292559910', 'SSF6205222'),
('+919753839541', 'SSF6329417'),
('+919534229369', 'SSF3814216'),
('+919079621538', 'SSF6298372'),
('+919031273619', 'SSF4506529'),
('+919918731415', 'SSF3916191'),
('+919321189078', 'SSF4601163'),
('+919504084799', 'SID951375724003'),
('+919005221148', 'SSF5727674'),
('+919936929085', 'SSF3706363'),
('+919519594624', 'SSF3237798'),
('+919896366950', 'SSF3230266'),
('+919153900674', 'SID951373177681'),
('+919931829546', 'SSF6192161'),
('+919693248909', 'SSF6313009'),
('+917489397190', 'SID951373145966'),
('+918252717239', 'CID211204742'),
('+919102764787', 'SID2125562537'),
('+919936691658', 'SSF4463249'),
('+916207109265', 'SID951375053802'),
('+917070405234', 'SID951374945042'),
('+917458804898', 'SID951373964272'),
('+919263449461', 'SID951374644441'),
('+919302674879', 'SID951375609913'),
('+916202804531', 'SSF2679722'),
('+916299048122', 'SSF2642686'),
('+917677458671', 'SSF2499357'),
('+917762002733', 'SSF2770736'),
('+917460856784', 'SSF2853073'),
('+917082769166', 'SSF2405504'),
('+917761915842', 'SSF2836392'),
('+918538949574', 'SSF2353888'),
('+918770534894', 'SSF2662787'),
('+918969546643', 'SID951375950990'),
('+919508870876', 'SSF2642034'),
('+919794783491', 'SSF2864869'),
('+919592843296', 'SID951376043869'),
('+919631740840', 'SSF2742409'),
('+916204219730', 'SSF3810356'),
('+916390196569', 'SSF3812605'),
('+916202428034', 'SSF6199645'),
('+916261548269', 'SSF4066835'),
('+917250864040', 'SSF6208411'),
('+917634940195', 'SSF6209521'),
('+917870398228', 'SSF3462519'),
('+917061769286', 'SSF6223524'),
('+917999007014', 'SSF4463604'),
('+917309902954', 'SSF3631730'),
('+917352358141', 'SSF6189522'),
('+917745907110', 'SSF4211688'),
('+917256873533', 'SSF3108035'),
('+917543926147', 'SSF6141654'),
('+917091959881', 'SSF3055675'),
('+917870599975', 'SSF3052387'),
('+917070666414', 'SSF3863534'),
('+918603322608', 'SSF6185958'),
('+918839866231', 'SSF3671142'),
('+918603244387', 'SSF4130300'),
('+918815547955', 'SSF6242463'),
('+918603890236', 'SSF6183652'),
('+918252778603', 'SSF6301912'),
('+918287506908', 'SSF3147245'),
('+918075852843', 'SSF6180714'),
('+918103596281', 'SSF4463677'),
('+918815783400', 'SSF3700952'),
('+918226802891', 'SSF6148065'),
('+918955648783', 'SSF3399931'),
('+919263039982', 'SSF3944816'),
('+919244294067', 'SSF4011785'),
('+919175793923', 'SSF4045279'),
('+919341853974', 'SSF3157142'),
('+919508080963', 'SSF3221323'),
('+919798293943', 'SSF5969198'),
('+919111989136', 'SSF2915464'),
('+919353597628', 'SSF3038985'),
('+919939648922', 'SSF3096853'),
('+919508504173', 'SSF4223502'),
('+919546256541', 'SSF4255885'),
('+919238755312', 'SSF6180505'),
('+919589329292', 'SSF4059210'),
('+919798632672', 'SSF3028401'),
('+919685005768', 'SSF6182631'),
('+919306135581', 'SSF3497038'),
('+916394167140', 'SSF6256608'),
('+916202773561', 'SSF4747074'),
('+917766825868', 'SSF6238300'),
('+916268930628', 'SID951374708720'),
('+917894987291', 'SSF2407209'),
('+919116475717', 'SSF2677220'),
('+916263793910', 'SSF3050258'),
('+916200091011', 'SSF2884810'),
('+916263944139', 'SSF3975510'),
('+916376013175', 'SSF5869191'),
('+917879431371', 'SID951373308458'),
('+917856045350', 'SSF4374301'),
('+917898168080', 'SSF3934039'),
('+919555850603', 'SSF6166622'),
('+918252163748', 'SSF6149007'),
('+916283338421', 'SSF4864519'),
('+916203172595', 'SSF2658758'),
('+918737900257', 'SSF4036741'),
('+918303072075', 'SSF2788183'),
('+918235825308', 'SSF2609030'),
('+918305094853', 'SID951374111806'),
('+919098313575', 'SSF3762355'),
('+919693002491', 'SID951375954149'),
('+919304706656', 'SSF3060824'),
('+919931049295', 'SID951374182903'),
('+919162832787', 'SSF2891190'),
('+918294290266', 'SSF4129405'),
('+917258846913', 'SSF6398574'),
('+918905468744', 'SSF4862297'),
('+917634063508', 'SSF4801537'),
('+916205168427', 'SSF6224105'),
('+916263512118', 'SID951375900739'),
('+916267683920', 'SSF5347092'),
('+916268957432', 'SSF5326604'),
('+916206378239', 'SID2125472739'),
('+917073283506', 'SSF2785030'),
('+917340556419', 'SSF2408103'),
('+918809111021', 'SID951375534033'),
('+918863986928', 'SSF2575945'),
('+919835277708', 'SSF3062755'),
('+919507131685', 'SSF5395763'),
('+919343344991', 'SID951375279610'),
('+919933135514', 'SSF3935050'),
('+919113349219', 'SSF3411747'),
('+919602818060', 'SSF4364341'),
('+919238085204', 'SSF5603534'),
('+919006756088', 'SSF3067553'),
('+919534490416', 'SSF5296159'),
('+919109328384', 'SSF5399387'),
('+918176015618', 'SSF4717186'),
('+917200187593', 'SSF6239958'),
('+916265339448', 'SSF5163635'),
('+916207509066', 'SSF4992582'),
('+917023760764', 'SSF5164075'),
('+917357576694', 'SSF5146621'),
('+917489377344', 'SID951374094812'),
('+917479877505', 'SSF2405580'),
('+917851827582', 'SID951375598954'),
('+918769471142', 'SSF5203882'),
('+918769706433', 'SSF5098388'),
('+918469191586', 'SID951375306175'),
('+918780712433', 'SID951374856912'),
('+918521201987', 'SSF3303441'),
('+918813898061', 'SSF5102104'),
('+919784631698', 'SSF5107117'),
('+919279241361', 'SSF5461140'),
('+919829690891', 'SSF3002901'),
('+919587480922', 'SID951375597977'),
('+919341684244', 'SSF5102012'),
('+919653921330', 'SSF2479367'),
('+919548665492', 'SID951375045721'),
('+919835469564', 'SSF2934980'),
('+919546894383', 'SID951375763359'),
('+919511561131', 'SSF5130398'),
('+918000377480', 'SSF4958622'),
('+918769909039', 'SSF4898153'),
('+919675527354', 'SSF4943190'),
('+919784694041', 'SSF5067821'),
('+917881177125', 'SSF2812676'),
('+918000694014', 'SSF2350263'),
('+918233437042', 'SSF3932988'),
('+919693553228', 'CID211200142'),
('+919511311871', 'SID951374255652'),
('+918962995435', 'SID951375599156'),
('+916203634611', 'SSF4568599'),
('+917091775164', 'SSF4565849'),
('+917091716286', 'SSF2333322'),
('+917898322488', 'CID261400904'),
('+918128098852', 'SSF2411831'),
('+918000905395', 'SSF4620082'),
('+918764737448', 'SSF4435607'),
('+918686899876', 'SSF2409080'),
('+919352614602', 'SSF4609993'),
('+919588863250', 'SSF4457956'),
('+917296807663', 'SSF4355646'),
('+918829942742', 'SSF3922037'),
('+918179360687', 'SSF3696992'),
('+916261545511', 'CID080604139'),
('+918871401521', 'SSF2720509'),
('+919301969943', 'SSF2388138'),
('+917869210630', 'CID122501583'),
('+917879929785', 'SSF4085433'),
('+918719936489', 'SSF3139748'),
('+918815742280', 'SSF3392282'),
('+918770595918', 'SSF4333077'),
('+919244943895', 'SSF3427767'),
('+919713126768', 'SSF3088170'),
('+918815408871', 'SSF4499992'),
('+917610765193', 'CID128702162'),
('+919754754434', 'SID951373525090'),
('+919109524426', 'SSF3693777'),
('+918829986303', 'SSF4745515'),
('+919508734048', 'SID951375004628'),
('+919399964355', 'SSF2877252'),
('+918817937404', 'SID951374577489'),
('+919755665526', 'SID2125159125'),
('+917746971706', 'SID951374317988'),
('+919950290100', 'SID951376111430'),
('+918866639209', 'SID951373958784'),
('+919303763605', 'SSF3714418'),
('+917759997579', 'SSF3263609'),
('+917879247875', 'SSF4035674'),
('+919305688134', 'SSF6081777'),
('+919644412747', 'SSF3862304'),
('+919244137631', 'SSF4904811'),
('+919122243397', 'SSF3353717'),
('+918102283457', 'SSF4370021'),
('+916263602567', 'SSF3632809'),
('+919302477493', 'SID951373310599'),
('+919565609970', 'SSF2894724'),
('+919797776677', 'SSF2863368'),
('+919826314614', 'SSF4021861'),
('+918303437291', 'SSF5192607'),
('+919523207564', 'SSF4482683'),
('+919340600491', 'SSF3982378'),
('+919669487971', 'SID951375909497'),
('+918932045192', 'SSF5600889'),
('+917726920085', 'SSF3629525'),
('+917000771861', 'SID2125045794'),
('+917480830932', 'SID951375728852'),
('+919918247864', 'SSF4800428'),
('+919343392414', 'SID951376225283'),
('+919122985338', 'SSF4721970'),
('+919685913705', 'CID038502058'),
('+917408880064', 'SSF2859437'),
('+917307131336', 'SSF4829260'),
('+919294629886', 'SSF3834158'),
('+918871668264', 'CID081903010'),
('+918717923681', 'SSF3441326'),
('+919939614962', 'SSF4527511'),
('+919792166451', 'SSF3101693'),
('+917067293711', 'SSF2611165'),
('+918690477265', 'SSF2561563'),
('+919621767595', 'SID951374875052'),
('+916299224667', 'SID951373309547'),
('+918109753433', 'SID951375495038'),
('+919783739030', 'SSF3781587'),
('+917723059780', 'CID213703109'),
('+918470985309', 'SID951374235098'),
('+917389961696', 'SSF3429886'),
('+917607592217', 'SSF2740604'),
('+919690738552', 'SSF3567840'),
('+919602026357', 'SSF3583706'),
('+918271525186', 'SSF6158423'),
('+917509385381', 'SSF3156420'),
('+917029520266', 'SSF4492853'),
('+917296035664', 'SSF4780380'),
('+919610539132', 'SSF2548023'),
('+919522808067', 'CID061106698'),
('+919462244456', 'SSF2769631'),
('+918966086098', 'SSF3245119'),
('+917339823799', 'SSF3804091'),
('+917805938251', 'SSF5014119'),
('+919179017562', 'SID951375979547'),
('+919648466464', 'SID951373024305'),
('+916260454501', 'SSF3432216'),
('+919301529697', 'SID951375081018'),
('+918890584611', 'SSF4315942'),
('+919303054060', 'SSF2998406'),
('+916266469634', 'SSF4055541'),
('+917723804335', 'SID951376129720'),
('+918238576911', 'SID951375236928'),
('+916232559492', 'CID053202377'),
('+918604834702', 'SSF4455386'),
('+918824384024', 'SSF2877479'),
('+918435625237', 'SID2125559707'),
('+917050572310', 'SID951374006870'),
('+919026894775', 'SSF2417071'),
('+916207835225', 'SID951375390976'),
('+918128840791', 'SSF3267094'),
('+918707242645', 'SSF3746829'),
('+918690557527', 'SID951375950390'),
('+919644042266', 'SSF3516845'),
('+919905478983', 'SSF3353999'),
('+916207848269', 'SID951374335148'),
('+919135317510', 'SSF3877006'),
('+918434998007', 'SSF2945780'),
('+919329833070', 'SSF3707591'),
('+916201143291', 'SSF3807361'),
('+919205082782', 'SID951375857331'),
('+918757140874', 'SSF3144466'),
('+917974172956', 'SSF4011793'),
('+919244070709', 'SSF3626160'),
('+917015479281', 'SID951376013452'),
('+917004335048', 'SID951373438485'),
('+917761841446', 'SSF2365604'),
('+917414029496', 'SID951374733343'),
('+918881659932', 'SSF4439298'),
('+917352715005', 'SSF2753558'),
('+918471805537', 'SSF3348472'),
('+917652989741', 'SSF3213638'),
('+919065078912', 'SID951376028265'),
('+919186497656', 'SSF3202738'),
('+918319028710', 'SID951373123704'),
('+917566465317', 'SID951375520662'),
('+916202085594', 'SSF3091322'),
('+919302144416', 'SSF2695969'),
('+917860371519', 'SSF4288674'),
('+919905506479', 'SID951372939042'),
('+918824704879', 'SSF2823382'),
('+917049413177', 'SID951374610757'),
('+917033513775', 'SID951375476922'),
('+919302023907', 'SSF3014545'),
('+919117643277', 'SSF5010224'),
('+918982163475', 'SSF2283605'),
('+919241370517', 'SSF3571365'),
('+917999771436', 'SID112141'),
('+919352100565', 'SSF3960915'),
('+918264987747', 'SSF2725784'),
('+916231644046', 'SSF3493255'),
('+919262671519', 'SID951376040171'),
('+918276073783', 'SID951373227438'),
('+917645978531', 'SSF2888070'),
('+918235606148', 'SSF2407388'),
('+917412884869', 'SSF3876526'),
('+917739760598', 'SSF3211219'),
('+917393915326', 'SSF6144779'),
('+917379062890', 'SSF6189434'),
('+918209356644', 'SSF3180689'),
('+918235692966', 'SSF3268576'),
('+918889599857', 'SSF6136594'),
('+918127477419', 'SSF6189195'),
('+918305732471', 'SSF6199914'),
('+918824619554', 'SID951375883853'),
('+919883917361', 'SSF3197440'),
('+919199705112', 'SSF3011224'),
('+919661279644', 'SSF4194959'),
('+919303337974', 'SSF4037083'),
('+919755634853', 'SSF3456612'),
('+918871128782', 'SSF4017013'),
('+919672308054', 'SSF4458819'),
('+919523305281', 'SSF4000260'),
('+919343288489', 'SSF4061840'),
('+919993084388', 'SSF3068560'),
('+919576991987', 'SSF4782588'),
('+917004144119', 'SSF6255161'),
('+918271377561', 'SSF4554047'),
('+919939156280', 'SSF6255274'),
('+919708367938', 'CID171507052'),
('+917587056965', 'SID951375287351'),
('+919279651278', 'SID951375510004'),
('+916263737559', 'SSF2630278'),
('+917564809981', 'SID951376095894'),
('+919835444696', 'SSF2906355'),
('+917518760787', 'SSF3389482'),
('+918795304570', 'SSF4661993'),
('+918766261407', 'SSF4267825'),
('+919241722116', 'SSF4701854'),
('+916206589775', 'SSF4622960'),
('+916203073290', 'SSF2910449'),
('+916378712530', 'SSF3928178'),
('+917828884031', 'SSF3969020'),
('+917970866063', 'SSF3816483'),
('+917425807922', 'SSF2877536'),
('+918252080869', 'CID951376205341'),
('+918252819745', 'SSF3248799'),
('+919752268026', 'SSF5698730'),
('+919234767396', 'SSF3935441'),
('+919104136291', 'SSF3423284'),
('+919279667951', 'SSF3351677'),
('+919006628805', 'SSF3063846'),
('+916390976216', 'SSF4066818'),
('+916267898899', 'SSF2944707'),
('+917427012372', 'SSF3838197'),
('+917224807501', 'SSF2823663'),
('+917352462364', 'SSF3393066'),
('+917070316494', 'SSF3478237'),
('+917302879962', 'SSF2923179'),
('+918373994589', 'SID951376109270'),
('+918789831664', 'SSF3155360'),
('+919151167151', 'SSF5857421'),
('+919122683181', 'SSF3630222'),
('+919662483459', 'SSF3723126'),
('+919571703901', 'SID951376045846'),
('+919724087079', 'SID951375308415'),
('+919234101087', 'SSF5058713'),
('+918603965474', 'SSF6389338'),
('+918319334347', 'SSF3708328'),
('+919155649981', 'SSF5263500'),
('+916306135896', 'SSF5498688'),
('+916205518201', 'SSF3818822'),
('+916267013055', 'SSF3371388'),
('+917633887095', 'SSF3210244'),
('+917321903014', 'SSF3242763'),
('+917999052955', 'SSF3103676'),
('+918438126496', 'SSF5614603'),
('+918002517897', 'SSF3156076'),
('+918770337334', 'SSF3366955'),
('+918757422136', 'SID951376201166'),
('+919661485588', 'SID951375392850'),
('+919351696117', 'SID951375345103'),
('+919265653194', 'SSF2436446'),
('+919301070487', 'SSF5603036'),
('+919060706794', 'SID951372819270'),
('+919352392985', 'SSF3272934'),
('+919770775009', 'SSF5113360'),
('+919598966608', 'SSF3355684'),
('+919302610029', 'SSF5281442'),
('+919238063188', 'SSF5322647'),
('+917986777268', 'SSF6334735'),
('+916378018724', 'SSF5088142'),
('+916299961813', 'SID951375790800'),
('+917033894638', 'SID951376110248'),
('+917870462753', 'SSF2399915'),
('+918003722882', 'SSF5088122'),
('+918432471461', 'SSF5399496'),
('+918269690690', 'SID951375956243'),
('+918302733465', 'SSF2483843'),
('+919473755979', 'SSF3517966'),
('+919102322395', 'SSF3325930'),
('+919587447550', 'SSF5106702'),
('+919119262405', 'SSF2821302'),
('+917765040396', 'SSF2285773'),
('+919060121422', 'SSF3197492'),
('+916376054228', 'SSF2907353'),
('+918290899018', 'SID951374382056'),
('+918905220508', 'SSF2898279'),
('+918959997132', 'SSF3246180'),
('+919657648048', 'SID951375422441'),
('+919640734435', 'SID951374921593'),
('+919065914186', 'SID951373316155'),
('+919351111698', 'SSF2375499'),
('+919680553351', 'SID951375714281'),
('+916205962263', 'SSF3199650'),
('+917877973951', 'SSF4733644'),
('+917250963258', 'SSF2282783'),
('+917073292136', 'SSF4464194'),
('+917742113321', 'SID951375487283'),
('+918218254677', 'SSF2300205'),
('+918289856882', 'SSF2300285'),
('+918103145812', 'SSF4505254'),
('+918602252523', 'SSF4547777'),
('+919984840449', 'SSF2492632'),
('+919523252600', 'SID951375619826'),
('+917023368261', 'SSF2553392'),
('+919866568855', 'SID951375867952'),
('+919302014638', 'SID951374063518'),
('+917986527601', 'SSF4077594'),
('+917479729616', 'SID951373796702'),
('+917725807351', 'SID951375851005'),
('+917427023053', 'SID951375111884'),
('+918815563587', 'SID951375161317'),
('+919153263949', 'SID951374763913'),
('+919102856891', 'SID951374431843'),
('+916205689702', 'SID951376005143'),
('+918388875451', 'SSF3022172'),
('+919693373658', 'SSF2635970'),
('+916205804831', 'SSF2972965'),
('+916268539823', 'SSF3494094'),
('+917543078387', 'SSF3806287'),
('+917667207973', 'SSF4050185'),
('+917479910972', 'SID951375641425'),
('+917004369743', 'SSF4077507'),
('+918695838205', 'SSF3963317'),
('+918461079780', 'SID951374413194'),
('+918817471492', 'SID951373084655'),
('+918949641847', 'SSF4033806'),
('+918109857656', 'SSF3940099'),
('+918319875403', 'SSF3146505'),
('+919646404362', 'SID951374803349'),
('+919322902609', 'SSF3988954'),
('+919302981414', 'SSF6136821'),
('+919798225467', 'SSF4289712'),
('+917061792453', 'CID262701580'),
('+917209648488', 'SID951374039830'),
('+917257012248', 'SID951374429360'),
('+917489040335', 'SID951374942370'),
('+918709881316', 'SID951375470813'),
('+919128296526', 'SID951374763887'),
('+916203878402', 'SSF2923950'),
('+917294944958', 'SSF2408316'),
('+918409426192', 'SSF2857636'),
('+918757017174', 'SID951376124168'),
('+919693368263', 'SSF2786906'),
('+919973452878', 'SSF2903666'),
('+919667947715', 'SSF2892056'),
('+919973807683', 'SSF2864287'),
('+919905623420', 'SSF2928588'),
('+919931817341', 'SSF2857758'),
('+919279614988', 'SSF2575913'),
('+916202671298', 'SSF3943465'),
('+916266238168', 'SSF6007026'),
('+916232976009', 'SSF3945493'),
('+916263040447', 'SSF3605120'),
('+917489139664', 'SSF4005236'),
('+917470356796', 'SSF4060015'),
('+917050052446', 'SSF3031694'),
('+917782074054', 'SSF3697095'),
('+917470551965', 'SSF3989876'),
('+917033168897', 'SSF6172653'),
('+918104348747', 'SSF3230640'),
('+918976126698', 'SSF2928464'),
('+918252086700', 'SSF3784549'),
('+919302267770', 'SSF4085722'),
('+919131888316', 'SSF4193475'),
('+919709557304', 'SSF3567653'),
('+919919592796', 'SSF2896314'),
('+919098091059', 'SSF4163334'),
('+919120222064', 'SSF5875392'),
('+919708359027', 'SSF4609818'),
('+919031692154', 'SSF4147751'),
('+919135442346', 'SSF6020896'),
('+918934892813', 'SSF5222894'),
('+919798577949', 'SSF4715262'),
('+919344979584', 'SSF6294929'),
('+919931259592', 'SSF4839125'),
('+919608001971', 'SSF4719405'),
('+919098221311', 'SID2231'),
('+917667999160', 'SSF3602944'),
('+918529650417', 'SID951375532189'),
('+919648335128', 'SSF3124441'),
('+919554655079', 'SSF2905042'),
('+916307762481', 'SSF4563139'),
('+917970605928', 'SSF5818261'),
('+917724083866', 'SID951375956926'),
('+917773082221', 'SID951376199758'),
('+918521083293', 'SSF3033403'),
('+919798504619', 'SID951375940400'),
('+919693856837', 'SSF3097538'),
('+919173834691', 'SID951375867292'),
('+919651580075', 'SSF3231055'),
('+917979710388', 'SSF4508855'),
('+917408054201', 'SSF4639029'),
('+917856895655', 'SSF5923513'),
('+917643890598', 'SSF5819782'),
('+916299967547', 'SSF3198048'),
('+916204284391', 'SSF2638488'),
('+917879495360', 'SSF3305507'),
('+917061064109', 'SSF3563339'),
('+917879439092', 'SSF3518608'),
('+917992458485', 'SSF2595774'),
('+918955731965', 'SID951375438399'),
('+918889979637', 'SSF5686606'),
('+918434733248', 'SID951376153212'),
('+918889130273', 'SID951375642467'),
('+919708991834', 'SSF5545007'),
('+919778583437', 'SID951375509488'),
('+919102653152', 'SSF3460466'),
('+919162152402', 'SSF3373014'),
('+919303524482', 'SSF5189810'),
('+919576577620', 'SSF3650138'),
('+919234834317', 'SSF3142840'),
('+916564994646', 'SID951374841331'),
('+916377432943', 'SSF3354989'),
('+917665602746', 'SSF3254914'),
('+917857894474', 'SSF3644079'),
('+917256882113', 'SSF3175479'),
('+917414057528', 'SSF2761847'),
('+917209367390', 'SSF2430531'),
('+918955551649', 'SSF3226515'),
('+918290669101', 'SSF3323863'),
('+918294774938', 'SSF3333613'),
('+918539931197', 'SSF2890708'),
('+918790760430', 'SID951374880614'),
('+919057283661', 'SSF5088070'),
('+919636652158', 'SSF5088099'),
('+919955477039', 'SSF2400176'),
('+919777860263', 'SID951374763538'),
('+919004408456', 'SSF2730862'),
('+919142115150', 'SSF5125123'),
('+919351059963', 'SSF2340751'),
('+917696047309', 'SSF5045340'),
('+917462008214', 'SSF4390061'),
('+918279226932', 'SSF2854894'),
('+919548467876', 'SID951375276536'),
('+919065631686', 'SSF4722039'),
('+919875442213', 'SID951375882487'),
('+916586868606', 'SID951376142595'),
('+918655322143', 'SID951374617977'),
('+919835256324', 'SID951375993410'),
('+918757843494', 'SID951375036380'),
('+918949358787', 'SSF2679275'),
('+919119379416', 'SSF4285843'),
('+917296977020', 'SSF2378840'),
('+918000854649', 'SSF2550954'),
('+919610145306', 'SSF3219921'),
('+919024818201', 'SSF2367011'),
('+919770696587', 'SSF2844270'),
('+916267159503', 'SSF6174310'),
('+916267899176', 'SSF3262401'),
('+917692884497', 'SSF4058377'),
('+917804054622', 'SSF3441774'),
('+918109320814', 'SSF3685806'),
('+918817584176', 'SSF3661535'),
('+918602526135', 'SSF3552559'),
('+918718083055', 'SSF4144718'),
('+918461825379', 'SSF3194859'),
('+919584457202', 'SSF2830751'),
('+919329694189', 'SSF6169209'),
('+918823049152', 'SSF2900650'),
('+919171644035', 'SID951374571532'),
('+919572552870', 'SID951374555886'),
('+919026771574', 'SSF4781968'),
('+917724800234', 'CID118112477'),
('+917015642074', 'SSF4733259'),
('+917440962721', 'SID951373608179'),
('+916263094418', 'SID951373121639'),
('+919926259848', 'CID204901959'),
('+917667329039', 'SSF2714059'),
('+918815396078', 'SID951373258093'),
('+918871457331', 'SID951374069202'),
('+917879869221', 'SID951374573498'),
('+919511516972', 'SID951375930582'),
('+919993202651', 'CID191605743'),
('+916263766893', 'SSF5600358'),
('+917987646649', 'SID951373948662'),
('+917804991182', 'SID951374931518'),
('+917009011312', 'SSF3211036'),
('+919631657290', 'SID951374947261'),
('+919174468588', 'SID2125156650'),
('+918434064879', 'SSF4634316'),
('+917687766737', 'SSF3673961'),
('+918429548388', 'SSF5355937'),
('+917999985945', 'SSF4554877'),
('+917484023092', 'SID951376171804'),
('+919794502679', 'SSF4123859'),
('+917352358795', 'SID951375250128'),
('+917828487625', 'SID951375222174'),
('+917974450809', 'SID951373738193'),
('+919565157680', 'SSF3468841'),
('+919685212575', 'SID951374284512'),
('+917258955068', 'SSF2719605'),
('+919685486710', 'SID951375457829'),
('+917828122184', 'SID951373581200'),
('+919098738529', 'CID174507272'),
('+916264413291', 'SID951373866489'),
('+919519026134', 'SSF5038263'),
('+919931166989', 'SSF3391392'),
('+918823082567', 'SID2125327510'),
('+918303647767', 'SSF2870759'),
('+917240157782', 'SSF3094717'),
('+918770866047', 'SID951375914823'),
('+919301644654', 'SID951373975650'),
('+917462945030', 'SID951375034127'),
('+919950141829', 'SID951374941138'),
('+917808484052', 'SSF5014322'),
('+919343933660', 'SID951373799680'),
('+918103154964', 'SID951373429897'),
('+919012054532', 'SSF5470923'),
('+917317341933', 'SSF4771972'),
('+917000925489', 'CID122607354'),
('+918789285731', 'SSF5266197'),
('+919118629716', 'SSF4890464'),
('+918965986570', 'SID951375924121'),
('+918799246955', 'SID951376047680'),
('+916268752133', 'SID951374779910'),
('+916260719119', 'SID951372925033'),
('+918440825392', 'SSF2600950'),
('+919198491606', 'SSF5044634'),
('+916260914583', 'SID2125483525'),
('+919341907709', 'SSF3178834'),
('+917320983559', 'SSF4334490'),
('+919567997676', 'SID951375221144'),
('+917828393169', 'SSF3062198'),
('+918400629246', 'SSF2893383'),
('+919589722349', 'CID129701599'),
('+916263496169', 'SSF5263098'),
('+917568257029', 'SSF2347719'),
('+919519780957', 'SSF3521405'),
('+918949063780', 'SSF3275416'),
('+919116244546', 'SSF4838120'),
('+918797952735', 'SID2125037041'),
('+919569174347', 'SSF5086661'),
('+917412843750', 'SSF4112722'),
('+919391615029', 'SSF4378375'),
('+919473095823', 'SSF5527858'),
('+919682436856', 'SSF5435391'),
('+916264342669', 'SID951373782640'),
('+919060894256', 'SSF3357486'),
('+919437053731', 'SSF2705233'),
('+916262468198', 'SSF2814680'),
('+919835504599', 'SSF3377550'),
('+919196913766', 'SID951373764302'),
('+917497016338', 'SSF3066765'),
('+918423060728', 'SID951375215455'),
('+919219143316', 'SSF3690188'),
('+918002934417', 'SSF3991037'),
('+917879373341', 'SSF3828732'),
('+918757787677', 'SID951375964736'),
('+918484946484', 'SSF2713910'),
('+916204495218', 'SSF3020682'),
('+918102782703', 'SID951373840919'),
('+917757844848', 'CID093708865'),
('+919769797870', 'SSF3491956'),
('+919201636818', 'CID213701362'),
('+917739850454', 'SID951375592908'),
('+918817673228', 'SID951375430564'),
('+917984288757', 'SID951376215049'),
('+917870640760', 'SID951376163362'),
('+919162202054', 'SSF2972761'),
('+916386394767', 'SSF3146855'),
('+917489583245', 'SSF4080748'),
('+917294013494', 'SSF4213751'),
('+917280908475', 'SSF3546961'),
('+917781808277', 'SSF3353276'),
('+918521082576', 'SSF3658452'),
('+918084336662', 'SSF3682794'),
('+918670300506', 'SID951374874076'),
('+918924813561', 'SSF6314809'),
('+918228057446', 'SSF3338689'),
('+919244599108', 'SSF3666839'),
('+919798836713', 'SID951376157740'),
('+919631881847', 'SSF3328297'),
('+919784251907', 'SSF4299355'),
('+919150531712', 'SSF3195221'),
('+919958220339', 'SSF6296399'),
('+916263663246', 'SSF3372739'),
('+918305383164', 'SSF4675400'),
('+918709348365', 'SSF6275212'),
('+919508353907', 'SSF3485488'),
('+919343385813', 'SSF4350133'),
('+919661467294', 'SSF3411286'),
('+919508849454', 'SSF3543221'),
('+919334566043', 'SID951373891645'),
('+919341053349', 'SID951373782656'),
('+916287767464', 'SID951375238801'),
('+917297043414', 'SID951375387113'),
('+919771949549', 'SID951375964385'),
('+917367899840', 'SSF5950049'),
('+918881774538', 'SSF4264957'),
('+918127708530', 'SSF4565342'),
('+919373735845', 'SSF5320280'),
('+919766260158', 'SSF3753570'),
('+917909365982', 'SSF2842271'),
('+918000374080', 'SSF2677262'),
('+919006206932', 'SID951376132853'),
('+919983471137', 'SID951374569029'),
('+919399949764', 'SSF2312666'),
('+917250272168', 'SSF3900538'),
('+917488915346', 'SSF3094475'),
('+917705951976', 'SSF2911674'),
('+918000801695', 'SSF3299368'),
('+919451200492', 'SSF3039004'),
('+919661744906', 'SSF3146601'),
('+919244582142', 'SSF3152256'),
('+919770942846', 'SSF4027614'),
('+919919665162', 'SSF2942665'),
('+919451209334', 'SSF6037607'),
('+916203595546', 'SSF2800253'),
('+916264674461', 'SSF6066978'),
('+917065607238', 'SSF2817558'),
('+917067672447', 'SSF6014751'),
('+917878498244', 'SSF2944790'),
('+917224976673', 'SSF6059761'),
('+917489371902', 'SSF2546258'),
('+917061270821', 'SSF3733359'),
('+917294028013', 'SSF4237707'),
('+917324024669', 'SSF3665264'),
('+918797347909', 'SSF3003303'),
('+918092769390', 'SSF3678816'),
('+918789920343', 'SSF3167460'),
('+918434549114', 'SSF3647780'),
('+918227957192', 'SSF2752852'),
('+918210049062', 'SSF4075526'),
('+919754533672', 'SSF2894984'),
('+919693382035', 'SSF3398283'),
('+919343068548', 'SSF3975724'),
('+919771168184', 'SID951375508977'),
('+919546930539', 'SSF2919586'),
('+919755766745', 'SID951375996453'),
('+919024815094', 'SSF3814277'),
('+919828038320', 'SSF2579273'),
('+919905789048', 'SSF4530276'),
('+919602808231', 'SSF3664302'),
('+919009579558', 'SSF6008847'),
('+919522484625', 'SSF3466284'),
('+916267269045', 'CID040214325'),
('+917368849615', 'SID951372795729'),
('+919102651410', 'SSF4770835'),
('+916268241610', 'SSF3627325'),
('+917209783301', 'SSF2590078'),
('+917647095623', 'SID951374774762'),
('+917762948288', 'SSF3099067'),
('+917970486473', 'SID951374957415'),
('+917903440228', 'SSF3689887'),
('+918839218688', 'SSF3425114'),
('+918128901706', 'SSF5163793'),
('+918319033933', 'SSF3355624'),
('+919166395491', 'SID951375404742'),
('+919752714504', 'SID951374523965'),
('+919304391672', 'SSF6151605'),
('+916203427731', 'SID951376193590'),
('+917070448032', 'SSF2494549'),
('+917073898723', 'SSF3099266'),
('+917667934421', 'SSF2346098'),
('+917372020320', 'SSF4650464'),
('+917358748308', 'SSF3304514'),
('+917675786484', 'SID951374690424'),
('+917870863745', 'SID951376215773'),
('+917033586495', 'SSF2580278'),
('+918969347552', 'SID951375267819'),
('+918369900169', 'SSF2949394'),
('+918207727675', 'SSF3150820'),
('+919982774602', 'SSF5270821'),
('+919199017211', 'SSF2605038'),
('+919471168059', 'SSF3320770'),
('+916204067261', 'SSF2886382'),
('+919153592764', 'SID951373194023'),
('+916204025346', 'SSF3107257'),
('+917340363478', 'SID951375574396'),
('+917061998902', 'SSF2870388'),
('+917568424003', 'SSF2599924'),
('+918955486483', 'SID951376154818'),
('+918854803139', 'SSF3046312'),
('+918709312220', 'SSF3704327'),
('+918817256165', 'SID951375452133'),
('+918003712953', 'SSF3028225'),
('+918349603031', 'SID951373829128'),
('+919555676326', 'SSF2984360'),
('+919057269425', 'SSF3039862'),
('+919310464348', 'SID951374690151'),
('+919558024662', 'SID951374846920'),
('+919351443411', 'SID951375882202'),
('+917073449994', 'SSF2722841'),
('+917425893146', 'SID951374521947'),
('+919294656323', 'SSF3820349'),
('+917903172247', 'SID951374185936'),
('+919992319763', 'SID951375883929'),
('+919454545457', 'SID951375214520'),
('+918566468988', 'SSF2350261'),
('+917542071858', 'SID951375495284'),
('+919549930172', 'SID951375458561'),
('+919262236516', 'SID951374543190'),
('+917209697595', 'SSF2877180'),
('+917413803067', 'SSF2806356'),
('+918102710344', 'SSF2337067'),
('+918303470376', 'SSF2587180'),
('+919559375149', 'SSF2924418'),
('+919125622851', 'SSF2596079'),
('+919360508384', 'SSF2377029'),
('+916204124646', 'SSF6292476'),
('+916264248867', 'SSF4167065'),
('+917761897370', 'SSF3022152'),
('+917061240171', 'SSF3369537'),
('+917689865829', 'SSF3968829'),
('+918210057860', 'SSF2937069'),
('+918102252793', 'SSF3189869'),
('+918789657625', 'SID951374849073'),
('+918848635803', 'SSF3573351'),
('+918709627387', 'SSF4122100'),
('+918889588467', 'SSF4243685'),
('+919559025464', 'SSF3476607'),
('+919198858759', 'SSF3200273'),
('+917091654303', 'SID951374389976'),
('+918349157008', 'SID951375600665'),
('+916299692352', 'SID951376163630'),
('+919983515911', 'SSF2723023'),
('+919752894021', 'SID951373774028'),
('+919929497213', 'SSF2587905'),
('+919955390515', 'SSF2767139'),
('+916207166224', 'SSF3838505'),
('+916206459884', 'SSF3480131'),
('+916267569994', 'SSF2926538'),
('+916264011918', 'SSF6333092'),
('+917004008967', 'SSF3885532'),
('+917267863638', 'SSF3918498'),
('+917367896247', 'SSF3285929'),
('+917462943517', 'SSF4012137'),
('+917250459229', 'SSF3384424'),
('+917089693495', 'SSF4381930'),
('+917319874913', 'SSF3105505'),
('+918434827369', 'SSF3953837'),
('+918210816547', 'SSF3464029'),
('+918294381806', 'SSF3466365'),
('+919329346825', 'SSF3659891'),
('+919341112825', 'SSF3212779'),
('+919110998554', 'SSF3022029'),
('+919155937712', 'SID951374725529'),
('+919708049082', 'SSF3800494'),
('+919608546917', 'SID951375765484'),
('+919341737701', 'SSF3406470'),
('+919140252962', 'SSF4380167'),
('+919060096105', 'SSF3800120'),
('+919328194463', 'SSF3376767'),
('+919617888210', 'SSF6332954'),
('+919939068647', 'SSF4699803'),
('+917023304660', 'SSF3299390'),
('+918959961411', 'SID951373783859'),
('+918107893562', 'SSF3901796'),
('+919955908210', 'SID951375899686'),
('+919523897751', 'SSF3111185'),
('+919251748921', 'SSF3028136'),
('+919546588717', 'SSF4660220'),
('+917028127682', 'SSF4221937'),
('+916202710151', 'SID951376212094'),
('+916378642093', 'SSF3696153'),
('+917321933627', 'SSF3060905'),
('+918601915611', 'SSF2740952'),
('+918340446936', 'SSF2913319'),
('+918757259389', 'SSF4203209'),
('+918305759089', 'SSF6072434'),
('+919993643392', 'SSF3553352'),
('+919523835698', 'SSF3075676'),
('+919343101346', 'SSF6066885'),
('+919329889520', 'SID951375681315'),
('+919798726335', 'SSF2953350'),
('+919835242951', 'SSF2619800'),
('+919004698158', 'SSF4502271'),
('+919358072839', 'SSF4187811'),
('+918303407518', 'SSF4735515'),
('+917095462329', 'SSF5392091'),
('+917091759818', 'SSF4271813'),
('+916207235973', 'SSF3637504'),
('+916376501677', 'SSF2793522'),
('+917828431861', 'SSF3576232'),
('+917782887612', 'SSF3629113'),
('+917489878030', 'SSF3755243'),
('+917000446526', 'SSF3168100'),
('+917470665041', 'SSF3472657'),
('+918690972038', 'SID951375756010'),
('+918002219065', 'SID951375232692'),
('+918529553196', 'SID951374538674'),
('+918840714615', 'SSF5436476'),
('+918382919162', 'SSF4446879'),
('+916367945393', 'SID951375223382'),
('+916206799209', 'SSF2974938'),
('+918209105715', 'SSF3187817'),
('+918464618876', 'SID951375683219'),
('+919950548887', 'SID951375894492'),
('+919955325745', 'SID951374251260'),
('+919509462157', 'SID951374522577'),
('+919784348234', 'SID951375302811'),
('+919302981904', 'SSF3144096'),
('+916565656464', 'SID951375336976'),
('+918302020480', 'SID951375971061'),
('+919142005173', 'SID2125752914'),
('+916375229395', 'SSF2573564'),
('+918249224904', 'SID951374909182'),
('+919648754694', 'SID951375267372'),
('+917073514748', 'SSF2438080'),
('+919864345761', 'SID951374729412'),
('+919588880715', 'SSF2684853'),
('+919466095660', 'SSF2546463'),
('+919484546488', 'SID951376177849'),
('+917771928918', 'SID951373001967'),
('+917240930703', 'SID951375586513'),
('+917225807829', 'SSF2868941'),
('+917518997196', 'SSF2612134'),
('+919244901181', 'SSF2801756'),
('+916267172792', 'SSF3222751'),
('+916264519651', 'SSF3371504'),
('+916266341202', 'SID951375120396'),
('+917477008244', 'SSF3838919'),
('+917067798505', 'SSF4173243'),
('+917067605783', 'SSF3362821'),
('+917828542771', 'SSF4465634'),
('+917000991282', 'SSF3363652'),
('+917000638415', 'SSF3849882'),
('+917224835186', 'SSF3562578'),
('+917974413362', 'SSF3048411'),
('+918319298611', 'SSF4408973'),
('+918247081704', 'SSF3548723'),
('+918305588463', 'SSF3186410'),
('+918103456686', 'SSF6300481'),
('+919039624580', 'SSF3519779'),
('+919294870318', 'SSF4318343'),
('+919575109810', 'SSF3538000'),
('+919174774955', 'SSF3353595'),
('+919755459070', 'SSF3675039'),
('+918757875720', 'SID951376133981'),
('+919580220735', 'SSF5822362'),
('+918969114318', 'SID951375978222'),
('+919770219765', 'SID951374904061'),
('+919568643236', 'SID951372802997'),
('+919981229078', 'SID951376226983'),
('+918564964837', 'SSF3681475'),
('+917049182502', 'SID951374169301'),
('+919219047306', 'SSF3293818'),
('+918707832294', 'SSF5511488'),
('+919911635336', 'SSF5307507'),
('+919302339232', 'SSF2428444'),
('+919027143941', 'SSF4047309'),
('+919693304670', 'SSF2548450'),
('+917806075082', 'CID213701016'),
('+919302558941', 'SID951374532055'),
('+918103890598', 'SSF5851900'),
('+916261127415', 'SSF4061568'),
('+919651667154', 'SSF4589230'),
('+916388214792', 'SSF5081682'),
('+917770814484', 'SSF2825364'),
('+916375102842', 'SSF4595684'),
('+917771880388', 'SID951374365954'),
('+919201551751', 'SSF4808790'),
('+919770700476', 'SSF3384645'),
('+917697990981', 'SSF2765293'),
('+916267098104', 'SSF2481710'),
('+919554106766', 'SSF2608299'),
('+917014576492', 'SID951375760653'),
('+916266158529', 'SSF4164907'),
('+917895515160', 'SSF4179196'),
('+917302826449', 'SSF4940391'),
('+919510247196', 'SSF3684324'),
('+918602428371', 'SSF4334789'),
('+918239963412', 'SSF2722818'),
('+919309865269', 'SSF3975089'),
('+919406659025', 'SID951375959147'),
('+917800254950', 'SSF2397107'),
('+916287912586', 'SSF4248203'),
('+917803050395', 'CID087403051'),
('+919256668817', 'SID951375455591'),
('+917247537084', 'SSF3815550'),
('+919784845355', 'SSF4591202'),
('+916200643580', 'SSF2814982'),
('+919695316867', 'SSF5108090'),
('+919199536885', 'SSF2965846'),
('+917734007328', 'SSF3167836'),
('+918406970005', 'SSF4747745'),
('+919236757694', 'SSF2979235'),
('+919060294189', 'SSF2319466'),
('+919798810509', 'SSF2973963'),
('+917426866830', 'SID951375297452'),
('+917739750873', 'SID951374571658'),
('+919755945450', 'SID951375897798'),
('+919301219203', 'SSF3763116'),
('+917493853920', 'SSF3835326'),
('+917987211482', 'SID951375748666'),
('+919793335525', 'SSF2805958'),
('+916268593118', 'SSF2713596'),
('+918815521487', 'SSF3345471'),
('+918942859742', 'SID951374249627'),
('+917408502357', 'SSF2735548'),
('+919026392619', 'SSF4266344'),
('+919931429767', 'SSF4413555'),
('+917828614877', 'SID951375106061'),
('+919571449412', 'SID951376065610'),
('+917297070477', 'SSF3691098'),
('+918305843196', 'SID951375633837'),
('+916266627717', 'SID2125622407'),
('+919981534566', 'SID951374091001'),
('+919905623863', 'SSF4046631'),
('+917742938473', 'SID2125566573'),
('+919928422146', 'SSF3674714'),
('+919016601745', 'SSF2304195'),
('+918464949449', 'SSF3711678'),
('+919834389631', 'CID219102163'),
('+919575479897', 'CID072007889'),
('+919343423471', 'SSF3985177'),
('+918227075166', 'SSF3816214'),
('+917484954083', 'SID951376234804'),
('+918287290162', 'SSF5922693'),
('+918271609474', 'SSF4495014'),
('+916269236592', 'SSF3779685'),
('+918601287513', 'SSF2847528'),
('+918292633939', 'SID951375627647'),
('+918009430990', 'SSF5708994'),
('+917023263718', 'SSF4701159'),
('+919516855722', 'SID2125158231'),
('+917878447375', 'SID951375438317'),
('+916390187586', 'SSF2814290'),
('+917566855584', 'SID951376163662'),
('+917849807274', 'SSF2703343'),
('+917697368127', 'SID951372954182'),
('+919955794987', 'SID951375769748'),
('+917295934160', 'SID951375619816'),
('+918120789098', 'SID951373103700'),
('+918084076262', 'SSF2905903'),
('+919166400110', 'SSF4299157'),
('+919329112524', 'SSF4456051'),
('+917024719968', 'SID951374946403'),
('+919234740976', 'SSF4387556'),
('+918115966769', 'SSF5030721'),
('+917033562288', 'SSF4564694'),
('+919669149455', 'SSF3339180'),
('+919329000261', 'SSF3247028'),
('+918252603431', 'SID2125743706'),
('+919708820121', 'SID951373106196'),
('+919234911143', 'SID951375565745'),
('+916352995719', 'SSF4157409'),
('+917091334173', 'SSF3364905'),
('+917828978017', 'SSF3796011'),
('+917667038419', 'SSF4243288'),
('+918982021024', 'SSF3790227'),
('+919834841596', 'SSF4103443'),
('+919835480674', 'SSF4593313'),
('+919098790416', 'SID951373063458'),
('+919026940993', 'SSF3365809'),
('+917877830309', 'SSF2701053'),
('+918815305484', 'SSF4162917'),
('+918409163758', 'SSF3985161'),
('+918271707709', 'SSF6346212'),
('+917727049211', 'SID951375545495'),
('+917339899612', 'SID951374514036'),
('+919340018884', 'SID951375155242'),
('+917357463360', 'SSF3866787'),
('+917987354593', 'SSF4054856'),
('+918602701644', 'SSF3960733'),
('+919352331636', 'SSF3451082'),
('+919509245569', 'SSF2675155'),
('+916268677323', 'CID050410190'),
('+919644426030', 'SID2125634869'),
('+916268557858', 'SSF3979835'),
('+916202389512', 'SSF3546968'),
('+916261966717', 'SID951375947735'),
('+917489947323', 'SSF2934929'),
('+917901716979', 'SSF3761158'),
('+918442975762', 'SSF3588077'),
('+919631642554', 'SSF3469979'),
('+919244824595', 'SSF3294072'),
('+916265392041', 'SID951372939906'),
('+916261058037', 'SSF3022069'),
('+916266094565', 'SID951375166282'),
('+916267854193', 'SSF3521055'),
('+916262470761', 'SSF3630503'),
('+917974172766', 'SID951374203606'),
('+917727995411', 'SSF3340312'),
('+918458734978', 'SSF2786630'),
('+918815297401', 'SSF5500214'),
('+918677907553', 'SSF3142446'),
('+919122057938', 'SID951374547376'),
('+919131572133', 'SSF3657561'),
('+919238298124', 'SSF5500431'),
('+919770732858', 'SSF4195660'),
('+919118818606', 'SSF3539465'),
('+919113318898', 'SSF2996680'),
('+919021887086', 'SSF3237150'),
('+919753841073', 'SID951375358624'),
('+919219517520', 'SSF6265626'),
('+917965425246', 'SID951375911577'),
('+917041521128', 'SSF3158123'),
('+917250737492', 'SID951375224323'),
('+918328540982', 'SSF2519043'),
('+918980937954', 'SID951375384306'),
('+918112274237', 'SSF3121341'),
('+919521122414', 'SSF4719218'),
('+919644345217', 'SSF3202118'),
('+919122303358', 'SSF2969568'),
('+919153798215', 'SSF3190920'),
('+917856886992', 'SID951374065147'),
('+918102630110', 'SID951375789702'),
('+919546434949', 'SSF3666337'),
('+917033602977', 'SSF4889175'),
('+917033602448', 'SSF4886808'),
('+917568406240', 'SSF3617124'),
('+918770950229', 'SSF3119992'),
('+918824654468', 'SSF2585205'),
('+918209292352', 'CID951376204759'),
('+919549001104', 'SID951375888657'),
('+919798552212', 'SSF2833433'),
('+917698689215', 'SSF2515883'),
('+918769011527', 'SSF2886225'),
('+918464345464', 'SSF2385811'),
('+919783681697', 'SSF2342572'),
('+919556853011', 'SSF2377325'),
('+919329392933', 'SID951375435080'),
('+916267372619', 'SID951375551795'),
('+916350679113', 'SSF2677758'),
('+917845951885', 'SID951376023921'),
('+918934384548', 'SSF3309873'),
('+919983235612', 'CID951376206243'),
('+917689905821', 'SSF2302897'),
('+919564997637', 'SID951374574755'),
('+916207267811', 'SID951374439653'),
('+918651056035', 'SID951375125440'),
('+919523145198', 'SID951375045316'),
('+919326148946', 'SID951374950369'),
('+916352086796', 'SSF3863908'),
('+917782079368', 'SSF3890467'),
('+918809993516', 'SSF3617780'),
('+918871769090', 'SSF3122158'),
('+919263619917', 'SSF2820906'),
('+919685504769', 'SSF3948483'),
('+919905777120', 'SSF3247172'),
('+919329270438', 'SSF3656449'),
('+919926125855', 'SSF3854630'),
('+918643093981', 'SID2125703593'),
('+918349311572', 'SID951373391956'),
('+917250665760', 'SID951375501692'),
('+918757501904', 'SSF2433863'),
('+918651886851', 'SSF2859804'),
('+919669591938', 'SSF2732676'),
('+919326168797', 'SSF2923272'),
('+916200403336', 'SSF3991492'),
('+916263400497', 'SSF3837917'),
('+917319903375', 'SSF3283452'),
('+917206642610', 'SSF3250304'),
('+917319904754', 'SSF3652528'),
('+917415181750', 'SSF3570485'),
('+918252588399', 'SSF3690768'),
('+918102122397', 'SSF3204627'),
('+918292207881', 'SSF3335340'),
('+918817842071', 'SSF3940092'),
('+918709376219', 'SSF3108103'),
('+918092597369', 'SSF3640729'),
('+918271867983', 'SSF3244460'),
('+918303655640', 'SSF3183706'),
('+919771001572', 'SSF4063826'),
('+919680840712', 'SSF3161480'),
('+919031893330', 'SSF4170642'),
('+919264488087', 'SSF2674741'),
('+918873175489', 'SSF6395590'),
('+918252169968', 'SID951375755853'),
('+916376353352', 'SSF3723379'),
('+918094926177', 'SSF3680212'),
('+919602019712', 'SID951375722271'),
('+919263472776', 'SSF3084297'),
('+919452863729', 'SSF4405660'),
('+916297914526', 'SSF3392966'),
('+917366050996', 'SSF4013420'),
('+918817782185', 'SSF3554654'),
('+918340622371', 'SSF3007100'),
('+919128536659', 'SSF4462587'),
('+919693929723', 'SID951376195027'),
('+919238646848', 'SID951375915474'),
('+919508005849', 'SSF2618143'),
('+916206737370', 'SSF5000840'),
('+919570197362', 'SSF6402492'),
('+919570643441', 'SSF6411023'),
('+919798841129', 'SSF4830445'),
('+917758624821', 'SID2125331368'),
('+919399242055', 'CID204606016'),
('+917665546804', 'SSF4067597'),
('+917000468656', 'SID951375071551'),
('+917762971877', 'SSF3387624'),
('+917746896312', 'SSF3619124'),
('+918305232166', 'SSF4864868'),
('+919142834167', 'SSF3880600'),
('+919354305175', 'SSF2381849'),
('+919602244974', 'SSF3777143'),
('+919399923601', 'SID951374338817'),
('+919771229472', 'SSF3267814'),
('+919993110747', 'SSF3284851'),
('+919935061256', 'SSF5052415'),
('+916367555654', 'SID951375888625'),
('+917073531193', 'SSF3044717'),
('+917050791684', 'SSF3268688'),
('+917073906819', 'SID951375378527'),
('+917784648469', 'SID951375381092'),
('+917644058604', 'SSF2609251'),
('+918875081192', 'SSF2751850'),
('+919587572852', 'SSF3987336'),
('+919937880372', 'SSF4487401'),
('+919509362018', 'SID951375219362'),
('+919752235462', 'SSF4387827'),
('+919300302788', 'SSF3790145'),
('+917091805098', 'SSF2876798'),
('+917033602518', 'SSF4887016'),
('+917877953067', 'SSF2584721'),
('+918059369296', 'SSF2801629'),
('+917851062679', 'SSF4160287'),
('+917297917671', 'SSF2318887'),
('+918107550922', 'SSF2633079'),
('+918955185854', 'SID951375534097'),
('+919558965884', 'SID951376074968'),
('+919854876767', 'SSF3641453'),
('+919928472766', 'SSF2702294'),
('+919343516778', 'SID951374924604'),
('+916269837450', 'SSF4385699'),
('+917489722089', 'SSF3152972'),
('+917987980186', 'SSF3392372'),
('+917999746092', 'SSF4192869'),
('+918600811975', 'SSF4292545'),
('+918989081254', 'SSF3214276'),
('+918641058712', 'SSF3289836'),
('+919455213969', 'SSF3078975'),
('+916265776351', 'SID951373192695'),
('+919279335279', 'SID951374541074'),
('+917999739518', 'CID080813506'),
('+916268788638', 'SSF2892919'),
('+916265944966', 'SID951374162348'),
('+917023113596', 'SID951374076170'),
('+919131025391', 'SSF3344114'),
('+918827760511', 'CID087110589'),
('+919358077761', 'SSF3910093'),
('+919575762954', 'SSF3699572'),
('+919153929614', 'SSF3008260'),
('+918847025911', 'SSF4510819'),
('+919131523610', 'SID951374072527'),
('+917771014332', 'SID2125428661'),
('+916209487011', 'SSF3371033'),
('+917610329815', 'SID2125244369'),
('+916376786712', 'SID951375506916'),
('+919508166860', 'SSF3324662'),
('+917310381010', 'SSF4514737'),
('+917752915568', 'SSF3941381'),
('+918544847471', 'SSF3417359'),
('+919199929861', 'SSF2555083'),
('+919279580883', 'SSF5090306'),
('+918585876364', 'SSF3351141'),
('+919955952860', 'SID951375524525'),
('+919165014335', 'CID225201804'),
('+918875910572', 'SID951375375392'),
('+916268706568', 'SID2125756562'),
('+916978465134', 'SSF2473927'),
('+917974695960', 'SSF4657458'),
('+918757744963', 'SID951375163161'),
('+916260257426', 'SSF3566848'),
('+917355030337', 'CID212301296'),
('+919691506379', 'CID140902235'),
('+918809508268', 'SSF2888948'),
('+919973653236', 'SID951375780645'),
('+919174151383', 'SSF3015207'),
('+918720063395', 'SSF3560448'),
('+919691191942', 'CID084400491'),
('+918127150745', 'SSF5155283'),
('+919340630892', 'SSF5090673'),
('+918810887271', 'SSF5075343'),
('+916203177391', 'SSF4815377'),
('+919098453797', 'SID951374431258'),
('+919981744045', 'SID2125196609'),
('+919256932147', 'SSF3420116'),
('+919838980451', 'SSF4993525'),
('+917598575890', 'SSF3380782'),
('+916209159710', 'SSF3230057'),
('+916375218467', 'SSF2995444'),
('+917856032799', 'SSF2984512'),
('+919685440073', 'SID2125475147'),
('+917722991951', 'SID951373558752'),
('+917224008116', 'SID6381'),
('+919770929481', 'SID951376211455'),
('+918210240565', 'SID951373458887'),
('+919691016278', 'SSF4573155'),
('+918959844136', 'CID140609153'),
('+917295969396', 'SID951374911100'),
('+919770989172', 'SID951374290158'),
('+918827718611', 'SID2125214480'),
('+919165710037', 'SID951373142285'),
('+918797496503', 'SSF6311596'),
('+918696620660', 'SID951376224475'),
('+916204825709', 'SID951374978210'),
('+918543814832', 'SSF4562220'),
('+916353555023', 'SSF5851579'),
('+916268504387', 'SID951374538466'),
('+917067055232', 'SID951373928976'),
('+919334284337', 'SSF3197277'),
('+918271186782', 'SSF2405568'),
('+918052099527', 'SID951374971875'),
('+917389572245', 'SID951374393116'),
('+919256808417', 'SID951375216073'),
('+919109084696', 'SID951375813112'),
('+918922867128', 'SSF5524684'),
('+919993929336', 'SID951375065849'),
('+917415817208', 'CID048714300'),
('+918889663614', 'SID951373790734'),
('+917009824846', 'SSF2553810'),
('+919571705175', 'SSF4564490'),
('+918218611827', 'SSF4763924'),
('+918871215513', 'CID057501866'),
('+916265644840', 'SID951376093682'),
('+917759986736', 'SSF2865460'),
('+918653853064', 'SID951376051178'),
('+916206768520', 'SSF3370717'),
('+916267822362', 'SSF4318355'),
('+917320913520', 'SSF4393519'),
('+917974684025', 'SSF4828737'),
('+918003725022', 'SSF3321321'),
('+919835000584', 'SSF4268130'),
('+919835314126', 'SSF4275918'),
('+917209988951', 'SID951373304885'),
('+918720055879', 'SSF4061094'),
('+918269420097', 'SSF4338464'),
('+919693682827', 'SSF3953815'),
('+919304550273', 'SSF3242563'),
('+917033334338', 'SSF4438452'),
('+918953725478', 'SSF4814537'),
('+919955777402', 'SSF6326160'),
('+917645023392', 'SID951375410438'),
('+919509872493', 'SID951374858074'),
('+918115054239', 'SSF2837610'),
('+919784815170', 'SSF2674077'),
('+918757706304', 'SSF2836168'),
('+918757655478', 'SSF3016614'),
('+918103026387', 'SSF3611440'),
('+919575825130', 'SSF2811199'),
('+919244023352', 'SSF3772146'),
('+917393010535', 'SSF4516864'),
('+916263485326', 'SSF3966040'),
('+916206675952', 'SSF3110958'),
('+917236886680', 'SSF3038314'),
('+917477010083', 'SSF3335462'),
('+918797926505', 'SSF2840131'),
('+918797377323', 'SSF3211613'),
('+918084169575', 'SSF2780681'),
('+918875692516', 'SSF3858413'),
('+919256726699', 'SSF3504429'),
('+919241046273', 'SSF4424509'),
('+919608028151', 'SSF2542269'),
('+919523974244', 'SSF2678488'),
('+917974787964', 'CID191802184'),
('+918817919998', 'SID951373042697'),
('+917050350288', 'SSF3054912'),
('+917294989195', 'CID951376205114'),
('+918423997932', 'SSF3619939'),
('+919155666140', 'SID951372939818'),
('+919303778487', 'SSF3475684'),
('+919343395900', 'SSF3585735'),
('+916350153905', 'SID951374853884'),
('+916206994227', 'SID951375832399'),
('+916200277306', 'SSF3087298'),
('+917368954213', 'SSF3197574'),
('+917858910032', 'SID951375709867'),
('+917725020611', 'SSF3963522'),
('+919728313690', 'SSF3128215'),
('+919955886876', 'SSF3205829'),
('+919155036226', 'SSF3302589'),
('+918815389077', 'SSF3078089'),
('+918770522521', 'SID951373509144'),
('+918955060594', 'SSF3627795'),
('+919508329204', 'SSF4058319'),
('+919693361923', 'SSF4449657'),
('+919575478899', 'SSF3294458'),
('+916202955365', 'SSF2759617'),
('+917998998979', 'SSF2827251'),
('+917764686611', 'SID951374578828'),
('+918094373528', 'SSF2302898'),
('+918607083643', 'SID951375987690'),
('+917728860506', 'SID951374426418'),
('+917987600329', 'SID2125641992'),
('+917366984906', 'SID951375375244'),
('+916205542890', 'SSF2897360'),
('+916205328261', 'SSF4238781'),
('+917301650463', 'SSF4030752'),
('+917828733036', 'SID951374966180'),
('+918948838033', 'SSF3400835'),
('+919343348599', 'SSF4402692'),
('+919565856074', 'SSF3137526'),
('+919279615018', 'SSF4612025'),
('+917985252759', 'SSF2569538'),
('+917023818410', 'SSF2555690'),
('+917084416254', 'SSF2545061'),
('+918788849664', 'CID951376208829'),
('+919110114863', 'SSF2494742'),
('+916360736345', 'SSF2806486'),
('+917054438582', 'SSF3177535'),
('+917440383655', 'SID951375351852'),
('+917633066503', 'SSF4027858'),
('+917877227811', 'SSF4185835'),
('+917488977768', 'SSF3576813'),
('+917061163450', 'SSF3306793'),
('+917054669581', 'SSF3078280'),
('+917388715605', 'SSF3438378'),
('+918757138064', 'SSF3539798'),
('+919584537397', 'SSF4471393'),
('+919709126092', 'SSF3805312'),
('+919661521861', 'SSF4012190'),
('+919523048840', 'SSF2928306'),
('+919014597994', 'SSF4234013'),
('+918226032460', 'SID951375919230'),
('+918809098297', 'SSF2805795'),
('+917340524380', 'SSF4549513'),
('+918420862401', 'SSF3269716'),
('+919981906200', 'SID951374851016'),
('+918982428480', 'CID084600741'),
('+917304127477', 'SSF2878160'),
('+917564078852', 'SSF2730437'),
('+917762964279', 'SID951375620278'),
('+919546129047', 'SSF3241700'),
('+919939088559', 'SID951374910321'),
('+919982363678', 'SSF3760735'),
('+917482979878', 'SID951376158070'),
('+916268020180', 'SSF3456853'),
('+917247580058', 'SSF3610474'),
('+917974251377', 'SSF3477732'),
('+917000724403', 'SSF4461312'),
('+918805921766', 'SSF3350058'),
('+919162046758', 'SSF3602930'),
('+919257197635', 'SSF3606529'),
('+918824474626', 'SSF4337050'),
('+919175474025', 'SSF3252265'),
('+917742852850', 'SSF2434877'),
('+917209396011', 'SSF4246128'),
('+918945942406', 'SSF3116738'),
('+919024858365', 'SID951374543002'),
('+919631132072', 'SSF3365226'),
('+919822164848', 'SID951375094437'),
('+919155276404', 'SSF2855846'),
('+919257898383', 'SID951374721224'),
('+918107022612', 'SSF2606546'),
('+918003385113', 'SSF2546588'),
('+919518257573', 'SID951376125708'),
('+919464646892', 'SSF2465419'),
('+917742143236', 'SID951373582036'),
('+919009435023', 'SID951374147045'),
('+916268820620', 'SID951376128698'),
('+916263262801', 'SSF3602457'),
('+917447035079', 'SSF4037724'),
('+917722964907', 'SSF3696007'),
('+918103737235', 'SSF4133281'),
('+918871552399', 'SSF4206252'),
('+919752184757', 'SSF4211505'),
('+919981116689', 'SSF4297999'),
('+919691875740', 'SSF4004621'),
('+919992246468', 'SSF3984558'),
('+916207052315', 'SID951373825521'),
('+918209950460', 'SID951375306641'),
('+917723033810', 'SID951373858569'),
('+917023417941', 'SID951375571777'),
('+919575751696', 'SID951373236841'),
('+918109862495', 'SID951375426648'),
('+916267690523', 'SID951375056154'),
('+916299676280', 'SID951372844916'),
('+918889054969', 'CID190101556'),
('+919617928981', 'SID951373962648'),
('+917665984133', 'SID951375460497'),
('+919131098120', 'SSF3333657'),
('+916263886315', 'SID951373953431'),
('+917250541168', 'SID951376047883'),
('+919835062038', 'SSF5276136'),
('+916264248059', 'SID951374345244'),
('+917479401057', 'SSF2315858'),
('+917236012948', 'SSF4419011'),
('+918251001722', 'SSF5198491'),
('+918103204216', 'SSF2343498'),
('+919685439388', 'SID951374296213'),
('+917803003365', 'SID951375836826'),
('+919939830168', 'SID951374645622'),
('+919414420055', 'SSF3737847'),
('+919006899308', 'SSF3999818'),
('+919956001580', 'SSF5794487'),
('+917061034513', 'SID951374504749'),
('+918521509184', 'SSF4381673'),
('+918709875626', 'SID951375268407'),
('+919926706454', 'SID2125512225'),
('+918269852583', 'SID951375072468'),
('+919034801654', 'SID951374627120'),
('+919753336708', 'CID117911438'),
('+919516666051', 'SSF4000966'),
('+916263354110', 'SID951374117037'),
('+919696569839', 'SSF2761976'),
('+918127569469', 'SID951375632665'),
('+919026488196', 'SSF4747528'),
('+919171380545', 'SID951374409308'),
('+918687215385', 'SID951373794890'),
('+918757949285', 'SID951374367294'),
('+916201094611', 'SSF4270038'),
('+919905483058', 'SSF3042294'),
('+918815168263', 'SSF4184086'),
('+916264032342', 'SID951374590414'),
('+916350366962', 'SID951374201344'),
('+919835061149', 'SSF5192411'),
('+919928580003', 'SSF3055664'),
('+918800368248', 'SID951374588759'),
('+919798895417', 'SSF3001812'),
('+919630272116', 'SID951372887304'),
('+919153038517', 'SSF4203125'),
('+919179419215', 'SSF3777707'),
('+917582055102', 'SID951375925356'),
('+919303159350', 'SSF5571640'),
('+917804902440', 'SID951373460464'),
('+917766839166', 'SSF5931106'),
('+919754445594', 'SID951373499122'),
('+919005825582', 'SSF3564459'),
('+919632547888', 'SSF2825153'),
('+919770092048', 'CID140604161'),
('+917466063457', 'SSF5596510'),
('+919359684470', 'SID951376139757'),
('+917050796500', 'SSF4454683'),
('+919363573493', 'SSF2600570'),
('+919258369917', 'SSF5956415'),
('+918969078056', 'SID951374039686'),
('+919201225160', 'SSF3187467'),
('+919691596180', 'SSF3237305'),
('+917970685270', 'SSF5056208'),
('+917254824740', 'SSF3541856'),
('+919109456210', 'SSF3475929'),
('+919304414407', 'SID951375752633'),
('+919098393268', 'SID951375546999'),
('+919934945554', 'SSF2760765'),
('+919835512093', 'SSF3016931'),
('+919205308037', 'SSF4393390'),
('+919508264141', 'SID951374946292'),
('+916205586800', 'SSF2832501'),
('+917828844680', 'SSF4286714'),
('+917482025300', 'SSF3110103'),
('+917631852131', 'SSF4620990'),
('+919452190390', 'SSF4668068'),
('+919358397820', 'SID951373956689'),
('+919157844719', 'SID951373766360'),
('+917994939891', 'CID951376207715'),
('+916360150571', 'SSF3200183'),
('+917748079908', 'SSF4189510'),
('+917366068306', 'SSF3183401'),
('+918959014190', 'SSF3371857'),
('+918349066147', 'SSF3975125'),
('+918290284658', 'SSF2961278'),
('+919179942966', 'SSF3960732'),
('+919009923447', 'SSF3452442'),
('+918294630448', 'CID171506434'),
('+916378012967', 'SSF2343243'),
('+917488086690', 'SID951375225867'),
('+917007951994', 'SSF3085224'),
('+918294294195', 'SSF4060878'),
('+919509671985', 'SSF3619412'),
('+919279880889', 'SSF2813967'),
('+919386499110', 'SSF3048851'),
('+917803981539', 'SID951373196147'),
('+917067384896', 'SID2125586224'),
('+919153387897', 'CID204504654'),
('+916262172993', 'SID951373086023'),
('+916263810353', 'SSF3338307'),
('+916377962610', 'SSF5798822'),
('+916376732969', 'SSF4391127'),
('+916206061323', 'SSF4394121'),
('+916202057048', 'SSF4478905'),
('+916005170427', 'SSF3997686'),
('+917974438200', 'SSF3338322'),
('+917877584665', 'SSF4162544'),
('+917300472615', 'SSF3346290'),
('+917412912757', 'SSF2827944'),
('+917908800239', 'SSF3097387'),
('+917357396817', 'SSF3649525'),
('+917318052710', 'SSF3424819'),
('+917304756113', 'SSF5325190'),
('+917643822128', 'SSF3371095'),
('+917023122538', 'SSF5309170'),
('+917737682836', 'SSF4084729'),
('+917894043170', 'SID951374397569'),
('+917021352430', 'SSF2455998'),
('+917976091331', 'SSF3626917'),
('+917509563766', 'SSF3311926'),
('+917260031457', 'SSF4245381'),
('+917470998709', 'SSF3452977'),
('+917903255227', 'SSF3194198'),
('+917426847106', 'SSF3601178'),
('+918769135238', 'SSF3344490'),
('+918619764656', 'SSF3514136'),
('+918544715067', 'SSF4904613'),
('+918051296535', 'SSF4399775'),
('+918003924244', 'SSF5231634'),
('+918574712215', 'SSF3035676'),
('+918294506870', 'SSF2763855'),
('+918875716460', 'SID951375051946'),
('+918000153273', 'SSF2584429'),
('+918290570964', 'SSF3164380'),
('+918690148154', 'SSF3491127'),
('+918824470076', 'SSF3494702'),
('+918103590897', 'SSF3970429'),
('+918349995679', 'SSF5164390'),
('+918738835575', 'SSF4483746'),
('+918905887586', 'SSF3602058'),
('+918871508837', 'SSF3414691'),
('+918858121784', 'SID951376090596'),
('+918868896555', 'SSF3612930'),
('+918602022302', 'SSF3175111'),
('+918709013076', 'SID951374101781'),
('+919509227079', 'SID951374762614'),
('+919079995149', 'SSF4200749'),
('+919352035369', 'SSF4164158'),
('+919658472358', 'SSF3361659'),
('+919529498264', 'SSF4256490'),
('+919798649919', 'SSF3978828'),
('+919065665296', 'SSF4200764'),
('+919765484545', 'SSF2885223'),
('+919348434656', 'SSF3129698'),
('+919770549623', 'SSF4829516'),
('+919931550063', 'SSF3751144'),
('+919057249769', 'SSF2881252'),
('+919691366008', 'SSF3621274'),
('+919691527157', 'SSF3654984'),
('+919521489867', 'SSF2802379'),
('+919301987954', 'SID951374248791'),
('+919783836114', 'SID951375355418'),
('+919329176135', 'SSF3561014'),
('+919343273116', 'SSF4068941'),
('+919343485880', 'SSF3654999'),
('+919636090808', 'SSF3045194'),
('+919918526508', 'SSF3689237'),
('+919950593607', 'SSF2734851'),
('+919358635367', 'SSF4161060'),
('+919171910394', 'SSF2451772'),
('+919587489031', 'SSF2829500'),
('+919588898035', 'SSF3773396'),
('+916375354718', 'SSF3891368'),
('+916863895599', 'SSF3674513'),
('+916202419564', 'SSF2364389'),
('+916354800632', 'SSF2551427'),
('+916268871031', 'SSF2940610'),
('+916231542126', 'SSF3309462'),
('+916368034933', 'SSF2942979'),
('+916377560618', 'SSF2870575'),
('+916263497129', 'SSF3997866'),
('+916377045179', 'SSF5385476'),
('+917738745906', 'SSF3679071'),
('+917727870081', 'SSF2876169'),
('+917878531801', 'SSF4108304'),
('+917737925146', 'SSF3093658'),
('+917987077128', 'SSF3338141'),
('+917426874819', 'SSF4112751'),
('+917426005934', 'SSF2588410'),
('+917033248994', 'SID951375852825'),
('+917079788328', 'SSF4200704'),
('+917487013394', 'SSF3040772'),
('+917023472102', 'SSF2665247'),
('+917768616158', 'SSF3765363'),
('+917869314276', 'SSF3687313'),
('+917230999511', 'SSF3346698'),
('+917023463620', 'SSF4689997'),
('+917764871288', 'SSF3661814'),
('+917879713106', 'SSF4346404'),
('+917762901544', 'SSF2964049'),
('+917000295462', 'SSF5228715'),
('+917230097004', 'SSF3196171'),
('+917065327877', 'SSF4630674'),
('+917380963151', 'SSF4828281'),
('+917690892512', 'SSF4270183'),
('+917877671919', 'SSF4263646'),
('+917891412910', 'SSF5341560'),
('+917023541566', 'SSF3623334'),
('+917479609365', 'SSF5140728'),
('+917033295670', 'SSF4850986'),
('+917891853454', 'SSF3938940'),
('+917726998615', 'SSF4041280'),
('+917568605931', 'SSF3947023'),
('+917897924319', 'SSF3098845'),
('+918279232661', 'SSF5204054'),
('+918959132464', 'SSF3773546'),
('+918302824627', 'SSF3553033'),
('+918094411731', 'SSF2591446'),
('+918120149230', 'SSF4566391'),
('+918619263952', 'SSF3406544'),
('+918195829850', 'SSF4200677'),
('+918619784546', 'SSF2330475'),
('+918078565488', 'SSF3352580'),
('+918000948509', 'SSF3773483'),
('+918832743221', 'SSF3741243'),
('+918619234361', 'SSF4064654'),
('+918854892544', 'SSF3077131'),
('+918849904034', 'SSF2990819'),
('+918882491110', 'SSF2861070'),
('+918955359396', 'SSF4983937'),
('+918645543436', 'SSF3024913'),
('+918556554768', 'SSF3128838'),
('+918583554556', 'SSF3137163'),
('+918736030831', 'SSF4751129'),
('+918948426141', 'SSF4630859'),
('+918556969517', 'SSF3137229'),
('+918853054733', 'SSF5102545'),
('+918887982977', 'SSF4628673'),
('+918955561949', 'SSF2288794'),
('+918789200688', 'SSF2997319'),
('+918875757126', 'SSF2582472'),
('+918757332327', 'SSF5125124'),
('+918619785792', 'SSF3757975'),
('+918239498825', 'SSF3352432'),
('+918696617005', 'SSF4387798'),
('+918000506503', 'SSF3715463'),
('+918269740260', 'SSF3300847'),
('+918824905740', 'SSF4027837'),
('+918529510366', 'SSF5275678'),
('+918955231922', 'SSF4165553'),
('+918568785855', 'SSF3558685'),
('+918003407555', 'SSF2479068'),
('+918217276300', 'SSF2393824'),
('+918853136311', 'SSF3406900'),
('+918302401923', 'SSF4273179'),
('+918529211879', 'SSF3959540'),
('+918875530560', 'SSF2575871'),
('+918889957220', 'SSF3252996'),
('+918817280507', 'SSF3063751'),
('+918094637922', 'SSF2767550'),
('+918875674339', 'SSF2605969'),
('+918236038943', 'SSF3569249'),
('+918305986217', 'SSF3266916'),
('+918319189259', 'SSF2767891'),
('+919351373197', 'SSF3853910'),
('+919680505764', 'SSF4927080'),
('+919602086236', 'SSF3842613'),
('+919885988809', 'SSF3319446'),
('+919325846856', 'SSF3183252'),
('+919666855778', 'SSF2647836'),
('+919024301081', 'SSF3715887'),
('+919464640407', 'SSF3648214'),
('+919024949322', 'SSF3797118'),
('+919794694648', 'SSF3211577'),
('+919293889006', 'SSF3417854'),
('+919001367265', 'SSF4149510'),
('+919784703014', 'SSF3800857'),
('+919122445572', 'SSF4200958'),
('+919142006228', 'SSF4198583'),
('+919892083782', 'SSF2416230'),
('+919691520055', 'SSF5302627'),
('+919244247363', 'SSF3001471'),
('+919057860582', 'SSF3627196'),
('+919155016137', 'SSF3227975'),
('+919931190686', 'SSF2834717'),
('+919304943108', 'SSF4343708'),
('+919610216201', 'SSF2932374'),
('+919521699882', 'SSF3707479'),
('+919829580350', 'SSF2804994'),
('+919279126896', 'SSF4472432'),
('+919352752843', 'SSF3783412'),
('+919549764375', 'SSF4352424'),
('+919308386757', 'SSF3651616'),
('+919784694331', 'SSF4298331'),
('+919799425343', 'SSF3804453'),
('+919571143626', 'SSF4317727'),
('+919539655995', 'SSF3475860'),
('+919821185053', 'SSF4435755'),
('+919829715012', 'SSF3275068'),
('+919166881078', 'SSF2932304'),
('+919506387789', 'SSF3159503'),
('+919631292874', 'SSF2955013'),
('+919990203962', 'SSF4628246'),
('+919219738372', 'SSF5067397'),
('+919695670157', 'SSF3013105'),
('+919783690337', 'SSF2549651'),
('+919071098551', 'SSF4483367'),
('+919161453159', 'SSF4630747'),
('+919829795322', 'SSF5163267'),
('+919173284635', 'SSF3249260'),
('+919939221796', 'SSF4164983'),
('+919602528093', 'SSF2582814'),
('+919636246580', 'SSF2390579'),
('+919865587884', 'SSF3091726'),
('+919867645454', 'SSF3229809'),
('+919636664143', 'SSF2741471'),
('+919688542133', 'SID951373182670'),
('+919571022292', 'SSF3649126'),
('+919430450336', 'SID951375809162'),
('+919950549636', 'SSF2680465'),
('+919755487763', 'SSF3171095'),
('+919116369921', 'SSF3150637'),
('+919661907456', 'SSF4862614'),
('+919502871270', 'SSF3414190'),
('+919496464498', 'SSF2828021'),
('+919783993314', 'SSF3562294'),
('+916555448494', 'SSF2748428'),
('+917463065396', 'SSF4511462'),
('+917667821634', 'SSF2473312'),
('+918601218462', 'SSF2746575'),
('+918809843718', 'SSF4121230'),
('+919006458478', 'SSF3554926'),
('+919525767518', 'SSF3594276'),
('+919784910471', 'SSF2692414'),
('+918429996407', 'SSF4807164'),
('+916261306025', 'SSF3448160'),
('+916263242945', 'SSF4071405'),
('+916376033138', 'SSF2945609'),
('+916376390634', 'SSF3983892'),
('+916299957316', 'SSF4525112'),
('+916489494646', 'SSF3578435'),
('+916658889998', 'SSF3895763'),
('+916377524670', 'SSF2609449'),
('+916464826482', 'SSF3721969'),
('+916284516481', 'SSF2923332'),
('+916287926521', 'SSF4525462'),
('+916268706476', 'SSF4838296'),
('+916254046182', 'SSF2927318'),
('+916350640529', 'SSF4399562'),
('+917906338594', 'SSF3249118'),
('+917742241094', 'SSF3118868'),
('+917073302120', 'SSF4300989'),
('+917737423452', 'SSF4076035'),
('+917073631781', 'SSF3701054'),
('+917610555198', 'SSF3054086'),
('+917340612324', 'SSF2375196'),
('+917427880404', 'SSF4544919'),
('+917389791679', 'SSF3563276'),
('+917878738983', 'SSF3516489'),
('+917854576757', 'SSF2895920'),
('+917852834233', 'SSF2584627'),
('+917728987983', 'SSF4672656'),
('+917632892158', 'SSF2917813'),
('+917520613690', 'SSF4555013'),
('+917439007099', 'SSF4555042'),
('+917877756139', 'SSF2653130'),
('+917425856640', 'SSF2690334'),
('+918955438225', 'SSF3046607'),
('+918442152654', 'SSF3118867'),
('+918949865686', 'SSF3762331'),
('+918890238409', 'SSF4157733'),
('+918276467987', 'SSF2924056'),
('+918502855236', 'SSF3983953'),
('+918824055874', 'SSF4377315'),
('+918955253516', 'SSF2664087'),
('+918266922145', 'SSF4327126'),
('+918797695121', 'SID951375783991'),
('+918003601504', 'SSF2858512'),
('+918569864251', 'SSF2820363'),
('+918158150510', 'SSF3696005'),
('+918854831917', 'SSF4129318'),
('+918564213848', 'SSF3569813'),
('+918078686892', 'SSF3973202'),
('+918529162173', 'SSF3795285'),
('+918302551603', 'SSF3448805'),
('+918107990976', 'SSF2592152'),
('+918824661531', 'SSF2555339'),
('+918529463824', 'SSF4025050'),
('+918949615363', 'SSF2730445'),
('+918873494373', 'SSF3580394'),
('+918734934485', 'SSF4255233'),
('+918435865969', 'SSF2733533'),
('+918290127311', 'SSF4330483'),
('+918306072686', 'SSF4078161'),
('+918651264126', 'SSF4808338'),
('+918890037960', 'SSF2573609'),
('+918829965724', 'SSF3813325'),
('+919162272281', 'SSF2776133'),
('+919546691359', 'SID951373981387'),
('+919098554792', 'SSF2891803'),
('+919845784594', 'SSF3432819'),
('+919352730286', 'SSF3575382'),
('+919856467686', 'SSF2738011'),
('+919895643649', 'SSF3543262'),
('+919349565959', 'SSF3655521'),
('+919983677986', 'SSF4390663'),
('+919983469231', 'SSF2567393'),
('+919165503801', 'SSF2932615'),
('+919868646466', 'SSF3189825'),
('+919783676551', 'SSF2720043'),
('+919664261456', 'SSF3975554'),
('+919785604554', 'SSF3739788'),
('+919351632074', 'SSF3033441'),
('+919558084412', 'SSF3806487'),
('+919682789358', 'SSF3722585'),
('+919929413246', 'SSF4274580'),
('+919738497997', 'SSF2586571'),
('+919983992414', 'SSF2924520'),
('+919672114299', 'SSF3839250'),
('+919608081495', 'SSF4893566'),
('+919783087528', 'SSF4017960'),
('+919891616649', 'SSF3611298'),
('+919691186930', 'SSF2413800'),
('+919521022307', 'SSF4539307'),
('+919128525896', 'SSF3045264'),
('+919352294828', 'SSF4672630'),
('+919892466092', 'SSF4555090'),
('+919657885699', 'SSF3199021'),
('+919594649468', 'SSF3824451'),
('+919358563045', 'SSF2914926'),
('+919256477050', 'SSF3245782'),
('+919351205993', 'SSF3385168'),
('+919636552657', 'SSF2837445'),
('+919784123042', 'SSF4232301'),
('+919484545454', 'SSF2965188'),
('+919983093995', 'SSF3815463'),
('+916464644804', 'SSF3165199'),
('+916294592922', 'SID951374413960'),
('+916768596883', 'SSF3753857'),
('+916164646494', 'SSF3614096'),
('+916787653284', 'SSF2934445'),
('+916644848849', 'SSF3330194'),
('+916797838597', 'SSF3356468'),
('+916367611959', 'SSF4407924'),
('+916266428897', 'SID951373725146'),
('+917414087035', 'SSF2689263'),
('+917879866458', 'SSF2862301'),
('+917610235649', 'SSF3800603'),
('+917727843437', 'SSF4000469'),
('+917231087701', 'SSF2722115'),
('+917300098581', 'SSF2793882'),
('+917742716403', 'SSF2553453'),
('+917523669821', 'SSF3688328'),
('+918233485671', 'SSF2575845'),
('+918529121024', 'SSF4293340'),
('+918955213466', 'SSF3448880'),
('+918946825662', 'SSF3575462'),
('+918769023365', 'SSF4165376'),
('+918890496302', 'SSF2638905'),
('+918690787846', 'SSF3672251'),
('+918000359048', 'SSF4456953'),
('+918950214177', 'SSF4507482'),
('+918619315533', 'SSF2845208'),
('+918905548397', 'SSF3172413'),
('+918541025449', 'SSF2883175'),
('+918014059204', 'SSF3001386'),
('+918081834287', 'SSF4004115'),
('+918320609713', 'SSF3147733'),
('+919465683835', 'SSF3663400'),
('+919982478923', 'SSF3847784'),
('+919670848466', 'SSF2767184'),
('+919982911402', 'SID951374966984'),
('+919929295661', 'SSF2807225'),
('+919305140536', 'SSF3087836'),
('+919928173909', 'SSF3391696'),
('+919216266177', 'SSF4385735'),
('+919685255255', 'SSF2482430'),
('+919521686858', 'SSF2691680'),
('+919532945484', 'SSF3754992'),
('+919468676072', 'SSF3355440'),
('+919602505123', 'SSF3492420'),
('+919024509452', 'SSF4272686'),
('+919983746101', 'SSF2343802'),
('+919768868868', 'SSF3312020'),
('+919351282535', 'SSF2878037'),
('+919024222907', 'SSF3979635'),
('+919860725142', 'SSF2699734'),
('+919976166467', 'SSF3626609'),
('+916378027352', 'SSF4001879'),
('+916376635388', 'SSF2590920'),
('+916845409951', 'SSF2561752'),
('+916376180868', 'SSF2559825'),
('+916291971606', 'SSF3675226'),
('+916375660687', 'SSF2804907'),
('+916797646948', 'SSF3607566'),
('+917459867319', 'SSF3833936'),
('+917664889888', 'SSF2550849'),
('+917695576767', 'SSF2725537'),
('+917877255221', 'SSF3824776'),
('+917412828666', 'SSF3810352'),
('+917568468714', 'SSF4024224'),
('+917740806036', 'SSF2520063'),
('+917753498414', 'SSF2691013'),
('+917891287734', 'SSF2868298'),
('+917742485965', 'SSF2558729'),
('+918235478961', 'SSF3466035'),
('+918307366613', 'SSF3103427'),
('+918890401773', 'SSF4047628'),
('+918107144712', 'SSF3305714'),
('+918824977405', 'SSF3092690'),
('+918890110682', 'SSF3839544'),
('+918160802679', 'SSF4422549'),
('+919636515624', 'SSF2330579'),
('+919116941473', 'SSF3440315'),
('+919672085401', 'SSF2977311'),
('+919680420076', 'SSF2587581'),
('+919009938890', 'SSF3647753'),
('+919991613843', 'SSF3514657'),
('+919977676343', 'SSF3540206'),
('+919469622395', 'SSF3444782'),
('+919783311608', 'SSF3250423'),
('+919636186368', 'SSF3494901'),
('+919864343435', 'SSF3052273'),
('+919797997994', 'SSF3738093'),
('+919171012167', 'SSF3655272'),
('+919928434767', 'SSF2624565'),
('+919602406025', 'SSF4076643'),
('+919734215428', 'SSF2833318'),
('+919828536245', 'SSF3163158'),
('+919664413969', 'SSF2376395'),
('+919636451518', 'SSF2715355'),
('+919764686868', 'SSF3834252'),
('+919684648555', 'SSF2824567'),
('+919680641779', 'SSF4137526'),
('+919829389219', 'SSF2664188'),
('+919950045125', 'SSF3649002'),
('+919797634964', 'SSF2832024'),
('+919797679940', 'SSF2589409'),
('+919116698708', 'SSF4121542'),
('+919983457878', 'SSF3161889'),
('+919983107481', 'SSF2878990'),
('+919672786756', 'SSF2845434'),
('+919351264236', 'SSF2729296'),
('+919672610982', 'SSF3301584'),
('+919729183246', 'SSF3421988'),
('+919856856856', 'SSF3217859'),
('+919783273844', 'SSF4277051'),
('+916682875586', 'SSF2281348'),
('+916378224874', 'SSF4097823'),
('+916375133458', 'SSF2849341'),
('+916446449746', 'SSF2691768'),
('+916465646566', 'SSF3439458'),
('+916494994949', 'SSF3723163'),
('+916338673462', 'SSF2684346'),
('+916464544848', 'SSF2301867'),
('+916377081944', 'SSF2485920'),
('+916385297420', 'SSF3745657'),
('+916377813841', 'SSF2343367'),
('+916464643498', 'SSF3425802'),
('+917285056082', 'SSF3392839'),
('+917014751022', 'SSF3442282'),
('+917726815349', 'SSF3918296'),
('+917297069655', 'SSF3973122'),
('+917568056971', 'SSF3910991'),
('+917568295366', 'SSF3087487'),
('+917761316841', 'SSF3407522'),
('+917339745042', 'SSF4010215'),
('+917023845029', 'SSF2766124'),
('+917888855222', 'SSF2873224'),
('+917568114950', 'SSF2381031'),
('+918955753117', 'SSF3352431'),
('+918767786776', 'SSF2894856'),
('+918107258153', 'SSF3995088'),
('+918726324894', 'SSF2760189'),
('+918239328906', 'SSF2620027'),
('+918290810635', 'SSF3473000'),
('+918278664296', 'SSF4053543'),
('+918769933266', 'SSF2427621'),
('+918558674560', 'SSF2427481'),
('+918094911681', 'SSF4184811'),
('+918865239280', 'SSF3128263'),
('+918690054682', 'SSF4253609'),
('+919557924624', 'SSF3004373'),
('+919467354427', 'SSF2555456'),
('+919822524512', 'SSF3015728'),
('+919464655858', 'SSF3452226'),
('+919496464644', 'SSF3512243'),
('+919464676484', 'SSF3440519'),
('+919494646464', 'SSF3516212'),
('+919057591462', 'SSF3103624'),
('+919131379928', 'SSF4032517'),
('+919683854455', 'SSF3025958'),
('+919958877456', 'SSF3434387'),
('+919876434346', 'SSF3167455'),
('+919797799797', 'SSF3695983'),
('+919636897836', 'SSF3916450'),
('+919864989494', 'SSF3488381'),
('+919656839060', 'SID951376006557'),
('+919680268520', 'SSF2578306'),
('+919587265470', 'SSF2427516'),
('+919958888889', 'SSF3882996'),
('+919521160422', 'SSF3808962'),
('+919511375236', 'SSF3565554'),
('+919950820216', 'SSF2480546'),
('+919784278141', 'SSF3188432'),
('+919527738816', 'SSF2813062'),
('+919685679556', 'SSF2967628'),
('+919145858655', 'SSF3764001'),
('+919509611255', 'SSF3969595'),
('+919001374826', 'SSF2947696'),
('+919467344875', 'SSF2501650'),
('+919983321612', 'SSF2832432'),
('+919983475217', 'SSF2316316'),
('+919889959594', 'SSF2530938'),
('+919494676544', 'SSF3280559'),
('+919631568566', 'SSF3760204'),
('+919532404949', 'SSF2567532'),
('+919828616059', 'SSF4163152'),
('+916378567856', 'SSF2692322'),
('+916378315229', 'SSF2605859'),
('+916494873767', 'SSF3102898'),
('+916378344099', 'SSF3907120'),
('+916557485755', 'SSF3326548'),
('+917575765663', 'SSF3020980'),
('+917979786767', 'SSF2911726'),
('+917873767997', 'SSF2716745'),
('+917568265697', 'SID951374037837'),
('+917696003020', 'SSF3766603'),
('+917309174661', 'SSF3894436'),
('+917410921994', 'SSF4307612'),
('+917733555882', 'SSF3180441'),
('+917227025722', 'SSF2387077'),
('+917073321628', 'SSF3416800'),
('+917924788952', 'SSF3873289'),
('+917062495175', 'SSF3627080'),
('+917425001184', 'SSF3920913'),
('+917742753992', 'SSF3473772'),
('+917412960694', 'SSF2592663'),
('+918554544856', 'SSF3347801'),
('+918851496665', 'SSF3671037'),
('+918854475998', 'SSF3692590'),
('+918302213724', 'SSF2347226'),
('+918290191655', 'SSF3928251'),
('+918079463484', 'SSF3638614'),
('+918079668763', 'SSF3727159'),
('+918754679466', 'SSF3098864'),
('+918955653065', 'SSF3669892'),
('+918746767676', 'SSF3048388'),
('+918875623259', 'SSF2520172'),
('+918466790946', 'SSF3330383'),
('+918239825550', 'SSF2738366'),
('+918964949949', 'SSF3215366'),
('+918444679579', 'SSF2743142'),
('+918219994677', 'SSF2561703'),
('+918586605868', 'SSF2696040'),
('+918440093050', 'SSF3729987'),
('+918290357970', 'SSF2893493'),
('+918302127886', 'SSF2697669'),
('+918855844258', 'SSF2611812'),
('+918079024239', 'SSF3631399'),
('+918619119460', 'SSF4155917'),
('+918368726868', 'SSF3254179'),
('+919680990237', 'SSF3379421'),
('+919983484967', 'SSF3701590'),
('+919454349488', 'SSF2877628'),
('+919636568457', 'SSF3485537'),
('+919845164646', 'SSF3151834'),
('+919813394614', 'SID951376026680'),
('+919660279434', 'SSF2347228'),
('+919602459063', 'SSF3674795'),
('+919829312516', 'SSF3602268'),
('+919565756947', 'SSF2570473'),
('+919050008349', 'SSF2363570'),
('+919509579434', 'SSF2485768'),
('+919358618614', 'SSF2687436'),
('+919694872813', 'SSF2340746'),
('+919685647518', 'SSF2545666'),
('+919889628218', 'SSF2666137'),
('+919898365355', 'SSF3311255'),
('+919464646468', 'SSF3445621'),
('+919654288676', 'SSF2761410'),
('+919464646464', 'SSF3138078'),
('+919464946846', 'SSF2816052'),
('+919565467554', 'SSF2749993'),
('+919378927938', 'SSF2642694'),
('+919828921003', 'SSF3775640'),
('+919636328331', 'SSF4024687'),
('+919898911528', 'SSF2693224'),
('+919883848750', 'SSF3685154'),
('+919521792262', 'SSF3890601'),
('+919784109563', 'SSF3026672'),
('+919145830204', 'SSF3242219'),
('+919488698885', 'SSF3414968'),
('+919784785957', 'SID951375021437'),
('+919549301961', 'SSF3904069'),
('+919672705518', 'SSF3985603'),
('+919767799781', 'SSF2552173'),
('+919497679484', 'SSF2301743'),
('+919660723167', 'SSF3921484'),
('+916464548448', 'SSF3572780'),
('+916245222288', 'SSF2922117'),
('+917569853284', 'SSF2359772'),
('+917254046923', 'SSF3249769'),
('+917984673460', 'SSF3550913'),
('+918233713128', 'SSF2400284'),
('+918271459796', 'SSF3384779'),
('+918757452545', 'SSF3463868'),
('+918955818764', 'SSF3701602'),
('+918306723680', 'SSF3159928'),
('+918154648478', 'SSF3701920'),
('+919728386571', 'SSF3285592'),
('+919929683183', 'SSF2647232'),
('+919521126582', 'SSF2864908'),
('+919646464646', 'SSF2460001'),
('+919571256665', 'SSF3193427'),
('+919855464215', 'SSF3151960'),
('+918809534469', 'SID951375848660'),
('+918709797390', 'SSF2816140'),
('+917746824713', 'SSF4138271'),
('+917370059907', 'SSF3410717'),
('+917856019437', 'SSF4503515'),
('+917292921174', 'SSF4019290'),
('+918400985760', 'SSF3304325'),
('+918102820026', 'SSF3346877'),
('+918349806468', 'SSF2926510'),
('+918252154614', 'SSF3189607'),
('+919199215591', 'SID951375758517'),
('+919340173968', 'SSF3151799'),
('+919905320047', 'SSF3385508'),
('+919576828582', 'SSF4007002'),
('+919926144009', 'SSF5011609'),
('+918319715871', 'CID224401449'),
('+918235403048', 'SID2125766154'),
('+917061841281', 'SID951375091562'),
('+919257326296', 'SID951375194221'),
('+917779840579', 'SSF2857543'),
('+917631157026', 'SSF2856169'),
('+919572658553', 'SSF2885221'),
('+919162771076', 'SSF2856107'),
('+917491034993', 'SSF4232770'),
('+917858006227', 'SSF3369079'),
('+917024340060', 'SSF4093281'),
('+917250942082', 'SSF3037425'),
('+918450845877', 'SSF4326755'),
('+918092900231', 'SSF3120029'),
('+919155775788', 'SSF4238549'),
('+919343591073', 'SSF4137630'),
('+919399042711', 'SSF4137629'),
('+919691816981', 'SSF3060401'),
('+919098718491', 'SSF4644391'),
('+919329630090', 'SSF4651859'),
('+919304320198', 'SSF4383696'),
('+919882858159', 'SSF3376201'),
('+917379329060', 'SID951376057382'),
('+919950886593', 'SSF2365377'),
('+919142308711', 'SSF2735449'),
('+917447013687', 'SSF2425854'),
('+918302675874', 'SSF2676147'),
('+919244585418', 'SSF4511576'),
('+919665445684', 'CID204503269'),
('+917416091564', 'SSF3003386'),
('+918690791578', 'SSF3990958'),
('+918083277018', 'SID951375601101'),
('+919939013980', 'SSF3546528'),
('+916262520187', 'SSF3589659'),
('+917979025248', 'SSF3448567'),
('+917762800166', 'SSF3869234'),
('+917067867026', 'CID261400976'),
('+918235463521', 'SID2125049306'),
('+918450040352', 'CID050408984'),
('+916301478429', 'SSF4285112'),
('+916207755957', 'SSF3978867'),
('+916258735805', 'SSF2946751'),
('+916367323441', 'SSF4303720'),
('+916262964721', 'SSF4320877'),
('+916205605053', 'SSF2661446'),
('+916205494056', 'SSF4334323'),
('+916264100593', 'SSF3635332'),
('+917878417055', 'SSF3960888'),
('+917852883034', 'SSF3691991'),
('+917070870977', 'SSF5767943'),
('+917024590714', 'SSF3845321'),
('+917426093765', 'SSF3012319'),
('+917485263996', 'SSF3463047'),
('+917742083912', 'SSF3485154'),
('+917091667527', 'SSF3355575'),
('+917742776779', 'SSF4484143'),
('+917250651970', 'SSF4077452'),
('+917779825054', 'SSF2977954'),
('+917657757959', 'SSF2916547'),
('+917440341934', 'SID951376015655'),
('+918319475457', 'SID951373082586'),
('+918340182595', 'SID951373714299'),
('+918003001497', 'SSF3345807'),
('+918935956873', 'SSF4240465'),
('+918353467676', 'SSF2723179'),
('+918764222456', 'SSF3326527'),
('+918103545410', 'SSF3855856'),
('+918290633862', 'SSF2587407'),
('+918302376910', 'SSF3764628'),
('+918109190934', 'SSF5000929'),
('+918719008531', 'SSF2523378'),
('+919753213435', 'SSF4727381'),
('+919006422691', 'SSF3744705'),
('+919328095612', 'SSF3496637'),
('+919162872364', 'SSF5202782'),
('+919981673004', 'SID951373276770'),
('+919783311416', 'SSF2581185'),
('+919680482234', 'SID951374300343'),
('+919079023206', 'SSF3859045'),
('+919572538273', 'SSF3482780'),
('+919693529075', 'SSF5230767'),
('+919852763862', 'SSF3197197'),
('+919110062510', 'SID951375984561'),
('+919530223976', 'SSF3632668'),
('+919691630158', 'SSF5446628'),
('+919601462872', 'SSF4642812'),
('+919955750271', 'SSF4015145'),
('+919675698858', 'SSF3578372'),
('+919799198126', 'SSF3232795'),
('+919351504744', 'SSF5277093'),
('+919559048734', 'SSF2941554'),
('+919661095215', 'SSF4117028'),
('+919752226617', 'SSF3585763'),
('+919587861480', 'SSF2697457'),
('+919340491571', 'SSF3850464'),
('+919680251672', 'SSF2542310'),
('+919098930880', 'SSF3656860'),
('+916264390904', 'SSF5053916'),
('+916390718448', 'SSF2491488'),
('+916367385204', 'SSF3605211'),
('+916375273931', 'SSF3919106'),
('+916261939941', 'SSF2991266'),
('+916377875699', 'SSF3489226'),
('+916287225847', 'SSF4886963'),
('+916378954491', 'SSF2433845'),
('+916376309644', 'SSF2464111'),
('+916206727737', 'SSF4940717'),
('+916376205429', 'SSF3004183'),
('+916377232225', 'SSF2317285'),
('+917414004544', 'SSF2639083'),
('+917081518341', 'SSF4648754'),
('+917069160793', 'SSF3668389'),
('+917297896610', 'SSF4035338'),
('+917976810100', 'SSF3910372'),
('+917742280287', 'SSF3879244'),
('+917230857781', 'SSF3668635'),
('+917340339138', 'SSF3648273'),
('+917898046588', 'SSF3388550'),
('+917320013684', 'SSF4452405'),
('+917357681554', 'SSF2724214'),
('+917463077281', 'SSF4621289'),
('+917979977761', 'SSF3232008'),
('+917877639842', 'SSF2588564'),
('+917033602465', 'SSF4888463'),
('+917544905248', 'SSF4111250'),
('+917586923548', 'SSF3511646'),
('+917891633815', 'SSF3559474'),
('+917737038414', 'SSF4756536'),
('+917850026829', 'SSF5239974'),
('+917610854461', 'SSF3548832'),
('+917878488484', 'SSF2582702'),
('+917742085190', 'SSF4005935'),
('+917878293061', 'SID951373834293'),
('+917061350667', 'SSF4768409'),
('+917493823657', 'SSF3479509'),
('+917828745758', 'SSF2950122'),
('+917884679885', 'SSF3689588'),
('+918824330072', 'SSF5214338'),
('+918976649259', 'SSF2967391'),
('+918852049841', 'SSF4014998'),
('+918529614720', 'SSF4150671'),
('+918769115956', 'SSF4607696'),
('+918306848392', 'SSF3443575'),
('+918302792701', 'SSF2608050'),
('+918709106443', 'SSF3118627'),
('+918325963241', 'SSF3741242'),
('+918690660798', 'SSF5035039'),
('+918890894402', 'SSF2990821'),
('+918306539437', 'SSF4002285'),
('+918533544856', 'SSF3013108'),
('+918302467936', 'SSF4999866'),
('+918696800609', 'SSF5224430'),
('+918769348426', 'SSF3917453'),
('+918875781615', 'SSF3344871'),
('+918434309453', 'SSF3431521'),
('+918521899989', 'SSF3704404'),
('+918107359572', 'SSF3998685'),
('+918890871087', 'SSF4073578'),
('+918084306139', 'SSF2468097'),
('+918271586630', 'SSF2923043'),
('+919261729329', 'SSF2576404'),
('+919399577822', 'SSF3054065'),
('+919340044328', 'SSF3780779'),
('+919993249453', 'SSF3252876'),
('+919351549477', 'SSF5168913'),
('+919928280690', 'SSF3140614'),
('+919729851029', 'SSF3594337'),
('+919799216122', 'SSF3708764'),
('+919351131087', 'SSF2972900'),
('+919772709647', 'SSF2843774'),
('+919643556826', 'SSF2886765'),
('+919955757225', 'SSF4198050'),
('+919521893730', 'SSF4471924'),
('+919587852904', 'SSF2934601'),
('+919939325421', 'SSF3668041'),
('+919304493526', 'SSF2859684'),
('+919979894794', 'SSF3131716'),
('+919601833063', 'SSF3950169'),
('+919057281646', 'SSF3745272'),
('+919244042014', 'SSF3493094'),
('+919549693640', 'SSF4823255'),
('+919525175037', 'SSF4968385'),
('+919113706961', 'SSF3627311'),
('+919636502290', 'SSF2668975'),
('+919525806606', 'SSF4649169'),
('+919929208854', 'SSF5186124'),
('+919199373174', 'SSF4765034'),
('+919001090809', 'SSF3861006'),
('+919886656467', 'SSF3568589'),
('+919235020629', 'SSF5435949'),
('+919263726798', 'SSF2871407'),
('+919376795379', 'SSF3578028'),
('+919918847543', 'SSF4494833'),
('+919693684026', 'SSF3215049'),
('+919834854787', 'SSF3723484'),
('+919155857502', 'SSF5440338'),
('+919568747654', 'SSF3104631'),
('+919588027090', 'SSF2674027'),
('+919798477068', 'SSF4119823'),
('+919846848454', 'SSF3087452'),
('+919636480371', 'SSF3251527'),
('+919958865488', 'SSF3577100'),
('+919610184673', 'SSF2995518'),
('+919545488494', 'SSF3602041'),
('+919734934676', 'SSF3414139'),
('+919024973252', 'SSF4135230'),
('+919867544545', 'SSF3130117'),
('+919137903060', 'SSF3610747'),
('+919839546520', 'SSF3999240'),
('+919105050562', 'SSF3625226'),
('+919587721574', 'SSF2385325'),
('+919672432069', 'SSF3142021'),
('+919636412895', 'SSF4377047'),
('+919587319423', 'SSF3676481'),
('+919103945440', 'SSF4277003'),
('+919352873037', 'SSF2409371'),
('+919024688898', 'SSF4273187'),
('+919351856531', 'SSF4273200'),
('+919123245033', 'SSF4251064'),
('+919789766464', 'SSF2612876'),
('+919414430479', 'SSF2707436'),
('+919602269231', 'SSF4022599'),
('+919587549746', 'SSF4254418'),
('+919125455325', 'SSF3196042'),
('+919461252405', 'SSF2868459'),
('+919929080912', 'SSF3984560'),
('+919771360164', 'SSF2359030'),
('+919630434535', 'SSF3810190'),
('+919679798404', 'SID951375910013'),
('+919770731882', 'SSF3494110'),
('+919024188020', 'SSF4687239'),
('+919784158865', 'SSF3589540'),
('+919828219703', 'SSF3484162'),
('+919660963872', 'SSF2833615'),
('+919636224047', 'SSF4119661'),
('+919304588362', 'SSF4215312'),
('+917856014961', 'SSF4458274'),
('+916667946766', 'SSF2366577'),
('+916541288753', 'SSF2695961'),
('+916486405688', 'SSF3721991'),
('+916378698237', 'SSF3907543'),
('+917878328662', 'SSF3391193'),
('+918306799183', 'SSF4556636'),
('+918306499598', 'SSF3838598'),
('+918094532327', 'SSF4336540'),
('+919963582789', 'SSF3431762'),
('+919984224471', 'SSF3374465'),
('+919652422538', 'SSF3155382'),
('+916200549754', 'SSF3386122'),
('+916299765592', 'SID951375203688'),
('+916863356465', 'SSF2664276'),
('+916267207746', 'SID951375422429'),
('+916284001707', 'SSF4829759'),
('+916367959225', 'SSF4152362'),
('+916558456844', 'SSF3682470'),
('+916464849448', 'SSF3689388'),
('+916202078513', 'SSF3542141'),
('+916375521186', 'SSF3437346'),
('+917851095058', 'SSF3219866'),
('+917875433957', 'SSF2980196'),
('+917488544981', 'SSF4129521'),
('+917340319960', 'SSF4001696'),
('+917321073758', 'SSF3007412'),
('+917340029994', 'SSF4592426'),
('+917697182878', 'SSF3872194'),
('+917877094311', 'SSF3716998'),
('+917999844695', 'SSF3563356'),
('+917297995593', 'SID951375383876'),
('+917742687338', 'SSF4412544'),
('+917985439975', 'SSF2896685'),
('+917854268448', 'SSF3610094'),
('+917766864631', 'SSF2831076'),
('+917413891373', 'SSF4777736'),
('+917206563885', 'SID951373493416'),
('+917877795472', 'SSF2546569'),
('+917742818447', 'SSF3748796'),
('+918758698355', 'SSF3575463'),
('+918829889246', 'SSF4004354'),
('+918307309246', 'SSF4004312'),
('+918936802703', 'SSF2922440'),
('+918084608829', 'SSF3477131'),
('+918564627665', 'SSF3883048'),
('+918290167744', 'SSF3895853'),
('+918829818411', 'SSF2685086'),
('+918686897979', 'SSF2761487'),
('+918890147566', 'SSF3493592'),
('+918560839801', 'SSF3359890'),
('+918003709484', 'SSF3601224'),
('+918003283057', 'SSF4014528'),
('+918949592599', 'SSF3575281'),
('+918107748719', 'SSF2886276'),
('+918092808156', 'SSF2763225'),
('+918003578436', 'SSF3644783'),
('+918646437043', 'SSF3030616'),
('+918302158506', 'SSF3510413'),
('+918938429566', 'SSF3890602'),
('+919882819122', 'SSF3531981'),
('+919928848432', 'SSF4483549'),
('+919680632623', 'SSF4601760'),
('+919771577500', 'SSF4873107'),
('+919950464575', 'SSF2318078'),
('+919868646056', 'SSF2985477'),
('+919670855546', 'SSF3481774'),
('+919660728253', 'SSF4129998'),
('+919128757361', 'SSF4357221'),
('+919835965656', 'SSF3224634'),
('+919983652886', 'SSF3165574'),
('+919770962558', 'SSF3514957'),
('+919680870989', 'SSF4152354'),
('+919314576703', 'SSF4310115'),
('+919525916416', 'SSF4826204'),
('+919982701208', 'SSF2389245'),
('+919352635611', 'SSF4727010'),
('+919256272540', 'SSF2700962'),
('+919864840484', 'SSF3087451'),
('+919931568806', 'SID2125477863'),
('+919557975949', 'SSF2973861'),
('+919533662566', 'SSF2951817'),
('+919256278581', 'SSF4122009'),
('+919934854722', 'SSF3459073'),
('+919523689613', 'SSF3957303'),
('+919341074126', 'SSF4531544'),
('+919116841829', 'SSF4668700'),
('+919776575742', 'SID951375943616'),
('+919257467426', 'SSF2678783'),
('+919828524321', 'SSF3405795'),
('+919787678879', 'SSF3796002'),
('+919983591877', 'SSF3994987'),
('+919351155118', 'SSF2669262'),
('+916354640761', 'SSF2631880'),
('+916367354091', 'SSF3850875'),
('+916398428101', 'SSF2846419'),
('+916350054112', 'SSF2829699'),
('+916346484484', 'SSF3575611'),
('+916367644304', 'SSF4457133'),
('+916261276668', 'CID219406273'),
('+916350538173', 'SSF3961840'),
('+917300360862', 'SSF3804584'),
('+917016226241', 'SSF3210729'),
('+917978549794', 'SSF2703658'),
('+917737044582', 'SSF3828525'),
('+917665051453', 'SSF4131285'),
('+917852848095', 'SSF3928907'),
('+917850048120', 'SSF2377769'),
('+917427082728', 'SSF3560496'),
('+917357670292', 'SSF4757520'),
('+917370065901', 'SSF2836043'),
('+918686767979', 'SSF2727761'),
('+918905943966', 'SSF2725867'),
('+918890779091', 'SSF3287575'),
('+918690704495', 'SSF4082709'),
('+918562553457', 'SSF3887062'),
('+918875735834', 'SSF2725251'),
('+918528378020', 'SSF3149081'),
('+918962858613', 'SSF4235192'),
('+918890482044', 'SSF4310753'),
('+918890951926', 'SSF2844998'),
('+918107976123', 'SSF4410070'),
('+918683838383', 'SSF3555382'),
('+918824054144', 'SSF3676336'),
('+918955056758', 'SSF3300665'),
('+918690701293', 'SSF3102295'),
('+918239697446', 'SSF2341939'),
('+918769685453', 'SSF2699655'),
('+918690846927', 'SSF4202867'),
('+918209599618', 'SSF2708481'),
('+918829989155', 'SSF2664619'),
('+918305308035', 'SSF3775428'),
('+918866368104', 'SSF4014529'),
('+918643434461', 'SSF2864634'),
('+918107756678', 'SSF3961841'),
('+919965494616', 'SSF3535668'),
('+919302255660', 'SSF3117456'),
('+919652556658', 'SSF3444229'),
('+919509005982', 'SSF3994988'),
('+919352256018', 'SSF2679912'),
('+919571610296', 'SSF2938128'),
('+919162799344', 'SSF2357774'),
('+919024423624', 'SSF4523238'),
('+919928941165', 'SSF2988373'),
('+919464649489', 'SSF3436155'),
('+919399789707', 'SID951375664908'),
('+919580220907', 'SSF3134816'),
('+919610405124', 'SSF2728178'),
('+919636687667', 'SSF2804906'),
('+919256424817', 'SSF4452649'),
('+919511577321', 'SSF4476034'),
('+919649348278', 'SSF3554164'),
('+919024563702', 'SSF3817071'),
('+919772578857', 'SSF2971353'),
('+919983478227', 'SSF2603801'),
('+919509642190', 'SSF4122981'),
('+919894664616', 'SSF3626608'),
('+919664124357', 'SSF2360918'),
('+916784389488', 'SSF3172978'),
('+916168303461', 'SSF2700083'),
('+916665778886', 'SSF3677642'),
('+916388457848', 'SSF2351250'),
('+916767467648', 'SSF3112183'),
('+916464848484', 'SSF3375774'),
('+916376446011', 'SSF3896476'),
('+917665136446', 'SSF3280604'),
('+917340248155', 'SSF3462135'),
('+917878274526', 'SSF2499564'),
('+917427054708', 'SSF2814251'),
('+918458989493', 'SSF4031814'),
('+918094271207', 'SSF3384912'),
('+918962393008', 'SSF3790144'),
('+918954765589', 'SSF2741973'),
('+918619225775', 'SSF2327032'),
('+918819833211', 'SSF4076497'),
('+918103277140', 'SSF3044260'),
('+918005501172', 'SSF2638910'),
('+918094400912', 'SSF2804908'),
('+918000495185', 'SSF2643757'),
('+918955745070', 'SSF2745135'),
('+918686577585', 'SSF3437919'),
('+918690042029', 'SSF4151480'),
('+918107424432', 'SSF2314236'),
('+918290919726', 'SSF2585926'),
('+918409464334', 'SSF2676040'),
('+918079040699', 'SSF2701015'),
('+918302750781', 'SSF3401703'),
('+918824206548', 'SSF4288053'),
('+918905039733', 'SSF3481809'),
('+919918502849', 'SSF2397007'),
('+919846499456', 'SSF2685851'),
('+919655867578', 'SSF2675578'),
('+919448489464', 'SSF3274972'),
('+919602500802', 'SSF4039207'),
('+919448344646', 'SSF3169770'),
('+919672548951', 'SSF2551868'),
('+919131464643', 'SSF4076500'),
('+919358427073', 'SSF4408805'),
('+919494664656', 'SSF3384607'),
('+919928456758', 'SSF2749638'),
('+919602522475', 'SSF3888002'),
('+919982932726', 'SSF2285380'),
('+919669901113', 'SSF4288252'),
('+919680678541', 'SSF2397259'),
('+919887393595', 'SSF2930790'),
('+919521471746', 'SSF3984322'),
('+919636648265', 'SSF2925515'),
('+919465161961', 'SSF3713143'),
('+916350382857', 'SSF4032516'),
('+916561656499', 'SSF3823243'),
('+916388784243', 'SSF2302085'),
('+916564689479', 'SSF3202870'),
('+916376998672', 'SID951375933385'),
('+916868449895', 'SSF3034228'),
('+916350009107', 'SSF3721330'),
('+916743511684', 'SSF3287295'),
('+917954354884', 'SSF2581306'),
('+917734032308', 'SSF3971165'),
('+917874623153', 'SSF3629410'),
('+917733046484', 'SSF3331782'),
('+917727033597', 'SSF3692301'),
('+917891616489', 'SSF3721562'),
('+917073366913', 'SSF3629467'),
('+917300269687', 'SSF3287467'),
('+917877625658', 'SSF2750194'),
('+917665891274', 'SSF2418640'),
('+917426842606', 'SSF3540535'),
('+917877453041', 'SSF4399454'),
('+918568723354', 'SSF3248869'),
('+918568446544', 'SSF3229302'),
('+918468034064', 'SSF4151502'),
('+918696821541', 'SSF2815333'),
('+918824426946', 'SSF3243849'),
('+918958623212', 'SSF3181077'),
('+918624785699', 'SSF3564739'),
('+918775769873', 'SSF3098683'),
('+918690503237', 'SSF2732315'),
('+918079646494', 'SSF3638615'),
('+918239317780', 'SSF2427620'),
('+918824549565', 'SSF2492285'),
('+918696231437', 'SSF2358770'),
('+918209738958', 'SSF4051997'),
('+918499494645', 'SSF3205212'),
('+919495848484', 'SSF3594326'),
('+919859826865', 'SSF2761651'),
('+919785861118', 'SSF3652887'),
('+919828987545', 'SSF3652886'),
('+919351357056', 'SSF2959893'),
('+919764481861', 'SSF2669394'),
('+919494946799', 'SSF2669497'),
('+919571391522', 'SSF3117234'),
('+919540607232', 'SSF2966002'),
('+919568885588', 'SSF3709807'),
('+919950887803', 'SSF3929736'),
('+919876434343', 'SSF3187409'),
('+919494649878', 'SSF2356856'),
('+919079691418', 'SSF2316311'),
('+919976764676', 'SSF3692531'),
('+919642542586', 'SSF2914432'),
('+919654278626', 'SSF3007604'),
('+919024533753', 'SSF3147987'),
('+919465546407', 'SSF3440679'),
('+919001036230', 'SSF2485046'),
('+919521669312', 'SSF3549960'),
('+919449868487', 'SSF3196609'),
('+919406237391', 'SSF3199341'),
('+919464646599', 'SSF3452297'),
('+919494664649', 'SSF3426949'),
('+919497667464', 'SSF3425801'),
('+919494646646', 'SSF3492141'),
('+919494648484', 'SSF2427656'),
('+919649327482', 'SSF2378891'),
('+919461618680', 'SSF3924238'),
('+919216487966', 'SSF2931999'),
('+919675319448', 'SSF2690455'),
('+919610103966', 'SSF3323891'),
('+919521442181', 'SSF2543334'),
('+916131919191', 'SSF3663115'),
('+916388477352', 'SID951374431726'),
('+916758890957', 'SSF3330195'),
('+916446494646', 'SSF3700799'),
('+916376468918', 'SID951376046687'),
('+916865255258', 'SSF2969840'),
('+917568679407', 'SSF3799572'),
('+917067767673', 'SSF2912033'),
('+917763821397', 'SSF3790219'),
('+917851909504', 'SSF3800181'),
('+917568912071', 'SSF4014519'),
('+917974115499', 'SSF2955754'),
('+917073878481', 'SSF3161459'),
('+917764648494', 'SSF3225655'),
('+917665107803', 'SSF2505706'),
('+917878332797', 'SSF2427679'),
('+917967767346', 'SSF2459454'),
('+917849928915', 'SSF2327031'),
('+918724675845', 'SSF3212535'),
('+918662478998', 'SSF3578213'),
('+918890322098', 'SSF3607439'),
('+918107601033', 'SSF2362141'),
('+918949923037', 'SSF2611813'),
('+918966476648', 'SSF3003638'),
('+918769338796', 'SSF4094641'),
('+918302255605', 'SSF2592639'),
('+919548872532', 'SSF3603879'),
('+919784232536', 'SSF2319543'),
('+919024189667', 'SID951375156804'),
('+919413772138', 'SSF3883941'),
('+919509004953', 'SSF3782612'),
('+919544788999', 'SSF3104115'),
('+919464521249', 'SSF3314596'),
('+919449976763', 'SSF2912036'),
('+919946798484', 'SSF3464786'),
('+919664255845', 'SSF3956868'),
('+919434835644', 'SSF2900934'),
('+919636124512', 'SSF3602402'),
('+919799505776', 'SSF2458361'),
('+919935859438', 'SSF3743250'),
('+919958888888', 'SSF3316447'),
('+919116301019', 'SSF3955708'),
('+919494646566', 'SSF3325426'),
('+919369695745', 'SSF2352009'),
('+919464887678', 'SSF3429892'),
('+919494646849', 'SSF3445660'),
('+919772270841', 'SSF2820716'),
('+919783542131', 'SSF3597350'),
('+919571335618', 'SSF2555828'),
('+919454348464', 'SSF2717317'),
('+919464349948', 'SSF3452365'),
('+919660100605', 'SSF2915085'),
('+919351063543', 'SSF3405323'),
('+919057706574', 'SSF3405412'),
('+919335182764', 'SSF2688900'),
('+919858757272', 'SSF3123591'),
('+919571688112', 'SSF2964667'),
('+919358951260', 'SSF3784139'),
('+919928936404', 'SSF2764124'),
('+919797978787', 'SSF2552175'),
('+919357436875', 'SSF2764940'),
('+916565959593', 'SSF2690533'),
('+916254349389', 'SSF3721737'),
('+917791077957', 'SSF2341432'),
('+918757974184', 'SSF2922178'),
('+918239364152', 'SSF2554605'),
('+918496464646', 'SSF3727176'),
('+918824929520', 'SSF2618533'),
('+919987639644', 'SSF2432423'),
('+919795895968', 'SSF2473962'),
('+919652253658', 'SID951374061133'),
('+919735653566', 'SSF3432140'),
('+919346826729', 'SSF2764835'),
('+919845464646', 'SSF3151961'),
('+919952438497', 'SSF3483999'),
('+919468434985', 'SSF2764874'),
('+919559596889', 'SSF3718082'),
('+919571648873', 'SSF3602229'),
('+919315437965', 'SSF2911150'),
('+916232934188', 'SSF5034984'),
('+917999474679', 'SID951373192871'),
('+918269161046', 'SID951373652178'),
('+918770946103', 'SID951375971888'),
('+919001967320', 'SID951376056957'),
('+919721372391', 'SSF2789600'),
('+916261367154', 'SSF4407672'),
('+917470429612', 'SID951373747906'),
('+917700068467', 'SSF4379633'),
('+919617723155', 'SSF3435279'),
('+919644313416', 'SSF3466933'),
('+919617752520', 'SSF4173432'),
('+919801670518', 'SID951374868409'),
('+918290313560', 'SID951375812490'),
('+918306046121', 'SID951375384002'),
('+919472009046', 'SSF3050426'),
('+919516462206', 'SSF2974532'),
('+917041873316', 'SID951375798570'),
('+917828997176', 'SID951373017919'),
('+916261537457', 'SSF3577451'),
('+917898068640', 'SID951374270395'),
('+919508193421', 'SSF4404787'),
('+916201357715', 'SID951373394352'),
('+919670011828', 'SSF4017543'),
('+919517070208', 'SSF4299525'),
('+919340483360', 'SID951374965311'),
('+916267816369', 'SID951373940858'),
('+918797681640', 'SSF5320734'),
('+916296794959', 'SID951374576111'),
('+918982439588', 'CID225400807'),
('+918630316018', 'SSF5035258'),
('+917781844039', 'SSF5347245'),
('+917024001203', 'SID951373246631'),
('+917470987276', 'CID951376201120'),
('+917309716145', 'SSF3883891'),
('+916265898395', 'SSF4068164'),
('+918640076726', 'SSF3241354'),
('+917091378355', 'SSF5419677'),
('+919136354644', 'SSF4999618'),
('+917368081938', 'SSF5722220'),
('+917879791565', 'SSF3653397'),
('+918957396880', 'SSF5794623'),
('+917372013047', 'SSF3019668'),
('+919753997954', 'SSF3567409'),
('+917258810802', 'SSF4179995'),
('+919351056635', 'SSF5437886'),
('+918984687816', 'SID951372872405'),
('+916202555850', 'SID951375783381'),
('+919770806125', 'SSF3965892'),
('+918485907691', 'SSF4253166'),
('+919579455350', 'SID951374999744'),
('+918793400320', 'SSF2597702'),
('+919696812551', 'SSF4983919'),
('+917566699953', 'SID951373546509'),
('+918290235202', 'SSF2358133'),
('+918084119410', 'SID951373408282'),
('+918757203543', 'SSF3998861'),
('+918423330277', 'SSF4509266'),
('+919340724715', 'SSF5822460'),
('+917061243923', 'SID951375593004'),
('+919302755676', 'SID951373798504'),
('+919060204394', 'SSF3294973'),
('+919651336147', 'SSF4305437'),
('+919584557560', 'SSF3597360'),
('+919335718326', 'SID951374661109'),
('+919344884848', 'SID951374962850'),
('+916379751943', 'SID951373387568'),
('+918341373226', 'SSF5102339'),
('+916389780567', 'SSF4381293'),
('+917739394037', 'SID951374658778'),
('+916205580478', 'SID951375294836'),
('+917804056937', 'CID084702728'),
('+918208042180', 'SSF5374244'),
('+918103424153', 'SID951374131242'),
('+916263625655', 'SID951373513139'),
('+919695637632', 'SSF3081187'),
('+916200781996', 'SSF4078240'),
('+919793983338', 'SSF4688034'),
('+916267242891', 'SSF4978649'),
('+919767884997', 'SID951374610888'),
('+917354419899', 'SID2125689861'),
('+918767663794', 'SID951375640754'),
('+917489040822', 'SID951374705731'),
('+919142755040', 'SSF2630541'),
('+917806094158', 'SID2125042245'),
('+917828297878', 'SID951373172170'),
('+919798417186', 'SSF6330215'),
('+919919354800', 'SSF5492311'),
('+919001498617', 'SSF4030464'),
('+917739482306', 'SID951375369148'),
('+918890142762', 'SSF3890378'),
('+917762835562', 'SID951373663963'),
('+917692065271', 'CID142802220'),
('+916206795406', 'SSF3607028'),
('+916203156788', 'SSF4405349'),
('+918422078815', 'SID951374786799'),
('+919336530591', 'SSF5367149'),
('+919580307613', 'SSF5566978'),
('+919644213280', 'CID087102602'),
('+918718891109', 'CID129508281'),
('+918450010316', 'SID951375793312'),
('+919352617644', 'SSF4025782'),
('+918209551310', 'SSF5307965'),
('+917758938984', 'SSF3033378'),
('+917250215331', 'SID951374893732'),
('+917000859503', 'CID207302014'),
('+919645484655', 'SID951375755029'),
('+919329691710', 'SID951373942851'),
('+919102296562', 'SID951375943939'),
('+919931925512', 'SID951374927108'),
('+919693160697', 'SSF2763899'),
('+916264920976', 'SSF3703708'),
('+917974756140', 'SSF3694832'),
('+917870003804', 'SSF4376011'),
('+917898842634', 'SSF3761963'),
('+918207741238', 'SSF3477614'),
('+918815705265', 'SSF4103093'),
('+919801159163', 'SSF4163546'),
('+919358804958', 'SSF4680204'),
('+919303536812', 'SSF4361711'),
('+919356244528', 'SSF4512523'),
('+919523959873', 'SSF3475810'),
('+919950480223', 'SID951375404194'),
('+919973805102', 'SID951375927943'),
('+916260058783', 'SSF3710077'),
('+917812817758', 'SSF4610790'),
('+917011679113', 'SSF3517646'),
('+918102883879', 'SSF3459641'),
('+919098812505', 'SSF2454361'),
('+917368918352', 'SSF4515765'),
('+916265681603', 'SID951375277470'),
('+916260332943', 'SID101762'),
('+917415393054', 'SID951375395401'),
('+919234088580', 'SSF4579604'),
('+916287056915', 'SSF2494174'),
('+919523145413', 'SSF2499359'),
('+916268567238', 'SSF3280324'),
('+917782934109', 'SSF4489060'),
('+917089236570', 'SID951376034044'),
('+917620461832', 'SSF4033857'),
('+918521609113', 'SSF2965398'),
('+918409943870', 'SSF3535691'),
('+918799761779', 'SID951374964777'),
('+919289784173', 'SSF3992044'),
('+919058834360', 'SSF5036074'),
('+916202652274', 'SSF4048952'),
('+918764088053', 'SSF2724177'),
('+919244527572', 'SSF3838235'),
('+919572701144', 'SID951375243116'),
('+919621429312', 'SSF3104723'),
('+919682648560', 'SSF2936068'),
('+917903678644', 'SSF4788627'),
('+919798920164', 'SSF5018359'),
('+916265769124', 'SID951372853247'),
('+916201988124', 'SSF3473052'),
('+916266121182', 'SSF3178392'),
('+917654702837', 'SSF3458278'),
('+917079624306', 'SSF3446628'),
('+917389029122', 'SID951373227264'),
('+917389715869', 'SSF3825387'),
('+918209161770', 'SSF3806381'),
('+919244331937', 'SSF4360496'),
('+919506702295', 'SSF3513453'),
('+919294688573', 'SSF3369613'),
('+919644836689', 'SSF3087669'),
('+919304763152', 'SID951375250173'),
('+918279417106', 'SSF5185537'),
('+917979778486', 'SSF4313053'),
('+917761947649', 'SSF2406392'),
('+917357858415', 'SSF3040803'),
('+917742101335', 'SSF3322752'),
('+919329606576', 'SSF4120558'),
('+919570096385', 'SSF4215247'),
('+919887957246', 'SSF2682088'),
('+919358435315', 'SSF3157722'),
('+919935179385', 'SSF4806809'),
('+918003132540', 'SSF2497720'),
('+918233459110', 'SSF2681182'),
('+919343284268', 'SSF3544896'),
('+919256003818', 'SSF3039623'),
('+916376975090', 'SSF3333935'),
('+917781886089', 'SID951375585097'),
('+919466488768', 'SSF2908354'),
('+919406470962', 'SSF2301478'),
('+919257989506', 'SSF2478252'),
('+919728544744', 'SSF2722574'),
('+919691980722', 'SID951373227654'),
('+918464374838', 'SID951375162481'),
('+918059055131', 'SSF2596533'),
('+919745621375', 'SID951375750857'),
('+918160040811', 'SID951375577992'),
('+916268846137', 'SID951374999829'),
('+916203501580', 'SSF4550664'),
('+916266898935', 'SSF3808917'),
('+917317518755', 'SSF3187566'),
('+917700890572', 'SSF3384131'),
('+918319145627', 'SSF4479937'),
('+918541829063', 'SSF3338545'),
('+918809940054', 'SSF3864736'),
('+919142590767', 'SSF4102848'),
('+919555846835', 'SSF2398387'),
('+919399635357', 'SSF3509174'),
('+917999264052', 'SID951375061590'),
('+919771082538', 'SID951375705304'),
('+916267699348', 'SSF4070141'),
('+917991430154', 'SSF4045564'),
('+917321848724', 'SSF3654226'),
('+917979001619', 'SSF2297483'),
('+917859043544', 'SSF3851816'),
('+917050987818', 'SSF3008093'),
('+917397158408', 'SSF3832766'),
('+917828612439', 'SSF2656448'),
('+917858882330', 'SSF5511965'),
('+918757312296', 'SSF3891884'),
('+918002693351', 'SSF4302531'),
('+918292998228', 'SSF3505181'),
('+918235122933', 'SSF4106150'),
('+918815017667', 'SSF3709578'),
('+919835197732', 'SSF3838999'),
('+919263639189', 'SSF3541136'),
('+919279186620', 'SSF4692361'),
('+919610805664', 'SSF3526784'),
('+919570608507', 'SSF3364855'),
('+919621821322', 'SSF4824678'),
('+919104916677', 'SID951376047868'),
('+918890848024', 'SSF3304104'),
('+918306256108', 'SSF2458917'),
('+917771094711', 'SSF3570365'),
('+918767780282', 'SSF2981970'),
('+918122835135', 'SSF3555013'),
('+919926120415', 'SSF4032524'),
('+919939596347', 'SSF3398640'),
('+919262973726', 'SSF3393540'),
('+919234796681', 'SSF4010334'),
('+916261942928', 'SID951374005452'),
('+917583905965', 'SSF3470594'),
('+919685393146', 'SID951374998363'),
('+919301629197', 'SSF3658285'),
('+919302337820', 'SSF3745826'),
('+919340879993', 'SID124997'),
('+919005555296', 'SSF3690887'),
('+916287214620', 'SSF3113192'),
('+916375286436', 'SSF4033825'),
('+917319852289', 'SSF2592496'),
('+917991136940', 'SSF3574248'),
('+918409238906', 'SSF2302887'),
('+918873629982', 'SSF3590197'),
('+919636041290', 'SSF3673989'),
('+918084137126', 'SID951375953050'),
('+918972908681', 'SSF2685727'),
('+919454646446', 'SSF3016853'),
('+919001037613', 'SID951375278890'),
('+919928681230', 'SSF2377138'),
('+917548844555', 'SSF2772855'),
('+917568921147', 'SSF2549485'),
('+918307225639', 'SID951376162770'),
('+919654646586', 'SID951375049404'),
('+919918506255', 'SSF2392640'),
('+916377165281', 'SID951375318419'),
('+918103426906', 'SID951374604751'),
('+919340330711', 'SID951375891451'),
('+919950226018', 'SSF2640161'),
('+916263430824', 'SSF4240527'),
('+916387099928', 'SSF3938699'),
('+916264594393', 'SSF3558024'),
('+916269356136', 'SSF3474372'),
('+918353974675', 'SSF3802774'),
('+919238473770', 'SSF4029094'),
('+919770400467', 'SSF3810400'),
('+919009586019', 'SSF3121001'),
('+919981193642', 'SSF3176447'),
('+919301348238', 'SSF4208159'),
('+916260362423', 'SID951373254893'),
('+918225828493', 'SID951374696493'),
('+918789434784', 'SSF4651054'),
('+919669825052', 'SID951373203760'),
('+919330315152', 'SID951375225149'),
('+917724827961', 'CID081911724'),
('+916266018521', 'SID951373443154'),
('+918120653322', 'SID951373078981'),
('+917488905518', 'SSF5840288'),
('+919135789347', 'SSF5329433'),
('+919934290149', 'SID951375752301'),
('+919955583867', 'SID951374361573'),
('+919235809672', 'SSF4808018'),
('+919235245348', 'SSF4537276'),
('+919661923964', 'SID951375461999'),
('+919244245845', 'SID951375662925'),
('+919793072541', 'SSF4602498'),
('+919617379726', 'SID951373650009'),
('+916285459853', 'SID951375424674'),
('+919060201026', 'SID951375845700'),
('+919983161684', 'SID951374548105'),
('+916205400579', 'SSF4232729'),
('+919238652278', 'SSF4083995'),
('+918305198994', 'SID951375981674'),
('+919546516509', 'SSF5073055'),
('+919098115083', 'SID951374674042'),
('+919761987663', 'SID951375059832'),
('+919998972667', 'SID951375305894'),
('+919244008794', 'SID951375248896'),
('+916266853713', 'SID951374253106'),
('+917541990645', 'SID951374326661'),
('+919461557886', 'SID951375220302'),
('+916367891511', 'SSF3546531'),
('+919950931859', 'SID951376108257'),
('+919835129870', 'SSF3896987'),
('+918922971036', 'SSF5440300'),
('+916232169190', 'SSF5127957'),
('+916260188192', 'CID093700463'),
('+917089820145', 'SID951373756694'),
('+916201018980', 'SID951372982090'),
('+916264783989', 'SSF4019702'),
('+917049560417', 'SID2125145690'),
('+917651834315', 'SSF3201304'),
('+918651360735', 'SID951373936272'),
('+916268424317', 'SID951374644675'),
('+916267434789', 'SID2125561823'),
('+919865646766', 'SID2125643153'),
('+918817270832', 'SID951374087221'),
('+917723874511', 'SSF3756976'),
('+919399728036', 'SSF4681953'),
('+916200005284', 'SID951376092303'),
('+919906586295', 'SSF2927729'),
('+919162968586', 'SSF2740074'),
('+919372895672', 'SSF2739841'),
('+919341952359', 'SSF2372442'),
('+916200472692', 'SSF3014685'),
('+916206414341', 'SSF3677127'),
('+917646001929', 'SSF3421820'),
('+919153550515', 'SSF4599535'),
('+919572698233', 'SSF3690629'),
('+917879894730', 'SSF2896522'),
('+916299233106', 'SID951375236781'),
('+917519546473', 'SID951375015497'),
('+918809326560', 'SID951374571542'),
('+919006232580', 'SID951375574276'),
('+917783025400', 'SSF2555042'),
('+919523069885', 'SSF2611803'),
('+916263877875', 'SSF4232354'),
('+916391603428', 'SSF3738050'),
('+917635030461', 'SID951374503681'),
('+917068480365', 'SSF3055844'),
('+917067822702', 'SSF4113279'),
('+918849496860', 'SSF4706609'),
('+918853266979', 'SSF3007026'),
('+918109524924', 'SSF4015038'),
('+919241405956', 'SSF4409023'),
('+919826751484', 'SSF4048033'),
('+919303616026', 'CID050409577'),
('+919669804890', 'CID261401659'),
('+917758060017', 'SSF2636784'),
('+917549159140', 'SSF3314067'),
('+918120299494', 'SSF4030217'),
('+918000364574', 'SSF3857377'),
('+919102920282', 'SSF4010908'),
('+919060082446', 'SSF2965997'),
('+919798839864', 'SID951374308729'),
('+917275325105', 'SSF2985504'),
('+919343040254', 'SSF2318294'),
('+916260425857', 'CID213101199'),
('+919644424126', 'CID239800543'),
('+916264152410', 'SSF3121108'),
('+917851960912', 'SID951375021573'),
('+917970950338', 'SSF3646117'),
('+917489214698', 'SSF3651350'),
('+917042781213', 'SSF3401582'),
('+918809144621', 'SID951374966292'),
('+918360540879', 'SSF3439651'),
('+919329460471', 'SSF3589768'),
('+919576969883', 'SID951373150531'),
('+919770898489', 'SSF2417219'),
('+919109492041', 'SSF3558906'),
('+919199681107', 'SSF4845413'),
('+918809671324', 'SSF3339805'),
('+918578921072', 'SSF3273075'),
('+918949992418', 'SSF3267283'),
('+919955871345', 'SSF3551893'),
('+919199876367', 'SSF2666983'),
('+919955057735', 'SID951375454998'),
('+919358781713', 'SSF3115767'),
('+919137970541', 'SSF3273137'),
('+919302937039', 'SSF3557876'),
('+917568831086', 'SSF2374049'),
('+918651504235', 'SSF3110645'),
('+919967767575', 'SID951375894460'),
('+919516235362', 'SID951375431168'),
('+917426050520', 'SID951376037668'),
('+917725923255', 'SID951374351714'),
('+917600806302', 'SSF2847660'),
('+918248869850', 'SID951374142682'),
('+919636859995', 'SSF2952673'),
('+916263136372', 'SID951375915619'),
('+917424982886', 'SSF2613162'),
('+918303479693', 'SSF2858153'),
('+918890571873', 'SSF2302820'),
('+918875705587', 'SSF2320500'),
('+919799743996', 'SSF2830295'),
('+918930386303', 'SSF2574533'),
('+918804085849', 'SID951374669107'),
('+919691799468', 'SID951373315344'),
('+917703949318', 'SID951375467710'),
('+919546100247', 'SID951375199058'),
('+919801389279', 'SID951376145277'),
('+917209501295', 'SSF3350444'),
('+918717963465', 'SSF3590561'),
('+919153848148', 'SSF4512747'),
('+919263908054', 'SID951374993941'),
('+919572489047', 'SSF3180819'),
('+919691260614', 'SSF4561241'),
('+919540498828', 'SSF4110032'),
('+918292989078', 'SID2125018850'),
('+917724872704', 'SSF2447348'),
('+918962809770', 'SID951375037693'),
('+919302658676', 'SID951376050926'),
('+916260032413', 'SSF4229129'),
('+916287857500', 'SSF3780019'),
('+916200271951', 'SSF2918830'),
('+917061285820', 'SSF4395250'),
('+917746874705', 'SID951373556982'),
('+917492976524', 'SSF3439283'),
('+918292292344', 'SSF4338116'),
('+918863817262', 'SSF4111448'),
('+918340207161', 'SSF3463090'),
('+919508272509', 'SSF4325554'),
('+919693966945', 'SSF3480132'),
('+919060629738', 'SSF3407085'),
('+919234520478', 'SSF3554850'),
('+917737980490', 'SID951374688288'),
('+919958469360', 'SID951375722343'),
('+919575124170', 'SSF4254035'),
('+916200415420', 'SSF4131786'),
('+916266420357', 'SID951376054801'),
('+917489336487', 'SSF2940613'),
('+919142525795', 'SID951374880678'),
('+918271084219', 'SSF5113504'),
('+917067960602', 'SID951374781080'),
('+918809339174', 'SSF3392142'),
('+919905513615', 'SSF2841317'),
('+919060288446', 'SID951375253727'),
('+917073965481', 'SSF3494507'),
('+917321043713', 'SSF2959483'),
('+918467042272', 'SSF3754332'),
('+919950224535', 'SSF3414985'),
('+919352734770', 'SSF3376182'),
('+917250995380', 'SID951373715789'),
('+917470499942', 'SSF3561981'),
('+918696933877', 'SID951376122590'),
('+918955097559', 'SSF3138370'),
('+918209396434', 'SSF3338677'),
('+919521427800', 'SSF3026266'),
('+919734649949', 'SID951373840815'),
('+917068615808', 'SSF2350060'),
('+919645785578', 'SID951375704739'),
('+917857982414', 'SSF2388175'),
('+916510210518', 'SSF2319878'),
('+917665442051', 'SSF2674810'),
('+919669892468', 'SID951375063542'),
('+918103541266', 'SSF4223719'),
('+919238725805', 'SSF4626723'),
('+918815008426', 'SID951375735092'),
('+916202614125', 'SSF5183897'),
('+918840853148', 'SSF3032459'),
('+917605987400', 'SSF3581373'),
('+919244142195', 'SID951373885618'),
('+917033351665', 'SSF3439563'),
('+917765928615', 'SSF3599550'),
('+918319165544', 'SSF3997598'),
('+917067443815', 'SSF3447554'),
('+917295078490', 'SID951376136873'),
('+917710566126', 'SSF3249723'),
('+918294989933', 'SSF5986554'),
('+918094411477', 'SID951374304464'),
('+918264824476', 'SSF3050557'),
('+918839408337', 'SSF3784795'),
('+916307581623', 'SSF3551647'),
('+917755040066', 'SSF4377919'),
('+917080328363', 'SID951375106840'),
('+919162304519', 'SID951375742999'),
('+919508221891', 'SSF2493635'),
('+919166132243', 'SSF3553348'),
('+919009895347', 'SSF4420128'),
('+917764818770', 'SSF4419239'),
('+917900055071', 'SID951375962333'),
('+916235485698', 'SID951373903185'),
('+918799576042', 'SSF4156825'),
('+917481072470', 'SID951374547313'),
('+919973252762', 'SID951376092941'),
('+919006766942', 'SID951375157407'),
('+918103654238', 'SID951374697740'),
('+918975310124', 'SID951373721046'),
('+917999279400', 'SID951374252972'),
('+916262758859', 'SID951374377534'),
('+916267464626', 'SID951374742841'),
('+919341490634', 'SID951375464259'),
('+919773520012', 'SSF3714327'),
('+917477219219', 'CID040001693'),
('+919113365831', 'SSF5776530'),
('+917646012881', 'SID951374156344'),
('+919636116567', 'SID951375929964'),
('+919177925539', 'SID951376169920'),
('+919981787877', 'SID2125196758'),
('+919996334845', 'SID951376009501'),
('+919728981918', 'SID951375988501'),
('+918295886958', 'SID951376024026'),
('+918816898112', 'SID951375988534'),
('+919827852816', 'SSF2391818'),
('+919027793490', 'SSF5497458'),
('+919111849580', 'SSF3660501'),
('+916268618375', 'SSF3348585'),
('+916267834100', 'SID951372926211'),
('+919334296736', 'SID951375469271'),
('+916203928824', 'SID951374565733'),
('+918225841937', 'SID951373282167'),
('+919329286995', 'SID951374948638'),
('+916299430986', 'SID951373160318'),
('+917081264515', 'SSF3039015'),
('+919263022146', 'SID951372836197'),
('+919343616356', 'SID951375998989'),
('+917739734914', 'SSF2702372'),
('+917999754878', 'SID951372915758'),
('+919301644277', 'SID951373147039'),
('+919399444659', 'CID191605300'),
('+919695791023', 'SSF2587680'),
('+919263422794', 'SSF2368750'),
('+919241585090', 'SSF3003231'),
('+917737528899', 'SID951373868549'),
('+919617711301', 'SID2125702709'),
('+917247267906', 'SID2125245649'),
('+918349058209', 'SID951375806979'),
('+918825269767', 'SSF5485998'),
('+917257829227', 'SSF5348055'),
('+919023326932', 'SID951372948982'),
('+918890043848', 'SID951376089502'),
('+919165737839', 'SID951373784460'),
('+917806043749', 'SID951373631955'),
('+916267123676', 'SID2125363684'),
('+917803827824', 'SID951373349221'),
('+918296012379', 'SSF3048332'),
('+916264414242', 'SSF4234459'),
('+916263937582', 'SSF3308042'),
('+916201323044', 'SSF3793572'),
('+917848838545', 'SSF4040279'),
('+919305506006', 'SSF3840804'),
('+919709315131', 'SSF4218708'),
('+919341556192', 'SSF3621278'),
('+919770895009', 'SSF4683831'),
('+918789490351', 'SSF4454659'),
('+919241199815', 'SSF2971469'),
('+917631201054', 'SSF4952501'),
('+918815236152', 'SID951372930749'),
('+919934783408', 'SSF3753541'),
('+918769529476', 'SID951375130593'),
('+918815737093', 'SID951373959690'),
('+916264765692', 'SID951374786137'),
('+917073002899', 'SSF3227235'),
('+917320083016', 'SSF2817856'),
('+917489036349', 'SSF3680764'),
('+918128248960', 'SSF3178321'),
('+918310963492', 'SSF3892016'),
('+918003571212', 'SSF4681299'),
('+918305537926', 'SID951374211899'),
('+919304017355', 'SSF3734789'),
('+919006540525', 'SSF4132229'),
('+916377069995', 'SSF3856174'),
('+917841997504', 'SSF2868193'),
('+917000141400', 'SSF4450137'),
('+917737061015', 'SSF3169640'),
('+917041942530', 'SSF3183041'),
('+917725969635', 'SSF3031660'),
('+918108948122', 'SSF3116489'),
('+918009838763', 'SSF3067955'),
('+919580957582', 'SSF4197698'),
('+916388968200', 'SSF2678332'),
('+916200421112', 'SID951375572254'),
('+916378992863', 'SID951375509973'),
('+917091938838', 'SSF3408238'),
('+918319246476', 'SSF3974898'),
('+918434937711', 'SSF3497481'),
('+918817602181', 'SSF3655078'),
('+919108237225', 'SSF3537187'),
('+919309845822', 'SID951375213332'),
('+918873194018', 'SSF5905770'),
('+918235925486', 'SSF4722014'),
('+919110156757', 'SSF4716470'),
('+917611152695', 'SID2125526767'),
('+917878874889', 'SSF2997471'),
('+917004707240', 'SSF3197118'),
('+917746014687', 'SSF3455656'),
('+917282890878', 'SSF3698759'),
('+918871363994', 'SID951375218148'),
('+918319595087', 'SSF3459173'),
('+918235693252', 'SSF3408259'),
('+919166935278', 'SSF3247556'),
('+919693287219', 'SID951373130897'),
('+919983714581', 'SID951374464027'),
('+919462578627', 'SSF3528089'),
('+919508255929', 'SSF2339853'),
('+919691465744', 'SID951374200230'),
('+917300327032', 'SID951375933435'),
('+919644463734', 'SSF3592368'),
('+917357556146', 'SSF2543419'),
('+917280871725', 'SID951375009428'),
('+918435636540', 'SID951376092310'),
('+919114920927', 'SID951375244919'),
('+916284546464', 'SID951376117537'),
('+918887925648', 'SSF2852987'),
('+919982637960', 'SID951374618859'),
('+919509112737', 'SID951375466204'),
('+919098783535', 'SSF2907709'),
('+917023452047', 'SSF2666427'),
('+918949691240', 'SSF2499547'),
('+917404894606', 'SSF2663942'),
('+919996370831', 'SSF2678464'),
('+919278614865', 'SID951375066222'),
('+918696299670', 'SSF2690186'),
('+917485075623', 'SID951375035479'),
('+917464084427', 'SSF2786739'),
('+918092715165', 'SSF4039349'),
('+918604674408', 'SSF3116537'),
('+919263936637', 'SSF4330892'),
('+919942587301', 'SSF3552081'),
('+919608046892', 'SSF4131042'),
('+916299071947', 'SID2125564431'),
('+919939316298', 'SID951373095153'),
('+918107445510', 'SID951375299374'),
('+918409366039', 'SID951375298429'),
('+917061113957', 'SSF2777785'),
('+916205166313', 'SSF3014377'),
('+917007905202', 'SSF3280578'),
('+917722856729', 'SID951375689961'),
('+917542952762', 'SSF4018019'),
('+917870028587', 'SSF4219513'),
('+917870329514', 'SSF3688795'),
('+917654798294', 'SSF2847821'),
('+918794424921', 'SSF4362436'),
('+918529585127', 'SSF3823159'),
('+919244565008', 'SSF3529015'),
('+919508591391', 'SSF3865497'),
('+919608003410', 'SSF3328519'),
('+916207223861', 'SID951375079836'),
('+917850862613', 'SSF4078504'),
('+918619067961', 'SSF3834988'),
('+918209225549', 'SID951375098366'),
('+918502821659', 'SSF3701613'),
('+918423716498', 'SSF3104259'),
('+919955141016', 'SSF3414920'),
('+919630317170', 'SID2125107259'),
('+916267421992', 'SID951373951197'),
('+917067379708', 'SID951374716147'),
('+917563847486', 'SSF3608804'),
('+917300285152', 'SID951376017831'),
('+918144949052', 'SID951375293276'),
('+918643096485', 'SSF3758711'),
('+918955673358', 'SID951373758895'),
('+918815922634', 'SSF3651402'),
('+918982693214', 'SSF3245708'),
('+919835976108', 'SSF3602358'),
('+919660181653', 'SSF4053303'),
('+919631477705', 'SSF3533506'),
('+919934292650', 'SSF4437363'),
('+916367859683', 'SSF2931203'),
('+917828430764', 'SSF3466817'),
('+917851874994', 'SID951375319500'),
('+919023656603', 'SSF3620436'),
('+919351691652', 'SSF2878874'),
('+919721695056', 'SID951375551283'),
('+919784675887', 'SSF3812694'),
('+916350503767', 'SSF2595313'),
('+917340422065', 'SID951375466669'),
('+917359268509', 'SSF2845825'),
('+917742228086', 'SSF3250644'),
('+918905489168', 'SSF3025965'),
('+919113138882', 'SSF2768192'),
('+919929635528', 'SSF3248424'),
('+916207405368', 'SSF2920140'),
('+919691253780', 'SID951373158174'),
('+917082895176', 'SSF2588274'),
('+918959132888', 'SID951374026666'),
('+919244194950', 'SID951375056721'),
('+917722967192', 'CID044202244'),
('+919301968809', 'SID951375591817'),
('+918058340162', 'SSF2602836'),
('+916261635479', 'SSF3800740'),
('+916232784652', 'SSF3239800'),
('+917354709269', 'SID951373399030'),
('+919713477738', 'SSF3348057'),
('+919340624376', 'SSF3373966'),
('+919685051014', 'SSF3294371'),
('+918719845105', 'SID2125159824'),
('+919111206975', 'SID951373024991'),
('+919669886988', 'SID951375316763'),
('+916268248960', 'CID213602333'),
('+916267107231', 'SSF3356499'),
('+918521301535', 'SSF3309609'),
('+918827293870', 'SID951375216772'),
('+917067605733', 'CID206602186'),
('+919721217103', 'SSF4824272'),
('+917427812034', 'SID951376174971'),
('+919343528695', 'SID951375178577'),
('+916268401528', 'SID951373199551'),
('+919229344434', 'SID951375351810'),
('+918247256350', 'SSF5962109'),
('+916385866628', 'SID951374801330'),
('+917779850419', 'SSF5384065'),
('+919631141507', 'SSF5384036'),
('+918917891425', 'SSF4578910'),
('+917024001261', 'SID951374703426'),
('+916388728540', 'SSF5983490'),
('+919919380610', 'SID951373645171'),
('+918953917450', 'SSF5028286'),
('+917523078879', 'SID951372972765'),
('+919981249026', 'SSF4374095'),
('+917772904670', 'SSF3486896'),
('+917748063950', 'SID951375897453'),
('+917067683036', 'SSF2648436'),
('+917081751254', 'SID951375893854'),
('+918953567504', 'SID951374166950'),
('+918435774320', 'SID951374920615'),
('+918529111424', 'SID951374517419'),
('+917697131892', 'SID2125654917'),
('+919893280897', 'SID2125561741'),
('+918290599240', 'SID951375641116'),
('+919632589633', 'SID2125746802'),
('+919263216892', 'SID951373982109'),
('+917067771202', 'CID261400372'),
('+919691838293', 'SID951375282050'),
('+918770354671', 'CID093212416'),
('+918788253987', 'SID951375851787'),
('+919753918336', 'SSF4413200'),
('+919981632795', 'SSF4328241'),
('+918233313124', 'SID951374935881'),
('+918252928438', 'SSF3914407'),
('+918969016319', 'SID951374182062'),
('+919798377996', 'SID951374648756'),
('+919617364655', 'SID951375044608'),
('+917803897277', 'SID951374605273'),
('+918517081522', 'SSF5167335'),
('+917725874904', 'SID951374405820'),
('+916299015755', 'SSF3229318'),
('+917645815689', 'SSF5210519'),
('+917368909538', 'SSF3130069'),
('+918265022026', 'SSF3674994'),
('+919060764766', 'SSF3058435'),
('+919262507344', 'SSF4161322'),
('+917260071593', 'SID951373200442'),
('+918889720375', 'SSF4511753'),
('+918603383789', 'SSF4502340'),
('+919935277095', 'SSF4898080'),
('+917462832890', 'SSF4318451'),
('+919580451796', 'SSF5023744'),
('+916263198309', 'SID2125048874'),
('+919201144202', 'SID951372984361'),
('+916388507825', 'SID951374507960'),
('+919508948756', 'SID951375154064'),
('+917763979469', 'SID951376215683'),
('+917742400758', 'SSF2770669'),
('+916355575801', 'SSF3493337'),
('+917379069237', 'SSF3625469'),
('+917261056980', 'SSF3003147'),
('+919931704639', 'SSF3304542'),
('+919648425115', 'SSF3100253'),
('+919928652149', 'SSF4414501'),
('+919263991640', 'SSF4406471'),
('+919717434023', 'SSF3350391'),
('+919122350772', 'SSF2967891'),
('+916266241882', 'SSF3375632'),
('+917562971024', 'SSF3689531'),
('+917352276635', 'SSF3204628'),
('+918002236753', 'SSF2941621'),
('+919905268831', 'SID951372972146'),
('+919102191913', 'SID951375269359'),
('+919001644075', 'SSF3813236'),
('+919009668767', 'SID951375898361'),
('+917050443118', 'SSF3453564'),
('+919372485079', 'SID951373714309'),
('+919006440386', 'SSF3619566'),
('+919199058121', 'SSF3866366'),
('+919784029262', 'SID951376002537'),
('+916287032734', 'SSF2886528'),
('+917070554240', 'SID951374453034'),
('+919630289309', 'SID14053'),
('+919001219561', 'SSF3335913'),
('+919024360036', 'SSF3665410'),
('+919166507250', 'SSF3508744'),
('+916378768371', 'SID951375418654'),
('+917732995315', 'SSF2981485'),
('+919262616670', 'SSF3254741'),
('+919057937843', 'SSF3051875'),
('+918290319902', 'SSF2564068'),
('+918769690596', 'SSF3131717'),
('+918290776459', 'SSF2989807'),
('+919950907690', 'SSF2846603'),
('+917691820481', 'SSF2771084'),
('+919817374546', 'SSF2586459'),
('+919285382235', 'SSF2758667'),
('+917852039938', 'SSF2356119'),
('+917891357861', 'SID951375404924'),
('+919784039834', 'SSF2708665'),
('+919352367533', 'SID951375105469'),
('+916206028720', 'SID951375719517'),
('+918962481123', 'SID2125605653'),
('+916362747328', 'SSF4323192'),
('+916206133637', 'SSF3403914'),
('+919006230890', 'SSF3981536'),
('+919142035501', 'SID2125503759'),
('+919279896016', 'SSF4416285'),
('+919399570060', 'SSF4424726'),
('+919369537860', 'SID951374830501'),
('+917366099255', 'SID951374988238'),
('+919109936767', 'SID951375839585'),
('+919525630365', 'SID951375021916'),
('+918102411716', 'SSF2881864'),
('+919229141416', 'SID951376017623'),
('+919660271508', 'SID951376053544'),
('+916374953841', 'SSF4714497'),
('+916287588126', 'SSF3324625'),
('+916204805670', 'SSF3796292'),
('+917255813919', 'SSF3048328'),
('+917564972001', 'SSF4198990'),
('+918521611961', 'SSF3295928'),
('+918233813103', 'SID951374366425'),
('+918541896220', 'SSF3439093'),
('+918434166440', 'SSF3459671'),
('+919572677388', 'SSF3756367'),
('+919303101294', 'SSF4003024'),
('+919934040966', 'SSF4238017'),
('+919263754379', 'SSF4478799'),
('+918757778471', 'SSF4853209'),
('+916202566353', 'SID951375153796'),
('+919569453968', 'SID951374846516'),
('+917079160976', 'SSF2950284'),
('+917877458600', 'SSF3144053'),
('+919984172550', 'SSF4701897'),
('+918797205725', 'SSF4593105'),
('+916266529689', 'SSF3623798'),
('+918591293927', 'SID951374722858'),
('+918406019564', 'SID951375497028'),
('+919279072913', 'SSF3963597'),
('+919241642322', 'SSF2473383'),
('+916376984370', 'SSF3691638'),
('+916268325052', 'SSF3379762'),
('+917256871033', 'SID951375242951'),
('+918235217376', 'SID951375031533'),
('+918602492103', 'SSF3627357'),
('+918107397355', 'SSF3583817'),
('+919534379527', 'SSF3290927'),
('+919835994858', 'SID951374017563'),
('+919142397437', 'SSF3812424'),
('+918320348419', 'SSF4722204'),
('+919354456464', 'SID951375017462'),
('+918817264607', 'CID078106772'),
('+916375835650', 'SSF3863873'),
('+916202802137', 'SID951376019202'),
('+917415001603', 'SSF3493364'),
('+917091975568', 'SID951374968551'),
('+917803864963', 'SSF3509351'),
('+918889764219', 'SID951373800989'),
('+919343085295', 'SSF3498335'),
('+919358983940', 'SSF3747401'),
('+919905461778', 'SSF3468435'),
('+919534257687', 'SID951375312568'),
('+919887291864', 'SSF3628336'),
('+918769008998', 'SID951375089630'),
('+919752516468', 'SID951374990266'),
('+916266394568', 'SSF3211195'),
('+917424995212', 'SID951375409743'),
('+919106186049', 'SSF2489934'),
('+919991943016', 'SSF2641141'),
('+919660507886', 'SSF2953743'),
('+918815997752', 'SSF3106554'),
('+918815806739', 'CID081112167'),
('+916265755792', 'SID951375109042'),
('+919244067868', 'SID951374600472'),
('+917498723958', 'SSF3566691'),
('+919956827027', 'SSF3970246'),
('+919244172352', 'SSF4354117'),
('+919981308791', 'SSF4517771'),
('+916306558969', 'SID951374135376'),
('+917879979337', 'SSF4532063'),
('+919060342546', 'SID951373903911'),
('+919628488467', 'SSF6167907'),
('+917477045853', 'SID951374525598'),
('+916260012823', 'SSF3725424'),
('+918439129963', 'SSF6087516'),
('+917392844179', 'SID951375736247'),
('+917870762118', 'SID951375954901'),
('+919164973443', 'SID951374357909'),
('+919109469460', 'SID951374250565'),
('+919587992765', 'SID951375008294'),
('+919835469500', 'SID951373063069'),
('+919685437968', 'SSF3901632'),
('+918770157631', 'SID951375861929'),
('+918052476213', 'SSF4856016'),
('+918252615479', 'SSF3278989'),
('+919450630558', 'SSF4668333'),
('+917079469029', 'SSF2724929'),
('+917739433403', 'SSF3343474'),
('+919955237181', 'SSF4302770'),
('+919279418228', 'SID951375000285'),
('+918294786965', 'CID204503123'),
('+919131033790', 'SSF3324172'),
('+919235678932', 'SSF5424916'),
('+919755131130', 'SSF3253816'),
('+917440451825', 'SID951375317201'),
('+916260902192', 'SSF4309216'),
('+919669089974', 'SSF3229731'),
('+919415838961', 'SSF3084160'),
('+917903712087', 'SSF3166098'),
('+917489661156', 'CID219301541'),
('+919259829107', 'SSF5884136'),
('+917258033078', 'SSF5009444'),
('+916201256465', 'SSF5507155'),
('+918209732410', 'SID951373814505'),
('+917033059017', 'SSF2436093'),
('+919234227280', 'SID951373875013'),
('+916268009022', 'SID951375415130'),
('+919672557338', 'SSF2545179'),
('+919664077321', 'SID951374637709'),
('+919327871497', 'SSF3096547'),
('+919784182291', 'SID951375892501'),
('+916260595163', 'SSF4003156'),
('+918817682787', 'SID951375367118'),
('+919516918671', 'CID191401124'),
('+916283547863', 'SID951376116545'),
('+918770690487', 'SID951374706850'),
('+917987286541', 'SID951375152475'),
('+916268411189', 'SSF3713341'),
('+917058505512', 'SSF2886126'),
('+919918545843', 'SSF4343601'),
('+916206269770', 'SID951374491474'),
('+917667150392', 'SID951375534699'),
('+919302414955', 'SID951374904671'),
('+919572920339', 'SID951374701389'),
('+917050778379', 'SSF2934228'),
('+916207450625', 'SID951373794317'),
('+917988491685', 'SSF3968755'),
('+917070411842', 'SSF4562649'),
('+917803832272', 'SSF4459300'),
('+918780718017', 'SSF3281556'),
('+919234185064', 'SSF3220065'),
('+919263047649', 'SSF3951242'),
('+917067132782', 'SID2125527062'),
('+918120442120', 'CID041600715'),
('+916266686597', 'SID951374116220'),
('+919576974079', 'SSF2730443'),
('+919060269400', 'SID951374000393'),
('+916367954911', 'SID951375772285'),
('+919993249205', 'SID951375730750'),
('+918207787182', 'SID951375977437'),
('+917369802600', 'SSF2390355'),
('+918817217805', 'SSF4292389'),
('+918084652112', 'SSF3686589'),
('+918528231990', 'SSF4171169'),
('+917651924873', 'SSF4639758'),
('+917033931056', 'SID951373968719'),
('+917050329789', 'SID2125684639'),
('+916261896127', 'SSF4315840'),
('+917644892437', 'SSF4105672'),
('+919102386521', 'SSF3981582'),
('+919509485483', 'SID951374205921'),
('+919102111243', 'SID951376037479'),
('+919234456067', 'SID951375658865'),
('+918882049287', 'SSF4584226'),
('+916267987541', 'SSF3758135'),
('+916367585681', 'SSF3840001'),
('+917033527218', 'SSF2730377'),
('+917493975519', 'SID951374516760'),
('+918619632639', 'SSF3489511'),
('+919065053550', 'SSF3756733'),
('+916266606411', 'SSF3258460'),
('+917761867080', 'SSF3103668'),
('+918690232680', 'SSF3641460'),
('+918409477156', 'SSF3443170'),
('+918603410773', 'SSF3362021'),
('+918239244744', 'SID951375202706'),
('+918823914540', 'SSF3609908'),
('+918769558864', 'SSF3665188'),
('+918969518235', 'SSF4697121'),
('+917354334429', 'SSF3537885'),
('+918025147896', 'SSF2334687'),
('+918625658325', 'SID951375800886'),
('+918529485772', 'SID951375881732'),
('+918233839247', 'SSF3427896'),
('+919783305158', 'SID951375694437'),
('+916346494946', 'SID951375899647'),
('+917805093395', 'SSF3212263'),
('+919464548464', 'SID951375119181'),
('+916375345541', 'SSF2478301'),
('+918769339632', 'SSF2708666'),
('+918769128365', 'SID951375951367'),
('+919521485824', 'SID951374775265'),
('+917348028949', 'SID951376180409'),
('+919610865092', 'SSF2479671'),
('+919079834274', 'SSF2554875'),
('+916207219600', 'SID2125070634'),
('+919724249402', 'SID951375111475'),
('+919135709920', 'SID951374835447'),
('+919343836070', 'SID951373953980'),
('+919263652816', 'SSF2886125'),
('+916207491604', 'SSF3784862'),
('+916396379112', 'SSF4583837'),
('+917645018695', 'SSF4521634'),
('+917717753831', 'SSF4439850'),
('+917079695923', 'SSF4097148'),
('+917488663483', 'SSF3066501'),
('+917489718027', 'SSF3080943'),
('+918003704618', 'SSF2600571'),
('+918839769877', 'SSF4546839'),
('+919102845764', 'SSF4220480'),
('+919065362443', 'SSF3276574'),
('+917563905167', 'SID951374763890'),
('+919572633970', 'SID951374191829'),
('+919142642423', 'SID951375761624'),
('+917209812860', 'SID951375442008'),
('+918051987593', 'SID951375991845'),
('+917876088133', 'SSF3583596'),
('+917295079255', 'SSF3591916'),
('+917352214418', 'SSF3651701'),
('+918639874813', 'SSF2615054'),
('+918955549296', 'SSF4315596'),
('+919661990465', 'SID951374708556'),
('+919835221673', 'SSF4097477'),
('+919279647946', 'SSF3104093'),
('+919148552311', 'SSF4410874'),
('+919343648804', 'SSF4287659'),
('+918103917160', 'SID951373193185'),
('+919339915530', 'SSF2635165'),
('+916376242649', 'SSF4157192'),
('+917415295713', 'SID951373748743'),
('+919905124451', 'SSF3497190'),
('+917482028751', 'SSF3344779'),
('+917024330760', 'SID951372931891'),
('+918602812178', 'SSF3219482'),
('+918797785754', 'SSF2746926'),
('+919256592182', 'SSF3672875'),
('+919358085520', 'SSF4152262'),
('+919305935462', 'SID951374746002'),
('+919339104625', 'SSF2451473'),
('+916200937922', 'SID951375536671'),
('+916200634613', 'SID951374566381'),
('+917878033294', 'SSF3913287'),
('+917976914050', 'SSF3795730'),
('+917987140970', 'SSF3708560'),
('+918824939601', 'SSF3335412'),
('+918003280605', 'SID951375984991'),
('+919279266493', 'SID951374538083'),
('+919508008422', 'SID951373941608'),
('+919334613723', 'SSF5110237'),
('+919026955688', 'SSF4446625'),
('+916378288776', 'SID951373760705'),
('+918709352575', 'SSF3849468'),
('+918086853995', 'SID951374495770'),
('+919680195717', 'SID951375775142'),
('+919082497740', 'SID951373079082'),
('+919556047742', 'SSF3599620'),
('+916595995949', 'SID2125266953'),
('+918233691466', 'SSF3498743'),
('+916378727604', 'SSF3248037'),
('+918434999529', 'SSF2886562'),
('+917258654756', 'SID951373951399'),
('+917297055284', 'SSF2464165'),
('+917804932735', 'SID951372982679'),
('+919179359194', 'SID951376096848'),
('+917247583403', 'SID951372874894'),
('+919359960171', 'SSF3141050'),
('+917850915202', 'SSF2678911'),
('+919571118301', 'SSF2596903'),
('+919797645897', 'SSF2844677'),
('+916713823155', 'SSF2691012'),
('+917846465576', 'SID951374516931'),
('+919034282813', 'SSF2669244'),
('+919675464946', 'SID951375555723'),
('+919340794285', 'SID951373732209'),
('+916265866742', 'SID951376163536'),
('+919340518360', 'SID951376006484'),
('+919294592771', 'SSF2906061'),
('+917974514329', 'SSF4507974'),
('+917974614776', 'SSF3618136'),
('+918839146366', 'SSF3840317'),
('+919752346367', 'SSF3190144'),
('+919753133641', 'SSF3316483'),
('+919324629127', 'SID951373608556'),
('+919198720598', 'SSF5046952'),
('+917571876155', 'SSF3471857'),
('+919575206074', 'SID2125618700'),
('+918959129430', 'SID2125715356'),
('+919455085975', 'SSF5917574'),
('+919770743253', 'SID951374358273'),
('+919764688676', 'SID951376045249'),
('+919608499320', 'SID951374781524'),
('+916267023264', 'SID951374550046'),
('+919238619540', 'SSF3522535'),
('+917869920615', 'SSF4398812'),
('+919257997576', 'SSF3634543'),
('+916266688783', 'SSF3767030'),
('+919303134229', 'SSF3525281'),
('+919641182073', 'SSF5070415'),
('+917067035972', 'CID213103589'),
('+918176914516', 'SSF5703199'),
('+917481015002', 'SSF2342811'),
('+919630335953', 'SID951373590950'),
('+918578975288', 'SID951372990112'),
('+917695913765', 'SID951373883834'),
('+919302183878', 'SID2125519271'),
('+916209774431', 'SID951375690319'),
('+918228896004', 'SID951375678858'),
('+918789561904', 'SID951375537050'),
('+919696042410', 'SSF4103382'),
('+919521778896', 'SSF5758168'),
('+919977210732', 'SSF2327291'),
('+919234305798', 'SID951375956700'),
('+917970797370', 'SSF6040430'),
('+917878752388', 'SSF4866030'),
('+919111305934', 'SID2125384424'),
('+917067796190', 'SID951372920160'),
('+919617231322', 'CID129801948'),
('+917247047793', 'SID2125614011'),
('+918709948382', 'SID951373200222'),
('+916375658542', 'SID951376013505'),
('+918959048338', 'CID053612637'),
('+918540032004', 'SSF5933490'),
('+918127266899', 'SID951374635181'),
('+919572730764', 'SID951374787016'),
('+916264656976', 'SSF4275739'),
('+917970089825', 'SSF2492481'),
('+919301376075', 'SID951373549718'),
('+918319603950', 'SID951372829417'),
('+916263138397', 'SID2125652928'),
('+916268207812', 'CID213601541'),
('+919584348952', 'SID951375318121'),
('+918517549466', 'CID093201548'),
('+918756709337', 'SSF5118958'),
('+918085369945', 'CID081013778'),
('+919770067994', 'SID2125361272'),
('+917024961753', 'SSF4274532'),
('+919956378909', 'SSF4843910'),
('+919981938415', 'SID951375103640'),
('+919534151279', 'SID951373071496'),
('+918839513570', 'SID951375263262'),
('+918602559118', 'CID061105002'),
('+916266163367', 'SSF3055925'),
('+919617804010', 'CID128801584'),
('+919685401293', 'SID951372940857'),
('+917488358809', 'SID951375795821'),
('+917020717905', 'SID951375532558'),
('+919162950447', 'SID951375062225'),
('+916205934842', 'SSF2757190'),
('+919430796551', 'SSF2670251'),
('+917634940037', 'SSF4391926'),
('+917643037188', 'SSF4300835'),
('+917439342436', 'SSF3348655'),
('+918569928594', 'SSF2983697'),
('+918084199564', 'SSF3128558'),
('+918815421119', 'SID951375357912'),
('+918839954278', 'SSF4674764'),
('+918319884764', 'SSF3930738'),
('+919142053100', 'SSF4402321'),
('+919060946113', 'SSF3229351'),
('+919771863729', 'SSF3776626'),
('+918881286970', 'SSF2932062'),
('+918103684405', 'SSF4137554'),
('+919301281695', 'SSF4326109'),
('+919905698439', 'SSF4462750'),
('+919026268028', 'SSF4950937'),
('+916266698327', 'SSF4348961'),
('+917061787349', 'SSF3639770'),
('+917710932653', 'SSF3620351'),
('+917587852060', 'SSF4375959'),
('+919303348553', 'SSF4445758'),
('+919171777837', 'SSF4287395'),
('+917081852053', 'SSF4696106'),
('+917999030788', 'SSF4391909'),
('+919691587129', 'SSF2402665'),
('+917340201731', 'SID951375941514'),
('+917225913863', 'SSF3839436'),
('+917999346381', 'SSF3488141'),
('+918003574229', 'SSF3638162'),
('+918819904380', 'SSF3789685'),
('+918290813104', 'SSF3259552'),
('+919329712049', 'SID951375585283'),
('+919301186749', 'SSF3851313'),
('+919328455037', 'SID951375942741'),
('+916378509377', 'SSF3939210'),
('+916367019611', 'SSF3243752'),
('+916265276124', 'SSF3603838'),
('+917067127138', 'SSF3348110'),
('+918239380552', 'SSF3531908'),
('+919329372447', 'SSF3757039'),
('+919216775011', 'SID951375386987'),
('+919214588835', 'SSF3628288'),
('+917481025131', 'SSF3375644'),
('+918435732601', 'SSF3455512'),
('+919097817823', 'SSF3087300'),
('+916287682146', 'SSF3342215'),
('+918770506978', 'SSF3168837'),
('+919680957838', 'SID951375306189'),
('+919415029838', 'SSF3544419'),
('+917735711041', 'SSF3211862'),
('+917414868080', 'SSF2572724'),
('+917828664279', 'SSF3144094'),
('+919328076832', 'SSF2679484'),
('+918955728760', 'SSF2900623'),
('+918398934693', 'SSF2719362'),
('+919784812472', 'SID951375709881'),
('+919786486646', 'SID951375198644'),
('+919897678797', 'SID951375433011'),
('+917419303100', 'SSF2555739'),
('+917520924951', 'SSF2381128'),
('+918103891047', 'SSF2851310'),
('+917991947611', 'SSF3493968'),
('+917091910971', 'SSF4463132'),
('+917349874340', 'SSF2697521'),
('+917388019812', 'SSF3074973'),
('+917805991937', 'SSF3438905'),
('+918349218928', 'SSF4530375'),
('+919238992805', 'SSF3273308'),
('+919798674939', 'SSF4574648'),
('+919155687525', 'SSF3367311'),
('+919263993451', 'CID211201981'),
('+916264092554', 'SID951374073458'),
('+917739920306', 'SID951374483068'),
('+917294813379', 'SID951376197162'),
('+917763893629', 'SSF4176438'),
('+917061060016', 'SSF3182850'),
('+918092733191', 'SSF4322197'),
('+918651143122', 'SSF3232088'),
('+919153317679', 'SID951375723771'),
('+919661080438', 'SSF3653116'),
('+919241225209', 'SSF3867217'),
('+917317632641', 'SSF5203359'),
('+918795107487', 'SSF4649764'),
('+917970925439', 'SID951374384020'),
('+919165641224', 'SID951374465939'),
('+917033248026', 'SID951375032765'),
('+917261852067', 'SSF2967754'),
('+917247201312', 'SSF2443822'),
('+917782035755', 'SID951375875652'),
('+919263494964', 'SSF4095226'),
('+919334054369', 'SSF2791683'),
('+918603204426', 'SSF4830471'),
('+917587007273', 'SID951374562072'),
('+918817376120', 'SID951376033416'),
('+918209645802', 'SSF3473109'),
('+918962445144', 'SSF2513653'),
('+919340379172', 'SSF3310726'),
('+919507714123', 'SSF3778523'),
('+916268609724', 'SSF3704574'),
('+916302168754', 'SSF3183564'),
('+917294979592', 'SID951372789198'),
('+918303666432', 'SSF3317062'),
('+919340118593', 'SSF3502850'),
('+919162507584', 'SID951375067629'),
('+919549702439', 'SSF3593281'),
('+917023710134', 'SSF2550568'),
('+919358630075', 'SSF2509068'),
('+918585085785', 'SSF3014672'),
('+919523511335', 'SID951375768841'),
('+919358036978', 'SID951375998174'),
('+919306833053', 'SSF2639010'),
('+919977039063', 'SID951373193962'),
('+917909481898', 'SSF3282307'),
('+917007799841', 'SSF3756155'),
('+918318640460', 'SSF3284440'),
('+918320794630', 'SSF3427269'),
('+919302861213', 'SSF3225540'),
('+918815369882', 'SSF3247557'),
('+918252453142', 'SSF5147513'),
('+917250655650', 'SID951372871020'),
('+919651207252', 'SSF5353729'),
('+917296042757', 'SSF4869347'),
('+919301621019', 'SSF3177824'),
('+916268129732', 'SID101298'),
('+919893721407', 'CID061201402'),
('+917772947967', 'SID951374238411'),
('+917417324501', 'SSF5163568'),
('+919687345985', 'SID951373024760'),
('+919708817673', 'SID951375387197'),
('+916207004732', 'SSF3518683'),
('+919174509659', 'SID951375680679'),
('+918720063816', 'SSF5564775'),
('+918409561876', 'SSF3351740'),
('+917806084251', 'SID951374956947'),
('+918804769237', 'SID951375935670'),
('+918770935054', 'CID129108187'),
('+919302662941', 'SSF4337795'),
('+919772403859', 'SID951375884850'),
('+918877829115', 'SID951374421481'),
('+919340159997', 'SID951374386412'),
('+919244770624', 'SID951376143643'),
('+918815703124', 'CID205802915'),
('+919667656797', 'SID951374988754'),
('+916386029419', 'SSF2466013'),
('+919399831868', 'SID2125296656'),
('+916261633061', 'SID71510'),
('+918435098589', 'SSF2752177'),
('+918839806926', 'SSF2992592'),
('+917988880462', 'SSF3095822'),
('+919199493346', 'SID951374348387'),
('+918817429767', 'SID951374877577'),
('+918511870986', 'SSF5740302'),
('+917983333963', 'SID951375214136'),
('+919238463828', 'SSF3683572'),
('+919669494190', 'SID951373624058'),
('+918222988295', 'SSF2670358'),
('+918120733915', 'SID951374494650'),
('+919893810379', 'SID2125453127'),
('+916201775488', 'SID951375810575'),
('+919926870215', 'SID951374740033'),
('+919889901402', 'SSF3310396'),
('+916260583014', 'SID2125245397'),
('+919926389391', 'SSF3345817'),
('+919031409795', 'SSF5471628'),
('+918518936563', 'SID2125261211'),
('+919669030384', 'CID072006135'),
('+917479956722', 'SSF3771540'),
('+917061291321', 'SID951374798958'),
('+918839355436', 'SID951374578194'),
('+917294019252', 'SID2125775443'),
('+916269805275', 'SID2125067072'),
('+918961370951', 'SID951375266747'),
('+919928777689', 'SID951375929013'),
('+916306643315', 'SSF2372823'),
('+917392063868', 'SSF2641511'),
('+919279047744', 'CID951376209322'),
('+919693995147', 'SSF2616408'),
('+916207662435', 'SSF3074805'),
('+916201781374', 'SSF4099866'),
('+916203037431', 'SSF4217383'),
('+917764816986', 'SSF3626108'),
('+917974676214', 'SSF3941945'),
('+917205666248', 'SSF4211481'),
('+918809949116', 'SSF3632103'),
('+919471360869', 'SSF3764772'),
('+919131281343', 'SSF3666179'),
('+919234906252', 'SSF3422416'),
('+917004905331', 'CID211201976'),
('+919026492844', 'SSF4534775'),
('+917546800684', 'SSF4775278'),
('+918797601452', 'SSF4579622'),
('+919031965981', 'SSF4467201'),
('+917016157788', 'SID951374510295'),
('+917665846096', 'SID951374542948'),
('+917318266862', 'SSF3095443'),
('+917859072060', 'SSF4561271'),
('+917666290782', 'SID951375348752'),
('+918542013824', 'SSF3729304'),
('+918434311812', 'SSF3093002'),
('+918103511389', 'SID951374149400'),
('+919801324780', 'SSF4102007'),
('+919343998119', 'SSF5102704'),
('+919340604177', 'SSF4043074'),
('+917979994627', 'SID951373304655'),
('+918103732377', 'SID951372828339'),
('+916200147202', 'SSF4320676'),
('+917804861280', 'SID951374961566'),
('+918959528681', 'SID951375909868'),
('+919576503094', 'SSF3601600'),
('+919303449702', 'SSF3280260'),
('+919648697473', 'SSF4633677'),
('+916268999463', 'SID951372961641'),
('+917737269009', 'SSF3742117'),
('+917667400510', 'SSF3344218'),
('+919680426699', 'SSF3248378'),
('+917726004071', 'SID951375638620'),
('+917541023451', 'SSF3590231'),
('+917375031692', 'SSF3686155'),
('+918982279294', 'SSF3474497'),
('+918949567942', 'SSF2728782'),
('+918302000860', 'SID951374795080'),
('+919610464993', 'SSF3813379'),
('+919106467121', 'SSF4209724'),
('+919343271956', 'SSF3671096'),
('+919887572347', 'SSF3607841'),
('+919983021286', 'SSF3686262'),
('+919399557518', 'SSF3577049'),
('+917600925956', 'SID951374853304'),
('+918757975213', 'SSF3449723'),
('+918935899281', 'SSF3253903'),
('+918901717637', 'SSF2943703'),
('+918905147655', 'SSF2510544'),
('+919610229118', 'SSF2832087'),
('+919772195240', 'SSF2683886'),
('+917587808641', 'SID951374620569'),
('+917783803791', 'SID951374874022'),
('+919939410915', 'SID951374899038'),
('+916267519811', 'SSF3757983'),
('+917987524159', 'SSF4558129'),
('+918075813062', 'SSF4928006'),
('+918252783587', 'SSF4216265'),
('+919153190709', 'SSF3363678'),
('+918540065418', 'SID951375609537'),
('+918539919168', 'SSF2780616'),
('+919785768420', 'SSF2599587'),
('+916390015566', 'SSF3157624'),
('+916203439315', 'SSF3369128'),
('+917858996507', 'SSF3842805'),
('+917488531869', 'SSF3645354'),
('+918827346103', 'SSF3795980'),
('+918173806077', 'SSF4113154'),
('+918757016128', 'SSF4250658'),
('+919131832405', 'SSF3296543'),
('+919120025592', 'SSF3682402'),
('+919162707270', 'SSF2966736'),
('+919572512784', 'SSF3008669'),
('+919931912200', 'SSF4683704'),
('+919041585315', 'SSF4512080'),
('+919238103299', 'SSF3785304'),
('+918920953287', 'SSF4944822'),
('+916263113899', 'SSF4082181'),
('+919950256646', 'SSF3777983'),
('+916205794362', 'SID951373937389'),
('+918797789687', 'SID951374561450'),
('+919918843012', 'SSF4875914'),
('+918853426522', 'SSF5157604'),
('+917318262292', 'SSF3295913'),
('+917879269021', 'SSF3726774'),
('+917632069732', 'SID951373656275'),
('+918953090278', 'SID951375453925'),
('+917489984607', 'SSF2824972'),
('+917488198676', 'SSF3590146'),
('+918290287058', 'SSF3394152'),
('+918741981492', 'SSF3671995'),
('+919672329114', 'SSF3458733'),
('+919694326513', 'SSF3316508'),
('+919119362188', 'SSF2819081'),
('+917410835113', 'SSF3675857'),
('+918003103942', 'SSF3222279'),
('+919119229146', 'SID951375002737'),
('+919320615535', 'SID951374151198'),
('+919199675612', 'SID951375263577'),
('+919636253152', 'SSF3285430'),
('+916375386642', 'SSF3074662'),
('+918000155985', 'SSF3465062'),
('+919633215357', 'SID951373657703'),
('+917073449953', 'SSF3020163'),
('+919306857658', 'SSF2639011'),
('+917869906107', 'CID135706733'),
('+919755542699', 'SID2125588311'),
('+919691494167', 'CID176206631'),
('+919109059467', 'SID951373706600'),
('+919301403513', 'SID951375812165'),
('+918223819426', 'SID951376100668'),
('+916387703288', 'SSF3124931'),
('+916375356961', 'SSF3959709'),
('+916268541967', 'SSF3097300'),
('+918461855452', 'SSF3315888'),
('+918319155468', 'SSF4401443'),
('+919644302720', 'SSF3596221'),
('+918249976988', 'SID951375836823'),
('+916207405254', 'SID951374837708'),
('+917073704894', 'SID951374652621'),
('+919231979538', 'SID951375596908'),
('+919521354883', 'SID951375161766'),
('+916350056708', 'SID951375428699'),
('+917207658614', 'SSF2573636'),
('+918875835498', 'SID951374678731'),
('+918235482570', 'SSF3689298'),
('+919329873927', 'SID110995'),
('+918825120192', 'SSF2740119'),
('+919325846488', 'SID951374781659'),
('+919006268167', 'SSF4010647'),
('+919631047036', 'SSF2453818'),
('+918875679023', 'SID951375210903'),
('+918109519861', 'SSF6019771'),
('+919285423676', 'SSF3043596'),
('+918982038886', 'SID951374418738'),
('+919044698693', 'SSF3859540'),
('+916864979798', 'SID951374587404'),
('+916366196511', 'SID951372859067'),
('+918319395654', 'SID951374462048'),
('+919630671491', 'CID087110436'),
('+918103338280', 'SID951374356930'),
('+917828254184', 'SSF4051892'),
('+919918291856', 'SID951376149032'),
('+918989409994', 'SID951374779873'),
('+919303519686', 'SSF2910658'),
('+918757646494', 'SID951375334856'),
('+918815042007', 'CID205801995'),
('+919350958888', 'SID951373804037'),
('+917209029763', 'SID951375378854'),
('+919006091482', 'SID951374572824'),
('+916287139615', 'SSF4615136'),
('+917634848908', 'SSF3060552'),
('+917367809076', 'SSF3327494'),
('+918839026578', 'SSF4478481'),
('+918577929819', 'SSF4396894'),
('+918942980703', 'SSF3174549'),
('+918674871268', 'SSF2946135'),
('+919199462141', 'SSF4551997'),
('+919525080207', 'SSF3659468'),
('+919753001125', 'CID261400003'),
('+917566250175', 'SSF3324321'),
('+919770047316', 'SSF4783609'),
('+917482855289', 'SSF5153697'),
('+917061069053', 'SSF4858559'),
('+917524013601', 'SSF4955471'),
('+917667291545', 'SSF2747446'),
('+918120254594', 'SSF2505219'),
('+919801914435', 'SID951376173693'),
('+918889747606', 'SSF4332998'),
('+918305384107', 'SSF3955628'),
('+919065694735', 'SSF4605732'),
('+917317886997', 'SSF4712778'),
('+918602285350', 'SID951372986080'),
('+919770318337', 'CID084609582'),
('+918460240824', 'SID951375472417'),
('+919754916883', 'SID951374675697'),
('+919649826606', 'SID951375516225'),
('+919155067775', 'SSF2409380'),
('+919118150625', 'SSF4859865'),
('+916263235365', 'SID951374796396'),
('+916268388746', 'SSF3925397'),
('+916232867800', 'SSF4059443'),
('+917304608762', 'SID951374493612'),
('+917224010143', 'SSF3337311'),
('+917804989965', 'SID951374916321'),
('+918878219480', 'SSF4086682'),
('+918305367463', 'SSF3849445'),
('+918306256813', 'SID951375037846'),
('+918824251717', 'SSF3449318'),
('+918554869875', 'SID951376229969'),
('+918789389265', 'SSF4793455'),
('+916267247404', 'SSF4120791'),
('+916266672527', 'SSF3258426'),
('+917737063764', 'SSF3574984'),
('+918302468670', 'SSF3797791'),
('+918290787360', 'SSF3703458'),
('+918000356623', 'SSF3653448'),
('+918209875674', 'SSF3626535'),
('+918688586868', 'SID951373658435'),
('+918370061987', 'SSF3807226'),
('+919770374225', 'SSF4252475'),
('+917870046734', 'SSF4548941'),
('+917644086812', 'SSF3554069'),
('+917070087891', 'SSF3554047'),
('+919905155386', 'SID2125188450'),
('+919316574375', 'SSF2428308'),
('+917697999338', 'SSF3197436'),
('+918769207433', 'SID951374556672'),
('+919668812358', 'CID219401783'),
('+917742938617', 'SID951374703469'),
('+917665580653', 'SID951376010050'),
('+919119352770', 'SSF3380488'),
('+919784196009', 'SSF2992530'),
('+919738247786', 'SSF2657603'),
('+917250456921', 'CID204503818'),
('+916367763922', 'SID951374561228'),
('+919340580640', 'SSF2377567'),
('+916268848665', 'SSF4832490'),
('+917089275397', 'SSF4923006'),
('+916299480921', 'SID951374947380'),
('+916200217843', 'SID951373315420'),
('+918269939895', 'SID951374200337'),
('+917091983218', 'SID951374803044'),
('+919572864406', 'SID951374658755'),
('+919455524694', 'SID951374726530'),
('+919631671557', 'SID951375166402'),
('+918948308197', 'SID951376227090'),
('+916268831473', 'SSF3472891'),
('+917014001581', 'SSF3776345'),
('+917247318119', 'SSF4056007'),
('+917567019122', 'SSF3446538'),
('+917545970144', 'SSF4037382'),
('+917870876409', 'SSF4129720'),
('+918767279758', 'SSF4539700'),
('+918271895221', 'SSF4525895'),
('+918168377802', 'SSF4037423'),
('+919546058284', 'SSF3986506'),
('+919462943200', 'SSF4610377'),
('+919334825184', 'SSF3203416'),
('+919264232202', 'SID951375625626'),
('+916264596244', 'SID951373983027'),
('+917723951039', 'SSF3366182'),
('+916267811084', 'SID2125588556'),
('+919617919908', 'SID951374090191'),
('+919523489125', 'SSF4452914'),
('+919982681167', 'SSF4195852'),
('+919525810827', 'SSF4773082'),
('+917982531142', 'SSF4996977'),
('+916267283788', 'SID2125612906'),
('+916260577113', 'SID951374921292'),
('+917050922015', 'SID951373718101'),
('+917766956084', 'SSF4247477'),
('+917796404061', 'SSF3829470'),
('+918290553462', 'SID951373889407'),
('+919955191845', 'SSF3612300'),
('+919660636393', 'SSF4101967'),
('+919301834274', 'SSF3836135'),
('+919630162882', 'SSF4080126'),
('+917000454180', 'SSF3280238'),
('+917724898459', 'SSF3980595'),
('+918271340682', 'SID951374622512'),
('+918290284159', 'SSF3703394'),
('+918544123668', 'SID951375984526'),
('+918003644545', 'SSF3917105'),
('+918340363211', 'SSF3626543'),
('+918504910256', 'SSF3701966'),
('+919929594814', 'SID951375361447'),
('+919024145272', 'SSF3631254'),
('+916393363836', 'SID2125718086'),
('+917014232690', 'SSF3460220'),
('+917383093980', 'SID951374788038'),
('+917999496977', 'SID951373479013'),
('+918511983565', 'SID951375525341'),
('+918690655428', 'SID951373759274'),
('+918441075620', 'SSF3141378'),
('+918850530478', 'SSF3207330'),
('+919610712662', 'SID951374825521'),
('+919310644752', 'SID951373113628'),
('+919009113937', 'SSF3057534'),
('+919575840599', 'SID951374174345'),
('+918905825408', 'SSF3456540'),
('+917691899575', 'SSF2997473'),
('+919406049193', 'SID951374079515'),
('+919799658004', 'SSF2994632'),
('+916200851696', 'SID951375986768'),
('+919767878513', 'SID951372896366'),
('+919755746155', 'CID061213257'),
('+916269495730', 'SID951372971776'),
('+916265851527', 'SID951376100643'),
('+917828856836', 'SSF2995439'),
('+918120717205', 'SSF3504519'),
('+919039765053', 'SSF3284574'),
('+919755200256', 'SSF4195012'),
('+919216199075', 'SSF3766982'),
('+919244985101', 'SSF4777943'),
('+919770233743', 'SSF4782936'),
('+917380702507', 'SSF5416085'),
('+916267706180', 'SID951375151248'),
('+916268285634', 'SSF3495107'),
('+918840940038', 'SSF4445808'),
('+919494664644', 'SID951374327214'),
('+917880028870', 'SSF4451176'),
('+918827039366', 'SID2125612123'),
('+919244381232', 'SID2125228592'),
('+919783507931', 'SSF4247946'),
('+919157655812', 'SSF3654234'),
('+917667695629', 'SSF4156616'),
('+919608740582', 'SSF4616535'),
('+919174988044', 'SID951373724497'),
('+917724847453', 'SID951373595652'),
('+919568475556', 'SID951374145510'),
('+918949432509', 'SID951375404864'),
('+919755472326', 'SSF4386488'),
('+916264205823', 'SID951373361240'),
('+919879247667', 'SSF3404919'),
('+918103132843', 'CID080903262'),
('+919834335362', 'SID951373868309'),
('+919955885204', 'SID951374566106'),
('+919630960874', 'SID951374439352'),
('+919509839182', 'SSF2423926'),
('+918871928663', 'SID2125728637'),
('+917549010494', 'SID951375597098'),
('+919163467594', 'SSF4067202'),
('+919691937709', 'SID951374492885'),
('+919155483548', 'SSF3627782'),
('+919022492044', 'SID951374795519'),
('+919340494781', 'SID951374555727'),
('+918817245463', 'SID951373317549'),
('+919771331231', 'SSF3581840'),
('+919009242058', 'SSF3745898'),
('+917851039394', 'SID951375450988'),
('+919022185916', 'CID140609071'),
('+918540830039', 'SID951374125031'),
('+918827140787', 'SSF3494760'),
('+919993169059', 'SID951375482611'),
('+918936854524', 'SID951375663839'),
('+919360282166', 'SID951373662354'),
('+919352926838', 'SID951374587373'),
('+917610158558', 'SID951374857752'),
('+916263850557', 'SID951374535420'),
('+917509439326', 'SSF3075683'),
('+918964864947', 'CID218000574'),
('+919589542769', 'SID951375082408'),
('+919608096586', 'SID951372881164'),
('+918085946350', 'SID2125753857'),
('+916266234597', 'SID951375296168'),
('+919798830599', 'SID951375917315'),
('+917070224398', 'SSF2797329'),
('+918757006774', 'SID951376006293'),
('+919651471831', 'SSF2757195'),
('+916200594929', 'SSF3892039'),
('+917678232335', 'SSF3628415'),
('+917870774193', 'SSF4144564'),
('+917061164065', 'SSF3261700'),
('+917815816249', 'SSF3579834'),
('+917808537902', 'SSF4401569'),
('+918815692905', 'SSF4293869'),
('+918960116140', 'SSF3264026'),
('+918252665947', 'SSF3507455'),
('+918292357551', 'SSF3084854'),
('+919669426390', 'SSF3983304'),
('+917484827020', 'SSF3792097'),
('+917644058205', 'SSF4551411'),
('+919304461382', 'SSF4890224'),
('+917976121973', 'SSF4491553'),
('+918924834366', 'SSF3094942'),
('+919162858051', 'SID951375441877'),
('+916200154346', 'SSF3479975'),
('+917509694080', 'SID951374084391'),
('+917632982846', 'SSF3619839'),
('+916267671074', 'SSF3923437'),
('+916306645865', 'SSF3609865'),
('+916267386909', 'SSF3814420'),
('+917879523126', 'SSF3736744'),
('+918305057301', 'SSF2820629'),
('+918959259229', 'SSF3038519'),
('+918103597351', 'SSF3986697'),
('+919024465801', 'SSF4063721'),
('+919981287958', 'SSF4053690'),
('+916375748704', 'SSF3242585'),
('+917546913513', 'SSF4165703'),
('+917033027733', 'SSF3338704'),
('+918329841273', 'SSF3823086'),
('+918955252746', 'SSF3725745'),
('+919509891720', 'SSF3498260'),
('+919334984598', 'SSF3806514'),
('+919798856578', 'SSF3776690'),
('+919116605781', 'SSF3682887'),
('+918305859956', 'SSF3458876'),
('+918797799246', 'SID951375953007'),
('+916287812209', 'SSF3150866'),
('+918871447822', 'SID951374891769'),
('+918890226348', 'SSF2950310'),
('+919649142944', 'SID951375267003'),
('+917300203420', 'SID951375058127'),
('+917413093533', 'SID951375462941'),
('+918845786558', 'SSF2929714'),
('+919671032615', 'SSF2685832'),
('+919304562051', 'CID204504646'),
('+917033494335', 'SSF2296881'),
('+918294829150', 'SSF2487685'),
('+917761873373', 'SSF3436139'),
('+918224929737', 'SSF4248387'),
('+919931544197', 'SSF4265726'),
('+919122367020', 'SSF3444727'),
('+919661770235', 'SSF3668584'),
('+919007282652', 'SSF4765355'),
('+919263942257', 'SSF2765606'),
('+919142695022', 'SSF2621600'),
('+917870662734', 'SSF3344287'),
('+918092450849', 'SSF3098528'),
('+918305493885', 'SSF3315957'),
('+918104190958', 'SSF3984415'),
('+918969831324', 'SSF4554688'),
('+919065779176', 'SSF4821369'),
('+919661545827', 'SSF4034883'),
('+919508251336', 'SSF2825823'),
('+919241638462', 'SID951373903219'),
('+919931281654', 'SSF3299682'),
('+919343223503', 'SSF3252875'),
('+919302243797', 'SSF4695709'),
('+918604408386', 'SSF5367251'),
('+916200507200', 'SSF5049238'),
('+918102862167', 'SID951375577877'),
('+917049485630', 'SSF3621699'),
('+917898140898', 'SSF4080225'),
('+917643085488', 'SSF3211049'),
('+917033791975', 'SID951375270114'),
('+917050462346', 'SID951376161112'),
('+919452465040', 'SID951375191801'),
('+916203191246', 'SID951374949803'),
('+919835324949', 'CID211201077'),
('+917225048751', 'SSF3934596'),
('+917898587690', 'SSF4035550'),
('+918928695682', 'SSF4132403'),
('+918824597288', 'SSF3679376'),
('+919329468254', 'SSF3600842'),
('+918955542081', 'SSF3678331'),
('+918905005564', 'SSF3625763'),
('+918824944835', 'SSF3366769'),
('+917340157256', 'SSF3183016'),
('+918815777464', 'CID078102523'),
('+918521399362', 'SSF3635774'),
('+918306887432', 'SSF3103840'),
('+918955782197', 'SID951375192598'),
('+919256301498', 'SID951374445410'),
('+919587143816', 'SSF3250547'),
('+917067364032', 'SID951373126347'),
('+918107931826', 'SSF3412964'),
('+919238216003', 'SSF3107542'),
('+919680985797', 'SSF2801883'),
('+918597986794', 'SID951375952201'),
('+919644708257', 'SID951374313686'),
('+919926827729', 'SID951375752737'),
('+919685186743', 'SID951375949402'),
('+919981325449', 'CID207000494'),
('+917879951276', 'SSF2615486'),
('+916260061140', 'SSF4335342'),
('+917389485810', 'SSF4730090'),
('+919302070934', 'SSF4844266'),
('+919340286549', 'SSF3446181'),
('+917999153847', 'SSF4820646'),
('+919425733828', 'SID951375744023'),
('+919754125326', 'SID951373127074'),
('+918102563480', 'SID951374649086'),
('+917583019297', 'SID951374615562'),
('+918400060311', 'SSF3001683'),
('+916261063522', 'SID951372921339'),
('+918821026166', 'CID077803766'),
('+917222963901', 'SSF3755226'),
('+918825363857', 'SID951374643735'),
('+918890732193', 'SID951374763595'),
('+916268525013', 'SID951373679140'),
('+918235513389', 'SSF4225243'),
('+917869032218', 'SID951376007332'),
('+917870196144', 'SID951374289890'),
('+919460344427', 'SID951374090805'),
('+917464022400', 'SSF4862845'),
('+917447281227', 'SSF3667736'),
('+919636893292', 'SSF4238580'),
('+916362442729', 'SSF2914275'),
('+917546802673', 'SSF5713491'),
('+916263647562', 'CID071203789'),
('+917747850843', 'SID951376062033'),
('+919301092765', 'CID038513268'),
('+919022261866', 'SID951374795520'),
('+916261597916', 'SSF4200477'),
('+919770186338', 'SSF3459763'),
('+919709491733', 'SSF5242729'),
('+919321803810', 'SSF3453405'),
('+917880047638', 'CID081003285'),
('+918462062913', 'SID2125647401'),
('+919131411332', 'SID951374180843'),
('+919369473186', 'SSF4516282'),
('+919128760531', 'SID951375392689'),
('+919955719996', 'SID951375200599'),
('+919340419597', 'SID951375968562'),
('+918962272950', 'SID951373654542'),
('+917024868889', 'CID219300786'),
('+917870908149', 'SSF4100652'),
('+917208125251', 'SID951376017153'),
('+919122870074', 'SID951375226570'),
('+919669543843', 'SID2125630921'),
('+916260849860', 'SID2125406556'),
('+917319928756', 'SID951373510883'),
('+917700810689', 'SID951374605347'),
('+917208629596', 'SID951375320782'),
('+918434934739', 'SSF2811756'),
('+916200635395', 'SSF4326704'),
('+917296079324', 'SSF4589344'),
('+919155346600', 'SSF4056262'),
('+919304124757', 'SID951374923705'),
('+919301345515', 'SSF3388900'),
('+919579336390', 'SSF3145122'),
('+918815803359', 'SSF3708807'),
('+919828390040', 'SSF3254890'),
('+919341061791', 'SSF4696061'),
('+917068677350', 'SID951375105798'),
('+919229062438', 'SSF4848135'),
('+917000456430', 'SSF3022107'),
('+917587147017', 'SSF4352923'),
('+918294723189', 'SSF3335434'),
('+918521357836', 'SSF3491543'),
('+918769235671', 'SID951374400725'),
('+918871884353', 'SSF3109952'),
('+919546291554', 'SSF2444425'),
('+916264861884', 'SSF4066924'),
('+919166367348', 'SID951375496672'),
('+919660858130', 'SSF3499134'),
('+919530195885', 'SSF3910420'),
('+919572842448', 'SSF4868542'),
('+916201383121', 'SID951374404893'),
('+918290603244', 'SSF4075346'),
('+918292195891', 'SID951374942340'),
('+919510348346', 'SSF4244864'),
('+919509708450', 'SSF4061389'),
('+919787484649', 'SID951374299646'),
('+919892136390', 'SSF3433618'),
('+919079373714', 'SSF3690986'),
('+919216938364', 'SID951375355913'),
('+919315369147', 'SSF3391931'),
('+919024888230', 'SSF3622446'),
('+918763794937', 'SID951374370934'),
('+919521256276', 'SID951376036056'),
('+919301219641', 'CID261401285'),
('+919136223528', 'SSF3150821'),
('+917803957892', 'SID951375511418'),
('+919812917628', 'SID951376049623'),
('+917828779357', 'SID2125064351'),
('+919793520517', 'SID951374120758'),
('+916202566378', 'SID951374497785'),
('+917061278621', 'SID951375073645'),
('+918839223977', 'SID951375249751'),
('+916205229975', 'SSF2811754'),
('+918969836402', 'SID951373114893'),
('+919065186485', 'SSF2493450'),
('+916267051667', 'SSF3432119'),
('+916261358136', 'SSF3274472'),
('+917549269544', 'SSF4616537'),
('+917724894041', 'SSF4378751'),
('+918294933724', 'SSF3087882'),
('+919098090647', 'SSF5011312'),
('+919135203543', 'SSF3077727'),
('+917250326494', 'SID951373068643'),
('+917772055648', 'SSF2447034'),
('+918809717709', 'SSF2817858'),
('+918084626431', 'SSF2721687'),
('+919106918921', 'SSF2300481'),
('+917879781805', 'SSF3228104'),
('+918276044010', 'SSF4119717'),
('+918827131921', 'SSF3284536'),
('+919065974440', 'SSF3478581'),
('+919649523480', 'SSF3857483'),
('+919839142683', 'SSF4895839'),
('+918839023481', 'CID050408118'),
('+917028920122', 'SSF3645671'),
('+917004047825', 'SID951373848904'),
('+918707532091', 'SSF4754169'),
('+916267359537', 'SSF3986473'),
('+918959873377', 'SSF3980930'),
('+918435472224', 'SSF4290262'),
('+919784267678', 'SID951375082157'),
('+919244375135', 'SSF2446831'),
('+919905395165', 'SID951373264955'),
('+919313776344', 'SID951375428589'),
('+919770191426', 'SSF4092008'),
('+919244714514', 'SSF3001238'),
('+916264397110', 'SID2125778471'),
('+917340153545', 'SSF3354722'),
('+917568307281', 'SSF4295284'),
('+918003123388', 'SID951375119177'),
('+918053912108', 'SID951375407573'),
('+918440879064', 'SSF3751112'),
('+917976584903', 'SID951374545012'),
('+917689834774', 'SSF2574254'),
('+918252203521', 'SSF3445704'),
('+917722904765', 'SSF3246233'),
('+918058894908', 'SSF3556470'),
('+918302108747', 'SSF3452400'),
('+919602607216', 'SSF2779032'),
('+916266302916', 'CID081100635'),
('+917441132677', 'SSF2612601'),
('+917354769889', 'SSF2407039'),
('+918269773085', 'SSF2542675'),
('+919625409149', 'SSF2547063'),
('+917974384630', 'SSF4444718'),
('+918756770114', 'SSF4413176'),
('+919009222808', 'SSF4832479'),
('+918103591041', 'SID951375678584'),
('+919303810633', 'SID951374870758'),
('+918057625762', 'SSF4662629'),
('+917470312090', 'SID951373442979'),
('+919569315196', 'SSF3207843'),
('+916266737720', 'CID129101816'),
('+919321791493', 'SID951373417344'),
('+919102414673', 'SSF4650711'),
('+919303057547', 'SSF3040699'),
('+919875474733', 'SID951376000759'),
('+919504418786', 'SSF4358660'),
('+917828681952', 'SID951373298973'),
('+918207687545', 'SID2125654265'),
('+919660054231', 'SID951375551117'),
('+917224042828', 'CID174402461'),
('+919589371919', 'SID951373185408'),
('+919708133396', 'SID951374252895'),
('+917747876295', 'SID951375010880'),
('+918693542183', 'SID951375774180'),
('+917974409081', 'SID951376105470'),
('+919302170875', 'CID204605299'),
('+919770002487', 'CID053212286'),
('+917808366244', 'SID951374718261'),
('+918757532717', 'SID951375518541'),
('+916264770449', 'SSF2881038'),
('+916306533826', 'SSF2939411'),
('+918797213919', 'SID951374142198'),
('+916204043046', 'SSF3048563'),
('+917275413336', 'SSF2726330'),
('+918815352033', 'SSF4375080'),
('+918966977307', 'SSF4901226'),
('+919279166821', 'SSF3725540'),
('+919588575088', 'SSF3304988'),
('+919625442367', 'SSF3295947'),
('+919229163446', 'SSF3203802'),
('+919928060869', 'SSF2594346'),
('+916362973302', 'SSF3792517'),
('+917464080759', 'SSF2837686'),
('+917250238080', 'SSF4220066'),
('+917632861044', 'SSF4216502'),
('+917256040164', 'SSF3145601'),
('+917727963731', 'SSF3947108'),
('+919608988027', 'SSF4249490'),
('+919341597841', 'SSF2534014'),
('+918090705487', 'SSF4668670'),
('+919118994799', 'SSF4643736'),
('+917828738433', 'SSF4444657'),
('+919065338209', 'SSF2634932'),
('+919031506537', 'SSF3104237'),
('+919334325598', 'SSF4521788'),
('+918260887634', 'SID951373471051'),
('+916268193738', 'SSF3961804'),
('+918302025159', 'SSF2425870'),
('+918239269747', 'SSF2661115'),
('+919685912054', 'SID951375435613'),
('+919244626714', 'SSF3927640'),
('+919549059554', 'SID951375996594'),
('+919936374397', 'SSF4046499'),
('+917489852815', 'CID076608717'),
('+919301431953', 'CID076607496'),
('+919905305324', 'SID951374060818'),
('+916367322120', 'SSF3676661'),
('+916986565984', 'SID951376055001'),
('+916205875545', 'SSF2450478'),
('+917568015116', 'SID951375902512'),
('+917014535957', 'SSF2587544'),
('+917737823607', 'SSF3799795'),
('+917985433224', 'SSF2362869'),
('+917357554019', 'SSF2539729'),
('+917415595210', 'SSF4065522'),
('+918005612703', 'SID951375531996'),
('+918829979331', 'SSF2644847'),
('+918690851261', 'SSF3679511'),
('+918949211585', 'SID951376186169'),
('+918239157152', 'SID951375783336'),
('+918826480753', 'SID951376066102'),
('+919929905688', 'SSF3740869'),
('+919664101653', 'SID951376217622'),
('+919216306637', 'SID951375088482'),
('+919982399895', 'SSF2567856'),
('+919098884682', 'SSF4087172'),
('+919525053828', 'SID951375492369'),
('+919983547592', 'SSF2574995'),
('+919983323922', 'SSF2300890'),
('+919166759079', 'SID951375165976'),
('+918299570291', 'SSF3817391'),
('+919511526497', 'SID951376038766'),
('+916894532584', 'SID951375748294'),
('+917254838655', 'SID951375464573'),
('+917281504000', 'SID2125477933'),
('+918078787878', 'SID951375629016'),
('+919982385392', 'SID951375883727'),
('+919801246143', 'SSF3270126'),
('+919358686233', 'SSF3436728'),
('+919166176640', 'SSF2585888'),
('+919602207282', 'SSF2454091'),
('+919109747101', 'SID951373990816'),
('+919950359721', 'SSF3367330'),
('+919783560472', 'SID951376188386'),
('+919079097925', 'SID951376093847'),
('+919518677028', 'SSF2550172'),
('+919884558555', 'SID951376046538'),
('+916376928149', 'SSF2485915'),
('+916396170950', 'SSF3081496'),
('+916377838818', 'SSF2302163'),
('+916352856566', 'SID951376054134'),
('+918769295515', 'SID951375996943'),
('+918905948529', 'SSF2552661'),
('+918434610238', 'SSF3433424'),
('+918302250231', 'SID951376028194'),
('+919444303234', 'SID101218'),
('+919343641227', 'SSF2440753'),
('+919460853331', 'SSF2752311'),
('+919685842783', 'SSF2569934'),
('+919649254439', 'SSF2453282'),
('+919839858056', 'SID951375497103'),
('+919199814353', 'SID951376214343'),
('+919595966499', 'SSF2579039'),
('+916375107713', 'SID951376041164'),
('+916378867394', 'SID951375910274'),
('+917321064681', 'SSF3053906'),
('+917043622396', 'SID951375683719'),
('+917425866793', 'SSF3276911'),
('+918003447962', 'SID951374889690'),
('+918905176142', 'SID951375645176'),
('+918854069258', 'SSF2697598'),
('+918306875912', 'SID951376065604'),
('+918221942567', 'SSF2587725'),
('+918591755020', 'SSF2589292'),
('+919680626357', 'SSF3105863'),
('+919636919784', 'SID951375392609'),
('+919683541854', 'SID951375451404'),
('+919982567352', 'SID951376076130'),
('+919108901648', 'SSF3899640'),
('+919784664539', 'SSF2419923'),
('+916857356366', 'SID951376202423'),
('+917568566648', 'SSF2297242'),
('+918976451545', 'SID951376088648'),
('+919079811247', 'SID951375750484'),
('+919785225254', 'SID951376167206'),
('+919636172256', 'SSF2381387'),
('+919868767664', 'SID951376152167'),
('+917275839575', 'SSF2577312'),
('+917752930814', 'SID951375997168'),
('+917418245316', 'SSF2634188'),
('+917846648784', 'SID951375994922'),
('+919434843949', 'SSF2358052'),
('+919817672448', 'SSF2617188'),
('+919564848454', 'SID951376086204'),
('+919137979135', 'SID951375538454'),
('+916464646468', 'SSF2470043'),
('+916764564668', 'SID951376209138'),
('+917573197677', 'SID951375965908'),
('+917876316484', 'SID951375967203'),
('+918890550797', 'SID951376129418'),
('+919437998997', 'SID951376034291'),
('+917000183718', 'SID951374134286'),
('+918969671215', 'CID263600482'),
('+919263787673', 'SID951373794159'),
('+916267442607', 'SID951374679226'),
('+918292800354', 'SID951375413536'),
('+919304459142', 'SID951374678301'),
('+919306944691', 'SSF2674315'),
('+917091644745', 'SSF3394209'),
('+917479511416', 'SSF4512774'),
('+917023326845', 'SSF3125836'),
('+918871322921', 'SSF5044131'),
('+918808966695', 'SSF4501246'),
('+919304441031', 'SSF3740113'),
('+919354240407', 'SSF4426064'),
('+919174292178', 'SSF3717852'),
('+917651962310', 'SID951374292404'),
('+919060608317', 'SID951375125088'),
('+916201565406', 'SSF4129731'),
('+917667187224', 'SSF3676366'),
('+917070795140', 'SSF4578343'),
('+918756094734', 'SSF3439958'),
('+919122546616', 'SSF3571643'),
('+919399427289', 'SSF4511466'),
('+919302974689', 'SSF3979949'),
('+919602230360', 'SID951375832101'),
('+916378339126', 'SID951374542196'),
('+918249932175', 'SID951373132972'),
('+917237873166', 'SSF4748849'),
('+917909876105', 'SSF4072381'),
('+917689099392', 'SID951374680911'),
('+917217752084', 'SSF4249254'),
('+917978361513', 'SSF2581514'),
('+918233888386', 'SSF2573841'),
('+918959654232', 'SSF3168033'),
('+918002839038', 'SSF4879335'),
('+919263918942', 'SID951372910750'),
('+917748816464', 'SSF3762353'),
('+918810502150', 'SSF5145634'),
('+917485962396', 'SID951374930874'),
('+918233825641', 'SID951376128989'),
('+918839433991', 'SSF3780299'),
('+918696760391', 'SSF3995119'),
('+918461985019', 'SSF4181961'),
('+918815956780', 'SID951373899874'),
('+919797676889', 'SID951376109363'),
('+919301831567', 'SID951373634422'),
('+919508972571', 'SSF4326964'),
('+916202639688', 'SID951375692826'),
('+916297549434', 'SID951374763592'),
('+916454878778', 'SID951376167153'),
('+917070833726', 'SID951374643964'),
('+917073757921', 'SSF2390575'),
('+917356184270', 'SSF3880585'),
('+917990536338', 'SSF4094115'),
('+918305174534', 'SSF3942013'),
('+918770135234', 'SSF2405369'),
('+919131841773', 'SSF3740505'),
('+919885464643', 'SID951376020633'),
('+919343386086', 'SSF3612604'),
('+919672399074', 'SSF2343368'),
('+919864359191', 'SID951375831602'),
('+917828609230', 'SID951375268152'),
('+917357437138', 'SID951376183936'),
('+918518020674', 'SID951374944910'),
('+918858026874', 'SSF2454543'),
('+916367751068', 'SID951375496926'),
('+916354964976', 'SID951376161851'),
('+916005939631', 'SID951376171393'),
('+917828175877', 'SID951374334279'),
('+917014695648', 'SSF3160417'),
('+917697017457', 'SID951375991145'),
('+918295145986', 'SSF2497275'),
('+919024057110', 'SSF3012299'),
('+919487646495', 'SID951375997362'),
('+919965479969', 'SID951375556876'),
('+917878551390', 'SSF2479585'),
('+917339947992', 'SID951375451327'),
('+918084436716', 'SSF3283797'),
('+918432656188', 'SSF3276870'),
('+919119219477', 'SSF2559889'),
('+919602279723', 'SSF3019220'),
('+919549881536', 'SSF2584360'),
('+919680458548', 'SID951375663141'),
('+919983460604', 'SID951375968192'),
('+919680665492', 'SID951375783388'),
('+919672501153', 'SID951375612496'),
('+919829758692', 'SID951375565755'),
('+918058765792', 'SSF2458177'),
('+918875350504', 'SID951375786367'),
('+918059953471', 'SID951375938615'),
('+918577912746', 'SSF3038476'),
('+918829935955', 'SSF2591831'),
('+919817553224', 'SID951376057069'),
('+919024225715', 'SSF2280477'),
('+919558658886', 'SSF2556856'),
('+916467686868', 'CID951376210355'),
('+917739281774', 'SID951375956090'),
('+917546598959', 'SID951376125098'),
('+917127646865', 'SID951376038726'),
('+919648555665', 'SSF2358053'),
('+919636676464', 'SID951376227263'),
('+919950585103', 'SID951376177764'),
('+917877716519', 'SID951376057304'),
('+918292949356', 'SID951375985970'),
('+919997348484', 'SID951375428588'),
('+919865983295', 'SSF2839510'),
('+919302673401', 'CID140603840'),
('+916263515449', 'SSF3558935'),
('+918770609888', 'SSF3011154'),
('+918518999363', 'SSF2481767'),
('+918319879323', 'SSF3095263'),
('+919165839989', 'SSF3655884'),
('+919630528074', 'SSF4035844'),
('+919201032858', 'SSF4115425'),
('+916254616454', 'SID951374014245'),
('+919369497374', 'SID951374417978'),
('+918878156347', 'SID2125720884'),
('+918837563710', 'SSF5285755'),
('+917579375139', 'SSF5707620'),
('+919079463986', 'SSF4377077'),
('+916232164919', 'CID081102404'),
('+919128755487', 'SSF4445366'),
('+917067353059', 'CID081012900'),
('+917000112577', 'SID951375141161'),
('+918252765834', 'CID951376201724'),
('+918757072546', 'SID951375031970'),
('+916263815744', 'CID129101248'),
('+919244621198', 'SID951373875961'),
('+919304094789', 'SSF4812856'),
('+917764073879', 'SID951374614783'),
('+917974611706', 'SID951373434792'),
('+919302209067', 'SID951374954017'),
('+918294052970', 'SID951373093559'),
('+918624255358', 'SID951373981467'),
('+919113153247', 'SSF5173027'),
('+919709867405', 'SID951374947836'),
('+919983692765', 'SSF3849307'),
('+919244314801', 'SID951373065182'),
('+918719979484', 'CID128603533'),
('+916204746253', 'SSF2396834'),
('+918090550747', 'SSF5008956'),
('+919009489771', 'SID951374096162'),
('+918827010124', 'SID951375290655'),
('+917725840625', 'SSF4827878'),
('+918757029302', 'SID951373529657'),
('+917321038113', 'SID951374115940'),
('+917200418277', 'SID951372849517'),
('+916201881662', 'SID2125696907'),
('+918340685560', 'SID951374064366'),
('+918102167144', 'SID951374991777'),
('+917633891822', 'SSF2627089'),
('+917723943342', 'SSF2597025'),
('+917068657177', 'SSF2764932'),
('+918470903414', 'SSF2687725'),
('+916299667673', 'SSF2952613'),
('+916387786630', 'SSF4033006'),
('+917481832536', 'SSF3415141'),
('+917860934659', 'SSF3731258'),
('+917206914764', 'SSF3548132'),
('+917360813392', 'SSF4251189'),
('+919341165927', 'SSF4332400'),
('+919031778483', 'SSF4775211'),
('+918600179862', 'SSF2997021'),
('+918789984858', 'SSF3100225'),
('+918889102553', 'SSF3542984'),
('+919098117241', 'SSF5075213'),
('+919975538312', 'SSF3580198'),
('+919179759802', 'SSF4903101'),
('+917999896299', 'SID951375664047'),
('+918434985481', 'SID951375793855'),
('+916205302981', 'SID951376247253'),
('+917080605703', 'SSF4418829'),
('+918084273080', 'SSF3891972'),
('+918852086926', 'SSF3044779'),
('+918002456235', 'SSF4961548'),
('+917081113459', 'SSF4649907'),
('+917804894933', 'SSF4565570'),
('+917879843058', 'SSF4545187'),
('+918651335995', 'SSF3734234'),
('+919301159266', 'SSF4383662'),
('+917803965122', 'CID213100940'),
('+919098101209', 'SID2125492978'),
('+919905757442', 'SID951374355865'),
('+917478379045', 'SSF5226413'),
('+916200285670', 'SSF4118811'),
('+917999615938', 'SSF4037317'),
('+917999526477', 'SSF3565049'),
('+918290386406', 'SSF3935363'),
('+918824629455', 'SSF3565298'),
('+919571786422', 'SSF3993813'),
('+919770625801', 'SSF4005693'),
('+919329825564', 'SSF4004676'),
('+919660443382', 'SSF3692297'),
('+918603213450', 'SSF4151541'),
('+918815709533', 'SSF4023700'),
('+919461791841', 'SSF3703343'),
('+918540966771', 'SSF4327673'),
('+919399815879', 'SSF3610445'),
('+917742432711', 'SID951375658818'),
('+918305878760', 'SID951374817954'),
('+919257606492', 'SSF3391834'),
('+919256337098', 'SSF3637889'),
('+918290840004', 'SSF2948232'),
('+919340198796', 'SID951374126243'),
('+919521323287', 'SSF3492888'),
('+917223057669', 'SSF3608749'),
('+919343110721', 'SSF3598805'),
('+918168062127', 'SSF2760280'),
('+918299171978', 'SID951374061201'),
('+917481035975', 'SSF2697494'),
('+916232482175', 'SSF4204973'),
('+917250324939', 'SSF4328177'),
('+917480026715', 'SSF3474253'),
('+917489477492', 'SSF3642114'),
('+918982416536', 'SSF4188820'),
('+918521473275', 'SID951374861777'),
('+918294136048', 'SSF3602673'),
('+918434839435', 'SSF3698754'),
('+918435912064', 'SSF5100500'),
('+919529127197', 'SSF3123509'),
('+918423336281', 'SSF4050554'),
('+919236298785', 'SSF3991390'),
('+918878569796', 'CID951376201210'),
('+919198579018', 'SSF2929059'),
('+916264194374', 'SSF4252443'),
('+917080410476', 'SSF2777051'),
('+917858841833', 'SSF4327354'),
('+917324042436', 'SID951373106194'),
('+917879283896', 'SSF4565150'),
('+918271523751', 'SSF3363795'),
('+918461023806', 'SSF3605428'),
('+918305385363', 'SSF4882522'),
('+918984419483', 'SSF3581371'),
('+919939927972', 'SSF3190631'),
('+919032308618', 'SSF3223010'),
('+919608388393', 'SSF4165730'),
('+919174477967', 'SSF4556029'),
('+919241495590', 'SSF3083878'),
('+919102295968', 'SSF3225925'),
('+919661814379', 'SID2125559119'),
('+917067441300', 'SSF4647307'),
('+917726866491', 'SSF4244388'),
('+919546705898', 'SID951375481520'),
('+919343833072', 'SSF4471367'),
('+919648197124', 'SSF2978476'),
('+916354567582', 'SSF4951361'),
('+917869452750', 'SID951372972232'),
('+916392033132', 'SID951374798739'),
('+916267551421', 'SSF4082061'),
('+918114505867', 'SSF4626048'),
('+919104550563', 'SSF3967350'),
('+916202589694', 'SSF4058824'),
('+917978283572', 'SSF3927641'),
('+919925978113', 'SSF3886127'),
('+916207576423', 'SSF4202208'),
('+916370636297', 'SSF3927679'),
('+917383605663', 'SID951374545599'),
('+917568895930', 'SID951375973434'),
('+919988536875', 'SID2125719161'),
('+917850048423', 'SSF2876622'),
('+919654349538', 'CID211202861'),
('+919009182049', 'SID951373170312'),
('+919369650997', 'SSF2736712'),
('+919516572941', 'SSF2649885'),
('+916232788332', 'SSF2894110'),
('+916261859365', 'SSF3765346'),
('+916267435326', 'SSF4212508'),
('+917489670687', 'SSF3333159'),
('+917007557821', 'SSF5850660'),
('+917749051708', 'SID951373505599'),
('+919691633365', 'SID951374660601'),
('+916203406603', 'SID951373431970'),
('+919009550493', 'SID951374288992'),
('+917879393707', 'CID038501683'),
('+918871567998', 'SID951375056907'),
('+918959619069', 'SID951375087335'),
('+916263729144', 'SID2125482316'),
('+918817737435', 'SSF4260079'),
('+919575087937', 'CID072002058'),
('+917492090381', 'SID951374941624'),
('+916260102948', 'SID951374527788'),
('+916207608462', 'SID951375983807'),
('+918817807882', 'SID52773'),
('+919691673656', 'SSF2728612'),
('+916282681778', 'SID951374677260'),
('+919644918985', 'SSF3668902'),
('+918878407078', 'SSF4223139'),
('+917440426486', 'SID951374375202'),
('+919098166036', 'SID951374137825'),
('+919166796017', 'SID951375278638'),
('+918770962342', 'SID951373792354'),
('+918878405550', 'CID174607332'),
('+917828684225', 'SID951372907142'),
('+918294007979', 'SID951375798979'),
('+919116721535', 'SID951375232519'),
('+919108195683', 'SID951375276937'),
('+918084552020', 'SSF2824638'),
('+919839263210', 'SSF2939744'),
('+916261472793', 'SSF4466287'),
('+916261616085', 'SSF4681161'),
('+916209027758', 'SSF4494505'),
('+917317410651', 'SSF4569072'),
('+918271752235', 'SSF4046780'),
('+919334866066', 'SSF3683132'),
('+919555718976', 'SSF2391366'),
('+919669194116', 'SSF4832459'),
('+917440657003', 'SID951373912089'),
('+919244268577', 'SID951373907741'),
('+917224995834', 'SSF4296363'),
('+918319230834', 'SSF4840715'),
('+917389715169', 'SID951373608885'),
('+918309568289', 'SID951374527083'),
('+918603519552', 'SSF2888247'),
('+918340640261', 'SSF3015097'),
('+919407991073', 'SSF5095006'),
('+919755600455', 'SID951372839586'),
('+916379415911', 'SSF3670537'),
('+916268466808', 'SSF2889764'),
('+916207888849', 'SSF3805046'),
('+917764933809', 'SID951375793239'),
('+919570092187', 'SSF3965408'),
('+919350134654', 'SSF2911184'),
('+917091150020', 'SSF3145736'),
('+917257016826', 'SSF2811954'),
('+917765989018', 'SSF3295923'),
('+917379680124', 'SSF2852496'),
('+918953394157', 'SSF3198358'),
('+918756368954', 'SSF2965718'),
('+917697089666', 'SID2125603645'),
('+919263133379', 'SID951375053189'),
('+917050447286', 'SSF4087809'),
('+917357681277', 'SSF2859361'),
('+918210269304', 'SSF3220131'),
('+918962406604', 'SSF4353364'),
('+919509235314', 'SSF4351756'),
('+919065072259', 'SSF4117157'),
('+918756937183', 'SSF5050106'),
('+917489209061', 'SSF3976517'),
('+918000116582', 'SSF4064741'),
('+919549099216', 'SSF3333490'),
('+919257215411', 'SID951376016146'),
('+917646911338', 'SID951373607918'),
('+918926895658', 'SID951373159077'),
('+918521646904', 'SID951375503089'),
('+916268584638', 'SSF3607622'),
('+916261967785', 'SSF3246077'),
('+919787978784', 'SID2125574859'),
('+919024674539', 'SSF3080601'),
('+919351527987', 'SSF2945573'),
('+919664234443', 'SSF3074660'),
('+919399877120', 'SID951374079514'),
('+917526896887', 'SSF2932826'),
('+918669855889', 'SID951375241625'),
('+916267831427', 'SSF2988418'),
('+917665295804', 'SSF2824919'),
('+918965319300', 'SID951373410628'),
('+919460053637', 'SSF3014989'),
('+917974153807', 'CID204600371'),
('+916266039506', 'SID951372944165'),
('+916264879420', 'SSF3850760'),
('+916260482457', 'SSF3833096'),
('+917091038038', 'SSF4639698'),
('+917070843230', 'SSF4808800'),
('+918207638927', 'SSF4574692'),
('+918817503783', 'SSF4966534'),
('+919135470067', 'SSF3264716'),
('+919572578260', 'SSF4934893'),
('+919234900349', 'SSF3571044'),
('+919935363445', 'SID951373974845'),
('+916380452708', 'SID951374756712'),
('+917828427340', 'SID101839'),
('+917000784558', 'SID951375737365'),
('+919939660085', 'SID951374361439'),
('+918789415290', 'SSF2790436'),
('+919693280852', 'SSF2845486'),
('+919334861134', 'SSF2767144'),
('+916206266341', 'SSF2898718'),
('+916363323937', 'SSF3911444'),
('+916386404237', 'SSF4291481'),
('+917256966724', 'SSF4610925'),
('+917488352580', 'SSF2448470'),
('+917804879758', 'SSF4608537'),
('+917879916552', 'SSF4802180'),
('+919279771742', 'SSF4423307'),
('+919171934014', 'SSF4906734'),
('+919631869410', 'SSF3828643'),
('+918115703878', 'SSF4716439'),
('+919982134742', 'SID951375668498'),
('+918103632744', 'SSF4565257'),
('+919399745995', 'SID951374531227'),
('+918239632866', 'SID951375493689'),
('+918658172602', 'SSF4253563'),
('+919135922038', 'SSF2796844'),
('+919343178557', 'SSF3386757'),
('+919801988655', 'SSF2985217'),
('+918894337258', 'SSF3277415'),
('+918292588868', 'SSF3264261'),
('+917974008657', 'SSF4468188'),
('+917749093279', 'SSF2994888'),
('+917043267798', 'SSF4092829'),
('+917691992612', 'SSF4042731'),
('+919770302450', 'SID951373494282'),
('+917665626621', 'SSF4002112'),
('+918429238991', 'SSF3729429'),
('+919525502822', 'SID951375547396'),
('+919376515668', 'SSF3658412'),
('+919006460142', 'SSF3883869'),
('+919929492605', 'SSF3974404'),
('+917740815341', 'SSF4393366'),
('+918949998789', 'SSF3791230'),
('+918559909813', 'SSF3752080'),
('+917033373894', 'SID951374772972'),
('+917372906196', 'SSF2506208'),
('+918809677062', 'SSF2711747'),
('+919571919968', 'SID951374895532'),
('+919632455859', 'SID951374618439'),
('+919783938965', 'SSF3180634'),
('+919680356225', 'SSF3015285'),
('+917023354035', 'SID951374819585'),
('+917665240384', 'SSF2580737'),
('+916564644676', 'SSF2803049'),
('+918879942601', 'SSF2769702'),
('+918815305029', 'SID951372860551'),
('+919589610193', 'CID176208403'),
('+919981825812', 'SID2125611091'),
('+916263923051', 'SID951375803699'),
('+917879343365', 'SID951375671248'),
('+916367909458', 'SID951374211264'),
('+919005727557', 'SSF4127690'),
('+917049085584', 'SSF5314518'),
('+916267370241', 'CID219402268'),
('+918084518134', 'SSF3698846'),
('+916200982267', 'SSF2305108'),
('+916263000678', 'SID951373526156'),
('+916261265079', 'SID951373624848'),
('+918917050590', 'SSF4625356'),
('+916267459976', 'SID951376139704'),
('+917693950823', 'SSF3931588'),
('+919302484577', 'SID2125067071'),
('+916262882695', 'CID122603169'),
('+918959420318', 'SID951372809905'),
('+918890761283', 'SID951375765996'),
('+916260302032', 'SID951373040213'),
('+918601747821', 'SID951375959533'),
('+917470682824', 'SSF4462316'),
('+917772812646', 'CID084401719'),
('+918699221925', 'SID951375176029'),
('+917370856897', 'CID262400898'),
('+919630925739', 'SID951375729125'),
('+917307488815', 'SSF2348561'),
('+918354049762', 'SSF4552919'),
('+918319140158', 'SSF4641613'),
('+919060864152', 'SSF4616555'),
('+919060980872', 'SSF5161880'),
('+919303832375', 'SSF5029733'),
('+918887659524', 'SSF2670563'),
('+919302775436', 'SSF5138758'),
('+917766065856', 'SSF3480000'),
('+917727950556', 'SSF4517676'),
('+918591436112', 'SSF3417960'),
('+918290445541', 'SSF4160937'),
('+919170823193', 'SSF4417590'),
('+919993511904', 'SSF4590141'),
('+919875886378', 'SSF5050166'),
('+919560215635', 'SSF4346700'),
('+919893958654', 'SSF4402812'),
('+917459940089', 'SSF4941632'),
('+919838898070', 'SSF4792766'),
('+916260110424', 'SSF4122123'),
('+917697120663', 'SSF3923684'),
('+917974274244', 'SSF2590430'),
('+917209343832', 'SSF3742705'),
('+917067917936', 'SSF4371755'),
('+919162779482', 'SID951374612118'),
('+919865332563', 'SID951375373519'),
('+916202321863', 'SSF5073072'),
('+918233152390', 'SSF4025920'),
('+919983675049', 'SSF4237276'),
('+919399242401', 'SID951373256782'),
('+918434812578', 'SID951375274296'),
('+917014744848', 'SID951376175761'),
('+919057138655', 'SSF3173244'),
('+919504990981', 'SSF3433423'),
('+917470584332', 'SSF3598149'),
('+917488920976', 'SID951374545390'),
('+918252450495', 'SSF4677343'),
('+918271342846', 'SSF4712263'),
('+919572705735', 'SSF4876993'),
('+919098164695', 'SSF3945561'),
('+919131679886', 'SSF4210212'),
('+919617806437', 'SSF4465558'),
('+918305898354', 'SID951373044015'),
('+917061694406', 'SID951375408908'),
('+918292410720', 'SID951375624737'),
('+917379842050', 'SSF2691696'),
('+918427312067', 'SSF2898717'),
('+916207440498', 'SSF3817686'),
('+916201292132', 'SSF2957556'),
('+917973412032', 'SSF2730452'),
('+917327995695', 'SSF4536604'),
('+917870123700', 'SSF3712092'),
('+918809390487', 'SSF3384163'),
('+918390173750', 'SSF4444048'),
('+919835528697', 'SSF3511269'),
('+919657859161', 'SSF3225594'),
('+919113885817', 'SSF5301302'),
('+919244733243', 'SSF4270712'),
('+916393916035', 'SSF5107725'),
('+919161048703', 'SSF2693137'),
('+916200811310', 'SSF4044000'),
('+919559079222', 'SSF3380165'),
('+919325752473', 'SSF4601469'),
('+919770599832', 'SSF2946082'),
('+917763031757', 'SSF4482487'),
('+917440547965', 'SSF2823711'),
('+918905511439', 'SSF4253074'),
('+919304860731', 'SSF4966641'),
('+917878691146', 'SSF3856178'),
('+917300316622', 'SSF2424765'),
('+918000942258', 'SSF3255659'),
('+918982810182', 'SSF3594095'),
('+918955293351', 'SSF3440314'),
('+919982353296', 'SSF3447446'),
('+917024923547', 'SID951373302791'),
('+918319369551', 'SID951373602524'),
('+917489218103', 'SID951375246312'),
('+917067233514', 'SID951375095744'),
('+917879686859', 'SSF2811268'),
('+917723947218', 'SSF3582856'),
('+917869026964', 'SSF3603266'),
('+917509201011', 'SSF3160926'),
('+918269565410', 'SSF2776403'),
('+919981496213', 'SSF3345834'),
('+919584091069', 'SSF3871484'),
('+919926626854', 'SSF3422872'),
('+917987778532', 'CID061202625'),
('+919835061832', 'SID951375073813'),
('+919166791138', 'SID951374741503'),
('+917595906212', 'SSF2715717'),
('+917700843326', 'SSF2701065'),
('+916260477587', 'SID951373560857'),
('+919516194690', 'CID061213372'),
('+919977365700', 'SID951375881352'),
('+916391427572', 'SSF4387733'),
('+919993814409', 'SSF3277042'),
('+919608647552', 'SID951375055614'),
('+919399600524', 'CID044713253'),
('+917879326442', 'CID093809257'),
('+918809841014', 'SID2125099925'),
('+919341808187', 'SSF5451266'),
('+917701800477', 'SID951375155239'),
('+919341476631', 'SID951374594051'),
('+919610814540', 'SID951376051605'),
('+917463933521', 'SSF4705281'),
('+917268855204', 'SSF4634746'),
('+918269402565', 'SSF3252431'),
('+918349993466', 'SSF4946223'),
('+918789265039', 'SSF3627517'),
('+918739093110', 'SSF3375427'),
('+919939257754', 'SSF4536243'),
('+919691931540', 'CID264108424'),
('+918518852845', 'SSF2717375'),
('+919117506720', 'SID951376153663'),
('+917972403175', 'SSF4703066'),
('+917070305315', 'SSF4712218'),
('+919162562747', 'SSF4619532'),
('+916261737519', 'CID050403371'),
('+917061825183', 'SSF5144485'),
('+917079146123', 'SID951374056009'),
('+919753287371', 'CID191804053'),
('+919399839500', 'SID951374132204'),
('+916299714398', 'SSF3553437'),
('+917803040838', 'SSF3353819'),
('+917742883365', 'SSF4762957'),
('+917488627456', 'SSF4213703'),
('+918225968967', 'SSF4170687'),
('+918294837504', 'SSF5043123'),
('+917856845829', 'SID951374240971'),
('+917014653651', 'SID951375883895'),
('+918252958291', 'SSF3740318'),
('+919664136431', 'SSF3448154'),
('+918310370515', 'SSF5185314'),
('+919525732507', 'SSF4220102'),
('+918866329827', 'SSF5254945'),
('+916261605430', 'SSF4219975'),
('+917742416073', 'SSF2476782'),
('+917877076683', 'SSF2847861'),
('+918251013062', 'SSF4228424'),
('+919325092312', 'SSF2948694'),
('+918815190193', 'SSF5078059'),
('+918739937510', 'SSF3653354'),
('+919784585076', 'SSF3686208'),
('+916262659920', 'SID951374516589'),
('+917667842164', 'SID951375491794'),
('+917587425456', 'SID951374559757'),
('+918003734280', 'SID951375975073'),
('+916208754623', 'SID951373674378'),
('+919631910524', 'SSF3075296'),
('+919572498463', 'SSF5105966'),
('+919628600161', 'SSF5048052'),
('+917903235358', 'SID951374063326'),
('+919691701383', 'SID951373301448'),
('+919264289423', 'SID951372920801'),
('+919560195917', 'SID951375922611'),
('+919939762976', 'SID951375138119'),
('+919616252795', 'SSF3993310'),
('+918319692802', 'SID951375386316'),
('+919399841673', 'SSF2822369'),
('+917070805357', 'SSF3682754'),
('+917091432016', 'SSF3581786'),
('+918104488902', 'SSF3020475'),
('+918298234045', 'SSF2653496'),
('+918540863426', 'SSF3796842'),
('+918757499081', 'SSF3090200'),
('+918084819163', 'SSF3552137'),
('+918953511823', 'SSF3503746'),
('+919026357759', 'SSF2950613'),
('+918409496468', 'SSF4858355'),
('+918873880694', 'SSF5340721'),
('+919667535669', 'SSF3489464'),
('+917828677758', 'SID951374017172'),
('+918102742492', 'SSF3981395'),
('+919509985837', 'SSF4055470'),
('+916263741202', 'SSF3930244'),
('+917987870934', 'SSF4061054'),
('+917301601368', 'SSF4335352'),
('+917489654342', 'SSF4193498'),
('+917440918998', 'SSF4596886'),
('+919279141665', 'SSF3993762'),
('+917043802254', 'SSF4302639'),
('+919982819529', 'SSF2597458'),
('+917073609644', 'SSF2653124'),
('+917976320849', 'SSF3566842'),
('+919653402039', 'SSF3078868'),
('+919179226499', 'SID2125580679'),
('+917987388589', 'SSF4473598'),
('+919630573693', 'SSF4306041'),
('+919983525436', 'SSF4299026'),
('+919893991076', 'SSF4894370'),
('+918966975869', 'CID040814081'),
('+918319487954', 'SID951375164518'),
('+919784136350', 'SSF3465504'),
('+919691884715', 'SID951373368926'),
('+919519362795', 'SSF4714159'),
('+917737737184', 'SID951374601708'),
('+917547870686', 'SID951374694290'),
('+919479566229', 'SID951374046809'),
('+917739548282', 'SSF3252026'),
('+919771186033', 'SID2125014475'),
('+917697411998', 'CID040021304'),
('+919407159653', 'CID224900191'),
('+917723915515', 'SID951373366576'),
('+918120036358', 'SID951373346093'),
('+918828296941', 'SID951374741092'),
('+916260346613', 'SSF5104861'),
('+919209956976', 'SSF4672666'),
('+919334642404', 'SSF3120435'),
('+919131958821', 'SSF5214073'),
('+919009519127', 'SSF3345238'),
('+919131278290', 'CID261400002'),
('+919302570775', 'SSF4375228'),
('+919131963571', 'SSF4172479'),
('+918305160470', 'SSF2288343'),
('+916260625309', 'SID951376016656'),
('+916265436618', 'SSF4475531'),
('+917759076376', 'SSF4577739'),
('+917804997256', 'SSF4594698'),
('+917545088615', 'SSF4961504'),
('+918521661830', 'SSF3317833'),
('+918629936447', 'SSF3135489'),
('+919142498241', 'SSF3965378'),
('+916266671094', 'SSF4364299'),
('+916287025647', 'SID951374619179'),
('+917488667916', 'SSF3470607'),
('+917489198761', 'SSF4008139'),
('+919982036338', 'SSF2724400'),
('+919065427406', 'SID951374985751'),
('+919798713499', 'SSF4951624'),
('+916363932048', 'SSF3898801'),
('+917722922472', 'SSF3979343'),
('+919793468734', 'SSF3997231'),
('+919835023757', 'SSF4171445'),
('+919263789957', 'SID951374916463'),
('+916265232046', 'SSF3986547'),
('+917568224302', 'SID951374949065'),
('+918209636311', 'SSF4126419'),
('+917898372165', 'SSF3950781'),
('+917070366067', 'SID951372986206'),
('+919929032219', 'SID951374870491'),
('+916282321398', 'SID951373372619'),
('+919771955907', 'SID951375681091'),
('+918757387625', 'SID951375892601'),
('+919153466505', 'SID951376188930'),
('+919329085469', 'SSF2728614'),
('+918815426090', 'SSF2505967'),
('+919229040239', 'SSF3746153'),
('+919307342361', 'SSF4738433'),
('+919973844918', 'SSF4350367'),
('+916263114282', 'SID951374684732'),
('+919142499130', 'SID951375233988'),
('+919479183137', 'SID951374532328'),
('+916203234383', 'SSF2448114'),
('+919102561021', 'SSF2881865'),
('+916363041198', 'SSF3375487'),
('+917070967520', 'SSF4406817'),
('+917089097293', 'SSF3815106'),
('+917566418969', 'SSF5148510'),
('+917781924623', 'SSF4887921'),
('+918817323284', 'SSF4474569'),
('+918962139174', 'SSF3199285'),
('+918103038694', 'SSF4884376'),
('+918839666515', 'SSF4411954'),
('+919523288722', 'SSF4184438'),
('+916202758906', 'SSF3236671'),
('+919279199133', 'SSF4316475'),
('+918797012137', 'SID951373430829'),
('+917667099138', 'SID951374644614'),
('+919302624107', 'SSF4609560'),
('+918757295541', 'SSF5258117'),
('+916299687823', 'SID2125729747'),
('+918103292693', 'SSF4100123'),
('+919328382159', 'SSF2587032'),
('+917404844044', 'SSF3556353'),
('+918969669269', 'SSF3268047'),
('+916167694955', 'SID951373365481'),
('+918890336774', 'SSF3457027'),
('+917742098751', 'SID951376108484'),
('+917665781260', 'SSF3024519'),
('+916586406868', 'SID951375348008'),
('+919301392586', 'SID951373950961'),
('+919893718054', 'SID951373899903'),
('+919893632060', 'SID951375646987'),
('+918839099858', 'SSF2956770'),
('+916265324983', 'SSF3125981'),
('+918827374220', 'CID093401677'),
('+916264865879', 'CID204604483'),
('+917489555549', 'CID076606555'),
('+916264921154', 'SID951374489273'),
('+916268080184', 'SID951375201158'),
('+919608800805', 'SID951374231789'),
('+916207339343', 'SSF3455435'),
('+919302963286', 'CID062602213'),
('+917723866917', 'CID052912212'),
('+918965830062', 'SID951373484113'),
('+919174850443', 'CID044711914'),
('+918236015040', 'SID951375758990'),
('+919801635911', 'SID951373488768'),
('+919936548753', 'SSF4948243'),
('+918815057970', 'SID951373455193'),
('+917856059087', 'SID2125589312'),
('+917479815467', 'SID951373490550'),
('+916267014738', 'SSF2821879'),
('+916006929858', 'SSF2844900'),
('+919244162915', 'SSF2728615'),
('+919399306968', 'SSF2786953'),
('+919244816015', 'SSF2712746'),
('+916204894365', 'SSF3807026'),
('+916267724759', 'SSF4792664'),
('+916204178506', 'SSF4807967'),
('+917987105381', 'SSF4793503'),
('+917879522064', 'CID078101203'),
('+918757701454', 'SSF3364934'),
('+918959622328', 'SSF4562059'),
('+918400716226', 'SSF4056620'),
('+918081652093', 'SID951373998035'),
('+919199911021', 'SID2125435123'),
('+918640061958', 'SID951375234354'),
('+919570298951', 'SSF5325135'),
('+919572679942', 'SSF5067441'),
('+917000963595', 'SID951374469450'),
('+918860657184', 'SSF5055134'),
('+916379247574', 'SSF2428963'),
('+917485825680', 'SSF3968040'),
('+917974465739', 'SSF4927214'),
('+918305823973', 'SSF4276708'),
('+919234858946', 'SID2125069793'),
('+916392095632', 'SSF2749962'),
('+917828402607', 'SSF4987163'),
('+918271897428', 'SSF2806055'),
('+919928469867', 'SID951374879116'),
('+918871863497', 'CID040002822'),
('+919506025490', 'SID951374582592'),
('+916266688938', 'SID951373269773'),
('+918003125037', 'SSF4192790'),
('+919461742049', 'SID951374796547'),
('+917073224243', 'SSF3953885'),
('+917023272496', 'SSF4384514'),
('+918602088443', 'SSF3941481'),
('+919119249793', 'SSF4065571'),
('+919060447364', 'SSF4157470'),
('+919116767925', 'SSF4298905'),
('+916352071249', 'SSF3626536'),
('+918863072658', 'SID951374137011'),
('+918690094050', 'SSF3531940'),
('+919888006988', 'SID951374574222'),
('+918770604817', 'SSF3536889'),
('+919135296950', 'SID951374197409'),
('+919279111689', 'SID951374034785'),
('+916264777715', 'SID951375236861'),
('+919122273951', 'SID951374870334'),
('+918177047824', 'SSF2372822'),
('+916387399342', 'SSF3024283'),
('+919664466110', 'SSF3913665'),
('+919569917940', 'SSF3202561'),
('+918817435588', 'CID261400231'),
('+917225012753', 'SID951373131020'),
('+919083474008', 'SID951373044617'),
('+918757359439', 'CID139204159'),
('+918084156872', 'SID951374707913'),
('+917001265716', 'SSF4036125'),
('+917518333856', 'SSF3335715'),
('+918102800863', 'SSF3253502'),
('+918260795725', 'SSF3321936'),
('+918103105572', 'SSF3156881'),
('+919905493029', 'SSF3669461'),
('+919204444471', 'SSF4349633'),
('+919628648930', 'SSF2934223'),
('+919162244105', 'SSF3360771'),
('+919931160854', 'SSF3356567'),
('+919113363845', 'SSF4887765'),
('+916299651750', 'SSF5325197'),
('+917980518623', 'SSF5294425'),
('+919752564038', 'CID261400285'),
('+916203624112', 'SID951376040200'),
('+919111623397', 'SID951374757469'),
('+917000314293', 'SID2125694114'),
('+918839164829', 'CID261401786'),
('+917033655274', 'SSF2982498'),
('+917747865414', 'SSF4088931'),
('+918579016114', 'SSF2864970'),
('+918982718128', 'SID951375324046'),
('+919241446621', 'SSF2322068'),
('+917974308944', 'SID951373841046'),
('+917067052690', 'SID951374353102'),
('+917665743703', 'SSF3980069'),
('+918889320171', 'SID2125419882'),
('+919893244606', 'SID951374193693'),
('+916269324978', 'SSF2520464'),
('+917089065702', 'SSF2846874'),
('+919575275331', 'SID951376243574'),
('+916260177322', 'SSF4047164'),
('+916386713556', 'SSF3198177'),
('+918112680994', 'SSF3106854'),
('+918009395291', 'SSF3253195'),
('+919981610971', 'SSF2515351'),
('+917509045366', 'SID951373004547'),
('+918247019938', 'SID951374952642'),
('+918235648203', 'SID951375353214'),
('+919151665603', 'SSF5361598'),
('+919301229231', 'SID951374330054'),
('+918989623831', 'CID044711997'),
('+918815943231', 'SID2125626940'),
('+916263877335', 'SID951373618303'),
('+918554037890', 'SID951374942250'),
('+918528171255', 'SSF4701541'),
('+919244637565', 'SID951374341024'),
('+916266411797', 'SID951374649704'),
('+918696383775', 'SSF4192987'),
('+919131410890', 'SID951374290077'),
('+918103726508', 'SID951375294406'),
('+919691453962', 'SID951375758107'),
('+916267372923', 'SSF6003350'),
('+919865525789', 'CID044213361'),
('+919685654810', 'SSF4107508'),
('+917724849171', 'SID951375835827'),
('+917581023432', 'SID2125522724'),
('+919691575511', 'SID951374300866'),
('+918303878168', 'SID951373358418'),
('+916260885407', 'CID076608475'),
('+918817823204', 'CID129113033'),
('+916264142565', 'SID951373149652'),
('+917739630783', 'SID951375669177'),
('+916300463161', 'SID951376030491'),
('+917068149617', 'SSF4566518'),
('+918305761633', 'SSF4597403'),
('+918817774977', 'SSF4580736'),
('+919608690716', 'SSF4841543'),
('+919343498648', 'SSF4414914'),
('+916265835489', 'SSF4575938'),
('+919244995112', 'SSF4471530'),
('+918578973123', 'SSF5257866'),
('+919304384850', 'SSF5212855'),
('+917050843379', 'SID951374644468'),
('+919661307755', 'SID951375784421'),
('+919621658756', 'SSF4850234'),
('+917510004792', 'SSF2683257'),
('+917000530972', 'SSF4717185'),
('+917489047862', 'SSF4173040'),
('+919297696758', 'SSF4212455'),
('+919142542461', 'SID951376003066'),
('+919173125490', 'SSF4204464'),
('+919263944391', 'SID951373535422'),
('+917441143510', 'SSF3503587'),
('+918294294165', 'SSF4699075'),
('+916204736705', 'SSF5320805'),
('+917903285013', 'SSF5029533'),
('+919669380658', 'SID2125338017'),
('+916266206083', 'SID2125559760'),
('+916269565807', 'SID951375946022'),
('+917723029921', 'SID951374937613'),
('+917493948272', 'SSF4573790'),
('+918382085875', 'SSF4063107'),
('+918349415590', 'SID21896'),
('+919993444252', 'SID951374881865'),
('+917321031839', 'SID951374676609'),
('+917974495559', 'SID227'),
('+919799182470', 'SID951374592521'),
('+917568292048', 'SSF3456722'),
('+917340158113', 'SSF3204596'),
('+919571821490', 'SID951375050229'),
('+919340266725', 'SID951373228516'),
('+916205932503', 'SID951374704334'),
('+919691184556', 'SID951374699748'),
('+919525748906', 'SSF2546884'),
('+917761975390', 'SSF5001382'),
('+917261096278', 'SSF5178290'),
('+919850342738', 'SSF4062076'),
('+919065697809', 'SSF4719550'),
('+918629920206', 'CID076607378'),
('+919798645147', 'CID139303979'),
('+916268521407', 'SID951375449692'),
('+916267080751', 'SID951375069814'),
('+919522491976', 'SID951374804669'),
('+917879190933', 'SID951376016666'),
('+917654005525', 'SSF2567787'),
('+916387782837', 'SSF4555463'),
('+917736748393', 'SSF4524204'),
('+917814795616', 'SSF4555270'),
('+917678816603', 'SSF4523935'),
('+918933899162', 'SSF4528938'),
('+918009765908', 'SSF4528018'),
('+918756038703', 'SSF4527569'),
('+918405846536', 'SSF4342692'),
('+919263479911', 'SSF4448863'),
('+919263018689', 'SSF3292739'),
('+919343362426', 'SSF3448974'),
('+919570270375', 'SSF5385874'),
('+919570527985', 'SSF5343328'),
('+918817380208', 'SSF4905905'),
('+918770892754', 'SSF3067643'),
('+919031222013', 'SSF4319934'),
('+917091664861', 'SSF3741070'),
('+917023668112', 'SSF4627046'),
('+919302253146', 'SSF4297882'),
('+919617015111', 'SSF4509171'),
('+917974431968', 'SSF4270786'),
('+918102652143', 'SID951372964232'),
('+919131695612', 'SID951375555239'),
('+919672113367', 'SSF3926552'),
('+918871689423', 'SSF4071938'),
('+919936545451', 'SID951374883852'),
('+916204546649', 'SID951373274396'),
('+918890885224', 'SID951374761832'),
('+917988756585', 'SID951376028121'),
('+917722981367', 'SID951372895292'),
('+919691861817', 'SID951374356198'),
('+918529872977', 'SID951375782777'),
('+919893462232', 'SID951375273829'),
('+919827751674', 'SID951376147694'),
('+917000827908', 'SSF5391616'),
('+917987266520', 'SSF3160809'),
('+919098040103', 'SSF3251051'),
('+919949400350', 'SSF5052665'),
('+918603887974', 'SID951375260336'),
('+919109238762', 'SSF3310771'),
('+919009129010', 'SID951375017466'),
('+919584707413', 'SID951373161243'),
('+917354245436', 'SID2125634638'),
('+918764465181', 'SID951375228231'),
('+918696339638', 'SID951375940223'),
('+919662554188', 'SID951375018954'),
('+917828381069', 'SID951374637367'),
('+918252213686', 'SSF5002549'),
('+917897355770', 'SID951374564408'),
('+919340694801', 'SID951373898831'),
('+919523792072', 'SSF2578645'),
('+919102480204', 'SSF2968867'),
('+917478160453', 'SID2125678110'),
('+919279846283', 'SID951376147806'),
('+917804867526', 'SSF3436045'),
('+917489898101', 'SSF4690938'),
('+919622132548', 'SSF5262059'),
('+919771657526', 'SSF5379281'),
('+917050411569', 'SID951374568574'),
('+917878524080', 'SID951374475151'),
('+917766879889', 'SID951375787695'),
('+917408749467', 'SSF2724428'),
('+919589271036', 'SSF2390145'),
('+918252416157', 'SSF4537167'),
('+918737946282', 'SSF3090282'),
('+918009607105', 'SSF4641862'),
('+919801321783', 'SID951376044262'),
('+919198218413', 'SSF4589445'),
('+919153471014', 'SSF4492967'),
('+918789848282', 'SID2125157713'),
('+917489265154', 'SID951374126175'),
('+919631823938', 'SSF2890472'),
('+919234814025', 'SSF3025748'),
('+919301363783', 'SSF4494355'),
('+919334261902', 'SID951375574258'),
('+919341690340', 'SID951375032715'),
('+919303375416', 'SID2125547387'),
('+918560930118', 'SSF3002844'),
('+918769572315', 'SSF4253066'),
('+919983412127', 'SSF4002392'),
('+917067964939', 'SID951375257184'),
('+918770769407', 'SID951373197434'),
('+919695787673', 'SID951375177596'),
('+917002695357', 'SSF3097163'),
('+919244169373', 'SSF4626372'),
('+919691965179', 'SSF2956717'),
('+919399189133', 'SSF4898907'),
('+916266028377', 'SID951372988292'),
('+916267638536', 'SID2125743564'),
('+919179458032', 'SID2125082815'),
('+916201918164', 'SID951374362298'),
('+916264135437', 'SSF2783233'),
('+917970052148', 'SSF2351763'),
('+917458820251', 'SID951375211463'),
('+919303268136', 'SSF2323622'),
('+919771936634', 'SID951376195280'),
('+919244846955', 'SSF2783234'),
('+919302735543', 'SSF3428360'),
('+919301911518', 'SSF4075765'),
('+916206908997', 'SSF2805460'),
('+917488602582', 'SSF3597111'),
('+919955707403', 'SSF2903843'),
('+917067569383', 'SID2125724476'),
('+917620020975', 'SSF3187308'),
('+919939884215', 'SID951374978181'),
('+918817095271', 'CID054002588'),
('+919302221789', 'SID951375021787'),
('+919301713959', 'SID951373361869'),
('+919644538149', 'CID207302611'),
('+917999884596', 'CID050408580'),
('+918840947859', 'SID951375063464'),
('+917770994809', 'SID2125496955'),
('+917692002333', 'CID040402136'),
('+916299208210', 'SID951374133055'),
('+919552886655', 'SID951374601416'),
('+919721748885', 'SSF4667010'),
('+918989623817', 'CID052902612'),
('+919238902779', 'SSF4883109'),
('+919587735014', 'SID951375975291'),
('+918305842483', 'SID951375595973'),
('+917869841251', 'CID081102854'),
('+919608045661', 'SID951373178673'),
('+917987718879', 'SID951373284769'),
('+918319467360', 'SID951374129440'),
('+919934324241', 'SID951374336511'),
('+916268438944', 'SSF2902647'),
('+919343928894', 'SSF2786954'),
('+916390292068', 'SSF3873227'),
('+917292997577', 'SSF4721847'),
('+918103899269', 'SSF3054826'),
('+919102890441', 'SSF3564615'),
('+919608134997', 'SSF4962747'),
('+919244957678', 'SSF4058606'),
('+918982966744', 'CID069700838'),
('+919631985424', 'CID171504835'),
('+916266275365', 'SID2125517874'),
('+919241331958', 'SSF4438527'),
('+919302370806', 'SID951374555730'),
('+919570919371', 'SSF5385706'),
('+918320924170', 'SID951375521682'),
('+919770865149', 'SID951375074912'),
('+919516968014', 'CID213102295'),
('+916388181195', 'SID951374386031'),
('+919371610680', 'SSF4717050'),
('+918960281938', 'SID951374446299'),
('+919525082487', 'SID951374981515'),
('+917600943363', 'SID951376154110'),
('+917061037549', 'CID139300819'),
('+916268855740', 'SID951376016653'),
('+919893313190', 'SID951374370511'),
('+917722975385', 'SID951373551115'),
('+916200810366', 'SID951373579515'),
('+919572997137', 'SID951375601571'),
('+916207481334', 'SID2125618018'),
('+916378224316', 'SSF3676504'),
('+919304326261', 'SID951373105538'),
('+919329557226', 'SID951373256832'),
('+917987193425', 'SID2125134614'),
('+918207623144', 'SID951375374882'),
('+916267401123', 'SSF2695954'),
('+918953523006', 'SSF2809121'),
('+916204646012', 'SSF5040156'),
('+917765891936', 'SSF3756413'),
('+918103223472', 'SSF3298168'),
('+919135757253', 'SSF3154925'),
('+919238850539', 'SSF3240771'),
('+917610464914', 'SID2125646405'),
('+918815178525', 'SID951373315373'),
('+916260578235', 'SID951373595229'),
('+916299801254', 'SSF3935094'),
('+917029054527', 'SSF4637719'),
('+917366830719', 'SSF3511009'),
('+918423738382', 'SSF2969971'),
('+919889910349', 'SSF4365266'),
('+919601473950', 'SSF3123848'),
('+917323862998', 'SSF5473146'),
('+919302446746', 'CID050404319'),
('+916263177334', 'SID951372926752'),
('+918869804520', 'SSF4895075'),
('+917676832068', 'SSF3049453'),
('+918962344787', 'SID951374233954'),
('+919279074198', 'SSF4569328'),
('+919977797831', 'SID2125598112'),
('+917644925948', 'CID211202363'),
('+916263245857', 'SID951375144372'),
('+919244936061', 'CID191802182'),
('+918107394019', 'SID951375883890'),
('+918302371412', 'SSF3355855'),
('+916267977589', 'SID951372874321'),
('+917354940879', 'SID2125114151'),
('+918604264157', 'SID951373107315'),
('+919669715052', 'SID951375874235'),
('+919301478115', 'SID951375810108'),
('+919691168573', 'SID951375570095'),
('+917861819768', 'SID2125078652'),
('+917694003122', 'SID951376186650'),
('+918109212033', 'SSF2879775'),
('+918287359934', 'SSF2335237'),
('+918602412648', 'SID951374946157'),
('+917693053481', 'SSF4937825'),
('+919770740109', 'SSF3925810'),
('+917000665428', 'SSF3375249'),
('+917646823538', 'SID951374775589'),
('+917879070135', 'SID951373417454'),
('+919685325499', 'CID135108050'),
('+919340211524', 'SID951374038356'),
('+918851091831', 'SID951373847226'),
('+916264658574', 'SID951374182301'),
('+918874028603', 'SSF4273623'),
('+919770791227', 'SID2125561087'),
('+919801012593', 'SID951373133334'),
('+919304071579', 'SID951374042487'),
('+918827422025', 'CID040021437'),
('+919713475643', 'SID951375404720'),
('+918120045827', 'SSF4703784'),
('+919142795946', 'SSF5105184'),
('+919226367104', 'SSF3137203'),
('+919506496890', 'SSF5025591'),
('+919661745459', 'SSF4851526'),
('+917692969814', 'SSF4085721'),
('+916204140282', 'SID951374893097'),
('+916265517642', 'SSF4711541'),
('+917620274805', 'SSF4596270'),
('+918529200365', 'SSF3951661'),
('+919340272801', 'SSF4573495'),
('+918770789920', 'CID191804062'),
('+917850832946', 'SSF4436842'),
('+917209652887', 'SSF4215008'),
('+918619644278', 'SSF3976214'),
('+919798306701', 'SID951374869476'),
('+918815897454', 'SID951372907790'),
('+918292636864', 'SSF5024863'),
('+916206911127', 'SID951372834559'),
('+916260808654', 'SID951375456857'),
('+917976772233', 'SID951374964021'),
('+918619496801', 'SID951374964015'),
('+918890627645', 'SID951375709437'),
('+918756418887', 'SID951374200898'),
('+919155992601', 'SID951375523787'),
('+919256354160', 'SID951375883552'),
('+916261784216', 'SID951373699773'),
('+916895892765', 'SID951372902232'),
('+916209252313', 'SID951373364052'),
('+917250521488', 'SID951375050849'),
('+917073498512', 'SID951375277699'),
('+917489700743', 'SSF4167317'),
('+918563247964', 'SID951375124509'),
('+918528561553', 'SID951374651810'),
('+919024011170', 'SID951374688362'),
('+919098428366', 'SID951372938014'),
('+919798538081', 'SID951374239254'),
('+917340092959', 'SID951374997179'),
('+918949077413', 'SID951375047957'),
('+918233410271', 'SID951374796409'),
('+916376014356', 'SID951376038382'),
('+917033735421', 'SID951374572006'),
('+918696578040', 'SID951375048046'),
('+919256154543', 'SID951375420495'),
('+917665077176', 'SID951375337012'),
('+919567426345', 'SID951375755137'),
('+916265943072', 'SID951374142763'),
('+919834973043', 'SID951374975086'),
('+918347958732', 'SID951376126846'),
('+916264160593', 'SSF3113928'),
('+918540021485', 'SSF3006451'),
('+917024315244', 'SID2125286594'),
('+919340719349', 'SID951372879700'),
('+919304711900', 'SID951374763823'),
('+916264106639', 'SSF4364293'),
('+917033779072', 'SSF4698032'),
('+917737562850', 'SSF4773921'),
('+918409532299', 'SSF4709679'),
('+918349408219', 'SSF4850418'),
('+919343049778', 'SSF4850269'),
('+919636655780', 'SSF4463707'),
('+917633012567', 'SSF4207862'),
('+917073600495', 'SID951374442239'),
('+917441152028', 'SSF4395103'),
('+918839905307', 'SID2125553317'),
('+919065338486', 'SID951375613339'),
('+919399998904', 'SID951374149891'),
('+919669507488', 'SID951373324986'),
('+919827195716', 'SID951374057869'),
('+919631153526', 'SID951373363493'),
('+916263597236', 'SID951373568191'),
('+916352708161', 'SSF3769209'),
('+917878186347', 'SID951375640965'),
('+917070900412', 'SID951374845654'),
('+917048714039', 'SSF3423654'),
('+918875632356', 'SID951374329728'),
('+918854006425', 'SID951375130136'),
('+918690947308', 'SID951374169969'),
('+919660192655', 'SSF3397278'),
('+919929825218', 'SID951373977265'),
('+919355422576', 'SID951375485604'),
('+919950149877', 'SID951375778550'),
('+919358372401', 'SID951375367905'),
('+917665414167', 'SID951375153247'),
('+917974322427', 'SID951375225158'),
('+917489594435', 'SID951375043450'),
('+917806017715', 'SID951373898562'),
('+917649764812', 'SID951374307507'),
('+918306892437', 'SID951375105782'),
('+919109204911', 'SID951373355425'),
('+919351921506', 'SID951375532820'),
('+919352773905', 'SID951375156143'),
('+918409348234', 'SID951374343445'),
('+916378105637', 'SID951373949449'),
('+917877945172', 'SID951375859023'),
('+917426842406', 'SID951375750930'),
('+917014010364', 'SID951375933713'),
('+918107292699', 'SID951375255313'),
('+919799813472', 'SID951375482094'),
('+916265329970', 'CID216401344'),
('+918959135309', 'CID081112077'),
('+917879243479', 'SID951374247728'),
('+919575959688', 'SID2125654547'),
('+919770836382', 'SSF2385933'),
('+916269307928', 'SSF3652835'),
('+919098678750', 'CID061214118'),
('+919753737058', 'CID044703259'),
('+919644826367', 'CID076605783'),
('+918823831320', 'CID056602999'),
('+916263025160', 'SSF2814638'),
('+917209758252', 'SID951376154117'),
('+918102162930', 'SID951373514752'),
('+918287557167', 'SSF2333505'),
('+918085540874', 'CID061100863'),
('+917321880912', 'SID951375099343'),
('+919102485751', 'SSF4930740'),
('+917389692459', 'SSF4683393'),
('+918310974735', 'SID951373971946'),
('+919128745262', 'SID951375019771'),
('+919462055408', 'SSF4787856'),
('+919329330814', 'SID951374528903'),
('+919973396656', 'SSF5208684'),
('+917000938511', 'CID239800737'),
('+917856981288', 'SID951373887461'),
('+918305221857', 'SID951373175128'),
('+917987007983', 'SSF4314531'),
('+918889388736', 'SSF4051312'),
('+916377568420', 'SSF3593936'),
('+917999273850', 'SID951375160986'),
('+918434703624', 'SID951373636062'),
('+918825129546', 'SID951376157224'),
('+919102033683', 'SID951373488074'),
('+916268726021', 'SSF4550712'),
('+917739778260', 'SSF4781940'),
('+916363476809', 'SID951374914989'),
('+917899457087', 'SID951374773741'),
('+917484884433', 'SID951375983812'),
('+918087658907', 'SSF4696441'),
('+919575877409', 'SSF4449951'),
('+919574536849', 'SSF4531389'),
('+917742774201', 'SSF4276254'),
('+917723880793', 'SID951375385519'),
('+919234179952', 'SSF4304939'),
('+919770535607', 'SID2125033974'),
('+917372046506', 'SSF3441448'),
('+917340635099', 'SSF4336562'),
('+918852085031', 'SSF2769317'),
('+919875847822', 'SID951374850111'),
('+917839978321', 'SID951375431791'),
('+918261832524', 'SSF4943157'),
('+916265332195', 'SID951373775670'),
('+918870887312', 'SSF3932147'),
('+916202015052', 'SID951373723769'),
('+916201250699', 'SSF4596377'),
('+918235188106', 'SID951374204262'),
('+917327964463', 'SID951375682916'),
('+918889906530', 'SID951373796173'),
('+917903678858', 'SID951374539169'),
('+918409922973', 'SID951375946811'),
('+919693337824', 'SID951375626042'),
('+918092841281', 'SSF5096598'),
('+918225065912', 'SSF4744451'),
('+918294696246', 'SID951375599068'),
('+916266114613', 'SID2125750138'),
('+916265545756', 'SID951373291257'),
('+918174801363', 'SSF4821530'),
('+919234522019', 'SSF5276835'),
('+916266827415', 'SID2125758108'),
('+919771742978', 'SSF4608847'),
('+918471033787', 'SID951374503777'),
('+918651283518', 'SSF3921425'),
('+919926655973', 'SID951372884386'),
('+919713260558', 'SSF4446089'),
('+919783628011', 'SSF4335032'),
('+919571119248', 'SSF2804743'),
('+917805052933', 'SID951374126759'),
('+918340481598', 'SID951375027544'),
('+916205664377', 'SSF5080641'),
('+919198005582', 'SSF5025760'),
('+917848087594', 'CID076606662'),
('+917250944843', 'SID951373406363'),
('+918292369570', 'SID951374805536'),
('+916201297792', 'SSF4941527'),
('+917999714466', 'SSF4979525'),
('+918434186584', 'SID951372794055'),
('+919234076686', 'SID951373090816'),
('+917761886901', 'SSF4170001'),
('+918349575212', 'SSF4198770'),
('+916376134435', 'SID951375994994'),
('+917805964772', 'SSF4439536'),
('+918780735929', 'SSF4295451'),
('+919303207303', 'SID951376195809'),
('+916268889717', 'SID951374386691'),
('+918817019227', 'SID951374185901'),
('+919174922384', 'SID951374132718'),
('+916262531524', 'SID951375432739'),
('+918815803269', 'SSF2343404'),
('+919753345499', 'SSF4993665'),
('+919644131239', 'SID2125285773'),
('+916265889927', 'CID076605665'),
('+919977836905', 'SID951374911350'),
('+918827080938', 'SID2125600006'),
('+919981779192', 'CID084607138'),
('+916266922622', 'CID213103171'),
('+919801862236', 'SID951375687026'),
('+919301373860', 'SID951375477753'),
('+919340896249', 'SSF2749809'),
('+917368860166', 'SID951372899336'),
('+917723973518', 'SSF4885125'),
('+917805933762', 'SID951373170220'),
('+917000665372', 'SID951375401119'),
('+918294801144', 'SSF5062281'),
('+918102869092', 'SID951373081285'),
('+916264027644', 'SID2125453024'),
('+916201633913', 'SSF2573678'),
('+918627854602', 'SSF4973516'),
('+918009015121', 'SSF4929449'),
('+919525889352', 'SSF4784079'),
('+918294296272', 'SSF4990885'),
('+919692102881', 'SID951374340323'),
('+917739029749', 'SSF4334714'),
('+918651870352', 'SSF2865059'),
('+916204312495', 'SSF2362662'),
('+919399501734', 'CID191802180'),
('+917389280143', 'SID951373662284'),
('+919546053632', 'SID951374971087'),
('+917903169316', 'SID951374959856'),
('+917319779803', 'SSF4875556'),
('+919691419944', 'SID951374035146'),
('+919165237031', 'SID2125735431'),
('+917479697642', 'SSF5202848'),
('+917634824456', 'CID951376205486'),
('+919515104430', 'SSF4988068'),
('+919525969247', 'SSF2450980'),
('+916268761337', 'SID951375033965'),
('+917023781639', 'SSF2833528'),
('+919799857980', 'SID951375214808'),
('+916267165101', 'SID951374706418'),
('+917354224624', 'SID951372900036'),
('+917024861060', 'SSF2910825'),
('+919918208126', 'SSF4271177'),
('+916265007097', 'SID951373198169'),
('+919713635639', 'SID951375777300'),
('+918103567979', 'CID219301510'),
('+918223942261', 'CID174606263'),
('+919784380266', 'SID951374742147'),
('+917646861149', 'SSF4926121'),
('+919302411439', 'SID951374247364'),
('+919238599546', 'SSF4088619'),
('+916265467415', 'SID951375530059'),
('+916264066658', 'SID951375217302'),
('+917067249726', 'SID951374578605'),
('+917488474181', 'SID951374789089'),
('+917481820411', 'SID951375371603'),
('+916200956448', 'SSF5177073'),
('+919691224347', 'SSF5190060'),
('+919731919326', 'SSF2991039'),
('+919834653217', 'SSF4955269'),
('+919793519084', 'SSF4979870'),
('+918849481192', 'SID951374142663'),
('+919131810199', 'CID207402332'),
('+917982854448', 'SSF5261911'),
('+917012224950', 'SID951373585202'),
('+918084922634', 'SID951374575974'),
('+916206627257', 'SSF4768016'),
('+918824784524', 'SSF4482576'),
('+917737789917', 'SSF2701379'),
('+919898989895', 'SID951375535028'),
('+917061658496', 'SID2125308064'),
('+919343294599', 'SID951375956950'),
('+917488152871', 'SSF2322435'),
('+919905381528', 'SSF5084567'),
('+919661355366', 'SSF4854216'),
('+918293296472', 'SSF4954507'),
('+919234452224', 'SSF4654112'),
('+919770196393', 'CID207402247'),
('+918305880745', 'SID951374552828'),
('+919929938318', 'SID951374538676'),
('+917804075040', 'CID076608715'),
('+917805968601', 'CID213100251'),
('+918003918962', 'SID951374869460'),
('+917909636747', 'SID951376107469'),
('+919165180220', 'SSF2367069'),
('+916260254041', 'SID951374011965'),
('+917828123661', 'SID2125300292'),
('+919009353062', 'CID129109745'),
('+919340048569', 'SID951375267432'),
('+916264264536', 'SID951374579518'),
('+919343015480', 'SID951374350878'),
('+919709728497', 'SID951374614600'),
('+916268894211', 'SSF4998280'),
('+919201392272', 'SID951373269951'),
('+917566265226', 'SSF4926201'),
('+917545000956', 'SSF4862770'),
('+919201477972', 'SID951376183612'),
('+918407921949', 'SSF4949601'),
('+919263775881', 'SSF5221124'),
('+919709925932', 'SSF4206726'),
('+918003066803', 'SSF3751314'),
('+918516899198', 'SID951374245545'),
('+919399545286', 'SID951374525175'),
('+916263084932', 'SID951375087049'),
('+916260772278', 'SID951374809697'),
('+918875970668', 'SSF4590229'),
('+917247269349', 'SSF5202432'),
('+916267104371', 'SSF3838027'),
('+919244515674', 'SSF4637355'),
('+919713903334', 'SID951373638494'),
('+918815605801', 'SID951375146136'),
('+918251025459', 'SID951374597156'),
('+919754080371', 'SID951373547233'),
('+917509885423', 'SID951373119299'),
('+917896541339', 'CID076200435'),
('+919522910431', 'SID951372921446'),
('+917024736350', 'CID044309095'),
('+919302634228', 'SID42286'),
('+916268983531', 'SID951373426356'),
('+916205636927', 'SID951373089180'),
('+917070374065', 'SID951375431379'),
('+918305070367', 'SSF5374476'),
('+918084838648', 'SID951373840860'),
('+917247870460', 'SSF5485497'),
('+918959059803', 'CID191800391'),
('+919525248669', 'SID951375791616'),
('+916204957565', 'SSF4736779'),
('+919279732358', 'SSF4569287'),
('+919098268378', 'SSF4265392'),
('+919693704508', 'SID951373105374'),
('+919174681094', 'SID951375211551'),
('+919778546428', 'SID951373347098'),
('+919199942016', 'SID951374303311'),
('+919617796673', 'SID951375061490'),
('+917985106090', 'SSF3922647'),
('+918003066887', 'SID951376110027'),
('+919770350243', 'SID951376055214'),
('+919031155158', 'SID951376203502'),
('+919555903162', 'SSF5057784'),
('+919153661158', 'SSF5009011'),
('+919337102798', 'SSF5078867'),
('+916260960890', 'SID951375353065'),
('+917879351083', 'SID951373659867'),
('+917049072997', 'SID2125084285'),
('+917725885659', 'SID951372797190'),
('+917905006980', 'SID951375001528'),
('+919131772158', 'SID951375042861'),
('+917974404329', 'SID2125261210'),
('+918815075704', 'SID2125728265'),
('+919340019932', 'SID951373775547'),
('+918809823224', 'SSF5160832'),
('+919302217664', 'SID2125362158'),
('+919303866283', 'SID951373912959'),
('+919199537404', 'SID2125631720'),
('+917693913093', 'CID219405963'),
('+916200822173', 'SID951375439326'),
('+916563497677', 'SID2125632196'),
('+918102629941', 'SID951374390389'),
('+918340734640', 'SID951373903613'),
('+919263308657', 'SID951373209291'),
('+919691835013', 'SSF4364437'),
('+919752157412', 'SID2125068958'),
('+917023487831', 'SID951373949452'),
('+917240711531', 'SID951373977778'),
('+919214154225', 'SID951375136519'),
('+917700862476', 'SID951373524595'),
('+919116301663', 'SID951375171309'),
('+918102036541', 'CID211203880'),
('+918824118697', 'SID951375859318'),
('+918085187637', 'SID2125282111'),
('+917804939320', 'SID2125257372'),
('+918603449932', 'SID951374651910'),
('+918319878610', 'CID207401950'),
('+917974845420', 'SSF4905405'),
('+917492850035', 'SSF4945584'),
('+919691054252', 'SSF5287663'),
('+919399739575', 'SSF4904704'),
('+919166376167', 'SID951375203528'),
('+918815362937', 'CID076601763'),
('+918817051490', 'SID951374041132'),
('+919238250802', 'SSF4423126'),
('+917903205421', 'SID951375236785'),
('+919352208967', 'SID951374688368'),
('+919993720127', 'SID951372900613'),
('+917070051897', 'SID951374855376'),
('+918815829916', 'CID207302873'),
('+918789421557', 'SID951375100566'),
('+917566553266', 'SID2125085963'),
('+916377620937', 'SID951374652624'),
('+918982568363', 'CID213100199'),
('+918889710279', 'SID2125138143'),
('+919771625343', 'SID951375497124'),
('+919238261219', 'SID2125445177'),
('+918269406991', 'SID951376138428'),
('+919516913177', 'SID951374909214'),
('+919244142552', 'SID951375237443'),
('+919340369559', 'SID2125236639'),
('+919285449058', 'SID2125603382'),
('+917482941838', 'SID951374500951'),
('+919131301826', 'SID951373662278'),
('+918948078274', 'SSF3214290'),
('+917275268499', 'SSF4599136'),
('+917489248378', 'CID207300772'),
('+919201362865', 'CID219406458'),
('+919201065435', 'SSF5183182')
) AS m(contact_to, uid)
WHERE s.contact_to = m.contact_to;
""")

162390

In [28]:
unique_data['Phone Numeber'][3188:3190]

3192    9801809893
3193    8252906593
Name: Phone Numeber, dtype: int64

In [21]:
for index, row in unique_data.iterrows():
    print(index)
    query_sql(f"""
    UPDATE spandana_sphoorty_data
SET uid = '{row['BorrowerCode']}'
WHERE contact_to = '+91{row['Phone Numeber']}';
""")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188

KeyboardInterrupt:

In [ ]:
query_sql("""
UPDATE spandana_sphoorty_data
SET uid = SSF3552604
WHERE contact_to = '+919649887823' 
  AND meta_data->>'Name' = 'मेनका';
""")

7

In [35]:
db_data[db_data['phone'].isin(df[df['count'] > 1]['Phone Numeber'])][['phone','meta_data']].to_csv("db_data.csv",index=False)

In [19]:
from database.dependencies import DB_DEPENDENCY

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import (
    Column, Integer, BigInteger, String, Text, Float, Boolean, JSON, DateTime, Numeric, func, text
)
import sqlalchemy.dialects.postgresql as pg

Base = declarative_base()

class SpandanaSphoortyData(Base):
    __tablename__ = 'spandana_sphoorty_data'
    __table_args__ = {"schema": "public"}

    s_no = Column(Integer, primary_key=True, autoincrement=True)
    json_data = Column(pg.JSONB)
    disposition = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=text("(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')"))
    language = Column(Text)
    is_disposition_available = Column(Boolean, server_default=text('false'))
    transcript = Column(Text)
    is_transcript_available = Column(Boolean, server_default=text('false'))
    contact_to = Column(Text)
    contact_from = Column(Text)
    direction = Column(Text)
    call_start_ts = Column(Float)
    call_end_ts = Column(Float)
    chat = Column(pg.JSONB)
    provider = Column(Text)
    call_id = Column(Text)
    agent_id = Column(Text)
    duration = Column(Float)
    meta_data = Column(pg.JSONB)
    recording = Column(Text)
    model = Column(Text)
    cost = Column(Float)
    is_duplicate = Column(Boolean, server_default=text('false'))
    campaign_id = Column(Integer)
    session_id = Column(String)
    call_status = Column(String)
    error_message = Column(String)
    uid = Column(String)

class SpandanaDebtCollectionReport(Base):
    __tablename__ = 'spandana_debt_collection_report'
    __table_args__ = {"schema": "public"}

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    import_batch_id = Column(pg.UUID, server_default=text('gen_random_uuid()'), nullable=False)
    source_file_name = Column(String(255), nullable=False)
    imported_at = Column(DateTime(timezone=True), server_default=text("(now() AT TIME ZONE 'Asia/Kolkata')"), nullable=False)
    borrower_code = Column(String(100), nullable=False)
    vendor_name = Column(String(255))
    connected_status = Column(String(100))
    recording_link = Column(Text)
    duration_seconds = Column(Integer)
    disposition = Column(String(255))
    language = Column(String(100))
    zone = Column(String(100))
    svp_state = Column(String(100))
    region = Column(String(100))
    area = Column(String(100))
    cluster = Column(String(100))
    branch_code = Column(String(50))
    branch_name = Column(String(255))
    repayment_frequency = Column(String(100))
    center_id = Column(String(100))
    center_name = Column(String(255))
    group_name = Column(String(255))
    village_name = Column(String(255))
    borrower_name = Column(String(255))
    spouse_name = Column(String(255))
    phone_number = Column(String(50))
    no_of_loans = Column(Integer)
    pos = Column(Numeric(18, 2))
    od = Column(Numeric(18, 2))
    emi = Column(Numeric(18, 2))
    dpd = Column(Integer)
    last_repayment_paid_date = Column(String(50))
    npa_date_as_fimo = Column(String(50))
    old_new = Column(String(50))
    alternate_mobile_number = Column(String(50))
    phase = Column(String(100))
    created_at = Column(DateTime(timezone=True), server_default=text("(now() AT TIME ZONE 'Asia/Kolkata')"), nullable=False)

2026-02-17 15:05:44.250 | INFO     | database.session:<module>:50 - Database connected successfully
/var/folders/bc/5y0zpp3j3nnftxfjwv0njxj40000gn/T/ipykernel_14392/1799144677.py:9: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [21]:
# Use explicit Session object creation instead of get_db()/async_generator for sync scripts/notebooks.
# This avoids the TypeError due to 'async_generator' not being an iterator.

from sqlalchemy.orm import sessionmaker
from database.session import engine  # Adjust import path if needed
from datetime import datetime

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# dummy_records = [
#     SpandanaDebtCollectionReport(
#         import_batch_id=None,  # UUID generated in DB
#         source_file_name="dummy_file1.csv",
#         borrower_code="BCODE001",
#         vendor_name="Vendor1",
#         connected_status="Connected",
#         recording_link=None,
#         duration_seconds=120,
#         disposition="Disposition1",
#         language="en",
#         zone="ZoneA",
#         svp_state="StateA",
#         region="RegionA",
#         area="AreaA",
#         cluster="ClusterA",
#         branch_code="BR001",
#         branch_name="Branch One",
#         repayment_frequency="Monthly",
#         center_id="CEN001",
#         center_name="Center One",
#         group_name="Group1",
#         village_name="Village1",
#         borrower_name="Borrower One",
#         spouse_name="Spouse One",
#         phone_number="9000000001",
#         no_of_loans=2,
#         pos=1000.00,
#         od=50.00,
#         emi=500.00,
#         dpd=0,
#         last_repayment_paid_date="2024-01-01",
#         npa_date_as_fimo="",
#         old_new="Old",
#         alternate_mobile_number="9000000002",
#         phase="Phase 1",
#     ),
#     SpandanaDebtCollectionReport(
#         import_batch_id=None,
#         source_file_name="dummy_file2.csv",
#         borrower_code="BCODE002",
#         vendor_name="Vendor2",
#         connected_status="Missed",
#         recording_link=None,
#         duration_seconds=60,
#         disposition="Disposition2",
#         language="hi",
#         zone="ZoneB",
#         svp_state="StateB",
#         region="RegionB",
#         area="AreaB",
#         cluster="ClusterB",
#         branch_code="BR002",
#         branch_name="Branch Two",
#         repayment_frequency="Weekly",
#         center_id="CEN002",
#         center_name="Center Two",
#         group_name="Group2",
#         village_name="Village2",
#         borrower_name="Borrower Two",
#         spouse_name="Spouse Two",
#         phone_number="9000000003",
#         no_of_loans=1,
#         pos=2000.00,
#         od=0.00,
#         emi=900.00,
#         dpd=1,
#         last_repayment_paid_date="2024-02-01",
#         npa_date_as_fimo="",
#         old_new="New",
#         alternate_mobile_number="9000000004",
#         phase="Phase 2",
#     ),
#     SpandanaDebtCollectionReport(
#         import_batch_id=None,
#         source_file_name="dummy_file3.csv",
#         borrower_code="BCODE003",
#         vendor_name="Vendor3",
#         connected_status="Connected",
#         recording_link=None,
#         duration_seconds=90,
#         disposition="Disposition3",
#         language="en",
#         zone="ZoneC",
#         svp_state="StateC",
#         region="RegionC",
#         area="AreaC",
#         cluster="ClusterC",
#         branch_code="BR003",
#         branch_name="Branch Three",
#         repayment_frequency="Monthly",
#         center_id="CEN003",
#         center_name="Center Three",
#         group_name="Group3",
#         village_name="Village3",
#         borrower_name="Borrower Three",
#         spouse_name="Spouse Three",
#         phone_number="9000000005",
#         no_of_loans=3,
#         pos=1500.00,
#         od=100.00,
#         emi=700.00,
#         dpd=2,
#         last_repayment_paid_date="2024-03-01",
#         npa_date_as_fimo="",
#         old_new="Old",
#         alternate_mobile_number="9000000006",
#         phase="Phase 1",
#     ),
#     SpandanaDebtCollectionReport(
#         import_batch_id=None,
#         source_file_name="dummy_file4.csv",
#         borrower_code="BCODE004",
#         vendor_name="Vendor4",
#         connected_status="Missed",
#         recording_link=None,
#         duration_seconds=30,
#         disposition="Disposition4",
#         language="te",
#         zone="ZoneD",
#         svp_state="StateD",
#         region="RegionD",
#         area="AreaD",
#         cluster="ClusterD",
#         branch_code="BR004",
#         branch_name="Branch Four",
#         repayment_frequency="Bi-Weekly",
#         center_id="CEN004",
#         center_name="Center Four",
#         group_name="Group4",
#         village_name="Village4",
#         borrower_name="Borrower Four",
#         spouse_name="Spouse Four",
#         phone_number="9000000007",
#         no_of_loans=1,
#         pos=2500.00,
#         od=25.00,
#         emi=650.00,
#         dpd=0,
#         last_repayment_paid_date="2024-04-01",
#         npa_date_as_fimo="",
#         old_new="New",
#         alternate_mobile_number="9000000008",
#         phase="Phase 3",
#     ),
#     SpandanaDebtCollectionReport(
#         import_batch_id=None,
#         source_file_name="dummy_file5.csv",
#         borrower_code="BCODE005",
#         vendor_name="Vendor5",
#         connected_status="Connected",
#         recording_link=None,
#         duration_seconds=75,
#         disposition="Disposition5",
#         language="en",
#         zone="ZoneE",
#         svp_state="StateE",
#         region="RegionE",
#         area="AreaE",
#         cluster="ClusterE",
#         branch_code="BR005",
#         branch_name="Branch Five",
#         repayment_frequency="Monthly",
#         center_id="CEN005",
#         center_name="Center Five",
#         group_name="Group5",
#         village_name="Village5",
#         borrower_name="Borrower Five",
#         spouse_name="Spouse Five",
#         phone_number="9000000009",
#         no_of_loans=2,
#         pos=1700.00,
#         od=0.00,
#         emi=800.00,
#         dpd=3,
#         last_repayment_paid_date="2024-05-01",
#         npa_date_as_fimo="",
#         old_new="Old",
#         alternate_mobile_number="9000000010",
#         phase="Phase 2",
#     ),
# ]

# # Insert the dummy records in bulk using the synchronous SessionLocal (not FastAPI dependency)
# with SessionLocal() as session:
#     session.add_all(dummy_records)
#     session.commit()

In [22]:
with SessionLocal() as session:
    existing_report_data = session.query(SpandanaDebtCollectionReport).all()
    # for report in existing_report_data:
    #     print({
    #         "borrower_code": report.borrower_code,
    #         "borrower_name": report.borrower_name,
    #         "phone_number": report.phone_number,
    #         "disposition": report.disposition,
    #         "duration_seconds": report.duration_seconds,
    #         # Add any other fields you want to view here
    #     })

In [21]:
existing_report_data.__dict__

AttributeError: 'list' object has no attribute '__dict__'

In [22]:
from typing import Any

existing_report_data_list = []
for report in existing_report_data:
    # Print all attributes of the report object as a dictionary
    existing_report_data_list.append(report.__dict__)
existing_report_data_list

[{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca098c0>,
  'borrower_code': 'SSF4002279',
  'svp_state': 'Rajasthan',
  'center_name': 'khatoo kalan 719211',
  'pos': Decimal('2940.24'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Jodhpur',
  'group_name': '719211 Sanu And Marina Devi Gorup1',
  'od': Decimal('3001.00'),
  'connected_status': 'Connected',
  'area': 'Khatushyam',
  'village_name': 'Khatoo Kalan',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-OjPqDZ9jaGoi5SQXZz9.mp3',
  'cluster': 'Losal',
  'borrower_name': 'SHARDA DEVI',
  'dpd': 145,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 2,
  'branch_code': 'RJ3058',
  'spouse_name': 'KAILAS PURI',
  'last_repayment_paid_date': '17-Jun-25',
  'id': 1,
  'disposition': 'CONTACT ESTABLISHED_NO OUTCOME',
  'branch_name': 'Degana',
  'npa_date_as_fimo': '5-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '7737451883',
  'alternate_mobile_number': '7070037457, 9128235627',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '265706',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca099d0>,
  'borrower_code': 'SSF4009264',
  'svp_state': 'Chhattisgarh',
  'center_name': 'Ajagudh C3',
  'pos': Decimal('2940.24'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Ch-2',
  'group_name': 'Ajagudh C3 Pappi1',
  'od': Decimal('3001.00'),
  'connected_status': 'Connected',
  'area': 'Ambikapur',
  'village_name': 'Ajagudh',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-OgHlRIsqIoBL3Jo_xjr.mp3',
  'cluster': 'Renukoot',
  'borrower_name': 'DEVAKALI',
  'dpd': 145,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 21,
  'branch_code': 'UP2938',
  'spouse_name': 'RAY SINGH',
  'last_repayment_paid_date': '14-Jun-25',
  'id': 2,
  'disposition': 'MESSAGE DELIVERED_FOLLOW UP REQUIRED',
  'branch_name': 'Anpara',
  'npa_date_as_fimo': '5-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '6263481515',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'East',
  'center_id': '390727',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca09ae0>,
  'borrower_code': 'SSF3984941',
  'svp_state': 'Rajasthan',
  'center_name': '551433',
  'pos': Decimal('2940.24'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Chittorgarh',
  'group_name': '551433 Khajuri Mavaram1',
  'od': Decimal('3001.00'),
  'connected_status': 'Not Connected',
  'area': 'Salumbar',
  'village_name': 'Aarniya',
  'emi': Decimal('2240.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Sarada',
  'borrower_name': 'GAGALI MEENA',
  'dpd': 148,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 0,
  'branch_code': 'RJ3114',
  'spouse_name': 'SHANKAR',
  'last_repayment_paid_date': '12-Jun-25',
  'id': 3,
  'disposition': 'Not Connected',
  'branch_name': 'Lasadiya',
  'npa_date_as_fimo': '2-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '7232852188',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '273577',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca09bf0>,
  'borrower_code': 'SSF3988540',
  'svp_state': 'Chhattisgarh',
  'center_name': '411934',
  'pos': Decimal('2940.24'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Ch-2',
  'group_name': 'shiv',
  'od': Decimal('3001.00'),
  'connected_status': 'Connected',
  'area': 'Champa',
  'village_name': 'KIRIKMAL',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-Oj-T26ciETQxmbIO-4p.mp3',
  'cluster': 'Raigarh',
  'borrower_name': 'NILANDRI HATI',
  'dpd': 148,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 4,
  'branch_code': 'CHGL2136',
  'spouse_name': 'keshab hati',
  'last_repayment_paid_date': '24-Jun-25',
  'id': 4,
  'disposition': 'CONTACT ESTABLISHED_NO OUTCOME',
  'branch_name': 'Pussore',
  'npa_date_as_fimo': '2-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '7681805283',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'East',
  'center_id': '54411',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca09d00>,
  'borrower_code': 'SSF4006327',
  'svp_state': 'Rajasthan',
  'center_name': 'Lalas C1',
  'pos': Decimal('2940.24'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Jodhpur',
  'group_name': 'Lalas C1 G2',
  'od': Decimal('3001.00'),
  'connected_status': 'Connected',
  'area': 'Khatushyam',
  'village_name': 'Lalas',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-Oj-VHp1OVYdH_qPaiKm.mp3',
  'cluster': 'Didwana',
  'borrower_name': 'MAYA DEVI',
  'dpd': 145,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 39,
  'branch_code': 'RJ3254',
  'spouse_name': 'BAL RAM',
  'last_repayment_paid_date': '30-Jun-25',
  'id': 5,
  'disposition': 'WIP',
  'branch_name': 'Khatu Shyam',
  'npa_date_as_fimo': '5-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '9460050437',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '536206',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca09e10>,
  'borrower_code': 'SSF3983285',
  'svp_state': 'Chhattisgarh',
  'center_name': '464203',
  'pos': Decimal('2940.45'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Ch-2',
  'group_name': 'jaima',
  'od': Decimal('3001.00'),
  'connected_status': 'Not Connected',
  'area': 'Ambikapur',
  'village_name': 'Bangu bazar',
  'emi': Decimal('2130.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Ramanuj Ganj',
  'borrower_name': 'JAYANTI DEVI',
  'dpd': 147,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 0,
  'branch_code': 'CH2688',
  'spouse_name': 'KAMLESH KORWA',
  'last_repayment_paid_date': '13-Jun-25',
  'id': 6,
  'disposition': 'Not Connected',
  'branch_name': 'Ramanuj Ganj',
  'npa_date_as_fimo': '3-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '9361467621',
  'alternate_mobile_number': '7031894164',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'East',
  'center_id': '36588',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca09f20>,
  'borrower_code': 'SID951374966023',
  'svp_state': 'Chhattisgarh',
  'center_name': '291958',
  'pos': Decimal('2949.08'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Ch-2',
  'group_name': 'LAXMI',
  'od': Decimal('3043.00'),
  'connected_status': 'Not Connected',
  'area': 'Champa',
  'village_name': 'AMBETKARAVAS',
  'emi': Decimal('1470.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Raigarh',
  'borrower_name': 'PUSHPA SAHIS',
  'dpd': 149,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 0,
  'branch_code': 'CHGL0504',
  'spouse_name': 'NARESH KUMAR SAHIS',
  'last_repayment_paid_date': '14-Jun-25',
  'id': 7,
  'disposition': 'Not Connected',
  'branch_name': 'Raigarh',
  'npa_date_as_fimo': '1-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '9770185668',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'East',
  'center_id': '48512',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a030>,
  'borrower_code': 'SSF3925551',
  'svp_state': 'Rajasthan',
  'center_name': 'CHOKRI C1',
  'pos': Decimal('2962.00'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Chittorgarh',
  'group_name': 'sukna C1 G1',
  'od': Decimal('3023.00'),
  'connected_status': 'Connected',
  'area': 'Salumbar',
  'village_name': 'CHOKRI',
  'emi': Decimal('2150.00'),
  'recording_link': 'https://t1.finovateglobal.com/-Oj5iEb7TnH7AKUY0Ycc.mp3',
  'cluster': 'Peepalkhoont',
  'borrower_name': 'SUKNA',
  'dpd': 148,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 7,
  'branch_code': 'RJ2826',
  'spouse_name': 'RAJMAL',
  'last_repayment_paid_date': '19-Jun-25',
  'id': 8,
  'disposition': 'WIP',
  'branch_name': 'Ghatol',
  'npa_date_as_fimo': '2-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '7878513430',
  'alternate_mobile_number': '9934854811',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '545671',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a140>,
  'borrower_code': 'SSF3969183',
  'svp_state': 'Chhattisgarh',
  'center_name': '68',
  'pos': Decimal('2966.67'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Ch-1',
  'group_name': 'Taj',
  'od': Decimal('3028.00'),
  'connected_status': 'Connected',
  'area': 'Raipur',
  'village_name': 'Ashwani Nagar',
  'emi': Decimal('1970.00'),
  'recording_link': 'https://t1.finovateglobal.com/-OjPqfVeYcac6zeGy0w8.mp3',
  'cluster': 'Raipur',
  'borrower_name': 'TABASSUM BANO',
  'dpd': 145,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 18,
  'branch_code': 'CHGL0400',
  'spouse_name': 'MOHAMMED MOHSIN',
  'last_repayment_paid_date': '28-Jun-25',
  'id': 9,
  'disposition': 'WIP',
  'branch_name': 'Raipur-2',
  'npa_date_as_fimo': '5-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '8319171112',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'East',
  'center_id': '46574',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a250>,
  'borrower_code': 'SSF3984284',
  'svp_state': 'Rajasthan',
  'center_name': '555100',
  'pos': Decimal('2983.61'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Chittorgarh',
  'group_name': '1014831',
  'od': Decimal('3045.00'),
  'connected_status': 'Not Connected',
  'area': 'Sagwara',
  'village_name': 'Partapur',
  'emi': Decimal('2130.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Galiyakot',
  'borrower_name': 'MAMTA DAMOR',
  'dpd': 145,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 0,
  'branch_code': 'RJ3195',
  'spouse_name': 'AJAY KUMAR DAMOR',
  'last_repayment_paid_date': '6-Jun-25',
  'id': 10,
  'disposition': 'Not Connected',
  'branch_name': 'Galiyakot',
  'npa_date_as_fimo': '5-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '8000957949',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '207025',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a360>,
  'borrower_code': 'SSF4009891',
  'svp_state': 'Rajasthan',
  'center_name': '562266 C1',
  'pos': Decimal('2985.55'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Chittorgarh',
  'group_name': '562266 C1 Hejamal Se 4 kilo Mitar1',
  'od': Decimal('3047.00'),
  'connected_status': 'Connected',
  'area': 'Banswara',
  'village_name': 'Jhakoriya Natha',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-Oj-T437ff7te6iyLoC0.mp3',
  'cluster': 'Bagidora',
  'borrower_name': 'LALITA DEVI',
  'dpd': 144,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 7,
  'branch_code': 'RJ2846',
  'spouse_name': 'BENJI GARASIYA',
  'last_repayment_paid_date': '12-Jun-25',
  'id': 11,
  'disposition': 'CONNECTED_CUSTOMER NON RESPONSIVE',
  'branch_name': 'Bagidora',
  'npa_date_as_fimo': '6-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '7725940318',
  'alternate_mobile_number': '8809677062',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '417063',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a470>,
  'borrower_code': 'SSF4021482',
  'svp_state': 'Rajasthan',
  'center_name': 'KUJTI C1',
  'pos': Decimal('2985.55'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Jodhpur',
  'group_name': 'KUJTI C1 Sushila Devi1',
  'od': Decimal('3047.00'),
  'connected_status': 'Connected',
  'area': 'Khatushyam',
  'village_name': 'KUJTI',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-OggHFoqoItUe1pNKVz6.mp3',
  'cluster': 'Khajuwala',
  'borrower_name': 'SAVATRI DEVI',
  'dpd': 143,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 90,
  'branch_code': 'RJ3253',
  'spouse_name': 'RAMLAL',
  'last_repayment_paid_date': '23-Jun-25',
  'id': 12,
  'disposition': 'WRONG NUMBER',
  'branch_name': 'Lunkaransar',
  'npa_date_as_fimo': '7-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '9024801956',
  'alternate_mobile_number': '9777715427',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '323329',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a580>,
  'borrower_code': 'SSF4009930',
  'svp_state': 'Bihar-1',
  'center_name': 'Chiriya C8',
  'pos': Decimal('2985.55'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Muzaffarpur',
  'group_name': 'Chiriya C8 Chiraiya Santi Chauk1',
  'od': Decimal('3047.00'),
  'connected_status': 'Not Connected',
  'area': 'Sitamarhi',
  'village_name': 'Chiraia',
  'emi': Decimal('2240.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Dhaka',
  'borrower_name': 'RADHA DEVI',
  'dpd': 144,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 0,
  'branch_code': 'BH3349',
  'spouse_name': 'RUPLAL SAH',
  'last_repayment_paid_date': '25-Jun-25',
  'id': 13,
  'disposition': 'Not Connected',
  'branch_name': 'Chiraiya',
  'npa_date_as_fimo': '6-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '8294713226',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '412317',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a690>,
  'borrower_code': 'SSF3976280',
  'svp_state': 'Rajasthan',
  'center_name': 'UDASAR C7',
  'pos': Decimal('2985.55'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Jodhpur',
  'group_name': 'UDASAR C7 Manju Nayka 00071',
  'od': Decimal('3047.00'),
  'connected_status': 'Connected',
  'area': 'Khatushyam',
  'village_name': 'UDASAR',
  'emi': Decimal('2240.00'),
  'recording_link': 'https://t1.finovateglobal.com/-OjKpjpksbP1hjJS3n1o.mp3',
  'cluster': 'Losal',
  'borrower_name': 'SARALI',
  'dpd': 147,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),
  'duration_seconds': 25,
  'branch_code': 'RJ3252',
  'spouse_name': 'SHERA RAM NAYAK',
  'last_repayment_paid_date': '5-Jun-25',
  'id': 14,
  'disposition': 'WIP',
  'branch_name': 'Nokha',
  'npa_date_as_fimo': '3-Oct-25',
  'old_new': 'New POS',
  'source_file_name': 'SSFL__Debt Collection Report_27th Jan 2026.xlsx',
  'language': 'Hindi',
  'repayment_frequency': 'Monthly',
  'phone_number': '9351105389',
  'alternate_mobile_number': '',
  'imported_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 328000, tzinfo=datetime.timezone.utc),
  'zone': 'North',
  'center_id': '411289',
  'no_of_loans': 1,
  'phase': 'Phase 1'},
 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x11ca0a7a0>,
  'borrower_code': 'SSF2452889',
  'svp_state': 'Uttar Pradesh',
  'center_name': 'sonbarsa nonia patti C3',
  'pos': Decimal('2985.55'),
  'created_at': datetime.datetime(2026, 2, 2, 8, 35, 46, 453456, tzinfo=datetime.timezone.utc),
  'vendor_name': 'FGPL',
  'region': 'Gorakhpur',
  'group_name': 'sonbarsa nonia patti C3 jaitun1',
  'od': Decimal('3047.00'),
  'connected_status': 'Not Connected',
  'area': 'Deoria',
  'village_name': 'sonbarsa nonia patti',
  'emi': Decimal('2240.00'),
  'recording_link': 'Not Connected',
  'cluster': 'Pathardewa',
  'borrower_name': 'RUBINA',
  'dpd': 146,
  'import_batch_id': UUID('497695fa-61e5-454a-8f96-b9f9b0c8ee2d'),

In [ ]:
# Example: Update a record with respect to borrower_code

update_code = "SSF4002279"   # replace with your borrower_code
with SessionLocal() as session:
    report = session.query(SpandanaDebtCollectionReport).filter_by(borrower_code=update_code).first()
    if report:
        # Example update: change the disposition and commit
        report.disposition = "Updated Disposition"
        # update other fields as necessary
        session.commit()
        print(f"Record with borrower_code {update_code} updated successfully!")
    else:
        print(f"No record found for borrower_code {update_code}")

In [24]:
df = pd.read_csv("Untitled spreadsheet - Master Sheet.csv")
df_connected = df[df['Recording Link'] != 'Not Connected']
df_connected.head()

,BorrowerCode,Zone,Language,SVP State,Region,Area,Branch Code,BranchName,Repayment Frequency,CenterID,...,NPA_Date_as_fimo,AlterNateMobileNumber,Cluster,OLD /New,Phase,Vendor Name,Connected Status,Recording Link,Duration (in Seconds),Disposition (Best Accuracy)
0,SID951373615076,North,Hindi,Uttar Pradesh,Varanasi,Gopiganj,UPGL2114,Allahabad,Monthly,208254,...,43965,NaN,NaN,NaN,Phase 8,FGPL,Not Connected,na,na,na
1,SID951373688920,North,Hindi,Uttar Pradesh,Varanasi,Gopiganj,UP2815,Khaga,Monthly,257344,...,44199,NaN,NaN,NaN,Phase 8,FGPL,na,na,na,na
2,SID951373759985,West,Hindi,Madhya Pradesh-1,Itarsi,Pandhurna,MPGL2141,Pandhurna-2,Monthly,153184,...,2/2/21 0:00,NaN,NaN,NaN,Phase 8,FGPL,na,na,na,na
3,SID951373770509,West,Hindi,Madhya Pradesh-1,Indore,Indore,MP1207,Indore-4,Monthly,153738,...,2/2/21 0:00,NaN,NaN,NaN,Phase 8,FGPL,na,na,na,na
4,SID951373773568,West,Hindi,Madhya Pradesh-1,Itarsi,Itarsi,MPGL0576,Itarsi,Monthly,120050,...,1/4/22 0:00,NaN,NaN,NaN,Phase 8,FGPL,na,na,na,na

In [ ]:
df

In [74]:
import json
with open("campaign_data_feb_con-2.json", "r") as f:
    data_feb_con = json.load(f)

In [73]:
data_feb_con

[{'call_start_time': '2026-02-12T13:55:07.441879+05:30',
  'chat': [{'role': 'user',
    'content': 'The person you are trying to reach is not available. At the tone, please record your message. When you have finished recording, you may hang up.'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'}],
  'contact_to': '+919828454545',
  'direction': 'outbound',
  'duration': 25.62048840522766,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-OlFwxCy6zJxL_jHOOta.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-12T13:43:10.091262+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं लक्ष्मी बाई जी से बात कर रही हूँ?'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'}],
  'contact_to': '+918306185956',
  'direction': 'outbound',
  'duration': 19.474297523498535,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-OlFuC0obiY2AOw7YvAI.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T18:28:29.512550+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं थावरी बाई गरासिया जी से बात कर रही हूँ?'}],
  'contact_to': '+916367037412',
  'direction': 'outbound',
  'duration': 10.324589014053345,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol1Tm3UCmeHV9fk9ppt.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:22:19.716431+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं देवकाली जी से बात कर रही हूँ?'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'}],
  'contact_to': '+916263481515',
  'direction': 'outbound',
  'duration': 17.710072994232178,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-xD8F5GXv91SQqLS1.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T18:04:12.069843+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं मनीषा कुमारी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'जी जी बताइए.'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार पचास रुपये है वो अब दो सौ बयालीस दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि अब तीन हजार बावन हो चुकी है। क्या आप इस पर बात करना चाहेंगे?'},
   {'role': 'user',
    'content': 'देखिए हमें नहीं जाना है ही आपसे loan चाहिए, ना ही हमें जमा करना है क्योंकि आपको तो कई बार हम बता चुके हैं कि मेरी जो मेरे साथ जो किया है आपका staff आकर के यहां पर वह बदतमीज़ी जी का हमको बता दीजिए पहले कि जो बदतमीज़ी जी हमारे साथ किया आकर miss वह क्या बोलते हैं miss भी है जो किया मेरे साथ. पैसा हमको देना नहीं होता तो मैंने चौबीस किश्त में तेईस किश्त क्यों दे रखा था? नहीं देने के लिए? एक ही किश्त मांगने आया और इस तरह से क्यों pay उसका हुआ? कि बस अटक गया है. हम जान रहे हैं कहीं ना कहीं मेरी ही loss हो रही है. ना आपकी कुछ हो रही है ना उस बंदे की हो रही है. जिसने miss behave किया यहां पढ़ा करके. इसमें भी loss में हम ही हैं. लेकिन कोई नहीं अच्छी बात है. Loss में है तो है. मेरी तो यही तो बात ही नहीं करती. मेरी तो अगर आप समझती तो बार बार phone ही नहीं करती. अगर आपको मेरी इतनी ज़्यादा शुभ चिंता तक आप मेरी है तो आप जो staff जो यहां आकर जो किया था miss विहार मेरे साथ किया था मेरे साथ अथर्व का space आया था अहर language का इस्तेमाल किया था आप उससे ले लीजिए. उसको भी तो punish होना चाहिए ना आखिर पूरा का पूरा punish हमें क्यों मिलेगा? हम जमा नहीं करेंगे कि तो मेरा क्या loss हो रहा है वह मुझे मालूम है. लेकिन हमारा ही क्यों हम किसी का कुछ sun के खड़ी खेती अच्छा वाला sun के और मैं जहां करूं उसका भी तो कुछ loss होना चाहिए. वह आप लोग क्यों नहीं कर रहे हैं तो बताइए?'},
   {'role': 'assistant',
    'content': 'मैं आपकी स्थिति को समझ रही हूँ और आपकी चिंता को गंभीरता से ले रही हूँ। आपकी बातों से स्पष्ट है कि आपको पहले से ही कुछ समस्याओं का सामना करना पड़ा है। \n\nआपकी शिकायत को ध्यान में रखते हुए, मैं आपको सुझाव दूँगी कि आप अपनी नज़दीकी स्पंदना स्फूर्ति ब्रांच में जाकर अपनी समस्या को स्पष्ट रूप से बताएं। वहाँ पर आपको उचित सहायता मिलेगी और आपकी शिकायत पर कार्रवाई की जाएगी। \n\nकृपया ध्यान रखे'},
   {'role': 'user',
    'content': 'नहीं नहीं नहीं. नहीं नहीं नहीं. वह हम गए थे वैसा कुछ नहीं होता है. आप लोग सभी लोग मिले रखते हैं. आप लोग as a staff को अगर कुछ punish दिए जाते हैं ना तो हमको खुशी शायद मिलता कि जाने दीजिए. मेरे साथ जो कुछ भी हुआ चाहे उसने किया उसको punish मिला लेकिन नहीं. आप लोग सब लोग मिले जुड़े रहते हैं. कोई punish नहीं. किया तो उसको आप लोग भी website करोगे ना कि अच्छा किया. आप लोग as a staff उसको miss किए हो और किसी भी employee के साथ तो कुछ अमृता से face आता है तो आप लोग तो कुछ सहायता करोगे ना उसको? नहीं तो same time जैसे मैं complaint लेकर गई थी ना office में same time उसको नौकरी चले जाएंगे दिया दे दिया होता. और दिलवा दिया होता है. जिनको सुने तब ना. मेरे staff के साथ में कोई आवाज़ देता है आप पूरा पेश आता है तो आपके पास कोई कानूनी कार्यवाही है ना चाहिए कि हां उसको same time distribute किया जाए. उसको उसके जोड़ से. Job की ज़रूरत उसको है ना? तो उसको अपने employee से कैसे बात करना है? अपने customer से कैसे बात करना है? उसको पता'},
   {'role': 'assistant',
    'content': 'मैं आपकी भावनाओं को समझ रही हूँ और यह स्पष्ट है कि आपने बहुत कठिनाई का सामना किया है। आपकी शिकायत और अनुभव महत्वपूर्ण हैं, और मैं आपको आश्वस्त करना चाहती हूँ कि आपकी बातों को गंभीरता से लिया जाएगा।\n\nआपकी स्थिति को बेहतर ढंग से समझने और समाधान निकालने के लिए, मैं आपको सुझाव दूँगी कि आप अपनी नज़दीकी स्पंदना स्फूर्ति ब्रांच में जाकर अपनी शिकायत दर्ज करें। वहाँ पर आपको उचित सहायता मिलेगी और आपकी समस्या का समाधान'}],
  'contact_to': '+917549327052',
  'direction': 'outbound',
  'duration': 240.1078758239746,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Oks531G09FaEYWuCfvf.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:14:09.726269+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं पुष्पा खराडी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'नहीं.'},
   {'role': 'assistant',
    'content': 'ठीक है, असुविधा के लिए माफ़ कीजिए। मैं कॉल अभी समाप्त कर रही हूँ।'}],
  'contact_to': '+918690755610',
  'direction': 'outbound',
  'duration': 19.27433443069458,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-vLh_1vT2qB5SqnW2.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T18:18:47.186575+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं राजुडी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'नहीं sir वह तो घर से'},
   {'role': 'assistant',
    'content': 'ठीक है, असुविधा के लिए माफ़ कीजिए। मैं कॉल अभी समाप्त कर रही हूँ।'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'},
   {'role': 'user', 'content': 'हां. बोलिए. बोलो.'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार पचास रुपये है वो अब दो सौ ग्'},
   {'role': 'user', 'content': 'हां.'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार पचास रुपये है वो अब दो सौ ग्यारह दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि'},
   {'role': 'user', 'content': 'कितनी कितनी है?'},
   {'role': 'assistant',
    'content': 'आपकी दो हजार पचास रुपये की ईएमआई दो सौ ग्यारह दिन से बकाया है और अब कुल बकाया राशि तीन हजार चौहत्तर रुपये हो चुकी है। हम चाहते हैं कि इस स्थिति को आपके लिए थोड़ा आसान बनाया जा सके। क्या हम एक या दो ईएमआई के भुगतान से शुरू कर सकते हैं?'},
   {'role': 'user', 'content': 'एक किश्त तो बाकी है?'},
   {'role': 'assistant',
    'content': 'क्या आप यह कहना चाह रहे हैं कि आपकी एक किश्त बाकी है? अगर ऐस'},
   {'role': 'user', 'content': 'हां हां यही पुछ तू.'},
   {'role': 'assistant', 'content': 'जी, समझ गई। क्या आप बता सकते हैं कि आ'},
   {'role': 'user', 'content': 'कितने बजे से है?'},
   {'role': 'assistant',
    'content': 'आपकी ईएमआई दो सौ ग्यारह दिन से बकाया है। क्या आप इसका जल्दी ही भुगतान कर पाएँगे?'},
   {'role': 'user',
    'content': 'वह इस तरह से यह तो मेरा loan ही नहीं उठाया हुआ है madam.'},
   {'role': 'assistant',
    'content': 'समझ गई लेकिन हमारे रिकॉर्ड में आपके नाम पर स्पंदना स्फूर्ति फाइनेंस का लोन दिख रहा है, गाँव मेर्टा रोड से। क्या यह जानकारी'},
   {'role': 'user', 'content': 'कौन सा कौन सा वापस बताऊं?'},
   {'role': 'assistant',
    'content': 'जी, हमारे रिकॉर्ड के अनुसार यह लोन राजुडी जी के नाम पर है और गाँव मेर्टा रोड से संबंधित है। क्या यह जानकारी आपस'},
   {'role': 'user',
    'content': 'अच्छा नहीं नहीं मैं यह पुछ रहा हूं फिर. कि कौन सी कौन सी क्या नाम है इसका?'},
   {'role': 'assistant',
    'content': 'जी, हमारे रिकॉर्ड के अनुसार यह लोन राजुडी जी के नाम पर है। क्या आप यह जानक'},
   {'role': 'user',
    'content': 'नहीं नहीं वह तो वह तो ठीक है कौन सा बंदे ने बताया आपको आपने?'},
   {'role': 'assistant',
    'content': 'जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। क्या आप यह जानना चाह रहे हैं'},
   {'role': 'user', 'content': 'अच्छा.'},
   {'role': 'assistant',
    'content': 'अगर आपके पास और कोई सवाल है या आप कुछ और जानना चाहते हैं, तो कृपया बताएं। मैं आपकी मदद करने के लिए यहाँ हूँ।'},
   {'role': 'user', 'content': 'नहीं नहीं नहीं कुछ नहीं download करता.'},
   {'role': 'assistant',
    'content': 'ठीक है, अगर आपको कुछ और जानकारी चाहिए या कोई और सवाल हो, तो कृपया बताएं। मैं आपकी मदद करने के लिए यहाँ'},
   {'role': 'user', 'content': 'नहीं और कुछ नहीं चाहिए madam.'},
   {'role': 'assistant', 'content': 'ठीक है, धन्यवाद! अगर भविष्य में आपको'},
   {'role': 'user', 'content': 'ठीक.'},
   {'role': 'assistant',
    'content': 'क्या मैं आपकी और किसी चीज़ में मदद कर सकती हूँ? अगर नहीं, तो'},
   {'role': 'user', 'content': 'ठीक है.'},
   {'role': 'assistant', 'content': 'हमें अपना'},
   {'role': 'user', 'content': 'Sir. ठीक है sir.'},
   {'role': 'assistant',
    'content': 'हमें अपना समय देने के लिए धन्यवाद',
    'tool_calls': [{'id': 'call_SPVo5tKafYIngerutsP1Q2zA',
      'type': 'function',
      'function': {'name': 'end_conversation', 'arguments': '{}'}}]},
   {'name': 'end_conversation',
    'role': 'tool',
    'content': 'conversation ended',
    'tool_call_id': 'call_SPVo5tKafYIngerutsP1Q2zA'}],
  'contact_to': '+917023046835',
  'direction': 'outbound',
  'duration': 191.0719666481018,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Oks8MJC1xCP3dakoudV.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:20:08.848667+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं ममता देवी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'Hello.'},
   {'role': 'assistant',
    'content': 'जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। क्या आप ममता देवी जी हैं?'},
   {'role': 'user', 'content': 'हां जी.'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार दो सौ सोलह रुपये है वो अब दो सौ छह दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि अब तीन हजार एक सौ छियासी हो चुकी है।?'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही है?'}],
  'contact_to': '+917320830429',
  'direction': 'outbound',
  'duration': 43.13992476463318,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-wjqH3pHzrEklBIdT.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:14:33.529484+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं माला देवी जी से बात कर रही हूँ?'}],
  'contact_to': '+919523192755',
  'direction': 'outbound',
  'duration': 9.821599245071411,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-vTIKoLF6yZjzfd9G.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:11:27.044937+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयश'},
   {'role': 'user',
    'content': 'Hello, मैं इस वंदनाा छोड़कर से ऐश. क्या बात है?'},
   {'role': 'assistant', 'content': 'जी, मैं स्पंदना स्फूर्ति फाइने'},
   {'role': 'user',
    'content': 'मैं इस पंद्रह minute क्या बात है तो बोलिए ना तो.'},
   {'role': 'assistant', 'content': 'जी, मैं स्पंदना स्फूर्ति'},
   {'role': 'user', 'content': 'जी, दस पंद्रह'}],
  'contact_to': '+917256843389',
  'direction': 'outbound',
  'duration': 20.539059162139893,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-ujh4Lni3QGB49IO-.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T18:12:58.236159+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं घिसी देवी जी से बात कर रही हूँ?'},
   {'role': 'user',
    'content': 'हां जी से debit है और कल बाकी से वह आ कर रहा है आपका या करूंगा?'},
   {'role': 'assistant', 'content': 'जी, मेरी आवाज़ आ रही ह'},
   {'role': 'user',
    'content': 'हां तो रही है लेकिन मैं बता रही हूं आपको किसी देवी नहीं है यहां पर वह मेरा number दे दिया है अपना account number'},
   {'role': 'assistant',
    'content': 'ठीक है, असुविधा के लिए माफ़ कीजिए। मैं कॉल अभी समाप्त'},
   {'role': 'user', 'content': 'बोलिए.'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार दो सौ पचास रुपये है वो अब दो'},
   {'role': 'user',
    'content': 'अरे भाई मैं घिसी रही हूं phone की ना यह परेशान करा है बिना फ़ालतू तो पाएंगे. मना तो दिए हुए मैं तो बहुत मैं तो बोलूं बुझी हूं.'},
   {'role': 'assistant', 'content': 'ठीक है, क्या आप बता स'},
   {'role': 'user',
    'content': 'यह सीधे account में आकर देखो ना कौन बमूटा है कौन का finger आ रहा है क्या बात है बाहर में आप परेशान कर रहे हो लेकिन समझ में नहीं आ रही है. यह तो भोर ही सकते हैं ना नारायण, भोरी सकते नारायण बोल रही हूं. आपने कितनी बार भी बोल दिया लेकिन तो आप तो समझ में नहीं आ रही है मैंने बोला नहीं हमारे यहां किसी दे दी वह मेरे पड़ोस में रहती है लेकिन मेरा number आपने दे दिया वह मैंने तो loan दिया नहीं.'},
   {'role': 'assistant',
    'content': 'समझ गई, लेकिन हमारे रिकॉर्ड में आपके नाम पर स्पंदना स्फूर्ति फाइनेंस का लोन दिख रहा है। क्या आप ब'},
   {'role': 'user',
    'content': 'अरे दिया तो है वह तो ले रखी है लेकिन वह खुद आप phone के number तो बंद कर दिया है. ठीक है ना? वह हमारा number आपको दे दिया वह सब में उसको बहुत सारी बोलते हूं गाली देती हूं समझ में नहीं आ रही है उनको तो.'},
   {'role': 'assistant',
    'content': 'ठीक है, हम नोट कर लेते हैं कि यह लोन आपके नाम का नहीं है। कृपया इस स्पष्टता के'},
   {'role': 'user', 'content': 'हां, मेरा नाम का नहीं है.'},
   {'role': 'assistant', 'content': 'ठीक है, कृपया अपनी नज़दीकी स्प'},
   {'role': 'user', 'content': 'हां. ठीक.'},
   {'role': 'assistant',
    'content': 'ठीक है, मैं कॉल यहीं समाप्त कर रही हूँ। अगर आपको और कोई सहायता चाहिए हो, तो'},
   {'role': 'user', 'content': 'हां.'},
   {'role': 'assistant',
    'content': 'हमें अपना समय दे देने के लिए धन्यवाद',
    'tool_calls': [{'id': 'call_woecgKg25QAsooNwgnBI1VZt',
      'type': 'function',
      'function': {'name': 'end_conversation', 'arguments': '{}'}}]},
   {'name': 'end_conversation',
    'role': 'tool',
    'content': 'conversation ended',
    'tool_call_id': 'call_woecgKg25QAsooNwgnBI1VZt'}],
  'contact_to': '+918290552045',
  'direction': 'outbound',
  'duration': 137.2252278327942,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Oks70jLO--sM2uyFxn0.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T15:03:38.102771+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं सुनीता देवी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'जी'},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो तीन हजार पांच सौ रुपये है वो अब तीन सौ तिरसठ दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल बकाया राशि अब तीन हजार पांच सौ हो चुकी है?'},
   {'role': 'user', 'content': 'बात कर रहे हैं वही नहीं है.'},
   {'role': 'assistant',
    'content': 'ठीक है, असुविधा के लिए माफ़ कीजिए। मैं कॉल अभी समाप्त कर रही हूँ।'}],
  'contact_to': '+919931543473',
  'direction': 'outbound',
  'duration': 38.874149560928345,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-OkrRcX9A6MKv0lnf_8H.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T15:08:30.044221+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं कौशल्या बाई यादव जी से बात कर रही हूँ?'}],
  'contact_to': '+919399017257',
  'direction': 'outbound',
  'duration': 8.697995662689209,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-OkrSoWbltx3wB9j_pXT.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-07T18:22:28.975551+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं समीना जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'Hello.'},
   {'role': 'assistant', 'content': 'जी, मैं स्पंद'},
   {'role': 'user', 'content': 'Hello'},
   {'role': 'assistant',
    'content': 'जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। क्या मैं समीना जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'बंदे ना company.'},
   {'role': 'assistant', 'content': 'जी, मेरी आव'},
   {'role': 'user', 'content': 'अच्छा अच्छा.'}],
  'contact_to': '+918505019515',
  'direction': 'outbound',
  'duration': 34.93865418434143,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Oks9C3xAF-4ngvxgqZy.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:20:55.101269+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं शशिकला जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'Hello.'},
   {'role': 'assistant',
    'content': 'जी, मैं स्पंदना स्फूर्ति फाइनेंस से बात कर रही हूँ। क्या मैं शशिकला जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': 'नहीं.'},
   {'role': 'assistant',
    'content': 'ठीक है, असुविधा के लिए माफ़ कीजिए। मैं कॉल अभी समाप्त कर रही हूँ।'}],
  'contact_to': '+918817355946',
  'direction': 'outbound',
  'duration': 28.373260021209717,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-wqyELCiQWkhb1_1D.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:24:03.518816+05:30',
  'chat': [],
  'contact_to': '+919835654586',
  'direction': 'outbound',
  'duration': 0.1330552101135254,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-xbkeHAppqKg4QjbF.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:11:25.368940+05:30',
  'chat': [{'role': 'assistant',
    'content': 'हेलो मैं स्पंदना स्फूर्ति से आयशा बात कर रही हूँ। क्या मैं लक्ष्मी जी से बात कर रही हूँ?'},
   {'role': 'user', 'content': "हां जी? हां हां जी. हां जी ma'am."},
   {'role': 'assistant',
    'content': 'जी, आपके लोन की EMI जो दो हजार छह सौ सत्तरी रुपये है वो अब दो सौ दस दिन से बकाया है। हम जानना चाहते हैं कि क्या आप इसका जल्दी ही भुगतान कर पाएँगे, क्योंकि कुल ब'}],
  'contact_to': '+916261758475',
  'direction': 'outbound',
  'duration': 27.583762884140015,
  'recording': 'https://millis-ai-recordings.s3.us-west-1.amazonaws.com/XqGjHMbb5kUh7SfsRelENfzNj753/-Ol-uiyOS9xO_2LKtr4C.mp3',
  'campaign_id': 221},
 {'call_start_time': '2026-02-09T11:23:08.563937+05:30',
  'chat': [],
  'contact_to': '+918824105261',
  'direction': 'outbound',
  'duration': 3.321505308151245,

In [71]:
data_feb_con

,call_start_time,chat,contact_to,direction,duration,recording,campaign_id
0,2026-02-12 13:55:07.441879+05:30,"[{'role': 'user', 'content': 'The person you a...",919828454545,outbound,25.620488,https://millis-ai-recordings.s3.us-west-1.amaz...,221
1,2026-02-12 13:43:10.091262+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",918306185956,outbound,19.474298,https://millis-ai-recordings.s3.us-west-1.amaz...,221
2,2026-02-09 18:28:29.512550+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",916367037412,outbound,10.324589,https://millis-ai-recordings.s3.us-west-1.amaz...,221
3,2026-02-09 11:22:19.716431+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",916263481515,outbound,17.710073,https://millis-ai-recordings.s3.us-west-1.amaz...,221
4,2026-02-07 18:04:12.069843+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917549327052,outbound,240.107876,https://millis-ai-recordings.s3.us-west-1.amaz...,221
...,...,...,...,...,...,...,...
5235,2026-02-07 13:54:24.722199+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919721312310,outbound,11.650485,https://millis-ai-recordings.s3.us-west-1.amaz...,221
5236,2026-02-07 13:54:21.377198+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919262952399,outbound,26.746710,https://millis-ai-recordings.s3.us-west-1.amaz...,221
5237,2026-02-07 13:47:02.504466+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919109701355,outbound,512.312168,https://millis-ai-recordings.s3.us-west-1.amaz...,221
5238,2026-02-07 13:55:44.306821+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917633938141,outbound,44.070786,https://millis-ai-recordings.s3.us-west-1.amaz...,221
5239,2026-02-07 13:55:48.039659+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917999486707,outbound,46.649226,https://millis-ai-recordings.s3.us-west-1.amaz...,221

In [3]:
import pandas as pd

In [4]:
df_feb_con = pd.read_json("campaign_data_feb_con-2.json")

In [8]:
df_feb_con['meta_data'][0]['Uid']

'SSF3732341'

In [10]:
df_feb_con['uid'] = df_feb_con['meta_data'].apply(lambda x: x['Uid'])

In [15]:
'https://t1.finovateglobal.com/'+df_feb_con['recording'][0].split('/')[4]

'https://t1.finovateglobal.com/-OlFwxCy6zJxL_jHOOta.mp3'

In [16]:
df_feb_con['Recording Link'] = df_feb_con['recording'].apply(lambda x: 'https://t1.finovateglobal.com/'+x.split('/')[4])

In [17]:
df_feb_con

,call_start_time,chat,contact_to,direction,duration,recording,meta_data,campaign_id,uid,Recording Link
0,2026-02-12 13:55:07.441879+05:30,"[{'role': 'user', 'content': 'The person you a...",919828454545,outbound,25.620488,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF3732341', 'Name': 'आशा सेन', 'camp...",221,SSF3732341,https://t1.finovateglobal.com/-OlFwxCy6zJxL_jH...
1,2026-02-12 13:43:10.091262+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",918306185956,outbound,19.474298,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF3888830', 'Name': 'लक्ष्मी बाई', '...",221,SSF3888830,https://t1.finovateglobal.com/-OlFuC0obiY2AOw7...
2,2026-02-09 18:28:29.512550+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",916367037412,outbound,10.324589,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF3598802', 'Name': 'थावरी बाई गरासि...",221,SSF3598802,https://t1.finovateglobal.com/-Ol1Tm3UCmeHV9fk...
3,2026-02-09 11:22:19.716431+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",916263481515,outbound,17.710073,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF4009264', 'Name': 'देवकाली', 'camp...",221,SSF4009264,https://t1.finovateglobal.com/-Ol-xD8F5GXv91SQ...
4,2026-02-07 18:04:12.069843+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917549327052,outbound,240.107876,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF3858350', 'Name': 'मनीषा कुमारी', ...",221,SSF3858350,https://t1.finovateglobal.com/-Oks531G09FaEYWu...
...,...,...,...,...,...,...,...,...,...,...
5235,2026-02-07 13:54:24.722199+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919721312310,outbound,11.650485,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SID951375029248', 'Name': 'कमलेश्या द...",221,SID951375029248,https://t1.finovateglobal.com/-OkrBq2tKr2PfhJR...
5236,2026-02-07 13:54:21.377198+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919262952399,outbound,26.746710,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SID951375471561', 'Name': 'प्रभावती द...",221,SID951375471561,https://t1.finovateglobal.com/-OkrBmDxdREJUrfF...
5237,2026-02-07 13:47:02.504466+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",919109701355,outbound,512.312168,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'CID077811671', 'Name': 'लक्ष्मी', 'ca...",221,CID077811671,https://t1.finovateglobal.com/-OkrA6qnJsl1Aods...
5238,2026-02-07 13:55:44.306821+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917633938141,outbound,44.070786,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SID951375537489', 'Name': 'भारती देवी...",221,SID951375537489,https://t1.finovateglobal.com/-OkrC5H8WYm5zNMy...
5239,2026-02-07 13:55:48.039659+05:30,"[{'role': 'assistant', 'content': 'हेलो मैं स्...",917999486707,outbound,46.649226,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SID951373281096', 'Name': 'गीता यादव'...",221,SID951373281096,https://t1.finovateglobal.com/-OkrC9EPdZqaNHJP...

In [25]:
import numbers

def ensure_py_types(val):
    """
    Converts numpy numeric types to built-in Python types.
    Returns None for NaN values.
    """
    if pd.isna(val):
        return None
    # Convert numpy.integer/float to built-in types
    if isinstance(val, numbers.Integral):
        return int(val)
    if isinstance(val, numbers.Real):
        return float(val)
    return val

def get_float(val):
    """Attempts to coerce to float, returns None if not possible (empty, strange text, etc.)."""
    try:
        # Will be nan if not convertible, caught by ensure_py_types
        return ensure_py_types(pd.to_numeric(val, errors='coerce'))
    except Exception:
        return None

def get_int(val):
    """Attempts to coerce to int, returns None if not possible (empty, strange text, etc.)."""
    try:
        result = pd.to_numeric(val, errors='coerce')
        return int(result) if not pd.isna(result) else None
    except Exception:
        return None

def safe_str(val):
    if pd.isna(val):
        return None
    value = str(val).strip()
    if value.lower() in ('nan', 'none', ''):
        return None
    return value

# For all strictly numeric fields, ensure only proper numbers (no accidental text!); 
# for all text fields, always treat as string or None.
with SessionLocal() as session:
    records = []
    for _, row in df.iterrows():
        try:
            # Numeric fields - ensure only int or float or None
            duration_seconds = get_float(row['Duration (in Seconds)'])
            center_id = get_int(row['CenterID'])
            no_of_loans = get_int(row['NOof_Loans'])
            pos = get_float(row['POS'])
            od = get_float(row['OD '])
            emi = get_float(row['EMI'])
            dpd = get_int(row['DPD'])

            record = SpandanaDebtCollectionReport(
                source_file_name='SSFL__Debt Collection Report_27th Jan 2026.xlsx',
                borrower_code=safe_str(row['BorrowerCode']),
                vendor_name='FGPL',
                connected_status=safe_str(row['Connected Status']),
                recording_link=safe_str(row['Recording Link']),
                duration_seconds=duration_seconds,
                disposition=safe_str(row['Disposition (Best Accuracy)']),
                language=safe_str(row['Language']),
                zone=safe_str(row['Zone']),
                svp_state=safe_str(row['SVP State']),
                region=safe_str(row['Region']),
                area=safe_str(row['Area']),
                cluster=safe_str(row['Cluster']),
                branch_code=safe_str(row['Branch Code']),
                branch_name=safe_str(row['BranchName']),
                repayment_frequency=safe_str(row['Repayment Frequency']),
                center_id=center_id,
                center_name=safe_str(row['CenterName']),
                group_name=safe_str(row['GroupName']),
                village_name=safe_str(row['Village Name']),
                borrower_name=safe_str(row['BorrowerName']),
                spouse_name=safe_str(row['Spouse Name']),
                phone_number=safe_str(row['Phone Numeber']),
                no_of_loans=no_of_loans,
                pos=pos,
                od=od,
                emi=emi,
                dpd=dpd,
                last_repayment_paid_date=safe_str(row['Last Repayment Paid Date']),
                npa_date_as_fimo=safe_str(row['NPA_Date_as_fimo']),
                old_new=safe_str(row['OLD /New']),
                alternate_mobile_number=safe_str(row['AlterNateMobileNumber']),
                phase=safe_str(row['Phase'])
            )
            records.append(record)
        except Exception as e:
            # Log bad row and skip
            print(f"Skipping row {_} due to error: {e}")
            continue
    session.add_all(records)
    session.commit()

In [28]:
df_feb_con.head(1)

,call_start_time,chat,contact_to,direction,duration,recording,meta_data,campaign_id,uid,Recording Link
0,2026-02-12 13:55:07.441879+05:30,"[{'role': 'user', 'content': 'The person you a...",919828454545,outbound,25.620488,https://millis-ai-recordings.s3.us-west-1.amaz...,"{'Uid': 'SSF3732341', 'Name': 'आशा सेन', 'camp...",221,SSF3732341,https://t1.finovateglobal.com/-OlFwxCy6zJxL_jH...

In [36]:
ls = []
for i in existing_report_data:
    ls.append(i.borrower_code)

DetachedInstanceError: Instance <SpandanaDebtCollectionReport at 0x1185fc410> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)

In [38]:
with SessionLocal() as session:
    existing_report_data = session.query(SpandanaDebtCollectionReport).all()
    for report in existing_report_data:
        
        uid = report.borrower_code
        u_data = df_feb_con[df_feb_con['uid'] == uid]
        if len(u_data) > 0:
            source_file_name = 'SSFL__Debt Collection Report_27th Jan 2026.xlsx'
            report.vendor_name = 'FGPL'
            report.connected_status = "Connected"
            report.recording_link = u_data['Recording Link'].values[0]
            report.duration_seconds = int(u_data['duration'].values[0])
            report.disposition = "WIP"
        
    session.commit()

In [ ]:
SSF4978901

In [34]:
import pandas as pd

df_report = pd.DataFrame(existing_report_data_list)
df_report

,_sa_instance_state,borrower_code,svp_state,center_name,pos,created_at,vendor_name,region,group_name,od,...,source_file_name,language,repayment_frequency,phone_number,alternate_mobile_number,imported_at,zone,center_id,no_of_loans,phase
0,<sqlalchemy.orm.state.InstanceState object at ...,SSF3984941,Rajasthan,551433,2940.24,2026-02-02 08:35:46.453456+00:00,FGPL,Chittorgarh,551433 Khajuri Mavaram1,3001.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,7232852188,,2026-02-02 08:35:46.328000+00:00,North,273577,1,Phase 1
1,<sqlalchemy.orm.state.InstanceState object at ...,SSF3983285,Chhattisgarh,464203,2940.45,2026-02-02 08:35:46.453456+00:00,FGPL,Ch-2,jaima,3001.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,9361467621,7031894164,2026-02-02 08:35:46.328000+00:00,East,36588,1,Phase 1
2,<sqlalchemy.orm.state.InstanceState object at ...,SID951374966023,Chhattisgarh,291958,2949.08,2026-02-02 08:35:46.453456+00:00,FGPL,Ch-2,LAXMI,3043.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,9770185668,,2026-02-02 08:35:46.328000+00:00,East,48512,1,Phase 1
3,<sqlalchemy.orm.state.InstanceState object at ...,SSF3984284,Rajasthan,555100,2983.61,2026-02-02 08:35:46.453456+00:00,FGPL,Chittorgarh,1014831,3045.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,8000957949,,2026-02-02 08:35:46.328000+00:00,North,207025,1,Phase 1
4,<sqlalchemy.orm.state.InstanceState object at ...,SSF4009930,Bihar-1,Chiriya C8,2985.55,2026-02-02 08:35:46.453456+00:00,FGPL,Muzaffarpur,Chiriya C8 Chiraiya Santi Chauk1,3047.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,8294713226,,2026-02-02 08:35:46.328000+00:00,North,412317,1,Phase 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16692,<sqlalchemy.orm.state.InstanceState object at ...,SID951374500951,Bihar-1,534681,81582.10,2026-02-02 08:35:46.453456+00:00,FGPL,Muzaffarpur,1050302,39843.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,7482941838,"9328352037, 7294184131",2026-02-02 08:35:46.328000+00:00,North,27864,2,Phase 1
16693,<sqlalchemy.orm.state.InstanceState object at ...,SSF3214290,Uttar Pradesh,CHANDRAUTA C8,85178.29,2026-02-02 08:35:46.453456+00:00,FGPL,Gorakhpur,CHANDRAUTA C8 Hashanah Tara Nesha Iachhia FAZI...,47310.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,8948078274,,2026-02-02 08:35:46.328000+00:00,North,374209,2,Phase 1
16694,<sqlalchemy.orm.state.InstanceState object at ...,CID219406458,Chhattisgarh,270,91219.25,2026-02-02 08:35:46.453456+00:00,FGPL,Ch-1,JAY,104264.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,9201362865,9286979046,2026-02-02 08:35:46.328000+00:00,East,56547,2,Phase 3
16695,<sqlalchemy.orm.state.InstanceState object at ...,SSF5183182,Chhattisgarh,62365,96261.42,2026-02-02 08:35:46.453456+00:00,FGPL,Ch-2,120643,60150.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,9201065435,9279088462,2026-02-02 08:35:46.328000+00:00,East,52836,3,Phase 1
16696,<sqlalchemy.orm.state.InstanceState object at ...,SSF3910084,Bihar-2,697969 C1,3302.66,2026-02-02 08:35:46.453456+00:00,FGPL,Patna,697969 C1 Kalin 21,3371.00,...,SSFL__Debt Collection Report_27th Jan 2026.xlsx,Hindi,Monthly,9572544276,7842293423,2026-02-02 08:35:46.328000+00:00,North,320162,1,Phase 1

In [1]:
import pandas as pd
df = pd.read_json("campaign_data_feb_19.json")

In [8]:
print(df['recording'])

0       https://millis-ai-recordings.s3.us-west-1.amaz...
1       https://millis-ai-recordings.s3.us-west-1.amaz...
2       https://millis-ai-recordings.s3.us-west-1.amaz...
3       https://millis-ai-recordings.s3.us-west-1.amaz...
4       https://millis-ai-recordings.s3.us-west-1.amaz...
                              ...
7050    https://millis-ai-recordings.s3.us-west-1.amaz...
7051    https://millis-ai-recordings.s3.us-west-1.amaz...
7052    https://millis-ai-recordings.s3.us-west-1.amaz...
7053    https://millis-ai-recordings.s3.us-west-1.amaz...
7054    https://millis-ai-recordings.s3.us-west-1.amaz...
Name: recording, Length: 7055, dtype: str

In [11]:
df[['recording']].to_csv("19_feb.csv", index=False)

In [ ]:
import json

# Custom JSON loader for possibly malformed lines
def safe_json_load(line):
    try:
        return json.loads(line)
    except Exception as e:
        print(f"Could not parse line (starts with {line[:30]}...): {e}")
        return None

data = []
filename = "/Users/apple/Downloads/campaign_data-4.json"
with open(filename, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        item = safe_json_load(line)
        if item is None:
            continue
        # If 'meta_data' is a string, decode it when possible
        if 'meta_data' in item and isinstance(item['meta_data'], str):
            try:
                item['meta_data'] = json.loads(item['meta_data'])
            except Exception:
                # If nested 'meta_data' string is not valid JSON, just leave it
                pass
        data.append(item)

# Print a few examples of meta_data (to check unicode decoding)
for i, item in enumerate(data[:5]):
    print(item.get('meta_data'))

# Example of accessing the 'Name' key
for item in data[:5]:
    meta = item.get('meta_data', {})
    name = meta.get("Name") if isinstance(meta, dict) else None
    print("Name:", name)

Could not parse line (starts with [...): Expecting value: line 1 column 2 (char 1)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919111449346",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919238530768",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF2...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+918521654783",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919179629739",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919302918869",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919238332105",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919131398686",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919302878377",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919304629975",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF2...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919343697762",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919369631687",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919098222365",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919507168518",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919630404946",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF2...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919507017428",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919369950247",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919752384591",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919648908113",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916205448253",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919341464289",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916202312619",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919616776098",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916263363878",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919798852073",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919927803181",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919935647781",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919301612869",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919771036921",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919993648534",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919887249040",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916299998361",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916388293495",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917015918429",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+918530730997",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+916396192875",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917061810324",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917091284748",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF5...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917078183531",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917250754664",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF2...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917070026230",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917223096694",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SID9...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+919905159119",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917426854878",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917470685432",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF4...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917388939979",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917761802634",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF6...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Could not parse line (starts with "contact_to": "+917667075184",...): Extra data: line 1 column 13 (char 12)
Could not parse line (starts with "meta_data": "{\"Uid\": \"SSF3...): Extra data: line 1 column 12 (char 11)
Could not parse line (starts with },...): Expecting value: line 1 column 1 (char 0)
Could not parse line (starts with {...): Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [4]:
data

[{'contact_to': '+919111449346',
  'meta_data': '{"Uid": "SID951373518230", "Name": "\\u0915\\u092e\\u0932\\u093e \\u092c\\u093e\\u0908 \\u0917\\u092e\\u093e\\u0926", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u093e\\u0924", "token_applicable": "TRUE", "villageNameWords": "\\u0930\\u093e\\u091c\\u0917\\u0922\\u093c", "overdueAmountWords": "\\u0906\\u0920 \\u0939\\u091c\\u093e\\u0930 \\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u0924\\u0940\\u0928"}'},
 {'contact_to': '+919238530768',
  'meta_data': '{"Uid": "SSF2633075", "Name": "\\u0905\\u0902\\u0917\\u0942\\u0930\\u0940 \\u092c\\u093e\\u0908", "campaign_id": "243", "EMI_In_Words": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0926\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0948\\u0902\\u0924\\u0940\\u0938", "token_applicable": "TRUE", "villageNameWords": "\\u092a\\u094d\\u0930\\u0938\\u093e\\u0908 \\u092e\\u093e\\u0932\\u0917\\u0941\\u091c\\u093e\\u0930\\u0940", "overdueAmountWords": "\\u0924\\u0947\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u091b\\u0939 \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940"}'},
 {'contact_to': '+918521654783',
  'meta_data': '{"Uid": "SSF5427863", "Name": "\\u0938\\u094b\\u0928\\u0940 \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0928\\u094c \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092c\\u0939\\u0924\\u094d\\u0924\\u0930", "token_applicable": "TRUE", "villageNameWords": "\\u091f\\u094b\\u0932\\u093e \\u0930\\u093e\\u091c\\u0932\\u093e \\u0915\\u0932\\u093e\\u0902", "overdueAmountWords": "\\u092a\\u091a\\u094d\\u091a\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0928 \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u0930"}'},
 {'contact_to': '+919179629739',
  'meta_data': '{"Uid": "SID951373836380", "Name": "\\u0938\\u0941\\u092e\\u093f\\u0924\\u093e \\u092c\\u093e\\u0908", "campaign_id": "243", "EMI_In_Words": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u092a\\u091a\\u093e\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u093e\\u0924", "token_applicable": "TRUE", "villageNameWords": "\\u0926\\u0947\\u0939\\u0902\\u0926\\u0940", "overdueAmountWords": "\\u091b\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0928\\u094c \\u0938\\u094c \\u092a\\u091a\\u094d\\u091a\\u0940\\u0938"}'},
 {'contact_to': '+919302918869',
  'meta_data': '{"Uid": "SID951375139505", "Name": "\\u0938\\u0941\\u0927\\u0948\\u0928 \\u092c\\u093e\\u0908", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u090f\\u0915 \\u0938\\u094c \\u0926\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u093e\\u0924", "token_applicable": "TRUE", "villageNameWords": "\\u0928\\u0928\\u094d\\u0939\\u0947\\u0938\\u0930", "overdueAmountWords": "\\u091a\\u094c\\u0926\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u0930"}'},
 {'contact_to': '+919238332105',
  'meta_data': '{"Uid": "SSF6004854", "Name": "\\u091c\\u0940\\u0930\\u093e \\u092c\\u093e\\u0908 \\u0926\\u0941\\u0927\\u092c\\u0941\\u0930\\u0947", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091a\\u093e\\u0932\\u0940\\u0938", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u094b", "token_applicable": "TRUE", "villageNameWords": "\\u0917\\u0902\\u0917\\u093e \\u0928\\u0917\\u0930", "overdueAmountWords": "\\u092c\\u093e\\u0908\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u091a\\u093e\\u0930 \\u0938\\u094c"}'},
 {'contact_to': '+919131398686',
  'meta_data': '{"Uid": "SSF3393921", "Name": "\\u0932\\u093e\\u0907\\u0915\\u093e \\u092e\\u0927\\u0941\\u092e\\u0915\\u094d\\u0916\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0924\\u0940\\u0928 \\u0939\\u091c\\u093e\\u0930 \\u091a\\u093e\\u0930 \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u0930", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u093e\\u0924", "token_applicable": "TRUE", "villageNameWords": "\\u0917\\u0948\\u0930\\u0924\\u0917\\u0902\\u091c", "overdueAmountWords": "\\u091a\\u094c\\u092c\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u0928\\u092c\\u094d\\u092c\\u0947"}'},
 {'contact_to': '+919302878377',
  'meta_data': '{"Uid": "SID951374146990", "Name": "\\u092d\\u0941\\u0935\\u093e\\u0928\\u0940 \\u0928\\u093e\\u0917\\u0947\\u0936", "campaign_id": "243", "EMI_In_Words": "\\u091a\\u093e\\u0930 \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u0930", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u094b", "token_applicable": "TRUE", "villageNameWords": "\\u0938\\u093f\\u0928\\u093e\\u092a\\u093e\\u0932\\u0940", "overdueAmountWords": "\\u092c\\u092f\\u093e\\u0932\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c"}'},
 {'contact_to': '+919304629975',
  'meta_data': '{"Uid": "SSF2919081", "Name": "\\u092a\\u0948\\u0928 \\u091a\\u094c\\u0930\\u0947", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0909\\u0928\\u0924\\u093e\\u0932\\u0940\\u0938", "token_applicable": "TRUE", "villageNameWords": "\\u092c\\u091f\\u0948\\u0932", "overdueAmountWords": "\\u0924\\u0947\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0906\\u0920 \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0908\\u0938"}'},
 {'contact_to': '+919343697762',
  'meta_data': '{"Uid": "SSF5374050", "Name": "\\u092e\\u092e\\u0924\\u093e \\u0906\\u0926\\u093f\\u0935\\u093e\\u0938\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0926\\u0938", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u094b", "token_applicable": "TRUE", "villageNameWords": "\\u0916\\u0947\\u0921\\u093c\\u093e", "overdueAmountWords": "\\u0938\\u0924\\u094d\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0907\\u0915\\u094d\\u0915\\u0940\\u0938"}'},
 {'contact_to': '+919369631687',
  'meta_data': '{"Uid": "SSF3798216", "Name": "\\u0932\\u093f\\u0932\\u093e\\u0935\\u0924\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0924\\u0940\\u0928 \\u0939\\u091c\\u093e\\u0930 \\u091a\\u093e\\u0930 \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u0930", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u094b", "token_applicable": "TRUE", "villageNameWords": "\\u0930\\u0947\\u0928\\u0941\\u0915\\u0942\\u091f", "overdueAmountWords": "\\u091a\\u094c\\u0902\\u0924\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c"}'},
 {'contact_to': '+919098222365',
  'meta_data': '{"Uid": "SSF3757950", "Name": "\\u092d\\u0942\\u0930\\u0940\\u092c\\u093e\\u0908 \\u0928\\u093e\\u092f\\u0915", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "TRUE", "villageNameWords": "\\u091a\\u092a\\u0932\\u093e\\u0928\\u093e", "overdueAmountWords": "\\u0938\\u0924\\u094d\\u0924\\u093e\\u0908\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0906\\u0920 \\u0938\\u094c"}'},
 {'contact_to': '+919507168518',
  'meta_data': '{"Uid": "SSF5257561", "Name": "\\u0938\\u094b\\u0928\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092c\\u0924\\u094d\\u0924\\u0940\\u094d\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u0924\\u094d\\u0930\\u093f\\u092c\\u0947\\u0928\\u0940", "overdueAmountWords": "\\u0924\\u0947\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091b\\u092a\\u094d\\u092a\\u0928"}'},
 {'contact_to': '+919630404946',
  'meta_data': '{"Uid": "SSF2896502", "Name": "\\u0928\\u0940\\u0932\\u0942 \\u092a\\u093e\\u092f\\u0915", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "TRUE", "villageNameWords": "\\u092e\\u093f\\u0921\\u0915\\u0940", "overdueAmountWords": "\\u0938\\u094b\\u0932\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u092a\\u091a\\u0939\\u0924\\u094d\\u0924\\u0930"}'},
 {'contact_to': '+919507017428',
  'meta_data': '{"Uid": "SSF4460565", "Name": "\\u0938\\u0902\\u091c\\u0942 \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0924\\u0940\\u0928 \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0928 \\u0938\\u094c \\u092a\\u091a\\u093e\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "TRUE", "villageNameWords": "\\u0930\\u093e\\u0927\\u093e\\u0928\\u0917\\u0930", "overdueAmountWords": "\\u0924\\u0948\\u0902\\u0924\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u092a\\u093e\\u0902\\u091a \\u0938\\u094c"}'},
 {'contact_to': '+919369950247',
  'meta_data': '{"Uid": "SSF5717897", "Name": "\\u0939\\u0947\\u092e\\u0932\\u0924\\u093e", "campaign_id": "243", "EMI_In_Words": "\\u0938\\u093e\\u0924 \\u0938\\u094c \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092a\\u0948\\u0902\\u0924\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u0938\\u0947\\u092e\\u093e\\u0930\\u0940", "overdueAmountWords": "\\u0924\\u0940\\u0928 \\u0939\\u091c\\u093e\\u0930 \\u0928\\u094c \\u0938\\u094c \\u092c\\u092f\\u093e\\u0938\\u0940"}'},
 {'contact_to': '+919752384591',
  'meta_data': '{"Uid": "SSF4241793", "Name": "\\u0935\\u093f\\u0928\\u0940\\u0924\\u093e", "campaign_id": "243", "EMI_In_Words": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u091b\\u0939 \\u0938\\u094c \\u092a\\u091a\\u093e\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "TRUE", "villageNameWords": "\\u0915\\u0941\\u0938\\u0932\\u0940", "overdueAmountWords": "\\u0938\\u094b\\u0932\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u092a\\u093e\\u0902\\u091a \\u0938\\u094c"}'},
 {'contact_to': '+919648908113',
  'meta_data': '{"Uid": "SSF5364901", "Name": "\\u0928\\u0940\\u0932\\u092e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u091b\\u0924\\u094d\\u0924\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u092d\\u093e\\u0930\\u0917\\u0935\\u0928 \\u092c\\u0938\\u094d\\u0924\\u0940", "overdueAmountWords": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u090f\\u0915 \\u0938\\u094c \\u0924\\u093f\\u0930\\u0947\\u092a\\u0928"}'},
 {'contact_to': '+916205448253',
  'meta_data': '{"Uid": "SSF6375473", "Name": "\\u0932\\u0915\\u094d\\u0937\\u094d\\u092e\\u0940\\u0928\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0905\\u0921\\u093c\\u0924\\u093e\\u0932\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u0915\\u0947\\u0930\\u092a\\u093e", "overdueAmountWords": "\\u0905\\u0920\\u093e\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u092c\\u0940\\u0938"}'},
 {'contact_to': '+919341464289',
  'meta_data': '{"Uid": "SSF5742282", "Name": "\\u0928\\u091c\\u092e\\u093e \\u0916\\u093e\\u0924\\u0942\\u0928", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u0938\\u093e\\u0920", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092a\\u0948\\u0902\\u0924\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u0905\\u0935\\u093e\\u092a\\u0941\\u0930 \\u0909\\u0930\\u094d\\u092b \\u0936\\u0947\\u0930\\u092a\\u0941\\u0930", "overdueAmountWords": "\\u0909\\u0928\\u094d\\u0928\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u091a\\u093e\\u0932\\u0940\\u0938"}'},
 {'contact_to': '+916202312619',
  'meta_data': '{"Uid": "SSF4730195", "Name": "\\u0928\\u093f\\u0930\\u094d\\u092e\\u0932\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091a\\u093e\\u0932\\u0940\\u0938", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0924\\u0940\\u0928", "token_applicable": "TRUE", "villageNameWords": "\\u0926\\u0941\\u0930\\u092e\\u093e\\u091f\\u094d\\u091f\\u093e", "overdueAmountWords": "\\u0938\\u094b\\u0932\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u091a\\u094c\\u0902\\u0924\\u0940\\u0938"}'},
 {'contact_to': '+919616776098',
  'meta_data': '{"Uid": "SSF5875751", "Name": "\\u092a\\u094d\\u0930\\u093f\\u092f\\u0902\\u0915\\u093e \\u092e\\u094c\\u0930\\u094d\\u092f\\u093e", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u0938\\u093e\\u0920", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0905\\u091f\\u094d\\u0920\\u093e\\u0928\\u0935\\u0947", "token_applicable": "FALSE", "villageNameWords": "\\u0938\\u0948\\u092f\\u0926 \\u0935 \\u0930\\u093e", "overdueAmountWords": "\\u091a\\u094c\\u092c\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0905\\u0938\\u094d\\u0938\\u0940"}'},
 {'contact_to': '+916263363878',
  'meta_data': '{"Uid": "SSF3000454", "Name": "\\u0909\\u0937\\u093e \\u092c\\u093e\\u0908", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0905\\u0938\\u094d\\u0938\\u0940", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u090f\\u0915", "token_applicable": "TRUE", "villageNameWords": "\\u092c\\u093e\\u092c\\u093e \\u0924\\u094b\\u0932\\u093e", "overdueAmountWords": "\\u0938\\u0924\\u094d\\u0924\\u093e\\u0908\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0906\\u0920 \\u0938\\u094c"}'},
 {'contact_to': '+919798852073',
  'meta_data': '{"Uid": "SSF6248605", "Name": "\\u092a\\u0941\\u0928\\u093f\\u0924\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0938\\u093e\\u0924 \\u0938\\u094c \\u092c\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092a\\u0948\\u0902\\u0924\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u0930\\u093e\\u0928\\u0940\\u092a\\u0924\\u094d\\u0924\\u0940", "overdueAmountWords": "\\u091a\\u094c\\u0926\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0938\\u093e\\u0924 \\u0938\\u094c \\u0905\\u0921\\u093c\\u0924\\u0940\\u0938"}'},
 {'contact_to': '+919927803181',
  'meta_data': '{"Uid": "SSF5269506", "Name": "\\u0928\\u093e\\u091c\\u093c\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u090f\\u0915 \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "FALSE", "villageNameWords": "\\u0939\\u0930\\u093f\\u0928\\u0917\\u0930", "overdueAmountWords": "\\u092c\\u0924\\u094d\\u0924\\u0940\\u094d\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091a\\u094c\\u0930\\u093e\\u0928\\u0935\\u0947"}'},
 {'contact_to': '+919935647781',
  'meta_data': '{"Uid": "SSF4898369", "Name": "\\u0936\\u092c\\u093e\\u0928\\u093e \\u092c\\u0947\\u0917\\u092e", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u090f\\u0915 \\u0938\\u094c \\u0924\\u0940\\u0938", "dpdDaysWords": "\\u0924\\u0940\\u0928 \\u0938\\u094c \\u0926\\u094b", "token_applicable": "TRUE", "villageNameWords": "\\u0926\\u093e\\u0926\\u093f\\u092f\\u093e\\u092a\\u0941\\u0930\\u093e \\u091d\\u093e\\u0902\\u0938\\u0940", "overdueAmountWords": "\\u0938\\u0924\\u094d\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0906\\u0920 \\u0938\\u094c \\u0938\\u0948\\u0902\\u0924\\u0940\\u0938"}'},
 {'contact_to': '+919301612869',
  'meta_data': '{"Uid": "SSF3998293", "Name": "\\u092c\\u093e\\u0930\\u093e\\u092a\\u0940 \\u0915\\u0941\\u0936\\u0935\\u093e\\u0939", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091a\\u093e\\u0932\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u091a\\u093e\\u0932\\u0940\\u0938", "token_applicable": "TRUE", "villageNameWords": "\\u091c\\u094b\\u0930\\u093e \\u0936\\u0939\\u0930", "overdueAmountWords": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u0909\\u0928\\u0924\\u093e\\u0932\\u0940\\u0938"}'},
 {'contact_to': '+919771036921',
  'meta_data': '{"Uid": "SID951375485124", "Name": "\\u0917\\u0941\\u0921\\u093c\\u093f\\u092f\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0924\\u0940\\u0928 \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "TRUE", "villageNameWords": "\\u0917\\u093e\\u0935\\u093e \\u091a\\u0915", "overdueAmountWords": "\\u0924\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0928 \\u0938\\u094c"}'},
 {'contact_to': '+919993648534',
  'meta_data': '{"Uid": "SSF6121215", "Name": "\\u0938\\u093f\\u0902\\u0915\\u0942 \\u0915\\u0941\\u092e\\u093e\\u0930\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u092a\\u093e\\u0902\\u091a \\u0938\\u094c \\u0938\\u093e\\u0920", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0938\\u0924\\u094d\\u0924\\u093e\\u0928\\u0935\\u0947", "token_applicable": "FALSE", "villageNameWords": "\\u091a\\u093e\\u0902\\u0926\\u092a\\u0941\\u0930 \\u0927\\u093e\\u092e\\u094c\\u0928", "overdueAmountWords": "\\u091a\\u094c\\u092c\\u0940\\u0938 \\u0939\\u091c\\u093e\\u0930 \\u0905\\u0938\\u094d\\u0938\\u0940"}'},
 {'contact_to': '+919887249040',
  'meta_data': '{"Uid": "SSF5726598", "Name": "\\u092e\\u0928\\u0940\\u0937\\u093e \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0924\\u0940\\u0928 \\u0938\\u094c", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u092a\\u0948\\u0902\\u0924\\u0940\\u0938", "token_applicable": "FALSE", "villageNameWords": "\\u092d\\u0942\\u0935\\u093e\\u0915\\u093e", "overdueAmountWords": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0924\\u0940\\u0928 \\u0938\\u094c \\u0924\\u093f\\u0939\\u0924\\u094d\\u0924\\u0930"}'},
 {'contact_to': '+916299998361',
  'meta_data': '{"Uid": "SSF6642202", "Name": "\\u0932\\u0915\\u094d\\u0937\\u094d\\u092e\\u0940 \\u0926\\u0947\\u0935\\u0940", "campaign_id": "243", "EMI_In_Words": "\\u0926\\u094b \\u0939\\u091c\\u093e\\u0930 \\u0926\\u094b \\u0938\\u094c \\u091a\\u093e\\u0932\\u0940\\u0938", "dpdDaysWords": "\\u0926\\u094b \\u0938\\u094c \\u0907\\u0915\\u0924\\u093e\\u0932\\u0940\\u0938", "token_applicable": "TRUE", "villageNameWords": "\\u0915\\u0930\\u094d\\u092e\\u0924\\u093e\\u0930", "overdueAmountWords": "\\u0938\\u0924\\u094d\\u0930\\u0939 \\u0939\\u091c\\u093e\\u0930 \\u0928\\u094c \\u0938\\u094c \\u092c\\u0940\\u0938"}'},
 {'contact_to': '+916388293495',

In [ ]:
import pandas as pd

df = pd.read_csv("/Users/apple/Downloads/campaign_data-4.json")